Repository forem/forem, pull requests merged in 2019-06, with the labels that each got.

#3018 Fix close modal click action
  app/javascript/listings/listings.jsx
Labels: PR: unreviewed

#3021 [Theme] Fixes inappropriate comment header background color bug #3020
  app/assets/stylesheets/comments.scss
Labels: PR: reviewed-approved

#3019 User website URL should be https
  app/views/users/_profile.html.erb
Labels: PR: reviewed-approved

#3027 Adjust listing modal view spacing and hide scroll bar
  app/assets/stylesheets/classified_listings.scss
Labels: listings

#3022 Fix flaky editor spec & change dev configs
  .simplecov
  .travis.yml
  Gemfile
  Gemfile.lock
  spec/rails_helper.rb
  spec/system/articles/user_edits_an_article_spec.rb
  spec/system/articles/user_visits_an_article_spec.rb
Labels: PR: reviewed-approved

#3038 Fix 404 issue when submitting abuse report
  config/routes.rb
  spec/requests/feedback_messages_create_spec.rb
Labels: PR: reviewed-approved

#3041 Finalize multi-org features
  app/assets/stylesheets/dashboard.scss
  app/controllers/credits_controller.rb
  app/javascript/article-form/articleForm.jsx
  app/javascript/listings/listingForm.jsx
  app/views/articles/_v2_form.html.erb
  app/views/classified_listings/_form.html.erb
  app/views/credits/index.html.erb
  app/views/dashboards/_actions.html.erb
  app/views/dashboards/pro.html.erb
  app/views/dashboards/show.html.erb
Labels: PR: unreviewed

#3040 fix(chat): remove an extra at sign
  app/javascript/chat/chat.jsx
Labels: PR: reviewed-approved

#3039 Added specs for the PodcastFeed #2952
  app/labor/podcast_feed.rb
  spec/labor/podcast_feed_spec.rb
Labels: PR: reviewed-approved

#3043 Add Vulnerability disclosure to README
  README.md
Labels: PR: reviewed-approved

#3044 Cache bust banished users' posts after the posts are deleted
  app/services/moderator/manage_activity_and_roles.rb
Labels: PR: reviewed-approved

#3048 Format issue label in CONTRIBUTING.md [skip ci]
  CONTRIBUTING.md
Labels: PR: reviewed-approved

#3045 Remove switch organizations tab from settings and clear Rails cache for PUT /admin/organizations
  app/controllers/admin/organizations_controller.rb
  app/models/user.rb
  app/views/users/_switch_organizations.html.erb
Labels: PR: reviewed-approved

#3054 Remove unused lib
  app/assets/javascripts/lib/js-yaml.js
  config/initializers/assets.rb
Labels: PR: unreviewed

#3059 Added rubocop-rails
  .codeclimate.yml
  .rubocop.yml
  Gemfile
  Gemfile.lock
  app/controllers/api/v0/reactions_controller.rb
  app/controllers/application_controller.rb
  app/controllers/chat_channel_memberships_controller.rb
  app/controllers/chat_channels_controller.rb
  app/controllers/comments_controller.rb
  app/controllers/image_uploads_controller.rb
  app/controllers/messages_controller.rb
  app/controllers/push_notification_subscriptions_controller.rb
  app/controllers/social_previews_controller.rb
  app/controllers/stripe_cancellations_controller.rb
  app/controllers/twilio_tokens_controller.rb
  app/controllers/video_states_controller.rb
Labels: PR: reviewed-approved

#3057 Moved Podcast#pull_all_episodes to a separate ActiveJob #2952 #2497
  app/jobs/podcasts/get_episodes_job.rb
  app/labor/podcast_feed.rb
  app/models/podcast.rb
  lib/tasks/fetch.rake
  spec/jobs/podcasts/get_episodes_job_spec.rb
Labels: PR: reviewed-approved

#3053 Fix listings cache/indexing and add bumping feature to internal
  app/controllers/classified_listings_controller.rb
  app/controllers/concerns/classified_listings_toolkit.rb
  app/controllers/internal/classified_listings_controller.rb
  app/views/internal/classified_listings/edit.html.erb
  app/views/social_previews/listing.html.erb
Labels: PR: reviewed-approved

#3065 Clear Rails cache for destroyed comment's ancestors and destroy buffer_updates for articles
  app/models/article.rb
  app/models/comment.rb
Labels: PR: reviewed-approved

#3064 Fix improper archive redirect
  app/assets/javascripts/initializers/initializeEllipsisMenu.js
  app/controllers/articles_controller.rb
  spec/requests/articles_update_spec.rb
Labels: PR: unreviewed

#3068 Add linuxrocks.online to Mastodon whitelist
  app/lib/constants.rb
Labels: PR: reviewed-approved

#3066 Adds bug bounty and security info to contact page
  app/views/pages/contact.html.erb
Labels: PR: reviewed-approved

#3067 Adds bug bounty link
  app/assets/javascripts/hello-dev.js
Labels: PR: reviewed-approved

#3074 Add badges to key tags
  app/assets/stylesheets/user-profile-header.scss
  app/controllers/admin/tags_controller.rb
  app/controllers/internal/tags_controller.rb
  app/labor/badge_rewarder.rb
  app/models/badge.rb
  app/models/tag.rb
  app/views/articles/tag_index.html.erb
  app/views/internal/tags/index.html.erb
  app/views/internal/tags/show.html.erb
  db/migrate/20190606202826_add_badge_id_to_tags.rb
  db/schema.rb
  spec/labor/badge_rewarder_spec.rb
  spec/models/tag_spec.rb
Labels: PR: unreviewed

#3063 Add a space between "Change meta tag" and canonical_url
  app/javascript/article-form/elements/moreConfig.jsx
Labels: PR: reviewed-approved

#3075 Disable Podcast episodes fetching during seeding
  db/seeds.rb
Labels: PR: reviewed-approved

#3072 Analytics: refactoring for speed improvements
  app/controllers/api/v0/analytics_controller.rb
  app/controllers/api/v0/api_controller.rb
  app/services/analytics_service.rb
  db/migrate/20190607110030_add_indexes_for_analytics.rb
  db/schema.rb
  spec/requests/api/v0/analytics_spec.rb
  spec/requests/pages_spec.rb
  spec/services/analytics/analytics_service_spec.rb
  spec/services/analytics_service_spec.rb
Labels: PR: reviewed-approved

#3087 Fix js-breaking webcomponent
  app/assets/javascripts/base.js.erb
  app/assets/javascripts/initializers/initializeCommentDropdown.js
  app/assets/javascripts/lib/webcomponents-loader.js
  app/javascript/packs/clipboardCopy.js
  app/views/articles/show.html.erb
  package.json
  yarn.lock
Labels: PR: reviewed-approved

#3113 Fix inconsistent spec
  spec/services/analytics_service_spec.rb
  spec/system/articles/user_edits_an_article_spec.rb
Labels: PR: unreviewed

#3119 docs: add DEV API link in the account settings UI
  app/views/users/_account.html.erb
Labels: PR: reviewed-approved

#3115 Make `AdditionalContentBoxesController#randomize` private
  app/controllers/additional_content_boxes_controller.rb
Labels: PR: reviewed-approved

#3116 Refactor array creation
  app/controllers/api/v0/articles_controller.rb
  app/models/credit.rb
Labels: PR: reviewed-approved

#3117 Refactor `Timeframer#datetime` to use a hash instead of a conditional
  app/labor/timeframer.rb
Labels: PR: reviewed-approved

#3089 Fix reading list filters input's color in night theme
  app/assets/stylesheets/readinglist.scss
Labels: PR: reviewed-approved, reading-list

#3131 Fix access token revoking
  app/controllers/api_secrets_controller.rb
  app/views/users/_account.html.erb
  config/routes.rb
  spec/requests/api_secrets_destroy_spec.rb
Labels: PR: reviewed-approved

#3125 Destroy organization memberships if user is destroyed
  app/models/user.rb
  spec/models/user_spec.rb
Labels: PR: reviewed-approved

#3128 "Contact via Connect" checked by default
  app/views/classified_listings/_form.html.erb
Labels: PR: reviewed-approved, listings

#3110 Bug/Action Buttons Fix
  app/assets/stylesheets/article-show.scss
Labels: PR: reviewed-approved

#3139 Moved SlackBot.delay.ping calls to ActiveJob #3136
  app/jobs/slack_bot_ping_job.rb
  app/observers/application_observer.rb
  app/observers/article_observer.rb
  app/observers/organization_observer.rb
  app/observers/reaction_observer.rb
  app/services/rss_reader.rb
  spec/jobs/slack_bot_ping_job_spec.rb
  spec/observers/article_observer_spec.rb
Labels: PR: reviewed-approved

#3102 Dashboard Pro: support InstantClick and show org analytics
  app/controllers/dashboards_controller.rb
  app/javascript/analytics/dashboard.js
  app/javascript/packs/analyticsDashboard.js
  app/javascript/packs/proCharts.js
  app/views/dashboards/pro.html.erb
Labels: PR: reviewed-approved

#3144 Extracts compound conditional to a private method
  app/models/tag_adjustment.rb
Labels: PR: reviewed-approved

#3143 Fix visibility of unread channel name
  app/assets/stylesheets/chat.scss
Labels: PR: reviewed-approved

#3055 Implement ActiveJob for Mention
  app/jobs/mentions/create_all_job.rb
  app/jobs/mentions/send_email_notification_job.rb
  app/models/mention.rb
  app/services/mentions/create_all.rb
  spec/jobs/mentions/create_all_job_spec.rb
  spec/jobs/mentions/send_email_notification_job_spec.rb
  spec/models/mention_spec.rb
  spec/services/mentions/create_all_spec.rb
Labels: PR: reviewed-approved

#3146 Remove dead code
  app/labor/user_states.rb
  spec/models/user_spec.rb
Labels: PR: reviewed-approved

#3142 Update Service Worker and Favicon
  app/assets/javascripts/serviceworker.js.erb
  public/favicon.ico
Labels: PR: reviewed-approved

#3098 Removed fetching podcasts from a callback
  app/controllers/admin/podcasts_controller.rb
  app/models/podcast.rb
  db/seeds.rb
  spec/factories/podcasts.rb
  spec/requests/admin/podcasts_spec.rb
Labels: PR: reviewed-approved

#3123 Podcasts validations
  app/models/podcast.rb
  app/models/podcast_episode.rb
  db/migrate/20190611102309_add_constraints_to_podcasts.rb
  db/migrate/20190611102923_add_unique_indexes_to_podcasts.rb
  db/migrate/20190612095748_add_constraints_to_podcast_episodes.rb
  db/migrate/20190612095959_add_unique_indexes_to_podcast_episodes.rb
  db/schema.rb
  spec/models/podcast_episode_spec.rb
  spec/models/podcast_spec.rb
Labels: PR: reviewed-approved

#3150 Fix broken spec
  spec/requests/admin/podcasts_spec.rb
Labels: PR: reviewed-approved

#3012 Change notifications unique indexes #2525
  .vscode/settings.json
  app/services/notifications/reactions/send.rb
  db/migrate/20190531085252_remove_notifications_unique_index.rb
  db/migrate/20190531094609_add_unique_user_id_notifications_index.rb
  db/migrate/20190531094926_add_unique_organization_id_notifications_index.rb
  db/schema.rb
  spec/models/notification_spec.rb
  spec/services/notifications/remove_all_spec.rb
Labels: PR: reviewed-approved

#3148 Validate usernames and organization slugs against podcast slugs
  app/models/organization.rb
  app/models/user.rb
  spec/models/organization_spec.rb
  spec/models/user_spec.rb
Labels: PR: reviewed-approved

#3120 Pro Analytics: stats for a single article
  app/assets/javascripts/initializers/initializeBaseUserData.js
  app/assets/javascripts/utilities/userData.js
  app/controllers/articles_controller.rb
  app/controllers/async_info_controller.rb
  app/javascript/analytics/dashboard.js
  app/javascript/packs/analyticsArticle.js
  app/models/user.rb
  app/policies/article_policy.rb
  app/services/analytics_service.rb
  app/views/articles/stats.html.erb
  config/routes.rb
  spec/models/user_spec.rb
  spec/requests/articles_spec.rb
  spec/system/articles/user_visits_article_stats.rb
Labels: PR: reviewed-approved

#3155 Added organization_id index to notifications
  db/migrate/20190614093041_add_notifications_organization_id_index.rb
  db/schema.rb
Labels: PR: reviewed-approved

#3158 Remove org notifications count from notifications view
  app/controllers/notifications_controller.rb
  app/views/notifications/index.html.erb
Labels: PR: reviewed-approved

#3149 New Feature: Subscribe to posts!
  app/assets/javascripts/initializers/initializeEllipsisMenu.js
  app/assets/stylesheets/article-show.scss
  app/controllers/article_mutes_controller.rb
  app/controllers/comment_mutes_controller.rb
  app/controllers/comments_controller.rb
  app/controllers/notification_subscriptions_controller.rb
  app/javascript/packs/notificationSubscriptionHandler.js
  app/models/article.rb
  app/models/comment.rb
  app/models/notification_subscription.rb
  app/models/user.rb
  app/services/article_creation_service.rb
  app/services/notifications/new_comment/send.rb
  app/views/articles/_actions.html.erb
  app/views/comments/settings.html.erb
  app/views/dashboards/_dashboard_article.html.erb
  config/initializers/reserved_words.rb
  config/routes.rb
  db/migrate/20190611144112_create_notification_subscriptions.rb
  db/schema.rb
  spec/factories/articles.rb
  spec/factories/notification_subscriptions.rb
  spec/models/article_spec.rb
  spec/models/comment_spec.rb
  spec/models/notification_spec.rb
  spec/models/notification_subscription_spec.rb
  spec/models/user_spec.rb
  spec/requests/article_mutes_spec.rb
  spec/requests/comment_mutes_spec.rb
  spec/requests/notification_subscriptions_spec.rb
  spec/requests/notifications_spec.rb
  spec/services/notifications/new_comment/send_spec.rb
  spec/system/articles/user_visits_an_article_spec.rb
Labels: PR: reviewed-approved

#3159 Fix analytics grouped by day with nil page views average
  app/services/analytics_service.rb
  spec/services/analytics_service_spec.rb
Labels: PR: reviewed-approved

#3161 Remove old Dashboard Pro code
  app/controllers/dashboards_controller.rb
  app/facades/dashboard/pro.rb
  app/views/dashboards/pro.html.erb
Labels: PR: reviewed-approved

#3084 Setting default reading time of 1 minute for articles within liquid tags
  app/views/articles/_liquid.html.erb
  spec/fixtures/files/article_long_content.txt
  spec/liquid_tags/link_tag_spec.rb
Labels: PR: reviewed-approved

#3160 Performance: save some queries when pluck is not needed
  app/controllers/internal/feedback_messages_controller.rb
  app/controllers/moderations_controller.rb
  app/controllers/pages_controller.rb
  app/services/mentions/create_all.rb
Labels: PR: reviewed-approved

#3157 Fix icons size in Safari reader mode
  app/assets/stylesheets/article-show.scss
Labels: PR: reviewed-approved

#3164 Finalize UI for all types of notification settings
  app/assets/stylesheets/article-show.scss
  app/controllers/notification_subscriptions_controller.rb
  app/javascript/packs/notificationSubscriptionHandler.js
  app/models/notification_subscription.rb
  app/services/notifications/new_comment/send.rb
  app/views/articles/_actions.html.erb
  app/views/comments/settings.html.erb
  app/views/dashboards/_dashboard_article.html.erb
  spec/requests/notification_subscriptions_spec.rb
  spec/services/notifications/new_comment/send_spec.rb
Labels: PR: unreviewed

#3165 Adjust notification subscriptions JS and css
  app/assets/stylesheets/article-show.scss
  app/javascript/packs/notificationSubscriptionHandler.js
Labels: PR: unreviewed

#2956 Buffer Listings
  Envfile
  app/controllers/internal/buffer_updates_controller.rb
  app/controllers/social_previews_controller.rb
  app/helpers/social_image_helper.rb
  app/labor/bufferizer.rb
  app/models/buffer_update.rb
  app/models/classified_listing.rb
  app/views/classified_listings/index.html.erb
  app/views/internal/articles/_article_script.html.erb
  app/views/internal/articles/_individual_article.html.erb
  app/views/internal/classified_listings/index.html.erb
  app/views/layouts/internal.html.erb
  app/views/social_previews/listing.html.erb
  config/initializers/assets.rb
  config/routes.rb
  db/migrate/20190524214445_add_last_buffered_to_classified_listings.rb
  db/schema.rb
  db/seeds.rb
  spec/labor/bufferizer_spec.rb
  spec/requests/social_previews_spec.rb
Labels: PR: reviewed-approved

#3166 Clean up internal and add admin tool for cache busting
  app/controllers/internal/members_controller.rb
  app/controllers/internal/tools_controller.rb
  app/views/internal/members/index.html.erb
  app/views/internal/tools/index.html.erb
  config/routes.rb
Labels: PR: reviewed-approved

#3167 Create comments notification subscription upon creation
  app/controllers/comments_controller.rb
  spec/requests/comments_create_spec.rb
Labels: PR: unreviewed

#3168 Adjust text in mobile notification title
  app/services/notifications/new_comment/send.rb
Labels: PR: unreviewed

#3170 Add subtitle to ios push notification
  app/models/comment.rb
  app/services/notifications/new_comment/send.rb
Labels: PR: unreviewed

#3176 Beta polls feature (admin use only for now)
  app/assets/stylesheets/ltags/LiquidTags.scss
  app/assets/stylesheets/ltags/PollTag.scss
  app/controllers/poll_skips_controller.rb
  app/controllers/poll_votes_controller.rb
  app/decorators/article_decorator.rb
  app/labor/markdown_parser.rb
  app/liquid_tags/poll_tag.rb
  app/models/article.rb
  app/models/poll.rb
  app/models/poll_option.rb
  app/models/poll_skip.rb
  app/models/poll_vote.rb
  app/models/user.rb
  app/views/articles/show.html.erb
  app/views/liquids/_poll.html.erb
  config/routes.rb
  db/migrate/20190525233909_create_polls.rb
  db/migrate/20190525233918_create_poll_options.rb
  db/migrate/20190525233934_create_poll_votes.rb
  db/migrate/20190611195955_create_poll_skips.rb
  db/schema.rb
  spec/factories/poll_options.rb
  spec/factories/poll_skips.rb
  spec/factories/poll_votes.rb
  spec/factories/polls.rb
  spec/models/article_spec.rb
  spec/models/poll_option_spec.rb
  spec/models/poll_skip_spec.rb
  spec/models/poll_spec.rb
  spec/models/poll_vote_spec.rb
  spec/requests/poll_skips_spec.rb
  spec/requests/poll_votes_spec.rb
Labels: PR: unreviewed

#3178 Add a possible error resolution for windows installation
  docs/installation/windows.md
Labels: PR: reviewed-approved

#3177 Further generalize pages and site Twitter handle
  Envfile
  app/assets/javascripts/initializers/initializeFooterMod.js
  app/controllers/giveaways_controller.rb
  app/controllers/internal/pages_controller.rb
  app/controllers/stories_controller.rb
  app/helpers/application_helper.rb
  app/models/organization.rb
  app/models/page.rb
  app/models/podcast.rb
  app/models/user.rb
  app/views/articles/_sidebar.html.erb
  app/views/articles/index.html.erb
  app/views/articles/manage.html.erb
  app/views/articles/search/_meta.html.erb
  app/views/articles/show.html.erb
  app/views/articles/tags/_meta.html.erb
  app/views/classified_listings/index.html.erb
  app/views/comments/index.html.erb
  app/views/events/index.html.erb
  app/views/events/show.html.erb
  app/views/giveaways/_form.html.erb
  app/views/giveaways/edit.html.erb
  app/views/giveaways/new.html.erb
  app/views/internal/articles/_individual_article.html.erb
  app/views/internal/pages/_form.html.erb
  app/views/notifications/index.html.erb
  app/views/pages/about.html.erb
  app/views/pages/api.html.erb
  app/views/pages/badges.html.erb
  app/views/pages/bounty.html.erb
  app/views/pages/code_of_conduct.html.erb
  app/views/pages/community_moderation.html.erb
  app/views/pages/contact.html.erb
  app/views/pages/show.html.erb
  app/views/pages/tag_moderation.html.erb
  config/routes.rb
  db/migrate/20190616024727_add_is_top_level_path_to_pages.rb
  db/schema.rb
  spec/models/organization_spec.rb
  spec/models/page_spec.rb
  spec/models/podcast_spec.rb
  spec/models/user_spec.rb
  spec/requests/pages_spec.rb
  spec/system/user_fills_out_givaway_form_spec.rb
Labels: PR: unreviewed

#3179 Add minimal light theme
  app/assets/stylesheets/ltags/PollTag.scss
  app/controllers/html_variants_controller.rb
  app/models/user.rb
  app/views/html_variants/index.html.erb
  app/views/html_variants/show.html.erb
  app/views/layouts/_user_config.html.erb
  app/views/users/_misc.html.erb
  spec/models/user_spec.rb
Labels: PR: unreviewed

#3187 Remove double presence validator in PollVote
  app/models/poll_vote.rb
  spec/models/poll_vote_spec.rb
Labels: PR: reviewed-approved

#3182 Add warn_on_records_fetched_greater_than setting in development [skip ci]
  config/environments/development.rb
Labels: PR: reviewed-approved

#3126 Add Date to Link Liquid Tag
  app/views/articles/_liquid.html.erb
  spec/liquid_tags/link_tag_spec.rb
Labels: PR: reviewed-approved

#3203 Add organization liquid tag
  app/liquid_tags/organization_tag.rb
  app/views/organizations/_liquid.html.erb
  spec/liquid_tags/organization_tag_spec.rb
Labels: PR: unreviewed

#3202 fix(article): `<hr>` should be visible in night theme
  app/assets/stylesheets/article-show.scss
Labels: PR: reviewed-approved

#3214 Fix some typos in Dockerfile comments
  Dockerfile
Labels: PR: reviewed-approved

#3076 Update timestamp on notifications
  app/views/notifications/_article.html.erb
  app/views/notifications/_comment.html.erb
Labels: PR: reviewed-approved

#3218 Updated slack channel name
  app/observers/application_observer.rb
Labels: PR: reviewed-approved

#3014 Listings Dashboard
  app/assets/stylesheets/classified_listings.scss
  app/controllers/classified_listings_controller.rb
  app/javascript/listings/__tests__/__snapshots__/listingDashboard.test.jsx.snap
  app/javascript/listings/__tests__/listingDashboard.test.jsx
  app/javascript/listings/dashboard/listingRow.jsx
  app/javascript/listings/listingDashboard.jsx
  app/javascript/listings/listings.jsx
  app/javascript/packs/listingDashboard.jsx
  app/views/classified_listings/_form.html.erb
  app/views/classified_listings/dashboard.html.erb
  config/routes.rb
Labels: PR: reviewed-approved, listings

#3220 Pro: History
  app/assets/javascripts/initializers/initializeEllipsisMenu.js
  app/assets/javascripts/utilities/checkUserLoggedIn.js
  app/assets/stylesheets/history.scss
  app/assets/stylesheets/scaffolds.scss
  app/controllers/history_controller.rb
  app/controllers/reading_list_items_controller.rb
  app/javascript/history/history.jsx
  app/javascript/packs/history.jsx
  app/javascript/readingList/readingList.jsx
  app/javascript/src/utils/algolia.js
  app/models/page_view.rb
  app/views/articles/_sidebar_nav.html.erb
  app/views/history/index.html.erb
  app/views/layouts/_footer.html.erb
  app/views/layouts/_styles.html.erb
  config/routes.rb
  package.json
  spec/requests/history_spec.rb
  yarn.lock
Labels: PR: reviewed-approved, pro

#3219 Don't try to register webhook when twitch returns empty data
  app/services/streams/twitch_webhook/register.rb
  spec/services/streams/twitch_webhook/register_spec.rb
Labels: PR: reviewed-approved

#3215 Allow stackoverflow sub communities profiles
  app/models/user.rb
  spec/models/user_spec.rb
Labels: PR: reviewed-approved

#3188 Fix mention validation when validating an empty instance
  app/models/mention.rb
  spec/factories/mentions.rb
  spec/mailers/notify_mailer_spec.rb
  spec/models/mention_spec.rb
Labels: PR: reviewed-approved

#3173 Move HtmlVariantSuccess.create delay calls to ActiveJob
  app/controllers/html_variant_successes_controller.rb
  app/jobs/html_variant_success_create_job.rb
  spec/jobs/html_variant_success_create_job_spec.rb
  spec/requests/html_variant_successes_spec.rb
Labels: PR: reviewed-approved

#3233 Dashboard listings: optimized queries
  app/controllers/classified_listings_controller.rb
Labels: PR: reviewed-approved

#3232 Display stats for organization article
  app/controllers/articles_controller.rb
  app/javascript/analytics/dashboard.js
  app/javascript/packs/analyticsArticle.js
  app/javascript/src/utils/errors.js
  app/services/analytics_service.rb
  app/views/articles/stats.html.erb
Labels: PR: reviewed-approved

#3235 Remove hardcoded image from chat channel images
  app/models/chat_channel_membership.rb
Labels: PR: unreviewed

#3230 Add article pro stats button in dashboard
  app/controllers/dashboards_controller.rb
  app/views/dashboards/_dashboard_article.html.erb
  spec/requests/dashboard_spec.rb
Labels: PR: reviewed-approved, pro

#3237 Add missing listings logo for social card
  app/assets/images/devlistings-horizontal.svg
Labels: PR: reviewed-approved

#3238 add buffered checkbox to individual articles
  app/controllers/internal/articles_controller.rb
  app/views/internal/articles/_individual_article.html.erb
  app/views/internal/tools/index.html.erb
Labels: PR: reviewed-approved

#3228 Manage listings as organization admin
  app/controllers/classified_listings_controller.rb
  app/models/classified_listing.rb
  app/policies/classified_listing_policy.rb
  app/views/classified_listings/edit.html.erb
  spec/models/classified_listing_spec.rb
Labels: PR: reviewed-approved, listings

#3240 Add backend functionality for muting users you follow
  app/models/follow.rb
  app/services/notifications/notifiable_action/send.rb
  db/migrate/20190619153428_add_subscription_status_to_follows.rb
  db/schema.rb
  spec/models/follow_spec.rb
  spec/services/notifications/notifiable_action/send_spec.rb
Labels: PR: reviewed-approved

#3247 Update Listings Buffer Text
  app/views/internal/classified_listings/index.html.erb
Labels: PR: reviewed-approved

#3221 Feature/reading list loadmore button
  app/assets/stylesheets/readinglist.scss
  app/javascript/readingList/readingList.jsx
Labels: PR: reviewed-approved

#3248 Update doc on statement_timeout errors
  docs/installation/windows.md
Labels: PR: unreviewed

#3229 Update RssReader's liquid & youtube parsing logic
  app/services/rss_reader/assembler.rb
Labels: PR: reviewed-approved

#3249 Delete a comment's title if it is deleted
  app/assets/stylesheets/notifications.scss
  app/models/comment.rb
  app/views/comments/index.html.erb
  app/views/notifications/_notifications_list.html.erb
  spec/models/comment_spec.rb
Labels: PR: reviewed-approved

#3239 Move HtmlVariantTrial.create delay calls to ActiveJob (#3173)
  app/controllers/html_variant_trials_controller.rb
  app/jobs/html_variant_trial_create_job.rb
  spec/jobs/html_variant_trial_create_job_spec.rb
  spec/requests/html_variant_trials_spec.rb
Labels: PR: reviewed-approved

#3251 Fix logic and adjust copy for tag rewarding
  app/labor/badge_rewarder.rb
  spec/labor/badge_rewarder_spec.rb
Labels: PR: unreviewed

#3258 Add context data to comment notifications
  app/models/comment.rb
  app/services/notifications.rb
  app/services/notifications/remove_each.rb
  spec/models/comment_spec.rb
  spec/models/notification_spec.rb
  spec/requests/stories_index_spec.rb
Labels: PR: reviewed-approved

#3255 Fixed rubocop issues, new .rubocop_todo.yml
  .rubocop_todo.yml
  app/controllers/html_variants_controller.rb
  app/controllers/notification_subscriptions_controller.rb
  app/controllers/poll_skips_controller.rb
  app/controllers/poll_votes_controller.rb
  app/helpers/application_helper.rb
  app/labor/badge_rewarder.rb
  app/liquid_tags/poll_tag.rb
  app/models/article.rb
  app/models/poll.rb
  app/models/poll_option.rb
  app/models/poll_skip.rb
  spec/labor/badge_rewarder_spec.rb
  spec/liquid_tags/link_tag_spec.rb
  spec/liquid_tags/organization_tag_spec.rb
  spec/models/poll_skip_spec.rb
  spec/models/user_spec.rb
Labels: PR: reviewed-approved

#3186 Remove code for legacy mentoring feature
  app/controllers/internal/users_controller.rb
  app/labor/mentorship_matcher.rb
  app/labor/user_similarity.rb
  app/mailers/notify_mailer.rb
  app/models/mentor_relationship.rb
  app/models/role.rb
  app/models/user.rb
  app/policies/user_policy.rb
  app/services/moderator/manage_activity_and_roles.rb
  app/views/internal/users/_mentee_match.erb
  app/views/internal/users/index.html.erb
  app/views/internal/users/show.html.erb
  app/views/mailers/notify_mailer/mentee_email.html.erb
  app/views/mailers/notify_mailer/mentee_email.text.erb
  app/views/mailers/notify_mailer/mentor_email.html.erb
  app/views/mailers/notify_mailer/mentor_email.text.erb
  app/views/users/_mentorship.html.erb
  db/migrate/20190617101811_remove_mentorship_columns_from_user.rb
  db/migrate/20190617102149_drop_mentor_relationships.rb
  db/schema.rb
  spec/labor/mentorship_matcher_spec.rb
  spec/labor/user_similarity_spec.rb
  spec/mailers/notify_mailer_spec.rb
  spec/mailers/previews/notify_mailer_preview.rb
  spec/models/mentor_relationship_spec.rb
  spec/models/user_spec.rb
  spec/requests/follows_update_spec.rb
  spec/requests/internal/users_spec.rb
  spec/requests/internal_users_spec.rb
  spec/services/moderator/manage_activity_and_roles_spec.rb
Labels: PR: reviewed-approved

#3245 More specs and refactoring podcasts fetching
  app/jobs/podcasts/get_episodes_job.rb
  app/labor/podcast_feed.rb
  app/services/podcasts/create_episode.rb
  app/services/podcasts/feed.rb
  app/services/podcasts/get_episode.rb
  app/services/podcasts/update_episode.rb
  spec/requests/podcast_episodes_api_spec.rb
  spec/services/podcasts/create_episode_spec.rb
  spec/services/podcasts/feed_spec.rb
  spec/services/podcasts/update_episode_spec.rb
  spec/support/fixtures/awayfromthekeyboard.rss
  spec/support/fixtures/developertea.rss
Labels: PR: reviewed-approved

#3262 Add comment context for notifications and comment pages
  app/assets/stylesheets/articles.scss
  app/assets/stylesheets/comments.scss
  app/assets/stylesheets/notifications.scss
  app/models/comment.rb
  app/views/comments/index.html.erb
  app/views/notifications/_comment.html.erb
  app/views/notifications/index.html.erb
  app/views/notifications/shared/_comment_box.html.erb
  spec/models/comment_spec.rb
  spec/requests/comments_spec.rb
  spec/requests/notifications_spec.rb
Labels: PR: unreviewed

#3273 Return original body instead of nil for new comment push notifications
  app/services/notifications/new_comment/send.rb
Labels: PR: reviewed-approved

#3270 Comments: remove double stripping undoing escaping
  app/models/comment.rb
  app/views/comments/index.html.erb
  app/views/notifications/shared/_comment_box.html.erb
Labels: PR: reviewed-approved

#3278 Rubocop: disable style rule and fix some issues
  .rubocop.yml
  .rubocop_todo.yml
  spec/labor/badge_rewarder_spec.rb
  spec/models/comment_spec.rb
  spec/requests/notifications_spec.rb
Labels: PR: reviewed-approved

#3268 Added the dependabot badge.
  README.md
Labels: PR: reviewed-approved

#3071 Move bust_cache methods in own jobs
  app/controllers/concerns/classified_listings_toolkit.rb
  app/jobs/classified_listings/bust_cache_job.rb
  app/jobs/events/bust_cache_job.rb
  app/jobs/organizations/bust_cache_job.rb
  app/jobs/pages/bust_cache_job.rb
  app/jobs/podcast_episodes/bust_cache_job.rb
  app/jobs/podcasts/bust_cache_job.rb
  app/jobs/tags/bust_cache_job.rb
  app/labor/cache_buster.rb
  app/models/event.rb
  app/models/organization.rb
  app/models/page.rb
  app/models/podcast.rb
  app/models/podcast_episode.rb
  app/models/tag.rb
  spec/jobs/classified_listings/bust_cache_job_spec.rb
  spec/jobs/events/bust_cache_job_spec.rb
  spec/jobs/organizations/bust_cache_job_spec.rb
  spec/jobs/pages/bust_cache_job_spec.rb
  spec/jobs/podcast_episodes/bust_cache_job_spec.rb
  spec/jobs/podcasts/bust_cache_job_spec.rb
  spec/jobs/tags/bust_cache_job_spec.rb
  spec/labor/cache_buster_spec.rb
  spec/models/event_spec.rb
  spec/models/organization_spec.rb
  spec/models/page_spec.rb
  spec/models/podcast_episode_spec.rb
  spec/models/podcast_spec.rb
  spec/models/tag_spec.rb
  spec/requests/internal/classified_listings_spec.rb
Labels: PR: reviewed-approved

#3269 Add pinned articles box to profiles
  app/assets/images/pushpin.svg
  app/assets/stylesheets/articles.scss
  app/assets/stylesheets/dashboard.scss
  app/controllers/profile_pins_controller.rb
  app/controllers/stories_controller.rb
  app/javascript/history/history.jsx
  app/javascript/listings/__tests__/listingDashboard.test.jsx
  app/javascript/listings/dashboard/listingRow.jsx
  app/javascript/listings/listingDashboard.jsx
  app/javascript/listings/listings.jsx
  app/models/article.rb
  app/models/organization.rb
  app/models/profile_pin.rb
  app/models/user.rb
  app/views/articles/_single_story.html.erb
  app/views/articles/manage.html.erb
  app/views/dashboards/_dashboard_article.html.erb
  app/views/users/_main_feed.html.erb
  config/routes.rb
  db/migrate/20190616053854_create_profile_pins.rb
  db/schema.rb
  spec/factories/profile_pins.rb
  spec/models/profile_pin_spec.rb
  spec/requests/profile_pins_spec.rb
  spec/requests/user_profile_spec.rb
Labels: PR: unreviewed

#3299 3035 - Increase tag length limit from 20 to 30 chars
  app/models/article.rb
  spec/models/article_spec.rb
Labels: PR: reviewed-approved

#3279 Pro: Deduplicate history items
  app/javascript/history/history.jsx
  app/models/page_view.rb
Labels: PR: reviewed-approved

#3265 Improve social card caching 🚀
  app/views/social_previews/article.html.erb
  app/views/social_previews/listing.html.erb
  app/views/social_previews/tag.html.erb
  app/views/social_previews/user.html.erb
  spec/requests/social_previews_spec.rb
Labels: PR: reviewed-approved

#3162 Add Item Count to Reading List Header
  app/javascript/readingList/readingList.jsx
Labels: PR: reviewed-approved

#3147 use dynamic route name
  app/controllers/users_controller.rb
  config/routes.rb
Labels: PR: reviewed-approved

#3301 Use publish date for article notifications
  app/services/notifications.rb
  app/views/notifications/_article.html.erb
  spec/requests/notifications_spec.rb
Labels: PR: reviewed-approved

#3295 Pro: add referrers to dashboard and single article stats
  app/assets/stylesheets/dashboard.scss
  app/controllers/api/v0/analytics_controller.rb
  app/controllers/page_views_controller.rb
  app/javascript/analytics/client.js
  app/javascript/analytics/dashboard.js
  app/models/page_view.rb
  app/services/analytics_service.rb
  app/views/articles/stats.html.erb
  app/views/dashboards/pro.html.erb
  app/views/shared/_stats.html.erb
  config/routes.rb
  db/migrate/20190624093012_add_domain_and_path_to_page_views.rb
  db/migrate/20190625143841_add_index_to_page_view_domain.rb
  db/schema.rb
  lib/assets/.keep
  lib/tasks/.keep
  lib/tasks/db.rake
  lib/tasks/linters.rake
  lib/tasks/temporary/page_views.rake
  spec/factories/page_views.rb
  spec/models/page_view_spec.rb
  spec/requests/api/v0/analytics_spec.rb
  spec/services/analytics_service_spec.rb
Labels: PR: reviewed-approved

#3310 Allow Embed of specific gist version
  app/liquid_tags/gist_tag.rb
  app/views/pages/_editor_guide_text.html.erb
  spec/liquid_tags/gist_tag_spec.rb
Labels: PR: reviewed-approved

#3307 Add Instagram URL to profile links
  app/controllers/admin/users_controller.rb
  app/dashboards/user_dashboard.rb
  app/models/user.rb
  app/policies/user_policy.rb
  app/services/moderator/banish_user.rb
  app/views/users/_profile.html.erb
  app/views/users/_profile_header.html.erb
  app/views/users/show.html.erb
  db/migrate/20190626022355_add_instagram_url_to_users.rb
  db/schema.rb
  spec/models/user_spec.rb
Labels: PR: reviewed-approved

#3304 Add rel="nofollow" to links in comments
  app/labor/markdown_parser.rb
  app/models/comment.rb
  spec/models/comment_spec.rb
Labels: PR: reviewed-approved

#3306 Fix escape key handling and add space in single listing view
  app/javascript/listings/listings.jsx
Labels: PR: reviewed-approved

#3312 Tweak black box so posts won't stick
  app/black_box/black_box.rb
Labels: PR: unreviewed

#3315 Hide delete article button for non-authors
  app/views/dashboards/_dashboard_article.html.erb
  spec/requests/dashboard_spec.rb
Labels: PR: reviewed-approved

#3311 Fix comment title encoding issue
  Gemfile
  Gemfile.lock
  app/models/comment.rb
  spec/models/comment_spec.rb
Labels: PR: unreviewed

#3319 Refactored and optimized getting existing podcast episode
  app/models/podcast.rb
  app/services/podcasts/get_episode.rb
  spec/models/podcast_spec.rb
Labels: PR: reviewed-approved

#3323 Documentation update for Admin panel, on Backend instructions
  docs/backend/admin.md
Labels: PR: reviewed-approved

#3320 Make item count 'empty' instead of '0' when reading list is empty
  app/javascript/readingList/readingList.jsx
Labels: PR: reviewed-approved

#3321 Fix org credits in internal view
  app/controllers/internal/users_controller.rb
  app/models/credit.rb
  app/views/internal/users/_credits.erb
  spec/requests/internal/users_spec.rb
Labels: PR: reviewed-approved

#3327 Add GET /internal/tags/:id route back in
  app/controllers/internal/tags_controller.rb
  config/routes.rb
  spec/requests/internal/tags_spec.rb
Labels: PR: reviewed-approved

#3313 Set max file size limit for profile images
  app/uploaders/profile_image_uploader.rb
  spec/fixtures/files/large_profile_img.jpg
  spec/requests/user_settings_spec.rb
Labels: PR: reviewed-approved

#3326 Allow multiple banishes on the same account
  app/models/user.rb
  app/views/internal/users/edit.html.erb
Labels: PR: reviewed-approved

#3322 Disable use of localStorage when cookie-less
  app/assets/javascripts/utilities/browserStoreCache.js
Labels: PR: reviewed-approved
