Repository forem/forem, pull requests merged in 2019-10, with the labels that each got.

#4166 Add hacktoberfest sidebar and flare
  app/labor/flare_tag.rb
  app/views/articles/_sidebar_additional.html.erb
Labels: PR: unreviewed

#4154 Refactoring view.jsx removes code duplication
  app/javascript/chat/__tests__/__snapshots__/view.test.jsx.snap
  app/javascript/chat/view.jsx
Labels: PR: reviewed-approved

#4120 Fix medium liquid tags scraping (#3485)
  app/services/medium_article_retrieval_service.rb
  spec/services/medium_article_retrieval_service_spec.rb
  spec/support/fixtures/vcr_cassettes/medium.yml
Labels: PR: unreviewed

#4171 Add some architecture docs [skip ci]
  docs/getting-started/architecture.md
  docs/getting-started/readme.md
Labels: PR: unreviewed

#4115 Refactoring Notifications::NewComment::Send
  app/services/notifications/new_comment/send.rb
Labels: PR: reviewed-approved

#4159 Refactoring articleForm.jsx removes code duplication
  app/javascript/article-form/articleForm.jsx
Labels: PR: unreviewed

#4178 Add comment syntax explanation #4130
  app/views/pages/_editor_guide_text.html.erb
Labels: PR: reviewed-approved

#4140 Adjust RSS's publish date
  app/models/article.rb
  app/services/rss_reader.rb
  app/services/rss_reader/assembler.rb
  spec/fixtures/approvals/rssreader/get_all_articles/parses_correctly.approved.txt
  spec/models/article_spec.rb
Labels: PR: reviewed-approved

#4177 Fix typos and mechanical mistakes [ci skip]
  docs/backend/algolia.md
  docs/backend/auth-github.md
  docs/backend/auth-twitter.md
  docs/backend/authorization.md
  docs/backend/notification.md
  docs/backend/pusher.md
  docs/backend/roles.md
  docs/backend/scheduled-jobs.md
  docs/contributing.md
  docs/contributing_api.md
  docs/design/branding.md
  docs/design/theming.md
  docs/faqs.md
  docs/frontend/liquid-tags.md
  docs/frontend/plain-js.md
  docs/frontend/webpacker.md
  docs/getting-started/architecture.md
  docs/getting-started/branching.md
  docs/getting-started/config-env.md
  docs/getting-started/pull-request.md
  docs/getting-started/syncing.md
  docs/getting-started/workflow.md
  docs/installation/docker.md
  docs/installation/linux.md
  docs/installation/mac.md
  docs/installation/postgresql.md
  docs/readme.md
  docs/self-hosting.md
  docs/tests/acceptance-tests.md
  docs/tests/code-coverage.md
  docs/tests/integration-tests.md
  docs/tests/preact-tests.md
  docs/tests/unit-functional-tests.md
Labels: PR: reviewed-approved

#4175 Remove repetitive docs phrasing to improve readability
  docs/technical-overview.md
Labels: PR: reviewed-approved

#4161 Refactoring userDetails.jsx removes user config duplication
  app/javascript/chat/userDetails.jsx
Labels: PR: unreviewed

#4157 Refactoring sendFetch.jsx removes code duplication
  app/assets/javascripts/utilities/sendFetch.js
Labels: PR: unreviewed

#4191 Prepend before_destroy(s) in models with destroy dependents
  app/models/article.rb
  app/models/chat_channel.rb
  app/models/user.rb
Labels: PR: reviewed-approved

#4152 Add Asciinema Liquid tag
  app/liquid_tags/asciinema_tag.rb
  app/views/liquids/_asciinema.html.erb
  app/views/pages/_editor_guide_text.html.erb
  spec/liquid_tags/asciinema_tag_spec.rb
Labels: PR: reviewed-approved

#4193 Fix rubocop issue
  spec/models/pro_membership_spec.rb
Labels: PR: reviewed-approved

#4189 Fixed contributing docs
  CONTRIBUTING.md
Labels: PR: reviewed-approved

#4170 Limit access to the API actions when authorized by doorkeeper token
  app/controllers/api/v0/api_controller.rb
  app/controllers/api/v0/articles_controller.rb
  app/controllers/api/v0/classified_listings_controller.rb
  app/controllers/api/v0/users_controller.rb
  spec/requests/api/v0/articles_spec.rb
  spec/requests/api/v0/classified_listings_spec.rb
  spec/requests/api/v0/users_spec.rb
Labels: PR: reviewed-approved

#4188 Added test markdown parse snake case
  .gitignore
  spec/labor/markdown_parser_spec.rb
Labels: PR: reviewed-approved

#3965 Fix footer position bug
  app/assets/stylesheets/footer.scss
Labels: PR: reviewed-approved

#4190 Fixes Dev listings button color in pink theme
  app/assets/stylesheets/classified_listings.scss
Labels: PR: reviewed-approved

#4137 Improve the tag edit page (Tag moderators only)
  app/assets/stylesheets/tag-edit.scss
  app/views/tags/edit.html.erb
Labels: PR: reviewed-approved

#4201 Fix technical overview doc layout [ci skip]
  docs/technical-overview.md
Labels: PR: reviewed-approved

#4198 Make onboarding compatible with all themes (#3604)
  app/assets/stylesheets/preact/onboarding-modal.scss
Labels: PR: reviewed-approved

#4202 Updates nio4r gem version
  Gemfile.lock
Labels: PR: reviewed-approved

#4187 Added anchor and basic setup using docker
  README.md
Labels: PR: reviewed-approved

#4169 Create tests to PingAdmins
  Envfile
  app/services/ping_admins.rb
  config/initializers/slack_notifier.rb
  spec/services/ping_admins_spec.rb
Labels: PR: reviewed-approved

#4156 Refactoring personalInfoForm.jsx removes code duplication
  app/javascript/onboarding/components/PersonalInfoForm.jsx
Labels: PR: reviewed-approved

#4203 Move user.follow delay calls to ActiveJob (#3136)
  app/controllers/api/v0/follows_controller.rb
  app/controllers/users_controller.rb
  app/jobs/users/follow_job.rb
  spec/jobs/users/follow_job_spec.rb
  spec/requests/follows_api_spec.rb
  spec/system/user_selects_looking_for_work_spec.rb
Labels: PR: reviewed-approved

#4180 Add collection ids to Api (reading + filtering)
  app/controllers/api/v0/articles_controller.rb
  app/services/article_api_index_service.rb
  app/views/api/v0/articles/index.json.jbuilder
  app/views/api/v0/articles/show.json.jbuilder
  spec/requests/api/v0/articles_spec.rb
Labels: PR: reviewed-approved

#4176 Remove periods in technical overview list
  docs/technical-overview.md
Labels: PR: reviewed-approved

#4200 Removed useless argument
  app/views/liquid_embeds/show.html.erb
Labels: PR: reviewed-approved

#4218 Adding cybre.space instance
  app/lib/constants.rb
Labels: PR: reviewed-approved

#4192 Fix tabbing order of article engagement icons
  app/views/articles/_single_story.html.erb
Labels: PR: reviewed-approved

#4213 Mobile friendly design for /credits page
  app/assets/stylesheets/credits.scss
Labels: PR: reviewed-approved

#4215 Update DEV onboarding documentation
  docs/getting-started/branching.md
  docs/getting-started/committing.md
  docs/getting-started/config-env.md
  docs/getting-started/db.md
  docs/getting-started/forking.md
  docs/getting-started/start-app.md
  docs/getting-started/workflow.md
Labels: PR: reviewed-approved

#4209 Fix embedded comment date alignmemt issue
  app/assets/stylesheets/comments.scss
Labels: PR: reviewed-approved

#4172 #3777 Fix lint errors in notificationSubscriptionHander.js
  app/javascript/packs/notificationSubscriptionHandler.js
Labels: PR: reviewed-approved

#4256 Remove commented out SCSS
  app/assets/stylesheets/article-form-needed-legacy.scss
  app/assets/stylesheets/article-show.scss
  app/assets/stylesheets/articles.scss
  app/assets/stylesheets/chat.scss
  app/assets/stylesheets/classified_listings.scss
  app/assets/stylesheets/comments.scss
  app/assets/stylesheets/dashboard.scss
  app/assets/stylesheets/footer.scss
  app/assets/stylesheets/ltags/DevCommentTag.scss
  app/assets/stylesheets/ltags/GithubTag.scss
  app/assets/stylesheets/ltags/PodcastTag.scss
  app/assets/stylesheets/podcast-episodes-show.scss
  app/assets/stylesheets/preact/onboarding-modal.scss
  app/assets/stylesheets/shared.scss
  app/assets/stylesheets/top-bar.scss
  app/assets/stylesheets/user-profile-header.scss
Labels: PR: reviewed-approved

#4257 Mini refactor to make variable names clearer in the Categories component
  app/javascript/listings/elements/categories.jsx
Labels: PR: reviewed-approved

#4236 Add badges index page.
  app/assets/stylesheets/badges.scss
  app/controllers/badges_controller.rb
  app/views/badges/index.html.erb
  app/views/layouts/_styles.html.erb
  config/routes.rb
  spec/requests/badges_spec.rb
Labels: PR: reviewed-approved

#4205 Added link to podcats from episodes feed
  app/views/podcast_episodes/_episodes_feed.html.erb
Labels: PR: reviewed-approved

#4246 Fix text color "Load more listings" button
  app/assets/stylesheets/classified_listings.scss
Labels: PR: reviewed-approved

#4237 Test: add test for opening help window on articleForm
  app/javascript/article-form/__tests__/articleForm.test.jsx
Labels: PR: reviewed-approved

#4275 Bust non-article comment cache without issues
  app/labor/cache_buster.rb
  spec/labor/cache_buster_spec.rb
Labels: PR: reviewed-approved

#4153 removing unneeded margin-left in @media tag
  app/assets/stylesheets/footer.scss
Labels: PR: reviewed-approved

#4155 Bug/fixes links without http(s)
  app/lib/redcarpet/render/html_rouge.rb
  spec/labor/markdown_parser_spec.rb
Labels: PR: reviewed-approved

#4260 Comment Social Preview
  app/controllers/social_previews_controller.rb
  app/helpers/social_image_helper.rb
  app/views/articles/show.html.erb
  app/views/comments/index.html.erb
  app/views/social_previews/comment.html.erb
  config/routes.rb
  spec/requests/social_previews_spec.rb
Labels: PR: reviewed-approved

#4274 Rescue SocketError when trying to fetch a podcast
  app/services/podcasts/feed.rb
Labels: PR: reviewed-approved

#4225 removed invert filter from profile header social icons
  app/assets/stylesheets/user-profile-header.scss
Labels: PR: reviewed-approved

#4282 Create CODEOWNERS [ci skip]
  .github/CODEOWNERS
Labels: PR: reviewed-approved

#4249 Fixed printing issues with header & footer
  app/assets/stylesheets/scaffolds.scss
Labels: PR: reviewed-approved

#4278 Fix badges overlapping in badges index page
  app/assets/stylesheets/badges.scss
Labels: PR: reviewed-approved

#4301 Test: add test for sidebarUser component
  app/javascript/sidebar-widget/__tests__/__snapshots__/sidebarUser.test.jsx.snap
  app/javascript/sidebar-widget/__tests__/sidebarUser.test.jsx
Labels: PR: reviewed-approved

#4303 Refactor initializeArticleReactions.js
  app/assets/javascripts/initializers/initializeArticleReactions.js
Labels: PR: reviewed-approved

#4222 fixes bug in tag search feature
  app/javascript/shared/components/tags.jsx
Labels: PR: reviewed-approved

#4233 Add more info to architecture
  app/labor/flare_tag.rb
  docs/frontend/liquid-tags.md
  docs/getting-started/architecture.md
  docs/getting-started/pull-request.md
Labels: PR: unreviewed

#4220 Added `purpose` tag to 192x192
  app/assets/javascripts/manifest.json.erb
Labels: PR: reviewed-approved

#4312 Refactor: initializeCreditsPage.js
  app/assets/javascripts/initializers/initializeCreditsPage.js
Labels: PR: reviewed-approved

#4311 Create scoped policy for internal/comment
  app/controllers/internal/comments_controller.rb
  app/models/comment.rb
  app/policies/internal/comment_policy.rb
  spec/policies/internal/comment_policy_spec.rb
Labels: PR: reviewed-approved

#4270 Fixes Github Liquid Tag alignment in notifications page
  app/assets/stylesheets/ltags/GithubTag.scss
Labels: PR: reviewed-approved

#4226 added mod_roundrobin_notifications to user_policy.rb
  app/policies/user_policy.rb
  spec/requests/user_settings_spec.rb
Labels: PR: reviewed-approved

#4212 Fix #4106: Showing color preview in Edit Profile
  app/assets/stylesheets/settings.scss
  app/javascript/packs/colorPreview.js
  app/views/users/_profile.html.erb
Labels: PR: reviewed-approved

#4258 Fixed invalid body_markdown in article with video
  app/controllers/articles_controller.rb
  app/services/article_with_video_creation_service.rb
  spec/services/article_with_video_creation_service_spec.rb
Labels: PR: reviewed-approved

#4265 Markdown fixer: fix front matter bug with no space
  app/labor/markdown_fixer.rb
  spec/labor/markdown_fixer_spec.rb
  spec/models/article_spec.rb
Labels: PR: reviewed-approved

#4272 Feat: #3498 Display episode's published_at
  app/assets/stylesheets/podcast-episodes-show.scss
  app/controllers/podcast_episodes_controller.rb
  app/controllers/stories_controller.rb
  app/decorators/podcast_episode_decorator.rb
  app/views/articles/_podcast_episodes_feed.html.erb
  app/views/podcast_episodes/_episodes_feed.html.erb
  app/views/podcast_episodes/show.html.erb
  spec/system/podcasts/user_visits_podcast_episode_spec.rb
  spec/system/podcasts/user_visits_podcast_page_spec.rb
  spec/system/podcasts/user_visits_podcasts_root_page_spec.rb
Labels: PR: reviewed-approved

#4183 Delete messages without instantiating ActiveRecord objects
  app/controllers/chat_channels_controller.rb
  app/models/chat_channel.rb
Labels: PR: reviewed-approved

#2322 Combining tags together in a search query (#2238)
  app/views/articles/_algolia_search.html.erb
Labels: PR: reviewed-approved

#4323 Now eslint ignores the app/assets/javascripts/lib folder.
  .eslintignore
Labels: PR: reviewed-approved

#4322 Fix gotchas with color preview and some style adjustments and add docs
  app/assets/stylesheets/settings.scss
  app/javascript/packs/colorPreview.js
  docs/getting-started/architecture.md
Labels: PR: unreviewed

#4318 Refactor/fix initializeCommentDropdown.js
  app/assets/javascripts/initializers/initializeCommentDropdown.js
Labels: PR: reviewed-approved

#4313 Refactor: initializeDashboardSort.js
  app/assets/javascripts/initializers/initializeDashboardSort.js
Labels: PR: reviewed-approved

#4334 Specs: use a bigger sample for badges titles
  spec/factories/badges.rb
Labels: PR: reviewed-approved

#4331 Add an alt text and some type="button" attributes
  app/assets/javascripts/utilities/buildArticleHTML.js.erb
  app/views/articles/_sidebar_additional.html.erb
  app/views/articles/_single_story.html.erb
  app/views/articles/index.html.erb
  app/views/articles/tag_index.html.erb
  app/views/layouts/_signup_modal.html.erb
  app/views/layouts/_top_bar.html.erb
  app/views/stories/_sign_in_invitation.html.erb
Labels: PR: reviewed-approved

#4340 Fix invalid anchored links due to "//" prefix.
  app/lib/redcarpet/render/html_rouge.rb
  spec/labor/markdown_parser_spec.rb
Labels: PR: reviewed-approved

#4319 Fix eslint issues in initializeCommentDate.js
  app/assets/javascripts/initializers/initializeCommentDate.js
Labels: PR: reviewed-approved

#4320 Fix eslint issues in initializeCommentPreview.js
  app/assets/javascripts/initializers/initializeCommentPreview.js
Labels: PR: reviewed-approved

#4329 Fix eslint issues in initializeSettings.js
  app/assets/javascripts/initializers/initializeSettings.js
Labels: PR: reviewed-approved

#4281 Fix broken job specs
  spec/jobs/articles/bust_cache_job_spec.rb
  spec/jobs/articles/detect_human_language_job_spec.rb
  spec/jobs/articles/score_calc_job_spec.rb
  spec/jobs/articles/update_main_image_background_hex_job_spec.rb
  spec/jobs/comments/calculate_score_job_spec.rb
  spec/jobs/comments/create_id_code_job_spec.rb
  spec/jobs/comments/send_email_notification_job_spec.rb
  spec/jobs/comments/touch_user_job_spec.rb
  spec/jobs/pro_memberships/populate_history_job_spec.rb
  spec/jobs/users/bust_cache_job_spec.rb
  spec/jobs/users/resave_articles_job_spec.rb
  spec/jobs/users/subscribe_to_mailchimp_newsletter_job_spec.rb
Labels: PR: reviewed-approved

#4248 Simplify key codes expression in Tags component
  app/javascript/shared/components/__tests__/tags.test.jsx
  app/javascript/shared/components/tags.jsx
Labels: PR: reviewed-approved

#4182 Dark-Theme: remove white background ChatMessage username link
  app/assets/stylesheets/chat.scss
Labels: PR: reviewed-approved

#4345 Windows Docs: Updated PostgreSQL Section
  docs/installation/windows.md
Labels: PR: reviewed-approved

#4346 VS Code Settings Update / Frontend Debug Documentation
  .vscode/extensions.json
  .vscode/launch.json
  docs/.static/vscode_launch_debugger.png
  docs/frontend/debugging.md
  docs/frontend/readme.md
Labels: PR: reviewed-approved

#4267 Fix ESLint errors in initializeBodyData.js
  app/assets/javascripts/initializers/initializeBodyData.js
Labels: PR: reviewed-approved

#4348 Refactor: BodyPreview.jsx
  app/javascript/article-form/elements/bodyPreview.jsx
Labels: PR: reviewed-approved

#4351 Refactor classified_listings.rb
  app/models/classified_listing.rb
Labels: PR: reviewed-approved

#4341 Add a clearer error message when link tag contains non-article URL
  app/liquid_tags/link_tag.rb
  spec/liquid_tags/liquid/raw_spec.rb
Labels: PR: reviewed-approved

#3086 Fixing image upload button in comment form.
  app/assets/stylesheets/comments.scss
Labels: PR: reviewed-approved

#4309 Routine rubocop fixes after gem update
  .rubocop.yml
  .rubocop_todo.yml
  app/labor/hex_comparer.rb
  config/initializers/slack_notifier.rb
  spec/labor/badge_rewarder_spec.rb
  spec/models/comment_spec.rb
  spec/models/notification_spec.rb
  spec/requests/api/v0/articles_spec.rb
Labels: PR: reviewed-approved

#4251 #4129 Reduce Dockerfile size
  .dockerignore
  Dockerfile
  docker-compose.yml
  docker-entrypoint.sh
Labels: PR: reviewed-approved

#4339 Add tag rules to article v2 editor
  app/assets/stylesheets/classified_listings.scss
  app/assets/stylesheets/preact/article-form.scss
  app/javascript/article-form/__tests__/__snapshots__/articleForm.test.jsx.snap
  app/javascript/article-form/articleForm.jsx
  app/javascript/article-form/elements/__tests__/__snapshots__/tags.test.jsx.snap
  app/javascript/shared/components/tags.jsx
  app/models/tag.rb
  app/views/articles/_v2_form.html.erb
Labels: PR: reviewed-approved

#4362 Remove unused import
  app/javascript/chat/article.jsx
Labels: PR: reviewed-approved

#4353 Add post as an alias to the link liquid tag
  app/liquid_tags/link_tag.rb
  app/views/pages/_editor_guide_text.html.erb
  spec/liquid_tags/link_tag_spec.rb
Labels: PR: reviewed-approved

#4360 Add a sentence to clarify GitHub Authentication
  docs/backend/auth-github.md
Labels: PR: reviewed-approved

#4359 remove unused variable and querySelector method in initializeBodyData.js
  app/assets/javascripts/initializers/initializeBodyData.js
Labels: PR: reviewed-approved

#4370 Add todayilearned as a flare tag
  app/labor/flare_tag.rb
Labels: PR: reviewed-approved

#4374 Fixed a typo
  docs/frontend/debugging.md
Labels: PR: reviewed-approved

#4306 Prepend non-url paths with https://dev.to instead of just https
  app/lib/redcarpet/render/html_rouge.rb
  spec/labor/markdown_parser_spec.rb
Labels: PR: reviewed-approved

#4376 Add Z-Index to Editor Image Upload Container
  app/assets/stylesheets/comments.scss
Labels: PR: reviewed-approved

#4371 macOS installatoin guide: add two possible problems + solutions
  docs/installation/mac.md
Labels: PR: reviewed-approved

#4368 Centre with flex rather than padding
  app/assets/stylesheets/settings.scss
Labels: PR: reviewed-approved

#4352 Refactor: moreConfig.jsx
  app/javascript/article-form/elements/moreConfig.jsx
Labels: PR: reviewed-approved

#4363 Resolve linting issue in app/assets/javascript/sendFetch.js
  app/assets/javascripts/.eslintrc.js
  app/assets/javascripts/utilities/sendFetch.js
Labels: PR: reviewed-approved

#4391 Test: add test for ItemListItem and ItemListItemArchiveButton
  app/javascript/src/components/ItemList/__tests__/ItemListItem.test.jsx
  app/javascript/src/components/ItemList/__tests__/ItemListItemArchiveButton.test.jsx
Labels: PR: reviewed-approved

#4394 Add anarchism.space as a mastodon instance
  app/lib/constants.rb
Labels: PR: reviewed-approved

#4347 preview of organization logo design on settings
  app/views/shared/_logo_design.html.erb
  app/views/users/_org_admin.html.erb
  app/views/users/_profile.html.erb
Labels: PR: reviewed-approved

#4361 Update the docs readme with instructions [ci skip]
  docs/contributing.md
  docs/readme.md
Labels: PR: reviewed-approved

#4254 Remove unused onboarding files
  app/assets/stylesheets/onboarding.scss
  app/assets/stylesheets/preact/onboarding-modal.scss
  app/javascript/src/Onboarding.jsx
  app/javascript/src/__tests__/Onboarding.test.jsx
  app/javascript/src/__tests__/__snapshots__/Onboarding.test.jsx.snap
  app/javascript/src/components/ItemList/ItemListTags.jsx
  app/javascript/src/components/OnboardingArticle.jsx
  app/javascript/src/components/OnboardingArticles.jsx
  app/javascript/src/components/OnboardingFollowTags.jsx
  app/javascript/src/components/OnboardingFollowUsers.jsx
  app/javascript/src/components/OnboardingProfile.jsx
  app/javascript/src/components/OnboardingSingleTag.jsx
  app/javascript/src/components/OnboardingTags.jsx
  app/javascript/src/components/OnboardingUsers.jsx
  app/javascript/src/components/OnboardingWelcome.jsx
  app/javascript/src/components/OnboardingWelcomeThread.jsx
  app/javascript/src/components/__stories__/OnboardingArticle.stories.jsx
  app/javascript/src/components/__stories__/OnboardingArticles.stories.jsx
  app/javascript/src/components/__stories__/OnboardingWelcome.stories.jsx
  app/javascript/src/components/__stories__/OnboardingWelcomeThread.stories.jsx
  app/javascript/src/components/__tests__/OnboardingFollowTags.test.jsx
  app/javascript/src/components/__tests__/OnboardingFollowUsers.test.jsx
  app/javascript/src/components/__tests__/OnboardingSingleTag.test.jsx
  app/javascript/src/components/__tests__/OnboardingUsers.test.jsx
  app/javascript/src/components/__tests__/OnboardingWelcome.test.jsx
  app/javascript/src/components/__tests__/OnboardingWelcomeThread.test.jsx
  app/javascript/src/components/__tests__/__snapshots__/OnboardingFollowTags.test.jsx.snap
  app/javascript/src/components/__tests__/__snapshots__/OnboardingFollowUsers.test.jsx.snap
  app/javascript/src/components/__tests__/__snapshots__/OnboardingSingleTag.test.jsx.snap
  app/javascript/src/components/__tests__/__snapshots__/OnboardingUsers.test.jsx.snap
  app/javascript/src/components/__tests__/__snapshots__/OnboardingWelcome.test.jsx.snap
  app/javascript/src/components/__tests__/__snapshots__/OnboardingWelcomeThread.test.jsx.snap
  app/javascript/src/utils/getUnopenedChannels.jsx
  app/javascript/src/utils/pusher.js
Labels: PR: reviewed-approved

#4413 Update feed to have popular posts sink a bit faster
  app/black_box/black_box.rb
  spec/black_box/black_box_spec.rb
Labels: PR: unreviewed

#4414 Fix eslint errors in JavaScript initializers
  app/assets/javascripts/initializers/initializeAllTagEditButtons.js
  app/assets/javascripts/initializers/initializeArchivedPostFilter.js
  app/assets/javascripts/initializers/initializeArticleDate.js
Labels: PR: reviewed-approved

#4364 Internal article: change display to flex and adjust code to remove the extra characters
  app/views/internal/articles/_individual_article.html.erb
  app/views/layouts/internal.html.erb
Labels: PR: reviewed-approved

#4253 Fix eslint issues in app/javascript/listings
  app/javascript/.eslintrc.js
  app/javascript/listings/__tests__/__snapshots__/listingDashboard.test.jsx.snap
  app/javascript/listings/elements/categories.jsx
  app/javascript/listings/elements/contactViaConnect.jsx
  app/javascript/listings/elements/expireDate.jsx
  app/javascript/listings/elements/orgSettings.jsx
  app/javascript/listings/listingDashboard.jsx
  app/javascript/listings/listingForm.jsx
  app/javascript/listings/listings.jsx
  app/javascript/listings/singleListing.jsx
Labels: PR: reviewed-approved

#4418 Eslint fix: for sidebarwidget pack, sidebarwidget and sidebaruser
  app/javascript/packs/sidebarWidget.jsx
  app/javascript/sidebar-widget/SidebarWidget.jsx
  app/javascript/sidebar-widget/sidebarUser.jsx
Labels: PR: reviewed-approved

#4437 remove a space and refactor conditions
  app/views/internal/articles/_individual_article.html.erb
Labels: PR: reviewed-approved

#4452 Remove unused import and unused props
  app/javascript/onboarding/components/ClosingSlide.jsx
Labels: PR: reviewed-approved

#4447 Change branching naming scheme for PRs [ci skip]
  CONTRIBUTING.md
Labels: PR: reviewed-approved

#4261 Fix eslint errors for jsx files in app/javascript/src/components/
  app/javascript/src/components/ItemList/ItemListItem.jsx
  app/javascript/src/components/ItemList/ItemListTags.jsx
  app/javascript/src/components/Search/__tests__/SearchForm.test.jsx
  app/javascript/src/components/Search/__tests__/__snapshots__/SearchForm.test.jsx.snap
  app/javascript/src/components/common-prop-types/user-prop-types.js
  docs/readme.md
Labels: PR: reviewed-approved

#4317 Added ChatChannels::IndexingJob
  app/jobs/chat_channels/index_job.rb
  app/models/message.rb
  spec/jobs/chat_channels/index_job_spec.rb
Labels: PR: reviewed-approved

#4439 Technical overview docs: move product name/link to beginning of line
  docs/technical-overview.md
Labels: PR: reviewed-approved

#4453 Test: add test for errors, mainimage and notice
  app/javascript/article-form/elements/__tests__/__snapshots__/errors.test.jsx.snap
  app/javascript/article-form/elements/__tests__/__snapshots__/mainImage.test.jsx.snap
  app/javascript/article-form/elements/__tests__/__snapshots__/notice.test.jsx.snap
  app/javascript/article-form/elements/__tests__/errors.test.jsx
  app/javascript/article-form/elements/__tests__/mainImage.test.jsx
  app/javascript/article-form/elements/__tests__/notice.test.jsx
Labels: PR: reviewed-approved

#4417 Improve error message when creating article using API
  app/controllers/api/v0/articles_controller.rb
  spec/requests/api/v0/articles_spec.rb
Labels: PR: reviewed-approved

#4442 update initializePodcastPlayback muteUnmute to use ternaries
  app/assets/javascripts/initializers/initializePodcastPlayback.js
Labels: PR: reviewed-approved

#4420 Fixed Leave organization not working (#4387)
  app/views/users/_org_member.html.erb
  config/routes.rb
  spec/system/organization/user_leaves_an_organization_spec.rb
Labels: PR: reviewed-approved

#4393 Add views count for authenticated users articles [#4250]
  app/views/api/v0/articles/me.json.jbuilder
  docs/api_v0.yml
Labels: PR: reviewed-approved, area: api-v0

#4458 Fix broken error interface in Article creation API
  app/controllers/api/v0/articles_controller.rb
  spec/requests/api/v0/articles_spec.rb
Labels: PR: reviewed-approved

#4454 Add info about bumping API version to docs.dev
  CONTRIBUTING.md
  docs/contributing_api.md
  docs/getting-started/pull-request.md
Labels: PR: reviewed-approved

#4446 Fix JavaScript Console errors in /Comments sub-page of any article
  app/assets/javascripts/initializers/initializeCommentDropdown.js
Labels: PR: reviewed-approved

#4366 Removed unused methods _without_delay
  app/labor/rate_limit_checker.rb
  app/models/article.rb
  app/models/badge_achievement.rb
  app/models/mention.rb
  app/models/notification.rb
  app/models/user.rb
  spec/models/notification_spec.rb
  spec/models/user_spec.rb
  spec/requests/articles/articles_update_spec.rb
  spec/requests/internal/users_spec.rb
  spec/requests/notifications_spec.rb
  spec/services/notifications/tag_adjustment_notification/send_spec.rb
Labels: PR: merged

#4459 API: docs update to add error info and other small fixes [ci skip]
  docs/api_v0.yml
Labels: PR: reviewed-approved

#4461 Fix some strange wordings on the pro dashboard
  app/views/dashboards/pro.html.erb
Labels: PR: reviewed-approved

#4392 Fix post title going out of the box (#4383)
  app/assets/stylesheets/article-show.scss
  app/assets/stylesheets/articles.scss
  app/assets/stylesheets/more-articles.scss
Labels: PR: reviewed-approved

#4416 Refactor initializeTimeFixer.js
  app/assets/javascripts/initializers/initializeTimeFixer.js
  app/views/events/_event.html.erb
Labels: PR: reviewed-approved

#4476 Persist Canvas State on Resizing
  public/offline.html
Labels: PR: reviewed-approved

#4467 Remove unused function
  app/javascript/packs/Onboarding.jsx
Labels: PR: reviewed-approved

#4451 Upgrade Ruby to 2.6.5
  .ruby-version
  .travis.yml
  Dockerfile
  Gemfile
  Gemfile.lock
  README.md
  docs/installation/linux.md
  docs/installation/mac.md
  docs/installation/windows.md
Labels: PR: reviewed-approved

#4468 [docs] Update "Installing on Linux" docs with more error messages
  docs/installation/linux.md
Labels: PR: reviewed-approved

#4479 Increased redirects limit when fetching podcasts
  app/services/podcasts/feed.rb
  spec/services/podcasts/feed_spec.rb
Labels: PR: reviewed-approved

#4478 Refactor app/javascript/article-form/elements/bodyPreview.jsx
  app/javascript/article-form/elements/bodyPreview.jsx
Labels: PR: reviewed-approved

#4484 Remove unused import
  app/javascript/onboarding/components/FollowUsers.jsx
Labels: PR: reviewed-approved

#4444 Events page: add specs
  spec/requests/events_spec.rb
Labels: PR: reviewed-approved

#4481 Mention `POSTGRES_VERSION` variable in documentation
  docs/installation/docker.md
Labels: PR: reviewed-approved

#4492 Refactor UsersController#handle_settings_tab
  app/controllers/users_controller.rb
Labels: PR: reviewed-approved

#4279 fix scrollheight calculation by using scrollable element instead of document element
  app/assets/javascripts/initializers/initScrolling.js.erb
Labels: PR: reviewed-approved

#4448 Refactor: component Tags.jsx
  app/javascript/shared/components/tags.jsx
Labels: PR: reviewed-approved

#4217 Fix eslint issues in article-form's jsx files
  app/javascript/article-form/__tests__/articleForm.test.jsx
  app/javascript/article-form/articleForm.jsx
  app/javascript/article-form/elements/__tests__/__snapshots__/errors.test.jsx.snap
  app/javascript/article-form/elements/__tests__/__snapshots__/mainImage.test.jsx.snap
  app/javascript/article-form/elements/__tests__/tags.test.jsx
  app/javascript/article-form/elements/bodyPreview.jsx
  app/javascript/article-form/elements/errors.jsx
  app/javascript/article-form/elements/mainImage.jsx
  app/javascript/article-form/elements/moreConfig.jsx
  app/javascript/article-form/elements/orgSettings.jsx
Labels: PR: reviewed-approved

#4505 Fix article submission error
  app/javascript/article-form/actions.js
  app/javascript/article-form/articleForm.jsx
Labels: PR: reviewed-approved

#4530 Add Molly Struve to Core Team Members
  README.md
Labels: PR: reviewed-approved

#4508 Ignore .tool-versions file
  .gitignore
Labels: PR: reviewed-approved

#4510 Little placeholder tweak to encourage using https
  app/views/users/_org_admin.html.erb
  app/views/users/_org_non_member.html.erb
Labels: PR: reviewed-approved

#4531 Only show hello-dev.js in production
  app/views/layouts/_footer.html.erb
Labels: PR: reviewed-approved

#4495 Move all internals request spec under internal namespace
  spec/requests/internal/buffer_updates_spec.rb
  spec/requests/internal/events_spec.rb
  spec/requests/internal/feedback_messages_spec.rb
  spec/requests/internal/reactions_spec.rb
  spec/requests/internal/users_banish_spec.rb
  spec/requests/internal/users_spec.rb
  spec/requests/internal_buffer_updates_spec.rb
  spec/requests/internal_users_spec.rb
Labels: PR: reviewed-approved
