Repository forem/forem, pull requests merged in 2019-09, with the labels that each got.

#3540 Listing Drafts and Deletion
  app/assets/stylesheets/classified_listings.scss
  app/assets/stylesheets/dashboard.scss
  app/assets/stylesheets/delete-confirm.scss
  app/assets/stylesheets/minimal.scss
  app/assets/stylesheets/scaffolds.scss
  app/controllers/classified_listings_controller.rb
  app/controllers/concerns/classified_listings_toolkit.rb
  app/javascript/listings/__tests__/__snapshots__/listingDashboard.test.jsx.snap
  app/javascript/listings/dashboard/listingRow.jsx
  app/javascript/listings/dashboard/rowElements/actionButtons.jsx
  app/javascript/listings/dashboard/rowElements/listingDate.jsx
  app/javascript/listings/dashboard/rowElements/location.jsx
  app/javascript/listings/dashboard/rowElements/tags.jsx
  app/javascript/listings/elements/contactViaConnect.jsx
  app/javascript/listings/listingDashboard.jsx
  app/javascript/listings/listingForm.jsx
  app/javascript/listings/listings.jsx
  app/models/classified_listing.rb
  app/policies/classified_listing_policy.rb
  app/views/classified_listings/_form.html.erb
  app/views/classified_listings/dashboard.html.erb
  app/views/classified_listings/delete_confirm.html.erb
  app/views/classified_listings/edit.html.erb
  app/views/classified_listings/new.html.erb
  app/views/credits/index.html.erb
  app/views/dashboards/show.html.erb
  app/views/internal/classified_listings/index.html.erb
  config/routes.rb
  spec/requests/classified_listings_spec.rb
Labels: PR: reviewed-approved, area: listings

#3890 Rename uncommunicative variables
  app/labor/badge_rewarder.rb
  app/labor/bufferizer.rb
  app/labor/cache_buster.rb
  app/labor/flare_tag.rb
  app/labor/html_cleaner.rb
  app/labor/mailchimp_bot.rb
  app/labor/markdown_fixer.rb
  app/labor/markdown_parser.rb
  app/liquid_tags/codepen_tag.rb
  app/liquid_tags/codesandbox_tag.rb
  app/liquid_tags/glitch_tag.rb
  app/liquid_tags/jsfiddle_tag.rb
  app/liquid_tags/stackblitz_tag.rb
  app/models/chat_channel.rb
  app/models/comment.rb
  app/models/identity.rb
  app/models/message.rb
  app/models/notification.rb
  app/models/organization.rb
  app/models/tag.rb
  app/models/tweet.rb
  app/models/user.rb
  app/services/credits/ledger.rb
  app/services/notifications/new_follower/send.rb
  app/services/notifications/reactions/send.rb
Labels: PR: reviewed-approved

#3899 Fix flaky listings specs
  spec/liquid_tags/classified_listing_tag_spec.rb
  spec/requests/classified_listings_spec.rb
Labels: PR: reviewed-approved

#3923 update vscode settings
  .vscode/settings.json
Labels: PR: reviewed-approved

#3922 Fix rubocop complaints
  app/liquid_tags/kotlin_tag.rb
  spec/liquid_tags/kotlin_tag_spec.rb
  spec/system/user_visits_downloads_page_spec.rb
Labels: PR: reviewed-approved

#3903 Adding pixel limit to Editors Guide
  app/views/pages/_editor_guide_text.html.erb
Labels: PR: reviewed-approved

#3902 Use a clearer method name to render chat channel
  app/controllers/chat_channels_controller.rb
Labels: PR: reviewed-approved

#3886 Re-sort example Algolia keys
  config/sample_application.yml
Labels: PR: reviewed-approved

#3853 Update PingAdmins to triggering event
  app/controllers/comments_controller.rb
  app/controllers/image_uploads_controller.rb
  app/jobs/rate_limit_checker_job.rb
  app/labor/rate_limit_checker.rb
  app/services/articles/creator.rb
  app/services/ping_admins.rb
  spec/jobs/rate_limit_checker_job_spec.rb
  spec/labor/rate_limit_checker_spec.rb
Labels: PR: reviewed-approved

#3901 Webhooks: API fixes and docs
  app/controllers/api/v0/webhooks_controller.rb
  app/models/webhook/endpoint.rb
  app/views/api/v0/webhooks/show.json.jbuilder
  docs/api_v0.yml
  spec/factories/webhook_endpoints.rb
  spec/models/webhook/endpoint_spec.rb
  spec/requests/api/v0/webhooks_spec.rb
Labels: PR: reviewed-approved

#3931 Add commas and fix split infinitive
  README.md
Labels: PR: reviewed-approved

#3930 Remove a link to a missing section in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: PR: reviewed-approved

#3934 Remove homepage placement for bronze and silver
  app/views/partnerships/_bronze_sponsor_copy.html.erb
  app/views/partnerships/_silver_sponsor_copy.html.erb
  app/views/partnerships/index.html.erb
Labels: PR: unreviewed

#3904 Roles docs: Fix aggregated query to avoid deprecation
  docs/backend/roles.md
Labels: PR: reviewed-approved

#3927 Reading list: set default reading time to 1 minute
  app/javascript/src/components/ItemList/ItemListItem.jsx
  app/javascript/src/components/ItemList/__tests__/ItemListItem.test.jsx
  app/javascript/src/components/ItemList/__tests__/__snapshots__/ItemListItem.test.jsx.snap
Labels: PR: reviewed-approved

#3888 Update and format console copy [ci skip]
  app/assets/javascripts/hello-dev.js
Labels: PR: reviewed-approved

#3935 Modify headers to allow embed
  app/controllers/liquid_embeds_controller.rb
Labels: PR: unreviewed

#3885 Add Setup for storybook.dev.to
  docs/deploy-script.js
  netlify.toml
Labels: PR: reviewed-approved

#3873 Update article specs to include missing dependent: :destroy (#3365)
  spec/models/article_spec.rb
Labels: PR: reviewed-approved

#3907 Simplify the images uploading code
  app/controllers/image_uploads_controller.rb
Labels: PR: reviewed-approved

#3790 Escape raw tags in codeblocks properly
  app/labor/markdown_parser.rb
  spec/labor/markdown_parser_spec.rb
Labels: PR: reviewed-approved

#3894 Update notifications reply form to use theme colors
  app/assets/stylesheets/notifications.scss
Labels: PR: reviewed-approved

#3940 Use make build instead of only gitdocs command
  docs/deploy-script.js
Labels: PR: reviewed-approved

#3937 API: /api/articles/me defaults to published articles
  app/controllers/api/v0/articles_controller.rb
  app/models/article.rb
  config/routes.rb
  docs/api_v0.yml
  spec/requests/api/v0/articles_spec.rb
Labels: PR: reviewed-approved

#3896 Make report notification use theme colors
  app/assets/stylesheets/feedback_messages.scss
Labels: PR: reviewed-approved

#3897 Hide scrollbars in the editor textarea
  app/assets/stylesheets/preact/article-form.scss
Labels: PR: reviewed-approved

#3960 Replace "DEV access token" with "DEV API key"
  app/controllers/api_secrets_controller.rb
  app/views/users/_account.html.erb
  docs/api_v0.yml
Labels: PR: reviewed-approved

#3959 Send JSON 404 response to API error routes
  app/controllers/application_controller.rb
  config/routes.rb
  spec/requests/api/v0/articles_spec.rb
Labels: PR: reviewed-approved

#3943 Use explicit email domain for badge email links and minor cleanup
  app/views/mailers/notify_mailer/new_badge_email.html.erb
  app/views/mailers/notify_mailer/new_badge_email.text.erb
  app/views/pages/live.html.erb
Labels: PR: reviewed-approved

#3964 Revert changes as a hotfix
  app/controllers/application_controller.rb
  config/routes.rb
  spec/requests/api/v0/articles_spec.rb
Labels: PR: unreviewed

#3938 Rescue InvalidURIError when busting cache
  app/labor/cache_buster.rb
Labels: PR: reviewed-approved

#3962 Rake task for fixing credit counter cache
  lib/tasks/fetch.rake
Labels: PR: reviewed-approved

#3958 Images uploads: fix UI for multiple images
  app/assets/stylesheets/preact/article-form.scss
  app/javascript/article-form/__tests__/__snapshots__/articleForm.test.jsx.snap
  app/javascript/article-form/articleForm.jsx
  app/javascript/article-form/elements/imageManagement.jsx
Labels: PR: reviewed-approved

#3948 Paginate notifications
  app/assets/javascripts/initializers/initNotifications.js
  app/assets/stylesheets/_mixins.scss
  app/assets/stylesheets/item-list.scss
  app/assets/stylesheets/notifications.scss
  app/controllers/notifications_controller.rb
  app/views/notifications/_comment.html.erb
  app/views/notifications/_notifications_list.html.erb
  app/views/notifications/index.html.erb
  spec/requests/notifications_spec.rb
Labels: PR: reviewed-approved

#3872 Dispatch events to the webhook endpoints #3715
  Gemfile
  Gemfile.lock
  app/controllers/admin/articles_controller.rb
  app/controllers/articles_controller.rb
  app/helpers/application_helper.rb
  app/helpers/social_image_helper.rb
  app/jobs/webhook/dispatch_event_job.rb
  app/models/webhook/event.rb
  app/serializers/webhook/article_destroyed_serializer.rb
  app/serializers/webhook/article_serializer.rb
  app/serializers/webhook/event_serializer.rb
  app/serializers/webhook/user_serializer.rb
  app/services/articles/creator.rb
  app/services/articles/destroyer.rb
  app/services/articles/updater.rb
  app/services/webhook/dispatch_event.rb
  app/services/webhook/payload_adapter.rb
  app/view_objects/articles/social_image.rb
  app/view_objects/cloud_cover_url.rb
  config/application.rb
  config/environments/development.rb
  config/environments/production.rb
  config/environments/test.rb
  spec/jobs/webhook/dispatch_event_job_spec.rb
  spec/models/webhook/event_spec.rb
  spec/requests/articles/articles_create_spec.rb
  spec/requests/articles/articles_update_spec.rb
  spec/services/articles/creator_spec.rb
  spec/services/articles/destroyer_spec.rb
  spec/services/articles/updater_spec.rb
  spec/services/webhook/dispatch_event_spec.rb
  spec/services/webhook/payload_adapter_spec.rb
Labels: PR: unreviewed

#3966 Add missing commas [ci skip]
  CONTRIBUTING.md
Labels: PR: reviewed-approved

#3868 Make markdown's mention work with italic
  app/labor/markdown_parser.rb
  spec/labor/markdown_parser_spec.rb
Labels: PR: reviewed-approved

#3956 Update image of Algolia backend docs
  docs/backend/algolia.md
Labels: PR: reviewed-approved

#3972 Webhook events: use a sortable unique ID for the event_id
  Gemfile
  Gemfile.lock
  app/models/webhook/event.rb
  app/serializers/webhook/event_serializer.rb
  app/services/secrets/generator.rb
  spec/models/webhook/event_spec.rb
  spec/services/secrets/generator_spec.rb
Labels: PR: reviewed-approved

#3987 Fix edge case for rewarding when unpublished
  app/labor/badge_rewarder.rb
  spec/labor/badge_rewarder_spec.rb
Labels: PR: reviewed-approved

#3944 Fixes encoding of special characters on organization page rendering
  app/controllers/organizations_controller.rb
  app/views/articles/_user_metadata.html.erb
  app/views/organizations/show.html.erb
  app/views/users/_profile_header.html.erb
  spec/requests/user_profile_spec.rb
Labels: PR: reviewed-approved

#3989 Remove commented code and tests
  app/controllers/api/v0/comments_controller.rb
  app/controllers/api/v0/tags_controller.rb
  app/controllers/chat_channels_controller.rb
  app/controllers/comments_controller.rb
  app/controllers/internal/articles_controller.rb
  app/controllers/internal/reactions_controller.rb
  spec/models/article_spec.rb
  spec/requests/pusher_auth_spec.rb
Labels: PR: reviewed-approved

#3997 Show webhooks list in internal
  app/controllers/internal/webhook_endpoints_controller.rb
  app/views/internal/shared/_navbar.html.erb
  app/views/internal/webhook_endpoints/index.html.erb
  app/views/layouts/internal.html.erb
  config/routes.rb
Labels: PR: reviewed-approved

#3986 Notifications: increase efficiency and fix pagination offset issue
  app/assets/javascripts/initializers/initNotifications.js
  app/assets/stylesheets/notifications.scss
  app/controllers/notifications_controller.rb
  app/models/notification.rb
  app/views/notifications/_notifications_list.html.erb
  app/views/notifications/index.html.erb
Labels: PR: reviewed-approved

#3998 Fix notifications past aggregation query logic
  app/controllers/notifications_controller.rb
  app/models/notification.rb
Labels: PR: unreviewed

#4008 Dispatch events only to the corresponding user endpoints
  app/services/webhook/dispatch_event.rb
  spec/requests/articles/articles_create_spec.rb
  spec/requests/articles/articles_update_spec.rb
  spec/services/webhook/dispatch_event_spec.rb
Labels: PR: reviewed-approved

#3991 Generate doorkeeper's view
  app/views/doorkeeper/applications/_delete_form.html.erb
  app/views/doorkeeper/applications/_form.html.erb
  app/views/doorkeeper/applications/edit.html.erb
  app/views/doorkeeper/applications/index.html.erb
  app/views/doorkeeper/applications/new.html.erb
  app/views/doorkeeper/applications/show.html.erb
  app/views/doorkeeper/authorizations/error.html.erb
  app/views/doorkeeper/authorizations/new.html.erb
  app/views/doorkeeper/authorizations/show.html.erb
  app/views/doorkeeper/authorized_applications/_delete_form.html.erb
  app/views/doorkeeper/authorized_applications/index.html.erb
  app/views/layouts/doorkeeper/admin.html.erb
  app/views/layouts/doorkeeper/application.html.erb
Labels: PR: unreviewed

#4006 fixed links in badge email
  app/views/mailers/notify_mailer/new_badge_email.html.erb
Labels: PR: reviewed-approved

#3988 Replace try with safe navigation operator
  app/models/tweet.rb
Labels: PR: reviewed-approved

#3993 Internal Listings: Filter by Category
  app/controllers/internal/classified_listings_controller.rb
  app/views/internal/classified_listings/index.html.erb
Labels: PR: reviewed-approved, area: internal

#4009 Add new mod links and tooling
  app/assets/images/emoji/emoji-one-sloth.png
  app/assets/javascripts/initializePage.js.erb
  app/assets/javascripts/initializers/initializeAllTagEditButtons.js
  app/assets/stylesheets/scaffolds.scss
  app/assets/stylesheets/sidebar-data.scss
  app/controllers/async_info_controller.rb
  app/controllers/moderations_controller.rb
  app/decorators/user_decorator.rb
  app/labor/assign_tag_moderator.rb
  app/models/reaction.rb
  app/models/user.rb
  app/views/articles/_sidebar_nav.html.erb
  app/views/articles/tags/_sidebar.html.erb
  app/views/moderations/_reactions.html.erb
  app/views/moderations/index.html.erb
  config/routes.rb
  spec/models/user_spec.rb
  spec/requests/moderations_spec.rb
Labels: PR: unreviewed

#4017 Use build_stubbed in Policy specs
  spec/policies/admin_policy_spec.rb
  spec/policies/api_secret_policy_spec.rb
  spec/policies/article_policy_spec.rb
  spec/policies/block_policy_spec.rb
  spec/policies/buffer_update_policy_spec.rb
  spec/policies/chat_channel_membership_policy_spec.rb
  spec/policies/chat_channel_policy_spec.rb
  spec/policies/comment_policy_spec.rb
  spec/policies/follow_policy_spec.rb
  spec/policies/github_repo_policy_spec.rb
  spec/policies/html_variant_policy_spec.rb
  spec/policies/image_upload_policy_spec.rb
  spec/policies/organization_policy_spec.rb
  spec/policies/reaction_policy_spec.rb
  spec/policies/stripe_active_card_policy_spec.rb
  spec/policies/stripe_subscription_policy_spec.rb
  spec/policies/tag_policy_spec.rb
  spec/policies/user_policy_spec.rb
Labels: PR: reviewed-approved

#3328 Resolve inconsistent reading time estimate
  app/assets/javascripts/utilities/buildArticleHTML.js.erb
  app/views/articles/_algolia_search.html.erb
Labels: PR: reviewed-approved

#4046 Send only public events to the webhook endpoints #3715
  app/services/articles/creator.rb
  app/services/articles/destroyer.rb
  app/services/articles/updater.rb
  spec/requests/articles/articles_create_spec.rb
  spec/services/articles/creator_spec.rb
  spec/services/articles/destroyer_spec.rb
  spec/services/articles/updater_spec.rb
Labels: PR: reviewed-approved

#4049 Fix reading time logic
  app/assets/javascripts/utilities/buildArticleHTML.js.erb
Labels: PR: reviewed-approved

#4013 Api endpoint for user webhooks
  app/controllers/api/v0/webhooks_controller.rb
  app/views/api/v0/webhooks/index.json.jbuilder
  config/routes.rb
  spec/requests/api/v0/webhooks_spec.rb
Labels: PR: reviewed-approved

#4028 Move index.delay.delete_object calls to ActiveJob
  app/jobs/search/remove_from_index_job.rb
  app/models/article.rb
  app/models/comment.rb
  app/models/user.rb
  spec/jobs/search/remove_from_index_job_spec.rb
Labels: PR: reviewed-approved

#4053 Switch to CDN for iframe resizer
  app/javascript/packs/iframeResizerFile.js
  app/views/liquid_embeds/show.html.erb
Labels: PR: reviewed-approved

#4056 API: add doc for webhooks index
  app/views/api/v0/webhooks/index.json.jbuilder
  app/views/api/v0/webhooks/show.json.jbuilder
  docs/api_v0.yml
Labels: PR: reviewed-approved

#4059 Generate HTTPS urls with Rails url helpers
  config/environments/production.rb
Labels: PR: unreviewed

#4062 Fix delete container alignment
  app/assets/stylesheets/scaffolds.scss
Labels: PR: reviewed-approved

#4060 Added association between webhook_endpoints and oauth apps
  app/controllers/api/v0/webhooks_controller.rb
  app/models/webhook/endpoint.rb
  db/migrate/20190918104106_add_oauth_application_id_to_webhook_endpoints.rb
  db/schema.rb
  spec/requests/api/v0/webhooks_spec.rb
Labels: PR: reviewed-approved

#4051 Fix mention's inconsistent hyperlink
  app/labor/markdown_parser.rb
  spec/labor/markdown_parser_spec.rb
Labels: PR: reviewed-approved

#4065 Define Doorkeeper::Application association on webhook_endpoints
  app/models/webhook/endpoint.rb
  config/initializers/doorkeeper.rb
  spec/models/webhook/endpoint_spec.rb
Labels: PR: reviewed-approved

#4067 Change reply notification background color
  app/assets/stylesheets/notifications.scss
Labels: PR: reviewed-approved

#4063 Silence page views log
  config/initializers/timber.rb
Labels: PR: reviewed-approved

#4054 Add no-readme option to GitHub tag
  app/liquid_tags/github_tag/github_readme_tag.rb
  app/views/liquids/_github_readme.html.erb
  app/views/pages/_editor_guide_text.html.erb
  spec/liquid_tags/github_tag/github_readme_tag_spec.rb
Labels: PR: reviewed-approved

#4016 Give interns access to internal articles
  app/controllers/internal/articles_controller.rb
  app/controllers/internal/buffer_updates_controller.rb
  app/models/role.rb
  app/policies/application_policy.rb
  app/policies/internal/article_policy.rb
  app/policies/internal/buffer_update_policy.rb
  spec/policies/internal/article_policy_spec.rb
Labels: PR: unreviewed

#4069 Add more variation to home feed
  app/assets/javascripts/initializers/initializeFetchFollowedArticles.js.erb
  app/black_box/black_box.rb
  app/controllers/stories_controller.rb
  app/views/stories/_main_stories_feed.html.erb
  spec/black_box/black_box_spec.rb
Labels: PR: unreviewed

#4071 Add climate strike widget
  app/views/articles/index.html.erb
Labels: PR: unreviewed

#4075 Fix tags format in Article create API
  docs/api_v0.yml
Labels: PR: reviewed-approved

#3895 Refactor tags components
  app/javascript/article-form/__tests__/__snapshots__/articleForm.test.jsx.snap
  app/javascript/article-form/articleForm.jsx
  app/javascript/article-form/elements/__tests__/__snapshots__/tags.test.jsx.snap
  app/javascript/article-form/elements/__tests__/tags.test.jsx
  app/javascript/article-form/elements/tags.jsx
  app/javascript/listings/listingForm.jsx
  app/javascript/shared/components/tags.jsx
Labels: PR: reviewed-approved

#4022 Move Reaction.create delay calls to ActiveJob (#3136)
  app/controllers/api/v0/reactions_controller.rb
  app/jobs/reactions/create_job.rb
  spec/jobs/reactions/create_job_spec.rb
Labels: PR: reviewed-approved

#4072 Replace ^ and $ with \A and \z in Ruby regexps
  app/helpers/application_helper.rb
  app/liquid_tags/codepen_tag.rb
  app/liquid_tags/glitch_tag.rb
  app/liquid_tags/jsfiddle_tag.rb
  app/liquid_tags/kotlin_tag.rb
  app/liquid_tags/stackblitz_tag.rb
  app/liquid_tags/stackexchange_tag.rb
  app/liquid_tags/tweet_tag.rb
  spec/helpers/application_helper_spec.rb
  spec/liquid_tags/codepen_tag_spec.rb
  spec/liquid_tags/kotlin_tag_spec.rb
  spec/liquid_tags/stackexchange_tag_spec.rb
Labels: PR: reviewed-approved

#4076 Fix opacity issue on low quality comments
  app/assets/stylesheets/comments.scss
Labels: PR: reviewed-approved

#4070 Adjust BufferUpdatesController's authorization
  app/controllers/internal/buffer_updates_controller.rb
  app/models/article.rb
  app/models/buffer_update.rb
  app/models/role.rb
  app/policies/application_policy.rb
  app/policies/internal/article_policy.rb
  app/policies/internal/buffer_update_policy.rb
  spec/models/role_spec.rb
  spec/policies/internal/buffer_update_policy_spec.rb
Labels: PR: reviewed-approved

#4077 fixed Load More button not readable in night theme
  app/assets/stylesheets/_mixins.scss
Labels: PR: reviewed-approved

#3933 Refactor intro slide component
  app/javascript/onboarding/components/IntroSlide.jsx
  app/javascript/onboarding/components/SlideContent.jsx
Labels: PR: unreviewed

#4014 Listings creation and update API
  app/controllers/api/v0/classified_listings_controller.rb
  app/controllers/classified_listings_controller.rb
  app/controllers/concerns/classified_listings_toolkit.rb
  app/models/classified_listing.rb
  app/views/api/v0/articles/index.json.jbuilder
  app/views/api/v0/articles/me.json.jbuilder
  app/views/api/v0/articles/show.json.jbuilder
  app/views/api/v0/classified_listings/_listing.json.jbuilder
  app/views/api/v0/classified_listings/index.json.jbuilder
  app/views/api/v0/classified_listings/show.json.jbuilder
  app/views/api/v0/shared/_organization.json.jbuilder
  app/views/api/v0/shared/_user.json.jbuilder
  app/views/api/v0/webhooks/show.json.jbuilder
  config/routes.rb
  spec/factories/api_secrets.rb
  spec/requests/api/v0/classified_listings_spec.rb
Labels: PR: reviewed-approved

#4066 Doorkeeper default scope
  app/controllers/api/v0/articles_controller.rb
  app/controllers/api/v0/webhooks_controller.rb
  config/initializers/doorkeeper.rb
  config/locales/doorkeeper.en.yml
  spec/requests/api/v0/articles_spec.rb
  spec/requests/api/v0/webhooks_spec.rb
Labels: PR: reviewed-approved

#4102 Cache pro membership
  app/models/pro_membership.rb
  app/models/user.rb
Labels: PR: unreviewed

#3882 Listing Body Markdown Changes
  app/javascript/listings/elements/bodyMarkdown.jsx
  app/labor/markdown_parser.rb
Labels: PR: reviewed-approved, area: listings, javascript, ruby

#4108 Add styling for oauth page
  app/views/doorkeeper/authorizations/new.html.erb
Labels: PR: reviewed-approved

#4107 Refactoring userDetails.jsx removes button code duplication
  app/javascript/chat/userDetails.jsx
Labels: PR: reviewed-approved

#3870 Unsubscribe to notification clicking on selected option (#3800)
  app/javascript/packs/notificationSubscriptionHandler.js
  app/views/articles/_actions.html.erb
Labels: PR: reviewed-approved

#4112 Fix biller spec's zonebie issue
  spec/liquid_tags/classified_listing_tag_spec.rb
  spec/services/pro_memberships/biller_spec.rb
Labels: PR: unreviewed

#4099 Destroy webhook endpoints when user revokes oaurh app access
  app/controllers/oauth/tokens_controller.rb
  app/jobs/webhook/destroy_job.rb
  config/locales/doorkeeper.en.yml
  config/routes.rb
  spec/jobs/webhook/destroy_job_spec.rb
  spec/requests/oauth/tokens_spec.rb
Labels: PR: reviewed-approved

#4113 Add initial functionality for Stackbit on integrations settings tab
  app/assets/stylesheets/settings.scss
  app/decorators/user_decorator.rb
  app/views/users/_integrations.html.erb
  spec/system/user/user_edits_integrations_spec.rb
Labels: PR: unreviewed

#4118 Change stackbit integrations page details
  app/views/users/_integrations.html.erb
Labels: PR: unreviewed

#4109 JS Linting
  app/javascript/packs/colorPicker.js
  app/javascript/packs/notificationSubscriptionHandler.js
Labels: PR: reviewed-approved

#4123 Use server side comments for templates
  app/views/credits/new.html.erb
  app/views/internal/shared/_navbar.html.erb
  app/views/layouts/internal.html.erb
  app/views/notifications/_mention.html.erb
  app/views/pages/code_of_conduct.html.erb
  app/views/pages/faq.html.erb
  app/views/pages/generator.html.erb
  app/views/pages/information.html.erb
  app/views/pages/privacy.html.erb
  app/views/pages/show.html.erb
  app/views/pages/swagnets.html.erb
  app/views/pages/terms.html.erb
  app/views/users/_billing.html.erb
  docs/api_template.hbs
Labels: PR: reviewed-approved

#4122 Do not cache articles notifications "time ago" indication
  app/controllers/notifications_controller.rb
  app/views/notifications/_article.html.erb
Labels: PR: reviewed-approved

#4127 Fix images in chat overflowing outside chat window.
  app/assets/stylesheets/chat.scss
Labels: PR: reviewed-approved

#4119 Fix radio button labels on Report Abuse page
  app/views/feedback_messages/_form.html.erb
Labels: PR: reviewed-approved

#4133 Update rubyzip to 1.3.0 to fix vulnerability
  Gemfile
  Gemfile.lock
  config/initializers/rubyzip.rb
Labels: PR: reviewed-approved

#4141 Require rubyzip
  config/initializers/rubyzip.rb
Labels: PR: reviewed-approved

#4150 Update core team members [ci skip]
  README.md
Labels: PR: reviewed-approved

#4160 Increase length limit for organization URL
  app/views/users/_org_admin.html.erb
Labels: PR: unreviewed
