Repository forem/forem, pull requests merged in 2019-11, with the labels that each got.

#4677 Make The Default Email An Enviroment Variable.
  Envfile
  app/controllers/api_secrets_controller.rb
  app/controllers/users_controller.rb
  app/labor/error_message_cleaner.rb
  app/mailers/application_mailer.rb
  app/mailers/digest_mailer.rb
  app/mailers/pro_membership_mailer.rb
  app/models/organization.rb
  app/views/devise/shared/_authorization_error.html.erb
  app/views/feedback_messages/index.html.erb
  app/views/mailers/notify_mailer/account_deleted_email.html.erb
  app/views/mailers/notify_mailer/account_deleted_email.text.erb
  app/views/moderations/index.html.erb
  app/views/notifications/_notifications_list.html.erb
  app/views/notifications/_tagadjustment.html.erb
  app/views/pages/contact.html.erb
  app/views/pages/swagnets.html.erb
  app/views/podcast_episodes/_sidebar.html.erb
  app/views/users/_account.html.erb
  app/views/users/_publishing_from_rss.html.erb
  app/views/users/edit.html.erb
  app/views/videos/new.html.erb
  spec/mailers/digest_mailer_spec.rb
  spec/mailers/pro_membership_mailer_spec.rb
  spec/requests/user_settings_spec.rb
Labels: PR: reviewed-approved

#4679 Add proper deployment condition
  .travis.yml
Labels: PR: unreviewed

#4676 Use ActiveSupport::Cache::RedisCacheStore As RedisRailsCache
  config/initializers/redis.rb
  config/initializers/redis_rails.rb
  lib/redis_rails_cache.rb
  spec/lib/redis_rails_cache_spec.rb
Labels: PR: unreviewed

#4684 [deploy] Move cached_following_podcasts_ids to Redis
  app/models/user.rb
Labels: PR: reviewed-approved

#4685 Move cached_following_organizations_ids to Redis
  app/models/user.rb
Labels: PR: reviewed-approved

#4688 [deploy] Add guard for block button presence and add theming of profile dropdown
  app/assets/stylesheets/user-profile-header.scss
  app/javascript/profileDropdown/blockButton.js
Labels: PR: unreviewed

#4689 Remove Cacheing for preferred_languages_array [deploy]
  app/models/user.rb
Labels: PR: reviewed-approved

#4617 Listings: fix 'Contact via Connect' checkbox to be checkable [deploy]
  app/javascript/listings/listingForm.jsx
Labels: PR: reviewed-approved

#4692 Add HoneycombClient for sending our own events to Honeycomb
  config/initializers/honeycomb_event_client.rb
  config/initializers/honeycomb_rails.rb
Labels: PR: reviewed-approved

#4690 Move moderator_for_tags Cache Key to Redis
  app/labor/assign_tag_moderator.rb
  app/models/user.rb
Labels: PR: reviewed-approved

#4691 Move has_pro_membership cache to Redis
  app/models/pro_membership.rb
  app/models/user.rb
Labels: PR: reviewed-approved, cache/index

#4694 Move ga daily_random_key to Redis [deploy]
  app/controllers/ga_events_controller.rb
Labels: PR: reviewed-approved, cache/index

#4699 Use libhoney explicitly and group initializers
  Envfile
  Gemfile
  Gemfile.lock
  config/initializers/honeycomb.rb
  config/initializers/honeycomb_event_client.rb
  config/initializers/honeycomb_rails.rb
Labels: PR: reviewed-approved

#4697 Move users' has_trusted_role keys to redis
  app/labor/assign_tag_moderator.rb
  app/models/user.rb
  app/services/moderator/manage_activity_and_roles.rb
Labels: PR: reviewed-approved

#4722 Loosen Codeclimate's duplication rule
  .codeclimate.yml
Labels: PR: reviewed-approved

#4695 Move count_for_reactable-* keys to redis
  app/controllers/api/v0/reactions_controller.rb
  app/controllers/reactions_controller.rb
  app/models/reaction.rb
Labels: PR: reviewed-approved, cache/index

#4696 Move cached_user_reactions-* keys to Redis
  app/controllers/reactions_controller.rb
Labels: PR: reviewed-approved, cache/index

#4709 Moved article_flare_tag to Redis
  app/labor/flare_tag.rb
Labels: PR: reviewed-approved

#4711 Moved reading_list_ids_of_articles to Redis [deploy]
  app/labor/reading_list.rb
Labels: PR: reviewed-approved

#4721 Chat message: return 401 instead of 500 when a channel is blocked [deploy]
  app/controllers/messages_controller.rb
  app/models/message.rb
  spec/models/message_spec.rb
  spec/requests/messages_spec.rb
Labels: PR: reviewed-approved

#4678 Hide a blocked user's content [deploy]
  app/assets/javascripts/initializers/initScrolling.js.erb
  app/assets/javascripts/initializers/initializeFetchFollowedArticles.js.erb
  app/assets/javascripts/utilities/buildArticleHTML.js.erb
  app/assets/javascripts/utilities/buildCommentHTML.js.erb
  app/assets/javascripts/utilities/sendFetch.js
  app/controllers/async_info_controller.rb
  app/javascript/.eslintrc.js
  app/javascript/chat/__tests__/__snapshots__/userDetails.test.jsx.snap
  app/javascript/chat/userDetails.jsx
  app/javascript/contentDisplayPolicy/hideBlockedContent.js
  app/javascript/packs/contentDisplayPolicy.js
  app/javascript/profileDropdown/blockButton.js
  app/views/articles/_single_story.html.erb
  app/views/articles/index.html.erb
  app/views/comments/_comment_proper.html.erb
  app/views/layouts/application.html.erb
  config/routes.rb
  spec/requests/user_blocks_spec.rb
Labels: PR: reviewed-approved

#4302 Fix eslint issues in chat's jsx files
  app/javascript/chat/__tests__/__snapshots__/article.test.jsx.snap
  app/javascript/chat/__tests__/__snapshots__/chat.test.jsx.snap
  app/javascript/chat/__tests__/__snapshots__/compose.test.jsx.snap
  app/javascript/chat/__tests__/__snapshots__/githubRepo.test.jsx.snap
  app/javascript/chat/__tests__/__snapshots__/message.test.jsx.snap
  app/javascript/chat/__tests__/__snapshots__/video.test.jsx.snap
  app/javascript/chat/__tests__/__snapshots__/view.test.jsx.snap
  app/javascript/chat/__tests__/channelDetails.test.jsx
  app/javascript/chat/__tests__/chat.test.jsx
  app/javascript/chat/article.jsx
  app/javascript/chat/channelDetails.jsx
  app/javascript/chat/channels.jsx
  app/javascript/chat/chat.jsx
  app/javascript/chat/codeEditor.jsx
  app/javascript/chat/compose.jsx
  app/javascript/chat/githubRepo.jsx
  app/javascript/chat/message.jsx
  app/javascript/chat/messages/errorMessage.jsx
  app/javascript/chat/video.jsx
  app/javascript/chat/view.jsx
Labels: PR: reviewed-approved

#4708 Moved following_users_ids to Redis
  app/models/user.rb
Labels: PR: reviewed-approved

#4710 Moved user-github-token to Redis
  app/controllers/chat_channels_controller.rb
Labels: PR: reviewed-approved

#4706 Moved classic-article-for-tag to Redis [deploy]
  app/services/suggester/articles/classic.rb
Labels: PR: reviewed-approved

#4725 Check for existence of honeycomb before using it
  config/initializers/honeycomb.rb
Labels: PR: merged

#4724 Add /future redirect
  config/initializers/reserved_words.rb
  config/routes.rb
Labels: PR: merged

#4715 move cached_follow_check to redis
  app/labor/follow_checker.rb
Labels: PR: merged

#4714 Move cached_followed_tags to redis [deploy]
  app/decorators/user_decorator.rb
Labels: PR: merged

#4657 Add JSitor liquid tag
  app/liquid_tags/jsitor_tag.rb
  app/views/liquids/_jsitor.html.erb
  app/views/pages/_editor_guide_text.html.erb
  spec/liquid_tags/jsitor_tag_spec.rb
  spec/support/fixtures/approvals/jsitor_liquid_tag.approved.html
Labels: PR: merged

#4438 Allow backticks within codeblocks
  config/initializers/redcarpet.rb
Labels: PR: reviewed-approved

#4726 improve editor guide: typos and formatting issues
  app/views/pages/_editor_guide_text.html.erb
Labels: PR: reviewed-approved

#4732 Listings Page: Adding spaces around the words in the listings message form
  app/javascript/listings/listings.jsx
Labels: PR: reviewed-approved

#4728 Onboarding a11y fixes
  app/javascript/onboarding/Onboarding.jsx
  app/javascript/onboarding/__tests__/__snapshots__/Onboarding.test.jsx.snap
  app/javascript/onboarding/components/EmailListTermsConditionsForm.jsx
  app/javascript/onboarding/components/IntroSlide.jsx
  app/javascript/onboarding/components/SlideContent.jsx
  app/views/layouts/application.html.erb
  app/views/pages/_terms_text.html.erb
Labels: PR: reviewed-approved

#2150 Enable viewport scaling for a11y
  app/views/layouts/application.html.erb
Labels: PR: reviewed-approved

#4512 Fix CSS on onboarding page
  app/assets/stylesheets/preact/onboarding-modal.scss
Labels: PR: reviewed-approved

#4733 Add noopener to sponsor links
  app/views/articles/_single_sponsor.html.erb
  app/views/comments/_comment_proper.html.erb
  app/views/layouts/_signup_modal.html.erb
Labels: PR: reviewed-approved

#4645 Wrap <figcaption> elements and content inside <figure> elements
  app/assets/stylesheets/article-show.scss
  app/labor/markdown_parser.rb
  spec/labor/markdown_parser_spec.rb
Labels: PR: reviewed-approved

#4647 Rate limit daily user follows to 500
  Envfile
  app/controllers/follows_controller.rb
  app/labor/rate_limit_checker.rb
  db/migrate/20191031131016_add_created_at_index_to_users.rb
  db/schema.rb
  spec/labor/rate_limit_checker_spec.rb
  spec/requests/follows_create_spec.rb
Labels: PR: reviewed-approved

#4736 Add disable_ddl_transaction to user created_at migration
  db/migrate/20191031131016_add_created_at_index_to_users.rb
Labels: PR: unreviewed

#4738 Remove follow limit for single request
  app/controllers/follows_controller.rb
  spec/requests/follows_create_spec.rb
Labels: PR: unreviewed

#4737 Add missing closing div to internal permissions
  app/views/internal/permissions/index.html.erb
Labels: PR: reviewed-approved

#4740 Remove hacktoberfest from sidebar
  app/labor/flare_tag.rb
  app/views/articles/_sidebar_additional.html.erb
Labels: PR: reviewed-approved

#4731 Comments API: simplify controller code, add tests
  app/controllers/api/v0/comments_controller.rb
  app/models/comment.rb
  spec/requests/api/v0/comments_spec.rb
Labels: PR: reviewed-approved, area: api-v0

#4704 Add cache breaker variable, resolves #4703
  .gitpod.dockerfile
Labels: PR: unreviewed

#4372 Freely color social icon backgrounds for each theme.
  app/assets/stylesheets/article-show.scss
  app/views/layouts/_user_config.html.erb
Labels: PR: reviewed-approved

#4739 Add more randomness to factories
  spec/factories/articles.rb
  spec/factories/badges.rb
  spec/factories/classified_listings.rb
Labels: PR: reviewed-approved

#4730 Generalised my dev feed text to use the community name variable
  app/views/articles/tag_index.html.erb
  app/views/stories/_narrow_nav_menu.html.erb
Labels: PR: reviewed-approved, area: generalization

#4742 Fix http status code for daily account follow rate limiting
  app/controllers/follows_controller.rb
  spec/requests/follows_create_spec.rb
Labels: PR: reviewed-approved

#4746 Docs: Move architecture to technical overview
  docs/readme.md
  docs/technical-overview/architecture.md
  docs/technical-overview/readme.md
  docs/technical-overview/stack.md
Labels: PR: reviewed-approved

#4729 Add site config and remove sail
  Gemfile
  Gemfile.lock
  app/models/site_config.rb
  db/migrate/20191106095242_create_site_configs.rb
  db/migrate/20191106102826_drop_sail_settings.rb
  db/schema.rb
Labels: PR: reviewed-approved

#4789 Add redis-rails gem and REDIS_SESSIONS_URL env variable
  Envfile
  Gemfile
  Gemfile.lock
Labels: PR: reviewed-approved

#4480 Self-deleting user account
  app/assets/stylesheets/shared.scss
  app/controllers/users_controller.rb
  app/jobs/users/self_delete_job.rb
  app/policies/user_policy.rb
  app/services/moderator/delete_user.rb
  app/services/moderator/manage_activity_and_roles.rb
  app/services/users/delete.rb
  app/services/users/delete_activity.rb
  app/services/users/delete_articles.rb
  app/services/users/delete_comments.rb
  app/views/layouts/application.html.erb
  app/views/users/_account.html.erb
  config/routes.rb
  spec/jobs/users/self_delete_job_spec.rb
  spec/requests/user/user_organization_spec.rb
  spec/requests/user/user_profile_spec.rb
  spec/requests/user/user_settings_spec.rb
  spec/services/moderator/delete_user_spec.rb
  spec/services/users/delete_articles_spec.rb
  spec/services/users/delete_comments_spec.rb
  spec/services/users/delete_spec.rb
  spec/system/user/user_self_destroy_spec.rb
Labels: PR: reviewed-approved

#4754 add suggester sidebar class suggest to RedisRailsCache
  app/services/suggester/users/sidebar.rb
Labels: PR: reviewed-approved

#4755 Add AnalyticsService to RedisRailsCache
  app/services/analytics_service.rb
Labels: PR: reviewed-approved

#4791 Add latest articles and possible spam users to internal/reports
  app/controllers/internal/feedback_messages_controller.rb
  app/views/internal/feedback_messages/index.html.erb
Labels: PR: unreviewed

#4788 Use latest Node LTS
  .nvmrc
Labels: PR: reviewed-approved

#4567 Add link to /community-moderation on all /mod pages
  app/assets/stylesheets/minimal.scss
  app/assets/stylesheets/moderators.scss
  app/views/moderations/index.html.erb
  app/views/moderations/mod.html.erb
Labels: PR: reviewed-approved

#4004 Use Redis for session storage
  .travis.yml
  Envfile
  app/controllers/async_info_controller.rb
  app/controllers/omniauth_callbacks_controller.rb
  app/models/user.rb
  config/initializers/devise.rb
  config/initializers/session_store.rb
  config/routes.rb
  spec/requests/api_secrets_create_spec.rb
Labels: PR: reviewed-approved

#4790 Add additional cache value for block
  app/controllers/async_info_controller.rb
Labels: PR: reviewed-approved

#4801 Use REDIS_SESSIONS_URL and default to REDIS_URL
  config/initializers/session_store.rb
Labels: PR: reviewed-approved

#4800 Add additional conditions to internal/reports page
  app/controllers/internal/feedback_messages_controller.rb
  app/services/moderator/banish_user.rb
Labels: PR: unreviewed

#4793 Expire Frequently Updated Cache Keys Sooner
  app/models/user.rb
Labels: PR: reviewed-approved

#4716 Add tag_colors cache to redis
  app/helpers/application_helper.rb
  app/views/articles/show.html.erb
  app/views/moderations/index.html.erb
Labels: PR: reviewed-approved

#4766 CacheBuster refactoring
  app/controllers/internal/articles_controller.rb
  app/controllers/internal/events_controller.rb
  app/controllers/internal/tools_controller.rb
  app/controllers/profile_pins_controller.rb
  app/jobs/articles/bust_cache_job.rb
  app/jobs/articles/bust_multiple_caches_job.rb
  app/jobs/classified_listings/bust_cache_job.rb
  app/jobs/events/bust_cache_job.rb
  app/jobs/organizations/bust_cache_job.rb
  app/jobs/pages/bust_cache_job.rb
  app/jobs/podcast_episodes/bust_cache_job.rb
  app/jobs/podcasts/bust_cache_job.rb
  app/jobs/reactions/bust_homepage_cache_job.rb
  app/jobs/reactions/bust_reactable_cache_job.rb
  app/jobs/tags/bust_cache_job.rb
  app/jobs/users/bust_cache_job.rb
  app/labor/cache_buster.rb
  app/models/article.rb
  app/models/badge.rb
  app/models/comment.rb
  app/models/github_repo.rb
  app/models/reaction.rb
  app/models/user.rb
  app/services/edge_cache/commentable/bust.rb
  app/services/moderator/banish_user.rb
  app/services/moderator/delete_user.rb
  app/services/moderator/merge_user.rb
  app/services/users/delete.rb
  app/services/users/delete_articles.rb
  app/services/users/delete_comments.rb
  lib/tasks/fetch.rake
  spec/jobs/events/bust_cache_job_spec.rb
  spec/jobs/organizations/bust_cache_job_spec.rb
  spec/jobs/pages/bust_cache_job_spec.rb
  spec/jobs/podcast_episodes/bust_cache_job_spec.rb
  spec/jobs/podcasts/bust_cache_job_spec.rb
  spec/jobs/tags/bust_cache_job_spec.rb
  spec/labor/cache_buster_spec.rb
  spec/requests/internal/classified_listings_spec.rb
  spec/services/users/delete_spec.rb
Labels: PR: reviewed-approved

#4809 Move user_data Async Controller Cache to Redis
  app/controllers/async_info_controller.rb
Labels: PR: reviewed-approved

#4806 Normalize podcast url before checking for reachability
  app/services/podcasts/get_media_url.rb
  spec/services/podcasts/get_media_url_spec.rb
Labels: PR: reviewed-approved

#4813 Update docs with more architecture info
  docs/technical-overview/architecture.md
  docs/technical-overview/readme.md
Labels: PR: reviewed-approved

#4762 Redo JSitor
  app/liquid_tags/jsitor_tag.rb
  app/views/pages/_editor_guide_text.html.erb
  spec/liquid_tags/jsitor_tag_spec.rb
  spec/support/fixtures/approvals/jsitor_liquid_tag.approved.html
Labels: PR: reviewed-approved

#4812 Move cached_followed_tag_names to Redis
  app/models/user.rb
Labels: PR: reviewed-approved

#4815 Remove Scout APM
  Gemfile
  Gemfile.lock
  config/scout_apm.yml
Labels: PR: reviewed-approved

#4216 Rails 5.2 features: Enable AES-256-GCM on encrypted cookies
  config/initializers/new_framework_defaults_5_2.rb
Labels: PR: reviewed-approved

#4822 Avoid N+1 queries when sending Notifications for Reactions
  app/services/notifications/reactions/send.rb
Labels: PR: reviewed-approved

#4817 move bufferized tags to RedisCache
  app/models/tag.rb
Labels: PR: reviewed-approved

#4821 Write to RedisCache to avoid cache miss in add html_css_to_image
  app/lib/html_css_to_image.rb
Labels: PR: reviewed-approved

#4819 move caching of reaction to rediscache
  app/models/reaction.rb
Labels: PR: reviewed-approved

#4818 move social_image cache to Redis
  app/view_objects/articles/social_image.rb
Labels: PR: reviewed-approved

#4797 Center podcast page footer.
  app/assets/stylesheets/footer.scss
Labels: PR: reviewed-approved

#4831 Add SiteConfig to internal and enable "main_social_image"
  app/controllers/internal/configs_controller.rb
  app/models/site_config.rb
  app/views/internal/articles/index.html.erb
  app/views/internal/configs/show.html.erb
  app/views/internal/shared/_navbar.html.erb
  app/views/layouts/internal.html.erb
  config/routes.rb
  spec/rails_helper.rb
  spec/requests/internal/configs_spec.rb
Labels: PR: reviewed-approved

#4673 Added lazy loading for iframes
  app/views/articles/_splash.html.erb
  app/views/html_variants/_single_html_variant.html.erb
  app/views/liquids/_asciinema.html.erb
  app/views/liquids/_blogcast.html.erb
  app/views/liquids/_codepen.html.erb
  app/views/liquids/_codesandbox.html.erb
  app/views/liquids/_glitch.html.erb
  app/views/liquids/_instagram.html.erb
  app/views/liquids/_jsfiddle.html.erb
  app/views/liquids/_kotlin.html.erb
  app/views/liquids/_parler.html.erb
  app/views/liquids/_replit.html.erb
  app/views/liquids/_slideshare.html.erb
  app/views/liquids/_soundcloud.html.erb
  app/views/liquids/_speakerdeck.html.erb
  app/views/liquids/_spotify.html.erb
  app/views/liquids/_stackblitz.html.erb
  app/views/liquids/_vimeo.html.erb
  app/views/liquids/_youtube.html.erb
  app/views/pages/live.html.erb
  spec/fixtures/approvals/parlertag/id/accepts_a_valid_parler_url.approved.html
  spec/liquid_tags/parler_tag_spec.rb
  spec/liquid_tags/spotify_tag_spec.rb
  spec/support/fixtures/approvals/codepen_liquid_tag.approved.html
  spec/support/fixtures/approvals/instagram_liquid_tag.approved.html
  spec/support/fixtures/approvals/jsfiddle_liquid_tag.approved.html
  spec/support/fixtures/approvals/kotlin_liquid_tag.approved.html
  spec/support/fixtures/approvals/soundcloud_liquid_tag.approved.html
  spec/support/fixtures/approvals/youtube_liquid_tag_no_time.approved.html
  spec/support/fixtures/approvals/youtube_liquid_tag_no_time_trailing_space.approved.html
  spec/support/fixtures/approvals/youtube_liquid_tag_with_time.approved.html
Labels: PR: reviewed-approved

#4841 Simplify sort tests in user_sorts_dashboard_articles_spec.rb
  spec/system/dashboards/user_sorts_dashboard_articles_spec.rb
Labels: PR: reviewed-approved

#4816 Allow while displaying podcasts episodes processed html
  app/views/podcast_episodes/show.html.erb
Labels: PR: reviewed-approved

#4829 Rails 5.2 features: Enable action_view.form_with_generates_ids
  config/initializers/new_framework_defaults_5_2.rb
Labels: PR: reviewed-approved

#4859 Routine rubocop fixes
  .rubocop_todo.yml
  config/environments/production.rb
  config/initializers/redis_rails.rb
  spec/models/tag_spec.rb
Labels: PR: reviewed-approved

#4836 Updated 'ten-x-hacker' var `--theme-anchor-color`
  app/views/layouts/_user_config.html.erb
Labels: PR: reviewed-approved

#4861 Add additional keys to site configuration
  app/controllers/internal/configs_controller.rb
  app/models/site_config.rb
  app/views/internal/configs/show.html.erb
  spec/requests/internal/configs_spec.rb
Labels: PR: reviewed-approved

#4824 Add Clipboard polyfill
  app/assets/javascripts/initializers/initializeCommentDropdown.js
  app/javascript/packs/clipboardCopy.js
  package.json
  yarn.lock
Labels: PR: reviewed-approved

#4830 Add - to support dash character in JSitor liquid tag
  app/liquid_tags/jsitor_tag.rb
  spec/liquid_tags/jsitor_tag_spec.rb
Labels: PR: reviewed-approved

#4858 Fix broken layout from "additional config/settings" overlap
  app/javascript/article-form/articleForm.jsx
Labels: PR: reviewed-approved

#4375 Add pagination to followers and following page in dashboard (#258)
  app/assets/javascripts/initializers/initScrolling.js.erb
  app/assets/stylesheets/articles.scss
  app/controllers/api/v0/followers_controller.rb
  app/controllers/api/v0/followings_controller.rb
  app/controllers/api/v0/follows_controller.rb
  app/controllers/dashboards_controller.rb
  app/views/api/v0/followers/organizations.json.jbuilder
  app/views/api/v0/followers/users.json.jbuilder
  app/views/api/v0/followings/organizations.json.jbuilder
  app/views/api/v0/followings/podcasts.json.jbuilder
  app/views/api/v0/followings/tags.json.jbuilder
  app/views/api/v0/followings/users.json.jbuilder
  app/views/api/v0/shared/_follows.json.jbuilder
  app/views/dashboards/_actions.html.erb
  app/views/dashboards/_subactions.html.erb
  app/views/dashboards/_sublist.html.erb
  app/views/dashboards/followers.html.erb
  app/views/dashboards/following.html.erb
  app/views/dashboards/following_organizations.html.erb
  app/views/dashboards/following_podcasts.html.erb
  app/views/dashboards/following_tags.html.erb
  app/views/dashboards/following_users.html.erb
  config/routes.rb
  spec/factories/organizations.rb
  spec/factories/podcasts.rb
  spec/factories/tags.rb
  spec/requests/api/v0/followers_spec.rb
  spec/requests/api/v0/followings_spec.rb
  spec/requests/dashboard_spec.rb
  spec/requests/follows_api_spec.rb
  spec/system/dashboards/user_scrolls_down_dashboard_follows_spec.rb
Labels: PR: reviewed-approved

#4872 Upgrade docs Ruby version to 2.6.5, same as the main app
  docs/.ruby-version
  docs/Gemfile
Labels: PR: reviewed-approved

#4869 Fixes count error from multiple clicks on comment like button (#4680)
  app/assets/javascripts/initializers/initializeCommentsPage.js.erb
Labels: PR: reviewed-approved

#4875 Delete a commented out test
  spec/system/homepage/user_sees_checklist_on_home_page_spec.rb
Labels: PR: reviewed-approved

#4750 Mod tooling: add tags via /mod
  app/controllers/moderations_controller.rb
  app/controllers/tag_adjustments_controller.rb
  app/models/article.rb
  app/models/tag_adjustment.rb
  app/services/tag_adjustment_creation_service.rb
  app/views/moderations/mod.html.erb
  app/views/notifications/_tagadjustment.html.erb
  spec/requests/tag_adjustments_spec.rb
  spec/services/notifications/tag_adjustment_notification/send_spec.rb
  spec/services/tag_adjustment_creation_service_spec.rb
  spec/services/tag_adjustment_update_service_spec.rb
Labels: PR: reviewed-approved

#4873 Javascript automated testing and a11y doc
  app/javascript/onboarding/__tests__/Onboarding.test.jsx
  docs/tests/accessibility-tests.md
  docs/tests/readme.md
  package.json
  yarn.lock
Labels: PR: reviewed-approved

#4867 Fix missing series in article edit form (v2)
  app/assets/stylesheets/preact/article-form.scss
  app/javascript/article-form/articleForm.jsx
  app/views/articles/_v2_form.html.erb
Labels: PR: unreviewed

#4865 Add script to display and migrate environment variables to SiteConfig
  lib/tasks/temporary/migrate_environment_variables_site_config.rake
Labels: PR: reviewed-approved

#4881 Remove Service Worker Desktop Notification Code
  app/javascript/chat/actions.js
  app/javascript/chat/chat.jsx
  app/javascript/chat/util.js
Labels: PR: reviewed-approved

#4878 Onboarding test love
  app/javascript/onboarding/__tests__/Onboarding.test.jsx
Labels: PR: reviewed-approved

#4880 Replace current_user.id with session_current_user_id
  app/controllers/application_controller.rb
  app/controllers/chat_channels_controller.rb
  app/controllers/display_ad_events_controller.rb
  app/controllers/messages_controller.rb
  app/controllers/page_views_controller.rb
  app/controllers/reactions_controller.rb
  app/controllers/reading_list_items_controller.rb
Labels: PR: reviewed-approved

#4883 Remove WebPush Gem and Code
  Envfile
  Gemfile
  Gemfile.lock
  app/controllers/messages_controller.rb
  app/jobs/messages/send_push_job.rb
  app/models/message.rb
  app/services/messages/send_push.rb
  app/views/chat_channels/index.html.erb
  spec/jobs/messages/send_push_job_spec.rb
  spec/services/messages/send_push_spec.rb
Labels: PR: reviewed-approved

#4826 Rails 5.2 features: Enable AES-256-GCM on encrypted messages
  config/initializers/new_framework_defaults_5_2.rb
Labels: PR: reviewed-approved

#4891 Add a link for Twitter developer access [ci skip]
  docs/backend/auth-twitter.md
Labels: PR: reviewed-approved

#4896 Fix typo in architecture.md
  docs/technical-overview/architecture.md
Labels: PR: reviewed-approved

#4905 Delete a commented out system spec
  spec/system/user/user_edits_profile_spec.rb
Labels: PR: reviewed-approved

#4885 Update reading list updated_at cache key timestamp
  app/labor/reading_list.rb
Labels: PR: reviewed-approved

#4924 Routine rubocop fixes
  .rubocop_todo.yml
  spec/factories/activesupport_events.rb
  spec/factories/webhook_endpoints.rb
Labels: PR: reviewed-approved

#4799 Fix light outline around sidebar profile picture in night mode
  app/assets/stylesheets/articles.scss
Labels: PR: reviewed-approved

#4928 Remove article-main-reactions Cache Key
  .rubocop_todo.yml
  app/views/articles/_actions.html.erb
Labels: PR: reviewed-approved

#4927 Move bottom_content Article Content to Redis
  .rubocop_todo.yml
  app/views/articles/show.html.erb
Labels: PR: reviewed-approved

#4930 Move Organization Profile Image Cache to Redis
  app/views/articles/_org_branding.html.erb
Labels: PR: reviewed-approved

#4923 Remove extra dependencies for PageViewsController
  app/controllers/application_metal_controller.rb
  app/controllers/page_views_controller.rb
  spec/requests/page_views_spec.rb
  spec/system/comments/user_fills_out_comment_spec.rb
Labels: PR: unreviewed

#4932 Revert Redis fragment cache
  app/views/articles/_org_branding.html.erb
  app/views/articles/show.html.erb
Labels: PR: reviewed-approved

#4933 Replace deprecated inline_svg
  app/helpers/application_helper.rb
  app/helpers/articles_helper.rb
  app/views/articles/show.html.erb
  app/views/devise/registrations/_registration_form.html.erb
  app/views/layouts/_top_bar.html.erb
  app/views/social_previews/article.html.erb
  app/views/social_previews/comment.html.erb
  app/views/social_previews/listing.html.erb
  app/views/social_previews/tag.html.erb
  app/views/social_previews/user.html.erb
  app/views/users/_profile_header.html.erb
  app/views/users/show.html.erb
  spec/helpers/articles_helper_spec.rb
Labels: PR: reviewed-approved

#4899 Improve the clarity of the docs and fix Prettier config
  docs/backend/admin.md
  docs/backend/algolia.md
  docs/backend/auth-github.md
  docs/backend/auth-twitter.md
  docs/backend/authentication.md
  docs/backend/authorization.md
  docs/backend/notification.md
  docs/backend/pusher.md
  docs/backend/roles.md
  docs/backend/scheduled-jobs.md
  docs/contributing.md
  docs/contributing_api.md
  docs/deployment.md
  docs/design/branding.md
  docs/design/theming.md
  docs/faqs.md
  docs/frontend/debugging.md
  docs/frontend/liquid-tags.md
  docs/frontend/plain-js.md
  docs/frontend/preact.md
  docs/getting-started/branching.md
  docs/getting-started/committing.md
  docs/getting-started/config-env.md
  docs/getting-started/db.md
  docs/getting-started/forking.md
  docs/getting-started/pull-request.md
  docs/getting-started/start-app.md
  docs/getting-started/syncing.md
  docs/getting-started/workflow.md
  docs/installation/docker.md
  docs/installation/gitpod.md
  docs/installation/linux.md
  docs/installation/mac.md
  docs/installation/postgresql.md
  docs/installation/readme.md
  docs/installation/windows.md
  docs/licensing.md
  docs/readme.md
  docs/self-hosting.md
  docs/technical-overview/architecture.md
  docs/technical-overview/readme.md
  docs/technical-overview/stack.md
  docs/tests/acceptance-tests.md
  docs/tests/accessibility-tests.md
  docs/tests/code-coverage.md
  docs/tests/codeclimate.md
  docs/tests/integration-tests.md
  docs/tests/preact-tests.md
  docs/tests/readme.md
  docs/tests/skip-ci.md
  docs/tests/unit-functional-tests.md
  package.json
Labels: PR: reviewed-approved

#4912 Refactor raise_error(specific_error) expectation
  spec/liquid_tags/jsitor_tag_spec.rb
  spec/support/fixtures/approvals/jsitor_liquid_tag_with_hyphen.approved.html
  spec/support/fixtures/approvals/jsitor_liquid_tag_with_params.approved.html
Labels: PR: reviewed-approved

#4882 Increase efficiency in models/article_spec.rb
  app/models/article.rb
  spec/decorators/article_decorator_spec.rb
  spec/models/article_spec.rb
  spec/models/shared_examples/sync_reactions_count.rb
  spec/rails_helper.rb
Labels: PR: reviewed-approved

#4935 Remove rubyzip initializer, unnecessary on rubyzip 2
  config/initializers/rubyzip.rb
Labels: PR: reviewed-approved

#4936 Refactor session_current_user_id in a shared concern
  app/controllers/application_controller.rb
  app/controllers/application_metal_controller.rb
  app/controllers/concerns/session_current_user.rb
Labels: PR: reviewed-approved

#4886 Store FollowChecker responses to Avoid Multiple db Hits
  app/controllers/follows_controller.rb
  app/labor/follow_checker.rb
Labels: PR: reviewed-approved

#4945 Modify page view recount rate in page_views_controller
  app/controllers/page_views_controller.rb
Labels: PR: unreviewed

#4876 Cleanup JS part as suggested under users/_account.html.erb
  app/views/users/_account.html.erb
Labels: PR: reviewed-approved

#4937 Add ApplicationMetalController to relevant controllers
  app/controllers/application_controller.rb
  app/controllers/application_metal_controller.rb
  app/controllers/concerns/valid_request.rb
  app/controllers/display_ad_events_controller.rb
  app/controllers/html_variant_successes_controller.rb
  app/controllers/html_variant_trials_controller.rb
  spec/factories/articles.rb
Labels: PR: unreviewed

#4943 Update readme formatting
  README.md
Labels: PR: reviewed-approved

#4954 Fix black-on-black etc. buttons and update social preview cards
  app/controllers/social_previews_controller.rb
  app/decorators/user_decorator.rb
  app/views/shared/_logo_design.html.erb
  app/views/social_previews/article.html.erb
  app/views/social_previews/comment.html.erb
  app/views/social_previews/user.html.erb
Labels: PR: unreviewed

#4753 add html_css_to_image to RedisRailsCache
  app/lib/html_css_to_image.rb
  spec/lib/html_css_to_image_spec.rb
Labels: PR: reviewed-approved

#4863 User deletion by email
  app/assets/stylesheets/settings.scss
  app/controllers/users_controller.rb
  app/mailers/notify_mailer.rb
  app/policies/user_policy.rb
  app/services/users/delete.rb
  app/services/users/request_destroy.rb
  app/views/mailers/notify_mailer/account_deletion_requested_email.html.erb
  app/views/mailers/notify_mailer/account_deletion_requested_email.txt.erb
  app/views/users/_account.html.erb
  app/views/users/confirm_destroy.html.erb
  config/routes.rb
  spec/requests/user/user_destroy_spec.rb
  spec/requests/user/user_settings_spec.rb
  spec/services/users/delete_spec.rb
  spec/system/user/user_self_destroy_spec.rb
Labels: PR: reviewed-approved

#4947 Expand the contributing guide
  CONTRIBUTING.md
Labels: PR: unreviewed

#4963 Resolve TypeError when clearing new changes in articleform
  app/javascript/article-form/articleForm.jsx
Labels: PR: reviewed-approved

#4967 Fix podcast episode validation error
  app/services/podcasts/create_episode.rb
  spec/services/podcasts/create_episode_spec.rb
Labels: PR: reviewed-approved

#4965 Add redis container to docker-compose
  docker-compose.yml
  docs/installation/docker.md
Labels: PR: reviewed-approved

#4968 Modify cache rate for additional_content_boxes
  app/assets/javascripts/initializers/initializeAdditionalContentBoxes.js
Labels: PR: unreviewed
