Repository forem/forem, pull requests merged in 2019-05, with the labels that each got.

#2633 Added the themeable mixin.
  app/assets/stylesheets/_mixins.scss
  app/assets/stylesheets/articles.scss
Labels: PR: reviewed-approved

#2627 Add page for users to "manage" their posts after publication (distribution, etc.)
  app/assets/javascripts/initializers/initializeBaseUserData.js
  app/assets/stylesheets/article-show.scss
  app/assets/stylesheets/dashboard.scss
  app/controllers/articles_controller.rb
  app/controllers/buffer_updates_controller.rb
  app/models/rating_vote.rb
  app/policies/application_policy.rb
  app/policies/buffer_update_policy.rb
  app/views/articles/manage.html.erb
  app/views/dashboards/_dashboard_article.html.erb
  app/views/dashboards/show.html.erb
  config/routes.rb
  spec/models/rating_vote_spec.rb
  spec/policies/article_policy_spec.rb
  spec/policies/buffer_update_policy_spec.rb
  spec/requests/articles_spec.rb
  spec/requests/buffer_updates_spec.rb
  spec/system/articles/user_deletes_an_article_spec.rb
Labels: PR: unreviewed

#2636 Fix buffer_updates conditional in /manage
  app/controllers/articles_controller.rb
Labels: PR: unreviewed

#2597 Add hover to article save button
  app/assets/javascripts/utilities/buildArticleHTML.js.erb
  app/assets/stylesheets/articles.scss
  app/assets/stylesheets/more-articles.scss
  app/views/articles/_single_story.html.erb
  app/views/articles/index.html.erb
Labels: PR: reviewed-approved

#2620 Embed Single File from Gist
  app/liquid_tags/gist_tag.rb
  app/views/pages/_editor_guide_text.html.erb
  spec/liquid_tags/gist_tag_spec.rb
Labels: PR: reviewed-approved

#2188 Social Cards Part 2
  app/helpers/application_helper.rb
  app/helpers/social_image_helper.rb
  app/models/article.rb
  app/views/api/v0/articles/show.json.jbuilder
  app/views/articles/show.html.erb
  app/views/articles/tags/_meta.html.erb
  app/views/comments/index.html.erb
  app/views/users/_meta.html.erb
  config/routes.rb
  spec/helpers/social_image_helper_spec.rb
Labels: PR: unreviewed

#2635 Allow admins to remove credits from internal/users
  app/controllers/internal/users_controller.rb
  app/models/user.rb
  app/views/internal/users/_credits.erb
  spec/requests/internal/users_spec.rb
Labels: PR: reviewed-approved

#2563 Fix Save Changes text spill out of button
  app/assets/stylesheets/preact/article-form.scss
Labels: PR: reviewed-approved

#2213 Added unique index to notifications #2124
  app/models/notification.rb
  app/services/notifications/new_follower/send.rb
  db/migrate/20190326085046_add_unique_index_to_notifications.rb
  db/schema.rb
  spec/models/notification_spec.rb
Labels: PR: reviewed-approved

#2596 Move async comment methods to comment jobs
  app/jobs/comments/bust_cache_job.rb
  app/jobs/comments/calculate_score_job.rb
  app/jobs/comments/create_first_reaction_job.rb
  app/jobs/comments/create_id_code_job.rb
  app/jobs/comments/send_email_notification_job.rb
  app/jobs/comments/touch_user_job.rb
  app/models/comment.rb
  spec/jobs/comments/bust_cache_job_spec.rb
  spec/jobs/comments/calculate_score_job_spec.rb
  spec/jobs/comments/create_first_reaction_job_spec.rb
  spec/jobs/comments/create_id_code_job_spec.rb
  spec/jobs/comments/send_email_notification_job_spec.rb
  spec/jobs/comments/touch_user_job_spec.rb
Labels: PR: reviewed-approved

#2478 [SMALL] UX improvement on chronofiter hover
  app/assets/stylesheets/articles.scss
Labels: PR: reviewed-approved

#2640 Add nightmode version of sponsorship images
  app/assets/stylesheets/articles.scss
  app/assets/stylesheets/variables.scss
  app/dashboards/organization_dashboard.rb
  app/models/organization.rb
  app/views/articles/_sidebar.html.erb
  db/migrate/20190501180125_add_dark_nav_image_to_organizations.rb
  db/schema.rb
Labels: PR: unreviewed

#2590 Add file argument to Stackblitz embed.
  app/liquid_tags/stackblitz_tag.rb
  app/views/pages/_editor_guide_text.html.erb
  spec/liquid_tags/stackblitz_tag_spec.rb
Labels: PR: reviewed-approved

#2645 Fix social image order logic
  app/helpers/social_image_helper.rb
Labels: PR: unreviewed

#2641 dev tag liquid tag render utilize html.erb
  app/liquid_tags/tag_tag.rb
  app/views/tags/_liquid.html.erb
Labels: PR: reviewed-approved, refactor

#2554 devcomment liquid tag render utilize html.erb
  app/liquid_tags/dev_comment_tag.rb
  app/views/comments/_liquid.html.erb
  spec/liquid_tags/dev_comment_tag_spec.rb
Labels: PR: reviewed-approved, refactor

#2649 Upgrade Ruby to 2.6.3
  .ruby-version
  .travis.yml
  Dockerfile
  Gemfile
  Gemfile.lock
  README.md
  db/seeds.rb
  docker-entrypoint.sh
  docker-run.sh
  docs/installation/docker.md
  docs/installation/linux.md
  docs/installation/mac.md
  docs/installation/windows.md
Labels: PR: reviewed-approved

#2653 Correctly align saved/unsave
  app/assets/stylesheets/articles.scss
Labels: PR: reviewed-approved

#2656 Adds Ruby source code documentation to docs.dev.to
  .gitignore
  .yardopts
  Gemfile
  Gemfile.lock
  docs/.gitdocs.json
  docs/.ruby-version
  docs/Gemfile
  docs/Makefile
  docs/faqs.md
  netlify.toml
Labels: PR: reviewed-approved

#2650 Added hover effect for `sidebar-profile-snapshot`
  app/assets/stylesheets/articles.scss
Labels: PR: reviewed-approved

#2637 Create listings permalink
  app/controllers/classified_listings_controller.rb
  app/javascript/listings/singleListing.jsx
  app/models/classified_listing.rb
  config/routes.rb
  db/migrate/20190501141654_add_slug_to_classified_listings.rb
  db/schema.rb
Labels: PR: reviewed-approved

#2658 Create serialized cached user and cached organization for articles
  app/models/article.rb
  app/models/organization.rb
  db/migrate/20190502165056_add_cached_user_to_articles.rb
  db/schema.rb
  spec/models/article_spec.rb
  spec/models/organization_spec.rb
Labels: PR: unreviewed

#2659 Quick minor cache improvements to tag index
  app/views/articles/tag_index.html.erb
Labels: PR: unreviewed

#2661 Add profile_image_90 to serialized data on article
  app/models/article.rb
  app/models/organization.rb
  spec/models/article_spec.rb
Labels: PR: unreviewed

#2663 Small cached attribute fix
  app/views/additional_content_boxes/_article_box.html.erb
  app/views/stories/_main_stories_feed.html.erb
Labels: PR: unreviewed

#2660 Update Listings Price
  app/assets/stylesheets/credits.scss
  app/controllers/credits_controller.rb
  app/views/classified_listings/_form.html.erb
  app/views/credits/new.html.erb
Labels: PR: reviewed-approved

#2657 Add application "page" model
  app/controllers/internal/pages_controller.rb
  app/controllers/pages_controller.rb
  app/labor/markdown_parser.rb
  app/models/page.rb
  app/views/articles/show.html.erb
  app/views/internal/pages/_form.html.erb
  app/views/internal/pages/edit.html.erb
  app/views/internal/pages/index.html.erb
  app/views/internal/pages/new.html.erb
  app/views/layouts/internal.html.erb
  app/views/pages/show.html.erb
  config/routes.rb
  db/migrate/20190501191830_create_pages.rb
  db/schema.rb
  spec/factories/pages.rb
  spec/models/page_spec.rb
  spec/requests/pages_spec.rb
Labels: PR: unreviewed

#2643 Add policy for article manage action
  app/assets/javascripts/initializers/initializeBaseUserData.js
  app/views/articles/show.html.erb
Labels: PR: reviewed-approved

#2672 Fixes custom listing credit amount bug #2566
  app/views/credits/new.html.erb
Labels: PR: reviewed-approved

#2674 Move new listing form to Preact
  app/assets/stylesheets/classified_listings.scss
  app/assets/stylesheets/classified_listings_form.scss
  app/javascript/listings/elements/bodyMarkdown.jsx
  app/javascript/listings/elements/categories.jsx
  app/javascript/listings/elements/organizationField.jsx
  app/javascript/listings/elements/tags.jsx
  app/javascript/listings/elements/title.jsx
  app/javascript/listings/listingForm.jsx
  app/javascript/packs/listingForm.jsx
  app/models/classified_listing.rb
  app/views/classified_listings/_form.html.erb
  app/views/classified_listings/new.html.erb
Labels: PR: unreviewed

#2667 More themeable mixin in action.
  app/assets/stylesheets/_mixins.scss
  app/assets/stylesheets/ltags/TagTag.scss
  app/assets/stylesheets/more-articles.scss
  app/assets/stylesheets/notifications.scss
  app/assets/stylesheets/settings.scss
Labels: PR: unreviewed

#2634 Customize RSS feed by tag
  app/controllers/articles_controller.rb
  config/routes.rb
  spec/requests/articles_spec.rb
  spec/requests/rss_feed_spec.rb
Labels: PR: reviewed-approved

#2437 Add localized visible short comment date
  app/assets/javascripts/initializers/initializeCommentDate.js
  app/assets/javascripts/utilities/localDateTime.js
Labels: PR: reviewed-changes-requested

#2619 dev link liquid tag render utilize html.erb
  app/liquid_tags/link_tag.rb
  app/views/articles/_liquid.html.erb
  spec/liquid_tags/link_tag_spec.rb
Labels: PR: reviewed-changes-requested, refactor

#2692 Twitch Webhook Fixes
  app/controllers/twitch_stream_updates_controller.rb
  app/models/user.rb
  app/services/streams/twitch_webhook/register.rb
  spec/requests/twitch_stream_updates_spec.rb
  spec/services/streams/twitch_webhook/register_spec.rb
Labels: PR: unreviewed

#2621 dev user liquid tag render utilize html.erb
  app/assets/stylesheets/ltags/UserTag.scss
  app/liquid_tags/user_tag.rb
  app/views/users/_liquid.html.erb
Labels: PR: unreviewed, refactor

#2644 dev podcast liquid tag render to html erb
  app/liquid_tags/podcast_tag.rb
  app/views/podcast_episodes/_liquid.html.erb
Labels: PR: unreviewed, refactor

#2721 Change Twitter liquid tag to utilize ActionController
  app/liquid_tags/tweet_tag.rb
  app/views/liquids/_tweet.html.erb
  spec/liquid_tags/tweet_tag_spec.rb
  spec/support/fixtures/approvals/liquid_tweet_tag_spec.approved.html
Labels: PR: unreviewed, refactor

#2723 Change Runkit liquid tag to utilize ActionController
  app/liquid_tags/runkit_tag.rb
  app/views/liquids/_runkit.html.erb
  spec/liquid_tags/runkit_tag_spec.rb
  spec/support/fixtures/approvals/runkit_liquid_tag_spec.approved.html
Labels: PR: unreviewed, refactor

#2745 Repl.it Liquid tag render to utilize ActionController
  app/liquid_tags/replit_tag.rb
  app/views/liquids/_replit.html.erb
Labels: refactor

#2746 JS Fiddle Liquid tag render to utilize ActionController
  app/liquid_tags/jsfiddle_tag.rb
  app/views/liquids/_jsfiddle.html.erb
  spec/support/fixtures/approvals/jsfiddle_liquid_tag.approved.html
Labels: refactor

#2747 Codesandbox Liquid tag render to utilize ActionController
  app/liquid_tags/codesandbox_tag.rb
  app/views/liquids/_codesandbox.html.erb
Labels: refactor

#2655 Refactor Comments::BustCacheJob to use a service
  app/jobs/comments/bust_cache_job.rb
  app/models/comment.rb
  app/services/edge_cache/commentable/bust.rb
  spec/jobs/comments/bust_cache_job_spec.rb
  spec/services/edge_cache/commentable/bust_spec.rb
Labels: PR: unreviewed

#2722 Show localized date/time on hover for articles/comments
  app/assets/javascripts/initializePage.js.erb
  app/assets/javascripts/initializers/initializeArticleDate.js
  app/assets/javascripts/initializers/initializeCommentDate.js
  app/assets/javascripts/utilities/buildArticleHTML.js.erb
  app/assets/javascripts/utilities/buildCommentHTML.js.erb
  app/assets/javascripts/utilities/localDateTime.js
  app/assets/stylesheets/comments.scss
  app/models/.keep
  app/models/article.rb
  app/views/api/v0/articles/index.json.jbuilder
  app/views/api/v0/articles/show.json.jbuilder
  app/views/articles/_bottom_content.html.erb
  app/views/articles/_single_story.html.erb
  app/views/articles/index.html.erb
  app/views/articles/show.html.erb
  app/views/comments/_comment_date.erb
  app/views/comments/_comment_proper.html.erb
  app/views/comments/_liquid.html.erb
  app/views/stories/_main_stories_feed.html.erb
  app/views/users/_comments_section.html.erb
  spec/models/article_spec.rb
  spec/system/articles/user_visits_an_article_spec.rb
  spec/system/comments/user_views_a_comment_spec.rb
  spec/system/homepage/user_visits_homepage_articles_spec.rb
  spec/system/user/view_user_index_spec.rb
Labels: PR: reviewed-approved

#2728 Youtube/Vimeo liquid tag render to utilize ActionController
  app/liquid_tags/vimeo_tag.rb
  app/liquid_tags/youtube_tag.rb
  app/views/liquids/_vimeo.html.erb
  app/views/liquids/_youtube.html.erb
  spec/liquid_tags/youtube_tag_spec.rb
  spec/support/fixtures/approvals/youtube_liquid_tag_no_time.approved.html
  spec/support/fixtures/approvals/youtube_liquid_tag_no_time_trailing_space.approved.html
  spec/support/fixtures/approvals/youtube_liquid_tag_with_time.approved.html
Labels: refactor

#2749 Instagram Liquid tag render to utilize ActionController
  app/liquid_tags/instagram_tag.rb
  app/views/liquids/_instagram.html.erb
  spec/liquid_tags/instagram_tag_spec.rb
  spec/support/fixtures/approvals/instagram_liquid_tag.approved.html
Labels: refactor

#2750 Speakerdeck Liquid tag render to utilize ActionController
  app/liquid_tags/speakerdeck_tag.rb
  app/views/liquids/_speakerdeck.html.erb
Labels: refactor

#2754 Blogcast Liquid tag render to utilize ActionController
  app/liquid_tags/blogcast_tag.rb
  app/views/liquids/_blogcast.html.erb
Labels: refactor

#2752 Soundcloud Liquid tag render to utilize ActionController
  app/liquid_tags/soundcloud_tag.rb
  app/views/liquids/_soundcloud.html.erb
  spec/support/fixtures/approvals/soundcloud_liquid_tag.approved.html
Labels: refactor

#2748 Codepen Liquid tag render to utilize ActionController
  app/liquid_tags/codepen_tag.rb
  app/views/liquids/_codepen.html.erb
  spec/support/fixtures/approvals/codepen_liquid_tag.approved.html
Labels: refactor

#2753 Spotify Liquid tag render to utilize ActionController
  app/liquid_tags/spotify_tag.rb
  app/views/liquids/_spotify.html.erb
  spec/liquid_tags/spotify_tag_spec.rb
Labels: refactor

#2654 Move tag adjustment notification to Active Jobs
  app/jobs/notifications/tag_adjustment_notification_job.rb
  app/models/notification.rb
  app/services/notifications/tag_adjustment_notification/send.rb
  spec/jobs/notifications/tag_adjustment_notification_job_spec.rb
  spec/models/notification_spec.rb
  spec/services/notifications/tag_adjustment_notification/send_spec.rb
  spec/services/tag_adjustment_creation_service_spec.rb
Labels: PR: unreviewed

#2647 Move async article methods to ActiveJob
  app/jobs/articles/bust_cache_job.rb
  app/jobs/articles/bust_multiple_caches_job.rb
  app/jobs/articles/detect_human_language_job.rb
  app/jobs/articles/update_main_image_background_hex_job.rb
  app/models/article.rb
  spec/jobs/articles/bust_cache_job_spec.rb
  spec/jobs/articles/bust_multiple_caches_job_spec.rb
  spec/jobs/articles/detect_human_language_job_spec.rb
  spec/jobs/articles/score_calc_job_spec.rb
  spec/jobs/articles/update_main_image_background_hex_job_spec.rb
  spec/models/article_destroy_spec.rb
Labels: PR: unreviewed

#2815 Fix localstorage key
  app/javascript/article-form/articleForm.jsx
Labels: PR: unreviewed

#2798 Allow archiving of posts
  app/assets/javascripts/initializePage.js.erb
  app/assets/javascripts/initializers/initializeArchivedPostFilter.js
  app/assets/javascripts/initializers/initializeEllipsisMenu.js
  app/assets/stylesheets/dashboard.scss
  app/controllers/article_mutes_controller.rb
  app/controllers/articles_controller.rb
  app/policies/article_policy.rb
  app/views/dashboards/_dashboard_article.html.erb
  app/views/dashboards/show.html.erb
  app/views/layouts/application.html.erb
  db/migrate/20190504015859_add_archived_to_articles.rb
  db/schema.rb
Labels: PR: unreviewed

#2816 Remove 'submit' type from buttons on internal reports
  app/views/internal/feedback_messages/_feedback_message.html.erb
Labels: PR: reviewed-approved

#2696 Move async user methods to ActiveJob
  app/jobs/users/bust_cache_job.rb
  app/jobs/users/subscribe_to_mailchimp_newsletter_job.rb
  app/models/user.rb
  spec/jobs/users/bust_cache_job_spec.rb
  spec/jobs/users/subscribe_to_mailchimp_newsletter_job_spec.rb
Labels: PR: reviewed-approved

#2817 Finalize archived posts in dashboard
  app/assets/stylesheets/dashboard.scss
  app/views/dashboards/_dashboard_article.html.erb
  app/views/layouts/application.html.erb
Labels: PR: unreviewed

#2805 Remove unused ModerationService
  app/models/article.rb
  app/services/moderation_service.rb
  spec/services/moderation_service_spec.rb
Labels: PR: reviewed-approved

#2819 Add JS guard
  app/assets/javascripts/initializers/initializeArchivedPostFilter.js
Labels: PR: unreviewed

#2821 Turn blank canonical url into nil
  app/models/article.rb
Labels: PR: unreviewed

#2785 Gist Liquid tag render to utilize ActionController
  app/liquid_tags/gist_tag.rb
  app/views/liquids/_gist.html.erb
  spec/liquid_tags/gist_tag_spec.rb
Labels: PR: reviewed-approved, refactor

#2802 Upgrade rubocop and rubocop-performance
  .rubocop_todo.yml
  Gemfile
  Gemfile.lock
  app/controllers/articles_controller.rb
  app/controllers/reading_list_items_controller.rb
  app/labor/markdown_parser.rb
  app/models/reaction.rb
  app/services/article_with_video_creation_service.rb
  docs/Gemfile
  spec/requests/reading_list_items_spec.rb
Labels: PR: reviewed-approved

#2823 Fix save article button action
  app/assets/javascripts/initializers/initializeReadingListIcons.js
Labels: PR: reviewed-approved

#2788 Parler Liquid tag render to utilize ActionController
  app/liquid_tags/parler_tag.rb
  app/views/liquids/_parler.html.erb
  app/views/pages/_editor_guide_text.html.erb
  spec/liquid_tags/parler_tag_spec.rb
Labels: PR: reviewed-approved, refactor

#2787 SlideShare Liquid tag render to utilize ActionController
  app/liquid_tags/slideshare_tag.rb
  app/views/liquids/_slideshare.html.erb
Labels: PR: reviewed-approved, refactor

#2774 Glitch Liquid tag render to utilize ActionController
  app/liquid_tags/glitch_tag.rb
  app/views/liquids/_glitch.html.erb
  spec/liquid_tags/glitch_tag_spec.rb
Labels: PR: reviewed-approved, refactor

#2786 Medium Liquid tag render to utilize ActionController
  app/liquid_tags/medium_tag.rb
  app/views/liquids/_medium.html.erb
Labels: PR: reviewed-approved, refactor

#2831 Fix text that says publishing for v1
  app/javascript/article-form/articleForm.jsx
  app/javascript/article-form/elements/notice.jsx
  app/views/users/_misc.html.erb
Labels: PR: unreviewed

#2835 use <label>'s for input field labels on account settings page
  app/views/users/_account.html.erb
Labels: PR: reviewed-approved

#2777 GitHub Liquid tag render to utilize ActionController
  app/liquid_tags/github_tag/github_issue_tag.rb
  app/liquid_tags/github_tag/github_readme_tag.rb
  app/views/liquids/_github_issue.html.erb
  app/views/liquids/_github_readme.html.erb
  spec/support/fixtures/approvals/github_liquid_tag_default.approved.html
Labels: PR: reviewed-approved, refactor

#2773 Convert articles & comments to ghost account for users who opt in
  app/controllers/internal/users_controller.rb
  app/models/user.rb
  app/services/moderator/banish_user.rb
  app/services/moderator/delete_user.rb
  app/services/moderator/manage_activity_and_roles.rb
  app/views/internal/users/edit.html.erb
  spec/requests/internal/users_spec.rb
Labels: PR: reviewed-approved

#2832 Finalize Medium liquid tag and add video to video article liquid tags
  app/assets/stylesheets/ltags/LinkTag.scss
  app/labor/markdown_parser.rb
  app/liquid_tags/medium_tag.rb
  app/views/articles/_liquid.html.erb
  app/views/liquids/_medium.html.erb
  app/views/pages/_editor_guide_text.html.erb
  spec/liquid_tags/link_tag_spec.rb
Labels: PR: unreviewed

#1579 Add click-to-copy to article share dropdown
  app/assets/images/content-copy.svg
  app/assets/javascripts/.eslintrc.js
  app/assets/javascripts/initializers/initializeCommentDropdown.js
  app/assets/stylesheets/article-show.scss
  app/javascript/packs/clipboardCopy.js
  app/views/articles/_actions.html.erb
  app/views/articles/show.html.erb
  package.json
  yarn.lock
Labels: PR: reviewed-approved

#2837 bust ghost cache and reindex articles
  app/services/moderator/delete_user.rb
Labels: PR: reviewed-approved

#2838 Move webcomponents-loader to lib and clean out some dead code (unrela…
  app/assets/javascripts/base.js.erb
  app/assets/javascripts/initializePage.js.erb
  app/assets/javascripts/initializers/initEditorResize.js
  app/assets/javascripts/initializers/initLeaveEditorWarning.js
  app/assets/javascripts/lib/webcomponents-loader.js
  app/javascript/article-form/__tests__/articleForm.test.jsx
  app/views/articles/show.html.erb
Labels: PR: unreviewed

#2827 Simplify article show page reactions
  app/assets/javascripts/initializers/initializeArticleReactions.js
  app/assets/javascripts/initializers/initializeCommentDropdown.js
  app/assets/javascripts/initializers/initializeCommentsPage.js.erb
  app/assets/javascripts/initializers/initializeTouchDevice.js
  app/assets/stylesheets/article-show.scss
  app/assets/stylesheets/comments.scss
  app/assets/stylesheets/more-articles.scss
  app/assets/stylesheets/scaffolds.scss
  app/assets/stylesheets/sticky-nav.scss
  app/javascript/article-form/articleForm.jsx
  app/javascript/packs/Search.jsx
  app/javascript/src/components/Search/Search.jsx
  app/labor/random_gif.rb
  app/views/articles/_actions.html.erb
  app/views/articles/_sticky_nav.html.erb
  app/views/layouts/_user_config.html.erb
  package.json
  yarn.lock
Labels: PR: unreviewed

#2841 Folllow on for show page adjustments and fix uglifier issue
  app/assets/javascripts/initializers/initializeCommentDropdown.js
  app/assets/stylesheets/article-show.scss
Labels: PR: unreviewed

#2843 Adjust bottom action bar padding
  app/assets/stylesheets/article-show.scss
Labels: PR: unreviewed

#2840 Double check opt-in before sending digest
  app/labor/email_digest.rb
Labels: PR: reviewed-approved

#2839 ActiveJob for updating notifications #1996
  app/jobs/notifications/update_job.rb
  app/models/article.rb
  app/models/notification.rb
  app/services/notifications.rb
  app/services/notifications/update.rb
  spec/jobs/notifications/update_job_spec.rb
  spec/models/notification_spec.rb
  spec/services/notifications/update_spec.rb
Labels: PR: reviewed-approved

#2833 Strip org secret before searching and add better error handling for invalid secrets
  app/controllers/users_controller.rb
  spec/requests/user_organization_spec.rb
Labels: PR: reviewed-approved

#2845 Fiddle with padding and adjust colors on show page
  app/assets/javascripts/initializers/initializeTouchDevice.js
  app/assets/stylesheets/article-show.scss
Labels: PR: unreviewed

#2820 🐛 Fix prefered language checkbox label ✅
  app/views/users/_language_settings.html.erb
Labels: PR: reviewed-approved

#2800 Upgrade fog-aws from 2.0 to 3.5
  Gemfile
  Gemfile.lock
Labels: PR: reviewed-approved

#2475 REF: Started refactoring onboarding react
  app/javascript/src/__tests__/__snapshots__/Onboarding.test.jsx.snap
  app/javascript/src/components/OnboardingSingleTag.jsx
  app/javascript/src/components/OnboardingTags.jsx
  app/javascript/src/components/__tests__/__snapshots__/OnboardingFollowTags.test.jsx.snap
  app/javascript/src/components/__tests__/__snapshots__/OnboardingSingleTag.test.jsx.snap
  app/javascript/src/utils/getUnopenedChannels.jsx
Labels: PR: reviewed-approved

#2849 Fix user liquid tag text color
  app/assets/stylesheets/ltags/UserTag.scss
Labels: PR: reviewed-approved

#2852 Fix pink theme button difference issue
  app/assets/stylesheets/article-show.scss
  app/views/layouts/_user_config.html.erb
Labels: PR: unreviewed

#2844 Articles API: create and update
  app/controllers/api/v0/analytics_controller.rb
  app/controllers/api/v0/api_controller.rb
  app/controllers/api/v0/articles_controller.rb
  app/controllers/api/v0/comments_controller.rb
  app/controllers/articles_controller.rb
  app/javascript/article-form/actions.js
  app/services/article_creation_service.rb
  app/services/articles/updater.rb
  app/views/api/v0/articles/show.json.jbuilder
  spec/factories/collections.rb
  spec/fixtures/files/article_published.txt
  spec/fixtures/files/article_published_canonical_url.txt
  spec/fixtures/files/article_published_cover_image.txt
  spec/fixtures/files/article_published_series.txt
  spec/fixtures/files/article_unpublished.txt
  spec/requests/api/v0/articles_spec.rb
  spec/requests/api/v0/comments_spec.rb
  spec/requests/api/v0/podcasts_episodes_spec.rb
  spec/requests/podcast_episodes_api_spec.rb
  spec/support/api_analytics_shared_examples.rb
  spec/system/articles/user_creates_an_article_spec.rb
  spec/system/articles/user_edits_an_article_spec.rb
Labels: PR: reviewed-approved

#2804 send_milestone_notification in own job
  app/jobs/notifications/milestone_job.rb
  app/labor/article_analytics_fetcher.rb
  app/models/notification.rb
  app/services/notifications/milestone/send.rb
  spec/jobs/notifications/milestone_job_spec.rb
  spec/labor/article_analytics_fetcher_spec.rb
  spec/models/notification_spec.rb
  spec/services/notifications/milestone/send_spec.rb
Labels: PR: reviewed-approved

#2855 Fix up articles controller
  app/assets/stylesheets/preact/article-form.scss
  app/controllers/articles_controller.rb
  app/javascript/article-form/articleForm.jsx
  app/services/article_creation_service.rb
  app/views/articles/_v2_form.html.erb
  spec/requests/articles_create_spec.rb
  spec/requests/articles_update_spec.rb
Labels: PR: unreviewed

#2856 Render correct editor based on article's existing format
  app/controllers/articles_controller.rb
  app/models/article.rb
  app/views/articles/_v2_form.html.erb
  app/views/articles/edit.html.erb
  spec/models/article_spec.rb
  spec/requests/articles_spec.rb
Labels: PR: unreviewed

#2861 Ensure the collection always belongs to the article owner
  app/services/articles/updater.rb
  spec/requests/api/v0/articles_spec.rb
Labels: PR: reviewed-approved

#2860 Unpack milestone hash
  app/jobs/notifications/milestone_job.rb
  app/models/notification.rb
  spec/jobs/notifications/milestone_job_spec.rb
Labels: PR: reviewed-approved

#2858 Add description to articles create/update API
  app/controllers/api/v0/articles_controller.rb
  app/models/article.rb
  spec/requests/api/v0/articles_spec.rb
Labels: PR: reviewed-approved

#2859 Articles update API: send publishing notification and set edited_at
  app/services/articles/updater.rb
  spec/requests/api/v0/articles_spec.rb
Labels: PR: reviewed-approved

#2857 Use cached_tag_list_array for tags
  app/views/api/v0/articles/show.json.jbuilder
  spec/requests/api/v0/articles_spec.rb
Labels: PR: reviewed-approved

#2865 Don't fail when twitch returns no user data, fixes #2784
  app/services/streams/twitch_webhook/register.rb
  spec/services/streams/twitch_webhook/register_spec.rb
Labels: PR: reviewed-approved

#2863 Add Submit Button to Integrations Tab
  app/views/users/_integrations.html.erb
  spec/system/user/user_edits_integrations_spec.rb
Labels: PR: reviewed-approved

#2477 Add visual indicator for chat channel more details
  app/assets/stylesheets/chat.scss
  app/javascript/chat/__tests__/__snapshots__/userDetails.test.jsx.snap
  app/javascript/chat/chat.jsx
  app/javascript/chat/content.jsx
  app/javascript/chat/userDetails.jsx
Labels: PR: unreviewed

#2851 Limit number of cover image uploads per 30 seconds
  app/controllers/image_uploads_controller.rb
  app/labor/rate_limit_checker.rb
  spec/requests/image_uploads_spec.rb
Labels: PR: reviewed-approved

#2874 Add awesome_print to development/test gems
  Gemfile
  Gemfile.lock
Labels: PR: reviewed-approved

#2875 Add rhymes to core team in README [ci skip]
  README.md
Labels: PR: reviewed-approved

#2903 Add safe navigation within chatchannelmemberships and remove some con…
  app/javascript/article-form/__tests__/articleForm.test.jsx
  app/javascript/chat/article.jsx
  app/javascript/chat/channelDetails.jsx
  app/javascript/chat/channels.jsx
  app/javascript/chat/chat.jsx
  app/models/chat_channel_membership.rb
Labels: PR: unreviewed

#2884 Add Anchor Links To The Post Editor Guide
  app/views/pages/_editor_guide_text.html.erb
Labels: PR: reviewed-approved

#2905 Remove some dead code for very minor perf improvements and code quality
  app/assets/javascripts/initializePage.js.erb
  app/assets/javascripts/initializers/initializeAllFollowButts.js
  app/assets/javascripts/initializers/initializeArticleReactions.js
  app/assets/javascripts/initializers/initializeSplitTestTracking.js
  app/assets/javascripts/utilities/showModal.js
  app/helpers/application_helper.rb
  app/helpers/articles_helper.rb
  app/views/articles/_follow_check_script.html.erb
  app/views/articles/_markdown_form.html.erb
  app/views/notifications/_signup_cta_test.html.erb
  app/views/notifications/index.html.erb
  spec/requests/notifications_spec.rb
Labels: PR: unreviewed

#2882 Move remove_all notifications method in own job
  app/jobs/notifications/remove_all_job.rb
  app/models/notification.rb
  app/services/notifications/remove_all.rb
  spec/jobs/notifications/remove_all_job_spec.rb
  spec/services/notifications/remove_all_spec.rb
Labels: PR: reviewed-approved

#2906 Fix date related spec failures
  spec/system/articles/user_visits_an_article_spec.rb
  spec/system/homepage/user_visits_homepage_articles_spec.rb
Labels: PR: unreviewed

#2904 Fix organization article ownership code
  app/controllers/articles_controller.rb
  spec/requests/articles_update_spec.rb
Labels: PR: reviewed-approved

#2876 Some small performance improvements
  Gemfile
  app/controllers/api/v0/github_repos_controller.rb
  app/controllers/api/v0/users_controller.rb
  app/controllers/giveaways_controller.rb
  app/controllers/internal/classified_listings_controller.rb
  app/controllers/internal/events_controller.rb
  app/controllers/internal/feedback_messages_controller.rb
  app/controllers/internal/pages_controller.rb
  app/controllers/internal/tags_controller.rb
  app/controllers/internal/users_controller.rb
  app/models/user.rb
  app/views/internal/classified_listings/index.html.erb
  config/environments/development.rb
  config/environments/test.rb
  config/routes.rb
Labels: PR: reviewed-approved

#2878 Implemented ActiveJob for RateLimitChecker Job
  app/jobs/rate_limit_checker_job.rb
  app/labor/rate_limit_checker.rb
  app/services/ping_admins.rb
  spec/jobs/rate_limit_checker_job_spec.rb
Labels: PR: reviewed-approved

#2913 Articles API: fix update org and add datetimes
  app/services/articles/updater.rb
  app/views/api/v0/articles/show.json.jbuilder
  spec/requests/api/v0/articles_spec.rb
Labels: PR: reviewed-approved

#2912 Add latest listings to home page
  app/assets/stylesheets/articles.scss
  app/controllers/classified_listings_controller.rb
  app/controllers/stories_controller.rb
  app/models/article.rb
  app/models/classified_listing.rb
  app/views/articles/_sidebar_additional.html.erb
  app/views/layouts/_user_config.html.erb
  spec/requests/stories_index_spec.rb
Labels: PR: unreviewed

#2909 improve contrast of badge-reward-message
  app/assets/stylesheets/notifications.scss
Labels: PR: reviewed-approved

#2915 Add API portal
  app/views/pages/api.html.erb
  config/routes.rb
  spec/requests/pages_spec.rb
Labels: PR: unreviewed

#2921 Add PWA target blank functionality
  app/assets/javascripts/initializers/initializePWAFunctionality.js
Labels: PR: unreviewed

#2923 Add noopener to external target blank links
  app/assets/javascripts/initializers/initializePWAFunctionality.js
Labels: PR: unreviewed

#2870 Update Slack Notifications
  app/observers/application_observer.rb
  app/observers/article_observer.rb
  app/observers/comment_observer.rb
  spec/observers/article_observer_spec.rb
  spec/observers/comment_observer_spec.rb
Labels: PR: reviewed-approved

#2918 Remove trailing dot from API token message [ci skip]
  app/controllers/api_secrets_controller.rb
Labels: PR: reviewed-approved

#2920 Do not ask to unpublish a draft article
  app/views/articles/delete_confirm.html.erb
Labels: PR: reviewed-approved

#2922 Article creation: fix improper error messaging
  app/controllers/articles_controller.rb
  app/javascript/article-form/elements/errors.jsx
  app/services/article_creation_service.rb
Labels: PR: reviewed-approved

#2910 Closes #2671 by fixing the issue with the welcome message.
  app/assets/stylesheets/preact/onboarding-modal.scss
Labels: PR: reviewed-approved

#2926 Award credits only if payment is successful
  app/controllers/credits_controller.rb
  spec/requests/credits_spec.rb
Labels: PR: reviewed-approved

#2930 Fix bug to allow users to remove org from article
  app/controllers/articles_controller.rb
  spec/requests/articles_update_spec.rb
Labels: PR: unreviewed

#2928 Make home page listings minimizeable
  app/assets/stylesheets/articles.scss
  app/assets/stylesheets/scaffolds.scss
  app/javascript/packs/homePage.js
  app/views/articles/_sidebar_additional.html.erb
  app/views/articles/index.html.erb
  app/views/layouts/_user_config.html.erb
Labels: PR: unreviewed

#2927 Add a proper exception in case of XSS attempt in markdown
  app/labor/markdown_parser.rb
  spec/labor/markdown_parser_spec.rb
Labels: PR: reviewed-approved

#2908 Internal Updates - Bust Cache for Listings and Add Note for Credits
  app/controllers/internal/classified_listings_controller.rb
  app/views/internal/users/_credits.erb
Labels: PR: reviewed-approved

#2931 Internal Listings View Enhancement
  app/controllers/internal/classified_listings_controller.rb
  app/models/organization.rb
  app/models/user.rb
  app/views/internal/classified_listings/edit.html.erb
  app/views/internal/classified_listings/index.html.erb
  app/views/layouts/internal.html.erb
Labels: PR: reviewed-approved

#2932 Fix wording in readme.md [skip ci]
  README.md
Labels: PR: reviewed-approved

#2936 API docs: Adjust document and add syntax highlight [skip ci]
  app/views/pages/api.html.erb
Labels: PR: reviewed-approved

#2869 Fixes Twitter video control bug
  app/views/liquids/_tweet.html.erb
  spec/support/fixtures/approvals/liquid_tweet_tag_spec.approved.html
Labels: PR: unreviewed

#2938 Sort internal/listings by recently bumped listings
  app/controllers/internal/classified_listings_controller.rb
Labels: PR: unreviewed

#2935 Moved notifying followers to a separate ActiveJob #1996
  app/jobs/notifications/notifiable_action_job.rb
  app/models/notification.rb
  app/services/notifications/notifiable_action/send.rb
  spec/jobs/notifications/notifiable_action_job_spec.rb
  spec/models/notification_spec.rb
  spec/services/notifications/notifiable_action/send_spec.rb
Labels: PR: reviewed-approved

#2948 Bug/markdown underscores in usernames
  app/labor/markdown_fixer.rb
  app/models/comment.rb
  spec/labor/markdown_fixer_spec.rb
Labels: PR: reviewed-approved

#2866 Move updating twitch username to a separate action #2784
  app/controllers/users_controller.rb
  app/policies/user_policy.rb
  app/views/users/_integrations.html.erb
  config/routes.rb
  spec/requests/user_settings_spec.rb
  spec/system/user/user_edits_integrations_spec.rb
Labels: PR: reviewed-approved

#2953 Fix some connect bugs with wrong url and remove some dead code
  app/assets/stylesheets/article_form.scss
  app/assets/stylesheets/minimal.scss
  app/controllers/followed_articles_controller.rb
  app/javascript/src/utils/getUnopenedChannels.jsx
  app/jobs/articles/score_calc_job.rb
  app/labor/flare_tag.rb
  app/models/article.rb
  app/views/articles/_hiring_form.html.erb
  spec/models/article_spec.rb
  spec/requests/followed_articles_spec.rb
  spec/requests/follows_create_spec.rb
Labels: PR: unreviewed

#2945 Docs: Fixes broken doc links
  docs/getting-started/pull-request.md
  docs/installation/readme.md
  docs/tests/integration-tests.md
Labels: PR: reviewed-approved

#2947 Use consistent colors for inline code, including night theme
  app/assets/stylesheets/article-show.scss
  app/assets/stylesheets/comments.scss
  app/views/layouts/_user_config.html.erb
Labels: PR: reviewed-approved

#2941 Unskip all skipped specs
  app/controllers/videos_controller.rb
  app/views/videos/js_response.js.erb
  db/schema.rb
  spec/models/comment_spec.rb
  spec/models/html_variant_success_spec.rb
  spec/models/html_variant_trial_spec.rb
  spec/models/page_view_spec.rb
  spec/rails_helper.rb
  spec/requests/classified_listings_spec.rb
  spec/requests/comments_spec.rb
  spec/requests/dashboard_spec.rb
  spec/requests/delayed_job_spec.rb
  spec/requests/feedback_messages_create_spec.rb
  spec/requests/follows_show_spec.rb
  spec/requests/follows_update_spec.rb
  spec/requests/internal_events_spec.rb
  spec/requests/internal_feedback_messages_spec.rb
  spec/requests/internal_reactions_spec.rb
  spec/requests/notifications_spec.rb
  spec/requests/reading_list_index_spec.rb
  spec/requests/reading_list_items_spec.rb
  spec/requests/registration_spec.rb
  spec/requests/stories_index_spec.rb
  spec/requests/user_settings_spec.rb
  spec/requests/users_api_spec.rb
  spec/requests/users_onboarding_spec.rb
  spec/requests/videos_spec.rb
  spec/services/tag_adjustment_update_service_spec.rb
  spec/support/fixtures/approvals/user_preview_article_body.approved.html
  spec/support/initializers/capybara.rb
  spec/system/homepage/user_visits_homepage_spec.rb
  spec/system/user_fills_out_givaway_form_spec.rb
  spec/system/user_selects_looking_for_work.rb
  spec/system/user_uses_the_editor_spec.rb
  spec/system/user_visits_tags_page_spec.rb
Labels: PR: reviewed-approved

#2962 Implemented ActiveJob for badge_achievements#send_email_notification
  app/jobs/badge_achievements/send_email_notification_job.rb
  app/models/badge_achievement.rb
  spec/jobs/badge_achievements/send_email_notification_job_spec.rb
Labels: PR: reviewed-approved

#2992 Fix css missing
  app/assets/stylesheets/article-form-needed-legacy.scss
  app/assets/stylesheets/minimal.scss
  app/views/layouts/_styles.html.erb
Labels: PR: unreviewed

#2985 Codepen Links with Underscore Usernames Flagged as Invalid
  app/liquid_tags/codepen_tag.rb
  spec/liquid_tags/codepen_tag_spec.rb
Labels: PR: reviewed-approved

#2993 Modify cache key for article sidebar cta
  app/views/articles/_sticky_nav.html.erb
Labels: PR: unreviewed

#2988 Require only used parts of Rails
  config/application.rb
  config/environments/test.rb
Labels: PR: reviewed-approved

#2965 Refactor: fix issues raised by bullet
  app/controllers/api/v0/comments_controller.rb
  app/controllers/api/v0/podcast_episodes_controller.rb
  app/controllers/articles_controller.rb
  app/controllers/comments_controller.rb
  app/controllers/dashboards_controller.rb
  app/controllers/moderations_controller.rb
  app/controllers/podcast_episodes_controller.rb
  app/labor/article_suggester.rb
  app/labor/cache_buster.rb
  app/models/article.rb
  app/models/comment.rb
  app/services/article_api_index_service.rb
  app/services/articles/updater.rb
  app/services/moderator/delete_user.rb
  app/services/moderator/manage_activity_and_roles.rb
  app/views/api/v0/comments/index.json.jbuilder
  app/views/articles/_bottom_content.html.erb
  app/views/articles/_v2_form.html.erb
  app/views/articles/_video_player.html.erb
  app/views/articles/edit.html.erb
  app/views/articles/new.html.erb
  app/views/articles/show.html.erb
  app/views/comments/index.html.erb
  app/views/dashboards/_dashboard_article.html.erb
  app/views/dashboards/show.html.erb
  app/views/moderations/index.html.erb
  config/environments/test.rb
  spec/labor/article_suggester_spec.rb
  spec/requests/articles_spec.rb
  spec/requests/moderations_spec.rb
Labels: PR: reviewed-approved

#2980 Cleanup bodyPreview component
  app/controllers/articles_controller.rb
  app/javascript/article-form/elements/bodyPreview.jsx
Labels: PR: reviewed-approved

#3000 fix(reading-list): better spacing for Save and Bookmark span
  app/assets/stylesheets/readinglist.scss
  app/javascript/readingList/readingList.jsx
Labels: PR: reviewed-approved

#2999 Fix a validation error when creating notifications #2525
  app/services/notifications/reactions/send.rb
  spec/models/notification_spec.rb
  spec/services/notifications/reactions/send_spec.rb
Labels: PR: reviewed-approved

#2991 Guard bust_comment against nil commentable
  app/labor/cache_buster.rb
  spec/labor/cache_buster_spec.rb
Labels: PR: reviewed-approved

#2946 Move remove_each notifications method in own job
  app/jobs/notifications/remove_each_job.rb
  app/models/notification.rb
  app/services/notifications/remove_each.rb
  spec/jobs/notifications/remove_each_job_spec.rb
  spec/models/notification_spec.rb
  spec/services/notifications/remove_each_spec.rb
Labels: PR: reviewed-approved
