Repository forem/forem, pull requests merged in 2019-04, with the labels that each got.

#2248 Add published in the SQL query to retrieve article
  app/controllers/api/v0/articles_controller.rb
  spec/requests/api/v0/articles_spec.rb
Labels: PR: reviewed-approved

#2257 Make comic sans default
  app/assets/stylesheets/variables.scss
  app/views/articles/_actions.html.erb
  app/views/articles/_sticky_nav.html.erb
  app/views/layouts/application.html.erb
Labels: PR: unreviewed

#2282 Allow orgs to be marked as sponsors
  app/dashboards/organization_dashboard.rb
  app/views/articles/_sidebar.html.erb
  db/migrate/20190401193017_add_sponsor_link_to_organizations.rb
  db/schema.rb
  spec/requests/stories_index_spec.rb
Labels: PR: unreviewed

#2283 Ignore unnecessary airbrake notices
  app/assets/javascripts/base.js.erb
  config/initializers/airbrake.rb
Labels: PR: unreviewed

#2284 Add sponsors to sponsors page and add sponsor order field
  app/views/articles/_sidebar.html.erb
  app/views/pages/sponsors.html.erb
  db/migrate/20190401213605_add_sponsorship_order_to_organizations.rb
  db/schema.rb
Labels: PR: unreviewed

#2270 Extract "followers" action from "show" in DashboardsController
  app/controllers/dashboards_controller.rb
  app/views/dashboards/_actions.html.erb
  app/views/dashboards/followers.html.erb
  app/views/dashboards/show.html.erb
  config/routes.rb
Labels: PR: reviewed-approved

#2289 Some night theme code, other style adjustments, and extracted app name into ENV var
  Envfile
  app/assets/javascripts/manifest.json.erb
  app/assets/stylesheets/articles.scss
  app/assets/stylesheets/preact/article-form.scss
  app/assets/stylesheets/scaffolds.scss
  app/assets/stylesheets/sidebar-data.scss
  app/helpers/application_helper.rb
  app/views/articles/_sidebar.html.erb
  app/views/articles/_sidebar_additional.html.erb
  app/views/articles/index.html.erb
  app/views/layouts/_footer.html.erb
  app/views/layouts/_signup_modal.html.erb
  app/views/layouts/_top_bar.html.erb
  app/views/layouts/application.html.erb
  app/views/pages/about.html.erb
  app/views/pages/sponsors.html.erb
  app/views/users/_comments_section.html.erb
  app/views/users/show.html.erb
  spec/features/homepage/user_visits_homepage_spec.rb
  spec/features/organization/user_views_an_organization_spec.rb
  spec/features/user/view_user_index_spec.rb
  spec/features/user_logs_in_with_twitter_spec.rb
Labels: PR: unreviewed

#2285 Fixes night mode issue #2244
  app/assets/stylesheets/comments.scss
Labels: PR: reviewed-approved

#2237 Optimize sign in: User
  app/models/user.rb
  db/migrate/20190329103059_add_unique_index_to_users_email.rb
  db/schema.rb
Labels: PR: reviewed-approved

#2292 Conditionally run feed validation
  app/models/user.rb
Labels: PR: unreviewed

#2297 Add tests to PodcastEpisodesController
  app/controllers/api/v0/podcast_episodes_controller.rb
  config/routes.rb
  spec/requests/api/v0/podcasts_episodes_spec.rb
Labels: PR: unreviewed

#2287 New comment notifications to Active Jobs #1996
  app/jobs/notifications/new_comment_job.rb
  app/models/notification.rb
  app/services/notifications.rb
  app/services/notifications/new_comment/send.rb
  spec/jobs/notifications/new_comment_job_spec.rb
  spec/services/notifications/new_comment/send_spec.rb
Labels: PR: reviewed-approved

#1408 Upgrade Rails to 5.2.3
  Gemfile
  Gemfile.lock
  app/controllers/internal/users_controller.rb
  app/controllers/pages_controller.rb
  app/labor/sticky_article_collection.rb
  app/labor/unread_notifications_emailer.rb
  app/liquid_tags/tweet_tag.rb
  app/models/chat_channel.rb
  app/models/html_variant.rb
  app/services/suggester/articles/classic.rb
  app/services/suggester/articles/high_quality.rb
  app/services/suggester/users/sidebar.rb
  app/views/articles/_sidebar.html.erb
  app/views/articles/_sidebar_additional.html.erb
  bin/bundle
  bin/rails
  bin/rake
  bin/setup
  bin/update
  bin/yarn
  config/boot.rb
  config/cable.yml
  config/environments/development.rb
  config/environments/test.rb
  config/initializers/application_controller_renderer.rb
  config/initializers/content_security_policy.rb
  config/initializers/new_framework_defaults_5_2.rb
  config/puma.rb
  config/storage.yml
  db/seeds.rb
  spec/support/fixtures/approvals/liquid_tweet_tag_spec.approved.html
Labels: PR: reviewed-approved, dependencies, ruby

#2298 Fix Blogcast styling issues
  app/liquid_tags/blogcast_tag.rb
Labels: PR: reviewed-approved

#2300 Use nil instead of empty string for banishing to account for new DB constraints
  app/services/moderator/banish_user.rb
Labels: PR: reviewed-approved

#2293 Add API Analytics Endpoints
  app/controllers/api/v0/analytics_controller.rb
  app/controllers/api/v0/api_controller.rb
  app/controllers/application_controller.rb
  app/errors/unauthorized_error.rb
  app/services/analytics_service.rb
  config/application.rb
  config/routes.rb
  spec/factories/users.rb
  spec/requests/api/v0/analytics_spec.rb
  spec/support/api_analytics_shared_examples.rb
Labels: PR: reviewed-approved

#2308 Simplify AnalyticsService code
  app/controllers/api/v0/analytics_controller.rb
  app/services/analytics_service.rb
  spec/factories/page_views.rb
  spec/services/analytics/analytics_service_spec.rb
  spec/support/api_analytics_shared_examples.rb
Labels: PR: reviewed-approved

#2306 Add ability for trusted users to suggest social copy for posts
  app/controllers/buffer_updates_controller.rb
  app/controllers/internal/articles_controller.rb
  app/controllers/internal/buffer_updates_controller.rb
  app/controllers/moderations_controller.rb
  app/models/buffer_update.rb
  app/policies/application_policy.rb
  app/policies/buffer_update_policy.rb
  app/views/internal/articles/_individual_article.html.erb
  app/views/internal/articles/index.html.erb
  app/views/moderations/index.html.erb
  app/views/moderations/mod.html.erb
  config/routes.rb
  db/migrate/20190402224426_add_user_info_to_buffer_updates.rb
  db/schema.rb
  spec/policies/buffer_update_policy_spec.rb
  spec/requests/buffer_updates_spec.rb
  spec/requests/internal_buffer_updates_spec.rb
Labels: PR: unreviewed

#2310 Finalize suggest-a-tweet functionality
  app/controllers/buffer_updates_controller.rb
  app/views/internal/articles/_individual_article.html.erb
  app/views/internal/articles/index.html.erb
  spec/requests/buffer_updates_spec.rb
Labels: PR: unreviewed

#2313 Update rubocop to 0.67
  .codeclimate.yml
  .rubocop.yml
  Gemfile
  Gemfile.lock
  app/controllers/omniauth_callbacks_controller.rb
  app/controllers/stories_controller.rb
  app/labor/rate_limit_checker.rb
  config/routes.rb
  spec/system/comments/user_fills_out_comment_spec.rb
  spec/system/organization/user_updates_org_settings_spec.rb
Labels: PR: reviewed-approved

#2291 "/videos"
  app/assets/javascripts/initializers/initScrolling.js.erb
  app/assets/stylesheets/minimal.scss
  app/assets/stylesheets/video-collection.scss
  app/controllers/api/v0/videos_controller.rb
  app/controllers/videos_controller.rb
  app/views/api/v0/videos/index.json.jbuilder
  app/views/videos/index.html.erb
  config/routes.rb
Labels: PR: reviewed-approved

#2315 Clean up videos page and add tests
  app/assets/stylesheets/video-collection.scss
  app/controllers/api/v0/videos_controller.rb
  app/controllers/videos_controller.rb
  app/labor/cache_buster.rb
  app/views/layouts/_styles.html.erb
  app/views/videos/index.html.erb
  spec/requests/videos_api_spec.rb
  spec/requests/videos_spec.rb
Labels: PR: unreviewed

#2318 Darken tag following weight input's background
  app/assets/stylesheets/dashboard.scss
Labels: PR: reviewed-approved

#2314 Fixed some Style/* rubocop violations
  .rubocop.yml
  .rubocop_todo.yml
  app/labor/hex_comparer.rb
  app/liquid_tags/github_tag/github_issue_tag.rb
  app/models/github_issue.rb
  app/services/rss_reader.rb
  config/initializers/honeycomb.rb
  config/initializers/reserved_words.rb
  spec/labor/hex_comparer_spec.rb
Labels: PR: unreviewed

#2316 Modify social share button and functionality
  app/assets/stylesheets/article-show.scss
  app/assets/stylesheets/articles.scss
  app/assets/stylesheets/chat.scss
  app/assets/stylesheets/ltags/GithubReadmeTag.scss
  app/assets/stylesheets/ltags/GithubTag.scss
  app/controllers/buffer_updates_controller.rb
  app/controllers/internal/articles_controller.rb
  app/javascript/chat/__tests__/__snapshots__/message.test.jsx.snap
  app/javascript/chat/chat.jsx
  app/javascript/chat/message.jsx
  app/views/articles/_actions.html.erb
  app/views/articles/_sticky_nav.html.erb
  app/views/moderations/index.html.erb
  app/views/moderations/mod.html.erb
  spec/requests/buffer_updates_spec.rb
Labels: PR: unreviewed

#2302 integrations github repos hover and text color
  app/assets/stylesheets/settings.scss
Labels: PR: reviewed-approved

#2319 Upgrade Honeycomb gem, fix and improve RssReader tests
  Gemfile
  Gemfile.lock
  app/controllers/application_controller.rb
  app/services/rss_reader.rb
  config.ru
  config/initializers/honeycomb.rb
  config/initializers/shutdown.rb
  lib/instrumentation.rb
  spec/fixtures/approvals/rssreader/fetch_user/gets_articles_for_user.approved.txt
  spec/services/rss_reader_spec.rb
Labels: PR: reviewed-approved

#2321 Automated DEV setup using Gitpod
  .gitpod.dockerfile
  .gitpod.yml
  README.md
Labels: PR: reviewed-approved

#2246 Fixed fluid-comments in dark mode
  app/assets/stylesheets/ltags/DevCommentTag.scss
Labels: PR: reviewed-approved

#2324 Improve rubocop config #2021
  .rubocop.yml
  .rubocop_todo.yml
  Gemfile
Labels: PR: reviewed-approved

#2335 Don't make additional SQL query on remembering user
  app/models/user.rb
  app/services/authorization_service.rb
  spec/services/authorization_service_spec.rb
Labels: PR: unreviewed

#2338 Fix human language detection
  Gemfile
  Gemfile.lock
  app/assets/javascripts/initializers/initializeFetchFollowedArticles.js.erb
  app/controllers/async_info_controller.rb
  app/controllers/stories_controller.rb
  app/decorators/user_decorator.rb
  app/labor/language_detector.rb
  app/models/article.rb
  app/models/user.rb
  app/policies/user_policy.rb
  app/views/stories/_main_stories_feed.html.erb
  app/views/users/_misc.html.erb
  spec/labor/language_detector_spec.rb
  spec/models/user_spec.rb
Labels: PR: unreviewed

#2341 Fix social share text bugs
  app/controllers/buffer_updates_controller.rb
  app/views/internal/articles/index.html.erb
Labels: PR: unreviewed

#2343 Add tech admin role and allow tech admins to view /delayed_job
  app/models/role.rb
  app/models/user.rb
  config/routes.rb
  spec/requests/delayed_job_spec.rb
Labels: PR: reviewed-approved

#2340 Enable Layout/AlignParameters
  .rubocop_todo.yml
  app/black_box/black_box.rb
  app/black_box/google_analytics.rb
  app/controllers/api/v0/articles_controller.rb
  app/controllers/api/v0/comments_controller.rb
  app/controllers/api/v0/podcast_episodes_controller.rb
  app/controllers/api/v0/tags_controller.rb
  app/controllers/api/v0/videos_controller.rb
  app/controllers/chat_channels_controller.rb
  app/controllers/followed_articles_controller.rb
  app/controllers/github_repos_controller.rb
  app/controllers/internal/events_controller.rb
  app/controllers/internal/users_controller.rb
  app/controllers/omniauth_callbacks_controller.rb
  app/controllers/podcast_episodes_controller.rb
  app/controllers/pusher_controller.rb
  app/controllers/stripe_active_cards_controller.rb
  app/controllers/users_controller.rb
  app/helpers/application_helper.rb
  app/labor/cache_buster.rb
  app/labor/coupon_generator.rb
  app/labor/email_logic.rb
  app/labor/generated_image.rb
  app/labor/markdown_parser.rb
  app/labor/profile_image.rb
  app/liquid_tags/gist_tag.rb
  app/liquid_tags/podcast_tag.rb
  app/models/article.rb
  app/models/badge_achievement.rb
  app/models/chat_channel.rb
  app/models/comment.rb
  app/models/display_ad.rb
  app/models/html_variant.rb
  app/models/job_opportunity.rb
  app/models/organization.rb
  app/models/podcast_episode.rb
  app/models/reaction.rb
  app/models/tag.rb
  app/models/user.rb
  app/observers/application_observer.rb
  app/observers/article_observer.rb
  app/views/articles/feed.rss.builder
  config/environments/production.rb
  config/initializers/devise.rb
  config/initializers/serviceworker.rb
  spec/requests/article_mutes_spec.rb
  spec/requests/buffer_updates_spec.rb
  spec/requests/chat_channels_spec.rb
  spec/requests/comments_spec.rb
  spec/requests/follows_update_spec.rb
  spec/requests/internal_buffer_updates_spec.rb
  spec/requests/video_states_update_spec.rb
  spec/support/initializers/capybara.rb
Labels: PR: reviewed-approved

#2342 Remove unnecessary queries from user save
  app/models/article.rb
  app/models/user.rb
  app/services/suggester/users/recent.rb
  spec/requests/users_api_spec.rb
Labels: PR: unreviewed

#2305 Set users email to nil instead of blank
  app/models/user.rb
  db/migrate/20190404102732_allow_null_on_users_email.rb
  db/schema.rb
  spec/models/user_spec.rb
  spec/requests/dashboard_spec.rb
Labels: PR: unreviewed

#2339 Add single article functionality to articles analytics
  app/controllers/api/v0/analytics_controller.rb
  app/services/analytics_service.rb
  spec/services/analytics/analytics_service_spec.rb
  spec/support/api_analytics_shared_examples.rb
Labels: PR: reviewed-approved

#2346 Only set cache control header on videos index page
  app/controllers/videos_controller.rb
Labels: PR: unreviewed

#2166 UX: Better width for footer and small refactors
  app/assets/stylesheets/footer.scss
  app/assets/stylesheets/notifications.scss
  app/views/layouts/_footer.html.erb
  app/views/reading_list_items/index.html.erb
Labels: PR: reviewed-approved

#2350 Do not require author for displaying notes in /internal
  app/views/internal/users/_notes.erb
Labels: PR: reviewed-approved

#2334 Enable Rails/TimeZone cop
  .rubocop.yml
  app/jobs/follows/touch_follower_job.rb
  app/models/notification.rb
  spec/jobs/follows/send_email_notification_job_spec.rb
  spec/jobs/follows/touch_follower_job_spec.rb
  spec/jobs/reactions/update_reactable_job_spec.rb
  spec/jobs/users/touch_job_spec.rb
  spec/models/follow_spec.rb
  spec/models/reaction_create_spec.rb
  spec/services/notifications/new_follower/send_spec.rb
  spec/services/notifications/reactions/send_spec.rb
  spec/system/articles/user_visits_articles_by_tag_spec.rb
Labels: PR: reviewed-approved

#2352 Add phpc.social to Mastodon List
  app/lib/constants.rb
Labels: PR: unreviewed

#2358 Rubocop: regenerate todo and fix RSpec/FilePath
  .rubocop.yml
  .rubocop_todo.yml
  spec/liquid_tags/liquid/raw_spec.rb
Labels: PR: reviewed-approved

#2363 UX: Fixed comment preview in darkmode
  app/assets/stylesheets/comments.scss
Labels: PR: unreviewed

#2362 Manage tag and community mod lists in Mailchimp
  Envfile
  app/controllers/internal/tags_controller.rb
  app/labor/assign_tag_moderator.rb
  app/labor/mailchimp_bot.rb
  app/models/user.rb
  app/policies/user_policy.rb
  app/services/moderator/manage_activity_and_roles.rb
  app/views/users/_notifications.html.erb
  config/routes.rb
  db/migrate/20190405190915_add_mailchimp_lists_to_users.rb
  db/schema.rb
  spec/labor/mailchimp_bot_spec.rb
Labels: PR: reviewed-approved

#2378 Remove honeycomb code from config.ru
  config.ru
Labels: PR: unreviewed

#2379 Ensure Gitpod init always succeeds
  .gitpod.yml
Labels: PR: reviewed-approved

#2376 Remove unused attr_reader
  app/services/rss_reader.rb
Labels: PR: reviewed-approved

#2374 Use published scope for articles
  .erb-lint.yml
  app/controllers/api/v0/articles_controller.rb
  app/controllers/api/v0/videos_controller.rb
  app/controllers/articles_controller.rb
  app/controllers/internal/articles_controller.rb
  app/controllers/moderations_controller.rb
  app/controllers/pages_controller.rb
  app/controllers/stories_controller.rb
  app/controllers/videos_controller.rb
  app/facades/dashboard/pro.rb
  app/labor/article_suggester.rb
  app/labor/badge_rewarder.rb
  app/labor/cache_buster.rb
  app/labor/email_logic.rb
  app/labor/rate_limit_checker.rb
  app/labor/sticky_article_collection.rb
  app/labor/user_states.rb
  app/models/article.rb
  app/models/user.rb
  app/services/analytics_service.rb
  app/services/article_api_index_service.rb
  app/services/suggester/articles/classic.rb
  app/services/suggester/articles/high_quality.rb
  app/services/suggester/users/recent.rb
  app/services/suggester/users/sidebar.rb
  app/views/articles/_collection.html.erb
  app/views/articles/_special_sidebar.html.erb
  app/views/articles/tags/_sidebar.html.erb
  app/views/mailers/digest_mailer/digest_email.html.erb
  app/views/stories/_main_stories_feed.html.erb
  app/views/users/_sidebar.html.erb
  config/sitemap.rb
  lib/tasks/fetch.rake
Labels: PR: reviewed-approved

#2364 Community Moderation Page
  app/views/pages/community_moderation.html.erb
  app/views/pages/tag_moderation.html.erb
  config/routes.rb
Labels: PR: reviewed-approved

#2383 [SMALL] UX: Fixed figcaption in nightmode
  app/assets/stylesheets/article-show.scss
Labels: PR: reviewed-approved

#2384 [SMALL] UX: Fixed no results found in nightmode
  app/assets/stylesheets/articles.scss
Labels: PR: reviewed-approved

#2372 settings.scss: Fix color contrast in text colors
  app/assets/stylesheets/settings.scss
Labels: PR: unreviewed

#2386 Touch profile_updated_at when updating social usernames
  app/controllers/users_controller.rb
  app/services/authorization_service.rb
  spec/requests/user_settings_spec.rb
  spec/services/authorization_service_spec.rb
Labels: PR: reviewed-approved

#2390 Grammatical fix
  app/views/pages/community_moderation.html.erb
Labels: PR: reviewed-approved

#2388 Fixed spacing typo
  app/views/pages/community_moderation.html.erb
Labels: PR: reviewed-approved

#2396 Fix typos
  app/views/pages/community_moderation.html.erb
Labels: PR: reviewed-approved

#2395 Use "touch" a little bit less
  app/controllers/organizations_controller.rb
  app/controllers/users_controller.rb
  app/models/comment.rb
  app/services/authorization_service.rb
Labels: PR: reviewed-approved

#2401 Add additional fragment caching to home page
  app/controllers/stories_controller.rb
  app/views/articles/index.html.erb
  app/views/stories/_main_stories_feed.html.erb
Labels: PR: unreviewed

#2404 Add sidebar condition for homepage cache
  app/views/articles/index.html.erb
Labels: PR: unreviewed

#2402 Remove unnecessary map functions in stories controller
  app/controllers/articles_controller.rb
  app/controllers/stories_controller.rb
Labels: PR: unreviewed

#2403 Add fragment cache to tag page
  app/views/articles/tag_index.html.erb
Labels: PR: unreviewed

#2413 Added missing indexes to the comments table
  db/migrate/20190412093614_add_comment_indexes.rb
  db/schema.rb
Labels: PR: unreviewed

#2382 UX: Fixed draft in nightmode
  app/assets/stylesheets/dashboard.scss
  app/views/dashboards/show.html.erb
Labels: PR: reviewed-approved

#2391 fixed grammar error in "thumbsdown" description
  app/views/pages/community_moderation.html.erb
Labels: PR: reviewed-approved

#2425 pinkify DEV
  app/models/user.rb
  app/views/layouts/application.html.erb
  app/views/users/_misc.html.erb
  spec/models/user_spec.rb
Labels: PR: reviewed-approved

#2427 Move themes config into separate partial and add logo theme-ability
  app/assets/stylesheets/settings.scss
  app/assets/stylesheets/top-bar.scss
  app/views/layouts/_user_config.html.erb
  app/views/layouts/application.html.erb
Labels: PR: unreviewed

#2423 remove Product Roadmap link from TOC
  README.md
Labels: PR: reviewed-approved

#2373 Move estimating user default language to ActiveJob
  app/jobs/users/estimate_default_language_job.rb
  app/models/user.rb
  app/services/users/estimate_default_language.rb
  spec/jobs/users/estimate_default_language_job_spec.rb
  spec/models/user_spec.rb
  spec/services/users/estimate_default_language_spec.rb
Labels: PR: reviewed-approved

#2415 Fix community name
  app/helpers/application_helper.rb
  app/views/articles/index.html.erb
  app/views/layouts/_signup_modal.html.erb
  app/views/layouts/application.html.erb
  app/views/videos/index.html.erb
  spec/helpers/application_helper_spec.rb
  spec/system/homepage/user_visits_homepage_articles_spec.rb
  spec/system/homepage/user_visits_homepage_spec.rb
  spec/system/videos/user_visits_videos_spec.rb
Labels: PR: unreviewed

#2360 Fix colon emoji in codeblock (#2216)
  app/labor/markdown_parser.rb
  spec/labor/markdown_parser_spec.rb
Labels: PR: reviewed-approved

#2430 UX: Several improvements for chat in nightmode
  app/assets/stylesheets/chat.scss
  app/assets/stylesheets/connect/_channel-details.scss
  app/assets/stylesheets/variables.scss
  app/javascript/chat/__tests__/__snapshots__/article.test.jsx.snap
  app/javascript/chat/__tests__/__snapshots__/channels.test.jsx.snap
  app/javascript/chat/__tests__/__snapshots__/chat.test.jsx.snap
  app/javascript/chat/__tests__/__snapshots__/userDetails.test.jsx.snap
  app/javascript/chat/__tests__/article.test.jsx
  app/javascript/chat/article.jsx
  app/javascript/chat/channels.jsx
  app/javascript/chat/chat.jsx
  app/javascript/chat/userDetails.jsx
Labels: PR: reviewed-approved

#2431 [SMALL] UX: Fixed dev badge in nightmode
  app/assets/stylesheets/variables.scss
  app/views/users/_profile.html.erb
Labels: PR: unreviewed

#2337 be able to sort dashboard articles (#1837)
  app/assets/javascripts/initializePage.js.erb
  app/assets/javascripts/initializers/initializeDashboardSort.js
  app/assets/stylesheets/dashboard.scss
  app/controllers/dashboards_controller.rb
  app/helpers/articles_helper.rb
  app/models/article.rb
  app/views/dashboards/_dashboard_article.html.erb
  app/views/dashboards/show.html.erb
  spec/system/dashboards/user_sorts_dashboard_articles_spec.rb
Labels: PR: reviewed-approved

#2447 Add short description for gems
  Gemfile
  Gemfile.lock
Labels: PR: unreviewed

#2449 Fix/augment dashboard and article view count issues
  app/assets/stylesheets/dashboard.scss
  app/controllers/page_views_controller.rb
  app/models/article.rb
  app/views/articles/_sidebar_additional.html.erb
  app/views/articles/tags/_sidebar_additional.html.erb
  app/views/dashboards/_dashboard_article.html.erb
  app/views/dashboards/show.html.erb
  app/views/layouts/_user_config.html.erb
  spec/models/article_spec.rb
  spec/requests/page_views_spec.rb
Labels: PR: unreviewed

#2451 Fix seo_boostable for latest
  app/models/article.rb
Labels: PR: unreviewed

#2450 Removed gems csv_shaper, bourbon and share_meow_client
  Envfile
  Gemfile
  Gemfile.lock
  config/initializers/share_meow_client.rb
Labels: PR: reviewed-approved

#2455 Modify sidebar seo-boostable cache
  app/models/article.rb
  app/views/articles/_sidebar_additional.html.erb
  app/views/articles/tags/_sidebar_additional.html.erb
Labels: PR: unreviewed

#2457 Add a blank href attribute if blank for GitHub readme tag
  app/liquid_tags/github_tag/github_readme_tag.rb
Labels: PR: reviewed-approved

#2458 Allow seo_boostable to better handle nil
  app/models/article.rb
  app/views/articles/_sidebar_additional.html.erb
  app/views/articles/tags/_sidebar_additional.html.erb
Labels: PR: unreviewed

#2460 [SMALL] UX: Twitter Liquid Tag Nightmode
  app/assets/stylesheets/ltags/TweetTag.scss
Labels: PR: reviewed-approved

#2461 Add GA_FETCH_RATE ENV var to ease rate limiting
  Envfile
  app/controllers/async_info_controller.rb
  app/controllers/dashboards_controller.rb
Labels: PR: unreviewed

#2459 UX: Liquid Tags Nightmode
  app/assets/stylesheets/ltags/TagTag.scss
  app/assets/stylesheets/variables.scss
Labels: PR: reviewed-approved

#2462 Delete jquery.highlighttextarea
  app/assets/javascripts/lib/jquery.highlighttextarea.js
  app/assets/stylesheets/jquery.highlighttextarea.scss
Labels: PR: reviewed-approved

#2465 Switch from chromedriver-helper to webdrivers
  .travis.yml
  Gemfile
  Gemfile.lock
  bin/chromedriver-update
  docs/testing.md
  spec/rails_helper.rb
  spec/support/initializers/capybara.rb
Labels: PR: reviewed-approved

#2454 [SMALL] UX: Fix comment preview loading in nightmode
  app/assets/stylesheets/comments.scss
Labels: PR: reviewed-approved

#2299 Move exporting into a job
  app/controllers/users_controller.rb
  app/jobs/export_content_job.rb
  spec/jobs/export_content_job_spec.rb
  spec/requests/user_settings_spec.rb
Labels: PR: reviewed-approved

#2281 db transactions for safer merging of users
  app/services/moderator/merge_user.rb
Labels: PR: reviewed-approved

#2467 Adjust badge streak copy for 16 week badge
  app/labor/badge_rewarder.rb
Labels: PR: unreviewed

#2392 console message ascii art & message to repo
  app/assets/javascripts/hello-dev.js
  app/views/layouts/_footer.html.erb
  config/initializers/assets.rb
Labels: PR: unreviewed

#2432 REF: react eslint
  .eslintignore
  app/javascript/article-form/elements/bodyPreview.jsx
  app/javascript/article-form/elements/errors.jsx
  app/javascript/article-form/elements/moreConfig.jsx
  app/javascript/article-form/elements/notice.jsx
  app/javascript/article-form/elements/orgSettings.jsx
  app/javascript/article-form/elements/tags.jsx
  app/javascript/chat/__tests__/channelDetails.test.jsx
  app/javascript/chat/__tests__/view.test.jsx
  app/javascript/chat/actions.js
  app/javascript/chat/channelDetails.jsx
  app/javascript/chat/codeEditor.jsx
  app/javascript/chat/compose.jsx
  app/javascript/chat/video.jsx
  app/javascript/chat/view.jsx
  app/javascript/packs/Onboarding.jsx
  app/javascript/packs/articleForm.jsx
  app/javascript/packs/githubRepos.jsx
  app/javascript/sidebar-widget/SidebarWidget.jsx
  app/javascript/src/Onboarding.jsx
  app/javascript/src/components/OnboardingArticle.jsx
  app/javascript/src/components/OnboardingArticles.jsx
  app/javascript/src/components/OnboardingProfile.jsx
  app/javascript/src/components/OnboardingSingleTag.jsx
  app/javascript/src/components/OnboardingTags.jsx
  app/javascript/src/components/OnboardingUsers.jsx
  app/javascript/src/components/OnboardingWelcome.jsx
  app/javascript/src/components/OnboardingWelcomeThread.jsx
  app/javascript/src/components/Search/Search.jsx
  app/javascript/src/components/UnopenedChannelNotice.jsx
  app/javascript/src/components/__stories__/OnboardingWelcome.stories.jsx
  app/javascript/src/components/__stories__/OnboardingWelcomeThread.stories.jsx
  app/javascript/src/utils/getUnopenedChannels.jsx
  package.json
Labels: PR: reviewed-approved

#2469 Allow API to return top articles
  app/services/article_api_index_service.rb
  spec/requests/api/v0/articles_spec.rb
Labels: PR: unreviewed

#1161 #118 Allow users to embed Medium posts with Liquid Tags
  app/labor/markdown_parser.rb
  app/liquid_tags/medium_tag.rb
  app/services/medium_article_retrieval_service.rb
  spec/liquid_tags/medium_tag_spec.rb
Labels: PR: reviewed-approved

#2466 Enable random order for specs
  config/environments/test.rb
  spec/jobs/follows/create_chat_channel_job_spec.rb
  spec/jobs/shared_examples/enqueues_job.rb
  spec/jobs/users/touch_job_spec.rb
  spec/models/article_destroy_spec.rb
  spec/models/article_spec.rb
  spec/models/follow_spec.rb
  spec/models/notification_spec.rb
  spec/models/reaction_create_spec.rb
  spec/models/reaction_destroy_spec.rb
  spec/models/user_spec.rb
  spec/observers/comment_observer_spec.rb
  spec/rails_helper.rb
  spec/requests/internal/users_spec.rb
  spec/requests/user_settings_spec.rb
  spec/spec_helper.rb
  spec/system/comments/user_fills_out_comment_spec.rb
  spec/system/dashboards/user_sorts_dashboard_articles_spec.rb
Labels: PR: unreviewed

#2472 Convert underscores in article slugs properly
  app/models/article.rb
  spec/models/article_spec.rb
Labels: PR: unreviewed

#2468 Release Open Inbox
  app/assets/stylesheets/chat.scss
  app/javascript/chat/__tests__/__snapshots__/userDetails.test.jsx.snap
  app/javascript/chat/userDetails.jsx
  app/views/users/_misc.html.erb
Labels: PR: reviewed-approved

#2473 Add inbox guidelines to users
  app/assets/javascripts/initializers/initScrolling.js.erb
  app/assets/stylesheets/user-profile-header.scss
  app/javascript/chat/content.jsx
  app/policies/user_policy.rb
  app/views/users/_misc.html.erb
  app/views/users/show.html.erb
  db/migrate/20190417171019_add_inbox_instructions_to_users.rb
  db/schema.rb
Labels: PR: unreviewed

#2476 Add caching for historical data
  app/services/analytics_service.rb
Labels: PR: reviewed-approved

#2482 Feature/filtered charts
  app/assets/stylesheets/dashboard.scss
  app/javascript/packs/proCharts.js
  app/views/dashboards/pro.html.erb
Labels: PR: reviewed-approved

#2484 Add nav buttons to pwa desktop
  app/assets/images/keyboard-left-arrow-button.svg
  app/assets/images/keyboard-right-arrow-button.svg
  app/assets/images/refresh-button.svg
  app/assets/javascripts/initializePage.js.erb
  app/assets/javascripts/initializers/initializePWAFunctionality.js
  app/assets/javascripts/manifest.json.erb
  app/assets/stylesheets/top-bar.scss
  app/views/layouts/_footer.html.erb
  app/views/layouts/_top_bar.html.erb
Labels: PR: unreviewed

#2486 Temporarily comment out random order in spec helper
  spec/spec_helper.rb
Labels: PR: unreviewed

#2488 Make Cards Change Dynamically and add Reader/Follower Charts
  app/assets/stylesheets/dashboard.scss
  app/javascript/packs/proCharts.js
  app/views/dashboards/pro.html.erb
Labels: PR: reviewed-approved

#2487 Remove extra param and add message for prefill
  app/assets/javascripts/initializers/initializeBaseTracking.js.erb
  app/assets/stylesheets/article_form.scss
  app/controllers/application_controller.rb
  app/views/articles/new.html.erb
  app/views/devise/registrations/_registration_form.html.erb
  app/views/layouts/_styles.html.erb
  spec/requests/editor_spec.rb
Labels: PR: unreviewed

#2491 Fix <br/> in footer.
  app/views/layouts/_footer.html.erb
Labels: PR: unreviewed

#2495 Fixed some frontend linting issues
  app/javascript/.eslintrc.js
  app/javascript/article-form/elements/__mocks__/algoliasearch.js
  app/javascript/chat/__mocks__/algoliasearchUsers.js
  app/javascript/chat/actions.js
  app/javascript/src/utils/__tests__/getUserData.test.js
  app/javascript/src/utils/getUserData.js
  app/javascript/src/utils/pusher.js
Labels: PR: reviewed-approved

#2481 Added troubleshooting for byebug without readline issue
  docs/installation/mac-os.md
Labels: PR: reviewed-approved

#2498 Add user_signed_in? to cache key for styles
  app/views/layouts/_styles.html.erb
Labels: PR: unreviewed

#2428 [SMALL] UX: Rename "Start an ask me anything" to "Start an AMA"
  app/views/articles/_sidebar_additional.html.erb
Labels: PR: reviewed-approved

#2500 Update docs
  docs/helpful-hints.md
  docs/installation/readme.md
Labels: PR: reviewed-approved

#2502 Disabled no-console for where we currently log an error.
  app/javascript/src/utils/sendFollowUser.js
Labels: PR: reviewed-approved

#2479 Added rbenv troubleshooting section.
  docs/installation/mac-os.md
Labels: PR: reviewed-approved

#2503 Show coupon codes on internal/users
  app/views/internal/users/show.html.erb
Labels: PR: reviewed-approved

#2516 Prevent creating reaction notifications with empty json_data
  app/services/notifications/reactions/send.rb
Labels: PR: reviewed-approved

#2517 Remove unused gem fake_stripe
  Gemfile
  Gemfile.lock
Labels: PR: reviewed-approved

#2485 Move Welcome Notification to Active Jobs
  app/jobs/notifications/welcome_notification_job.rb
  app/models/notification.rb
  app/services/notifications/welcome_notification/send.rb
  spec/jobs/notifications/welcome_notification_job_spec.rb
  spec/services/notifications/welcome_notification/send_spec.rb
Labels: PR: reviewed-approved

#2471 Add OrganizationMembership model
  app/controllers/organizations_controller.rb
  app/controllers/users_controller.rb
  app/models/organization_membership.rb
  app/models/role.rb
  app/models/user.rb
  app/policies/article_policy.rb
  app/services/membership_service.rb
  app/views/users/edit.html.erb
  db/migrate/20190415194929_create_organization_memberships.rb
  db/schema.rb
  spec/factories/organization_memberships.rb
  spec/factories/users.rb
  spec/models/organization_membership_spec.rb
  spec/models/user_spec.rb
  spec/policies/article_policy_spec.rb
  spec/requests/user_organization_spec.rb
Labels: PR: reviewed-approved

#2523 Add mailers specs for tracking
  app/mailers/notify_mailer.rb
  app/views/mailers/notify_mailer/account_deleted_email.html.erb
  app/views/mailers/notify_mailer/new_message_email.html.erb
  db/seeds.rb
  spec/mailers/.keep
  spec/mailers/digest_mailer_spec.rb
  spec/mailers/membership_mailer_spec.rb
  spec/mailers/notify_mailer_spec.rb
  spec/mailers/previews/notify_mailer_preview.rb
  spec/mailers/scholarship_mailer_spec.rb
  spec/rails_helper.rb
Labels: PR: reviewed-approved

#2529 Upgrade capybara to 3.18
  Gemfile
  Gemfile.lock
Labels: PR: reviewed-approved

#2532 Upgrade factory_bot_rails to 5.0.2
  Gemfile
  Gemfile.lock
  spec/factories/articles.rb
  spec/models/article_spec.rb
  spec/policies/api_secret_policy_spec.rb
  spec/policies/article_policy_spec.rb
  spec/policies/comment_policy_spec.rb
  spec/policies/github_repo_policy_spec.rb
Labels: PR: reviewed-approved

#2531 Upgrade emoji_regex to 2.0
  Gemfile
  Gemfile.lock
Labels: PR: reviewed-approved

#2534 Upgrade ahoy_email to 1.0.3
  Gemfile
  Gemfile.lock
  config/initializers/ahoy_email.rb
Labels: PR: reviewed-approved

#2543 Create assetlinks.json
  public/.well-known/assetlinks.json
Labels: PR: unreviewed

#2526 Upgrade airbrake to 9.1.0
  Gemfile
  Gemfile.lock
  config/initializers/airbrake.rb
  public/.well-known/assetlinks.json
Labels: PR: reviewed-approved

#2527 Upgrade brakeman to 4.5
  Gemfile
  Gemfile.lock
Labels: PR: reviewed-approved

#2528 Upgrade aws-sdk-lambda to 1.21
  Gemfile.lock
Labels: PR: reviewed-approved, dependencies

#2538 Apply theme color to sidebar widget links
  app/assets/stylesheets/preact/sidebar-widget.scss
Labels: PR: reviewed-approved

#2545 Classified Listings
  Envfile
  Gemfile
  Gemfile.lock
  app/assets/javascripts/initializers/initializeReadingListIcons.js
  app/assets/javascripts/lib/pulltorefresh.js
  app/assets/javascripts/serviceworker.js.erb
  app/assets/stylesheets/articles.scss
  app/assets/stylesheets/classified_listings.scss
  app/assets/stylesheets/credits.scss
  app/assets/stylesheets/fundamentals.scss
  app/assets/stylesheets/giveaways.scss
  app/assets/stylesheets/minimal.scss
  app/assets/stylesheets/variables.scss
  app/assets/stylesheets/video-collection.scss
  app/controllers/classified_listings_controller.rb
  app/controllers/credits_controller.rb
  app/helpers/application_helper.rb
  app/javascript/listings/listings.jsx
  app/javascript/listings/singleListing.jsx
  app/javascript/packs/listings.jsx
  app/models/article.rb
  app/models/classified_listing.rb
  app/models/credit.rb
  app/models/organization.rb
  app/models/user.rb
  app/policies/classified_listing_policy.rb
  app/views/articles/_algolia_search.html.erb
  app/views/articles/_sidebar_nav.html.erb
  app/views/articles/_sticky_nav.html.erb
  app/views/classified_listings/_form.html.erb
  app/views/classified_listings/edit.html.erb
  app/views/classified_listings/index.html.erb
  app/views/classified_listings/new.html.erb
  app/views/classified_listings/show.html.erb
  app/views/credits/index.html.erb
  app/views/credits/new.html.erb
  app/views/layouts/_styles.html.erb
  app/views/reading_list_items/index.html.erb
  app/views/users/_billing.html.erb
  app/views/videos/index.html.erb
  config/initializers/algoliasearch.rb
  config/routes.rb
  db/migrate/20190409123750_create_credits.rb
  db/migrate/20190417171020_create_classified_listings.rb
  db/schema.rb
  spec/factories/classified_listings.rb
  spec/factories/credits.rb
  spec/models/classified_listing_spec.rb
  spec/models/credit_spec.rb
  spec/requests/credits_spec.rb
  spec/requests/listings_spec.rb
  spec/requests/reading_list_index_spec.rb
Labels: PR: unreviewed

#2548 A couple small /listings fixes
  app/views/classified_listings/_form.html.erb
  app/views/classified_listings/index.html.erb
Labels: PR: unreviewed

#2522 Fixes Dashboard UI Positioning Bug #2506
  app/assets/stylesheets/dashboard.scss
  app/views/dashboards/show.html.erb
Labels: PR: unreviewed

#2530 Upgrade dry-struct to 0.7.0
  Gemfile
  Gemfile.lock
  app/services/notifications/new_follower/follow_data.rb
  app/services/notifications/reactions/reaction_data.rb
Labels: PR: reviewed-approved, dependencies

#2553 Rubocop fixes
  Gemfile
  app/controllers/classified_listings_controller.rb
  app/controllers/credits_controller.rb
  app/models/classified_listing.rb
  app/models/credit.rb
  spec/factories/credits.rb
  spec/models/classified_listing_spec.rb
  spec/models/credit_spec.rb
  spec/requests/credits_spec.rb
  spec/requests/listings_spec.rb
Labels: PR: reviewed-approved

#2551 Fix style issue video image on scroll
  app/assets/javascripts/initializers/initScrolling.js.erb
Labels: PR: unreviewed

#2542 BlackBox specs #2524
  app/black_box/black_box.rb
  app/labor/function_caller.rb
  app/services/aws/fake_client.rb
  config/initializers/aws_sdk.rb
  spec/black_box/black_box_spec.rb
  spec/labor/coupon_generator_spec.rb
  spec/labor/function_caller_spec.rb
Labels: PR: reviewed-approved

#2544 Added organizations to total following count
  app/views/dashboards/_actions.html.erb
  app/views/dashboards/following.html.erb
Labels: PR: unreviewed

#2493 Fix reading list comments reaction
  app/assets/javascripts/initializers/initializeCommentsPage.js.erb
  app/assets/javascripts/initializers/initializeReadingListPage.js.erb
Labels: PR: reviewed-approved

#2556 Banish User: only unsubscribe if user has an email address
  app/services/moderator/banish_user.rb
Labels: PR: reviewed-approved

#2555 Fix/improve edits for listings
  app/assets/stylesheets/classified_listings.scss
  app/controllers/classified_listings_controller.rb
  app/javascript/listings/listings.jsx
  app/javascript/listings/singleListing.jsx
  app/views/classified_listings/edit.html.erb
  spec/requests/listings_spec.rb
Labels: PR: unreviewed

#2557 Add Twitch to Profile Links
  app/controllers/admin/users_controller.rb
  app/dashboards/user_dashboard.rb
  app/models/user.rb
  app/policies/user_policy.rb
  app/services/moderator/banish_user.rb
  app/views/users/_profile.html.erb
  app/views/users/_profile_header.html.erb
  app/views/users/show.html.erb
  db/migrate/20180707162348_add_social_icons_to_user.rb
  db/schema.rb
  spec/models/user_spec.rb
Labels: PR: reviewed-approved

#2561 Add proper twitch url migration
  db/migrate/20180707162348_add_social_icons_to_user.rb
  db/migrate/20190425210432_add_twitch_url_to_users.rb
  db/schema.rb
Labels: PR: unreviewed

#2578 Upgrade dry-struct to 1.0
  Gemfile
  Gemfile.lock
Labels: PR: reviewed-approved

#2570 Fix double AWS_LAMBDA initialization
  config/initializers/aws_sdk.rb
Labels: PR: reviewed-approved

#2577 Upgrade webdrivers to 3.8.0
  Gemfile.lock
Labels: PR: reviewed-approved

#2576 Upgrade test-prof to 0.8.0
  Gemfile.lock
Labels: PR: reviewed-approved, dependencies

#2575 Upgrade rubocop-performance to 1.1.0
  Gemfile.lock
Labels: PR: reviewed-approved, dependencies

#2574 Upgrade httparty to 0.17.0
  Gemfile.lock
Labels: PR: reviewed-approved, dependencies

#2571 Upgrade counter_culture to 2.2.1
  Gemfile
  Gemfile.lock
Labels: PR: reviewed-approved, dependencies

#2567 Removed unused code
  app/services/aws/fake_client.rb
  spec/support/fixtures/vcr_cassettes/coupon_generator_1.yml
Labels: PR: reviewed-approved

#2572 Upgrade draper to 3.1.0
  Gemfile
  Gemfile.lock
Labels: PR: reviewed-approved, dependencies
