Repository forem/forem, pull requests merged in 2019-08, with the labels that each got.

#3593 Introduced published field to podcasts
  app/controllers/admin/podcasts_controller.rb
  app/controllers/api/v0/podcast_episodes_controller.rb
  app/controllers/podcast_episodes_controller.rb
  app/controllers/stories_controller.rb
  app/dashboards/podcast_dashboard.rb
  app/models/podcast.rb
  app/models/podcast_episode.rb
  app/views/internal/podcasts/index.html.erb
  app/views/layouts/internal.html.erb
  db/migrate/20190801083510_add_published_to_podcasts.rb
  db/schema.rb
  lib/tasks/fetch.rake
  spec/factories/podcasts.rb
  spec/models/podcast_episode_spec.rb
  spec/models/podcast_spec.rb
  spec/requests/admin/podcasts_spec.rb
  spec/requests/podcasts/podcast_show_spec.rb
  spec/system/podcasts/user_visits_podcasts_root_page_spec.rb
Labels: PR: reviewed-approved

#3596 Hash OAuth2 access tokens
  config/initializers/doorkeeper.rb
Labels: PR: reviewed-approved

#3597 Fix deprecations in internal/podcasts_spec
  spec/requests/internal/podcasts_spec.rb
Labels: PR: reviewed-approved

#3598 Update Readme
  README.md
Labels: PR: reviewed-approved

#3577 Fix podcasts episodes surrogate key and add "/podcasts"
  app/controllers/podcast_episodes_controller.rb
  config/routes.rb
  spec/requests/podcasts/podcast_episodes_index_spec.rb
Labels: PR: reviewed-approved

#3566 Moved send_mention_notification to ActiveJob
  app/jobs/notifications/mention_job.rb
  app/models/notification.rb
  app/services/notifications/moderation/send.rb
  app/services/notifications/new_mention/send.rb
  spec/jobs/notifications/mention_job_spec.rb
  spec/services/notifications/new_mention/send_spec.rb
Labels: PR: reviewed-approved

#3507 Update Complexity linters
  .codeclimate.yml
  .rubocop.yml
  .rubocop_todo.yml
  app/controllers/display_ad_events_controller.rb
  app/models/display_ad.rb
  app/models/display_ad_event.rb
  spec/models/display_ad_spec.rb
  spec/requests/display_ad_events_spec.rb
Labels: PR: reviewed-approved

#3605 Remove duplicate PodcastEpisodes API spec
  spec/requests/podcast_episodes_api_spec.rb
Labels: PR: reviewed-approved

#3383 Collection: remove optional user and add tests
  app/controllers/articles_controller.rb
  app/models/collection.rb
  spec/factories/collections.rb
  spec/models/collection_spec.rb
Labels: PR: reviewed-approved

#3609 remove ali from readme :(
  README.md
Labels: PR: reviewed-approved

#3615 Re-enable hello dev in console
  app/assets/javascripts/hello-dev.js
  app/views/layouts/_footer.html.erb
Labels: PR: reviewed-approved

#3635 Add git source to Gem file
  Gemfile
Labels: PR: unreviewed

#3634 Update content policy and faqs about sponsorship
  README.md
  app/views/pages/_terms_text.html.erb
  app/views/pages/sponsors.html.erb
  app/views/pages/sponsorship_faq.html.erb
Labels: PR: reviewed-approved

#3642 Add hackers.town to allowed Mastodon instances
  app/lib/constants.rb
Labels: PR: reviewed-approved

#3608 Improve Error Message for malformed Github Repo Links
  app/models/article.rb
  spec/models/article_spec.rb
Labels: PR: reviewed-approved

#3592 Allow CodePen usernames to be up to 30 characters long
  app/liquid_tags/codepen_tag.rb
  spec/liquid_tags/codepen_tag_spec.rb
Labels: PR: reviewed-approved

#3633 Resolve error with code blocks in numbered lists
  app/labor/markdown_parser.rb
  spec/labor/markdown_parser_spec.rb
  spec/support/fixtures/approvals/user_preview_article_body.approved.html
Labels: PR: reviewed-approved

#3640 Fix upload overlap with editor/help page
  app/javascript/article-form/__tests__/__snapshots__/articleForm.test.jsx.snap
  app/javascript/article-form/articleForm.jsx
Labels: PR: reviewed-approved

#3652 Update Faker to 2.1.0
  Gemfile
  Gemfile.lock
  db/seeds.rb
  spec/factories/articles.rb
  spec/factories/blocks.rb
  spec/factories/classified_listings.rb
  spec/factories/comments.rb
  spec/factories/events.rb
  spec/factories/html_variants.rb
  spec/factories/organizations.rb
  spec/factories/podcast_episode_rss_items.rb
  spec/factories/podcast_episodes.rb
  spec/factories/podcasts.rb
  spec/factories/poll_options.rb
  spec/factories/poll_skips.rb
  spec/factories/polls.rb
  spec/liquid_tags/youtube_tag_spec.rb
  spec/models/event_spec.rb
  spec/models/message_spec.rb
  spec/models/organization_spec.rb
  spec/models/user_spec.rb
Labels: PR: reviewed-approved

#3659 [skip ci] update contributing.md and readme for clarity
  CONTRIBUTING.md
  README.md
Labels: PR: reviewed-approved

#3651 Remove dead routes
  config/routes.rb
Labels: PR: reviewed-approved

#3553 Fixed bug with comments overlapping on IE and Edge
  app/assets/stylesheets/comments.scss
Labels: PR: reviewed-approved

#3644 Update core API endpoints to support access_token
  .codeclimate.yml
  app/controllers/api/v0/analytics_controller.rb
  app/controllers/api/v0/api_controller.rb
  app/controllers/api/v0/articles_controller.rb
  app/controllers/api/v0/users_controller.rb
  app/views/api/v0/articles/me.json.jbuilder
  app/views/api/v0/users/me.json.jbuilder
  config/initializers/doorkeeper.rb
  config/routes.rb
  spec/factories/doorkeeper_access_tokens.rb
  spec/factories/doorkeeper_applications.rb
  spec/rails_helper.rb
  spec/requests/api/v0/articles_spec.rb
  spec/requests/api/v0/users_spec.rb
Labels: PR: reviewed-approved

#3660 clean up readme and docs
  README.md
  docs/getting-started/committing.md
  docs/getting-started/readme.md
  docs/getting-started/start-app.md
  docs/getting-started/workflow.md
  docs/installation/docker.md
  docs/installation/gitpod.md
  docs/installation/readme.md
Labels: PR: reviewed-approved

#3666 Updates to the contributing guide
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
Labels: PR: reviewed-approved

#3663 Allow emoji in pinned repo description
  app/views/users/_sidebar_additional.html.erb
  spec/requests/user_profile_spec.rb
Labels: PR: reviewed-approved

#3671 Add force push notice to the PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: PR: reviewed-approved

#3673 Fix /sponsors page
  app/views/pages/sponsors.html.erb
Labels: PR: reviewed-approved

#3614 Add button to copy org secret to clipboard
  app/assets/stylesheets/settings.scss
  app/views/users/_org_admin.html.erb
Labels: PR: unreviewed

#3650 API: OpenAPI 3 spec and auto generated docs
  .gitignore
  app/controllers/api/v0/articles_controller.rb
  app/labor/cache_buster.rb
  app/views/api/v0/articles/index.json.jbuilder
  app/views/api/v0/articles/show.json.jbuilder
  app/views/pages/api.html.erb
  config/routes.rb
  docs/.gitdocs.json
  docs/Makefile
  docs/api_template.hbs
  docs/api_v0.yml
  docs/contributing_api.md
  docs/readme.md
  netlify.toml
  package.json
  spec/requests/api/v0/articles_spec.rb
  spec/requests/pages_spec.rb
  yarn.lock
Labels: PR: reviewed-approved

#3680 Adjust Algolia documentation
  docs/backend/algolia.md
Labels: PR: reviewed-approved

#3687 Add place holder alt text to markdown link
  app/javascript/article-form/elements/imageManagement.jsx
Labels: PR: reviewed-approved

#3689 Rescue all Errno exceptions while fetching a podcast episode
  app/services/podcasts/get_media_url.rb
  spec/services/podcasts/get_media_url_spec.rb
Labels: PR: reviewed-approved

#3707 API docs: Document OAuth2 and /api/articles/me
  app/controllers/api/v0/articles_controller.rb
  app/views/api/v0/articles/_flare_tag.json.jbuilder
  app/views/api/v0/articles/_organization.json.jbuilder
  app/views/api/v0/articles/_user.json.jbuilder
  app/views/api/v0/articles/index.json.jbuilder
  app/views/api/v0/articles/me.json.jbuilder
  app/views/api/v0/articles/show.json.jbuilder
  docs/api_v0.yml
  spec/requests/api/v0/articles_spec.rb
Labels: PR: reviewed-approved

#3681 Add notification section to docs
  docs/backend/notification.md
  docs/backend/readme.md
Labels: PR: reviewed-approved

#3645 Direct listing links only show listing if published
  app/controllers/classified_listings_controller.rb
  spec/requests/classified_listings_spec.rb
Labels: PR: reviewed-approved, area: listings

#3711 Expired Listing 404
  app/controllers/classified_listings_controller.rb
Labels: PR: reviewed-approved

#3714 Switch to internally built color picker
  app/assets/stylesheets/color-picker.scss
  app/assets/stylesheets/minimal.scss
  app/javascript/packs/colorPicker.js
  app/views/internal/tags/index.html.erb
  app/views/internal/tags/show.html.erb
  app/views/partnerships/index.html.erb
  app/views/tags/edit.html.erb
  app/views/users/_org_admin.html.erb
  app/views/users/_org_non_member.html.erb
  app/views/users/_profile.html.erb
Labels: PR: unreviewed

#3716 API: Remove /api/articles/onboarding
  app/controllers/api/v0/articles_controller.rb
  config/routes.rb
Labels: PR: reviewed-approved

#3653 Allow admins to undo a tag adjustment
  app/controllers/tag_adjustments_controller.rb
  app/models/tag_adjustment.rb
  app/views/moderations/mod.html.erb
  config/routes.rb
  spec/models/tag_adjustment_spec.rb
  spec/requests/tag_adjustments_spec.rb
Labels: PR: reviewed-approved

#3717 Update docs
  docs/design/branding.md
  docs/self-hosting.md
Labels: PR: reviewed-approved

#3721 Fix mention notification to mention proper user
  app/services/notifications/new_mention/send.rb
  spec/services/notifications/new_mention/send_spec.rb
Labels: PR: unreviewed

#3637 Add Stack Exchange Liquid tag
  Envfile
  app/assets/images/stackexchange-arrow-down.svg
  app/assets/images/stackexchange-arrow-up.svg
  app/assets/images/stackexchange-logo.svg
  app/assets/images/stackoverflow-logo.svg
  app/assets/stylesheets/ltags/LiquidTags.scss
  app/assets/stylesheets/ltags/StackexchangeTag.scss
  app/assets/stylesheets/preact/article-form.scss
  app/javascript/article-form/__tests__/__snapshots__/articleForm.test.jsx.snap
  app/javascript/article-form/elements/publishToggle.jsx
  app/javascript/listings/__tests__/__snapshots__/listingDashboard.test.jsx.snap
  app/liquid_tags/stackexchange_tag.rb
  app/views/liquids/_stackexchange.html.erb
  app/views/pages/_editor_guide_text.html.erb
  spec/liquid_tags/stackexchange_tag_spec.rb
  spec/support/fixtures/approvals/liquid_tweet_tag_spec.received.html
  spec/support/fixtures/vcr_cassettes/stackexchange_api.yml
Labels: PR: unreviewed

#3722 Delete unused, commented-out code
  app/javascript/article-form/articleForm.jsx
Labels: PR: reviewed-approved

#3727 Fix/icons in dark mode
  app/assets/stylesheets/article-show.scss
  app/views/layouts/_user_config.html.erb
Labels: PR: reviewed-approved

#3725 Onboarding : fixed bug that prevented toggle by clicking on label
  app/javascript/onboarding/__tests__/__snapshots__/Onboarding.test.jsx.snap
  app/javascript/onboarding/components/EmailListTermsConditionsForm.jsx
Labels: PR: reviewed-approved

#3603 Move delayed calls for update analytics to Active job
  app/controllers/async_info_controller.rb
  app/controllers/dashboards_controller.rb
  app/jobs/articles/update_analytics_job.rb
  app/labor/article_analytics_fetcher.rb
  app/services/articles/analytics_updater.rb
  spec/jobs/articles/update_analytics_job_spec.rb
  spec/services/articles/analytics_updater_spec.rb
Labels: PR: reviewed-approved

#3734 Adjust Google Analytics params to further increase user privacy
  app/assets/javascripts/initializers/initializeBaseTracking.js.erb
  app/views/pages/badge.html.erb
Labels: PR: unreviewed

#3729 Fix badges order on profile sidebar
  app/views/articles/_badges_area.html.erb
  app/views/users/_sidebar_additional.html.erb
Labels: PR: reviewed-approved

#3719 Sponsorship Updates
  app/assets/stylesheets/articles.scss
  app/assets/stylesheets/variables.scss
  app/controllers/partnerships_controller.rb
  app/views/articles/_single_sponsor.html.erb
  app/views/articles/tags/_sidebar.html.erb
  app/views/pages/_sponsor_image.html.erb
  app/views/pages/sponsors.html.erb
  app/views/partnerships/_tag_sponsor_copy.html.erb
  app/views/tags/index.html.erb
  spec/requests/partnerships_spec.rb
  spec/requests/stories_index_spec.rb
Labels: PR: unreviewed

#3738 Adds border-right to the menu for displays with min-width 1250 or higher
  app/assets/stylesheets/top-bar.scss
Labels: PR: reviewed-approved

#3599 Allow upload of multiple images at a time
  app/assets/stylesheets/preact/article-form.scss
  app/controllers/image_uploads_controller.rb
  app/javascript/article-form/actions.js
  app/javascript/article-form/articleForm.jsx
  app/javascript/article-form/elements/imageManagement.jsx
  spec/requests/image_uploads_spec.rb
  spec/support/fixtures/images/image2.jpeg
Labels: PR: reviewed-approved

#3742 Add random variants to onboarding for a/b testing
  app/controllers/async_info_controller.rb
  app/dashboards/display_ad_dashboard.rb
  app/dashboards/html_variant_dashboard.rb
  app/javascript/onboarding/Onboarding.jsx
  app/javascript/onboarding/__tests__/__snapshots__/Onboarding.test.jsx.snap
  app/javascript/onboarding/components/ClosingSlide.jsx
  app/javascript/onboarding/components/IntroSlide.jsx
  app/services/authorization_service.rb
  db/migrate/20190818191954_add_onboarding_variant_to_users.rb
  db/schema.rb
  spec/models/user_spec.rb
Labels: PR: unreviewed

#3743 Remove unnecessary imports from css
  app/assets/stylesheets/article-show.scss
  app/assets/stylesheets/comments.scss
  app/assets/stylesheets/scaffolds.scss
  app/assets/stylesheets/shared.scss
  app/assets/stylesheets/variables.scss
  app/views/articles/_video_player.html.erb
Labels: PR: unreviewed

#3745 Updated Preact to fix React DevTools errors.
  package.json
  yarn.lock
Labels: PR: reviewed-approved

#3749 Add internal dashboard for growth
  app/controllers/internal/growth_controller.rb
  app/views/internal/growth/_results.html.erb
  app/views/internal/growth/index.html.erb
  config/routes.rb
Labels: PR: unreviewed

#3768 Redesign series style
  app/assets/javascripts/initializers/initializeArticleReactions.js
  app/assets/stylesheets/article-show.scss
  app/views/articles/_collection.html.erb
  app/views/layouts/_user_config.html.erb
Labels: PR: unreviewed

#3771 Fix for multi-image upload to handle single imgs for comments
  app/assets/javascripts/initializers/initializeCommentsPage.js.erb
  app/controllers/image_uploads_controller.rb
  spec/requests/image_uploads_spec.rb
Labels: PR: reviewed-approved

#3774 Rubocop fixes and config update
  .rubocop.yml
  .rubocop_todo.yml
  app/liquid_tags/stackexchange_tag.rb
  spec/models/user_spec.rb
Labels: PR: reviewed-approved

#3778 Fix video image redirect issue
  app/controllers/articles_controller.rb
  spec/requests/articles_update_spec.rb
Labels: PR: unreviewed

#3780 Remove channel_users from chat_channel index
  app/models/chat_channel.rb
Labels: PR: unreviewed

#3782 Fixed some lint issues
  app/assets/javascripts/.eslintrc.js
  app/assets/javascripts/utilities/sendFetch.js
  app/assets/javascripts/utilities/sendHapticMessage.js
  app/assets/javascripts/utilities/showModal.js
  app/assets/javascripts/utilities/slideSidebar.js
  app/assets/javascripts/utilities/timeAgo.js
  app/assets/javascripts/utilities/userData.js
Labels: PR: reviewed-approved

#3788 Add dropdown and report-abuse for users
  app/assets/javascripts/initializePage.js.erb
  app/assets/javascripts/initializers/initializeUserProfilePage.js
  app/assets/stylesheets/user-profile-header.scss
  app/views/users/show.html.erb
Labels: PR: unreviewed

#3784 Remove listings privileges from banned users (Anti-spam)
  app/controllers/classified_listings_controller.rb
  spec/requests/classified_listings_spec.rb
Labels: PR: unreviewed, area: fighting abuse

#3787 Refactoring chat_channels_controller.rb.
  app/controllers/chat_channels_controller.rb
Labels: PR: reviewed-approved

#3789 Typo fix
  app/controllers/internal/organization_memberships_controller.rb
Labels: PR: reviewed-approved

#3804 Updates Possible error messages under windows installation docs
  docs/installation/windows.md
Labels: PR: reviewed-approved

#3803 Show single pinned articles
  app/views/users/show.html.erb
Labels: PR: reviewed-approved

#3786 Fixes some lint issues
  app/assets/javascripts/utilities/browserStoreCache.js
  app/assets/javascripts/utilities/checkUserLoggedIn.js
  app/assets/javascripts/utilities/createAjaxReq.js
  app/assets/javascripts/utilities/getCurrentPage.js
  app/assets/javascripts/utilities/getImageForLink.js
  app/assets/javascripts/utilities/insertAfter.js
  app/assets/javascripts/utilities/localDateTime.js
  app/assets/javascripts/utilities/localStorageTest.js
  app/assets/javascripts/utilities/preventDefaultAction.js
Labels: PR: reviewed-approved

#3794 Refactoring dashboards_controller.rb.
  app/controllers/dashboards_controller.rb
Labels: PR: reviewed-approved

#3793 Refactoring organizations_controller.rb.
  app/controllers/organizations_controller.rb
Labels: PR: reviewed-approved

#3798 Add android and ios apps download page (#3736)
  app/controllers/downloads_controller.rb
  app/views/downloads/index.html.erb
  app/views/pages/information.html.erb
  config/routes.rb
  spec/system/user_visits_downloads_page_spec.rb
Labels: PR: reviewed-approved

#3750 Add comment markdown to warned_user_ping
  app/observers/application_observer.rb
Labels: PR: reviewed-approved

#3812 Add onboarding variants and update variant display ratio
  app/controllers/internal/growth_controller.rb
  app/javascript/onboarding/Onboarding.jsx
  app/javascript/onboarding/components/ClosingSlide.jsx
  app/services/authorization_service.rb
  app/views/internal/growth/_results.html.erb
  app/views/internal/growth/index.html.erb
  spec/models/user_spec.rb
Labels: PR: unreviewed

#3797 Refactor articles creation
  app/controllers/admin/articles_controller.rb
  app/controllers/api/v0/articles_controller.rb
  app/controllers/articles_controller.rb
  app/services/article_creation_service.rb
  app/services/articles/creator.rb
  app/services/articles/destroyer.rb
  spec/requests/articles/articles_create_spec.rb
  spec/requests/articles/articles_destroy_spec.rb
  spec/requests/articles/articles_spec.rb
  spec/requests/articles/articles_update_spec.rb
  spec/services/articles/creator_spec.rb
Labels: PR: reviewed-approved

#3814 Backend docs: github authentication updated
  docs/backend/auth-github.md
Labels: PR: reviewed-approved

#3808 Refactoring chat_channels_controller.rb.
  app/controllers/chat_channels_controller.rb
Labels: PR: reviewed-approved

#3770 Listings set custom expiry date
  app/controllers/classified_listings_controller.rb
  app/controllers/concerns/classified_listings_toolkit.rb
  app/javascript/listings/dashboard/listingRow.jsx
  app/javascript/listings/elements/expireDate.jsx
  app/javascript/listings/listingForm.jsx
  app/models/classified_listing.rb
  app/views/classified_listings/dashboard.html.erb
  app/views/classified_listings/edit.html.erb
  db/migrate/20190822162434_add_expires_at_to_classified_listings.rb
  db/schema.rb
  lib/tasks/fetch.rake
Labels: PR: reviewed-approved, area: listings

#3813 Create endpoint for liquid tag embed
  app/controllers/liquid_embeds_controller.rb
  app/views/liquid_embeds/show.html.erb
  config/routes.rb
  spec/requests/liquid_embeds_spec.rb
  spec/support/fixtures/vcr_cassettes/LiquidEmbeds/get_/embeds/renders_proper_tweet.yml
Labels: PR: unreviewed

#3817 Fixes encoding of special characters in org (#3779)
  app/controllers/organizations_controller.rb
Labels: PR: reviewed-approved

#3818 Refactoring social_previews_controller.rb.
  app/controllers/social_previews_controller.rb
Labels: PR: reviewed-approved

#3821 Removes temp .received file (#3731)
  spec/support/fixtures/approvals/liquid_tweet_tag_spec.received.html
Labels: PR: reviewed-approved

#3854 Add listings to DEV digests
  app/views/mailers/digest_mailer/digest_email.html.erb
Labels: PR: reviewed-approved

#3869 Update mod internal backend to be safer and more intuitive
  app/controllers/internal/mods_controller.rb
  app/labor/assign_tag_moderator.rb
  app/views/internal/mods/index.html.erb
  app/views/layouts/internal.html.erb
Labels: PR: unreviewed

#3783 Webhook endpoints and webhook API #3715
  app/controllers/api/v0/webhooks_controller.rb
  app/models/user.rb
  app/models/webhook/endpoint.rb
  app/models/webhook/event.rb
  app/views/api/v0/webhooks/show.json.jbuilder
  config/routes.rb
  db/migrate/20190819104106_create_webhook_endpoints.rb
  db/schema.rb
  spec/factories/webhook_endpoints.rb
  spec/models/webhook/endpoint_spec.rb
  spec/requests/api/v0/webhooks_spec.rb
Labels: PR: reviewed-approved

#3871 Exclude AWS Cloud9 user config directory and resolve AWS install error "role ec2-user does not exist" in FAQ (v2)
  .gitignore
  docs/faqs.md
Labels: PR: reviewed-approved

#3801 Support for runnable kotlin snippets #3776
  app/liquid_tags/kotlin_tag.rb
  app/views/liquids/_kotlin.html.erb
  app/views/pages/_editor_guide_text.html.erb
  docs/frontend/liquid-tags.md
  spec/liquid_tags/kotlin_tag_spec.rb
  spec/support/fixtures/approvals/kotlin_liquid_tag.approved.html
Labels: PR: reviewed-approved

#3878 Clear previous ClassifiedListings in Algolia during DB Seed
  db/seeds.rb
Labels: PR: reviewed-approved, area: listings

#3875 Use maskable icons
  app/assets/javascripts/manifest.json.erb
Labels: PR: reviewed-approved

#3879 Fix internal mods interactivity and improve layout
  app/controllers/internal/mods_controller.rb
  app/views/internal/mods/index.html.erb
  app/views/layouts/internal.html.erb
Labels: PR: unreviewed

#3867 Update Email Copy for internal/reports
  app/helpers/feedback_messages_helper.rb
  spec/helpers/feedback_messages_helper_spec.rb
Labels: PR: reviewed-approved

#3883 singleListing Testing
  app/javascript/listings/__tests__/__snapshots__/singleListing.test.jsx.snap
  app/javascript/listings/__tests__/singleListing.test.jsx
  app/javascript/listings/singleListing.jsx
Labels: PR: reviewed-approved, area: listings, javascript, type: tests
