Repository forem/forem, pull requests merged in 2019-07, with the labels that each got.

#3336 Fix instagram URL validation rule
  app/models/user.rb
  spec/models/user_spec.rb
Labels: PR: reviewed-approved

#3337 expand common errors on macOS install
  docs/installation/mac.md
Labels: PR: reviewed-approved

#3342 Rubocop fixes
  Gemfile
  app/models/profile_pin.rb
  spec/models/profile_pin_spec.rb
  spec/requests/internal/users_spec.rb
  spec/requests/notifications_spec.rb
Labels: PR: reviewed-approved

#3343 Moved podcasts fixtures to their own folder
  spec/services/podcasts/create_episode_spec.rb
  spec/support/fixtures/podcasts/awayfromthekeyboard.rss
  spec/support/fixtures/podcasts/developertea.rss
Labels: PR: reviewed-approved

#3082 frontend refactor/eslint fixes
  app/assets/javascripts/.eslintrc.js
  app/assets/javascripts/initializers/initializeCommentPreview.js
Labels: PR: reviewed-approved

#3361 More rubocop fixes
  .rubocop_todo.yml
  spec/services/analytics_service_spec.rb
Labels: PR: reviewed-approved

#3341 Podcasts reachable status #2952
  .rubocop_todo.yml
  app/controllers/podcast_episodes_controller.rb
  app/controllers/stories_controller.rb
  app/dashboards/podcast_dashboard.rb
  app/models/podcast.rb
  app/services/podcasts/create_episode.rb
  app/services/podcasts/feed.rb
  app/views/podcast_episodes/show.html.erb
  config/locales/en.yml
  db/migrate/20190628123548_add_reachable_to_podcasts.rb
  db/schema.rb
  spec/requests/podcasts/podcast_episodes_index_spec.rb
  spec/requests/podcasts/podcast_show_spec.rb
  spec/services/podcasts/feed_spec.rb
  spec/system/podcasts/user_visits_podcast_episode_spec.rb
  spec/system/podcasts/user_visits_podcast_index_spec.rb
  spec/system/podcasts/user_visits_podcasts_root_page_spec.rb
Labels: PR: reviewed-approved

#3338 History and reading list refactoring
  app/assets/stylesheets/history.scss
  app/assets/stylesheets/item-list.scss
  app/assets/stylesheets/minimal.scss
  app/assets/stylesheets/readinglist.scss
  app/javascript/history/__tests__/__snapshots__/history.test.jsx.snap
  app/javascript/history/__tests__/history.test.jsx
  app/javascript/history/history.jsx
  app/javascript/packs/readingList.jsx
  app/javascript/readingList/__tests__/__snapshots__/readingList.test.jsx.snap
  app/javascript/readingList/__tests__/readingList.test.jsx
  app/javascript/readingList/readingList.jsx
  app/javascript/searchableItemList/searchableItemList.js
  app/javascript/src/components/ItemList/ItemListItem.jsx
  app/javascript/src/components/ItemList/ItemListItemArchiveButton.jsx
  app/javascript/src/components/ItemList/ItemListLoadMoreButton.jsx
  app/javascript/src/components/ItemList/ItemListTags.jsx
  app/javascript/src/components/ItemList/__tests__/ItemListItem.test.jsx
  app/javascript/src/components/ItemList/__tests__/ItemListItemArchiveButton.test.jsx
  app/javascript/src/components/ItemList/__tests__/ItemListLoadMoreButton.test.jsx
  app/javascript/src/components/ItemList/__tests__/ItemListTags.test.jsx
  app/javascript/src/components/ItemList/__tests__/__snapshots__/ItemListItem.test.jsx.snap
  app/javascript/src/components/ItemList/__tests__/__snapshots__/ItemListItemArchiveButton.test.jsx.snap
  app/javascript/src/components/ItemList/__tests__/__snapshots__/ItemListLoadMoreButton.test.jsx.snap
  app/javascript/src/components/ItemList/__tests__/__snapshots__/ItemListTags.test.jsx.snap
  app/views/history/index.html.erb
  app/views/reading_list_items/index.html.erb
  package.json
  yarn.lock
Labels: PR: reviewed-approved

#3367 add ids to terms page so each clause can be linked to directly
  app/views/pages/terms.html.erb
Labels: PR: reviewed-approved

#3369 Use time tags for article publish dates on user dashboard
  app/views/dashboards/_dashboard_article.html.erb
Labels: PR: reviewed-approved

#3368 Add /challenge redirect
  app/controllers/pages_controller.rb
  config/routes.rb
  spec/requests/pages_spec.rb
Labels: PR: reviewed-approved

#3378 Allow full links for cache buster tool
  app/controllers/internal/tools_controller.rb
  app/views/internal/tools/index.html.erb
  app/views/layouts/internal.html.erb
Labels: PR: reviewed-approved

#3374 Rescue possible SSLError when fetching a podcast
  app/services/podcasts/feed.rb
  config/locales/en.yml
  spec/services/podcasts/feed_spec.rb
  spec/support/fixtures/podcasts/arresteddevops.xml
Labels: PR: reviewed-approved

#3377 Add functionality to remove and recover identity
  app/controllers/internal/users_controller.rb
  app/models/backup_data.rb
  app/models/identity.rb
  app/models/user.rb
  app/views/internal/users/edit.html.erb
  app/views/users/_account.html.erb
  config/initializers/reserved_words.rb
  config/routes.rb
  db/migrate/20190703003817_create_backup_data_table.rb
  db/schema.rb
  spec/factories/identities.rb
  spec/models/backup_data_spec.rb
  spec/requests/internal_users_spec.rb
Labels: PR: reviewed-approved

#3371 Self-serve sponsorship options
  app/assets/stylesheets/articles.scss
  app/assets/stylesheets/partnerships.scss
  app/controllers/partnerships_controller.rb
  app/dashboards/organization_dashboard.rb
  app/dashboards/tag_dashboard.rb
  app/decorators/organization_decorator.rb
  app/helpers/application_helper.rb
  app/models/organization.rb
  app/models/tag.rb
  app/policies/organization_policy.rb
  app/views/articles/_sidebar.html.erb
  app/views/articles/_single_sponsor.html.erb
  app/views/articles/tags/_sidebar.html.erb
  app/views/credits/index.html.erb
  app/views/organizations/_sidebar_additional.html.erb
  app/views/pages/sponsors.html.erb
  app/views/partnerships/_bronze_sponsor_copy.html.erb
  app/views/partnerships/_editorial_consult_copy.html.erb
  app/views/partnerships/_form.html.erb
  app/views/partnerships/_gold_sponsor_copy.html.erb
  app/views/partnerships/_media_sponsor_copy.html.erb
  app/views/partnerships/_silver_sponsor_copy.html.erb
  app/views/partnerships/_tag_sponsor_copy.html.erb
  app/views/partnerships/index.html.erb
  app/views/partnerships/show.html.erb
  config/routes.rb
  db/migrate/20190626221336_add_additional_sponsor_options_to_organizations.rb
  db/schema.rb
  spec/requests/partnerships_spec.rb
  spec/requests/stories_index_spec.rb
  spec/requests/user_profile_spec.rb
Labels: PR: unreviewed

#3362 Remove notifications if article is unpublished
  app/controllers/articles_controller.rb
  spec/requests/articles_update_spec.rb
Labels: PR: reviewed-approved

#3373 Moved creating a new podcast to a separate ActiveJob #2952
  app/jobs/podcast_episodes/create_job.rb
  app/models/podcast.rb
  app/services/podcasts/create_episode.rb
  app/services/podcasts/episode_rss_item.rb
  app/services/podcasts/get_episode.rb
  app/services/podcasts/update_episode.rb
  spec/factories/podcast_episode_rss_items.rb
  spec/jobs/podcast_episodes/create_job_spec.rb
  spec/models/podcast_spec.rb
  spec/requests/podcast_episodes_api_spec.rb
  spec/services/podcasts/create_episode_spec.rb
  spec/services/podcasts/episode_rss_item_spec.rb
  spec/services/podcasts/feed_spec.rb
  spec/services/podcasts/get_episode_spec.rb
  spec/services/podcasts/update_episode_spec.rb
Labels: PR: reviewed-approved

#3385 Escape comment.title to fix failing spec
  spec/requests/notifications_spec.rb
Labels: PR: reviewed-approved

#3413 Mitigate CVE 2015-9284
  .travis.yml
  app/views/articles/_sidebar_additional.html.erb
  app/views/devise/registrations/_registration_form.html.erb
  app/views/layouts/_nav_menu.html.erb
  app/views/layouts/_signup_modal.html.erb
  app/views/shared/_github_sign_in_button.html.erb
  app/views/shared/_twitter_sign_in_button.html.erb
  app/views/stories/_sign_in_invitation.html.erb
  app/views/users/_account.html.erb
  app/views/users/_github_sign_in_button.html.erb
  app/views/users/_profile.html.erb
  app/views/users/_twitter_sign_in_button.html.erb
Labels: PR: reviewed-approved

#3419 Run `yarn upgrade`
  spec/models/credit_spec.rb
  yarn.lock
Labels: PR: unreviewed

#3052 Bust cache for articles in series
  app/models/article.rb
  app/models/collection.rb
  spec/factories/articles.rb
  spec/factories/collections.rb
  spec/models/collection_spec.rb
  spec/requests/comments_spec.rb
Labels: PR: reviewed-approved

#3314 Move messages send_push delay calls to ActiveJob
  app/controllers/messages_controller.rb
  app/jobs/messages/send_push_job.rb
  app/models/message.rb
  app/services/messages/send_push.rb
  spec/jobs/messages/send_push_job_spec.rb
  spec/services/messages/send_push_spec.rb
Labels: PR: reviewed-approved

#3417 Add history to sidebar for pro users
  app/assets/images/emoji/emoji-one-filmstrip.png
  app/assets/stylesheets/articles.scss
  app/assets/stylesheets/variables.scss
  app/decorators/user_decorator.rb
  app/views/articles/_sidebar_nav.html.erb
  spec/models/user_spec.rb
Labels: PR: unreviewed

#3387 Move RssReader fetch_user to Active Jobs
  app/controllers/users_controller.rb
  app/jobs/rss_reader_fetch_user_job.rb
  spec/jobs/rss_reader_fetch_user_job_spec.rb
Labels: PR: reviewed-approved

#3250 Listing Liquid Tag
  app/assets/stylesheets/ltags/ClassifiedListingTag.scss
  app/assets/stylesheets/ltags/LiquidTags.scss
  app/liquid_tags/classified_listing_tag.rb
  app/views/classified_listings/_liquid.html.erb
  app/views/pages/_editor_guide_text.html.erb
  spec/liquid_tags/classified_listing_tag_spec.rb
Labels: PR: reviewed-approved, listings

#3423 Small rubocop fixes
  app/controllers/partnerships_controller.rb
  config/routes.rb
  spec/models/collection_spec.rb
  spec/requests/partnerships_spec.rb
  spec/requests/user_profile_spec.rb
Labels: PR: reviewed-approved

#3394 Add markdown to article api response
  app/views/api/v0/articles/show.json.jbuilder
  spec/requests/api/v0/articles_spec.rb
Labels: PR: reviewed-approved

#3395 Credits ledger
  app/assets/javascripts/initializePage.js.erb
  app/assets/javascripts/initializers/initializeCreditsPage.js
  app/assets/javascripts/utilities/localDateTime.js
  app/assets/stylesheets/credits.scss
  app/controllers/classified_listings_controller.rb
  app/controllers/concerns/classified_listings_toolkit.rb
  app/controllers/credits_controller.rb
  app/models/classified_listing.rb
  app/models/credit.rb
  app/services/credits/buyer.rb
  app/services/credits/ledger.rb
  app/views/credits/_ledger.html.erb
  app/views/credits/index.html.erb
  config/routes.rb
  db/migrate/20190704082551_add_purchase_to_credits.rb
  db/migrate/20190704091636_add_index_to_credits_spent.rb
  db/migrate/20190704105143_add_spent_at_and_remove_spent_on_for_credits.rb
  db/schema.rb
  spec/factories/classified_listings.rb
  spec/models/classified_listing_spec.rb
  spec/models/credit_spec.rb
  spec/requests/classified_listings_spec.rb
  spec/requests/comments_spec.rb
  spec/services/credits/buyer_spec.rb
  spec/services/credits/ledger_spec.rb
Labels: PR: reviewed-approved

#3384 Add internal page for spinning up group chats (and make jokes flare tag)
  app/controllers/internal/chat_channels_controller.rb
  app/labor/flare_tag.rb
  app/models/chat_channel.rb
  app/views/internal/chat_channels/index.html.erb
  app/views/layouts/internal.html.erb
  config/routes.rb
Labels: PR: unreviewed

#3426 Remove temporary page views rake task
  lib/tasks/temporary/.keep
  lib/tasks/temporary/page_views.rake
Labels: PR: reviewed-approved

#3427 Fix profile pin max off-by-one errror
  app/controllers/profile_pins_controller.rb
  app/models/profile_pin.rb
  spec/models/profile_pin_spec.rb
  spec/requests/profile_pins_spec.rb
Labels: PR: unreviewed

#3388 Fix GistTag & RunkitTag preview issue
  app/javascript/article-form/articleForm.jsx
  app/liquid_tags/gist_tag.rb
  app/liquid_tags/runkit_tag.rb
  app/views/articles/_v2_form.html.erb
  package.json
  yarn.lock
Labels: PR: reviewed-approved

#3428 Make RSS's self-referential link an option
  app/models/user.rb
  app/policies/user_policy.rb
  app/services/rss_reader/assembler.rb
  app/views/users/_publishing_from_rss.html.erb
  db/migrate/20190709192214_add_feed_referential_link_to_users.rb
  db/schema.rb
  spec/services/rss_reader_spec.rb
Labels: PR: reviewed-approved

#3416 Update self-serve sponsorship copy/functionality
  app/assets/stylesheets/tags.scss
  app/controllers/partnerships_controller.rb
  app/controllers/tags_controller.rb
  app/helpers/application_helper.rb
  app/views/credits/index.html.erb
  app/views/partnerships/_bronze_sponsor_copy.html.erb
  app/views/partnerships/_devrel_consult_copy.html.erb
  app/views/partnerships/_editorial_consult_copy.html.erb
  app/views/partnerships/_form.html.erb
  app/views/partnerships/_gold_sponsor_copy.html.erb
  app/views/partnerships/_media_sponsor_copy.html.erb
  app/views/partnerships/_silver_sponsor_copy.html.erb
  app/views/partnerships/_tag_sponsor_copy.html.erb
  app/views/partnerships/index.html.erb
  app/views/partnerships/show.html.erb
  app/views/tags/index.html.erb
  spec/requests/partnerships_spec.rb
Labels: PR: unreviewed

#3433 Add basic (preliminary) pro accounts lander placeholder
  app/controllers/pro_accounts_controller.rb
  app/helpers/application_helper.rb
  app/views/pro_accounts/index.html.erb
  config/routes.rb
  spec/requests/pro_accounts_spec.rb
Labels: PR: unreviewed

#3434 Fix slackbot ping issue and tag copy
  app/controllers/partnerships_controller.rb
  app/views/partnerships/_form.html.erb
  app/views/partnerships/_tag_sponsor_copy.html.erb
Labels: PR: unreviewed

#3370 Add location to listings
  app/controllers/classified_listings_controller.rb
  app/controllers/concerns/classified_listings_toolkit.rb
  app/javascript/listings/__tests__/__snapshots__/listingDashboard.test.jsx.snap
  app/javascript/listings/__tests__/listingDashboard.test.jsx
  app/javascript/listings/dashboard/listingRow.jsx
  app/javascript/listings/singleListing.jsx
  app/models/classified_listing.rb
  app/views/classified_listings/_form.html.erb
  app/views/classified_listings/dashboard.html.erb
  app/views/classified_listings/edit.html.erb
  app/views/classified_listings/index.html.erb
  db/migrate/20190702194019_add_location_to_classified_listings.rb
  db/schema.rb
  db/seeds.rb
Labels: PR: reviewed-approved, listings

#3438 Sponsorship: add model (step 1)
  app/controllers/admin/sponsorships_controller.rb
  app/controllers/admin/tags_controller.rb
  app/dashboards/dashboard_manifest.rb
  app/dashboards/sponsorship_dashboard.rb
  app/dashboards/tag_dashboard.rb
  app/models/organization.rb
  app/models/sponsorship.rb
  db/migrate/20190710081915_create_new_sponsorships.rb
  db/schema.rb
  lib/tasks/temporary/sponsorships.rake
  spec/factories/sponsorships.rb
  spec/models/organization_spec.rb
  spec/models/sponsorship_spec.rb
Labels: PR: reviewed-approved

#3440 Sponsorship: business logic (step 2)
  app/controllers/partnerships_controller.rb
  app/controllers/tags_controller.rb
  app/decorators/organization_decorator.rb
  app/decorators/sponsorship_decorator.rb
  app/helpers/application_helper.rb
  app/models/sponsorship.rb
  app/models/tag.rb
  app/views/articles/_sidebar.html.erb
  app/views/articles/_single_sponsor.html.erb
  app/views/articles/tags/_sidebar.html.erb
  app/views/organizations/_sidebar_additional.html.erb
  app/views/pages/sponsors.html.erb
  app/views/partnerships/_form.html.erb
  app/views/partnerships/show.html.erb
  app/views/tags/index.html.erb
  config/routes.rb
  spec/models/sponsorship_spec.rb
  spec/requests/partnerships_spec.rb
  spec/requests/stories_index_spec.rb
  spec/requests/user_profile_spec.rb
Labels: PR: reviewed-approved

#3390 Fix long text code block preview from overflowing out of parent
  app/assets/stylesheets/comments.scss
Labels: PR: reviewed-approved

#3421 listings dashboard: sorting listings by created and bumped dates
  app/assets/stylesheets/classified_listings.scss
  app/javascript/listings/__tests__/__snapshots__/listingDashboard.test.jsx.snap
  app/javascript/listings/listingDashboard.jsx
  app/views/classified_listings/dashboard.html.erb
Labels: PR: reviewed-approved, listings

#3317 Toggle between PREVIEW and EDIT in article
  app/javascript/article-form/elements/publishToggle.jsx
  spec/system/articles/user_edits_an_article_spec.rb
Labels: PR: reviewed-approved

#3445 Add cursor for color select in Offline Page
  public/offline.html
Labels: PR: reviewed-approved

#3446 Sponsorship: remove old columns (step 3)
  app/controllers/admin/tags_controller.rb
  app/controllers/partnerships_controller.rb
  app/dashboards/organization_dashboard.rb
  app/dashboards/tag_dashboard.rb
  app/models/organization.rb
  app/models/tag.rb
  app/views/partnerships/_form.html.erb
  db/migrate/20190711070019_remove_sponsorship_old_columns.rb
  db/schema.rb
  lib/tasks/temporary/sponsorships.rake
  spec/requests/partnerships_spec.rb
Labels: PR: reviewed-approved

#3447 Credits ledger: show sponsorships
  app/assets/stylesheets/credits.scss
  app/services/credits/ledger.rb
  app/views/credits/_ledger.html.erb
  app/views/credits/_ledger_classified_listing.html.erb
  app/views/credits/_ledger_sponsorship.html.erb
  app/views/credits/index.html.erb
  spec/requests/credits_spec.rb
  spec/services/credits/ledger_spec.rb
Labels: PR: reviewed-approved

#3452 Fix copy on sponsorship page
  app/views/partnerships/_devrel_consult_copy.html.erb
  app/views/partnerships/index.html.erb
Labels: PR: unreviewed

#3459 Add inverted styling for social links in night mode on 'Key Links' page
  app/views/pages/information.html.erb
Labels: PR: reviewed-approved

#3458 Fix chat channel details profile pic issue
  app/models/chat_channel.rb
  app/views/api/v0/chat_channels/show.json.jbuilder
Labels: PR: unreviewed

#3386 Podcast episodes statuses #2952
  app/controllers/api/v0/podcast_episodes_controller.rb
  app/controllers/podcast_episodes_controller.rb
  app/controllers/stories_controller.rb
  app/dashboards/podcast_episode_dashboard.rb
  app/models/podcast_episode.rb
  app/services/podcasts/create_episode.rb
  app/services/podcasts/get_media_url.rb
  app/views/podcast_episodes/show.html.erb
  db/migrate/20190705111810_add_reachable_to_podcast_episodes.rb
  db/migrate/20190705114625_add_https_status_to_podcast_episodes.rb
  db/schema.rb
  spec/requests/podcast_episodes_api_spec.rb
  spec/requests/podcasts/podcast_episodes_index_spec.rb
  spec/requests/podcasts/podcast_show_spec.rb
  spec/services/podcasts/create_episode_spec.rb
  spec/services/podcasts/get_media_url_spec.rb
  spec/system/podcasts/user_visits_podcast_episode_spec.rb
Labels: PR: reviewed-approved

#3460 Don't check url and create podcast episode when there's no enclosure url
  app/services/podcasts/create_episode.rb
  app/services/podcasts/episode_rss_item.rb
  app/services/podcasts/get_episode.rb
  spec/services/podcasts/episode_rss_item_spec.rb
  spec/services/podcasts/get_episode_spec.rb
  spec/support/fixtures/podcasts/arresteddevops.xml
Labels: PR: reviewed-approved

#3464 Fix location link in single listing
  app/javascript/listings/singleListing.jsx
Labels: PR: reviewed-approved, listings

#3465 Add watercooler as sidebar tag and watercooler flare
  app/assets/stylesheets/articles.scss
  app/black_box/black_box.rb
  app/labor/flare_tag.rb
  app/views/articles/_sidebar_additional.html.erb
  app/views/classified_listings/_form.html.erb
  spec/black_box/black_box_spec.rb
Labels: PR: unreviewed

#3467 Add missing "dev-badge" class for proper night mode styling
  app/views/pages/badges.html.erb
Labels: PR: reviewed-approved

#3468 Adjust listings social image and add "About Listings" button to show page.
  app/assets/stylesheets/classified_listings.scss
  app/controllers/profile_pins_controller.rb
  app/javascript/listings/listings.jsx
  app/views/social_previews/listing.html.erb
Labels: PR: unreviewed

#3466 Fix ampersand not being escaped in Twitter share from the hamburger menu
  app/views/articles/_actions.html.erb
Labels: PR: reviewed-approved

#3335 Make xhr request's method dynamic for archiving.
  app/assets/javascripts/initializers/initializeEllipsisMenu.js
  app/controllers/articles_controller.rb
Labels: PR: unreviewed

#3488 Redirect to actual latest published thread
  app/controllers/pages_controller.rb
  spec/requests/pages_spec.rb
Labels: PR: reviewed-approved

#3492 Cache bust the article's path and add minor improvement for banishing
  app/labor/cache_buster.rb
  app/services/moderator/manage_activity_and_roles.rb
Labels: PR: reviewed-approved

#3450 Update podcast episode statuses #2952
  app/controllers/admin/podcasts_controller.rb
  app/jobs/podcast_episodes/update_media_url_job.rb
  app/jobs/podcasts/get_episodes_job.rb
  app/models/podcast.rb
  app/services/podcasts/feed.rb
  app/services/podcasts/get_episode.rb
  app/services/podcasts/update_episode.rb
  app/services/podcasts/update_episode_media_url.rb
  lib/tasks/fetch.rake
  spec/jobs/podcast_episodes/create_job_spec.rb
  spec/jobs/podcast_episodes/update_media_url_job_spec.rb
  spec/jobs/podcasts/get_episodes_job_spec.rb
  spec/requests/podcast_episodes_api_spec.rb
  spec/services/podcasts/feed_spec.rb
  spec/services/podcasts/get_episode_spec.rb
  spec/services/podcasts/update_episode_media_url_spec.rb
  spec/services/podcasts/update_episode_spec.rb
Labels: PR: reviewed-approved

#3308 Add support for hotkey to toggle article preview
  app/javascript/article-form/articleForm.jsx
  app/javascript/article-form/elements/keyboardShortcutsHandler.jsx
Labels: PR: reviewed-approved

#3495 Update Banisher
  app/services/moderator/banish_user.rb
  spec/requests/additional_content_boxes_spec.rb
Labels: PR: unreviewed

#2957 Add copy button to markdown image upload
  app/assets/stylesheets/preact/article-form.scss
  app/javascript/article-form/elements/imageManagement.jsx
  app/views/articles/edit.html.erb
  app/views/articles/new.html.erb
Labels: PR: reviewed-approved

#3496 A temp rake task to update podcast statuses
  lib/tasks/temporary/podcasts.rake
Labels: PR: reviewed-approved

#3501 Use each instead of find_each to keep order
  app/views/pages/sponsors.html.erb
Labels: PR: reviewed-approved

#3499 Open a page in a new tab w/o warning when playing a podcast #2958
  app/assets/javascripts/initializers/initializePodcastPlayback.js
Labels: PR: reviewed-approved

#3297 Add share to hacker news link
  app/views/articles/_actions.html.erb
Labels: PR: unreviewed

#3505 Remove logic relying on old podcast status
  app/views/podcast_episodes/show.html.erb
  lib/tasks/temporary/podcasts.rake
  spec/system/podcasts/user_visits_podcast_episode_spec.rb
Labels: PR: reviewed-approved

#3506 Open "buy credits" link in new tab in creating listings
  app/views/classified_listings/_form.html.erb
Labels: PR: reviewed-approved, listings

#3519 Use each instead of find_each to preserve order
  app/views/articles/_sidebar.html.erb
Labels: PR: reviewed-approved

#3510 Fix typos across dev.to repository
  Dockerfile
  app/controllers/classified_listings_controller.rb
  app/controllers/internal/tools_controller.rb
  app/controllers/twitch_stream_updates_controller.rb
  app/javascript/chat/chat.jsx
  app/labor/mailchimp_bot.rb
  app/models/chat_channel.rb
  app/models/profile_pin.rb
  app/views/pages/faq.html.erb
  config/environments/development.rb
  config/initializers/reverse_markdown.rb
  docker-run.sh
  docs/backend/pusher.md
  docs/getting-started/config-env.md
  docs/installation/docker.md
  spec/labor/email_logic_spec.rb
  spec/lib/acts_as_taggable_on/tag_parser_spec.rb
  spec/requests/twitch_stream_updates_spec.rb
Labels: PR: reviewed-approved

#3518 Make unsure specs more confident about time
  .travis.yml
  spec/services/analytics_service_spec.rb
  spec/services/credits/ledger_spec.rb
  spec/services/notifications/reactions/send_spec.rb
Labels: PR: reviewed-approved

#3534 Remove unnecessary `pluck` calls
  app/controllers/stories_controller.rb
  app/services/messages/send_push.rb
  app/services/notifications/new_follower/send.rb
  app/services/suggester/users/sidebar.rb
  spec/services/messages/send_push_spec.rb
Labels: PR: reviewed-approved

#3533 Change milestone notification statement to make it more clear
  app/views/notifications/_milestone.html.erb
Labels: PR: reviewed-approved

#3531 Remove double string escape by removing stip_tags from title
  app/liquid_tags/link_tag.rb
  spec/liquid_tags/link_tag_spec.rb
Labels: PR: reviewed-approved

#3539 Refactor the Spotify playlist option
  app/liquid_tags/spotify_tag.rb
  app/views/pages/api.html.erb
  spec/liquid_tags/spotify_tag_spec.rb
Labels: PR: reviewed-approved

#3532 Don't hide podcasts if they have reachable episodes
  app/jobs/podcasts/get_episodes_job.rb
  app/models/podcast.rb
  app/models/podcast_episode.rb
  app/services/podcasts/feed.rb
  db/migrate/20190723094834_add_index_to_podcasts_episodes.rb
  db/schema.rb
  spec/jobs/podcasts/get_episodes_job_spec.rb
  spec/jobs/shared_examples/enqueues_job.rb
  spec/models/podcast_spec.rb
  spec/requests/podcast_episodes_api_spec.rb
  spec/requests/stories_index_spec.rb
  spec/services/podcasts/feed_spec.rb
  spec/system/podcasts/user_visits_podcasts_root_page_spec.rb
Labels: PR: reviewed-approved

#3543 Remove duplicate property border-top-left-radius
  app/assets/stylesheets/comments.scss
Labels: PR: reviewed-approved

#3549 Tiny adjustments to copy and functionality of onboarding
  app/assets/stylesheets/preact/onboarding-modal.scss
  app/javascript/onboarding/__tests__/__snapshots__/Onboarding.test.jsx.snap
  app/javascript/onboarding/components/ClosingSlide.jsx
  app/javascript/onboarding/components/IntroSlide.jsx
Labels: PR: unreviewed

#3550 Make window.currentUser available globally
  app/javascript/packs/onboardingRedirectCheck.jsx
Labels: PR: unreviewed

#3486 Move delayed algoliasearch tasks to Active Jobs
  app/models/article.rb
  app/models/comment.rb
  app/models/user.rb
  spec/models/article_spec.rb
  spec/models/comment_spec.rb
  spec/models/user_spec.rb
Labels: PR: reviewed-approved

#3552 Added overflow-x: auto to comments.scss
  app/assets/stylesheets/comments.scss
Labels: PR: reviewed-approved

#3565 Add getunopenedchatchannels to onboardingredirect
  app/javascript/packs/onboardingRedirectCheck.jsx
Labels: PR: reviewed-approved

#3551 Fix out of place clipboard-copy icon
  app/assets/stylesheets/article-show.scss
Labels: PR: reviewed-approved

#3567 Update Bundler to 2.0.2
  Gemfile
  Gemfile.lock
Labels: PR: reviewed-approved

#3489 Bump organization listings with organization credits
  app/controllers/classified_listings_controller.rb
  spec/requests/classified_listings_spec.rb
Labels: PR: reviewed-approved, listings

#3442 Listing Dashboard: Handle expired listings
  app/assets/stylesheets/classified_listings.scss
  app/javascript/listings/__tests__/__snapshots__/listingDashboard.test.jsx.snap
  app/javascript/listings/dashboard/listingRow.jsx
  app/javascript/listings/listingDashboard.jsx
  app/views/classified_listings/dashboard.html.erb
Labels: PR: reviewed-approved, listings

#3569 Allow for the sending of arbitrary broadcasts
  app/services/notifications/welcome_notification/send.rb
  app/views/notifications/_broadcast.html.erb
Labels: PR: reviewed-approved

#3578 Fix failing algolia jobs
  app/models/comment.rb
  app/models/user.rb
  spec/models/comment_spec.rb
  spec/models/user_spec.rb
Labels: PR: reviewed-approved

#3576 Rename specs not named *_spec.rb
  spec/system/articles/user_visits_article_stats_spec.rb
  spec/system/user_adds_a_credit_card.rb
  spec/system/user_selects_looking_for_work_spec.rb
Labels: PR: reviewed-approved

#3572 Fix Video Duration to include hours
  app/models/article.rb
  spec/models/article_spec.rb
Labels: PR: reviewed-approved

#2367 Add index to ahoy_messages to
  db/migrate/20190410124957_add_index_to_ahoy_messages_to.rb
  db/schema.rb
Labels: PR: reviewed-approved

#3575 Remove all old membership code
  app/controllers/pages_controller.rb
  app/controllers/stripe_cancellations_controller.rb
  app/controllers/stripe_subscriptions_controller.rb
  app/labor/mailchimp_bot.rb
  app/mailers/membership_mailer.rb
  app/models/role.rb
  app/models/user.rb
  app/services/membership_service.rb
  app/views/mailers/membership_mailer/new_membership_subscription_email.html.erb
  app/views/mailers/membership_mailer/new_membership_subscription_email.text.erb
  app/views/mailers/membership_mailer/subscription_cancellation_email.html.erb
  app/views/mailers/membership_mailer/subscription_cancellation_email.text.erb
  app/views/mailers/membership_mailer/subscription_update_confirm_email.html.erb
  app/views/mailers/membership_mailer/subscription_update_confirm_email.text.erb
  config/routes.rb
  db/seeds.rb
  spec/labor/mailchimp_bot_spec.rb
  spec/mailers/membership_mailer_spec.rb
  spec/mailers/previews/membership_mailer_preview.rb
  spec/requests/stripe_active_cards_spec.rb
  spec/requests/stripe_cancellations_spec.rb
  spec/services/membership_service_spec.rb
Labels: PR: reviewed-approved

#3243 Escape HTML in the notifications view
  app/views/notifications/_aggregated_reactions.html.erb
  app/views/notifications/_article.html.erb
  app/views/notifications/_comment.html.erb
  app/views/notifications/_milestone.html.erb
  app/views/notifications/_tagadjustment.html.erb
  spec/requests/notifications_spec.rb
Labels: PR: reviewed-approved

#3581 Upgrade Rubocop related gems and fix new violations
  .rubocop_todo.yml
  Gemfile.lock
  app/controllers/api/v0/follows_controller.rb
  spec/labor/user_similarity_spec.rb
  spec/liquid_tags/dev_comment_tag_spec.rb
  spec/liquid_tags/link_tag_spec.rb
  spec/liquid_tags/medium_tag_spec.rb
  spec/liquid_tags/null_tag_spec.rb
  spec/liquid_tags/organization_tag_spec.rb
  spec/liquid_tags/podcast_tag_spec.rb
  spec/liquid_tags/tag_tag_spec.rb
  spec/liquid_tags/tweet_tag_spec.rb
  spec/liquid_tags/user_tag_spec.rb
  spec/models/article_spec.rb
  spec/models/block_spec.rb
  spec/models/buffer_update_spec.rb
  spec/models/chat_channel_spec.rb
  spec/models/comment_spec.rb
  spec/models/credit_spec.rb
  spec/models/feedback_message_spec.rb
  spec/models/follow_spec.rb
  spec/models/github_repo_spec.rb
  spec/models/html_variant_spec.rb
  spec/models/identity_spec.rb
  spec/models/job_opportunity_spec.rb
  spec/models/mention_spec.rb
  spec/models/notification_spec.rb
  spec/models/podcast_spec.rb
  spec/models/poll_option_spec.rb
  spec/models/poll_skip_spec.rb
  spec/models/poll_vote_spec.rb
  spec/models/push_notification_subscription_spec.rb
  spec/models/reaction_spec.rb
  spec/models/tag_spec.rb
  spec/models/tweet_spec.rb
  spec/requests/api/v0/articles_spec.rb
Labels: PR: reviewed-approved

#3586 Remove columns that don't existing from schema.rb
  db/schema.rb
Labels: PR: reviewed-approved

#3587 Update to Chromedriver 76
  .travis.yml
  Gemfile.lock
  spec/support/initializers/capybara.rb
Labels: PR: reviewed-approved

#3585 Add more partnership pricing info
  app/views/partnerships/_bronze_sponsor_copy.html.erb
  app/views/partnerships/_devrel_consult_copy.html.erb
  app/views/partnerships/_gold_sponsor_copy.html.erb
  app/views/partnerships/_media_sponsor_copy.html.erb
  app/views/partnerships/_silver_sponsor_copy.html.erb
  app/views/partnerships/_tag_sponsor_copy.html.erb
Labels: PR: unreviewed

#3504 Implement Doorkeeper gem
  Gemfile
  Gemfile.lock
  app/models/user.rb
  config/initializers/doorkeeper.rb
  config/locales/doorkeeper.en.yml
  config/routes.rb
  db/migrate/20190717220437_create_doorkeeper_tables.rb
  db/schema.rb
  spec/models/user_spec.rb
Labels: PR: reviewed-approved

#3589 Track success of DEV Shop ads
  app/assets/javascripts/initializePage.js.erb
  app/assets/javascripts/initializers/initializeBaseTracking.js.erb
  app/controllers/display_ad_events_controller.rb
  app/models/display_ad.rb
  app/models/display_ad_event.rb
  app/models/user.rb
  app/views/articles/_sidebar.html.erb
  app/views/articles/_sidebar_additional.html.erb
  config/routes.rb
  db/migrate/20190713213412_create_display_ad_events.rb
  db/migrate/20190713225409_add_success_rate_to_display_ads.rb
  db/schema.rb
  spec/factories/display_ad_events.rb
  spec/models/display_ad_event_spec.rb
  spec/models/display_ad_spec.rb
  spec/requests/display_ad_events_spec.rb
Labels: PR: unreviewed

#3325 Show article edit date in dashboard
  app/models/article.rb
  app/views/dashboards/_dashboard_article.html.erb
  spec/models/article_spec.rb
  spec/requests/dashboard_spec.rb
Labels: PR: reviewed-approved

#3541 Add organization membership functionality to internal
  app/assets/stylesheets/internal.scss
  app/controllers/internal/organization_memberships_controller.rb
  app/controllers/internal/tools_controller.rb
  app/controllers/internal/users_controller.rb
  app/dashboards/sponsorship_dashboard.rb
  app/models/organization.rb
  app/observers/application_observer.rb
  app/views/internal/users/_user_organizations.html.erb
  app/views/internal/users/edit.html.erb
  app/views/internal/users/index.html.erb
  app/views/internal/users/show.html.erb
  config/routes.rb
  db/seeds.rb
  spec/models/organization_spec.rb
  spec/requests/internal/users_spec.rb
Labels: PR: reviewed-approved

#3591 Make Doorkeeper inherit from ApplicationController
  config/initializers/doorkeeper.rb
  spec/requests/api/v0/articles_spec.rb
Labels: PR: reviewed-approved
