Repository forem/forem, pull requests merged in 2019-12, with the labels that each got.

#4950 Replace DEPLOYMENT_SIGNATURE with HEROKU_SLUG_COMMIT
  .rubocop_todo.yml
  Envfile
  app/views/articles/_sidebar.html.erb
  app/views/layouts/_styles.html.erb
  app/views/layouts/application.html.erb
  app/views/liquid_embeds/show.html.erb
  app/views/pages/live.html.erb
  app/views/pages/onboarding.html.erb
  app/views/partnerships/index.html.erb
  app/views/partnerships/show.html.erb
  app/views/pro_memberships/show.html.erb
Labels: PR: reviewed-approved

#4972 Customize UserContext Middleware in Timber logs
  config/initializers/timber.rb
Labels: PR: reviewed-approved

#4979 Fix gitpod setup
  .gitpod.dockerfile
  README.md
Labels: PR: reviewed-approved

#4989 Remove Unused Giveaways Code
  app/controllers/giveaways_controller.rb
  app/views/giveaways/new.html.erb
  config/routes.rb
Labels: PR: reviewed-approved

#4604 Chat: Remove Report Button from user's own profile sidebar
  app/javascript/chat/__tests__/__snapshots__/userDetails.test.jsx.snap
  app/javascript/chat/__tests__/userDetails.test.jsx
  app/javascript/chat/userDetails.jsx
  app/javascript/listings/listings.jsx
  app/javascript/onboarding/components/IntroSlide.jsx
  app/javascript/profileDropdown/blockButton.js
  app/javascript/shared/components/tags.jsx
Labels: PR: reviewed-approved

#4992 Add fosstodon to mastadon whitelist
  app/lib/constants.rb
Labels: PR: reviewed-approved

#4987 Replace serviceworker-rails gem with custome implementation
  Gemfile
  Gemfile.lock
  app/controllers/service_worker_controller.rb
  app/views/service_worker/index.js.erb
  app/views/service_worker/manifest.json.erb
  config/initializers/assets.rb
  config/initializers/serviceworker.rb
  config/routes.rb
  spec/requests/service_worker_spec.rb
Labels: PR: reviewed-approved

#4994 Add missing foreign keys to tag_adjustments
  db/migrate/20191203114809_add_missing_foreign_keys_tag_adjustments.rb
  db/schema.rb
Labels: PR: reviewed-approved

#4996 Set default Fastly Rails caching back to 30 days
  config/initializers/fastly.rb
  spec/requests/reactions_spec.rb
Labels: PR: reviewed-approved

#4997 Add missing fks to api_secrets, listings and identities
  db/migrate/20191203160028_add_missing_foreign_keys_api_secrets_listings_identities.rb
  db/schema.rb
  spec/models/identity_spec.rb
Labels: PR: reviewed-approved

#4988 Remove disable_indented_code_blocks
  config/initializers/redcarpet.rb
  spec/support/fixtures/approvals/user_preview_article_body.approved.html
  spec/support/fixtures/sample_article_template_spec.txt
Labels: PR: reviewed-approved

#4827 Rails 5.2 features: Enable default protect from forgery
  config/initializers/new_framework_defaults_5_2.rb
Labels: PR: reviewed-approved

#4903 Feature🚀: Ability to see chat history by scrolling up
  app/assets/stylesheets/chat.scss
  app/controllers/chat_channels_controller.rb
  app/javascript/chat/__tests__/__snapshots__/chat.test.jsx.snap
  app/javascript/chat/actions.js
  app/javascript/chat/chat.jsx
Labels: PR: reviewed-approved

#5001 Change copy on jump back button in /connect
  app/assets/stylesheets/chat.scss
  app/javascript/chat/__tests__/__snapshots__/chat.test.jsx.snap
  app/javascript/chat/chat.jsx
Labels: PR: unreviewed

#4993 Fix unique constraint violation on notifications create
  app/services/notifications/notifiable_action/send.rb
  spec/services/notifications/notifiable_action/send_spec.rb
Labels: PR: reviewed-approved

#4999 Add FKs to notifications_subscriptions, page_views and users_roles
  db/migrate/20191203171558_add_missing_foreign_keys_notifications_subs_page_views_users_roles.rb
  db/schema.rb
  spec/policies/article_policy_spec.rb
  spec/policies/chat_channel_policy_spec.rb
  spec/policies/comment_policy_spec.rb
  spec/policies/follow_policy_spec.rb
  spec/policies/github_repo_policy_spec.rb
  spec/policies/reaction_policy_spec.rb
  spec/policies/user_policy_spec.rb
Labels: PR: reviewed-approved

#5004 Update initializer and locales to doorkeeper 5.2.2
  config/initializers/doorkeeper.rb
  config/locales/doorkeeper.en.yml
Labels: PR: reviewed-approved

#5005 Rails 5.2 features: document why we can't enable some of them just yet
  config/initializers/new_framework_defaults_5_2.rb
Labels: PR: reviewed-approved

#5002 Add publication date to medium liquid tag (#4961)
  app/services/medium_article_retrieval_service.rb
  app/views/liquids/_medium.html.erb
  spec/liquid_tags/medium_tag_spec.rb
  spec/services/medium_article_retrieval_service_spec.rb
Labels: PR: reviewed-approved

#5007 Replace Airbrake with Honeybadger
  .rubocop_todo.yml
  .travis.yml
  Envfile
  Gemfile
  Gemfile.lock
  after_deploy.sh
  app/assets/javascripts/base.js.erb
  app/assets/javascripts/utilities/getCsrfToken.js.erb
  app/controllers/twitch_stream_updates_controller.rb
  app/labor/unread_notifications_emailer.rb
  app/views/internal/feedback_messages/_feedback_message.html.erb
  config/initializers/airbrake.rb
  config/initializers/honeybadger.rb
  docs/deployment.md
  docs/technical-overview/stack.md
  spec/support/fixtures/approvals/github_issue_test.approved.html
  spec/support/fixtures/vcr_cassettes/github_issue_api.yml
Labels: PR: reviewed-approved

#4991 Setup dual Redis store for rolling over fragment cacheing to Redis
  config/environments/development.rb
  config/environments/production.rb
  lib/active_support/cache/dual_rails_store.rb
  spec/lib/active_support/cache/dual_rails_store_spec.rb
Labels: PR: reviewed-approved

#5014 Revert "Setup dual Redis store for rolling over fragment cacheing to Redis"
  config/environments/development.rb
  config/environments/production.rb
  lib/active_support/cache/dual_rails_store.rb
  spec/lib/active_support/cache/dual_rails_store_spec.rb
Labels: PR: reviewed-approved

#5021 Group SIGTERM fetch_all_rss rake task Honeybadger Errors
  config/initializers/honeybadger.rb
  spec/initializers/honeybadger_spec.rb
Labels: PR: reviewed-approved

#4658 Add SRI Support
  app/views/articles/edit.html.erb
  app/views/articles/new.html.erb
  app/views/articles/show.html.erb
  app/views/shared/_webcomponents_loader_script.html.erb
  app/views/users/_org_admin.html.erb
Labels: PR: reviewed-approved

#5027 Group all BANNED errors in Honeybadger
  config/initializers/honeybadger.rb
  spec/initializers/honeybadger_spec.rb
Labels: PR: reviewed-approved

#5026 Add ENV variable to flip on Redis for fragment cacheing
  config/environments/production.rb
Labels: PR: reviewed-approved

#5028 Temporarily remove extra cache-oriented content
  app/labor/cache_buster.rb
  app/views/articles/_sticky_nav.html.erb
  app/views/articles/show.html.erb
  app/views/articles/tags/_sidebar_additional.html.erb
Labels: PR: reviewed-approved

#5030 Add additional content back in on sidebars and cache frequency
  app/labor/cache_buster.rb
  app/views/articles/_sticky_nav.html.erb
  app/views/articles/tags/_sidebar_additional.html.erb
Labels: PR: reviewed-approved

#5031 Add under-article article boxes
  app/views/articles/show.html.erb
Labels: PR: unreviewed

#5057 Remove Memcache Dalli gem and Setup Code
  Envfile
  Gemfile
  Gemfile.lock
  app/views/notifications/_article.html.erb
  config/environments/production.rb
  config/initializers/new_framework_defaults_5_2.rb
  docs/technical-overview/stack.md
Labels: PR: reviewed-approved

#5039 Added API related extensions to the recommended VS Code extensions
  .vscode/extensions.json
Labels: PR: reviewed-approved

#5058 Don't Alert Honeybadger until Right before a job is going to fail
  config/initializers/honeybadger.rb
Labels: PR: reviewed-approved

#5038 Extract image_path out of factories block
  spec/factories/badges.rb
  spec/factories/podcasts.rb
  spec/factories/users.rb
Labels: PR: reviewed-approved

#5016 Improve speed of model tests by around 50/60 seconds
  app/models/chat_channel.rb
  app/models/comment.rb
  app/models/display_ad.rb
  app/models/job_opportunity.rb
  app/models/mention.rb
  app/models/notification.rb
  app/models/page.rb
  app/models/podcast.rb
  app/models/podcast_episode.rb
  app/models/poll_skip.rb
  app/models/rating_vote.rb
  app/models/reaction.rb
  app/models/role.rb
  app/models/tag_adjustment.rb
  app/models/user.rb
  app/models/user_block.rb
  spec/decorators/user_decorator_spec.rb
  spec/factories/poll_skips.rb
  spec/models/article_spec.rb
  spec/models/audit_log_spec.rb
  spec/models/badge_achievement_spec.rb
  spec/models/badge_spec.rb
  spec/models/block_spec.rb
  spec/models/buffer_update_spec.rb
  spec/models/chat_channel_spec.rb
  spec/models/classified_listing_spec.rb
  spec/models/collection_spec.rb
  spec/models/comment_spec.rb
  spec/models/credit_spec.rb
  spec/models/display_ad_event_spec.rb
  spec/models/display_ad_spec.rb
  spec/models/event_spec.rb
  spec/models/feedback_message_spec.rb
  spec/models/html_variant_spec.rb
  spec/models/identity_spec.rb
  spec/models/job_opportunity_spec.rb
  spec/models/mention_spec.rb
  spec/models/message_spec.rb
  spec/models/notification_spec.rb
  spec/models/notification_subscription_spec.rb
  spec/models/organization_spec.rb
  spec/models/page_spec.rb
  spec/models/page_view_spec.rb
  spec/models/podcast_episode_spec.rb
  spec/models/podcast_spec.rb
  spec/models/poll_option_spec.rb
  spec/models/poll_skip_spec.rb
  spec/models/poll_spec.rb
  spec/models/profile_pin_spec.rb
  spec/models/rating_vote_spec.rb
  spec/models/reaction_create_spec.rb
  spec/models/reaction_destroy_spec.rb
  spec/models/reaction_spec.rb
  spec/models/role_spec.rb
  spec/models/search_keyword_spec.rb
  spec/models/sponsorship_spec.rb
  spec/models/tag_adjustment_spec.rb
  spec/models/user_block_spec.rb
  spec/models/user_spec.rb
  spec/models/webhook/event_spec.rb
Labels: PR: reviewed-approved

#5056 Feature🚀: Ability to Delete Messages realtime
  app/assets/stylesheets/chat.scss
  app/controllers/messages_controller.rb
  app/javascript/chat/__tests__/__snapshots__/chat.test.jsx.snap
  app/javascript/chat/__tests__/__snapshots__/message.test.jsx.snap
  app/javascript/chat/actions.js
  app/javascript/chat/chat.jsx
  app/javascript/chat/message.jsx
  app/javascript/src/utils/getUnopenedChannels.jsx
  app/javascript/src/utils/pusher.js
  app/policies/message_policy.rb
  app/views/chat_channels/show.json.jbuilder
  config/routes.rb
  spec/requests/messages_spec.rb
Labels: PR: reviewed-approved

#5059 Remove Temp RedisRailsCache and replace with Rails.cache
  app/controllers/api/v0/reactions_controller.rb
  app/controllers/async_info_controller.rb
  app/controllers/chat_channels_controller.rb
  app/controllers/ga_events_controller.rb
  app/controllers/reactions_controller.rb
  app/controllers/users_controller.rb
  app/decorators/user_decorator.rb
  app/helpers/application_helper.rb
  app/labor/assign_tag_moderator.rb
  app/labor/flare_tag.rb
  app/labor/follow_checker.rb
  app/labor/reading_list.rb
  app/lib/html_css_to_image.rb
  app/models/pro_membership.rb
  app/models/reaction.rb
  app/models/tag.rb
  app/models/user.rb
  app/services/analytics_service.rb
  app/services/moderator/manage_activity_and_roles.rb
  app/services/suggester/articles/classic.rb
  app/services/suggester/users/sidebar.rb
  app/services/users/delete.rb
  app/services/users/request_destroy.rb
  app/view_objects/articles/social_image.rb
  config/environments/production.rb
  config/initializers/redis_rails.rb
  spec/lib/html_css_to_image_spec.rb
  spec/requests/user/user_destroy_spec.rb
  spec/services/users/delete_spec.rb
  spec/system/user/user_self_destroy_spec.rb
Labels: PR: reviewed-approved

#5071 Remove unused "Edit" button as follow-on to #5056
  app/assets/stylesheets/chat.scss
  app/javascript/chat/__tests__/__snapshots__/message.test.jsx.snap
  app/javascript/chat/message.jsx
Labels: PR: unreviewed

#5060 Fixing microdata main entity reference
  app/views/articles/show.html.erb
  app/views/users/_profile_header.html.erb
  app/views/users/show.html.erb
Labels: PR: reviewed-approved

#5067 Don't send Internal Errors to HoneyBadger
  config/initializers/honeybadger.rb
  spec/initializers/honeybadger_spec.rb
Labels: PR: reviewed-approved

#5066 Use find_or_create_by when updating a PageView
  app/controllers/page_views_controller.rb
Labels: PR: reviewed-approved

#5065 Ensure remember_user_token is present for Fastly with Specs
  app/controllers/async_info_controller.rb
  spec/requests/async_info_spec.rb
Labels: PR: reviewed-approved

#4944 Hide comment feature
  app/assets/javascripts/initializers/initializeBaseUserData.js
  app/assets/stylesheets/comments.scss
  app/controllers/comments_controller.rb
  app/helpers/comments_helper.rb
  app/javascript/contentDisplayPolicy/hideBlockedContent.js
  app/javascript/contentDisplayPolicy/initHiddenComments.js
  app/javascript/packs/contentDisplayPolicy.js
  app/models/comment.rb
  app/policies/comment_policy.rb
  app/views/articles/_comments_actions.html.erb
  app/views/comments/_comment.html.erb
  app/views/comments/_comment_proper.html.erb
  app/views/comments/index.html.erb
  config/routes.rb
  db/migrate/20191108153914_add_hidden_by_commentable_user_to_comments.rb
  db/migrate/20191210144342_add_any_comments_hidden_to_articles.rb
  db/schema.rb
  spec/models/comment_spec.rb
  spec/policies/comment_policy_spec.rb
  spec/requests/comments_spec.rb
  spec/requests/shared_examples/comment_hide_or_unhide_request.rb
Labels: PR: reviewed-approved

#5070 Fix pending tests
  spec/system/articles/user_edits_an_article_spec.rb
  spec/system/user/user_edits_integrations_spec.rb
Labels: PR: reviewed-approved

#4958 Feature/add nexttech liquid tag
  app/liquid_tags/nexttech_tag.rb
  app/views/liquids/_nexttech.html.erb
  app/views/pages/_editor_guide_text.html.erb
  docs/frontend/liquid-tags.md
  spec/liquid_tags/next_tech_tag_spec.rb
  spec/support/fixtures/approvals/nexttech_liquid_tag.approved.html
Labels: PR: reviewed-approved

#5074 Switch back to update_column For Improved PageView Performance
  app/controllers/page_views_controller.rb
Labels: PR: reviewed-approved

#5063 Fix Algolia deserialization errors
  app/jobs/search/index_job.rb
  app/models/article.rb
  app/models/comment.rb
  app/models/user.rb
  spec/jobs/search/index_job_spec.rb
  spec/models/article_spec.rb
  spec/models/comment_spec.rb
  spec/models/user_spec.rb
Labels: PR: reviewed-approved

#5079 Ensure that we have a slug and owner before attempting Article Lookup
  app/controllers/articles_controller.rb
Labels: PR: reviewed-approved

#5080 Changed `.nvmrc` to support more Node version managers
  .nvmrc
Labels: PR: reviewed-approved

#5092 Use find_or_create_by to avoid duplicate records
  app/controllers/poll_skips_controller.rb
Labels: PR: reviewed-approved

#5090 Remove dead code
  app/controllers/internal/dogfood_controller.rb
  app/views/internal/dogfood/index.html.erb
  config/routes.rb
Labels: PR: reviewed-approved

#5084 Fix Technical Overview links [ci skip]
  docs/technical-overview/readme.md
Labels: PR: reviewed-approved

#5098 Remove Caches for html that Contains No External Requests
  app/views/notifications/_article.html.erb
Labels: PR: reviewed-approved

#5094 Refactoring app/services/exporter/articles.rb
  app/services/exporter/articles.rb
Labels: PR: reviewed-approved

#5078 Write docs on single_resource_admin workaround
  docs/internal/readme.md
  docs/readme.md
Labels: PR: reviewed-approved

#5097 Add Optimization option to PR template Types
  .github/PULL_REQUEST_TEMPLATE.md
Labels: PR: reviewed-approved

#5096 Remove commented specs
  spec/system/user_views_and_closes_onboarding_spec.rb
  spec/system/user_visits_tags_page_spec.rb
Labels: PR: reviewed-approved

#5093 Return not_found Response rather than trying to authorize a nil object
  app/controllers/articles_controller.rb
  app/controllers/users_controller.rb
  spec/requests/articles/articles_spec.rb
  spec/requests/user/user_destroy_spec.rb
Labels: PR: reviewed-approved

#5102 Removed old indexing code from the User model
  app/models/article.rb
Labels: PR: reviewed-approved

#5100 Fix Algolia sign-up link [ci skip]
  docs/backend/algolia.md
Labels: PR: reviewed-approved

#5077 Raise an error response saying the endpoint does not support the xml format on Articles#feed.xml (#5073)
  app/views/articles/feed.xml
Labels: PR: reviewed-approved

#5017 Mod tooling: add tags via /mod refactor
  app/controllers/moderations_controller.rb
  app/controllers/tag_adjustments_controller.rb
  app/models/tag_adjustment.rb
  app/services/tag_adjustment_creation_service.rb
  app/views/moderations/mod.html.erb
  spec/factories/tag_adjustments.rb
  spec/models/tag_adjustment_spec.rb
  spec/services/notifications/tag_adjustment_notification/send_spec.rb
  spec/services/tag_adjustment_update_service_spec.rb
Labels: PR: reviewed-approved

#5104 Remove Unused Aggregation Reaction cache
  app/views/notifications/_aggregated_reactions.html.erb
Labels: PR: reviewed-approved

#5103 Default return all user notifications if filter is unknown
  app/controllers/notifications_controller.rb
  spec/requests/notifications_spec.rb
Labels: PR: reviewed-approved

#5076 Asynchronously Update Algolia after a PageView Update
  app/jobs/search/index_job.rb
  app/models/page_view.rb
  spec/models/page_view_spec.rb
Labels: PR: reviewed-approved

#5109 Expand Lint-staged's ruby coverage
  package.json
Labels: PR: reviewed-approved

#5105 Cosmetic adjustment + code cleanup for article/mod page
  app/assets/stylesheets/moderators.scss
  app/views/moderations/mod.html.erb
Labels: PR: unreviewed

#5113 Add abuse report seed data
  db/seeds.rb
Labels: PR: reviewed-approved

#5117 refactor: minor code refactoring
  app/javascript/shared/components/tags.jsx
Labels: PR: reviewed-approved

#5115 Fixes glitch tag full screen button
  app/views/liquids/_glitch.html.erb
Labels: PR: reviewed-approved

#5118 Fix Backend Guide > Roles admin links [ci skip]
  docs/backend/roles.md
Labels: PR: reviewed-approved

#5136 Bump httparty from 0.17.2 to 0.17.3
  Gemfile.lock
Labels: PR: reviewed-approved, dependencies, ruby

#5110 Internal bulk badge awarder
  app/controllers/internal/badges_controller.rb
  app/views/internal/badges/index.html.erb
  app/views/internal/shared/_navbar.html.erb
  config/routes.rb
  spec/requests/internal/badges_spec.rb
  spec/system/internal/admin_awards_badges_spec.rb
  spec/system/internal/admin_bans_or_warns_user_spec.rb
  spec/system/internal/admin_creates_new_event_spec.rb
Labels: PR: reviewed-approved

#5114 Fix rubocop Rails.root.path complaints
  config/application.rb
  config/environments/development.rb
  config/initializers/assets.rb
  config/initializers/liquid.rb
  config/initializers/reverse_markdown.rb
  db/seeds.rb
  spec/factories/badges.rb
  spec/factories/organizations.rb
  spec/factories/podcasts.rb
  spec/factories/users.rb
  spec/models/comment_spec.rb
  spec/rails_helper.rb
  spec/requests/admin/podcasts_spec.rb
  spec/requests/image_uploads_spec.rb
  spec/requests/user/user_organization_spec.rb
  spec/system/organization/user_updates_org_settings_spec.rb
Labels: PR: reviewed-approved

#5020 Migrate to streaming app shell via serviceworkers
  app/assets/stylesheets/scaffolds.scss
  app/assets/stylesheets/settings.scss
  app/controllers/application_controller.rb
  app/controllers/async_info_controller.rb
  app/controllers/shell_controller.rb
  app/helpers/application_helper.rb
  app/javascript/chat/chat.jsx
  app/javascript/contentDisplayPolicy/hideBlockedContent.js
  app/views/articles/delete_confirm.html.erb
  app/views/articles/index.html.erb
  app/views/articles/tag_index.html.erb
  app/views/classified_listings/delete_confirm.html.erb
  app/views/comments/delete_confirm.html.erb
  app/views/layouts/_nav_menu.html.erb
  app/views/layouts/_styles.html.erb
  app/views/layouts/application.html.erb
  app/views/service_worker/index.js.erb
  app/views/shell/_bottom.html.erb
  app/views/shell/_top.html.erb
  app/views/users/signout_confirm.html.erb
  config/environments/development.rb
  config/environments/production.rb
  config/initializers/fastly.rb
  config/initializers/initialization_cachebust.rb
  config/routes.rb
  docs/technical-overview/architecture.md
  public/404.html
  public/500.html
  public/offline.html
  spec/requests/async_info_spec.rb
  spec/requests/service_worker_spec.rb
  spec/system/comments/user_delete_a_comment_spec.rb
Labels: PR: unreviewed

#5138 Guard for presence of page-content in JS
  app/assets/javascripts/base.js.erb
  app/assets/javascripts/initializers/initializeFooterMod.js
  app/views/service_worker/index.js.erb
  public/offline.html
Labels: PR: unreviewed

#5141 Move navbar rendering JS inline
  app/assets/javascripts/initializers/initNotifications.js
  app/views/layouts/_top_bar.html.erb
Labels: PR: unreviewed

#5119 Refactor all has_enough_credits to enough_credits
  app/models/organization.rb
  app/models/user.rb
  app/services/credits/buyer.rb
  app/services/pro_memberships/biller.rb
  app/services/pro_memberships/creator.rb
  app/services/pro_memberships/expiration_notifier.rb
  app/views/partnerships/_form.html.erb
  spec/models/organization_spec.rb
  spec/models/user_spec.rb
Labels: PR: reviewed-approved

#5112 Expand the testing docs
  docs/tests/acceptance-tests.md
  docs/tests/readme.md
  docs/tests/regression-tests.md
  docs/tests/skip-ci.md
  docs/tests/unit-functional-tests.md
Labels: PR: reviewed-approved

#5144 Remove unnecessary catch
  app/views/service_worker/index.js.erb
Labels: PR: unreviewed

#4240 Refactor/lint onboarding slides
  app/javascript/onboarding/__tests__/__snapshots__/Onboarding.test.jsx.snap
  app/javascript/onboarding/components/EmailListTermsConditionsForm.jsx
  app/javascript/onboarding/components/PersonalInfoForm.jsx
  app/javascript/onboarding/components/SlideContent.jsx
Labels: PR: reviewed-approved

#5145 Monkeypatch method to ensure https redirect
  app/controllers/concerns/valid_request.rb
Labels: PR: unreviewed

#5147 Fix feedback_messages styling
  app/views/feedback_messages/index.html.erb
Labels: PR: reviewed-approved

#5146 Add edge caching to shell
  app/controllers/shell_controller.rb
  spec/requests/shells_spec.rb
Labels: PR: unreviewed

#5095 Refactoring app/policies/user_policy.rb
  app/policies/user_policy.rb
Labels: PR: reviewed-approved

#5140 Return ActionController::RoutingError error when Invalid Format is Requested
  app/controllers/application_controller.rb
  spec/requests/articles/articles_spec.rb
Labels: PR: reviewed-approved

#5158 Frontend bug fixes
  app/javascript/chat/chat.jsx
  app/javascript/searchableItemList/searchableItemList.js
  app/javascript/src/components/ItemList/ItemListItem.jsx
  app/models/reaction.rb
  app/views/chat_channels/index.html.erb
  app/views/shell/_top.html.erb
Labels: PR: unreviewed

#5149 Add view for managing organizations
  app/controllers/internal/organizations_controller.rb
  app/views/internal/organizations/_activity.html.erb
  app/views/internal/organizations/index.html.erb
  app/views/internal/organizations/show.html.erb
  app/views/internal/shared/_navbar.html.erb
  config/routes.rb
  spec/requests/internal/organizations_spec.rb
  spec/system/internal/admin_manages_organizations_spec.rb
Labels: PR: reviewed-approved

#5159 Skip serviceworker logic for Twitter iOS referrals
  app/views/service_worker/index.js.erb
Labels: PR: unreviewed

#5148 Fix erb-lint config
  .erb-lint.yml
Labels: PR: reviewed-approved

#5089 Dont Raise Error For Incorrect Liquid Tags
  app/labor/markdown_parser.rb
  spec/labor/markdown_parser_spec.rb
Labels: PR: reviewed-approved

#5165 Ignore ActiveRecord::QueryCanceled errors in Honeybadger
  config/initializers/honeybadger.rb
Labels: PR: reviewed-approved

#5155 Rubocop fixes
  app/controllers/comments_controller.rb
  app/controllers/stories_controller.rb
  config/environments/production.rb
  spec/policies/comment_policy_spec.rb
  spec/requests/internal/organizations_spec.rb
Labels: PR: reviewed-approved

#5160 Add a default message to badge award action
  app/controllers/internal/badges_controller.rb
  app/views/internal/badges/index.html.erb
  spec/requests/internal/badges_spec.rb
  spec/services/notifications/new_badge_achievement/send_spec.rb
  spec/system/internal/admin_awards_badges_spec.rb
Labels: PR: reviewed-approved

#5169 Return not_found Response If Video's Related Article is Not Found
  app/controllers/video_states_controller.rb
  spec/requests/video_states_update_spec.rb
Labels: PR: reviewed-approved

#5122 Fix #5072: Remove unnecessary reaction call
  app/assets/javascripts/initializers/initializeAllFollowButts.js
  app/assets/javascripts/initializers/initializeReadingListIcons.js
  app/assets/javascripts/utilities/buildArticleHTML.js.erb
  app/assets/stylesheets/articles.scss
  app/assets/stylesheets/more-articles.scss
  app/views/articles/_single_story.html.erb
  app/views/articles/index.html.erb
Labels: PR: reviewed-approved

#5171 Handle missing commentable In Social Preview
  app/controllers/social_previews_controller.rb
  app/views/social_previews/comment.html.erb
Labels: PR: reviewed-approved

#5179 Raise ActiveRecord::RecordNotFound if Org is Not Found
  app/controllers/organizations_controller.rb
  spec/requests/organizations_update_spec.rb
Labels: PR: reviewed-approved

#5181 Don't serviceworker cache ?preview= requests
  app/views/service_worker/index.js.erb
Labels: PR: reviewed-approved

#5167 Use raw SQL to Update page_views so new and existing Records can be updated
  app/controllers/page_views_controller.rb
Labels: PR: reviewed-approved

#5183 Add rake task to reward tag badges weekly
  lib/tasks/fetch.rake
Labels: PR: unreviewed

#5185 Revert "Use raw SQL to Update page_views so new and existing Records can be updated"
  app/controllers/page_views_controller.rb
Labels: PR: reviewed-approved

#5184 Flaky Spec Fix: Sequence factory podcast episode slugs and guids to ensure uniqueness
  spec/factories/podcast_episodes.rb
Labels: PR: reviewed-approved

#5182 Return 422 if params are missing when creating an article via the API
  app/controllers/api/v0/articles_controller.rb
  spec/requests/api/v0/articles_spec.rb
Labels: PR: reviewed-approved

#4942 Add GitPitchTag resolves #4761
  app/liquid_tags/gitpitch_tag.rb
  app/views/liquids/_gitpitch.html.erb
  app/views/pages/_editor_guide_text.html.erb
  spec/liquid_tags/gitpitch_tag_spec.rb
Labels: PR: reviewed-approved

#5139 🚀Feature/ability to edit messages
  .vscode/settings.json
  app/assets/stylesheets/chat.scss
  app/controllers/messages_controller.rb
  app/javascript/chat/__tests__/__snapshots__/chat.test.jsx.snap
  app/javascript/chat/__tests__/__snapshots__/compose.test.jsx.snap
  app/javascript/chat/__tests__/__snapshots__/message.test.jsx.snap
  app/javascript/chat/actions.js
  app/javascript/chat/chat.jsx
  app/javascript/chat/compose.jsx
  app/javascript/chat/message.jsx
  app/javascript/src/utils/getUnopenedChannels.jsx
  app/javascript/src/utils/pusher.js
  app/policies/message_policy.rb
  app/views/chat_channels/show.json.jbuilder
  config/routes.rb
  db/migrate/20191215145706_add_edited_at_to_messages.rb
  db/schema.rb
  spec/requests/messages_spec.rb
Labels: PR: reviewed-approved

#5190 Flaky Spec Fix: Ensure model properties in factories are unique
  spec/factories/articles.rb
  spec/factories/badges.rb
  spec/factories/chat_channels.rb
  spec/factories/collections.rb
  spec/factories/github_repos.rb
Labels: PR: reviewed-approved

#5192 Return not_found response if we cant return users via the api
  app/controllers/api/v0/users_controller.rb
  spec/requests/api/v0/users_spec.rb
Labels: PR: reviewed-approved

#5193 Flaky Spec Fix: Check user follow count AFTER job is run
  spec/system/user_selects_looking_for_work_spec.rb
Labels: PR: reviewed-approved

#5189 Fix tag badge task logic
  lib/tasks/fetch.rake
Labels: PR: reviewed-approved

#5197 Ensure Comment has a path when created for specs
  spec/factories/comments.rb
  spec/system/comments/user_edits_a_comment_spec.rb
Labels: PR: reviewed-approved

#5198 Separate chat channel unopened status from Algolia
  app/assets/stylesheets/chat.scss
  app/assets/stylesheets/scaffolds.scss
  app/controllers/chat_channels_controller.rb
  app/javascript/chat/__tests__/__snapshots__/message.test.jsx.snap
  app/javascript/chat/__tests__/channels.test.jsx
  app/javascript/chat/actions.js
  app/javascript/chat/channels.jsx
  app/javascript/chat/chat.jsx
  app/javascript/chat/message.jsx
  spec/requests/chat_channels_spec.rb
Labels: PR: unreviewed

#5203 Open /connect sidecar links in iframe
  app/assets/javascripts/initializers/initializePWAFunctionality.js
  app/assets/stylesheets/article-show.scss
  app/assets/stylesheets/chat.scss
  app/assets/stylesheets/scaffolds.scss
  app/javascript/chat/__tests__/__snapshots__/article.test.jsx.snap
  app/javascript/chat/__tests__/__snapshots__/channelDetails.test.jsx.snap
  app/javascript/chat/__tests__/__snapshots__/message.test.jsx.snap
  app/javascript/chat/__tests__/article.test.jsx
  app/javascript/chat/__tests__/channelDetails.test.jsx
  app/javascript/chat/article.jsx
  app/javascript/chat/channelDetails.jsx
  app/javascript/chat/chat.jsx
  app/javascript/chat/message.jsx
  app/models/message.rb
  app/views/layouts/_user_config.html.erb
  spec/models/message_spec.rb
Labels: PR: unreviewed

#5200 Bug Fix 🐞: Fixing missing edit and delete option
  app/javascript/chat/chat.jsx
Labels: PR: reviewed-approved

#5220 Add ability to open /new in connect sidecar
  app/javascript/chat/chat.jsx
  app/javascript/src/utils/getUnopenedChannels.jsx
  app/models/message.rb
Labels: PR: unreviewed

#5206 Improve twitter card caching
  app/views/social_previews/article.html.erb
  app/views/social_previews/comment.html.erb
  app/views/social_previews/user.html.erb
  spec/requests/social_previews_spec.rb
Labels: PR: reviewed-approved

#5224 Routine Rubocop fixes
  .rubocop_todo.yml
  app/models/message.rb
  spec/liquid_tags/git_pitch_tag_spec.rb
Labels: PR: reviewed-approved

#5230 Redo /mod for performance and usability
  app/assets/stylesheets/moderators.scss
  app/controllers/moderations_controller.rb
  app/models/article.rb
  app/views/articles/tags/_sidebar.html.erb
  app/views/moderations/index.html.erb
  config/routes.rb
  db/migrate/20191223202251_add_nth_published.rb
  db/schema.rb
  spec/models/article_spec.rb
  spec/requests/moderations_spec.rb
Labels: PR: unreviewed

#5176 Fix check for whether shell has changed
  app/views/service_worker/index.js.erb
Labels: PR: reviewed-approved

#5229 Show Count of users followed from API
  app/controllers/api/v0/follows_controller.rb
Labels: PR: reviewed-approved

#5232 Fix off-by-one in nth_published_by_author
  app/models/article.rb
  spec/models/article_spec.rb
Labels: PR: unreviewed

#5233 Fix off by one for nth_published_by_author
  app/models/article.rb
  spec/models/article_spec.rb
Labels: PR: unreviewed

#5234 Final fixes to /mod
  app/views/moderations/index.html.erb
  spec/requests/moderations_spec.rb
Labels: PR: unreviewed

#5231 Group Honeybadger Rack::Timeout::RequestTimeoutExceptions
  config/initializers/honeybadger.rb
  spec/initializers/honeybadger_spec.rb
Labels: PR: reviewed-approved

#5238 API: Return an empty result set instead of 404 in case users are not available
  app/controllers/api/v0/users_controller.rb
  spec/requests/api/v0/users_spec.rb
Labels: PR: reviewed-approved

#5194 Use ApiController for ChatChannels and Return not_found If no Channel
  app/controllers/api/v0/chat_channels_controller.rb
  spec/requests/api/v0/chat_channels_spec.rb
Labels: PR: reviewed-approved

#5235 Remove code related to vscode color customization
  .vscode/settings.json
Labels: PR: reviewed-approved

#5239 Refactor specs for Api::V0::FollowsController
  spec/requests/api/v0/follows_spec.rb
  spec/requests/follows_api_spec.rb
Labels: PR: reviewed-approved

#5241 Fix title_with_timeframe and Update rake task to not use return
  app/helpers/application_helper.rb
  lib/tasks/fetch.rake
Labels: PR: reviewed-approved

#5236 Fix flaky Notifications::NewFollower::Send spec
  app/services/notifications/new_follower/send.rb
  spec/services/notifications/new_follower/send_spec.rb
Labels: PR: reviewed-approved

#5248 Handle a case when lambda client returns an empty result
  app/labor/function_caller.rb
  spec/labor/function_caller_spec.rb
Labels: PR: reviewed-approved

#5244 Rubocop fixes
  spec/models/article_spec.rb
  spec/rails_helper.rb
Labels: PR: reviewed-approved

#5195 Only Update page_views When They Are Valid (ie created)
  app/controllers/page_views_controller.rb
  spec/requests/page_views_spec.rb
Labels: PR: reviewed-approved

#5062 Reformat some code to break up especially long lines.
  app/controllers/articles_controller.rb
  app/controllers/comments_controller.rb
  app/controllers/users_controller.rb
Labels: PR: reviewed-approved

#5180 Create rake Task to Destroy Old Notifications
  app/models/notification.rb
  lib/tasks/fetch.rake
  spec/factories/notifications.rb
  spec/models/notification_spec.rb
Labels: PR: reviewed-approved

#5249 Return a 401 Response when Github creds are bad via the API
  app/controllers/api/v0/github_repos_controller.rb
  spec/requests/api/v0/github_repos_spec.rb
Labels: PR: reviewed-approved

#5251 Add Index to Notifications created_at
  db/migrate/20191226202114_add_created_at_index_to_notifications.rb
  db/schema.rb
Labels: PR: reviewed-approved

#5255 Update Rubocop configuration for breaking changes
  .rubocop.yml
  .rubocop_todo.yml
Labels: PR: reviewed-approved

#5257 Fix deprecation for not_to raise_error
  spec/labor/markdown_parser_spec.rb
Labels: PR: reviewed-approved

#5252 Introduce Sidekiq For Background Jobs
  Envfile
  Gemfile
  Gemfile.lock
  Procfile
  Procfile.dev
  config/initializers/sidekiq.rb
  config/routes.rb
  docs/technical-overview/stack.md
  spec/rails_helper.rb
Labels: PR: reviewed-approved

#5201 Added Tooltip for Badges in index page (#5040)
  app/views/badges/index.html.erb
Labels: PR: reviewed-approved

#5262 Ignore delayed job and sidekiq dashboards in the service worker
  app/views/service_worker/index.js.erb
Labels: PR: reviewed-approved

#5256 Create less data for Notification.fast_destroy_old_notifications spec
  spec/models/notification_spec.rb
Labels: PR: reviewed-approved

#5246 #5226 Unescape page title.
  app/views/shell/_top.html.erb
Labels: PR: reviewed-approved

#5227 Add canonical url to posts even if internal nav
  app/views/articles/show.html.erb
  spec/requests/stories_show_spec.rb
Labels: PR: unreviewed

#5263 Flaky Spec Fix: Ensure that article tag_list always has more than 3 tags
  spec/models/tag_adjustment_spec.rb
Labels: PR: reviewed-approved

#5253 Record counts for important db tables to help track growth
  lib/tasks/fetch.rake
Labels: PR: reviewed-approved

#5259 Remove search keywords
  app/models/search_keyword.rb
  db/migrate/20191227114543_drop_search_keywords.rb
  db/schema.rb
  spec/models/search_keyword_spec.rb
Labels: PR: unreviewed

#5266 Disable Sidekiq web sessions to make it work with Redis sessions
  config/initializers/sidekiq.rb
Labels: PR: reviewed-approved

#5264 Check if an organization is present when creating a reaction
  app/controllers/reactions_controller.rb
Labels: PR: reviewed-approved

#5258 Remove push notification subscriptions
  app/controllers/push_notification_subscriptions_controller.rb
  app/models/push_notification_subscription.rb
  app/models/user.rb
  config/routes.rb
  db/migrate/20191227113154_drop_push_notification_subscriptions.rb
  db/schema.rb
  spec/models/push_notification_subscription_spec.rb
  spec/models/user_spec.rb
  spec/requests/push_notification_subscriptions_spec.rb
Labels: PR: reviewed-approved
