Repository forem/forem, pull requests merged in 2019-03, with the labels that each got.

#1927 Update save(d) button states after articles are loaded, fixes #1785
  app/assets/javascripts/initializers/initializeFetchFollowedArticles.js.erb
  app/assets/javascripts/initializers/initializeReadingListIcons.js
  app/assets/javascripts/initializers/initializeReadingListPage.js.erb
Labels: PR: unreviewed

#1932 Simplify ArticlesController#feed
  app/controllers/articles_controller.rb
Labels: PR: unreviewed

#1933 Feature : `SEND_LOGS_TO_TIMBER` env variable to enable or disable timber logging
  config/environments/development.rb
  config/environments/production.rb
Labels: PR: reviewed-approved

#1907 Fix linting issues in app/views/videos
  .erb-lint.yml
  app/views/videos/new.html.erb
Labels: PR: reviewed-approved

#1920 Add Milestone Notifications
  app/assets/stylesheets/notifications.scss
  app/decorators/notification_decorator.rb
  app/labor/article_analytics_fetcher.rb
  app/labor/random_gif.rb
  app/models/notification.rb
  app/views/notifications/_article.html.erb
  app/views/notifications/_milestone.html.erb
  spec/models/notification_spec.rb
  yarn.lock
Labels: PR: reviewed-approved

#1939 Add missing data for org milestone notifications
  app/labor/random_gif.rb
  app/models/notification.rb
Labels: PR: reviewed-approved

#1936 Fix issue with boosted article in email digest
  app/labor/email_logic.rb
  app/mailers/digest_mailer.rb
  app/views/mailers/digest_mailer/digest_email.html.erb
  spec/factories/articles.rb
  spec/labor/email_digest_spec.rb
  spec/labor/email_logic_spec.rb
Labels: PR: unreviewed

#1945 add gifs to random_gif.rb
  app/labor/random_gif.rb
Labels: PR: reviewed-approved

#1951 Add GitDocs to "🔑 Key App tech/services" [skip ci]
  docs/addl-tech.md
Labels: PR: reviewed-approved

#1954 Fix some internal styling and add some internal tooling
  app/assets/javascripts/initializers/initializeFetchFollowedArticles.js.erb
  app/controllers/internal/articles_controller.rb
  app/controllers/users_controller.rb
  app/labor/email_digest.rb
  app/labor/email_logic.rb
  app/views/internal/articles/index.html.erb
  app/views/layouts/internal.html.erb
  app/views/mailers/digest_mailer/digest_email.html.erb
Labels: PR: unreviewed

#1956 Switch satellite view to any: true for tags
  app/controllers/internal/articles_controller.rb
Labels: PR: unreviewed

#1966 Fix rubocop issues
  .rubocop.yml
  .rubocop_todo.yml
  app/views/articles/feed.rss.builder
  config/environments/development.rb
  config/environments/production.rb
  config/routes.rb
  spec/requests/organizations_update_spec.rb
  spec/requests/stripe_cancellations_spec.rb
Labels: PR: reviewed-approved

#1968 Add shecoded page
  app/assets/images/SheCodedBackground.png
  app/assets/images/SheCodedLogo.png
  app/controllers/pages_controller.rb
  app/views/pages/shecoded.html.erb
  config/routes.rb
Labels: PR: unreviewed

#1969 Add shecoded meta tags
  app/views/pages/shecoded.html.erb
Labels: PR: unreviewed

#1967 Enable delayed_job web interface for admins
  Gemfile
  config/routes.rb
  spec/requests/delayed_job_spec.rb
Labels: PR: reviewed-approved

#1971 Basics of pro dashboard
  app/controllers/dashboards_controller.rb
  app/models/role.rb
  app/policies/user_policy.rb
  app/views/dashboards/pro.html.erb
  config/routes.rb
  spec/requests/dashboard_spec.rb
Labels: PR: unreviewed

#1972 Add tag template to v2 editor
  app/controllers/articles_controller.rb
  app/models/tag.rb
  app/views/articles/_v2_form.html.erb
Labels: PR: unreviewed

#1974 update shecoded copy
  app/views/pages/shecoded.html.erb
Labels: PR: reviewed-approved

#1975 Add shecoded social preview template
  app/controllers/social_previews_controller.rb
  app/views/social_previews/shecoded.html.erb
Labels: PR: unreviewed

#1977 Allow non-logged-in proper redirect for template posts
  app/controllers/articles_controller.rb
Labels: PR: unreviewed

#1957 Make less queries when displaying articles flare tags
  app/labor/flare_tag.rb
  app/models/article.rb
  app/views/articles/_tag_identifier.html.erb
  spec/labor/flare_tag_spec.rb
  spec/models/article_spec.rb
Labels: PR: reviewed-approved

#1944 Add new gifs to random_gif.rb
  app/labor/random_gif.rb
Labels: PR: merged

#1982 Adjust rankings to squash lingering popular stuff
  app/black_box/black_box.rb
Labels: PR: merged

#1980 Add ability to add pro role to internal
  app/controllers/internal/users_controller.rb
  app/models/user.rb
  app/policies/user_policy.rb
  app/views/internal/users/show.html.erb
Labels: PR: reviewed-approved

#1981 Add time ago to recent posts in feed
  app/assets/javascripts/initializers/initializeFetchFollowedArticles.js.erb
  app/assets/javascripts/utilities/buildArticleHTML.js.erb
  app/assets/javascripts/utilities/timeAgo.js
  app/assets/stylesheets/articles.scss
  app/decorators/article_decorator.rb
  app/views/articles/_single_story.html.erb
  app/views/articles/index.html.erb
  app/views/stories/_main_stories_feed.html.erb
Labels: PR: unreviewed

#1990 Minor improvements to tag admin
  app/controllers/admin/tags_controller.rb
  app/controllers/tags_controller.rb
  app/dashboards/tag_dashboard.rb
  app/policies/tag_policy.rb
  config/routes.rb
Labels: PR: reviewed-approved

#1993 Fix Mixed Content error in O RLY Parody Book Generator
  app/views/pages/generator.html.erb
Labels: PR: reviewed-approved

#1997 Specify node version to v10.15.0
  .nvmrc
  .travis.yml
Labels: PR: reviewed-approved

#1985 Add page_view model
  app/assets/javascripts/initializers/initializeBaseTracking.js.erb
  app/controllers/page_views_controller.rb
  app/models/article.rb
  app/models/page_view.rb
  app/models/user.rb
  config/routes.rb
  db/migrate/20190305221008_create_page_views.rb
  db/schema.rb
  spec/models/page_view_spec.rb
  spec/requests/page_views_spec.rb
Labels: PR: unreviewed

#1938 fix(runkit): Allow double quotes in preamble
  app/liquid_tags/runkit_tag.rb
Labels: PR: reviewed-approved

#1998 Use latest Node.js LTS Dubnium version
  .nvmrc
Labels: PR: reviewed-approved

#2000 Nevertheless, She Coded
  app/controllers/pages_controller.rb
  app/views/pages/shecoded.html.erb
  lib/tasks/fetch.rake
Labels: PR: unreviewed

#2003 Add shecoded sidebar/homepage decorations
  app/assets/stylesheets/articles.scss
  app/controllers/pages_controller.rb
  app/views/articles/_sidebar_additional.html.erb
  app/views/articles/index.html.erb
  app/views/pages/shecoded.html.erb
Labels: PR: unreviewed

#2006 Fix social card aspect ratio problem
  app/views/social_previews/shecoded.html.erb
Labels: PR: unreviewed

#2007 Ben/shecoded tweaks
  app/controllers/pages_controller.rb
  app/controllers/stories_controller.rb
Labels: PR: unreviewed

#2004 Fix sidebar widget header for she coded
  app/views/articles/_sidebar_additional.html.erb
Labels: PR: reviewed-approved

#2005 Update shecoded.html.erb copy!
  app/views/pages/shecoded.html.erb
Labels: PR: reviewed-approved

#2002 Fix undefined returned by timeAgo, showing up after the post date of older posts
  app/assets/javascripts/utilities/timeAgo.js
Labels: PR: reviewed-approved

#1970 Display comment published timestamp according to user's locale
  app/assets/javascripts/.eslintrc.js
  app/assets/javascripts/initializePage.js.erb
  app/assets/javascripts/initializers/initializeCommentDate.js
  app/assets/javascripts/initializers/initializeCommentsPage.js.erb
  app/assets/javascripts/initializers/initializeReadingListPage.js.erb
  app/assets/javascripts/utilities/buildCommentHTML.js.erb
  app/assets/javascripts/utilities/getLocalTime.js
  app/controllers/comments_controller.rb
  app/decorators/comment_decorator.rb
  app/liquid_tags/dev_comment_tag.rb
  app/views/comments/_comment_proper.html.erb
  app/views/users/_comments_section.html.erb
  spec/decorators/comment_decorator_spec.rb
  spec/features/comments/user_views_a_comment_spec.rb
  spec/features/user/view_user_index_spec.rb
  spec/liquid_tags/dev_comment_tag_spec.rb
Labels: PR: reviewed-approved

#2009 Add xoxo.zone to the allowed Mastodon instances
  app/lib/constants.rb
Labels: PR: reviewed-approved

#2011 Remove some hardcoded shecoded stuff
  app/assets/stylesheets/articles.scss
  app/controllers/stories_controller.rb
  app/views/articles/_sidebar_additional.html.erb
  app/views/articles/index.html.erb
Labels: PR: unreviewed

#2013 Fix typo in surrogate key header
  app/controllers/api/v0/articles_controller.rb
Labels: PR: reviewed-approved

#2037 Add initial charts implementation to pro dashboard
  app/controllers/dashboards_controller.rb
  app/decorators/chart_decorator.rb
  app/decorators/reaction_decorator.rb
  app/javascript/packs/proCharts.js
  app/views/dashboards/pro.html.erb
  package.json
  yarn.lock
Labels: PR: reviewed-approved

#2044 Fix charts and add nav buttons
  app/assets/stylesheets/dashboard.scss
  app/decorators/chart_decorator.rb
  app/views/dashboards/pro.html.erb
  app/views/dashboards/show.html.erb
Labels: PR: unreviewed

#2038 Add more logging to sign in failures
  app/controllers/omniauth_callbacks_controller.rb
Labels: PR: reviewed-approved

#1988 Optimize stories
  app/helpers/application_helper.rb
  app/labor/flare_tag.rb
  app/labor/sticky_article_collection.rb
  app/views/articles/_sticky_nav.html.erb
  db/migrate/20190306082543_add_index_to_articles_path.rb
  db/schema.rb
Labels: PR: reviewed-approved

#2015 Fixed time ago bug.
  app/assets/javascripts/initializers/initializeFetchFollowedArticles.js.erb
Labels: PR: reviewed-approved

#2047 Fixed typo on notifications state
  app/javascript/chat/chat.jsx
Labels: PR: unreviewed

#2039 Remove notifications when banishing and deleting a user
  app/models/comment.rb
  app/services/moderator/banisher.rb
Labels: PR: unreviewed

#1563 Implement open inbox for dev-connect
  app/assets/javascripts/initializePage.js.erb
  app/assets/javascripts/initializers/initializeAllChatButtons.js
  app/assets/javascripts/initializers/initializeAllFollowButts.js
  app/assets/javascripts/utilities/sendFetch.js
  app/assets/stylesheets/user-profile-header.scss
  app/controllers/chat_channels_controller.rb
  app/controllers/follows_controller.rb
  app/models/user.rb
  app/policies/user_policy.rb
  app/views/articles/_user_metadata.html.erb
  app/views/users/_misc.html.erb
  app/views/users/show.html.erb
  config/routes.rb
  db/migrate/20190121172642_add_inbox_to_user.rb
  db/migrate/20190121191754_change_inbox_name.rb
  docs/vocabulary.md
  spec/models/user_spec.rb
  spec/requests/follows_show_spec.rb
Labels: PR: unreviewed

#1844 Feature : docker-run.sh script + docker container build
  .dockerignore
  .gitignore
  Dockerfile
  docker-entrypoint.sh
  docker-run.sh
  dockerhub-readme.md
Labels: PR: unreviewed

#1866 Allow users to resize edit comment textarea element
  app/assets/stylesheets/comments.scss
Labels: PR: reviewed-approved

#1989 Fix unescaped front matter description in MarkdownFixer
  app/labor/markdown_fixer.rb
  spec/labor/markdown_fixer_spec.rb
Labels: PR: reviewed-approved

#2035 Refactor award_yearly_club_badges
  app/labor/badge_rewarder.rb
Labels: PR: unreviewed

#2018 Handle images uploading errors
  app/assets/javascripts/initializers/initializeCommentsPage.js.erb
  app/assets/stylesheets/preact/article-form.scss
  app/controllers/image_uploads_controller.rb
  app/javascript/article-form/actions.js
  app/javascript/article-form/elements/imageManagement.jsx
  app/views/articles/_markdown_form.html.erb
  spec/requests/image_uploads_spec.rb
Labels: PR: unreviewed

#2180 Bug fix broken giphy url
  app/views/notifications/_milestone.html.erb
Labels: PR: reviewed-approved

#2122 Moved new reaction notification method to a separate ActiveJob
  app/jobs/notifications/new_reaction_job.rb
  app/models/notification.rb
  app/models/reaction.rb
  app/services/notifications/reactions/reaction_data.rb
  app/services/notifications/reactions/send.rb
  spec/jobs/notifications/new_reaction_job_spec.rb
  spec/models/reaction_spec.rb
  spec/services/notifications/reactions/send_spec.rb
Labels: PR: reviewed-approved

#2191 Remove `dashboard/following_users` route
  app/controllers/dashboards_controller.rb
  app/views/dashboards/show.html.erb
  config/routes.rb
  spec/requests/dashboard_spec.rb
Labels: PR: reviewed-approved

#2206 Update Readme
  CONTRIBUTING.md
  README.md
Labels: PR: reviewed-approved

#2178 Feature/pro dashboard
  app/assets/stylesheets/dashboard.scss
  app/javascript/packs/proCharts.js
  app/views/dashboards/pro.html.erb
Labels: PR: reviewed-approved

#2215 DRY the Active Jobs specs
  spec/jobs/articles/bust_cache_job_spec.rb
  spec/jobs/articles/score_calc_job_spec.rb
  spec/jobs/follows/create_chat_channel_job_spec.rb
  spec/jobs/follows/send_email_notification_job_spec.rb
  spec/jobs/follows/touch_follower_job_spec.rb
  spec/jobs/notifications/new_follower_job_spec.rb
  spec/jobs/notifications/new_reaction_job_spec.rb
  spec/jobs/reactions/bust_homepage_cache_job_spec.rb
  spec/jobs/reactions/bust_reactable_cache_job_spec.rb
  spec/jobs/reactions/update_reactable_job_spec.rb
  spec/jobs/shared_examples/enqueues_job.rb
  spec/rails_helper.rb
Labels: PR: reviewed-approved

#2209 [Theme] Inverted social icons in night theme
  app/assets/stylesheets/articles.scss
  app/views/layouts/application.html.erb
Labels: PR: reviewed-approved

#2217 Add several recommended tags for onboarding
  app/models/tag.rb
Labels: PR: unreviewed

#2074 block/report abuse in dev-connect
  app/assets/javascripts/utilities/sendFetch.js
  app/assets/stylesheets/chat.scss
  app/controllers/chat_channels_controller.rb
  app/javascript/chat/__tests__/__snapshots__/userDetails.test.jsx.snap
  app/javascript/chat/content.jsx
  app/javascript/chat/userDetails.jsx
  app/models/chat_channel.rb
  config/routes.rb
Labels: PR: reviewed-approved

#2220 Clean up new chat channel functionality and add tests
  app/assets/javascripts/utilities/sendFetch.js
  app/controllers/chat_channels_controller.rb
  app/policies/chat_channel_policy.rb
  config/routes.rb
  spec/requests/chat_channels_spec.rb
Labels: PR: unreviewed

#2218 Improved article slug generation
  app/labor/podcast_feed.rb
  app/models/article.rb
  app/models/badge.rb
  app/models/chat_channel.rb
  app/models/event.rb
Labels: PR: reviewed-approved

#2214 Enabled a couple of rubocop cops which have no violations
  .rubocop.yml
Labels: PR: reviewed-approved

#2219 add scout config and gem
  Gemfile
  config/scout_apm.yml
Labels: PR: reviewed-approved

#2212 Extract "following" action from "show" in DashboardsController
  app/controllers/dashboards_controller.rb
  app/views/dashboards/_actions.html.erb
  app/views/dashboards/following.html.erb
  app/views/dashboards/show.html.erb
  config/routes.rb
  spec/requests/dashboard_spec.rb
Labels: PR: reviewed-approved

#2232 Rubocop fixes
  .rubocop.yml
  .rubocop_todo.yml
  app/controllers/html_variants_controller.rb
  app/models/chat_channel.rb
Labels: PR: reviewed-approved

#2229 Clear Cache When Merging Users
  app/services/moderator/merge_user.rb
Labels: PR: reviewed-approved

#2231 Optimize sign in: Identity #2061
  app/models/identity.rb
  db/migrate/20190327090030_add_indexes_to_indentities.rb
  db/schema.rb
  spec/models/identity_spec.rb
Labels: PR: reviewed-approved

#2236 Add form validation for follow 'points'
  app/views/dashboards/following.html.erb
Labels: PR: reviewed-approved

#2233 Fix notifications about the new child comments
  app/models/notification.rb
  spec/models/notification_spec.rb
Labels: PR: unreviewed

#2239 Scout Monitoring - Disable Remote IP Collection
  config/scout_apm.yml
Labels: PR: reviewed-approved

#2240 Fixed sticky nav summary color to use custom property.
  app/assets/stylesheets/sticky-nav.scss
Labels: PR: reviewed-approved

#2224 Remove controller specs
  Gemfile
  Gemfile.lock
  Guardfile
  app/helpers/feedback_messages_helper.rb
  app/labor/article_analytics_fetcher.rb
  spec/helpers/feedback_messages_helper_spec.rb
  spec/labor/article_analytics_fetcher_spec.rb
  spec/mailers/digest_mailer_spec.rb
  spec/rails_helper.rb
  spec/requests/api/v0/articles_spec.rb
  spec/requests/articles_spec.rb
  spec/requests/async_info_spec.rb
  spec/requests/chat_channels_spec.rb
  spec/requests/editor_spec.rb
  spec/requests/email_subscriptions_spec.rb
  spec/requests/internal/users_spec.rb
  spec/requests/notifications/reads_spec.rb
  spec/requests/social_previews_spec.rb
Labels: PR: reviewed-approved

#2241 Fixes Github Repositories not visible #2227
  app/assets/stylesheets/settings.scss
Labels: PR: reviewed-approved

#2243 Add night theme styling in various places
  app/assets/stylesheets/article_form.scss
  app/assets/stylesheets/articles.scss
  app/assets/stylesheets/comments.scss
  app/assets/stylesheets/preact/article-form.scss
  app/assets/stylesheets/scaffolds.scss
  app/assets/stylesheets/user-profile-header.scss
  app/views/layouts/application.html.erb
Labels: PR: unreviewed
