Repository forem/forem, pull requests merged in 2020-10, with the labels that each got.

#10471 API: add docs for api/follows/tags
  docs/api_v0.yml
Labels: PR: partially-approved

#10505 Split EdgeCache::Bust into Fastly + Nginx-specific classes
  app/services/edge_cache/bust.rb
  app/services/edge_cache/bust/fastly.rb
  app/services/edge_cache/bust/nginx.rb
  spec/services/edge_cache/bust_spec.rb
Labels: PR: partially-approved

#10514 Remove superfluous indexes on notifications
  db/migrate/20201001154006_remove_superfluous_indexes_from_notifications.rb
  db/schema.rb
Labels: PR: partially-approved

#10504 Refactor: Extract app-shell unsupported paths
  app/views/service_worker/index.js.erb
Labels: PR: partially-approved

#10515 Fixes 500 error when viewing the "Tag Mods" page without having the role on the database
  app/queries/admin/moderators_query.rb
  app/views/admin/mods/index.html.erb
  spec/queries/admin/moderators_query_spec.rb
  spec/requests/admin/mods_spec.rb
Labels: PR: partially-approved

#10519 Spec Fix:Dont Reuse Same Username and Let Factory Set Title
  spec/system/user/view_user_index_spec.rb
Labels: PR: partially-approved

#10516 Disable autoplay on native videos
  app/assets/javascripts/initializers/initializeVideoPlayback.js
Labels: PR: partially-approved

#10532 Slack notification with reminder to delete user gdpr data
  app/services/slack/messengers/user_deleted.rb
  app/workers/users/delete_worker.rb
  spec/services/slack/messengers/user_deleted_spec.rb
  spec/workers/users/delete_worker_spec.rb
Labels: PR: partially-approved

#10518 Optimization:Dont Notify of Channel Leavings
  app/controllers/chat_channel_memberships_controller.rb
  app/models/message.rb
  spec/models/message_spec.rb
  spec/requests/chat_channel_memberships_spec.rb
Labels: PR: partially-approved

#10530 Remove additional superfluous indexes
  db/migrate/20201002102257_remove_superfluous_indexes_part1.rb
  db/migrate/20201002102303_remove_superfluous_indexes_part2.rb
  db/schema.rb
Labels: PR: partially-approved

#10506 Manage listing categories in dashboard
  app/controllers/admin/listing_categories_controller.rb
  app/lib/constants/role.rb
  app/models/listing_category.rb
  app/views/admin/listing_categories/_form.html.erb
  app/views/admin/listing_categories/edit.html.erb
  app/views/admin/listing_categories/index.html.erb
  app/views/admin/listing_categories/new.html.erb
  app/views/admin/listings/index.html.erb
  config/routes.rb
  spec/requests/admin/listings_catogires_spec.rb
Labels: PR: partially-approved

#10339 Add co_author_ids to Articles
  app/controllers/admin/articles_controller.rb
  app/controllers/stories_controller.rb
  app/dashboards/article_dashboard.rb
  app/decorators/article_decorator.rb
  app/helpers/comments_helper.rb
  app/models/article.rb
  app/models/podcast_episode.rb
  app/views/admin/articles/_individual_article.html.erb
  app/views/articles/show.html.erb
  db/migrate/20200910155145_add_co_author_ids_to_articles.rb
  db/schema.rb
  lib/data_update_scripts/20200916202343_backfill_co_author_ids_for_articles.rb
  spec/models/article_spec.rb
  spec/requests/admin/articles_spec.rb
  spec/requests/stories_show_spec.rb
Labels: PR: unreviewed

#9444 Admin Panel for Configurable Navigational Links
  app/assets/stylesheets/admin.scss
  app/controllers/admin/application_controller.rb
  app/controllers/admin/navigation_links_controller.rb
  app/models/navigation_link.rb
  app/views/admin/navigation_links/_add_navigation_link_modal.html.erb
  app/views/admin/navigation_links/_edit_navigation_link_modal.html.erb
  app/views/admin/navigation_links/index.html.erb
  app/views/admin/profile_fields/_add_group_modal.html.erb
  app/views/articles/_sidebar_nav.html.erb
  config/routes.rb
  db/migrate/20201002104711_create_navigation_links.rb
  db/schema.rb
  spec/factories/navigation_links.rb
  spec/models/navigation_link_spec.rb
  spec/requests/admin/navigation_link_spec.rb
Labels: PR: unreviewed

#10537 Rename misspelled spec file
  spec/requests/admin/listings_categories_spec.rb
Labels: PR: reviewed-approved

#10538 Update CODEOWNERS to remove old teams
  .github/CODEOWNERS
Labels: PR: partially-approved

#10383 Removes second_user_id and third_user_id From the Articles Table
  db/migrate/20200918200231_remove_columns_from_articles.rb
  db/schema.rb
  lib/data_update_scripts/20200916202343_backfill_co_author_ids_for_articles.rb
Labels: PR: partially-approved

#10484 🚀Feature: Ability to upload images from clipboard in connect.
  app/javascript/chat/chat.jsx
  app/javascript/chat/compose.jsx
Labels: PR: partially-approved

#10536 added z-index to post editor options dropdown
  app/javascript/article-form/components/Options.jsx
Labels: PR: partially-approved

#10520 Refactor:Remove Screenshot Monkey Patch
  spec/support/initializers/monkeypatch_action_dispatch_screenshot_helper.rb
Labels: PR: partially-approved

#10527 CSS Cleanups, part 2
  app/assets/javascripts/initializers/initializeSpecialNavigationFunctionality.js
  app/assets/javascripts/initializers/initializeTouchDevice.js
  app/assets/stylesheets/_mixins.scss
  app/assets/stylesheets/article-show.scss
  app/assets/stylesheets/base/helpers.scss
  app/assets/stylesheets/base/layout.scss
  app/assets/stylesheets/base/main.scss
  app/assets/stylesheets/base/reset.scss
  app/assets/stylesheets/base/typography.scss
  app/assets/stylesheets/buttons.scss
  app/assets/stylesheets/components/header.scss
  app/assets/stylesheets/components/rich-selectors.scss
  app/assets/stylesheets/crayons.scss
  app/assets/stylesheets/dashboard.scss
  app/assets/stylesheets/fundamentals.scss
  app/assets/stylesheets/minimal.scss
  app/assets/stylesheets/scaffolds.scss
  app/assets/stylesheets/shared.scss
  app/assets/stylesheets/views.scss
  app/assets/stylesheets/views/article-form.scss
  app/assets/stylesheets/views/article.scss
  app/assets/stylesheets/views/signup-modal.scss
  app/decorators/user_decorator.rb
  app/javascript/.storybook/preview.js
  app/javascript/Search/SearchForm.jsx
  app/javascript/crayons/guidelines/__stories__/styling.md
  app/javascript/packs/Search.jsx
  app/javascript/packs/homePage.jsx
  app/views/admin/display_ads/index.html.erb
  app/views/articles/_bottom_content.html.erb
  app/views/articles/_sticky_nav.html.erb
  app/views/articles/_v2_form.html.erb
  app/views/layouts/_footer.html.erb
  app/views/layouts/_nav_menu.html.erb
  app/views/layouts/_styles.html.erb
  app/views/layouts/_top_bar.html.erb
  app/views/layouts/_user_config.html.erb
  app/views/layouts/admin.html.erb
  app/views/layouts/application.html.erb
  app/views/onboardings/show.html.erb
  app/views/shell/_top.html.erb
  spec/decorators/user_decorator_spec.rb
  spec/models/user_spec.rb
Labels: Crayons, PR: partially-approved, PR: unreviewed

#10384 Refactoring user_controller separating some classes to service
  app/controllers/admin/users_controller.rb
  app/services/credits/manage.rb
  spec/services/credits/manage_spec.rb
Labels: PR: partially-approved

#10355 Redesigned Comment Form
  app/assets/images/markdown.svg
  app/assets/images/templates.svg
  app/assets/javascripts/initializers/initializeCommentPreview.js
  app/assets/javascripts/initializers/initializeCommentsPage.js.erb
  app/assets/javascripts/utilities/buildCommentFormHTML.js.erb
  app/assets/javascripts/utilities/buildCommentHTML.js.erb
  app/assets/stylesheets/base/typography.scss
  app/assets/stylesheets/comments.scss
  app/assets/stylesheets/config/_colors.scss
  app/assets/stylesheets/views.scss
  app/assets/stylesheets/views/comments.scss
  app/javascript/responseTemplates/responseTemplates.js
  app/views/articles/_full_comment_area.html.erb
  app/views/comments/_comment_proper.html.erb
  app/views/comments/_form.html.erb
  app/views/comments/edit.html.erb
  spec/system/comments/user_edits_a_comment_spec.rb
  spec/system/comments/user_fills_out_comment_spec.rb
  spec/views/articles_spec.rb
Labels: Crayons, PR: partially-approved, PR: unreviewed, area: comments, area: design

#10578 Remove code link style so it uses the default link color
  app/assets/stylesheets/base/typography.scss
Labels: PR: reviewed-approved

#10609 [HOT FIX] Fix current_user cache issue in comments
  app/assets/javascripts/initializers/initializeBaseUserData.js
  app/views/comments/_form.html.erb
Labels: PR: partially-approved

#10602 Don't use "not_to raise_error" with specific class
  spec/labor/markdown_parser_spec.rb
  spec/liquid_tags/link_tag_spec.rb
  spec/liquid_tags/liquid_tag_base_spec.rb
  spec/services/github/oauth_client_spec.rb
  spec/workers/search/index_worker_spec.rb
  spec/workers/search/remove_from_index_worker_spec.rb
Labels: PR: partially-approved

#10577 Add twitch liquid tags
  app/helpers/articles_helper.rb
  app/liquid_tags/twitch_tag.rb
  app/views/articles/_fitvids.html.erb
  app/views/liquids/_twitch.html.erb
  app/views/pages/_editor_guide_text.html.erb
  app/views/pages/_editor_liquid_help.html.erb
  app/views/pages/markdown_basics.html.erb
  docs/frontend/liquid-tags.md
  spec/liquid_tags/twitch_tag_spec.rb
Labels: PR: partially-approved

#10616 Modify code to deal with flaky tests
  app/assets/javascripts/initializers/initializeCommentsPage.js.erb
  app/controllers/stories_controller.rb
  config/routes.rb
  spec/requests/profile_field_groups_request_spec.rb
Labels: PR: partially-approved

#10611 Removed unused CodeMirror CSS class
  app/assets/stylesheets/chat.scss
Labels: PR: reviewed-approved

#10622 Mention Facebook in authentication docs
  docs/backend/authentication.md
Labels: PR: reviewed-approved

#10632 Fixing padding on Notifications navigation
  app/views/notifications/_nav_menu.html.erb
Labels: PR: reviewed-approved, area: notifications, tech: html/css

#10620 Add default admin to seeds file
  db/seeds.rb
  docs/getting-started/db.md
Labels: PR: partially-approved

#10615 Add ability for admin to add anti-spam terms
  app/controllers/admin/configs_controller.rb
  app/lib/constants/site_config.rb
  app/models/article.rb
  app/models/comment.rb
  app/models/reaction.rb
  app/models/site_config.rb
  app/services/notifications/new_comment/send.rb
  app/views/admin/configs/show.html.erb
  app/views/admin/feedback_messages/_abuse_reports.html.erb
  spec/models/article_spec.rb
  spec/models/comment_spec.rb
  spec/requests/admin/configs_spec.rb
  spec/services/notifications/new_comment/send_spec.rb
Labels: PR: partially-approved

#10665 Fix spam trigger keyword input text
  app/views/admin/configs/show.html.erb
Labels: PR: unreviewed

#10630 🐞 Hotfix: Clipboard Text Paste Issue Fixed
  app/javascript/chat/chat.jsx
Labels: PR: reviewed-approved

#10623 Do not require SiteConfig.tagline
  app/controllers/concerns/verify_setup_completed.rb
  app/views/admin/configs/show.html.erb
  app/views/devise/invitations/edit.html.erb
  app/views/layouts/_signup_modal.html.erb
  spec/views/layouts/signup_modal.html.erb_spec.rb
Labels: PR: unreviewed

#10618 Return if receive own message
  app/javascript/utilities/connect/getUnopenedChannels.jsx
Labels: PR: reviewed-approved, area: notifications, javascript

#10612 feedback_message.message is required on backend but not required on view
  app/views/feedback_messages/_form.html.erb
Labels: PR: reviewed-approved

#10678 Remove community_action from SiteConfig
  app/controllers/admin/configs_controller.rb
  app/controllers/concerns/verify_setup_completed.rb
  app/lib/constants/site_config.rb
  app/models/site_config.rb
  app/views/admin/configs/show.html.erb
  app/views/mailers/digest_mailer/digest_email.html.erb
  app/views/mailers/notify_mailer/trusted_role_email.html.erb
  app/views/mailers/notify_mailer/trusted_role_email.text.erb
  spec/requests/admin/configs_spec.rb
  spec/system/admin/admin_manages_configuration_spec.rb
Labels: PR: partially-approved

#10245 Add feed_strategy config
  app/controllers/admin/configs_controller.rb
  app/controllers/stories/feeds_controller.rb
  app/controllers/stories_controller.rb
  app/lib/constants/site_config.rb
  app/models/site_config.rb
  app/services/articles/feed.rb
  app/services/articles/feeds/basic.rb
  app/services/articles/feeds/large_forem_experimental.rb
  app/views/admin/configs/show.html.erb
  docs/technical-overview/feed.md
  docs/technical-overview/readme.md
  spec/requests/admin/configs_spec.rb
  spec/requests/stories/feeds_spec.rb
  spec/services/articles/feeds/large_forem_experimental_spec.rb
Labels: PR: unreviewed

#10679 Auto-suspend multiple-spammers
  app/models/article.rb
  app/models/comment.rb
  app/models/reaction.rb
  spec/models/article_spec.rb
  spec/models/comment_spec.rb
Labels: PR: partially-approved

#10684 Allow pattern match for spam terms
  app/models/article.rb
  app/models/comment.rb
  app/views/admin/configs/show.html.erb
  spec/models/article_spec.rb
Labels: PR: partially-approved

#10685 Move spam check to after save
  app/models/article.rb
  app/models/comment.rb
Labels: PR: unreviewed

#10686 Limit articles created by newer users
  app/controllers/admin/configs_controller.rb
  app/helpers/rate_limit_checker_helper.rb
  app/models/site_config.rb
  app/services/articles/creator.rb
  app/services/rate_limit_checker.rb
  spec/requests/admin/configs_spec.rb
  spec/requests/articles/articles_create_spec.rb
  spec/services/rate_limit_checker_spec.rb
Labels: PR: unreviewed

#10593 Update BatchRewarder::REPOSITORIES
  app/labor/badge_rewarder.rb
Labels: PR: partially-approved

#10663 Move method #approved_liquid_tags to user service
  app/controllers/articles_controller.rb
  app/services/users/approved_liquid_tags.rb
  spec/services/users/approved_liquid_tags_spec.rb
Labels: PR: partially-approved

#10671 Add logo_svg to mandatory config fields
  app/controllers/concerns/verify_setup_completed.rb
Labels: PR: partially-approved

#10680 Add Recent Reactions to the Admin Users' Page
  app/controllers/admin/users_controller.rb
  app/views/admin/users/_reports.html.erb
  app/views/admin/users/edit.html.erb
  spec/requests/admin/users_spec.rb
Labels: PR: partially-approved

#10617 Skip service workers in development by default
  .env_sample
  app/views/service_worker/index.js.erb
Labels: PR: reviewed-approved

#10683 Remove random onboarding background images
  app/helpers/application_helper.rb
  app/views/admin/configs/show.html.erb
  app/views/onboardings/show.html.erb
  spec/helpers/application_helper_spec.rb
Labels: PR: partially-approved

#10662 Prepare the database for the configurable navigation items
  app/controllers/admin/navigation_links_controller.rb
  app/models/navigation_link.rb
  app/views/admin/navigation_links/_add_navigation_link_modal.html.erb
  app/views/admin/navigation_links/_edit_navigation_link_modal.html.erb
  app/views/admin/navigation_links/index.html.erb
  db/migrate/20201005181510_change_display_when_signed_in_column_name.rb
  db/migrate/20201007085440_add_position_to_navigation_links.rb
  db/migrate/20201007091041_add_unique_index_to_navigation_links_url_and_name.rb
  db/schema.rb
  lib/data_update_scripts/20201001173841_add_navigation_links.rb
  lib/tasks/temporary/add_dev_navigation_links.rake
Labels: PR: partially-approved, action: post deployment

#10717 Fix feed order for basic
  app/services/articles/feeds/basic.rb
  spec/models/article_spec.rb
  spec/services/articles/feeds/basic_spec.rb
Labels: PR: unreviewed

#10715 Ensure podcast episodes are created with processed_html
  app/services/podcasts/create_episode.rb
  spec/services/podcasts/create_episode_spec.rb
Labels: PR: unreviewed

#10464 Add scroll to Anchor
  app/assets/javascripts/base.js.erb
Labels: PR: partially-approved

#10488 Update Carrierwave's asset_host for Forem cloud
  config/initializers/carrierwave.rb
Labels: PR: reviewed-approved

#10720 Bump Rails to 6.0.3.4
  Gemfile.lock
  vendor/cache/actioncable-6.0.3.3.gem
  vendor/cache/actioncable-6.0.3.4.gem
  vendor/cache/actionmailbox-6.0.3.3.gem
  vendor/cache/actionmailbox-6.0.3.4.gem
  vendor/cache/actionmailer-6.0.3.3.gem
  vendor/cache/actionmailer-6.0.3.4.gem
  vendor/cache/actionpack-6.0.3.3.gem
  vendor/cache/actionpack-6.0.3.4.gem
  vendor/cache/actiontext-6.0.3.3.gem
  vendor/cache/actiontext-6.0.3.4.gem
  vendor/cache/actionview-6.0.3.3.gem
  vendor/cache/actionview-6.0.3.4.gem
  vendor/cache/activejob-6.0.3.3.gem
  vendor/cache/activejob-6.0.3.4.gem
  vendor/cache/activemodel-6.0.3.3.gem
  vendor/cache/activemodel-6.0.3.4.gem
  vendor/cache/activerecord-6.0.3.3.gem
  vendor/cache/activerecord-6.0.3.4.gem
  vendor/cache/activestorage-6.0.3.3.gem
  vendor/cache/activestorage-6.0.3.4.gem
  vendor/cache/activesupport-6.0.3.3.gem
  vendor/cache/activesupport-6.0.3.4.gem
  vendor/cache/nio4r-2.5.3.gem
  vendor/cache/nio4r-2.5.4.gem
  vendor/cache/rails-6.0.3.3.gem
  vendor/cache/rails-6.0.3.4.gem
  vendor/cache/railties-6.0.3.3.gem
  vendor/cache/railties-6.0.3.4.gem
  vendor/cache/sprockets-rails-3.2.1.gem
  vendor/cache/sprockets-rails-3.2.2.gem
Labels: PR: partially-approved

#10216 Connect: Highlight @ mentions to logged in user
  app/javascript/chat/__tests__/message.test.jsx
  app/javascript/chat/message.jsx
Labels: PR: partially-approved

#10732 Remove Twitch integration
  app/controllers/stories_controller.rb
  app/controllers/twitch_live_streams_controller.rb
  app/controllers/twitch_stream_updates_controller.rb
  app/controllers/users_controller.rb
  app/models/user.rb
  app/policies/user_policy.rb
  app/services/streams/twitch_access_token/get.rb
  app/services/streams/twitch_webhook/register.rb
  app/views/twitch_live_streams/no_twitch.html.erb
  app/views/twitch_live_streams/show.html.erb
  app/views/users/_integrations.html.erb
  app/views/users/show.html.erb
  app/workers/streams/twitch_webhook_registration_worker.rb
  config/routes.rb
  lib/tasks/twitch.rake
  spec/factories/users.rb
  spec/requests/twitch_stream_updates_spec.rb
  spec/requests/user/user_settings_spec.rb
  spec/requests/user/user_show_spec.rb
  spec/services/streams/twitch_access_token/get_spec.rb
  spec/services/streams/twitch_webhook/register_spec.rb
  spec/workers/streams/twitch_webhook_registration_worker_spec.rb
Labels: PR: partially-approved

#10735 Change admin password in docs
  docs/getting-started/db.md
Labels: PR: reviewed-approved

#10721 Do not require meta_keywords to be set
  app/controllers/concerns/verify_setup_completed.rb
  app/helpers/application_helper.rb
  app/views/admin/configs/show.html.erb
  app/views/articles/index.html.erb
  app/views/articles/search/_meta.html.erb
  app/views/articles/show.html.erb
  app/views/articles/tags/_meta.html.erb
  app/views/collections/_meta.html.erb
  app/views/comments/index.html.erb
  app/views/events/index.html.erb
  app/views/events/show.html.erb
  app/views/listings/index.html.erb
  app/views/notifications/index.html.erb
  app/views/pages/badges.html.erb
  app/views/pages/code_of_conduct.html.erb
  app/views/pages/contact.html.erb
  app/views/pages/editor_guide.html.erb
  app/views/pages/information.html.erb
  app/views/pages/markdown_basics.html.erb
  app/views/pages/privacy.html.erb
  app/views/pages/publishing_from_rss_guide.html.erb
  app/views/pages/report_abuse.html.erb
  app/views/pages/show.html.erb
  app/views/pages/sponsors.html.erb
  app/views/pages/terms.html.erb
  app/views/podcast_episodes/_meta.html.erb
  app/views/podcast_episodes/show.html.erb
  app/views/reading_list_items/index.html.erb
  app/views/tags/index.html.erb
  app/views/users/_meta.html.erb
  app/views/videos/index.html.erb
  spec/requests/articles/articles_show_spec.rb
  spec/requests/stories_index_spec.rb
  spec/system/admin/admin_manages_configuration_spec.rb
Labels: PR: partially-approved

#10741 Generalize Connect "Welcome Message"
  app/javascript/chat/__tests__/channels.test.jsx
  app/javascript/chat/channels.jsx
Labels: PR: reviewed-approved

#10487 fix: Clear chat input after Enter key submit
  app/assets/images/markdown.svg
  app/assets/images/templates.svg
  app/javascript/chat/__tests__/compose.test.jsx
  app/javascript/chat/chat.jsx
  app/javascript/chat/compose.jsx
  app/javascript/listings/__tests__/BodyMarkdown.test.jsx
  app/javascript/listings/components/Categories.jsx
  app/javascript/listings/components/Title.jsx
  app/javascript/shared/components/tags.jsx
  app/views/listings/_form.html.erb
Labels: PR: partially-approved

#10543 Remove tabindex of -1 on upload image input in the write a post editor
  app/assets/stylesheets/components/buttons.scss
  app/javascript/article-form/components/ImageUploader.jsx
Labels: PR: reviewed-approved, accessibility

#10736 Add recaptcha keys to as site-configurable keys
  app/controllers/admin/configs_controller.rb
  app/controllers/feedback_messages_controller.rb
  app/lib/constants/site_config.rb
  app/models/site_config.rb
  app/views/admin/configs/show.html.erb
  app/views/feedback_messages/_form.html.erb
  spec/requests/admin/configs_spec.rb
  spec/requests/feedback_messages_spec.rb
Labels: PR: reviewed-approved

#10719 Add Section for Series/Collections
  docs/technical-overview/architecture.md
Labels: PR: partially-approved

#10614 Articles API: filtering by tags (#3654)
  app/services/article_api_index_service.rb
  docs/api_v0.yml
  spec/requests/api/v0/articles_spec.rb
Labels: PR: partially-approved

#10742 Move Imgproxy endpoint config to Images::Optimizer
  app/services/images/optimizer.rb
  config/initializers/imgproxy.rb
Labels: PR: unreviewed

#10746 Link Email Account creation UI to existing Create Account UI
  app/assets/stylesheets/components/buttons.scss
  app/views/devise/registrations/new.html.erb
  app/views/shared/authentication/_providers_registration_form.html.erb
  spec/requests/registrations_spec.rb
Labels: PR: partially-approved

#10747 Add forem meta tags
  app/views/shell/_top.html.erb
  docs/technical-overview/compatibility.md
  docs/technical-overview/readme.md
Labels: PR: unreviewed

#10750 Remove Twitch-related columns from users table
  db/migrate/20201009040438_remove_twitch_columns_from_user.rb
  db/schema.rb
Labels: PR: partially-approved

#10740 Long text goes outside cards
  app/assets/stylesheets/components/cards.scss
Labels: PR: partially-approved

#10757 Remove Superfluous `sign_in` From `users_onboarding_spec.rb`
  spec/requests/users_onboarding_spec.rb
Labels: PR: partially-approved

#10544 Allow glitch id starting with ~
  app/liquid_tags/glitch_tag.rb
  spec/liquid_tags/glitch_tag_spec.rb
Labels: PR: partially-approved

#10737 Preparing Crayons to be a gem
  app/assets/stylesheets/base/layout.scss
  app/assets/stylesheets/base/main.scss
  app/assets/stylesheets/scaffolds.scss
  app/views/articles/search.html.erb
  app/views/devise/confirmations/new.html.erb
  app/views/devise/invitations/edit.html.erb
  app/views/listings/edit.html.erb
  app/views/listings/new.html.erb
  app/views/pages/_placeholder.html.erb
  app/views/pages/code_of_conduct.html.erb
  app/views/pages/contact.html.erb
  app/views/pages/information.html.erb
  app/views/pages/markdown_basics.html.erb
  app/views/pages/privacy.html.erb
  app/views/pages/report_abuse.html.erb
  app/views/pages/show.html.erb
  app/views/pages/sponsors.html.erb
  app/views/pages/terms.html.erb
  app/views/users/edit.html.erb
Labels: Crayons, PR: partially-approved, PR: unreviewed

#10631 Profile generalization tidbits
  app/models/profile.rb
  app/models/site_config.rb
  app/services/moderator/banish_user.rb
  app/views/users/_profile.html.erb
  spec/models/site_config_spec.rb
Labels: PR: unreviewed

#10785 Adding role and aria labels to welcome dialog help screen readers
  app/views/onboardings/_task_card.html.erb
Labels: PR: partially-approved

#10782 Fix overflow of indented code-blocks in lists
  app/assets/stylesheets/components/syntax.scss
Labels: PR: reviewed-approved

#10806 Disable flakey Runkit test
  spec/system/articles/user_creates_an_article_spec.rb
Labels: PR: reviewed-approved

#10787 Remove ignored columns from User
  app/models/user.rb
Labels: PR: partially-approved

#10804 Add im-in.space Mastodon instance
  app/lib/constants/mastodon.rb
Labels: PR: partially-approved

#10758 Allow Forem admins to enable an invite only mode.
  app/controllers/admin/configs_controller.rb
  app/helpers/application_helper.rb
  app/javascript/admin/controllers/config_controller.js
  app/lib/constants/site_config.rb
  app/models/site_config.rb
  app/services/authentication/providers.rb
  app/views/admin/configs/show.html.erb
  app/views/articles/_sidebar_additional.html.erb
  app/views/devise/registrations/_registration_form.html.erb
  app/views/devise/shared/_authorization_error.html.erb
  spec/requests/admin/configs_spec.rb
  spec/system/authentication/user_logs_in_with_facebook_spec.rb
  spec/system/authentication/user_logs_in_with_github_spec.rb
  spec/system/authentication/user_logs_in_with_twitter_spec.rb
Labels: PR: partially-approved

#10810 Flaky Spec Fix:Clear Article Content Before Filling In
  spec/system/articles/user_edits_an_article_spec.rb
Labels: PR: reviewed-approved

#10745 [Email/Password Authentication] Allow Admins to enable email/password login
  app/controllers/admin/configs_controller.rb
  app/lib/constants/site_config.rb
  app/models/site_config.rb
  app/views/admin/configs/show.html.erb
  app/views/devise/registrations/_registration_form.html.erb
  app/views/shared/authentication/_email_login_form.html.erb
  spec/fixtures/files/300x100.svg
  spec/requests/editor_spec.rb
  spec/requests/registrations_spec.rb
  spec/system/articles/user_edits_an_article_spec.rb
  spec/system/user_logs_in_with_password_spec.rb
Labels: PR: partially-approved

#10811 Remove code setting SiteConfig values in specs
  spec/requests/admin/configs_spec.rb
  spec/system/authentication/user_logs_in_with_facebook_spec.rb
  spec/system/authentication/user_logs_in_with_github_spec.rb
  spec/system/authentication/user_logs_in_with_twitter_spec.rb
Labels: PR: partially-approved

#10754 Dynamic frontend for the sidebar navigation Items
  app/assets/stylesheets/admin.scss
  app/assets/stylesheets/articles.scss
  app/controllers/admin/navigation_links_controller.rb
  app/models/navigation_link.rb
  app/views/admin/navigation_links/_add_navigation_link_modal.html.erb
  app/views/admin/navigation_links/_edit_navigation_link_modal.html.erb
  app/views/admin/navigation_links/_form.html.erb
  app/views/admin/navigation_links/index.html.erb
  app/views/articles/_sidebar_nav.html.erb
  app/views/articles/_sidebar_nav_link.html.erb
  db/seeds.rb
  lib/tasks/add_navigation_links.rake
  lib/tasks/temporary/add_dev_navigation_links.rake
  spec/factories/navigation_links.rb
  spec/requests/admin/navigation_link_spec.rb
  spec/system/homepage/user_visits_homepage_spec.rb
Labels: PR: partially-approved

#10820 Ensure serviceworker bypass only checks path
  app/views/service_worker/index.js.erb
Labels: PR: partially-approved

#10821 Adding name to core-team per my on-boarding doc
  README.md
Labels: PR: partially-approved

#10822 Add input validation for sidebar tags config
  app/views/admin/configs/show.html.erb
Labels: PR: partially-approved

#10826 SVG logo image re-sizing
  app/assets/stylesheets/components/header.scss
  app/views/admin/configs/show.html.erb
Labels: PR: partially-approved

#10541 Feature:Notify Devs when Sidekiq is Not Running in Development
  app/controllers/application_controller.rb
  app/controllers/concerns/development_dependency_checks.rb
Labels: PR: reviewed-approved

#10818 Feature:Add Video States Encoder Key to SiteConfig
  app/controllers/admin/configs_controller.rb
  app/lib/constants/site_config.rb
  app/models/site_config.rb
  app/views/admin/configs/show.html.erb
  spec/requests/admin/configs_spec.rb
Labels: PR: partially-approved

#10817 Skip edge caching for private forems
  app/controllers/concerns/caching_headers.rb
  spec/requests/stories_index_spec.rb
Labels: PR: partially-approved

#10831 Comment out Flaky Basic Feed Spec
  spec/services/articles/feeds/basic_spec.rb
Labels: PR: reviewed-approved

#10809 Fix missing category in delete draft listing URL
  app/controllers/listings_controller.rb
  spec/requests/listings_spec.rb
Labels: PR: partially-approved

#10756 Refactor carrierwave config
  config/initializers/carrierwave.rb
Labels: PR: reviewed-approved

#10748 Update [authentication] in /admin/config
  app/assets/stylesheets/admin.scss
  app/helpers/application_helper.rb
  app/views/admin/configs/show.html.erb
  app/views/shared/authentication/_providers_registration_form.html.erb
  docs/technical-overview/architecture.md
  docs/technical-overview/compatibility.md
  spec/fixtures/files/300x100.svg
Labels: PR: partially-approved

#10833 Add Specs for Basic Feed Class
  spec/services/articles/feeds/basic_spec.rb
Labels: PR: partially-approved

#10784 add fullscreen to code blocks
  app/assets/images/fullscreen-off.svg
  app/assets/images/fullscreen-on.svg
  app/assets/stylesheets/components/syntax.scss
  app/javascript/packs/articlePage.jsx
  app/javascript/utilities/codeFullscreenModeSwitcher.js
  app/labor/code_block_parser.rb
  app/labor/markdown_parser.rb
  app/views/articles/show.html.erb
  spec/support/fixtures/approvals/user_preview_article_body.approved.html
Labels: PR: partially-approved

#10841 Fix ui for signup with email
  app/views/shared/authentication/_providers_registration_form.html.erb
Labels: PR: partially-approved

#10694 Deprecate old button stylings with Crayons buttons
  app/assets/stylesheets/buttons.scss
  app/assets/stylesheets/comments.scss
  app/assets/stylesheets/dashboard.scss
  app/assets/stylesheets/listings.scss
  app/assets/stylesheets/minimal.scss
  app/assets/stylesheets/podcast-form.scss
  app/assets/stylesheets/settings.scss
  app/assets/stylesheets/widgets.scss
  app/javascript/chat/channelRequest.jsx
  app/javascript/githubRepos/__tests__/singleRepo.test.jsx
  app/javascript/githubRepos/singleRepo.jsx
  app/javascript/listings/__tests__/ListingDashboard.test.jsx
  app/javascript/listings/dashboard/rowElements/actionButtons.jsx
  app/views/admin/articles/rss_articles.html.erb
  app/views/articles/delete_confirm.html.erb
  app/views/articles/edit.html.erb
  app/views/articles/tag_index.html.erb
  app/views/articles/tags/_sidebar.html.erb
  app/views/comments/delete_confirm.html.erb
  app/views/comments/settings.html.erb
  app/views/dashboards/_dashboard_article.html.erb
  app/views/listings/delete_confirm.html.erb
  app/views/moderations/mod.html.erb
  app/views/notifications/_badgeachievement.html.erb
  app/views/notifications/_milestone.html.erb
  app/views/notifications/shared/_comment_box.html.erb
  app/views/podcast_episodes/_liquid.html.erb
  app/views/podcast_episodes/index.html.erb
  app/views/podcast_episodes/show.html.erb
  app/views/podcasts/_form.html.erb
  app/views/users/signout_confirm.html.erb
  spec/requests/notifications_spec.rb
  spec/requests/stories_index_spec.rb
  spec/system/articles/user_deletes_an_article_spec.rb
  spec/system/comments/user_delete_a_comment_spec.rb
  spec/system/notifications/notifications_page_spec.rb
Labels: PR: partially-approved, tech: html/css, type: refactoring

#10819 Default to Imgproxy on Forem-cloud
  app/services/images/optimizer.rb
  app/views/dashboards/show.html.erb
  config/initializers/1_imgproxy.rb
  config/initializers/carrierwave.rb
  lib/data_update_scripts/20201013205258_resave_articles_and_comments_for_imgproxy.rb
  spec/services/images/optimizer_spec.rb
Labels: PR: partially-approved

#10838 Make allow email password login default true
  app/lib/constants/site_config.rb
  app/models/site_config.rb
  spec/requests/registrations_spec.rb
Labels: PR: reviewed-approved

#10540 API - New endpoint to retrieve the articles in the reading list of the authenticated user
  app/controllers/api/v0/articles_controller.rb
  app/controllers/api/v0/readinglist_controller.rb
  app/controllers/api/v0/users_controller.rb
  app/views/api/v0/readinglist/index.json.jbuilder
  config/routes.rb
  docs/api_v0.yml
  spec/requests/api/v0/articles_spec.rb
  spec/requests/api/v0/readinglist_spec.rb
Labels: PR: partially-approved

#10547 Introduce /api/profile_images/:username endpoint
  app/controllers/api/v0/profile_images_controller.rb
  app/views/api/v0/profile_images/show.json.jbuilder
  config/routes.rb
  docs/api_v0.yml
  spec/factories/users.rb
  spec/requests/api/v0/profile_images_spec.rb
Labels: PR: unreviewed

#10840 Logo updates
  app/assets/stylesheets/base/main.scss
  app/assets/stylesheets/components/header.scss
  app/javascript/article-form/articleForm.jsx
  app/javascript/article-form/components/Header.jsx
  app/javascript/packs/articleForm.jsx
  app/views/articles/_v2_form.html.erb
  app/views/layouts/_footer.html.erb
  app/views/layouts/_logo.html.erb
  app/views/layouts/_top_bar.html.erb
  app/views/layouts/admin.html.erb
Labels: PR: partially-approved, action: post deployment

#10851 Optimization:Break up SiteConfig Updates by Groups
  app/views/admin/configs/_form_submission.html.erb
  app/views/admin/configs/show.html.erb
Labels: PR: partially-approved

#10767 Replacing globals with node env
  app/assets/javascripts/.eslintrc.js
  babel.config.js
  bin/generate-css-utility-classes-docs.js
  config/webpack/custom.js
  config/webpack/development.js
  config/webpack/environment.js
  config/webpack/loaders/erb.js
  config/webpack/production.js
  config/webpack/test.js
  jest.config.js
Labels: PR: partially-approved

#10853 Resave users for Imgproxy migration
  lib/data_update_scripts/20201014184856_resave_users_for_imgproxy.rb
Labels: PR: partially-approved

#10857 Fix required button styling in SiteConfig
  app/assets/stylesheets/admin.scss
  app/helpers/application_helper.rb
Labels: PR: partially-approved

#10847 Extracting prettier config
  .prettierrc.json
  app/javascript/.storybook/main.js
  package.json
Labels: PR: reviewed-approved

#10835 Fixed documentation and command for adding credits to a user's account for local development.
  docs/faqs.md
Labels: PR: partially-approved

#10850 Remove hardcoded Dev Community from privacy policy
  app/views/pages/privacy.html.erb
Labels: PR: partially-approved

#10856 Replace deprecated Devise method
  app/views/devise/confirmations/new.html.erb
  app/views/devise/passwords/edit.html.erb
  app/views/devise/passwords/new.html.erb
  app/views/devise/unlocks/new.html.erb
Labels: PR: reviewed-approved

#10528 Remove flare tag from title and hightlight it within the tags row
  app/assets/javascripts/utilities/buildArticleHTML.js
  app/assets/stylesheets/components/stories.scss
  app/javascript/articles/Article.jsx
  app/javascript/articles/__tests__/__snapshots__/Article.test.jsx.snap
  app/javascript/articles/components/ContentTitle.jsx
  app/javascript/articles/components/TagList.jsx
  app/views/articles/_single_story.html.erb
Labels: PR: partially-approved

#9466 Chat ui bug fix
  app/assets/stylesheets/chat.scss
  bin/__tests__/generate-css-utility-classes-docs.test.js
  bin/generate-css-utility-classes-docs.js
  package.json
Labels: PR: partially-approved

#10824 fix request center UI
  app/assets/stylesheets/chat.scss
  app/javascript/chat/RequestManager/RequestManager.jsx
  app/javascript/chat/channelRequest.jsx
Labels: PR: partially-approved

#10837 Begin cleaning up and generalizing events
  app/assets/images/sustaining-membership.svg
  app/views/events/index.html.erb
Labels: PR: partially-approved

#10848 Refactor/Feature:Use SiteConfig video_encoder_key For Processing Videos
  app/controllers/video_states_controller.rb
  spec/requests/video_states_update_spec.rb
Labels: PR: reviewed-approved

#10852 Ignore /images in service_worker
  app/views/service_worker/index.js.erb
Labels: PR: partially-approved

#10816 Centralize on "trusted" language: Add new copy and some slight feature adjustments.
  app/queries/admin/moderators_query.rb
  app/views/admin/mods/index.html.erb
  app/views/mailers/notify_mailer/trusted_role_email.html.erb
  app/views/mailers/notify_mailer/trusted_role_email.text.erb
  spec/queries/admin/moderators_query_spec.rb
Labels: PR: partially-approved

#10866 Optimization/Flaky Fix:Combine Spec Assertions and Use Timecop for Datetime Assertion
  spec/system/user/view_user_index_spec.rb
Labels: PR: partially-approved

#10859 Move settings tabs to constant
  app/controllers/organizations_controller.rb
  app/controllers/users_controller.rb
  app/lib/constants/settings.rb
  app/models/user.rb
  app/views/users/edit.html.erb
  spec/views/users/settings_spec.rb
Labels: PR: partially-approved

#10864 replace Envfile with env_sample and reference env file in auth docs
  docs/backend/auth-facebook.md
  docs/backend/auth-github.md
  docs/backend/auth-twitter.md
  docs/getting-started/config-env.md
  docs/installation/containers.md
  docs/installation/linux.md
  docs/installation/mac.md
  docs/installation/windows.md
Labels: PR: reviewed-approved

#10854 System test
  spec/system/authentication/user_logs_in_with_email_spec.rb
Labels: PR: partially-approved

#10875 User color fields in admin
  app/views/admin/configs/show.html.erb
  app/views/admin/tags/show.html.erb
Labels: PR: partially-approved

#10812 Allow all third party auth providers to be deactivated
  app/controllers/admin/configs_controller.rb
  spec/requests/admin/configs_spec.rb
Labels: PR: unreviewed, area: admin

#10877 Allow admins to turn "some" hardcoded pages into a "Page"
  app/controllers/admin/pages_controller.rb
  app/controllers/pages_controller.rb
  app/views/admin/pages/index.html.erb
  app/views/pages/_privacy_text.html.erb
  app/views/pages/privacy.html.erb
  app/views/pages/terms.html.erb
  spec/system/admin/admin_creates_new_page.rb
  spec/system/admin/admin_manages_pages_spec.rb
Labels: PR: partially-approved

#10881 Update feed docs
  docs/technical-overview/feed.md
Labels: PR: partially-approved

#10861 Add rails dbconsole
  docs/faqs.md
Labels: PR: reviewed-approved

#10844 Make feed_url nullable in RssReader
  app/services/rss_reader/assembler.rb
Labels: PR: partially-approved

#10870 Adds a new admin setting for experience levels.
  app/controllers/admin/configs_controller.rb
  app/controllers/organizations_controller.rb
  app/lib/constants/site_config.rb
  app/models/site_config.rb
  app/views/admin/configs/show.html.erb
  app/views/articles/manage.html.erb
  app/views/events/index.html.erb
  app/views/mailers/notify_mailer/trusted_role_email.html.erb
  app/views/users/_ux.html.erb
  docs/backend/auth-facebook.md
  docs/backend/auth-github.md
  docs/backend/auth-twitter.md
  docs/installation/containers.md
  docs/installation/linux.md
  docs/installation/mac.md
  docs/installation/windows.md
  spec/requests/admin/configs_spec.rb
Labels: PR: partially-approved, action: post deployment

#10867 Store Article's main_image path unprocessed
  app/controllers/image_uploads_controller.rb
  app/javascript/article-form/actions.js
  app/javascript/article-form/components/ArticleCoverImage.jsx
  lib/data_update_scripts/20201015190914_update_article_main_image_path.rb
  spec/lib/data_update_scripts/update_article_main_image_path_spec.rb
Labels: PR: reviewed-approved

#10788 new liquid tag - dotnetfiddle
  app/liquid_tags/dotnet_fiddle_tag.rb
  app/views/liquids/_dotnetfiddle.html.erb
  app/views/pages/_editor_liquid_help.html.erb
  docs/frontend/liquid-tags.md
  spec/liquid_tags/dotnet_fiddle_tag_spec.rb
  spec/support/fixtures/approvals/dotnetfiddle_liquid_tag.approved.html
Labels: PR: partially-approved

#10885 Revert "Allow all third party auth providers to be deactivated"
  app/controllers/admin/configs_controller.rb
  spec/requests/admin/configs_spec.rb
Labels: PR: partially-approved, area: admin

#10916 Allow admins to change user email to fix email edge cases
  app/controllers/resource_admin/users_controller.rb
  app/dashboards/user_dashboard.rb
Labels: PR: unreviewed

#10755 fix bug on chat input
  app/javascript/chat/__tests__/compose.test.jsx
  app/javascript/chat/compose.jsx
Labels: PR: reviewed-approved

#9799 Added the <ConnectStateProvider />
  app/javascript/chat/components/ConnectStateProvider.jsx
  app/javascript/chat/components/__tests__/ConnectStateProvider.test.jsx
Labels: PR: partially-approved, area: connect, area: frontend infrastructure, javascript

#10923 Added back overflow-y scroll to allow users to scroll through chat messages.
  app/assets/stylesheets/chat.scss
Labels: PR: reviewed-approved

#10919 Uncheck email preferences by default
  app/javascript/onboarding/components/EmailPreferencesForm.jsx
  app/javascript/onboarding/components/__tests__/EmailPreferencesForm.test.jsx
  db/migrate/20201019012200_change_email_preference_default_values.rb
  db/schema.rb
  spec/factories/users.rb
  spec/labor/mailchimp_bot_spec.rb
  spec/requests/incoming_webhooks/mailchimp/unsubscribe_spec.rb
Labels: PR: partially-approved

#10891 Flaky Spec Fix:Set TimeZone For All Spec Requests to Match Zonebie
  app/lib/middleware/time_zone_setter.rb
  config/environments/test.rb
  spec/rails_helper.rb
Labels: PR: unreviewed

#10921 Make the footer links dynamic
  app/assets/stylesheets/views/footer.scss
  app/views/articles/_sidebar_nav.html.erb
  app/views/layouts/_footer.html.erb
  spec/requests/stories_index_spec.rb
Labels: PR: partially-approved

#10930 Flaky Spec Fix:Don't Hard Code Comment Date
  spec/system/comments/user_views_a_comment_spec.rb
Labels: PR: reviewed-approved

#10929 Disable logo resizing on small resolutions
  app/assets/stylesheets/base/main.scss
Labels: PR: partially-approved, tech: html/css

#10926 Adding admin link for admins
  app/assets/javascripts/initializers/initializeBaseUserData.js
  app/controllers/async_info_controller.rb
  app/views/layouts/_nav_menu.html.erb
Labels: PR: partially-approved

#10932 Revert "Fix reading list counter"
  app/controllers/async_info_controller.rb
  app/controllers/reading_list_items_controller.rb
  app/models/user.rb
  db/migrate/20201017160628_add_last_reacted_at_to_user.rb
  db/schema.rb
  spec/requests/reading_list_items_spec.rb
Labels: PR: reviewed-approved

#10933 Fix Reading List Counter Without last_reacted_at Default
  app/controllers/async_info_controller.rb
  app/controllers/reading_list_items_controller.rb
  app/models/user.rb
  db/migrate/20201017160628_add_last_reacted_at_to_user.rb
  db/schema.rb
  spec/requests/reading_list_items_spec.rb
Labels: PR: reviewed-approved

#10936 Flaky Spec Fixes:Correctly Assert Dates in Views
  spec/system/articles/user_visits_an_article_spec.rb
  spec/system/comments/user_views_a_comment_spec.rb
  spec/system/homepage/user_visits_homepage_articles_spec.rb
Labels: PR: reviewed-approved

#10886 Fix weird highlighting bug
  app/views/admin/shared/_navbar.html.erb
Labels: PR: reviewed-approved

#10924 Allow the Pages contact page to override the hardcoded one
  app/controllers/pages_controller.rb
  spec/requests/pages_spec.rb
Labels: PR: partially-approved

#10846 [Team Email Login] Admin enable/disable recaptcha during email signup
  app/controllers/admin/configs_controller.rb
  app/controllers/registrations_controller.rb
  app/helpers/authentication_helper.rb
  app/javascript/admin/controllers/config_controller.js
  app/lib/constants/site_config.rb
  app/models/site_config.rb
  app/views/admin/configs/show.html.erb
  app/views/shared/authentication/_email_registration_form.html.erb
  spec/helpers/authentication_helper_spec.rb
  spec/requests/registrations_spec.rb
Labels: PR: partially-approved

#10934 Add invitations controller to Allow List
  app/controllers/application_controller.rb
  spec/requests/invitations_spec.rb
Labels: PR: partially-approved
