Repository forem/forem, pull requests merged in 2020-11, with the labels that each got.

#11225 Spec Fix:Remove Extra Space From Single Number Dates in Spec
  spec/system/articles/user_visits_an_article_spec.rb
Labels: PR: reviewed-approved, merge by any core

#11149 Add feature flag for profile admin section
  app/controllers/admin/application_controller.rb
  app/helpers/admin_helper.rb
  app/views/admin/admin_portals/index.html.erb
  app/views/admin/shared/_navbar.html.erb
  config/routes.rb
  spec/models/profile_field_group_spec.rb
  spec/requests/admin/admin_portals_spec.rb
  spec/requests/admin/profile_field_groups_spec.rb
  spec/requests/admin/profile_fields_spec.rb
  spec/requests/admin/sidebar_spec.rb
  spec/routing/profile_admin_routes_spec.rb
Labels: PR: partially-approved, merge by any core

#10890 Add mailer previews for Devise mailer
  spec/mailers/previews/devise/mailer_preview.rb
  spec/mailers/previews/devise_invitable/mailer_preview.rb
Labels: PR: partially-approved

#11224 fix for code fullscreen action on comment page
  app/javascript/packs/fullScreenModeControl.js
  app/views/comments/index.html.erb
Labels: PR: partially-approved

#11229 Z-index fix
  app/assets/stylesheets/articles.scss
Labels: PR: partially-approved, tech: html/css

#11200 Optimization:Speed Up Notifications Spec By Combining Assertions
  docs/tests/acceptance-tests.md
  spec/requests/notifications_spec.rb
Labels: PR: unreviewed, merge by any core

#11198 Refactor:Always Load Last 24 Hour Podcasts
  app/controllers/stories_controller.rb
Labels: PR: partially-approved

#11045 Copy username to search_fields
  config/elasticsearch/mappings/users.json
  lib/data_update_scripts/20200914042434_reindex_users_for_profiles.rb
  lib/data_update_scripts/20201030134117_reindex_users_for_username_search.rb
  spec/lib/data_update_scripts/reindex_users_for_username_search_spec.rb
  spec/services/search/user_spec.rb
Labels: PR: partially-approved

#11186 Remove social icons from comment liquid tag
  app/views/comments/_liquid.html.erb
Labels: PR: partially-approved

#11226 Remove unused method
  app/models/feedback_message.rb
Labels: PR: partially-approved

#10517 Added form fields for the admin podcasts dashboard.
  app/controllers/admin/podcasts_controller.rb
  app/views/admin/podcasts/edit.html.erb
  spec/requests/admin/podcasts_spec.rb
Labels: PR: partially-approved

#11197 Refactor:Show Same Number of Articles for all Envs
  app/controllers/stories_controller.rb
  spec/requests/stories_index_spec.rb
Labels: PR: partially-approved

#11117 Remove the hardcoded /future redirect + add the redirect back to only Forem as a pre/post deployment task
  app/views/service_worker/index.js.erb
  config/routes.rb
Labels: PR: partially-approved

#11196 Update comments label in widget
  app/views/articles/_widget_list_item.html.erb
Labels: PR: partially-approved

#11105 Adds a Default Color Hex Value to the Admin Tags Color Field
  app/views/admin/tags/show.html.erb
  spec/system/admin/admin_creates_new_page_spec.rb
  spec/system/admin/admin_updates_tag_spec.rb
Labels: PR: unreviewed

#11187 Filter by a few other roles when adding potential mods
  app/queries/admin/moderators_query.rb
Labels: PR: partially-approved

#11054 Render followed tags only if container available
  app/javascript/packs/homePage.jsx
Labels: PR: partially-approved

#11227 Fix Bug: Series index page showing series with 0 articles -#9658
  app/controllers/collections_controller.rb
  spec/system/collections/user_views_collections_spec.rb
Labels: PR: reviewed-approved

#11248 Z-index fix
  app/assets/stylesheets/components/header.scss
Labels: PR: partially-approved, tech: html/css

#11234 Add users param to Feeds::Import
  app/models/user.rb
  app/services/feeds/import.rb
  app/workers/articles/dev_feeds_import_worker.rb
  spec/fixtures/approvals/feeds_import/call/with_an_explicit_set_of_users/accepts_a_subset_of_users.approved.txt
  spec/fixtures/approvals/feeds_import/call/with_an_explicit_set_of_users/imports_no_articles_if_given_users_are_without_feed.approved.txt
  spec/services/feeds/import_spec.rb
  spec/workers/articles/dev_feeds_import_worker_spec.rb
Labels: PR: unreviewed

#11244 UX Settings: wrap radio button group in a fieldset
  app/views/users/_ux.html.erb
Labels: PR: partially-approved, accessibility

#11238 Replace SimpleIDN usage with Addressable
  Gemfile
  Gemfile.lock
  app/helpers/application_helper.rb
  spec/helpers/application_helper_spec.rb
  vendor/cache/simpleidn-0.1.1.gem
Labels: PR: reviewed-approved

#11250 Settings UI fix
  app/assets/stylesheets/theme-selector.scss
  app/views/users/_experience_selector.html.erb
  app/views/users/_ux.html.erb
  app/views/users/edit.html.erb
Labels: PR: partially-approved

#11233 Refactor:Implement Carrierwave Monkeypatch in all Envs
  config/initializers/carrierwave_monkeypatch.rb
  spec/initializers/carrierwave_monkeypatch_spec.rb
Labels: PR: partially-approved

#11254 Add expectation to ensure on edit comment page
  spec/system/comments/user_edits_a_comment_spec.rb
Labels: PR: reviewed-approved

#11251 Fixing tags in listing modal
  app/javascript/listings/singleListing/Header.jsx
Labels: PR: partially-approved

#11253 Improve Containerfile CMD readability
  Containerfile
Labels: PR: reviewed-approved

#11245 Add --spec option for data_update generator
  docs/backend/data-update-scripts.md
  lib/generators/data_update/data_update_generator.rb
  lib/generators/data_update/templates/data_update_spec.rb.tt
Labels: PR: partially-approved

#11102 Rate Limit Modal - Comments
  app/assets/javascripts/initializers/initializeCommentsPage.js.erb
  app/assets/javascripts/utilities/showUserAlertModal.js
  spec/system/comments/user_fills_out_comment_spec.rb
Labels: PR: unreviewed

#11169 [Front-End Q/A] Config Authentication view
  app/assets/stylesheets/admin.scss
  app/assets/stylesheets/components/forms.scss
  app/javascript/admin/adminModal.js
  app/javascript/admin/controllers/config_controller.js
  app/lib/constants/site_config.rb
  app/views/admin/configs/show.html.erb
Labels: PR: unreviewed, area: admin, tech: html/css

#11255 Clean up Gitpod Dockerfile Elasticsearch tarball
  .gitpod.dockerfile
Labels: PR: reviewed-approved

#11257 Update organization <select> to use Crayons
  app/views/users/edit.html.erb
Labels: PR: partially-approved

#11272 Fix rails db:seed error
  db/seeds.rb
Labels: PR: partially-approved

#11049 List single_resource_admin resources in the UI
  app/models/role.rb
  app/views/admin/users/_activity.html.erb
Labels: PR: partially-approved

#11199 [Crayons] Update comments card in Profile
  app/assets/stylesheets/index-comments.scss
  app/assets/stylesheets/minimal.scss
  app/assets/stylesheets/views/profile.scss
  app/views/users/_comments_section.html.erb
  spec/system/user/view_user_comments_spec.rb
  spec/system/user/view_user_index_spec.rb
Labels: Crayons, PR: partially-approved, PR: reviewed-changes-requested, PR: unreviewed, tech: html/css

#11259 Conditionally hide onboarding task card
  app/views/articles/index.html.erb
  app/views/onboardings/_task_card.html.erb
  spec/liquid_tags/user_subscription_tag_spec.rb
  spec/system/authentication/redirects_using_referer_spec.rb
  spec/system/authentication/user_logs_in_with_email_spec.rb
  spec/system/onboardings/user_completes_onboarding_spec.rb
  spec/system/user/user_edits_integrations_spec.rb
  spec/system/user/user_edits_profile_spec.rb
  spec/system/user/user_edits_ux_spec.rb
  spec/system/user/user_self_destroy_spec.rb
Labels: PR: unreviewed

#11258 Deploy In Parallel to Heroku Apps
  .travis.yml
Labels: PR: partially-approved

#11277 Comment out Flaky Onboarding spec
  spec/system/onboardings/user_completes_onboarding_spec.rb
Labels: PR: unreviewed

#9847 🚀 Feature: Give Tab Notification on New Message
  app/javascript/chat/chat.jsx
  app/javascript/utilities/connect/newMessageNotify.js
Labels: PR: partially-approved

#11275 Revert "Deploy In Parallel to Heroku Apps"
  .travis.yml
Labels: PR: partially-approved

#11262 Data update script generator: Use full path instead of filename for require
  docs/backend/data-update-scripts.md
  lib/generators/data_update/data_update_generator.rb
  lib/generators/data_update/templates/data_update_spec.rb.tt
Labels: PR: partially-approved

#11260 Fixing date in listing modal
  app/controllers/listings_controller.rb
  spec/requests/listings_spec.rb
Labels: PR: partially-approved

#11263 Refactor DataUpdateScript to make its code simpler
  app/models/data_update_script.rb
Labels: PR: reviewed-approved

#11267 Another tooltips fix: pointer-events
  app/assets/stylesheets/components/tooltips.scss
Labels: Crayons, PR: partially-approved, PR: reviewed-approved, PR: unreviewed

#11249 Comments inside article
  app/views/articles/_about_author.html.erb
  app/views/articles/_bottom_content.html.erb
  app/views/articles/_full_comment_area.html.erb
  app/views/articles/_org_branding.html.erb
  app/views/articles/_sticky_nav.html.erb
  app/views/articles/show.html.erb
Labels: Crayons, PR: partially-approved, PR: unreviewed, area: articles

#11274 Docs: Fix docker-compose instructions
  docs/getting-started/pull-request.md
  docs/installation/containers.md
Labels: PR: partially-approved

#11192 11163 - documentation - installation/containers
  docs/installation/containers.md
Labels: PR: partially-approved

#11221 Fixing flag user modal
  app/javascript/actionsPanel/actionsPanel.js
  app/javascript/modCenter/singleArticle/index.jsx
  app/javascript/packs/flagUserModal.jsx
Labels: PR: partially-approved

#10594 Update to Ruby 2.7.2
  .github/workflows/dependabot.yml
  .gitpod.dockerfile
  .ruby-version
  .travis.yml
  Containerfile
  Gemfile.lock
  config/environments/development.rb
  config/environments/test.rb
  docs/.ruby-version
Labels: PR: reviewed-approved, merge by any core

#11242 Add trusted role to new tag moderators
  app/controllers/admin/tags/moderators_controller.rb
  app/controllers/admin/tags_controller.rb
  app/labor/assign_tag_moderator.rb
  app/models/tag.rb
  app/views/admin/tags/_form.html.erb
  app/views/admin/tags/show.html.erb
  config/routes.rb
  spec/requests/admin/tags/moderators_spec.rb
  spec/requests/admin/tags_spec.rb
Labels: PR: partially-approved

#11278 Refactor:Enable Datadog When DD_API_KEY is Present
  config/initializers/datadog_apm.rb
Labels: PR: reviewed-approved

#11276 Wrap siteconfig images in optimizer
  app/views/admin/configs/show.html.erb
  app/views/comments/_form.html.erb
  app/views/layouts/_footer.html.erb
  app/views/layouts/admin.html.erb
  app/views/shell/_top.html.erb
Labels: PR: reviewed-approved

#11288 Makes Runtime.js detect the generalized ForemWebView User Agent
  app/assets/javascripts/initializers/runtime.js
  spec/system/podcasts/user_visits_podcast_episode_spec.rb
Labels: PR: partially-approved

#11296 Fix hidden progress bar
  app/assets/stylesheets/components/header.scss
Labels: PR: reviewed-approved

#11289 Use OPENRESTY_URL over protocol + domain
  .env_sample
  app/services/edge_cache/bust.rb
  app/services/edge_cache/bust/nginx.rb
  spec/services/edge_cache/bust_spec.rb
Labels: PR: partially-approved

#11301 Fixing missing category in listing modal
  app/controllers/listings_controller.rb
  spec/requests/listings_spec.rb
Labels: PR: reviewed-approved

#11294 Render op markers for coauthors
  app/helpers/comments_helper.rb
  spec/factories/articles.rb
  spec/system/user_visits_a_comments_page_spec.rb
Labels: PR: partially-approved

#11286 Update page views counters a little bit more often
  app/controllers/page_views_controller.rb
Labels: PR: partially-approved

#11185 [Team Email Login] Refactor Authentication Provider Enable/Disable
  app/assets/javascripts/utilities/showUserAlertModal.js
  app/assets/stylesheets/admin.scss
  app/controllers/admin/configs_controller.rb
  app/helpers/authentication_helper.rb
  app/javascript/admin/adminModal.js
  app/javascript/admin/controllers/config_controller.js
  app/views/admin/configs/_auth_provider_settings.html.erb
  app/views/admin/configs/show.html.erb
  spec/helpers/authentication_helper_spec.rb
  spec/requests/admin/configs_spec.rb
  spec/requests/admin/podcasts_spec.rb
  spec/system/comments/user_fills_out_comment_spec.rb
Labels: PR: unreviewed

#11303 [Team Email Login] Make final Auth Provider Refactor code changes
  app/assets/stylesheets/admin.scss
  app/javascript/admin/controllers/config_controller.js
  app/views/admin/configs/show.html.erb
Labels: PR: reviewed-approved

#11246 Prepare for profile column drop
  app/models/profile_field.rb
  app/services/profile_fields/field_definition.rb
  app/services/profile_fields/import_from_csv.rb
  lib/data/dev_profile_fields.csv
  lib/data_update_scripts/20201103050112_prepare_for_profile_column_drop.rb
  lib/tasks/forem.rake
  spec/fixtures/files/profile_fields.csv
  spec/lib/data_update_scripts/prepare_for_profile_column_drop_spec.rb
Labels: PR: reviewed-approved

#11040 Return video_source_url in API V0 Videos index (#6299)
  app/controllers/api/v0/videos_controller.rb
  app/views/api/v0/videos/index.json.jbuilder
  docs/api_v0.yml
  spec/requests/api/v0/videos_spec.rb
Labels: PR: partially-approved

#11341 Comment Out Flaky Onboarding Spec
  spec/system/onboardings/user_completes_onboarding_spec.rb
Labels: PR: partially-approved

#11336 Move TimeZoneSetter middleware in proper place
  app/lib/middleware/time_zone_setter.rb
  app/middlewares/set_time_zone.rb
  config/environments/test.rb
Labels: PR: partially-approved

#11297 Add custom instrumentation to Feeds::Import
  app/services/feeds/import.rb
Labels: PR: reviewed-approved

#11340 Refactor:Remove more_experience_level_weight_experiment From Feed Tests
  app/controllers/stories/feeds_controller.rb
  app/services/articles/feeds/large_forem_experimental.rb
  config/field_test.yml
  spec/services/articles/feeds/large_forem_experimental_spec.rb
Labels: PR: partially-approved

#11343 Update shell version when admin action taken
  app/controllers/admin/application_controller.rb
  app/controllers/async_info_controller.rb
  app/views/shell/_top.html.erb
Labels: PR: unreviewed

#11331 Correctly set constant in including modules
  app/models/concerns/acts_as_profile_field.rb
Labels: PR: reviewed-approved

#11265 Add service generator
  config/initializers/zeitwerk.rb
  docs/backend/readme.md
  docs/backend/service-objects.md
  lib/generators/service/USAGE
  lib/generators/service/service_generator.rb
  lib/generators/service/templates/service.erb
  lib/generators/service/templates/service_spec.erb
  spec/generator/services_generator_spec.rb
Labels: PR: unreviewed

#11256 Show canonical URL on article even after it has been updated
  app/views/articles/show.html.erb
  spec/views/articles_spec.rb
Labels: PR: partially-approved

#11345 Podcast + Video player native bridge small refactor
  app/assets/javascripts/initializers/initializePodcastPlayback.js
  app/assets/javascripts/initializers/initializeVideoPlayback.js
Labels: PR: partially-approved

#11113 Add chaining to shortcuts
  app/javascript/shared/components/__tests__/useKeyboardShortcuts.test.jsx
  app/javascript/shared/components/useKeyboardShortcuts.js
  app/javascript/shared/components/useKeyboardShortcuts.jsx
Labels: PR: unreviewed

#11348 Update to NodeJS 14.14.x to match with Fedora 33's installed version.
  .gitpod.dockerfile
  .nvmrc
  package.json
Labels: PR: reviewed-approved

#11355 Add "andygeorge" to Core team list
  README.md
Labels: PR: partially-approved

#11342 Update styles for Auth Providers in admin/config
  app/assets/stylesheets/admin.scss
  app/views/admin/configs/_auth_provider_settings.html.erb
  app/views/admin/configs/show.html.erb
Labels: PR: partially-approved

#11359 Flip values of email digest min/max
  app/models/site_config.rb
Labels: PR: reviewed-approved

#11360 Fix typo in placeholder anti-spam terms
  app/lib/constants/site_config.rb
Labels: PR: reviewed-approved

#11356 Refactor:Remove Duplicate from Onboarding Specs
  spec/system/onboardings/user_completes_onboarding_spec.rb
Labels: PR: reviewed-approved

#11252 Replace old assets with new ones if cached page mismatch
  app/views/layouts/_asset_reconciliation.html.erb
  app/views/layouts/_styles.html.erb
  app/views/layouts/application.html.erb
  app/views/shell/_top.html.erb
  spec/requests/stories_index_spec.rb
Labels: PR: unreviewed

#11368 Change from stylesheet_url to stylesheet_path
  app/views/layouts/_asset_reconciliation.html.erb
Labels: PR: unreviewed

#11363 Set default timeout to 0 ms for keyboard shortcuts.
  app/javascript/shared/components/useKeyboardShortcuts.js
Labels: PR: unreviewed

#10468 A11y: Add keyboard navigation to article feed
  app/assets/javascripts/utilities/buildArticleHTML.js
  app/assets/stylesheets/components/stories.scss
  app/javascript/Search/Search.jsx
  app/javascript/Search/__tests__/Search.test.jsx
  app/javascript/articles/Article.jsx
  app/javascript/articles/Feed.jsx
  app/javascript/articles/__tests__/__snapshots__/Article.test.jsx.snap
  app/javascript/packs/homePageFeedShortcuts.jsx
  app/javascript/shared/components/__tests__/useListNavigation.test.js
  app/javascript/shared/components/useListNavigation.js
  app/javascript/utilities/viewport.js
  app/views/articles/_single_story.html.erb
Labels: PR: partially-approved, accessibility

#11367 Use crayons buttons in card headers
  app/views/admin/configs/show.html.erb
  app/views/admin/profile_fields/_grouped_profile_fields.html.erb
  app/views/admin/profile_fields/_ungrouped_profile_fields.html.erb
  app/views/admin/shared/_card_header.html.erb
Labels: PR: reviewed-approved

#8311 Added Copy Permalink Functionality to Comment Dropdown
  app/assets/javascripts/initializers/initializeCommentDropdown.js
  app/assets/javascripts/utilities/buildCommentHTML.js.erb
  app/views/comments/_comment_proper.html.erb
Labels: PR: unreviewed

#11375 Comment out Still Flaky Onboarding spec
  spec/system/onboardings/user_completes_onboarding_spec.rb
Labels: PR: reviewed-approved

#11378 Parralelize Travis deploy
  .travis.yml
Labels: PR: partially-approved

#11369 Bust caches at different intervals on restart
  lib/tasks/cache.rake
Labels: PR: reviewed-approved

#11366 Add admin guide to "added to docs?" section of PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: PR: reviewed-approved

#11338 Adding select option to storybook
  app/javascript/crayons/Select/__stories__/Select.stories.jsx
Labels: PR: partially-approved

#11370 Move ArticleSuggester to Articles::Suggest service
  app/labor/article_suggester.rb
  app/services/articles/suggest.rb
  app/views/articles/show.html.erb
  spec/services/articles/suggest_spec.rb
Labels: PR: reviewed-approved

#11382 Some refactoring around fact that Email Login is now always on
  app/controllers/admin/configs_controller.rb
  app/helpers/authentication_helper.rb
  app/javascript/admin/controllers/config_controller.js
  app/views/admin/configs/_auth_provider_settings.html.erb
  app/views/admin/configs/show.html.erb
  spec/helpers/authentication_helper_spec.rb
  spec/requests/admin/configs_spec.rb
Labels: PR: reviewed-approved

#11344 Update rate limit modal
  app/assets/javascripts/utilities/showUserAlertModal.js.erb
  app/models/site_config.rb
  spec/system/comments/user_fills_out_comment_spec.rb
Labels: PR: partially-approved

#11364 Convert inline JS to Stimulus
  app/javascript/admin/controllers/modal_controller.js
  app/views/admin/profile_fields/_add_group_modal.html.erb
  app/views/admin/profile_fields/_add_profile_field_modal.html.erb
  app/views/admin/profile_fields/_edit_group_modal.html.erb
  app/views/admin/profile_fields/_grouped_profile_fields.html.erb
Labels: PR: partially-approved

#11357 Profile UI update
  app/assets/images/pin.svg
  app/assets/images/post.svg
  app/assets/images/tag.svg
  app/assets/javascripts/initializePage.js
  app/assets/javascripts/initializers/initializeUserProfilePage.js
  app/assets/stylesheets/articles.scss
  app/assets/stylesheets/base/layout.scss
  app/views/articles/_badges_area.html.erb
  app/views/users/_comments_section.html.erb
  app/views/users/_github_repositories_area.html.erb
  app/views/users/_main_feed.html.erb
  app/views/users/_organizations_area.html.erb
  app/views/users/_sidebar.html.erb
  app/views/users/_sidebar_additional.html.erb
  app/views/users/show.html.erb
  spec/system/user/view_user_index_spec.rb
Labels: Crayons, PR: partially-approved, PR: unreviewed, area: profile

#11386 Replace calls to Flipper with FeatureFlag
  app/helpers/admin_helper.rb
  app/helpers/authentication_helper.rb
  app/services/feature_flag.rb
  config/routes.rb
  spec/models/profile_field_group_spec.rb
  spec/requests/admin/admin_portals_spec.rb
  spec/requests/admin/profile_field_groups_spec.rb
  spec/requests/admin/profile_fields_spec.rb
  spec/requests/admin/sidebar_spec.rb
  spec/requests/registrations_spec.rb
  spec/routing/profile_admin_routes_spec.rb
  spec/services/feature_flag_spec.rb
Labels: PR: partially-approved

#11388 Hotfix: Remove mascot from JS template for modals
  app/assets/javascripts/utilities/showUserAlertModal.js
Labels: PR: partially-approved

#11377 feat: Preload links on focus
  app/assets/javascripts/base.js.erb
Labels: PR: partially-approved

#11389 Profile image loading glitch fix
  app/views/articles/_sidebar_nav.html.erb
Labels: PR: partially-approved

#11384 Badges area on profile
  app/assets/javascripts/initializePage.js
  app/assets/javascripts/initializers/initializeUserProfilePage.js
  app/controllers/stories_controller.rb
  app/views/articles/_badges_area.html.erb
Labels: PR: partially-approved, area: profile

#11373 Remove information route and add a temporary redirect to /about for SEO purposes
  app/views/layouts/_nav_menu.html.erb
  app/views/pages/information.html.erb
  config/routes.rb
Labels: PR: partially-approved, merge by any core

#11307 Email login always on
  app/controllers/admin/configs_controller.rb
  app/helpers/authentication_helper.rb
  app/javascript/admin/controllers/config_controller.js
  app/models/site_config.rb
  app/views/admin/configs/_auth_provider_settings.html.erb
  app/views/admin/configs/show.html.erb
  spec/helpers/authentication_helper_spec.rb
  spec/requests/admin/configs_spec.rb
Labels: PR: partially-approved

#11376 Bug Fix:Remove Deprecated SENDGRID_USERNAME and SENDGRID_PASSWORD from production.rb
  config/environments/production.rb
Labels: PR: partially-approved

#11096 Refactor:Replace Production Check with Average Metrics
  app/services/suggester/users/recent.rb
  spec/services/suggester/users/recent_spec.rb
Labels: PR: partially-approved

#11391 Bumped jest test coverage thresholds.
  jest.config.js
Labels: PR: partially-approved, area: frontend infrastructure, merge by any core

#11237 Developer experience/security: Make dev/test blow up if current_user is used erroneously
  Gemfile
  Gemfile.lock
  app/assets/javascripts/initializers/initializeBaseUserData.js
  app/controllers/application_controller.rb
  app/controllers/concerns/caching_headers.rb
  app/controllers/concerns/edge_cache_safety_check.rb
  app/views/articles/_sidebar.html.erb
  app/views/articles/_sidebar_nav.html.erb
  app/views/articles/index.html.erb
  app/views/articles/show.html.erb
  spec/system/articles/user_visits_an_article_spec.rb
  spec/system/homepage/user_visits_homepage_spec.rb
Labels: PR: unreviewed, merge by any core

#11381 Feature:Send Alerts for Failed DataUpdateScripts to Datadog
  app/workers/metrics/check_data_update_script_statuses.rb
  config/schedule.yml
  spec/factories/data_update_script.rb
  spec/workers/metrics/check_data_update_script_statuses_spec.rb
Labels: PR: partially-approved

#11299 Validate Image URLs in SiteConfig
  app/controllers/admin/configs_controller.rb
  spec/requests/admin/configs_spec.rb
Labels: PR: partially-approved

#11337 Footer UI update
  app/assets/images/logo-forem.svg
  app/assets/stylesheets/base/main.scss
  app/assets/stylesheets/config/_colors.scss
  app/assets/stylesheets/views/footer.scss
  app/views/layouts/_footer.html.erb
Labels: PR: partially-approved, merge by any core, tech: html/css

#11380 Auto generate mascot accounts
  app/controllers/concerns/verify_setup_completed.rb
  app/controllers/registrations_controller.rb
  app/models/site_config.rb
  app/services/users/create_mascot_account.rb
  spec/models/reaction_spec.rb
  spec/requests/registrations_spec.rb
  spec/services/search/query_builders/chat_channel_membership_spec.rb
  spec/services/users/create_mascot_account_spec.rb
Labels: PR: partially-approved

#11400 Move badges_area template in proper place and refactor the partial
  app/models/badge_achievement.rb
  app/views/articles/_badges_area.html.erb
  app/views/users/_badges_area.html.erb
  app/views/users/_sidebar.html.erb
  config/routes.rb
  spec/system/admin/admin_awards_badges_spec.rb
Labels: PR: partially-approved

#11362 Simplify admin config permissions and add links to help pages
  app/assets/images/circle-question.svg
  app/assets/stylesheets/admin.scss
  app/controllers/admin/application_controller.rb
  app/controllers/admin/configs_controller.rb
  app/views/admin/configs/show.html.erb
  app/views/layouts/admin.html.erb
  spec/requests/admin/configs_spec.rb
Labels: PR: partially-approved, merge by any core

#11394 Filter by tags of reading list items not tags you follow
  app/javascript/packs/readingList.jsx
  app/javascript/readingList/readingList.jsx
  app/javascript/searchableItemList/searchableItemList.js
Labels: PR: partially-approved

#11399 Use Rails path helpers in admin system specs
  spec/system/admin/admin_awards_badges_spec.rb
  spec/system/admin/admin_bans_or_warns_user_spec.rb
  spec/system/admin/admin_creates_new_event_spec.rb
  spec/system/admin/admin_deletes_user_spec.rb
  spec/system/admin/admin_updates_tag_spec.rb
Labels: PR: reviewed-approved

#11398 Add system spec for profile fields
  app/services/feature_flag.rb
  spec/system/admin/admin_manages_profile_fields_spec.rb
Labels: PR: partially-approved

#11405 Remove wrong metric from Feeds::Import
  app/services/feeds/import.rb
Labels: PR: partially-approved

#10764 Make markup for dashboard ellipsis menu more consistent
  app/assets/javascripts/initializers/initializeEllipsisMenu.js
  app/assets/stylesheets/dashboard.scss
  app/views/dashboards/_dashboard_article.html.erb
  app/views/dashboards/_dashboard_article_row.html.erb
Labels: PR: partially-approved

#11387 Fixed the scroll bar problem in Safari
  app/assets/stylesheets/components/modals.scss
Labels: PR: reviewed-approved

#11438 Fix small ERB linting issues
  app/views/articles/tags/_sidebar.html.erb
  app/views/moderations/mod.html.erb
  app/views/podcasts/_form.html.erb
Labels: PR: partially-approved

#10249 Removing data-testid from Article component
  app/javascript/articles/Article.jsx
  app/javascript/articles/__tests__/Article.test.jsx
  app/javascript/articles/__tests__/__snapshots__/Article.test.jsx.snap
Labels: PR: reviewed-approved

#11350 Update data update script
  lib/data_update_scripts/20201103050112_prepare_for_profile_column_drop.rb
  spec/lib/data_update_scripts/prepare_for_profile_column_drop_spec.rb
Labels: PR: reviewed-approved, action: pre deployment, merge by any core

#11441 Jest: Lower branches code coverage to 38 to unblock builds
  jest.config.js
Labels: PR: reviewed-approved

#11411 Add partial index on users.feed_url
  db/migrate/20201114151157_add_partial_index_to_users_feed_url.rb
  db/schema.rb
Labels: PR: reviewed-approved

#11409 Use faster JS selection methods
  app/assets/javascripts/initializers/initializeAllChatButtons.js
  app/assets/javascripts/initializers/initializeAllFollowButts.js
  app/assets/javascripts/initializers/initializeBaseUserData.js
  app/assets/javascripts/initializers/initializeCommentDropdown.js
  app/assets/javascripts/initializers/initializeCommentPreview.js
  app/assets/javascripts/initializers/initializeCommentsPage.js.erb
  app/assets/javascripts/initializers/initializeDrawerSliders.js
  app/assets/javascripts/initializers/initializeEllipsisMenu.js
  app/assets/javascripts/initializers/initializePodcastPlayback.js
  app/assets/javascripts/initializers/initializeUserProfilePage.js
  app/assets/javascripts/utilities/showModal.js
  app/assets/javascripts/utilities/slideSidebar.js
  app/javascript/actionsPanel/__tests__/actionsPanel.test.js
  app/javascript/actionsPanel/__tests__/initializeActionsPanelToggle.test.js
  app/javascript/actionsPanel/actionsPanel.js
  app/javascript/actionsPanel/initializeActionsPanelToggle.js
  app/javascript/admin/__tests__/controllers/article_controller.test.js
  app/javascript/admin/__tests__/controllers/buffer_controller.test.js
  app/javascript/admin/__tests__/controllers/config_controller.test.js
  app/javascript/admin/controllers/article_controller.js
  app/javascript/admin/controllers/buffer_controller.js
  app/javascript/admin/controllers/config_controller.js
  app/javascript/chat/chat.jsx
  app/javascript/chat/util.js
  app/javascript/contentDisplayPolicy/hideBlockedContent.js
  app/javascript/listings/utils.js
  app/javascript/modCenter/__tests__/moderationArticles.test.jsx
  app/javascript/modCenter/moderationArticles.jsx
  app/javascript/modCenter/singleArticle/__tests__/singleArticle.test.jsx
  app/javascript/modCenter/singleArticle/index.jsx
  app/javascript/packs/articlePage.jsx
  app/javascript/packs/commentModPage.js
  app/javascript/packs/flagUserModal.jsx
  app/javascript/packs/homePage.jsx
  app/javascript/packs/homePageFeedShortcuts.jsx
  app/javascript/packs/signupModalShortcuts.jsx
  app/javascript/packs/stickySaveFooter.js
  app/javascript/responseTemplates/responseTemplates.js
  app/javascript/shared/components/__tests__/useListNavigation.test.js
  app/javascript/utilities/codeFullscreenModeSwitcher.js
  app/javascript/utilities/viewport.js
  app/liquid_tags/user_subscription_tag.rb
  app/views/admin/feedback_messages/_feedback_message.html.erb
  app/views/articles/_fitvids.html.erb
  app/views/articles/_search.html.erb
  app/views/comments/_form.html.erb
  app/views/users/_profile.html.erb
  docs/frontend/readme.md
  docs/frontend/tips.md
  spec/system/comments/user_fills_out_comment_spec.rb
  spec/system/onboardings/user_completes_onboarding_spec.rb
Labels: PR: unreviewed

#11445 Bug Fix:Update Remove Draft Articles Scripts to not use Squish
  .rubocop.yml
  lib/data_update_scripts/20200901085230_remove_draft_articles_with_duplicate_canonical_url.rb
  lib/data_update_scripts/20200904132553_remove_draft_articles_with_duplicate_feed_source_url.rb
  lib/data_update_scripts/20200910135958_remove_draft_articles_with_duplicate_user_id_title_body_markdown.rb
Labels: PR: unreviewed

#11361 Spec Speed Up:Stories Index Spec
  spec/requests/stories_index_spec.rb
Labels: PR: partially-approved

#11446 Fix document.body.getElementById is not a function
  app/javascript/packs/homePage.jsx
Labels: PR: partially-approved

#11447 Refactor: Remove more_tag_weight_more_random_experiment
  app/controllers/stories/feeds_controller.rb
  app/services/articles/feeds/large_forem_experimental.rb
  config/field_test.yml
  spec/services/articles/feeds/large_forem_experimental_spec.rb
Labels: PR: partially-approved

#11448 Optimization:Only Check Past Day for DataUpdateScript failures
  app/workers/metrics/check_data_update_script_statuses.rb
Labels: PR: reviewed-approved

#11453 Change "use" to "Use" on Nav Link script
  lib/data_update_scripts/20201001173841_add_navigation_links.rb
Labels: PR: partially-approved

#11442 Allow Forems to specify which domains are allowed for registration
  app/controllers/admin/configs_controller.rb
  app/controllers/registrations_controller.rb
  app/javascript/admin/controllers/config_controller.js
  app/lib/constants/site_config.rb
  app/models/site_config.rb
  app/views/admin/configs/show.html.erb
  app/views/shared/authentication/_email_registration_form.html.erb
  spec/requests/admin/configs_spec.rb
  spec/requests/registrations_spec.rb
Labels: PR: partially-approved

#11451 Add username to profile more info button
  app/views/users/show.html.erb
  docs/technical-overview/architecture.md
  spec/requests/user/user_profile_spec.rb
Labels: PR: unreviewed

#11457 Fixes a bug where the data-article-path was malformed and caused 404 links
  app/assets/javascripts/utilities/buildArticleHTML.js
Labels: PR: partially-approved

#11450 Add community_emoji to SiteConfig
  app/controllers/admin/configs_controller.rb
  app/helpers/application_helper.rb
  app/lib/constants/site_config.rb
  app/models/site_config.rb
  app/views/admin/configs/show.html.erb
  app/views/articles/index.html.erb
  app/views/chat_channels/index.html.erb
  spec/liquid_tags/tweet_tag_spec.rb
  spec/requests/admin/configs_spec.rb
  spec/requests/stories_show_spec.rb
Labels: PR: partially-approved, action: post deployment

#11460 Fix snackbar component displayName
  app/javascript/Snackbar/Snackbar.jsx
Labels: PR: partially-approved, javascript, merge by any core

#11412 Refactor RssReader and Feeds::Import common parts: take 1
  app/models/tweet.rb
  app/services/feeds/check_item_medium_reply.rb
  app/services/feeds/check_item_previously_imported.rb
  app/services/feeds/import.rb
  app/services/rss_reader.rb
Labels: PR: partially-approved, merge by any core

#11459 Add Preact dev tools to development bundles
  app/javascript/Search/Search.jsx
  app/javascript/Search/SearchForm.jsx
  app/javascript/onboarding/Onboarding.jsx
  config/webpack/development.js
  docs/frontend/debugging.md
Labels: PR: partially-approved, area: frontend infrastructure, merge by any core

#11465 Fix broken article feed keyboard navigation
  app/assets/javascripts/utilities/buildArticleHTML.js
Labels: PR: partially-approved

#11473 Recommend Redis 6 for Forem self installation
  docs/installation/linux.md
  docs/installation/mac.md
  docs/installation/windows.md
Labels: PR: partially-approved

#11124 Added published date as editable in admin articles list/show
  app/controllers/admin/articles_controller.rb
  app/models/article.rb
  app/views/admin/articles/_individual_article.html.erb
  spec/models/article_spec.rb
  spec/requests/admin/articles_spec.rb
Labels: PR: reviewed-approved

#11407 Update PR template to prompt for accessibility
  .github/PULL_REQUEST_TEMPLATE.md
  docs/contributing/forem.md
  docs/frontend/accessibility.md
  docs/frontend/readme.md
Labels: PR: reviewed-approved

#11479 Feature:Backend Username Search Endpoint for Mention Completion
  app/controllers/search_controller.rb
  app/services/search/user.rb
  config/routes.rb
  spec/requests/search_spec.rb
  spec/services/search/user_spec.rb
Labels: PR: unreviewed

#11283 Comments UI update
  app/assets/images/collapse.svg
  app/assets/images/expand.svg
  app/assets/images/small-medal.svg
  app/assets/images/small-overflow-horizontal.svg
  app/assets/images/small-thread.svg
  app/assets/javascripts/initializers/initializeCommentDropdown.js
  app/assets/javascripts/initializers/initializeCommentsPage.js.erb
  app/assets/javascripts/utilities/buildCommentFormHTML.js.erb
  app/assets/javascripts/utilities/buildCommentHTML.js.erb
  app/assets/stylesheets/comments.scss
  app/assets/stylesheets/config/_generator.scss
  app/assets/stylesheets/fundamentals.scss
  app/assets/stylesheets/minimal.scss
  app/assets/stylesheets/podcast-episodes-show.scss
  app/assets/stylesheets/views/comments.scss
  app/views/articles/_bottom_content.html.erb
  app/views/articles/_conduct_and_abuse_actions.html.erb
  app/views/articles/_full_comment_area.html.erb
  app/views/articles/delete_confirm.html.erb
  app/views/comments/_comment.html.erb
  app/views/comments/_comment_avatar.html.erb
  app/views/comments/_comment_date.erb
  app/views/comments/_comment_footer.html.erb
  app/views/comments/_comment_header.html.erb
  app/views/comments/_comment_proper.html.erb
  app/views/comments/_comment_quality_marker.html.erb
  app/views/comments/_form.html.erb
  app/views/comments/delete_confirm.html.erb
  app/views/comments/deleted_commentable_comment.html.erb
  app/views/comments/edit.html.erb
  app/views/comments/index.html.erb
  app/views/comments/settings.html.erb
  app/views/listings/delete_confirm.html.erb
  app/views/notifications/shared/_comment_box.html.erb
  app/views/podcast_episodes/show.html.erb
  spec/requests/comments_spec.rb
  spec/system/comments/user_edits_a_comment_spec.rb
  spec/system/comments/user_views_article_comments_spec.rb
  spec/system/podcasts/user_visits_podcast_episode_spec.rb
  spec/system/user_visits_a_comments_page_spec.rb
  spec/views/comments/_comment.html.erb_spec.rb
Labels: Crayons, PR: partially-approved, PR: reviewed-changes-requested, PR: unreviewed, area: comments, merge by any core

#11472 Add article cachebust backoff update script
  lib/data_update_scripts/20201118141822_gradual_article_cache_bust.rb
Labels: PR: unreviewed

#11480 Fix comment phrasing
  app/views/users/_sidebar.html.erb
Labels: PR: reviewed-approved

#11474 Remove boolean checks for validate_inclusion_of in specs
  spec/models/follow_spec.rb
  spec/models/profile_field_spec.rb
  spec/models/user_spec.rb
Labels: PR: partially-approved

#11410 Podcast ownership join table (MLH Fellowship #81)
  app/models/podcast.rb
  app/models/podcast_ownership.rb
  app/models/user.rb
  db/migrate/20201114130315_create_podcast_ownerships.rb
  db/schema.rb
  spec/factories/podcast_ownership.rb
  spec/models/podcast_ownership_spec.rb
  spec/models/podcast_spec.rb
  spec/models/user_spec.rb
Labels: PR: partially-approved

#11481 Fix seed values for ProfileFields
  app/services/profile_fields/add_base_fields.rb
  app/services/profile_fields/add_branding_fields.rb
  app/services/profile_fields/add_link_fields.rb
  app/services/profile_fields/add_work_fields.rb
  app/services/profile_fields/field_definition.rb
Labels: PR: partially-approved

#11495 Remove under-used admin/growth tab
  app/controllers/admin/growth_controller.rb
  app/helpers/admin_helper.rb
  app/models/growth.rb
  app/views/admin/growth/_results.html.erb
  app/views/admin/growth/index.html.erb
  spec/requests/admin/growth_spec.rb
Labels: PR: reviewed-approved, merge by any core

#11468 Multistage container builds
  .buildkite/pipeline.containers.yml
  .github/CODEOWNERS
  Containerfile
  container-compose.yml
  docker-compose.yml
  scripts/build_containers.sh
Labels: PR: reviewed-approved

#11499 Fix buildkite login to quay.io
  .buildkite/pipeline.containers.yml
Labels: PR: partially-approved
