Repository forem/forem, pull requests merged in 2020-12, with the labels that each got.

#11613 Move app/labor/follow_checker.rb to service
  app/controllers/follows_controller.rb
  app/labor/follow_checker.rb
  app/services/follows/check_cached.rb
  spec/services/follows/check_cached_spec.rb
Labels: PR: partially-approved

#11678 Move app/labor/reaction_image.rb to helper
  app/helpers/notifications_helper.rb
  app/labor/reaction_image.rb
  app/views/notifications/_aggregated_reactions.html.erb
  app/views/notifications/_single_reaction.html.erb
  spec/helpers/notifications_helper_spec.rb
  spec/labor/reaction_image_spec.rb
Labels: PR: partially-approved

#11685 Cleaned up tests I wrote for #11525
  app/javascript/Search/__tests__/SearchFormSync.test.jsx
Labels: PR: partially-approved, area: tests, javascript, merge by any core

#11693 Move the color picker to its own initializer file
  app/assets/javascripts/initializePage.js
  app/assets/javascripts/initializers/initializeColorPicker.js
  app/views/users/_profile.html.erb
Labels: PR: reviewed-approved

#11689 Improve error message of User Subscriptions
  app/models/user_subscription.rb
  spec/models/user_subscription_spec.rb
  spec/requests/user_subscriptions_spec.rb
Labels: PR: reviewed-approved

#11358 Add configs/show api for admins
  app/controllers/api/v0/admin/configs_controller.rb
  app/controllers/api/v0/api_controller.rb
  app/views/api/v0/admin/configs/show.json.jbuilder
  config/routes.rb
  docs/api_v0.yml
  spec/requests/api/v0/admin/configs_spec.rb
Labels: PR: unreviewed

#11691 Move GeneratedImage to Images::GenerateSocialImage
  app/helpers/social_image_helper.rb
  app/labor/generated_image.rb
  app/services/images/generate_social_image.rb
  app/view_objects/articles/social_image.rb
  spec/helpers/social_image_helper_spec.rb
  spec/services/images/generate_social_image_spec.rb
Labels: PR: partially-approved

#11679 Move app/labor/error_message_cleaner.rb to service
  app/controllers/articles_controller.rb
  app/labor/error_message_cleaner.rb
  app/models/article.rb
  app/services/error_messages/clean.rb
Labels: PR: partially-approved

#11695 Fix invalid feed error display in settings
  app/views/users/_publishing_from_rss.html.erb
  app/views/users/_response_templates.html.erb
  spec/system/user/user_edits_extensions_spec.rb
Labels: PR: partially-approved

#11240 Adds ability for admins to create new tags via /admin/tags
  app/controllers/admin/tags/moderators_controller.rb
  app/controllers/admin/tags_controller.rb
  app/views/admin/tags/_form.html.erb
  app/views/admin/tags/edit.html.erb
  app/views/admin/tags/index.html.erb
  app/views/admin/tags/new.html.erb
  app/views/layouts/admin.html.erb
  config/routes.rb
  spec/requests/admin/tags_spec.rb
  spec/requests/stories_show_spec.rb
  spec/system/admin/admin_updates_tag_spec.rb
Labels: PR: partially-approved

#11692 Disable ActionController auto params wrapping
  config/initializers/wrap_parameters.rb
  spec/requests/api/v0/articles_spec.rb
Labels: PR: partially-approved

#10502 Refactor reCaptcha code and bypass in report abuse for trustworthy users only
  app/controllers/feedback_messages_controller.rb
  app/controllers/registrations_controller.rb
  app/helpers/authentication_helper.rb
  app/services/re_captcha.rb
  app/views/feedback_messages/_form.html.erb
  app/views/shared/authentication/_email_registration_form.html.erb
  spec/helpers/authentication_helper_spec.rb
  spec/requests/feedback_messages_spec.rb
  spec/requests/registrations_spec.rb
  spec/services/re_captcha_spec.rb
Labels: PR: partially-approved

#11700 Ensure first user of a Forem has a trusted role
  app/controllers/registrations_controller.rb
  spec/requests/registrations_spec.rb
Labels: PR: partially-approved

#11696 [EOY2020 Issue] Default new forems to Email Authentication only
  app/assets/stylesheets/admin.scss
  app/controllers/admin/configs_controller.rb
  app/helpers/authentication_helper.rb
  app/javascript/admin/controllers/config_controller.js
  app/models/site_config.rb
  app/views/admin/configs/_auth_provider_settings.html.erb
  spec/helpers/authentication_helper_spec.rb
  spec/models/user_spec.rb
  spec/policies/github_repo_policy_spec.rb
  spec/requests/admin/configs_spec.rb
  spec/requests/github_repos_spec.rb
  spec/requests/user/user_settings_spec.rb
  spec/services/authentication/authenticator_spec.rb
  spec/services/authentication/providers_spec.rb
  spec/services/broadcasts/welcome_notification/generator_spec.rb
  spec/services/users/delete_spec.rb
  spec/system/authentication/omniauth_redirect_uri_spec.rb
  spec/system/authentication/redirects_using_referer_spec.rb
  spec/system/authentication/user_logs_in_with_facebook_spec.rb
  spec/system/authentication/user_logs_in_with_github_spec.rb
  spec/system/authentication/user_logs_in_with_twitter_spec.rb
  spec/system/homepage/user_visits_homepage_spec.rb
  spec/system/user_logs_in_with_password_spec.rb
Labels: PR: partially-approved, merge by any core

#11706 Split ReCaptcha service and use verbs instead of pronouns
  app/controllers/feedback_messages_controller.rb
  app/controllers/registrations_controller.rb
  app/services/re_captcha.rb
  app/services/re_captcha/check_enabled.rb
  app/services/re_captcha/check_registration_enabled.rb
  app/views/feedback_messages/_form.html.erb
  app/views/shared/authentication/_email_registration_form.html.erb
  spec/services/re_captcha/check_enabled_spec.rb
  spec/services/re_captcha/check_registration_enabled_spec.rb
  spec/services/re_captcha_spec.rb
Labels: PR: unreviewed, merge by any core

#10707 Drop profile columns from user
  app/controllers/profiles_controller.rb
  app/controllers/stories_controller.rb
  app/lib/constants/mastodon.rb
  app/lib/database.rb
  app/models/profile.rb
  app/models/user.rb
  app/refinements/hash_any_key.rb
  app/services/moderator/banish_user.rb
  app/services/profile_fields/add_base_fields.rb
  app/services/profile_fields/import_from_csv.rb
  app/services/profiles/extract_data.rb
  app/services/profiles/update.rb
  app/validators/profile_validator.rb
  app/views/admin/profile_fields/_grouped_profile_fields.html.erb
  app/views/users/_profile.html.erb
  app/views/users/show.html.erb
  db/seeds.rb
  lib/data/coding_profile_fields.csv
  lib/data/dev_profile_fields.csv
  lib/data_update_scripts/20200819025131_migrate_profile_data.rb
  lib/data_update_scripts/20201103050112_prepare_for_profile_column_drop.rb
  lib/data_update_scripts/20201130041949_remove_name_profile_field.rb
  spec/factories/profiles.rb
  spec/factories/users.rb
  spec/fixtures/files/profile_fields.csv
  spec/lib/data_update_scripts/create_profile_fields_spec.rb
  spec/lib/data_update_scripts/migrate_profile_data_spec.rb
  spec/lib/data_update_scripts/prepare_for_profile_column_drop_spec.rb
  spec/models/organization_spec.rb
  spec/models/profile_spec.rb
  spec/models/user_spec.rb
  spec/rails_helper.rb
  spec/requests/admin/profile_fields_spec.rb
  spec/requests/profile_field_groups_request_spec.rb
  spec/requests/profiles_request_spec.rb
  spec/requests/user/user_show_spec.rb
  spec/requests/user/user_suggestions_spec.rb
  spec/services/profile_fields/field_definition_spec.rb
  spec/services/profile_fields/import_from_csv_spec.rb
  spec/services/profiles/update_spec.rb
  spec/system/admin/admin_manages_profile_fields_spec.rb
  spec/system/user_selects_looking_for_work_spec.rb
  spec/workers/moderator/banish_user_worker_spec.rb
Labels: PR: partially-approved

#11701 Logo on /new
  app/views/articles/_v2_form.html.erb
  spec/system/user_uses_the_editor_spec.rb
Labels: PR: reviewed-approved, area: publishing experience, tech: html/css

#11715 Fixes a rubocop failure that slipped through in a previous PR
  spec/requests/feedback_messages_spec.rb
Labels: PR: partially-approved, merge by any core

#11730 Adds a present? check to the DEV specific fields [Profile Generalization]
  app/views/users/show.html.erb
Labels: PR: reviewed-approved

#11650 Bugfix: Remove focus from avatars in notifications for better keyboard navigation
  app/views/notifications/_aggregated_reactions.html.erb
  app/views/notifications/_follow.html.erb
  app/views/notifications/shared/_profile_pic.html.erb
Labels: PR: partially-approved

#11675 Add a/b test for implicit follow points
  app/workers/follows/update_points_worker.rb
  config/field_test.yml
  docs/technical-overview/ab_testing.md
  docs/technical-overview/readme.md
  spec/workers/follows/update_points_worker_spec.rb
Labels: PR: unreviewed

#11729 Fix schema.db whitespace
  db/schema.rb
  spec/system/user_selects_looking_for_work_spec.rb
Labels: PR: unreviewed

#11710 Bug Fix: First Published Post Not Showing Properly in the Feed
  app/javascript/articles/Feed.jsx
Labels: PR: partially-approved

#11732 Change profile header cache key to purge headers
  app/views/users/show.html.erb
Labels: PR: reviewed-approved, action: pre deployment

#11733 Add first time admin login to FAQs
  docs/faqs.md
  docs/getting-started/start-app.md
Labels: PR: partially-approved

#11712 Remove confusing line from readme
  docs/readme.md
Labels: PR: reviewed-approved

#11464 Temp Feature: Award Hacktoberfest Badges Rake Task
  lib/tasks/temporary/hacktoberfest_badges.rake
Labels: PR: partially-approved

#11735 Improve user subscription UX flow when latency is high
  app/liquid_tags/user_subscription_tag.rb
  app/views/liquids/_user_subscription.html.erb
  spec/liquid_tags/user_subscription_tag_spec.rb
Labels: PR: partially-approved

#11736 Return from method if env called in boot up not available
  app/models/profile.rb
Labels: PR: reviewed-approved

#11721 Headings and alt text roundup
  app/assets/javascripts/utilities/buildArticleHTML.js
  app/javascript/articles/__tests__/__snapshots__/Article.test.jsx.snap
  app/javascript/articles/components/ContentTitle.jsx
  app/javascript/listings/components/MessageModal.jsx
  app/views/articles/_full_comment_area.html.erb
  app/views/articles/_sidebar_nav.html.erb
  app/views/articles/index.html.erb
  app/views/articles/tag_index.html.erb
  app/views/onboardings/_task_card.html.erb
  app/views/tags/index.html.erb
  app/views/users/_comments_section.html.erb
Labels: PR: partially-approved

#11737 Fix wikipedia tag z-index
  app/assets/stylesheets/ltags/WikipediaTag.scss
Labels: PR: partially-approved

#11725 Remove unused index_notifications_on_json_data
  db/migrate/20201203063435_remove_index_notifications_on_json_data_from_notifications.rb
  db/schema.rb
Labels: PR: unreviewed

#11752 Remove non application files from frontend code coverage
  .eslintignore
  app/javascript/CommentSubscription/index.js
  app/javascript/article-form/components/index.js
  app/javascript/articles/components/index.js
  app/javascript/podcasts/index.js
  jest.config.js
Labels: PR: partially-approved, area: tests, javascript

#11741 Generalize social image path and clean up code
  app/services/images/generate_social_image.rb
  spec/services/images/generate_social_image_spec.rb
Labels: PR: reviewed-approved

#11785 Revert "Bump husky from 4.3.0 to 4.3.4 (#11764)"
  package.json
  yarn.lock
Labels: PR: partially-approved

#11786 [Hotfix] Allow blank values for payment_pointer
  app/models/user.rb
  spec/models/user_spec.rb
Labels: PR: reviewed-approved

#11744 Use custom, dynamic, error pages
  app/controllers/errors_controller.rb
  app/models/comment.rb
  app/views/errors/internal_server_error.html.erb
  app/views/errors/not_found.html.erb
  app/views/errors/service_unavailable.html.erb
  app/views/errors/unprocessable_entity.html.erb
  app/views/service_worker/index.js.erb
  config/application.rb
  config/routes.rb
  spec/requests/errors_request_spec.rb
Labels: PR: partially-approved

#11734 Remove concept of "ongoing" field tests and clarify a/b test instructions/expectations.
  app/controllers/stories/feeds_controller.rb
  app/models/comment.rb
  app/models/page_view.rb
  app/models/reaction.rb
  app/workers/field_tests/prune_old_experiments_worker.rb
  config/field_test.yml
  config/schedule.yml
  docs/technical-overview/ab_testing.md
  spec/factories/field_test_memberships.rb
  spec/requests/comments_spec.rb
  spec/requests/page_views_spec.rb
  spec/requests/reactions_spec.rb
  spec/requests/stories/feeds_spec.rb
  spec/workers/field_tests/prune_old_experiments_worker_spec.rb
  spec/workers/users/record_field_test_event_worker_spec.rb
Labels: PR: partially-approved

#11704 Deployment Task: Update onboarding fields prior to #11629
  app/services/profile_fields/add_base_fields.rb
  app/services/profile_fields/field_definition.rb
  app/services/profile_fields/import_from_csv.rb
  lib/data/dev_profile_fields.csv
  lib/tasks/temporary/profile_onboarding_fields.rake
  spec/fixtures/files/profile_fields.csv
  spec/requests/profile_field_groups_request_spec.rb
Labels: PR: partially-approved

#11787 Fix Rspec warning regarding specific error class
  spec/labor/assign_tag_moderator_spec.rb
Labels: PR: partially-approved

#11783 Move profile initialization to after_initialize hook
  app/models/profile.rb
  config/application.rb
Labels: PR: partially-approved

#11782 Remove timeframer from app/labor
  app/controllers/stories/feeds_controller.rb
  app/controllers/stories_controller.rb
  app/models/timeframe.rb
  app/services/articles/feeds/large_forem_experimental.rb
  app/views/articles/_sidebar_additional.html.erb
  app/views/articles/index.html.erb
  app/views/articles/search.html.erb
  app/views/articles/tag_index.html.erb
  app/views/articles/tags/_sidebar_additional.html.erb
  app/views/organizations/show.html.erb
  app/views/podcast_episodes/index.html.erb
  spec/labor/timeframer_spec.rb
  spec/models/timeframe_spec.rb
Labels: PR: partially-approved

#11789 Remove @storybook/components from yarn.lock
  yarn.lock
Labels: PR: partially-approved

#11797 [Hotfix] Fix broken experience level button in moderation panel
  app/javascript/actionsPanel/actionsPanel.js
  app/javascript/packs/commentModPage.js
Labels: PR: partially-approved

#11795 Fix Mod Center compatibility issue with dark themes (Date column)
  app/assets/stylesheets/views/mod-center.scss
Labels: PR: reviewed-approved

#11776 Upgrade Admin to Stimulus 2.0
  app/javascript/admin/__tests__/controllers/article_controller.test.js
  app/javascript/admin/__tests__/controllers/buffer_controller.test.js
  app/javascript/admin/__tests__/controllers/config_controller.test.js
  app/javascript/admin/controllers/article_controller.js
  app/javascript/admin/controllers/buffer_controller.js
  app/javascript/admin/controllers/config_controller.js
  app/javascript/admin/controllers/image_upload_controller.js
  app/javascript/admin/controllers/modal_controller.js
  app/javascript/admin/controllers/reaction_controller.js
  app/views/admin/articles/_individual_article.html.erb
  app/views/admin/articles/index.html.erb
  app/views/admin/configs/show.html.erb
  app/views/admin/feedback_messages/_abuse_reports.html.erb
  app/views/admin/listings/index.html.erb
  app/views/admin/profile_fields/_add_group_modal.html.erb
  app/views/admin/profile_fields/_add_profile_field_modal.html.erb
  app/views/admin/profile_fields/_edit_group_modal.html.erb
  app/views/admin/shared/_image_uploader.html.erb
  package.json
  yarn.lock
Labels: PR: unreviewed

#11796 Invalidate cache for all org users' profiles
  app/controllers/organizations_controller.rb
Labels: PR: reviewed-approved

#11794 GitHub workflow for /ci trigger
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/buildkite.yml
  .github/workflows/pr.yml
Labels: PR: reviewed-approved

#10424 Updating navigation (especially mobile)
  app/assets/images/search.svg
  app/assets/javascripts/initializePage.js
  app/assets/javascripts/initializers/initializeBaseUserData.js
  app/assets/javascripts/initializers/initializeTouchDevice.js
  app/assets/stylesheets/components/hamburger.scss
  app/assets/stylesheets/components/header.scss
  app/assets/stylesheets/components/stories.scss
  app/assets/stylesheets/crayons.scss
  app/javascript/packs/base.js
  app/javascript/packs/homePage.jsx
  app/javascript/topNavigation/__tests__/utilities.test.js
  app/javascript/topNavigation/utilities.js
  app/views/articles/_sidebar.html.erb
  app/views/articles/_sidebar_additional.html.erb
  app/views/articles/_sidebar_nav.html.erb
  app/views/articles/index.html.erb
  app/views/articles/search.html.erb
  app/views/layouts/_main_nav.html.erb
  app/views/layouts/_nav_menu.html.erb
  app/views/layouts/_sidebar_nav_link.html.erb
  app/views/layouts/_sidebar_tags.html.erb
  app/views/layouts/_top_bar.html.erb
  app/views/shared/_auth_widget.html.erb
  app/views/shared/_hamburger.html.erb
  app/views/shell/_top.html.erb
  docs/technical-overview/ab_testing.md
  package.json
  spec/services/images/generate_social_image_spec.rb
  spec/system/authentication/user_logs_in_with_facebook_spec.rb
  spec/system/authentication/user_logs_in_with_github_spec.rb
  spec/system/authentication/user_logs_in_with_twitter_spec.rb
  spec/system/homepage/user_visits_homepage_spec.rb
  yarn.lock
Labels: Crayons, PR: partially-approved, PR: reviewed-changes-requested, PR: unreviewed, area: design, area: mobile, tech: html/css

#11799 Fix google action typo
  .github/workflows/buildkite.yml
Labels: PR: reviewed-approved

#11801 Fix YAML so it is actually valid GitHub Action YAMLs.
  .github/workflows/pr.yml
Labels: PR: partially-approved

#11800 Replace the "setup onboarding profile fields" temp rake task with a data update script
  lib/data_update_scripts/20201208151516_set_onboarding_profile_fields_for_existing_forems.rb
  lib/tasks/temporary/profile_onboarding_fields.rake
  spec/lib/data_update_scripts/set_onboarding_profile_fields_for_existing_forems_spec.rb
Labels: PR: unreviewed

#11806 Use static error files in serviceworker
  app/views/service_worker/index.js.erb
  public/error.html
  public/not_found.html
Labels: PR: partially-approved

#11779 Check github actions weekly with dependabot
  .github/dependabot.yml
Labels: PR: reviewed-approved

#11807 Try to fix GitHub Action conditionals again.
  .github/workflows/buildkite.yml
  .github/workflows/rebase.yml
Labels: PR: reviewed-approved

#11788 Add bust_article service
  app/services/edge_cache/bust.rb
  app/services/edge_cache/bust_article.rb
  spec/services/edge_cache/bust_article_spec.rb
  spec/services/edge_cache/bust_spec.rb
Labels: PR: partially-approved, merge by any core

#11629 Profile generalization for the onboarding workflow
  app/assets/stylesheets/preact/onboarding-modal.scss
  app/controllers/users_controller.rb
  app/javascript/onboarding/__tests__/Onboarding.test.jsx
  app/javascript/onboarding/components/FollowTags.jsx
  app/javascript/onboarding/components/FollowUsers.jsx
  app/javascript/onboarding/components/IntroSlide.jsx
  app/javascript/onboarding/components/ProfileForm.jsx
  app/javascript/onboarding/components/ProfileForm/CheckBox.jsx
  app/javascript/onboarding/components/ProfileForm/ColorPicker.jsx
  app/javascript/onboarding/components/ProfileForm/TextArea.jsx
  app/javascript/onboarding/components/ProfileForm/TextInput.jsx
  app/javascript/onboarding/components/__tests__/FollowUsers.test.jsx
  app/javascript/onboarding/components/__tests__/ProfileForm.test.jsx
  spec/requests/users_onboarding_spec.rb
Labels: PR: unreviewed, action: pre deployment

#11814 Add onboarding param to safe list
  config/fastly/snippets/safe_params_list.vcl
Labels: PR: partially-approved

#11810 Fix feed select dropdown
  app/views/articles/tag_index.html.erb
Labels: PR: partially-approved, merge by any core

#11811 Fix admin header links
  app/views/layouts/admin.html.erb
Labels: PR: partially-approved, merge by any core

#11816 GitHub Action bug fixes
  .github/workflows/buildkite.yml
  .github/workflows/pr.yml
  .github/workflows/rebase.yml
Labels: PR: partially-approved

#11819 Add debug to actions.
  .github/workflows/buildkite.yml
  .github/workflows/rebase.yml
Labels: PR: reviewed-approved

#11820 GitHub Actions comment out conditional
  .github/workflows/buildkite.yml
Labels: PR: reviewed-approved

#11821 Update buildkite.yml
  .github/workflows/buildkite.yml
Labels: PR: unreviewed

#11822 Add github.event.comment.author_association == 'CONTRIBUTOR' to if statement in GitHub Actions
  .github/workflows/buildkite.yml
  .github/workflows/dependabot.yml
  .github/workflows/pr.yml
  .github/workflows/rebase.yml
Labels: PR: partially-approved

#11812 Create services for busting pages, tags, events, and podcasts
  app/services/edge_cache/bust_events.rb
  app/services/edge_cache/bust_page.rb
  app/services/edge_cache/bust_podcast.rb
  app/services/edge_cache/bust_tag.rb
  spec/services/edge_cache/bust_events_spec.rb
  spec/services/edge_cache/bust_page_spec.rb
  spec/services/edge_cache/bust_podcast_spec.rb
  spec/services/edge_cache/bust_tag_spec.rb
Labels: PR: reviewed-approved, merge by any core

#11485 Render Profile Fields on user profiles
  app/controllers/stories_controller.rb
  app/decorators/profile_decorator.rb
  app/models/profile.rb
  app/views/users/_metadata.html.erb
  app/views/users/_profile_fields.html.erb
  app/views/users/_sidebar.html.erb
  db/seeds.rb
  lib/data/dev_profile_fields.csv
  spec/system/user/user_edits_profile_spec.rb
Labels: PR: partially-approved

#11830 Scope PR workflow only run when the PR is opened.
  .github/workflows/pr.yml
Labels: PR: reviewed-approved

#11829 Disable duplicate resave data upgrade script
  lib/data_update_scripts/20201014184856_resave_users_for_imgproxy.rb
  lib/data_update_scripts/20201020215535_resave_articles_and_comments_for_imgproxy.rb
  lib/data_update_scripts/20201103050112_prepare_for_profile_column_drop.rb
Labels: PR: partially-approved

#11813 Ensure Article's `username` method returns a downcased string
  app/models/article.rb
  lib/data_update_scripts/20201209134953_touch_articles_with_capitalized_paths.rb
  spec/lib/data_update_scripts/touch_articles_with_capitalized_paths_spec.rb
  spec/models/article_spec.rb
Labels: PR: unreviewed, action: post deployment, merge by any core

#11834 Update Buildkite workflow trigger-pipeline-action version
  .github/workflows/buildkite.yml
Labels: PR: reviewed-approved

#11835 Add Cypress for end to end testing (E2E)
  .travis.yml
  cypress/.eslintrc.js
  package.json
  yarn.lock
Labels: PR: partially-approved, area: frontend infrastructure, area: tests

#11825 Remove app/labor/color_from_image.rb
  Gemfile
  app/labor/color_from_image.rb
  app/models/article.rb
  app/workers/articles/update_main_image_background_hex_worker.rb
  spec/labor/color_from_image_spec.rb
  spec/models/article_spec.rb
  spec/workers/articles/update_main_image_background_hex_worker_spec.rb
Labels: PR: unreviewed

#11824 Move Twilio from labor to services
  app/controllers/twilio_tokens_controller.rb
  app/labor/twilio_token.rb
  app/services/twilio/get_jwt_token.rb
  spec/labor/twilio_token_spec.rb
  spec/services/twilio/get_jwt_token_spec.rb
Labels: PR: reviewed-approved

#11841 Fix eslint and jest configurations for cypress
  cypress/.eslintrc.js
  jest.config.js
Labels: PR: reviewed-approved, area: frontend infrastructure, area: tests, merge by any core

#11836 Don't attempt to call summary on profile during onboarding
  app/validators/profile_validator.rb
Labels: PR: partially-approved

#11527 Update aspect ratio of images on the Admin's config page
  app/lib/constants/site_config.rb
  app/models/site_config.rb
  app/views/admin/configs/show.html.erb
Labels: PR: partially-approved

#11847 Fix misleading comment
  app/validators/profile_validator.rb
Labels: PR: partially-approved

#11848 Update the contact email address in the database
  lib/data_update_scripts/20201210163704_set_contact_email_address.rb
  spec/lib/data_update_scripts/set_contact_email_address_spec.rb
Labels: PR: partially-approved, merge by any core

#11850 Refactor:Remove old teams from CODEOWNERS and update general teams
  .github/CODEOWNERS
Labels: PR: reviewed-approved

#11856 Make mod button only show up for trusted user
  app/views/layouts/_top_bar.html.erb
Labels: PR: partially-approved

#11832 Create services for busting organizations, podcast episodes, listings, and users
  app/services/edge_cache/bust_listings.rb
  app/services/edge_cache/bust_organization.rb
  app/services/edge_cache/bust_podcast_episode.rb
  app/services/edge_cache/bust_user.rb
  spec/services/edge_cache/bust_listings_spec.rb
  spec/services/edge_cache/bust_organization_spec.rb
  spec/services/edge_cache/bust_podcast_episode_spec.rb
  spec/services/edge_cache/bust_user_spec.rb
Labels: PR: partially-approved, merge by any core

#11864 Fix Dependabot GitHub action syntax
  .github/workflows/dependabot.yml
Labels: PR: partially-approved

#11862 Rubocop fixes
  app/models/tag.rb
  app/services/audit/notification.rb
  lib/data_update_scripts/20201118141822_gradual_article_cache_bust.rb
  spec/lib/data_update_scripts/set_onboarding_profile_fields_for_existing_forems_spec.rb
  spec/requests/reactions_spec.rb
  spec/services/authentication/providers_spec.rb
Labels: PR: partially-approved

#11849 Add create_buildkite_pr_build.sh
  .github/workflows/buildkite.yml
  .github/workflows/dependabot.yml
  .github/workflows/issue.yml
  .github/workflows/pr.yml
  .github/workflows/rebase.yml
  scripts/create_buildkite_pr_build.sh
Labels: PR: reviewed-approved

#11863 Disable Google reCAPTCHA in env file sample
  .env_sample
Labels: PR: unreviewed

#11866 Add GITHUB_TOKEN to buildkite workflow
  .github/workflows/buildkite.yml
Labels: PR: reviewed-approved

#11840 E2E Test: Initial Adminisitrator Login Flow
  app/views/shared/authentication/_email_login_form.html.erb
  config/webpack/environment.js
  cypress.json
  cypress/.eslintrc.js
  cypress/fixtures/logins/initialAdmin.json
  cypress/integration/loginFlows/initialAdminLogin.spec.js
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/index.js
  package.json
  yarn.lock
Labels: PR: unreviewed, area: tests, merge by any core

#11869 Rework the PULL_REQUEST_ID logic
  scripts/create_buildkite_pr_build.sh
Labels: PR: reviewed-approved

#11871 Rework the PULL_REQUEST_ID logic, again
  .github/workflows/buildkite.yml
  scripts/create_buildkite_pr_build.sh
Labels: PR: partially-approved

#11878 Add sidebar bust logic
  app/labor/cache_buster.rb
  app/services/edge_cache/bust_sidebar.rb
  spec/services/edge_cache/bust_sidebar_spec.rb
Labels: PR: unreviewed

#11879 Add campaign articles to sidebar controller
  app/controllers/sidebars_controller.rb
  app/views/articles/_sidebar_additional.html.erb
Labels: PR: unreviewed

#11039 Confirmations that users GDPR data was deleted
  app/controllers/admin/application_controller.rb
  app/controllers/admin/invitations_controller.rb
  app/controllers/admin/users/gdpr_delete_requests_controller.rb
  app/controllers/admin/users_controller.rb
  app/models/users/gdpr_delete_request.rb
  app/views/admin/invitations/index.html.erb
  app/views/admin/users/_menu.html.erb
  app/views/admin/users/gdpr_delete_requests/index.html.erb
  app/views/admin/users/index.html.erb
  app/workers/users/delete_worker.rb
  config/routes.rb
  db/migrate/20201012072557_create_users_gdpr_delete_requests.rb
  db/schema.rb
  spec/factories/gdpr_delete_requests.rb
  spec/requests/admin/users/gdpr_delete_requests_spec.rb
  spec/workers/users/delete_worker_spec.rb
Labels: PR: partially-approved

#11883 Remove duplicate test file
  app/javascript/chat/__tests__/membership.test.jsx
Labels: PR: partially-approved

#11872 Fix a few bugs with the create_buildkite_pr_build.sh script
  scripts/create_buildkite_pr_build.sh
Labels: PR: reviewed-approved

#11877 Update Dependabot configuration for Bundler, Yarn/NPM and actions
  .github/dependabot.yml
  .github/workflows/dependabot.yml
Labels: PR: partially-approved

#11882 Restore static error pages
  app/controllers/errors_controller.rb
  app/models/comment.rb
  app/views/errors/internal_server_error.html.erb
  app/views/errors/not_found.html.erb
  app/views/service_worker/index.js.erb
  config/application.rb
  config/routes.rb
  public/404.html
  public/422.html
  public/500.html
  public/503.html
  spec/requests/errors_request_spec.rb
Labels: PR: partially-approved, merge by any core

#11881 Move back from after_initialize to explicit call
  app/models/profile.rb
  config/application.rb
Labels: PR: partially-approved

#11873 Switch node-sass to dart-sass
  app/javascript/.storybook/main.js
  bin/generate-css-utility-classes-docs.js
  docs/frontend/readme.md
  package.json
  yarn.lock
Labels: PR: partially-approved

#11876 🐙Enhancement: Making connect Draw Responsive according to Device width
  app/javascript/chat/draw/index.jsx
Labels: PR: partially-approved

#11917 Fix html variant image prefix logic
  app/models/html_variant.rb
  app/services/images/optimizer.rb
  spec/models/html_variant_spec.rb
Labels: PR: unreviewed

#11903 Make social preview color a color field
  app/views/admin/listing_categories/_form.html.erb
Labels: PR: partially-approved

#11867 Add Cypress to Travis
  .gitignore
  .travis.yml
  app/views/shared/authentication/_email_registration_form.html.erb
  cypress.json
  cypress/fixtures/images/admin-image.png
  cypress/fixtures/logins/initialAdmin.json
  cypress/integration/loginFlows/initialAdminLogin.spec.js
  cypress/support/index.js
  package.json
  yarn.lock
Labels: PR: partially-approved

#11916 Avoid html_safe and violating Rails/OutputSafety
  app/controllers/admin/users_controller.rb
Labels: PR: reviewed-approved

#11930 Tell Dependabot to ignore Simplecov 0.18+
  .github/dependabot.yml
Labels: PR: reviewed-approved

#11915 Document the advanced startup setup
  docs/getting-started/start-app.md
Labels: PR: unreviewed, area: documentation

#11895 Update bust_comment to BustComment
  app/services/users/delete_articles.rb
  app/services/users/delete_comments.rb
  spec/services/users/delete_articles_spec.rb
  spec/services/users/delete_comments_spec.rb
Labels: PR: unreviewed

#11901 Cache bust sidebar instead of home page
  app/labor/cache_buster.rb
Labels: PR: reviewed-approved

#11826 Move AssignTagModerator from labor to services
  app/controllers/admin/mods_controller.rb
  app/controllers/admin/tags/moderators_controller.rb
  app/labor/assign_tag_moderator.rb
  app/services/tag_moderators/add.rb
  app/services/tag_moderators/add_trusted_role.rb
  app/services/tag_moderators/remove.rb
  spec/services/tag_moderators/add_spec.rb
  spec/services/tag_moderators/add_trusted_role_spec.rb
  spec/services/tag_moderators/remove_spec.rb
Labels: PR: partially-approved

#11946 Temporarily disable e2e tests
  .travis.yml
Labels: PR: partially-approved

#11935 Update repo link on /contact to /forem/forem
  app/views/pages/contact.html.erb
Labels: PR: unreviewed

#11931 Update bust_article to BustArticle
  app/controllers/admin/tools_controller.rb
  app/services/users/delete_articles.rb
  app/workers/articles/bust_cache_worker.rb
  spec/services/users/delete_articles_spec.rb
  spec/workers/articles/bust_cache_worker_spec.rb
Labels: PR: partially-approved

#10739 Add image composite element to feed if user exists
  app/views/articles/feed.rss.builder
  spec/requests/articles/articles_spec.rb
Labels: PR: partially-approved

#11945 Fix Rails/OutputSafety violations
  app/controllers/concerns/verify_setup_completed.rb
  app/helpers/application_helper.rb
Labels: PR: unreviewed

#11929 Removed slack notification for admins when user is deleted
  app/services/slack/messengers/user_deleted.rb
  app/workers/users/delete_worker.rb
  spec/services/slack/messengers/user_deleted_spec.rb
  spec/workers/users/delete_worker_spec.rb
Labels: PR: partially-approved

#11728 Allow admin to add users as podcast owners (MLH Fellowship)
  app/controllers/admin/podcasts_controller.rb
  app/views/admin/podcasts/edit.html.erb
  app/views/admin/podcasts/index.html.erb
  config/routes.rb
  spec/requests/admin/podcasts_spec.rb
Labels: PR: partially-approved

#11954 Point acts_as_follower gem at Forem repo fork
  Gemfile
  Gemfile.lock
  vendor/cache/acts_as_follower-06393d3693a1/acts_as_follower.gemspec
Labels: PR: partially-approved

#11950 Fix end to end testing for Forem forked repositories
  .travis.yml
  bin/e2e
  package.json
Labels: PR: partially-approved, area: frontend infrastructure, area: tests

#11969 Fix the way we check for AndroidBridge global
  app/assets/javascripts/initializers/runtime.js
Labels: PR: partially-approved, merge by any core

#11967 Updates the email_addresses hash with the contact info
  lib/data_update_scripts/20201210163704_set_contact_email_address.rb
  lib/data_update_scripts/20201218080343_update_default_email_addresses.rb
  spec/lib/data_update_scripts/update_default_email_addresses_spec.rb
Labels: PR: partially-approved, merge by any core

#11870 Make followers notification overflow-hidden
  app/views/notifications/_follow.html.erb
Labels: PR: partially-approved, merge by any core

#11952 Update bust_page to EdgeCache::BustPage
  app/workers/pages/bust_cache_worker.rb
  spec/workers/pages/bust_cache_worker_spec.rb
Labels: PR: partially-approved

#11962 Fix default favicon
  app/assets/images/favicon.ico
Labels: PR: unreviewed

#11961 Add missing default social image (and remove DEV version) from /pod and /events
  app/views/events/index.html.erb
  app/views/podcast_episodes/_meta.html.erb
Labels: PR: partially-approved

#11971 Remove config single resource admin from config logic
  app/controllers/registrations_controller.rb
  app/views/admin/configs/_form_submission.html.erb
  app/views/admin/configs/show.html.erb
  spec/requests/registrations_spec.rb
Labels: PR: partially-approved, merge by any core

#11975 Disabling Cypress temporarily to figure out why the web server errors action template errors.
  .travis.yml
Labels: PR: partially-approved, area: frontend infrastructure, area: tests

#11976 Resolve problem where profile fields have not been properly imported
  app/controllers/registrations_controller.rb
  app/models/user.rb
Labels: PR: reviewed-approved

#11979 Improve date/time picker on admin/events/new
  app/views/admin/events/_event_form.html.erb
Labels: PR: partially-approved

#11951 Remove GitHub repositories when GitHub identity is removed
  app/controllers/admin/users_controller.rb
  app/controllers/users_controller.rb
  app/views/users/_integrations_github_repositories.html.erb
  lib/data_update_scripts/20201217162454_cleanup_orphan_git_hub_repositories.rb
  spec/lib/data_update_scripts/cleanup_orphan_git_hub_repositories_spec.rb
  spec/requests/admin/users_spec.rb
  spec/requests/user/user_settings_spec.rb
Labels: PR: partially-approved, area: admin, area: auth, area: settings

#11970 Lengthen local caching max-age
  config/environments/production.rb
Labels: PR: partially-approved

#11977 Reenable End to End Testing... Again 😄
  .travis.yml
  config/environments/test.rb
Labels: PR: partially-approved, area: tests

#11981 Fix API's broken organization image
  app/controllers/api/v0/organizations_controller.rb
  spec/requests/api/v0/organizations_spec.rb
Labels: PR: reviewed-approved

#11958 Fixed initial e2e test now that data updates are run.
  .travis.yml
  app/views/devise/confirmations/new.html.erb
  cypress.json
  cypress/integration/loginFlows/initialAdminLogin.spec.js
Labels: PR: unreviewed, area: frontend infrastructure, area: tests

#11994 Add rel noopener to footer links
  app/views/layouts/_footer.html.erb
Labels: PR: partially-approved

#11997 Use default social image on /listings
  app/views/listings/index.html.erb
Labels: PR: reviewed-approved

#11974 Declare winner in update points worker
  app/workers/follows/update_points_worker.rb
  config/field_test.yml
  spec/workers/follows/update_points_worker_spec.rb
Labels: PR: partially-approved

#11955 Update bust_events to EdgeCache::BustEvents
  app/workers/events/bust_cache_worker.rb
  spec/workers/events/bust_cache_worker_spec.rb
Labels: PR: partially-approved

#11953 Update bust_tag to EdgeCache::BustTag
  app/workers/tags/bust_cache_worker.rb
  spec/workers/tags/bust_cache_worker_spec.rb
Labels: PR: partially-approved

#11995 Enable paranoid mode for Devise
  config/initializers/devise.rb
  spec/system/authentication/user_logs_in_with_email_spec.rb
  spec/system/user_logs_in_with_password_spec.rb
Labels: PR: unreviewed

#12003 Filter XSS in navigationLink's title
  app/assets/javascripts/utilities/buildArticleHTML.js
Labels: PR: reviewed-approved

#12009 Upgrade to SimpleCov 0.20
  .github/dependabot.yml
  .travis.yml
  Gemfile
  Gemfile.lock
  vendor/cache/docile-1.3.2.gem
  vendor/cache/docile-1.3.3.gem
  vendor/cache/json-2.3.1.gem
  vendor/cache/json-2.5.0.gem
  vendor/cache/simplecov-0.17.1.gem
  vendor/cache/simplecov-0.20.0.gem
  vendor/cache/simplecov-html-0.10.2.gem
  vendor/cache/simplecov-html-0.12.3.gem
  vendor/cache/simplecov_json_formatter-0.1.2.gem
Labels: PR: reviewed-approved

#12012 Log error message inline when Feeds::Import fails
  app/services/feeds/import.rb
  spec/services/feeds/import_spec.rb
Labels: PR: partially-approved

#11698 Add config post route for admin api
  app/controllers/admin/application_controller.rb
  app/controllers/admin/configs_controller.rb
  app/controllers/api/v0/admin/configs_controller.rb
  app/controllers/application_controller.rb
  app/controllers/concerns/site_config_params.rb
  app/services/site_configs/upsert.rb
  config/routes.rb
  docs/api_v0.yml
  spec/requests/api/v0/admin/configs_spec.rb
Labels: PR: partially-approved

#11597 Allow any admin to publish welcome thread
  app/models/article.rb
  spec/models/article_spec.rb
Labels: PR: partially-approved, merge by any core

#12013 Added webpack bundle analyzer
  bin/bundleAnalyzer
  docs/frontend/webpacker.md
  package.json
  yarn.lock
Labels: PR: partially-approved

#11722 Remove autofollowing hiring tag
  app/services/profiles/update.rb
  spec/system/user_selects_looking_for_work_spec.rb
Labels: PR: unreviewed

#10493 fix mention in chat
  app/assets/stylesheets/chat.scss
  app/controllers/search_controller.rb
  app/javascript/chat/__tests__/chat.test.jsx
  app/javascript/chat/chat.jsx
Labels: PR: partially-approved, area: connect

#11902 Split BadgeRewarder into multiple services
  app/labor/badge_rewarder.rb
  app/models/badge.rb
  app/services/badges/award.rb
  app/services/badges/award_beloved_comment.rb
  app/services/badges/award_contributor.rb
  app/services/badges/award_contributor_from_github.rb
  app/services/badges/award_eight_week_streak.rb
  app/services/badges/award_fab_five.rb
  app/services/badges/award_four_week_streak.rb
  app/services/badges/award_sixteen_week_streak.rb
  app/services/badges/award_streak.rb
  app/services/badges/award_tag.rb
  app/services/badges/award_top_seven.rb
  app/services/badges/award_yearly_club.rb
  app/workers/badge_achievements/badge_award_worker.rb
  config/schedule.yml
  lib/tasks/badges.rake
  spec/labor/badge_rewarder_spec.rb
  spec/models/badge_spec.rb
  spec/services/badges/award_beloved_comment_spec.rb
  spec/services/badges/award_contributor_from_github_spec.rb
  spec/services/badges/award_contributor_spec.rb
  spec/services/badges/award_eight_week_streak_spec.rb
  spec/services/badges/award_fab_five_spec.rb
  spec/services/badges/award_four_week_streak_spec.rb
  spec/services/badges/award_sixteen_week_streak_spec.rb
  spec/services/badges/award_spec.rb
  spec/services/badges/award_streak_spec.rb
  spec/services/badges/award_tag_spec.rb
  spec/services/badges/award_top_seven_spec.rb
  spec/services/badges/award_yearly_club_spec.rb
  spec/workers/badge_achievements/badge_award_worker_spec.rb
Labels: PR: partially-approved, merge by any core

#12016 Routine Rubocop fixes
  app/models/user.rb
  app/services/site_configs/upsert.rb
  spec/requests/api/v0/admin/configs_spec.rb
  spec/services/broadcasts/welcome_notification/generator_spec.rb
Labels: PR: partially-approved

#11838 First working version to integrate native bridge image upload
  app/javascript/article-form/components/ArticleCoverImage.jsx
  app/javascript/article-form/components/ImageUploader.jsx
  app/javascript/article-form/components/__tests__/ArticleCoverImage.test.jsx
  app/javascript/article-form/components/__tests__/Form.test.jsx
  app/javascript/article-form/components/__tests__/ImageUploader.test.jsx
  app/javascript/packs/homePage.jsx
  app/views/sidebars/show.html.erb
Labels: PR: partially-approved
