Repository forem/forem, pull requests merged in 2020-09, with the labels that each got.

#10094 Fixes unsafe reflection warning in dashboards_controller
  app/controllers/dashboards_controller.rb
Labels: PR: partially-approved

#10097 Allow admins to set brand color
  Gemfile
  Gemfile.lock
  app/assets/stylesheets/components/buttons.scss
  app/controllers/admin/configs_controller.rb
  app/lib/constants/site_config.rb
  app/models/site_config.rb
  app/services/color/accessibility.rb
  app/views/admin/configs/show.html.erb
  app/views/shell/_top.html.erb
  spec/requests/admin/configs_spec.rb
  spec/services/color/accessibility_spec.rb
  vendor/cache/wcag_color_contrast-0.1.0.gem
Labels: PR: partially-approved

#10117 Add multiple /entry page options
  app/controllers/application_controller.rb
  app/views/articles/_sidebar_additional.html.erb
  app/views/articles/_sidebar_nav.html.erb
  app/views/articles/tag_index.html.erb
  app/views/devise/registrations/_registration_form.html.erb
  app/views/devise/registrations/new.html.erb
  app/views/layouts/_footer.html.erb
  app/views/layouts/_nav_menu.html.erb
  app/views/layouts/_signup_modal.html.erb
  app/views/layouts/_top_bar.html.erb
  app/views/pages/badges.html.erb
  app/views/partnerships/show.html.erb
  app/views/shared/authentication/_providers_sidebar.html.erb
  app/views/shared/authentication/_providers_signup_modal.html.erb
  app/views/stories/_sign_in_invitation.html.erb
Labels: PR: partially-approved

#10127 Signup modal fix
  app/views/layouts/_signup_modal.html.erb
Labels: PR: partially-approved, area: auth, tech: html/css

#10126 Add unique index on articles slug user_id
  app/models/article.rb
  db/migrate/20200901084210_add_unique_index_to_articles_slug_user_id.rb
  db/schema.rb
Labels: PR: reviewed-approved

#10139 Remove ghostify from app
  app/controllers/admin/users_controller.rb
  app/controllers/users_controller.rb
  app/models/user.rb
  app/services/moderator/delete_user.rb
  app/views/admin/users/edit.html.erb
  app/views/users/_account.html.erb
  spec/requests/admin/users_manage_spec.rb
  spec/requests/user/user_settings_spec.rb
  spec/services/moderator/delete_user_spec.rb
Labels: PR: partially-approved

#10131 Rely on error types to determine when a repo should be removed on the RepoSyncWorker
  app/services/github/errors.rb
  app/workers/github_repos/repo_sync_worker.rb
  spec/services/github/oauth_client_spec.rb
  spec/workers/github_repos/repo_sync_worker_spec.rb
Labels: PR: reviewed-approved

#10143 Optimization:Throttle Noisy Honeycomb Events More
  app/lib/honeycomb/noise_cancelling_sampler.rb
  spec/lib/honeycomb/noise_cancelling_sampler_spec.rb
Labels: PR: partially-approved

#10148 Fix Flaky Runkit system spec
  spec/system/articles/user_creates_an_article_spec.rb
Labels: PR: partially-approved

#10146 Flaky Spec Fix:(Attempt)Ensure Article Suggester Count is Consistent
  spec/labor/article_suggester_spec.rb
Labels: PR: reviewed-approved

#10144 Add initial content security policy into codebase (to avoid reliance on edge configuration)
  config/initializers/content_security_policy.rb
Labels: PR: unreviewed

#10119 Add data update script for profile fields
  app/services/profile_fields/import_from_csv.rb
  lib/data_update_scripts/20200901040521_create_profile_fields.rb
  spec/lib/data_update_scripts/create_profile_fields_spec.rb
Labels: PR: partially-approved

#10133 Profile Admin updates
  app/assets/stylesheets/admin.scss
  app/controllers/admin/profile_field_groups_controller.rb
  app/controllers/admin/profile_fields_controller.rb
  app/views/admin/profile_fields/_add_group_modal.html.erb
  app/views/admin/profile_fields/_add_profile_field_modal.html.erb
  app/views/admin/profile_fields/_edit_group_modal.html.erb
  app/views/admin/profile_fields/_group_form.erb
  app/views/admin/profile_fields/_grouped_profile_fields.html.erb
  app/views/admin/profile_fields/_profile_field_form.html.erb
  app/views/admin/profile_fields/_ungrouped_profile_fields.html.erb
  app/views/admin/profile_fields/index.html.erb
  config/routes.rb
  spec/requests/admin/profile_field_groups_spec.rb
Labels: PR: partially-approved

#10159 Hide overflow text
  app/assets/stylesheets/notifications.scss
Labels: PR: reviewed-approved

#10152 Attempt to fix facebook login
  config/initializers/devise.rb
Labels: PR: partially-approved

#10153 Extracts DisplayAds from Administrate into admin
  app/controllers/admin/application_controller.rb
  app/controllers/admin/display_ads_controller.rb
  app/dashboards/dashboard_manifest.rb
  app/lib/constants/role.rb
  app/models/display_ad.rb
  app/views/admin/display_ads/_form.html.erb
  app/views/admin/display_ads/edit.html.erb
  app/views/admin/display_ads/index.html.erb
  app/views/admin/display_ads/new.html.erb
  config/routes.rb
  spec/requests/admin/display_ads_spec.rb
Labels: PR: unreviewed

#10147 Optimization:Select Article Columns for Digest Email, Limit 6, Use User Attributes
  app/mailers/digest_mailer.rb
  app/services/email_digest_article_collector.rb
  app/views/mailers/digest_mailer/digest_email.html.erb
  app/workers/emails/send_user_digest_worker.rb
  spec/services/email_digest_article_collector_spec.rb
  spec/workers/emails/send_user_digest_worker_spec.rb
Labels: PR: partially-approved

#10142 Index Reaction created_at Timestamp
  app/serializers/search/reaction_serializer.rb
  config/elasticsearch/mappings/reactions.json
  lib/data_update_scripts/20200415200651_index_reading_list_reactions.rb
  lib/data_update_scripts/20200901194251_reindex_reading_list_reactions.rb
  spec/lib/data_update_scripts/reindex_reading_list_reactions_spec.rb
  spec/serializers/search/reaction_serializer_spec.rb
Labels: PR: partially-approved

#10168 Remove unneeded eager load
  app/labor/sticky_article_collection.rb
  app/views/articles/_sticky_nav.html.erb
Labels: PR: partially-approved

#10038 [Admin Tooling] Allow admins unpublish articles from the Mod Actions Panel
  app/assets/stylesheets/moderators.scss
  app/controllers/articles_controller.rb
  app/javascript/actionsPanel/actionsPanel.js
  app/policies/article_policy.rb
  app/views/moderations/actions_panel.html.erb
  config/routes.rb
  spec/policies/article_policy_spec.rb
  spec/requests/articles/articles_admin_unpublish_spec.rb
Labels: PR: partially-approved

#10158 Add display_area & show_in_onboarding to the profile setup ui
  app/controllers/admin/profile_fields_controller.rb
  app/views/admin/profile_fields/_grouped_profile_fields.html.erb
  app/views/admin/profile_fields/_profile_field_form.html.erb
  app/views/admin/profile_fields/index.html.erb
Labels: PR: unreviewed

#10162 Fixing broken jest test
  app/javascript/modCenter/singleArticle/__tests__/singleArticle.test.jsx
Labels: PR: reviewed-approved

#10179 Revert removal of unneeded eager load (if needed)
  app/labor/sticky_article_collection.rb
  app/views/articles/_sticky_nav.html.erb
Labels: PR: unreviewed

#10124 Add ProfileFieldGroupsController to API
  app/controllers/profile_field_groups_controller.rb
  app/models/profile_field_group.rb
  app/views/profile_field_groups/index.json.jbuilder
  config/routes.rb
  spec/factories/profile_fields.rb
  spec/models/profile_field_group_spec.rb
  spec/requests/profile_field_groups_request_spec.rb
Labels: PR: partially-approved

#10183 Vertical alignment of post title in notification
  app/assets/stylesheets/notifications.scss
Labels: PR: reviewed-approved

#9912 Add Profiles::Update service object
  app/models/profile.rb
  app/models/user.rb
  app/services/profile_fields/add.rb
  app/services/profile_fields/remove.rb
  app/services/profiles/extract_data.rb
  app/services/profiles/update.rb
  spec/models/profile_spec.rb
  spec/models/user_spec.rb
  spec/requests/admin/profile_fields_spec.rb
  spec/services/profile_fields/remove_spec.rb
  spec/services/profiles/update_spec.rb
Labels: PR: reviewed-approved

#10184 Fixed new redirects
  app/views/service_worker/index.js.erb
Labels: PR: reviewed-approved

#10170 Fixes a duplicate page title on the /videos page
  app/views/videos/index.html.erb
  spec/system/videos/user_visits_videos_spec.rb
Labels: PR: partially-approved

#10169 Session cookie domain hotfix for login and logout
  app/controllers/omniauth_callbacks_controller.rb
  app/controllers/sessions_controller.rb
Labels: PR: partially-approved

#10185 New Profile Header
  app/assets/images/behance.svg
  app/assets/images/cake.svg
  app/assets/images/dribbble.svg
  app/assets/images/email.svg
  app/assets/images/external.svg
  app/assets/images/gitlab.svg
  app/assets/images/linkedin.svg
  app/assets/images/location.svg
  app/assets/images/mastodon.svg
  app/assets/images/medium.svg
  app/assets/images/stackoverflow.svg
  app/assets/images/youtube.svg
  app/assets/javascripts/initializers/initializeAllChatButtons.js
  app/assets/javascripts/initializers/initializeUserProfilePage.js
  app/assets/stylesheets/crayons.scss
  app/assets/stylesheets/views/profile.scss
  app/views/users/_metadata.html.erb
  app/views/users/show.html.erb
  spec/system/user/view_user_index_spec.rb
Labels: Crayons, PR: partially-approved, PR: unreviewed, area: profile

#10156 Extending documentation...
  app/javascript/article-form/components/Title.jsx
  docs/faqs.md
Labels: PR: partially-approved, area: documentation

#10187 Adds ability to create new sponsorships from admin dashboard
  app/controllers/admin/sponsorships_controller.rb
  app/views/admin/sponsorships/index.html.erb
  app/views/admin/sponsorships/new.html.erb
  config/routes.rb
  spec/requests/admin/sponsorships_spec.rb
Labels: PR: partially-approved

#10155 Enable CSP in report only mode and use Honeybadger to track violations
  config/initializers/content_security_policy.rb
Labels: PR: partially-approved

#10175 Optimization:Add Index for User ID and Mailer to Ahoy Messages
  db/migrate/20200902204028_add_user_id_mailer_index_to_ahoy_messages.rb
  db/schema.rb
Labels: PR: partially-approved

#10189 Add sponsorships to seed data
  db/seeds.rb
Labels: PR: reviewed-approved

#10191 Revert "[deploy] Enable CSP in report only mode and use Honeybadger t…
  config/initializers/content_security_policy.rb
Labels: PR: unreviewed

#10058 Add Recent Reports to Users' Admin User Page
  app/controllers/admin/users_controller.rb
  app/models/feedback_message.rb
  app/views/admin/users/_reports.html.erb
  app/views/admin/users/edit.html.erb
Labels: PR: partially-approved

#10192 Bug Fix:Comment out content security policy
  config/initializers/content_security_policy.rb
Labels: PR: partially-approved

#10171 Bug Fix:Sort Reactions by created_at
  app/services/search/query_builders/reaction.rb
  spec/services/search/reaction_spec.rb
Labels: PR: reviewed-approved

#10190 Move deletion of legacy cookie higher in omniauth callback
  app/controllers/omniauth_callbacks_controller.rb
  app/controllers/sessions_controller.rb
Labels: PR: partially-approved

#10194 Optimization:Select Only Necessary Columns from Ahoy Messages For Digest Emails
  app/services/email_digest_article_collector.rb
Labels: PR: partially-approved

#10157 Strip HTML from following list tags short_summary
  app/views/dashboards/following_tags.html.erb
Labels: PR: partially-approved

#10193 Add routes for i18n
  config/routes.rb
  docs/backend/internationalization.md
  docs/backend/readme.md
  spec/routing/all_routes_spec.rb
  spec/routing/i18n_routes_spec.rb
Labels: PR: partially-approved

#10197 Optimization:Limit Column Select for Sticky Nav Articles
  app/labor/sticky_article_collection.rb
Labels: PR: reviewed-approved

#10198 Don't include locale in service workers
  app/views/service_worker/index.js.erb
Labels: PR: reviewed-approved

#10196 Update nav menu in Notification to use crayons-link styling
  app/assets/stylesheets/notifications.scss
  app/views/notifications/_nav_menu.html.erb
  app/views/notifications/_nav_menu_filter.html.erb
  app/views/notifications/index.html.erb
Labels: Crayons, Forem team, PR: partially-approved, PR: unreviewed, area: notifications, tech: html/css

#10181 Add profiles controller
  app/controllers/profiles_controller.rb
  config/routes.rb
  spec/requests/profiles_request_spec.rb
Labels: PR: reviewed-approved

#10150 Add ga tracking to config
  app/controllers/admin/configs_controller.rb
  app/controllers/ga_events_controller.rb
  app/lib/constants/site_config.rb
  app/models/site_config.rb
  app/views/admin/configs/show.html.erb
  app/views/pages/badge.html.erb
  app/views/shell/_top.html.erb
  config/sample_application.yml
  spec/requests/admin/configs_spec.rb
  spec/requests/stories_index_spec.rb
Labels: PR: unreviewed

#10041 Add OAuth callback configuration to facebook docs
  docs/backend/auth-facebook.md
Labels: PR: partially-approved

#10207 Update JS sub-dependencies
  package.json
  yarn.lock
Labels: PR: reviewed-approved

#10205 Remove draft articles with duplicate feed source URL and cleanup invalid data
  lib/data_update_scripts/20200904132553_remove_draft_articles_with_duplicate_feed_source_url.rb
  lib/data_update_scripts/20200904141057_cleanup_articles_with_invalid_feed_source_url.rb
  spec/lib/data_update_scripts/cleanup_articles_with_invalid_feed_source_url_spec.rb
  spec/lib/data_update_scripts/remove_draft_articles_with_duplicate_feed_source_url_spec.rb
Labels: PR: unreviewed

#10209 Revert "Remove draft articles with duplicate feed source URL and cleanup invalid data"
  lib/data_update_scripts/20200904132553_remove_draft_articles_with_duplicate_feed_source_url.rb
  lib/data_update_scripts/20200904141057_cleanup_articles_with_invalid_feed_source_url.rb
  spec/lib/data_update_scripts/cleanup_articles_with_invalid_feed_source_url_spec.rb
  spec/lib/data_update_scripts/remove_draft_articles_with_duplicate_feed_source_url_spec.rb
Labels: PR: partially-approved

#10145 Drag and drop an image in the editor
  app/javascript/article-form/actions.js
  app/javascript/article-form/components/ArticleCoverImage.jsx
  app/javascript/article-form/components/EditorBody.jsx
  app/javascript/article-form/components/Help.jsx
  app/javascript/article-form/components/__tests__/ArticleCoverImage.test.jsx
  app/javascript/article-form/components/__tests__/dragAndDropHelpers.test.js
  app/javascript/article-form/components/dragAndDropHelpers.js
  app/javascript/chat/chat.jsx
  app/javascript/packs/articleForm.jsx
  app/javascript/utilities/__tests__/dragAndDrop.test.js
  app/javascript/utilities/dragAndDrop.js
  app/javascript/utilities/dragAndUpload.js
  package.json
  yarn.lock
Labels: PR: partially-approved, area: publishing experience, javascript, tech: html/css

#10195 Install and enable jemalloc to help improve memory usage in Ruby.
  Containerfile
Labels: PR: reviewed-approved

#10138 Remove draft articles with a duplicate canonical_url
  lib/data_update_scripts/20200901085230_remove_draft_articles_with_duplicate_canonical_url.rb
Labels: PR: unreviewed

#10161 Add unique index on articles canonical_url
  app/models/article.rb
  db/migrate/20200902132326_add_unique_index_to_articles_canonical_url.rb
  db/schema.rb
  spec/models/article_spec.rb
Labels: PR: partially-approved

#10211 Remove all attempts to delete cookies
  app/controllers/omniauth_callbacks_controller.rb
  app/controllers/sessions_controller.rb
  config/routes.rb
Labels: PR: reviewed-approved

#10235 Fix DataUpdateScripts::CreateProfileFields spec
  spec/lib/data_update_scripts/create_profile_fields_spec.rb
Labels: PR: reviewed-approved

#10242 Fix profile admin spec
  spec/requests/admin/profile_field_groups_spec.rb
Labels: PR: partially-approved

#10237 Routine rubocop fixes
  .rubocop.yml
  .rubocop_todo.yml
  app/controllers/api/v0/listings_controller.rb
  app/controllers/listings_controller.rb
  app/helpers/application_helper.rb
  app/labor/markdown_parser.rb
  app/liquid_tags/katex_tag.rb
  app/models/comment.rb
  app/models/notification.rb
  app/services/search/query_builders/chat_channel_membership.rb
  app/services/slack/messengers/feedback.rb
  app/services/suggester/users/sidebar.rb
  app/views/api/v0/podcast_episodes/show.json.jbuilder
  config/environments/development.rb
  lib/data_update_scripts/20200810083831_remove_orphaned_ahoy_rows.rb
  lib/data_update_scripts/20200813072205_remove_orphaned_display_ad_events.rb
  lib/data_update_scripts/20200818103028_nullify_orphaned_by_article_html_variant_trials.rb
  lib/data_update_scripts/20200818170410_remove_orphaned_poll_votes.rb
  lib/data_update_scripts/20200818170433_remove_orphaned_poll_skips.rb
  lib/data_update_scripts/20200818170505_remove_orphaned_poll_options.rb
  lib/data_update_scripts/20200818170523_remove_orphaned_polls.rb
  lib/data_update_scripts/20200821103125_nullify_orphaned_articles_by_organization.rb
  lib/data_update_scripts/20200821103305_nullify_orphaned_collections_by_organization.rb
  lib/data_update_scripts/20200821103405_remove_orphaned_credits_by_organization.rb
  lib/data_update_scripts/20200821103718_remove_orphaned_display_ads_by_organization.rb
  lib/data_update_scripts/20200821103834_remove_orphaned_listings_by_organization.rb
  lib/data_update_scripts/20200822082229_remove_orphaned_notifications_by_organization.rb
  lib/data_update_scripts/20200822083050_remove_orphaned_sponsorships_by_organization.rb
  lib/data_update_scripts/20200825095213_remove_orphaned_buffer_updates_by_article.rb
  lib/data_update_scripts/20200825095512_nullify_orphaned_comments_by_article.rb
  lib/data_update_scripts/20200825102635_remove_orphaned_notification_subscriptions_by_article.rb
  lib/data_update_scripts/20200825102956_remove_orphaned_notifications_by_article.rb
  lib/data_update_scripts/20200825103119_remove_orphaned_profile_pins_by_article.rb
  lib/data_update_scripts/20200825103244_remove_orphaned_rating_votes_by_article.rb
  lib/data_update_scripts/20200826092816_remove_orphaned_notes_by_user.rb
  lib/data_update_scripts/20200826133748_nullify_orphaned_tweets_by_user.rb
  lib/data_update_scripts/20200826140317_remove_orphaned_articles_by_user.rb
  lib/data_update_scripts/20200826140754_remove_orphaned_collections_by_user.rb
  lib/data_update_scripts/20200826140924_remove_orphaned_credits_by_user.rb
  lib/data_update_scripts/20200826141015_remove_orphaned_github_repos_by_user.rb
  lib/data_update_scripts/20200826141105_remove_orphaned_mentions_by_user.rb
  lib/data_update_scripts/20200826141145_remove_orphaned_organization_memberships_by_user.rb
  lib/data_update_scripts/20200826141447_nullify_orphaned_page_views_by_user.rb
  lib/data_update_scripts/20200826141550_nullify_orphaned_rating_votes_by_user.rb
  lib/data_update_scripts/20200826141652_remove_orphaned_reactions_by_user.rb
  lib/data_update_scripts/20200901085230_remove_draft_articles_with_duplicate_canonical_url.rb
  spec/black_box/black_box_spec.rb
  spec/labor/mailchimp_bot_spec.rb
  spec/labor/markdown_parser_spec.rb
  spec/models/profile_field_group_spec.rb
  spec/requests/admin/configs_spec.rb
  spec/requests/github_repos_spec.rb
  spec/requests/pages_spec.rb
  spec/requests/profile_field_groups_request_spec.rb
  spec/services/bulk_sql_delete_spec.rb
  spec/support/sidekiq_test_helpers.rb
Labels: PR: partially-approved

#10241 Add LiquidTagsController
  app/controllers/liquid_tags_controller.rb
  config/routes.rb
  spec/requests/liquid_tags_request_spec.rb
Labels: PR: partially-approved

#10239 Remove draft articles with duplicate feed source URL and cleanup invalid data: take 2
  lib/data_update_scripts/20200904132553_remove_draft_articles_with_duplicate_feed_source_url.rb
  lib/data_update_scripts/20200904141057_cleanup_articles_with_invalid_feed_source_url.rb
  spec/lib/data_update_scripts/cleanup_articles_with_invalid_feed_source_url_spec.rb
Labels: PR: partially-approved

#10251 Feature:Add ENV to Skip Fastly Config Update
  lib/tasks/fastly.rake
Labels: PR: reviewed-approved

#10208 Add unique index on articles feed_source_url
  app/models/article.rb
  db/migrate/20200904151734_add_unique_index_to_articles_feed_source_url.rb
  db/schema.rb
  spec/models/article_spec.rb
Labels: PR: unreviewed

#10254 Fixed issue with drag and drop image for cover image in editor in Safari
  app/javascript/article-form/components/ArticleCoverImage.jsx
  app/javascript/article-form/components/__tests__/ArticleCoverImage.test.jsx
Labels: PR: partially-approved, area: publishing experience, javascript

#10253 Bug Fix:Fix Data Update feed_source_url Script
  lib/data_update_scripts/20200904132553_remove_draft_articles_with_duplicate_feed_source_url.rb
Labels: PR: partially-approved

#10247 Fixing id and class of non featured article
  app/javascript/articles/Article.jsx
  spec/system/articles/user_visits_articles_by_timeframe_spec.rb
Labels: PR: partially-approved

#10255 Refactor:Remove Unused Figaro Gem and Temp Rake Task
  Gemfile
  Gemfile.lock
  bin/setup
  config/sample_application.yml
  lib/tasks/temporary/env_variables.rake
  vendor/cache/figaro-1.2.0.gem
Labels: PR: partially-approved

#10244 Using global util function for displaying date in listing dashboard
  app/assets/javascripts/utilities/localDateTime.js
  app/javascript/listings/__tests__/ListingDashboard.test.jsx
  app/javascript/listings/dashboard/rowElements/listingDate.jsx
  app/javascript/shared/components/__tests__/dateTime.test.jsx
  app/javascript/shared/components/dateTime.jsx
Labels: PR: partially-approved

#10203 Drop containers styling
  app/assets/stylesheets/views/article-form.scss
  app/javascript/article-form/components/EditorBody.jsx
  app/javascript/article-form/components/Meta.jsx
  app/javascript/article-form/components/__tests__/dragAndDropHelpers.test.js
  app/javascript/article-form/components/dragAndDropHelpers.js
  app/views/shell/_top.html.erb
Labels: PR: unreviewed, area: image uploading, area: publishing experience, tech: html/css

#10256 Article refactoring
  app/models/article.rb
Labels: PR: partially-approved

#10202 Add custom profile fields
  app/models/concerns/acts_as_profile_field.rb
  app/models/custom_profile_field.rb
  app/models/profile.rb
  app/models/profile_field.rb
  app/services/profiles/update.rb
  db/migrate/20200904040009_create_custom_profile_fields.rb
  db/schema.rb
  spec/factories/custom_profile_fields.rb
  spec/models/custom_profile_field_spec.rb
  spec/models/profile_field_spec.rb
  spec/models/shared_examples/a_profile_field.rb
  spec/services/profiles/update_spec.rb
Labels: PR: partially-approved

#10259 Actions bar overlapping footer
  app/assets/stylesheets/footer.scss
Labels: PR: partially-approved, tech: html/css

#10252 Give Admins the Ability to Add Co-Authors to Posts
  app/controllers/admin/articles_controller.rb
  app/models/article.rb
  app/views/admin/articles/_individual_article.html.erb
  spec/requests/admin/articles_spec.rb
Labels: PR: partially-approved

#10266 Bump Rails to 6.0.3.3
  Gemfile.lock
  vendor/cache/actioncable-6.0.3.2.gem
  vendor/cache/actioncable-6.0.3.3.gem
  vendor/cache/actionmailbox-6.0.3.2.gem
  vendor/cache/actionmailbox-6.0.3.3.gem
  vendor/cache/actionmailer-6.0.3.2.gem
  vendor/cache/actionmailer-6.0.3.3.gem
  vendor/cache/actionpack-6.0.3.2.gem
  vendor/cache/actionpack-6.0.3.3.gem
  vendor/cache/actiontext-6.0.3.2.gem
  vendor/cache/actiontext-6.0.3.3.gem
  vendor/cache/actionview-6.0.3.2.gem
  vendor/cache/actionview-6.0.3.3.gem
  vendor/cache/activejob-6.0.3.2.gem
  vendor/cache/activejob-6.0.3.3.gem
  vendor/cache/activemodel-6.0.3.2.gem
  vendor/cache/activemodel-6.0.3.3.gem
  vendor/cache/activerecord-6.0.3.2.gem
  vendor/cache/activerecord-6.0.3.3.gem
  vendor/cache/activestorage-6.0.3.2.gem
  vendor/cache/activestorage-6.0.3.3.gem
  vendor/cache/activesupport-6.0.3.2.gem
  vendor/cache/activesupport-6.0.3.3.gem
  vendor/cache/loofah-2.6.0.gem
  vendor/cache/loofah-2.7.0.gem
  vendor/cache/nio4r-2.5.2.gem
  vendor/cache/nio4r-2.5.3.gem
  vendor/cache/rails-6.0.3.2.gem
  vendor/cache/rails-6.0.3.3.gem
  vendor/cache/railties-6.0.3.2.gem
  vendor/cache/railties-6.0.3.3.gem
  vendor/cache/websocket-driver-0.7.2.gem
  vendor/cache/websocket-driver-0.7.3.gem
Labels: PR: partially-approved

#10199 Include locale in fragment cache key
  app/helpers/application_helper.rb
  spec/helpers/application_helper_spec.rb
Labels: PR: unreviewed

#10215 Optimization:Increase refresh_interval For Possible High Indexing Indexes
  app/services/search/base.rb
  app/services/search/cluster.rb
  app/services/search/feed_content.rb
  app/services/search/reaction.rb
  app/services/search/user.rb
  spec/services/search/base_spec.rb
  spec/services/search/cluster_spec.rb
Labels: PR: partially-approved

#10262 Fetch GA Tracking ID from SiteConfig
  app/assets/javascripts/initializers/initializeBaseTracking.js.erb
Labels: PR: unreviewed

#10267 Proper cache delete_matched
  app/controllers/admin/configs_controller.rb
  spec/requests/admin/configs_spec.rb
Labels: PR: partially-approved

#10243 [Documentation] Improvements to Windows installation & startup docs
  docs/getting-started/start-app.md
  docs/installation/windows.md
Labels: PR: reviewed-approved

#10270 Move mailchimp API key to app logic
  app/controllers/admin/configs_controller.rb
  app/labor/mailchimp_bot.rb
  app/lib/constants/site_config.rb
  app/models/site_config.rb
  config/initializers/gibbon.rb
  spec/requests/admin/configs_spec.rb
Labels: PR: partially-approved

#10277 Bug Fix:Update Text Request Email with confirm_delete Link
  app/views/mailers/notify_mailer/account_deletion_requested_email.text.erb
Labels: PR: reviewed-approved

#10279 Bug Fix:Add New Migration to Remove Active from Profile Fields
  db/migrate/20200910205316_remove_active_from_profile_fields2.rb
  db/schema.rb
Labels: PR: partially-approved

#10276 Create codeql-analysis.yml again
  .github/workflows/codeql-analysis.yml
Labels: PR: partially-approved

#10206 Enable admin-configured app_domain
  app/controllers/admin/feedback_messages_controller.rb
  app/controllers/admin/tools_controller.rb
  app/controllers/application_controller.rb
  app/controllers/async_info_controller.rb
  app/controllers/buffered_articles_controller.rb
  app/decorators/article_decorator.rb
  app/labor/cache_buster.rb
  app/labor/markdown_parser.rb
  app/lib/redcarpet/render/html_rouge.rb
  app/lib/url.rb
  app/middlewares/set_cookie_domain.rb
  app/models/message.rb
  app/models/site_config.rb
  app/services/streams/twitch_webhook/register.rb
  app/view_objects/articles/social_image.rb
  app/views/service_worker/manifest.json.erb
  app/views/shell/_top.html.erb
  app/views/users/_profile.html.erb
  config/application.rb
  config/environments/production.rb
  config/initializers/carrierwave_monkeypatch.rb
  config/initializers/devise_monkeypatch.rb
  config/sitemap.rb
  spec/decorators/article_decorator_spec.rb
  spec/helpers/application_helper_spec.rb
  spec/helpers/social_image_helper_spec.rb
  spec/lib/url_spec.rb
  spec/requests/async_info_spec.rb
  spec/requests/stories_index_spec.rb
Labels: PR: unreviewed

#10289 Feature:Allow for Search by ID for FeedContent
  app/controllers/search_controller.rb
  app/services/search/query_builders/feed_content.rb
  spec/services/search/feed_content_spec.rb
Labels: PR: partially-approved

#10287 Check that nginx is available before pinging it
  app/labor/cache_buster.rb
  spec/labor/cache_buster_spec.rb
Labels: PR: partially-approved

#10292 Refactor:Remove unused ReadingList Labor methods
  app/labor/reading_list.rb
  spec/labor/reading_list_spec.rb
Labels: PR: partially-approved

#10296 Fix URL.domain in development by correctly loading authentication providers
  app/services/authentication/providers.rb
  config/application.rb
  config/initializers/authentication.rb
Labels: PR: partially-approved

#10268 Move video_duration_in_minutes_integer to serializer
  app/models/article.rb
  app/serializers/search/article_serializer.rb
  lib/data_update_scripts/20200911045602_reindex_articles_with_videos.rb
  spec/serializers/search/article_serializer_spec.rb
Labels: PR: reviewed-approved

#10264 Removing duplicate date formatting for listing expiry date in listing dashboard
  app/javascript/listings/dashboard/listingRow.jsx
Labels: PR: partially-approved

#10312 Hide active broadcasts from /connect routes
  app/assets/javascripts/initializers/initializeBroadcast.js
  app/javascript/packs/articleForm.jsx
Labels: PR: partially-approved

#10310 Fix SiteConfig's default option of authentication_providers field
  app/models/site_config.rb
Labels: PR: reviewed-approved

#10273 Cleanup articles with duplicate user_id, title and body_markdown
  lib/data_update_scripts/20200910135958_remove_draft_articles_with_duplicate_user_id_title_body_markdown.rb
  lib/data_update_scripts/20200910140109_cleanup_published_articles_with_duplicate_user_id_title_body_markdown.rb
Labels: PR: partially-approved

#10314 Stop pinging sitemap tools locally
  app/models/site_config.rb
  app/workers/sitemap_refresh_worker.rb
  spec/models/site_config_spec.rb
  spec/workers/sitemap_refresh_worker_spec.rb
Labels: PR: partially-approved

#10284 Add unique index on articles user_id, title and body_markdown
  .rubocop_todo.yml
  db/migrate/20200911140318_add_unique_index_to_articles_user_id_title_body_markdown.rb
  db/schema.rb
  spec/models/article_spec.rb
Labels: PR: partially-approved

#10325 Optimization:Only Enqueue UpdateMainImageBackgroundHexWorker If Main Image Changes
  app/models/article.rb
  spec/models/article_spec.rb
Labels: PR: reviewed-approved

#10322 Refactor:Remove ReadingList Labor Class, Replace with user Method
  app/controllers/async_info_controller.rb
  app/labor/reading_list.rb
  app/models/user.rb
  spec/labor/reading_list_spec.rb
  spec/models/user_spec.rb
Labels: PR: unreviewed

#10327 Flaky Spec Fix:Set Expired Listing to 2 days ago
  spec/workers/listings/expire_old_listings_worker_spec.rb
Labels: PR: reviewed-approved

#10329 Flaky Spec Fix:Ensure Page View Domains are Unique for Analytics Serv…
  spec/services/analytics_service_spec.rb
Labels: PR: reviewed-approved

#10323 Adds runtime copy to clipboard
  app/assets/javascripts/initializers/initializeCommentDropdown.js
  app/assets/javascripts/initializers/runtime.js
  app/javascript/article-form/components/ImageUploader.jsx
  app/javascript/chat/ChatChannelSettings/MembershipManager/InvitationLinkManager.jsx
Labels: PR: partially-approved

#10330 Flaky Spec Fix:Ensure We Fill In Article Content Successfully with More Targeted tag
  spec/system/user_uses_the_editor_spec.rb
Labels: PR: reviewed-approved

#10332 Optimization:Use delete_by when Destroying HtmlVariant Trials and Successes
  app/workers/html_variants/remove_old_data_worker.rb
Labels: PR: partially-approved

#10326 Fixing links to tracking section in docs
  docs/backend/tracking.md
  docs/frontend/tracking.md
Labels: PR: partially-approved

#10320 Adding note about branch naming
  docs/getting-started/branching.md
Labels: PR: partially-approved

#10344 Optimization:Use Locally Bundled Gems in Containers
  scripts/bundle.sh
Labels: PR: partially-approved

#10331 Optimization:Store Podcast Ep Data in Redis, Rather than Sending as Sidekiq Argument
  app/services/podcasts/get_episode.rb
  app/workers/podcast_episodes/create_worker.rb
  spec/services/podcasts/feed_spec.rb
  spec/services/podcasts/get_episode_spec.rb
  spec/workers/podcast_episodes/create_worker_spec.rb
Labels: PR: partially-approved

#10350 Bug Fix/Optimization:Remove HttpCache from Github OauthClient
  app/services/github/oauth_client.rb
Labels: PR: reviewed-approved

#10321 Add missing foreign keys to ahoy_messages and articles
  app/models/article.rb
  app/models/email_message.rb
  app/models/feedback_message.rb
  db/migrate/20200914143753_add_missing_foreign_keys_to_ahoy_messages.rb
  db/migrate/20200914144033_validate_add_missing_foreign_keys_to_ahoy_messages.rb
  db/migrate/20200914144157_add_missing_foreign_keys_to_articles.rb
  db/migrate/20200914145500_validate_add_missing_foreign_keys_to_articles.rb
  db/schema.rb
  spec/factories/email_messages.rb
  spec/models/article_spec.rb
  spec/models/email_message_spec.rb
  spec/models/feedback_message_spec.rb
  spec/requests/admin/articles_spec.rb
  spec/services/users/delete_spec.rb
Labels: PR: unreviewed

#10349 Remove need for ENV vars during asset precompile
  app/assets/config/manifest.js
  app/assets/javascripts/base.js.erb
  app/assets/javascripts/initializers/initializeCommentsPage.js.erb
  app/assets/javascripts/utilities/buildCommentFormHTML.js.erb
  app/assets/javascripts/utilities/buildCommentHTML.js.erb
  app/controllers/open_search_controller.rb
  app/views/layouts/admin.html.erb
  app/views/open_search/show.xml.erb
  app/views/shell/_top.html.erb
  config/environments/production.rb
  config/initializers/hypershield.rb
  config/routes.rb
  spec/requests/open_search_spec.rb
Labels: PR: reviewed-approved

#10347 Update search menu to use Crayons styling, v2
  app/assets/javascripts/utilities/buildArticleHTML.js
  app/assets/stylesheets/widgets.scss
  app/views/articles/_search.html.erb
  app/views/articles/search.html.erb
  app/views/articles/search/_nav_menu.html.erb
  app/views/articles/search/_sidebar.html.erb
  app/views/articles/search/_sidebar_additional.html.erb
Labels: PR: partially-approved

#10346 Code snippets text wrapping fix
  app/assets/stylesheets/syntax.scss
Labels: PR: partially-approved, tech: html/css

#10313 Changes to profile field indexing
  app/models/user.rb
  app/serializers/search/user_serializer.rb
  config/elasticsearch/mappings/users.json
  lib/data_update_scripts/20200519142908_re_index_feed_content_and_users_to_elasticsearch.rb
  lib/data_update_scripts/20200914042434_reindex_users_for_profiles.rb
  spec/lib/data_update_scripts/re_index_feed_content_and_users_to_elasticsearch_spec.rb
  spec/serializers/search/user_serializer_spec.rb
Labels: PR: partially-approved

#10280 Better production container precompiling and bootstrapping
  Containerfile
  container-compose.yml
  docker-compose.yml
  scripts/entrypoint-dev.sh
  scripts/entrypoint.sh
Labels: PR: partially-approved, area: containers, area: systems

#10295 Fix broken links to admin guide in documentation
  docs/backend/configuration.md
Labels: PR: reviewed-approved

#10359 Bug Fix:Make entrypoint-dev.sh Runnable
  scripts/entrypoint-dev.sh
Labels: PR: partially-approved

#10364 Hide column backup_data.json_data from Blazer via Hypershield
  config/initializers/hypershield.rb
Labels: PR: partially-approved

#10290 Remove exceeded line
  app/controllers/chat_channel_memberships_controller.rb
Labels: PR: partially-approved

#10294 Feature: Serve Reading List from FeedContent Index
  app/controllers/search_controller.rb
  app/javascript/readingList/__tests__/readingList.test.jsx
  app/javascript/readingList/components/ItemListItem.jsx
  app/javascript/readingList/components/__tests__/ItemListItem.test.jsx
  app/javascript/searchableItemList/searchableItemList.js
  app/services/search/query_builders/feed_content.rb
  app/services/search/reading_list.rb
  spec/requests/search_spec.rb
  spec/services/search/feed_content_spec.rb
  spec/services/search/reading_list_spec.rb
Labels: PR: partially-approved

#10361 Add opacity to HexComparer
  app/labor/hex_comparer.rb
  spec/labor/hex_comparer_spec.rb
Labels: PR: partially-approved

#10371 add image in podcast seeds in suggested way
  db/seeds.rb
Labels: PR: reviewed-approved

#10375 More detailed notification when setup is not completed
  app/controllers/concerns/verify_setup_completed.rb
  spec/system/admin/admin_manages_configuration_spec.rb
Labels: PR: partially-approved

#10351 Refactor:Remove Unused Faraday Http Cache Gem
  Gemfile
  Gemfile.lock
  vendor/cache/faraday-http-cache-2.2.0.gem
Labels: PR: partially-approved

#10372 Replace need for GitHub ENV vars on bootup
  app/labor/badge_rewarder.rb
  app/liquid_tags/github_tag/github_readme_tag.rb
  app/models/github_issue.rb
  app/services/github/client.rb
  app/services/github/oauth_client.rb
  spec/liquid_tags/github_tag/github_readme_tag_spec.rb
  spec/services/github/client_spec.rb
Labels: PR: partially-approved

#10311 Optimization:Move Initialization CacheBust to Background Worker
  config/initializers/initialization_cachebust.rb
  config/initializers/set_release_footprint.rb
  lib/tasks/app_initializer.rake
  lib/tasks/cache.rake
Labels: PR: partially-approved

#10352 Fix case sensitive published bug for basic markdown posts
  app/labor/markdown_fixer.rb
  spec/labor/markdown_fixer_spec.rb
Labels: PR: partially-approved

#9108 API: Add route for fetching a user's followed tags
  app/controllers/api/v0/follows_controller.rb
  app/views/api/v0/follows/tags.json.jbuilder
  config/routes.rb
  spec/requests/api/v0/follows_spec.rb
Labels: PR: unreviewed

#10369 Refactor edge caching logic to live in EdgeCache::Service
  app/labor/cache_buster.rb
  app/services/edge_cache/bust.rb
  spec/labor/cache_buster_spec.rb
  spec/services/edge_cache/bust_spec.rb
Labels: PR: partially-approved

#10217 Showing date in listing tile
  app/assets/stylesheets/views/listings.scss
  app/controllers/concerns/listings_toolkit.rb
  app/javascript/listings/__tests__/AllListings.test.jsx
  app/javascript/listings/__tests__/Modal.test.jsx
  app/javascript/listings/__tests__/SingleListing.test.jsx
  app/javascript/listings/singleListing/Header.jsx
  app/serializers/search/listing_serializer.rb
  app/views/layouts/admin.html.erb
  app/views/shell/_top.html.erb
  config/elasticsearch/mappings/listings.json
  db/migrate/20200917114525_originally_published_at_for_listing.rb
  db/schema.rb
  db/seeds.rb
  lib/data_update_scripts/20200917115821_backfill_listing_published_date.rb
  spec/requests/listings_spec.rb
Labels: PR: partially-approved

#10382 Fix extra character typo in admin section
  app/views/layouts/admin.html.erb
Labels: PR: reviewed-approved

#10413 Revert "Bump puma from 4.3.6 to 5.0.0"
  Gemfile
  Gemfile.lock
  vendor/cache/nio4r-2.5.3.gem
  vendor/cache/nio4r-2.5.4.gem
  vendor/cache/puma-4.3.6.gem
  vendor/cache/puma-5.0.0.gem
Labels: PR: partially-approved

#10405 Adding missing variable
  app/views/shell/_top.html.erb
Labels: PR: partially-approved

#10411 Improve setup not completed notification
  app/controllers/concerns/verify_setup_completed.rb
  spec/system/admin/admin_manages_configuration_spec.rb
Labels: PR: partially-approved

#10257 Remove profile validations from user
  app/models/user.rb
  spec/models/user_spec.rb
Labels: PR: reviewed-approved

#10378 Bug: auto resize on type message connect
  app/assets/stylesheets/chat.scss
  app/javascript/chat/compose.jsx
Labels: PR: partially-approved

#10401 Better `position: sticky` support
  app/assets/stylesheets/views/article-form.scss
  app/assets/stylesheets/views/article.scss
Labels: PR: partially-approved, tech: html/css

#10400 Softer background for inline-code
  app/assets/stylesheets/syntax.scss
Labels: PR: partially-approved

#10415 Fix the asset precompile in the Container
  Containerfile
Labels: PR: partially-approved, area: containers

#10409 Refactor:Remove BackupData Model and Code
  app/controllers/admin/users_controller.rb
  app/models/backup_data.rb
  app/models/identity.rb
  app/models/user.rb
  app/services/users/delete_activity.rb
  app/views/admin/users/edit.html.erb
  config/routes.rb
  spec/factories/backup_data.rb
  spec/models/backup_data_spec.rb
  spec/models/identity_spec.rb
  spec/models/user_spec.rb
  spec/requests/admin/users_spec.rb
Labels: PR: partially-approved

#10419 Sets Omniauth full_host config to match the environment
  config/initializers/omniauth.rb
  spec/support/omniauth_helpers.rb
  spec/system/authentication/user_logs_in_with_facebook_spec.rb
  spec/system/authentication/user_logs_in_with_github_spec.rb
Labels: PR: partially-approved

#10377 Refactor:Remove Reaction Search Code
  app/models/article.rb
  app/models/reaction.rb
  app/serializers/search/reaction_serializer.rb
  app/services/data_sync/elasticsearch/article.rb
  app/services/data_sync/elasticsearch/tag.rb
  app/services/data_sync/elasticsearch/user.rb
  app/services/search/cluster.rb
  app/services/search/query_builders/reaction.rb
  app/services/search/reaction.rb
  lib/data_update_scripts/20200901194251_reindex_reading_list_reactions.rb
  spec/lib/acts_as_taggable_on/tag_spec.rb
  spec/lib/data_update_scripts/reindex_reading_list_reactions_spec.rb
  spec/models/article_spec.rb
  spec/models/reaction_spec.rb
  spec/models/tag_spec.rb
  spec/serializers/search/reaction_serializer_spec.rb
  spec/services/data_sync/elasticsearch/article_spec.rb
  spec/services/moderator/merge_user_spec.rb
  spec/services/search/query_builders/reaction_spec.rb
  spec/services/search/reaction_spec.rb
  spec/services/users/delete_spec.rb
  spec/workers/search/bulk_index_worker_spec.rb
Labels: PR: reviewed-approved

#10422 Refactor:Remove BackupData Table from Postgres
  config/initializers/hypershield.rb
  db/migrate/20200921160153_remove_backup_data.rb
  db/schema.rb
Labels: PR: partially-approved

#10426 Refactor:Remove Reactions Index
  lib/data_update_scripts/20200923173148_remove_reaction_index.rb
  spec/lib/data_update_scripts/remove_reaction_index_spec.rb
Labels: PR: partially-approved

#10416 Frontend cleanups
  app/assets/javascripts/initializers/initializeDrawerSliders.js
  app/assets/javascripts/initializers/initializeSpecialNavigationFunctionality.js
  app/assets/stylesheets/admin.scss
  app/assets/stylesheets/article-form-needed-legacy.scss
  app/assets/stylesheets/article-show.scss
  app/assets/stylesheets/articles.scss
  app/assets/stylesheets/buttons.scss
  app/assets/stylesheets/comments.scss
  app/assets/stylesheets/components/buttons.scss
  app/assets/stylesheets/components/comments.scss
  app/assets/stylesheets/components/syntax.scss
  app/assets/stylesheets/crayons.scss
  app/assets/stylesheets/leaderboard.scss
  app/assets/stylesheets/minimal.scss
  app/assets/stylesheets/more-articles.scss
  app/assets/stylesheets/scaffolds.scss
  app/assets/stylesheets/settings.scss
  app/assets/stylesheets/social_media.scss
  app/assets/stylesheets/tags.scss
  app/assets/stylesheets/views/dashboard.scss
  app/assets/stylesheets/views/footer.scss
  app/assets/stylesheets/views/top-bar.scss
  app/assets/stylesheets/widgets.scss
  app/javascript/packs/stickySaveFooter.js
  app/views/articles/_bottom_content.html.erb
  app/views/articles/_comments_actions.html.erb
  app/views/articles/_conduct_and_abuse_actions.html.erb
  app/views/articles/_full_comment_area.html.erb
  app/views/articles/_search.html.erb
  app/views/articles/_sidebar_nav.html.erb
  app/views/articles/index.html.erb
  app/views/articles/search.html.erb
  app/views/articles/tag_index.html.erb
  app/views/articles/tags/_sidebar.html.erb
  app/views/comments/index.html.erb
  app/views/layouts/_social_media.html.erb
  app/views/layouts/_styles.html.erb
  app/views/organizations/show.html.erb
  app/views/podcast_episodes/index.html.erb
  app/views/podcast_episodes/show.html.erb
  app/views/podcasts/new.html.erb
  app/views/shell/_top.html.erb
  app/views/stories/_narrow_nav_menu.html.erb
  app/views/users/show.html.erb
  spec/system/user/user_edits_profile_spec.rb
  spec/system/user/user_edits_ux_spec.rb
Labels: Crayons, PR: partially-approved, PR: unreviewed, tech: html/css

#10432 Fixes Omniauth redirect_uri when SiteConfig.app_domain is updated
  config/initializers/omniauth.rb
  spec/system/authentication/omniauth_redirect_uri_spec.rb
Labels: PR: unreviewed

#10430 Bug Fix:Remove Reaction Index By Name
  lib/data_update_scripts/20200923173148_remove_reaction_index.rb
  lib/data_update_scripts/20200924140813_remove_reaction_index_by_name.rb
  spec/lib/data_update_scripts/remove_reaction_index_by_name_spec.rb
  spec/lib/data_update_scripts/remove_reaction_index_spec.rb
Labels: PR: partially-approved

#10435 Bug Fix:Count the Health Checks Controller as Public
  app/controllers/application_controller.rb
Labels: PR: partially-approved

#10436 Feature:Rake Task to Return Health Check Token
  lib/tasks/forem.rake
Labels: PR: partially-approved

#10324 Fix unable to unfollow tags
  app/controllers/async_info_controller.rb
  app/decorators/user_decorator.rb
Labels: PR: partially-approved

#10439 Bug Fix:Remove More ReadingList Index Code
  app/services/users/delete_activity.rb
  app/services/users/delete_articles.rb
Labels: PR: partially-approved
