Repository forem/forem, pull requests merged in 2020-05, with the labels that each got.

#7607 Selects & Ghost Fields
  app/assets/stylesheets/components/forms.scss
  app/views/pages/crayons.html.erb
  app/views/users/_misc.html.erb
Labels: Crayons, PR: partially-approved, PR: unreviewed

#7639 Validate images are files
  app/controllers/concerns/image_uploads.rb
  app/controllers/image_uploads_controller.rb
  app/controllers/organizations_controller.rb
  app/controllers/podcasts_controller.rb
  app/controllers/users_controller.rb
  spec/requests/image_uploads_spec.rb
  spec/requests/organizations_update_spec.rb
  spec/requests/podcasts/podcast_create_spec.rb
  spec/requests/user/user_organization_spec.rb
  spec/requests/user/user_settings_spec.rb
Labels: PR: partially-approved

#7630 Create FastlyConfig & refactor params safe list
  app/errors/fastly_config.rb
  app/services/fastly_config/base.rb
  app/services/fastly_config/snippets.rb
  app/services/fastly_config/update.rb
  app/services/fastly_vcl/safe_params.rb
  config/fastly/safe_params.yml
  config/fastly/snippets/safe_params_list.vcl
  docs/backend/fastly.md
  lib/tasks/fastly.rake
  release-tasks.sh
  spec/services/fastly_config/snippets_spec.rb
  spec/services/fastly_config/update_spec.rb
  spec/services/fastly_vcl/safe_params_spec.rb
  spec/tasks/fastly_spec.rb
Labels: PR: partially-approved

#7644 Update bin/setup's db setup logic
  bin/setup
  db/seeds.rb
Labels: PR: partially-approved

#7648 Remove ClassifiedListing.categories_available.keys in seed
  db/seeds.rb
Labels: PR: reviewed-approved

#7554 Android native audio feature support
  app/assets/javascripts/initializers/initializePodcastPlayback.js
Labels: PR: partially-approved

#7646 Remove Unnecessary .downcases From the Stories::Controller
  app/controllers/stories_controller.rb
  spec/requests/stories_index_spec.rb
Labels: PR: unreviewed

#7650 Add proper 301 status to username change redirects
  app/controllers/stories_controller.rb
  spec/requests/stories_index_spec.rb
  spec/requests/stories_show_spec.rb
Labels: PR: partially-approved

#7647 Update Windows 10 installation docs
  docs/installation/windows.md
Labels: PR: partially-approved

#7636 RateLimit Refactor: Consolidate Logic for Checking a Limit and Raising an Error
  app/controllers/api/v0/api_controller.rb
  app/controllers/application_controller.rb
  app/controllers/comments_controller.rb
  app/controllers/follows_controller.rb
  app/controllers/image_uploads_controller.rb
  app/controllers/organizations_controller.rb
  app/labor/rate_limit_checker.rb
  app/services/articles/creator.rb
  app/services/articles/updater.rb
  spec/labor/rate_limit_checker_spec.rb
  spec/requests/api/v0/articles_spec.rb
  spec/requests/articles/articles_create_spec.rb
  spec/requests/comments_create_spec.rb
  spec/requests/user/user_organization_spec.rb
Labels: PR: partially-approved

#7651 Adds an extra check for Android Native app for playing podcasts
  app/assets/javascripts/initializers/initializePodcastPlayback.js
Labels: PR: partially-approved

#7637 Allow admins to configure default users to follow during onboarding
  app/controllers/internal/configs_controller.rb
  app/controllers/users_controller.rb
  app/models/site_config.rb
  app/views/internal/configs/show.html.erb
  spec/requests/internal/configs_spec.rb
  spec/requests/user/user_suggestions_spec.rb
Labels: PR: unreviewed

#7653 Log RateLimit hits to Datadog for Better Reporting
  app/labor/rate_limit_checker.rb
  app/services/slack/messengers/rate_limit.rb
  spec/labor/rate_limit_checker_spec.rb
  spec/services/slack/messengers/rate_limit_spec.rb
Labels: PR: partially-approved

#7642 Remove column and minor cleanup
  app/controllers/stories_controller.rb
  app/models/classified_listing.rb
  app/views/classified_listings/index.html.erb
  config/routes.rb
  db/migrate/20200501032629_remove_category_from_classified_listing.rb
  db/schema.rb
  db/seeds.rb
  spec/requests/api/v0/classified_listings_spec.rb
Labels: PR: partially-approved

#7662 Clear sponsor cache more frequently
  app/views/articles/_sidebar.html.erb
Labels: PR: reviewed-approved

#7656 Boxes coloring fix
  app/assets/stylesheets/base/boxes.scss
  app/assets/stylesheets/components/banners.scss
  app/assets/stylesheets/components/dropdowns.scss
  app/assets/stylesheets/components/modals.scss
  app/assets/stylesheets/components/notices.scss
  app/assets/stylesheets/components/snackbars.scss
  app/assets/stylesheets/config/_colors.scss
  app/assets/stylesheets/config/_import.scss
  app/assets/stylesheets/crayons.scss
  app/assets/stylesheets/themes/hacker.scss
  app/assets/stylesheets/themes/minimal.scss
  app/assets/stylesheets/themes/night.scss
  app/assets/stylesheets/themes/pink.scss
  app/javascript/crayons/Box/__stories__/box.description.stories.jsx
  app/javascript/crayons/Box/__stories__/box.html.stories.jsx
  app/views/users/_account.html.erb
Labels: Crayons, PR: partially-approved, PR: unreviewed

#7654 Add new VCL snippets for Fastly
  config/fastly/snippets/bad_bot_detection.vcl
  config/fastly/snippets/check_for_remember_user_token_in_cookie_to_set_header.vcl
  config/fastly/snippets/stale_while_revalidate_controls.vcl
  spec/services/fastly_config/snippets_spec.rb
Labels: PR: reviewed-approved

#7667 Upgrade Doorkeeper to 5.3.2
  Gemfile.lock
Labels: PR: partially-approved

#7652 Move more code to Webpack and add conditional tag adjustments section
  app/assets/stylesheets/moderators.scss
  app/javascript/actionsPanel/actionsPanel.js
  app/javascript/packs/actionsPanel.js
  app/views/moderations/actions_panel.html.erb
Labels: PR: reviewed-approved

#7669 Remove FASTLY_SAFE_PARAMS_SNIPPET_NAME env var
  Envfile
Labels: PR: partially-approved

#7671 Fixed a typo in a a folder name.
  app/javascript/crayons/Button/__stories__/Button.stories.jsx
  app/javascript/crayons/Button/__stories__/button.html.stories.jsx
  app/javascript/crayons/Button/__stories__/button.sizes.html.stories.jsx
  app/javascript/crayons/ButtonGroup/__stories__/ButtonGroup.stories.jsx
  app/javascript/crayons/Dropdown/__stories__/dropdown.description.stories.jsx
  app/javascript/crayons/Dropdown/__stories__/dropdown.html.stories.jsx
  app/javascript/crayons/Indicator/__stories__/indicator.description.stories.jsx
  app/javascript/crayons/Indicator/__stories__/indicator.html.stories.jsx
  app/javascript/crayons/Modal/__stories__/modal.description.stories.jsx
  app/javascript/crayons/Modal/__stories__/modal.html.stories.jsx
  app/javascript/crayons/Notice/__stories__/notice.description.stories.jsx
  app/javascript/crayons/Notice/__stories__/notice.html.stories.jsx
  app/javascript/crayons/avatarsAndLogos/Avatar/__stories__/avatars.html.stories.jsx
  app/javascript/crayons/avatarsAndLogos/Logo/__stories__/logos.html.stories.jsx
  app/javascript/crayons/avatarsAndLogos/__stories__/description.stories.jsx
  app/javascript/crayons/formElements/Checkbox/__stories__/checkbox.html.stories.jsx
  app/javascript/crayons/formElements/RadioButton/__stories__/radioButton.html.stories.jsx
  app/javascript/crayons/formElements/Text/__stories__/multilineText.html.stories.jsx
  app/javascript/crayons/formElements/Text/__stories__/text.html.stories.jsx
  app/javascript/crayons/formElements/__stories__/description.stories.jsx
  app/javascript/crayons/navigation/NavigationTabs/__stories__/navigationTab.description.stories.jsx
  app/javascript/crayons/navigation/NavigationTabs/__stories__/navigationTab.html.stories.jsx
  app/javascript/crayons/navigation/mainNavigation/__stories__/mainNavigation.description.stories.jsx
  app/javascript/crayons/navigation/mainNavigation/__stories__/mainNavigation.html.stories.jsx
  app/javascript/crayons/storybook-utilities/Fieldset.jsx
  app/javascript/crayons/storybook-utilities/designSystem.scss
  app/javascript/crayons/typography/__stories__/typography.stories.jsx
  app/javascript/crayons/typography/__stories__/typographyAccented.stories.jsx
Labels: PR: reviewed-approved

#7665 Fix showing "Remove OAuth" in settings with disabled identities
  app/models/identity.rb
  app/views/users/_account.html.erb
  spec/requests/user/user_settings_spec.rb
Labels: PR: partially-approved, area: auth, area: generalization

#7668 Refactor Tracking Rate Limits for Actions
  app/controllers/image_uploads_controller.rb
  app/controllers/organizations_controller.rb
  app/labor/rate_limit_checker.rb
  app/services/articles/updater.rb
  spec/labor/rate_limit_checker_spec.rb
Labels: PR: partially-approved

#7670 Set Jest's timezone to UTC
  jest.config.js
Labels: PR: reviewed-approved

#7673 Add missing variable oops
  app/controllers/moderations_controller.rb
Labels: PR: unreviewed

#7660 Decouple GitHub authentication from fetching GitHub issues
  Envfile
  Gemfile
  Gemfile.lock
  app/assets/stylesheets/ltags/GithubTag.scss
  app/liquid_tags/github_tag/github_issue_tag.rb
  app/models/github_issue.rb
  app/services/github/client.rb
  app/services/github/errors.rb
  app/views/liquids/_github_issue.html.erb
  lib/data_update_scripts/20200503134234_remove_github_issues.rb
  spec/factories/github_issues.rb
  spec/liquid_tags/github_tag/github_issue_tag_spec.rb
  spec/models/github_issue_spec.rb
  spec/services/github/client_spec.rb
  spec/support/fixtures/approvals/github_issue_test.approved.html
  spec/support/fixtures/approvals/github_liquid_tag_default.approved.html
  spec/support/fixtures/vcr_cassettes/github_client_comment.yml
  spec/support/fixtures/vcr_cassettes/github_client_issue.yml
  spec/support/fixtures/vcr_cassettes/github_client_issue_not_found.yml
  spec/support/fixtures/vcr_cassettes/github_client_pull_request.yml
  spec/support/fixtures/vcr_cassettes/github_client_pull_request_comment.yml
  spec/support/fixtures/vcr_cassettes/github_issue_api.yml
Labels: PR: partially-approved, area: auth, area: generalization

#7536 Fix 503 error on organisation rename
  app/models/organization.rb
  app/workers/organizations/update_organization_articles_paths_worker.rb
  spec/workers/organizations/update_organization_articles_paths_worker_spec.rb
Labels: PR: partially-approved

#7672 Refactor JSON-LD Within user_show_spec to Improve Testing
  spec/factories/users.rb
  spec/requests/user/user_show_spec.rb
Labels: PR: reviewed-approved

#7678 two minor typo changes (according to Grammarly)
  CONTRIBUTING.md
Labels: PR: reviewed-approved

#7603 Modals
  app/assets/stylesheets/components/modals.scss
  app/assets/stylesheets/preact/onboarding-modal.scss
  app/javascript/crayons/Modal/Modal.jsx
  app/javascript/crayons/Modal/__stories__/Modal.stories.jsx
  app/javascript/crayons/Modal/__stories__/modal.description.stories.jsx
  app/javascript/crayons/Modal/index.js
  app/javascript/crayons/index.js
  app/javascript/onboarding/__tests__/__snapshots__/Onboarding.test.jsx.snap
  app/javascript/onboarding/components/EmailPreferencesForm.jsx
  app/javascript/onboarding/components/FollowTags.jsx
  app/javascript/onboarding/components/FollowUsers.jsx
  app/javascript/onboarding/components/IntroSlide.jsx
  app/javascript/onboarding/components/ProfileForm.jsx
  app/views/pages/crayons.html.erb
Labels: Crayons, PR: partially-approved, PR: unreviewed, tech: html/css

#7674 Refactor Checking Rate Limits and Their Retry After settings
  app/services/rate_limit_checker.rb
  spec/requests/api/v0/articles_spec.rb
  spec/requests/articles/articles_create_spec.rb
  spec/requests/image_uploads_spec.rb
  spec/requests/user/user_organization_spec.rb
  spec/services/rate_limit_checker_spec.rb
Labels: PR: unreviewed

#7205 Add comment subscription component to article page
  app/assets/stylesheets/article-show.scss
  app/assets/stylesheets/comments.scss
  app/javascript/CommentSubscription/CommentSubscription.jsx
  app/javascript/CommentSubscription/__stories__/CommentSubscription.stories.jsx
  app/javascript/CommentSubscription/__tests__/CommentSubscription.test.jsx
  app/javascript/CommentSubscription/__tests__/__snapshots__/CommentSubscription.test.jsx.snap
  app/javascript/CommentSubscription/__tests__/commentSubscriptionUtilities.test.js
  app/javascript/CommentSubscription/commentSubscriptionUtilities.jsx
  app/javascript/CommentSubscription/index.jsx
  app/javascript/Snackbar/Snackbar.jsx
  app/javascript/Snackbar/SnackbarPoller.jsx
  app/javascript/Snackbar/__stories__/Snackbar.stories.jsx
  app/javascript/Snackbar/__stories__/SnackbarPoller.stories.jsx
  app/javascript/Snackbar/__tests__/Snackbar.test.jsx
  app/javascript/Snackbar/__tests__/__snapshots__/Snackbar.test.jsx.snap
  app/javascript/Snackbar/index.js
  app/javascript/icons/CogIcon.jsx
  app/javascript/icons/__stories__/CogIcon.stories.jsx
  app/javascript/icons/__tests__/CogIcon.test.jsx
  app/javascript/icons/__tests__/__snapshots__/CogIcon.test.jsx.snap
  app/javascript/icons/index.js
  app/javascript/packs/articlePage.jsx
  app/views/articles/_actions.html.erb
  app/views/articles/_full_comment_area.html.erb
  app/views/articles/show.html.erb
  app/views/layouts/_footer.html.erb
  app/views/shell/_top.html.erb
Labels: PR: unreviewed, tech: fullstack

#7684 Rate Limit Classified Listing Creation
  app/controllers/classified_listings_controller.rb
  app/controllers/concerns/classified_listings_toolkit.rb
  app/models/site_config.rb
  app/services/rate_limit_checker.rb
  spec/requests/listings_spec.rb
Labels: PR: partially-approved

#7687 Ben/fix comment max width
  app/assets/stylesheets/comments.scss
Labels: PR: unreviewed

#7689 Fix comment container width issue in comment permalink
  app/assets/stylesheets/comments.scss
Labels: PR: reviewed-approved

#7690 Fix double-fix of comment container
  app/assets/stylesheets/comments.scss
Labels: PR: unreviewed

#7681 Color Updates
  app/assets/stylesheets/components/navigation.scss
  app/assets/stylesheets/components/notices.scss
  app/assets/stylesheets/config/_colors.scss
  app/assets/stylesheets/themes/hacker.scss
  app/assets/stylesheets/themes/minimal.scss
  app/assets/stylesheets/themes/night.scss
  app/assets/stylesheets/themes/pink.scss
Labels: Crayons, PR: partially-approved, PR: unreviewed

#7691 Quick inline style to solve content jump
  app/views/articles/_full_comment_area.html.erb
Labels: PR: partially-approved

#7682 SCSS variables --> CSS variables
  CONTRIBUTING.md
  app/assets/stylesheets/article-form-needed-legacy.scss
  app/assets/stylesheets/article-show.scss
  app/assets/stylesheets/base/layout.scss
  app/assets/stylesheets/base/reset.scss
  app/assets/stylesheets/chat.scss
  app/assets/stylesheets/classified_listings.scss
  app/assets/stylesheets/comments.scss
  app/assets/stylesheets/components/avatars.scss
  app/assets/stylesheets/components/banners.scss
  app/assets/stylesheets/components/buttons.scss
  app/assets/stylesheets/components/cards.scss
  app/assets/stylesheets/components/dropdowns.scss
  app/assets/stylesheets/components/forms.scss
  app/assets/stylesheets/components/indicators.scss
  app/assets/stylesheets/components/modals.scss
  app/assets/stylesheets/components/navigation.scss
  app/assets/stylesheets/components/notices.scss
  app/assets/stylesheets/components/snackbars.scss
  app/assets/stylesheets/config/_generator.scss
  app/assets/stylesheets/config/_import.scss
  app/assets/stylesheets/config/_variables.scss
  app/assets/stylesheets/connect/_channel-details.scss
  app/assets/stylesheets/crayons.scss
  app/assets/stylesheets/dashboard.scss
  app/assets/stylesheets/generator.scss
  app/assets/stylesheets/item-list.scss
  app/assets/stylesheets/leaderboard.scss
  app/assets/stylesheets/ltags/ClassifiedListingTag.scss
  app/assets/stylesheets/ltags/DevCommentTag.scss
  app/assets/stylesheets/ltags/LinkTag.scss
  app/assets/stylesheets/ltags/PodcastTag.scss
  app/assets/stylesheets/ltags/PollTag.scss
  app/assets/stylesheets/ltags/TagTag.scss
  app/assets/stylesheets/ltags/TweetTag.scss
  app/assets/stylesheets/ltags/UserTag.scss
  app/assets/stylesheets/moderators.scss
  app/assets/stylesheets/more-articles.scss
  app/assets/stylesheets/notifications.scss
  app/assets/stylesheets/onboarding.scss
  app/assets/stylesheets/podcast-episodes-show.scss
  app/assets/stylesheets/preact/article-form.scss
  app/assets/stylesheets/preact/onboarding-modal.scss
  app/assets/stylesheets/rlyweb.scss
  app/assets/stylesheets/scaffolds.scss
  app/assets/stylesheets/shared.scss
  app/assets/stylesheets/sidebar-data.scss
  app/assets/stylesheets/signin.scss
  app/assets/stylesheets/signup-modal.scss
  app/assets/stylesheets/sticky-nav.scss
  app/assets/stylesheets/tags.scss
  app/assets/stylesheets/theme-selector.scss
  app/assets/stylesheets/top-bar.scss
  app/assets/stylesheets/typography.scss
  app/assets/stylesheets/user-profile-header.scss
  app/assets/stylesheets/variables.scss
  app/assets/stylesheets/widgets.scss
Labels: PR: unreviewed, tech: html/css

#7695 Add substract svg
  app/assets/images/subtract.svg
Labels: PR: unreviewed

#7685 Dont Allow Multiple User Destroy Requests
  app/controllers/users_controller.rb
  spec/requests/user/user_destroy_spec.rb
Labels: PR: reviewed-approved

#7688 Force Unique Jobs for User Initiated Jobs and Cache Jobs
  app/workers/articles/bust_cache_worker.rb
  app/workers/articles/score_calc_worker.rb
  app/workers/articles/update_analytics_worker.rb
  app/workers/articles/update_main_image_background_hex_worker.rb
  app/workers/bust_cache_base_worker.rb
  app/workers/classified_listings/bust_cache_worker.rb
  app/workers/comments/bust_cache_worker.rb
  app/workers/events/bust_cache_worker.rb
  app/workers/export_content_worker.rb
  app/workers/organizations/bust_cache_worker.rb
  app/workers/pages/bust_cache_worker.rb
  app/workers/podcast_episodes/bust_cache_worker.rb
  app/workers/podcasts/bust_cache_worker.rb
  app/workers/rss_reader_fetch_user_worker.rb
  app/workers/tags/bust_cache_worker.rb
  app/workers/users/bust_cache_worker.rb
  app/workers/users/resave_articles_worker.rb
  app/workers/users/subscribe_to_mailchimp_newsletter_worker.rb
Labels: PR: partially-approved

#7683 Limit Reactions Created in a 30 second Timeframe
  app/controllers/reactions_controller.rb
  app/models/site_config.rb
  app/services/rate_limit_checker.rb
  spec/requests/reactions_spec.rb
Labels: PR: partially-approved

#7694 Adding tabIndex prop to Buttons component
  app/javascript/crayons/Button/Button.jsx
  app/javascript/crayons/Button/__tests__/Button.test.jsx
  app/javascript/crayons/Button/__tests__/__snapshots__/Button.test.jsx.snap
Labels: Crayons, PR: partially-approved, PR: unreviewed

#7680 Change string concatenation to interpolation
  app/controllers/concerns/valid_request.rb
  app/liquid_tags/organization_tag.rb
  app/liquid_tags/user_tag.rb
  app/models/article.rb
  app/models/event.rb
  app/models/user.rb
  app/views/organizations/_liquid.html.erb
  app/views/users/_liquid.html.erb
  spec/labor/cache_buster_spec.rb
  spec/requests/page_views_spec.rb
  spec/requests/stories_show_spec.rb
Labels: PR: partially-approved

#7675 Unescape user's summary in followUser slide
  app/javascript/onboarding/components/FollowUsers.jsx
  package.json
Labels: PR: unreviewed

#7556 Add automated email ownership emails
  app/controllers/email_authorizations_controller.rb
  app/controllers/internal/users_controller.rb
  app/mailers/verification_mailer.rb
  app/models/email_authorization.rb
  app/views/internal/users/_email_tools.html.erb
  app/views/internal/users/show.html.erb
  app/views/mailers/verification_mailer/account_ownership_verification_email.html.erb
  app/views/mailers/verification_mailer/account_ownership_verification_email.text.erb
  config/routes.rb
  db/migrate/20200427094852_add_confirmation_token_to_email_authorization.rb
  db/migrate/20200427233631_remove_user_id_type_of_index_from_email_authorization_table.rb
  db/schema.rb
  spec/mailers/previews/verification_mailer_preview.rb
  spec/mailers/verification_mailer_spec.rb
  spec/requests/internal/users_spec.rb
Labels: PR: partially-approved

#7696 Adjust GitHub and Twitter Connect Copy for Broadcasts
  db/seeds.rb
  spec/factories/broadcasts.rb
Labels: PR: partially-approved

#7655 Refactor method in internal controller
  app/controllers/internal/configs_controller.rb
Labels: PR: reviewed-approved

#7703 Add social preview fields to dashboard
  app/dashboards/classified_listing_category_dashboard.rb
Labels: PR: reviewed-approved

#7698 Move first-nav-link from dynamic JS to erb
  app/assets/javascripts/initializers/initializeBaseUserData.js
  app/views/layouts/_nav_menu.html.erb
Labels: PR: reviewed-approved

#7704 Multiple user destroy request follow up
  app/controllers/users_controller.rb
Labels: PR: reviewed-approved

#7705 Add RateLimitCheckerHelper
  app/helpers/rate_limit_checker_helper.rb
  app/services/rate_limit_checker.rb
  app/views/internal/configs/show.html.erb
  spec/helpers/rate_limit_checker_helper_spec.rb
Labels: PR: partially-approved

#7638 Now the entire feed card is clickable.
  app/assets/javascripts/initializers/initScrolling.js.erb
  app/assets/javascripts/initializers/initializePodcastPlayback.js
  app/assets/javascripts/utilities/buildArticleHTML.js.erb
  app/assets/stylesheets/components/stories.scss
  app/javascript/articles/Article.jsx
  app/javascript/articles/__tests__/__snapshots__/Article.test.jsx.snap
  app/javascript/articles/components/CommentListItem.jsx
  app/javascript/articles/components/__tests__/__snapshots__/CommentsList.test.jsx.snap
  app/views/classified_listings/index.html.erb
  docs/self-hosting.md
  spec/helpers/classified_listing_helper_spec.rb
Labels: PR: partially-approved

#7730 Track Client IPs to Help Block Bad Actors
  config/initializers/rack/attack.rb
  spec/initializers/rack/attack_spec.rb
Labels: PR: partially-approved

#7727 Now pointer cursor is only on feed posts.
  app/assets/stylesheets/components/stories.scss
  app/javascript/articles/Article.jsx
Labels: PR: reviewed-approved, tech: html/css

#7626 Create 'Flag User' modal
  app/assets/stylesheets/article-show.scss
  app/javascript/actionsPanel/actionsPanel.js
  app/javascript/actionsPanel/initializeActionsPanelToggle.js
  app/javascript/packs/flagUserModal.js
  app/javascript/packs/loadActionsPanelButton.js
  app/views/articles/show.html.erb
  app/views/moderations/actions_panel.html.erb
Labels: PR: reviewed-approved

#7699 Mod Actions Panel: Prevent nonsensical reaction pairs
  app/controllers/reactions_controller.rb
  app/javascript/actionsPanel/actionsPanel.js
Labels: PR: unreviewed

#7734 Use same class for comment show page
  app/views/comments/edit.html.erb
Labels: PR: reviewed-approved

#7701 Generalize internal logo
  app/views/layouts/internal.html.erb
Labels: PR: reviewed-approved

#7732 Onboarding fix for mobile
  app/assets/stylesheets/components/forms.scss
  app/assets/stylesheets/preact/onboarding-modal.scss
  app/javascript/onboarding/__tests__/__snapshots__/Onboarding.test.jsx.snap
  app/javascript/onboarding/components/FollowTags.jsx
  app/javascript/onboarding/components/FollowUsers.jsx
  app/javascript/onboarding/components/IntroSlide.jsx
Labels: PR: reviewed-approved, area: new user experience, tech: html/css

#7708 Replaced ApplicationConfig with app_url in views
  app/views/articles/search/_meta.html.erb
  app/views/articles/show.html.erb
  app/views/mailers/pro_membership_mailer/expiring_membership.html.erb
  app/views/mailers/pro_membership_mailer/expiring_membership.text.erb
  app/views/sitemaps/show.xml.erb
  app/views/users/_org_admin.html.erb
  app/views/users/_profile.html.erb
Labels: PR: partially-approved

#7707 Decouple GithubReadmeTag liquid tag from GitHub auth
  app/liquid_tags/github_tag/github_readme_tag.rb
  app/services/github/client.rb
  app/services/github/errors.rb
  spec/liquid_tags/github_tag/github_readme_tag_spec.rb
  spec/models/article_spec.rb
  spec/support/fixtures/vcr_cassettes/github_api_readme.yml
  spec/support/fixtures/vcr_cassettes/github_client_repository.yml
  spec/support/fixtures/vcr_cassettes/github_client_repository_no_readme.yml
  spec/support/fixtures/vcr_cassettes/github_client_repository_not_found.yml
Labels: PR: reviewed-approved

#6960 Fix intermittent service worker runtime error
  app/views/service_worker/index.js.erb
Labels: PR: partially-approved, area: service worker

#7735 Track IPs and API Tokens for Throttled Requets, Send Retry After Header
  config/initializers/rack/attack.rb
  spec/initializers/rack/attack_spec.rb
Labels: PR: partially-approved

#7739 Allow empty status option for feedback messages
  app/views/internal/feedback_messages/index.html.erb
  spec/system/internal/admin_manages_reports_spec.rb
Labels: PR: reviewed-approved

#7733 Refactor articles_show_spec to Better Test JSON-LD
  app/controllers/stories_controller.rb
  spec/requests/articles/articles_show_spec.rb
Labels: PR: partially-approved

#7743 Routine rubocop fixes
  .rubocop_todo.yml
  app/controllers/notifications_controller.rb
  app/models/message.rb
  db/seeds.rb
  lib/tasks/fastly.rake
  lib/tasks/temporary/classified_listings.rake
  spec/helpers/classified_listing_helper_spec.rb
  spec/labor/bufferizer_spec.rb
  spec/requests/user/user_show_spec.rb
  spec/system/articles/user_visits_an_article_spec.rb
  spec/system/articles/user_visits_articles_by_timeframe_spec.rb
  spec/system/comments/user_fills_out_comment_spec.rb
  spec/system/comments/user_views_article_comments_spec.rb
  spec/system/homepage/user_visits_homepage_articles_spec.rb
  spec/system/homepage/user_visits_homepage_spec.rb
  spec/system/podcasts/user_visits_podcast_episode_spec.rb
  spec/system/podcasts/user_visits_podcast_page_spec.rb
  spec/system/user_views_a_reading_list_spec.rb
  spec/system/user_visits_a_comments_page_spec.rb
  spec/system/videos/user_visits_videos_spec.rb
Labels: PR: partially-approved

#7744 Adjust ModPanel Button position on mobile
  app/assets/stylesheets/article-show.scss
Labels: PR: reviewed-approved

#7725 Add generalized community name and description to onboarding slides
  app/javascript/onboarding/Onboarding.jsx
  app/javascript/onboarding/__tests__/Onboarding.test.jsx
  app/javascript/onboarding/__tests__/__snapshots__/Onboarding.test.jsx.snap
  app/javascript/onboarding/components/IntroSlide.jsx
  app/javascript/onboarding/components/ProfileForm.jsx
  app/javascript/packs/Onboarding.jsx
  app/views/onboardings/show.html.erb
Labels: PR: reviewed-approved

#7676 Bulk Fetch Follow Button Data for Users
  app/assets/javascripts/initializePage.js.erb
  app/assets/javascripts/initializers/initializeAdditionalContentBoxes.js
  app/assets/javascripts/initializers/initializeAllFollowButts.js
  app/assets/javascripts/initializers/initializeLocalStorageRender.js
  app/assets/javascripts/utilities/buildArticleHTML.js.erb
  app/controllers/follows_controller.rb
  app/services/search/user.rb
  app/views/articles/_search.html.erb
  config/fastly/snippets/safe_params_list.vcl
  config/routes.rb
  spec/requests/follows_bulk_show_spec.rb
  spec/system/search/user_searches_users_spec.rb
Labels: PR: partially-approved

#7745 Add Feature Search Tests for Users and Articles
  spec/support/elasticsearch_helpers.rb
  spec/system/search/display_articles_search_spec.rb
  spec/system/search/display_users_search_spec.rb
Labels: PR: partially-approved

#7741 Fix bug regarding negative reactions on users
  app/views/internal/negative_reactions/index.html.erb
  spec/factories/reactions.rb
  spec/requests/internal/negative_reactions_spec.rb
Labels: PR: partially-approved

#7740 Finalize tag adjustments
  app/assets/images/plus.svg
  app/assets/stylesheets/moderators.scss
  app/controllers/moderations_controller.rb
  app/controllers/tag_adjustments_controller.rb
  app/javascript/actionsPanel/actionsPanel.js
  app/views/moderations/actions_panel.html.erb
  spec/requests/moderations_spec.rb
Labels: PR: partially-approved

#7385 🚀 Feature: Ability to search discoverable channels and send request to join
  app/assets/stylesheets/chat.scss
  app/controllers/chat_channel_memberships_controller.rb
  app/controllers/chat_channels_controller.rb
  app/controllers/search_controller.rb
  app/javascript/chat/__tests__/__snapshots__/channelButton.test.jsx.snap
  app/javascript/chat/__tests__/__snapshots__/channelRequest.test.jsx.snap
  app/javascript/chat/__tests__/__snapshots__/channels.test.jsx.snap
  app/javascript/chat/__tests__/__snapshots__/chat.test.jsx.snap
  app/javascript/chat/__tests__/__snapshots__/content.test.jsx.snap
  app/javascript/chat/__tests__/channelButton.test.jsx
  app/javascript/chat/__tests__/channelRequest.test.jsx
  app/javascript/chat/__tests__/channels.test.jsx
  app/javascript/chat/actions.js
  app/javascript/chat/channelRequest.jsx
  app/javascript/chat/channels.jsx
  app/javascript/chat/chat.jsx
  app/javascript/chat/components/channelButton.jsx
  app/javascript/chat/content.jsx
  app/javascript/chat/util.js
  app/javascript/chat/videoContent.jsx
  app/javascript/packs/Chat.jsx
  app/models/chat_channel.rb
  app/models/chat_channel_membership.rb
  app/policies/chat_channel_policy.rb
  app/serializers/search/chat_channel_membership_serializer.rb
  app/services/search/query_builders/chat_channel_membership.rb
  app/views/chat_channel_memberships/edit.html.erb
  app/views/mailers/notify_mailer/channel_invite_email.html.erb
  config/elasticsearch/mappings/chat_channel_memberships.json
  config/routes.rb
  db/migrate/20200411085952_add_column_discoverable_to_chat_channels.rb
  db/schema.rb
  spec/requests/chat_channel_memberships_spec.rb
  spec/requests/chat_channels_spec.rb
  spec/services/search/chat_channel_membership_spec.rb
  spec/services/search/query_builders/chat_channel_membership_spec.rb
Labels: PR: partially-approved

#7759 Add Follow button to Dashboard Followers view
  app/assets/stylesheets/dashboard.scss
  app/views/dashboards/followers.html.erb
Labels: PR: partially-approved

#7761 Add org credit management to org mod page
  app/controllers/internal/organizations_controller.rb
  app/helpers/organization_helper.rb
  app/views/internal/organizations/show.html.erb
  app/views/internal/users/_credits.erb
  config/routes.rb
  spec/helpers/organization_helper_spec.rb
  spec/requests/internal/organizations_spec.rb
  spec/system/internal/admin_manages_organizations_spec.rb
Labels: PR: partially-approved

#7772 Final bug fixes mod panel
  app/javascript/actionsPanel/actionsPanel.js
Labels: PR: unreviewed

#7746 Limit User Email Changes
  app/helpers/rate_limit_checker_helper.rb
  app/models/site_config.rb
  app/models/user.rb
  app/services/rate_limit_checker.rb
  spec/initializers/rack/attack_spec.rb
  spec/models/user_spec.rb
  spec/services/rate_limit_checker_spec.rb
Labels: PR: partially-approved

#7702 Create notification page spec
  app/assets/javascripts/initializers/initializeCommentsPage.js.erb
  app/views/notifications/shared/_comment_box.html.erb
  spec/system/notifications/notifications_page_spec.rb
Labels: PR: unreviewed

#7773 Only Allow Direct Channels Between 2 Different People
  app/models/chat_channel.rb
  spec/models/chat_channel_spec.rb
Labels: PR: partially-approved

#7765 Render the correct partial when updating an organization fails
  app/controllers/organizations_controller.rb
  spec/system/organization/user_updates_org_settings_spec.rb
Labels: PR: partially-approved

#7736 Optimize FeedbackMessagesController#index
  app/controllers/internal/feedback_messages_controller.rb
Labels: PR: unreviewed

#6618 Dont configure Honeycomb if its disabled
  config/initializers/honeycomb.rb
  datadog/prerun.sh
Labels: PR: partially-approved

#7775 Use actions panel for /mod page
  app/assets/stylesheets/moderators.scss
  app/javascript/packs/loadActionsPanelButton.js
  app/views/moderations/index.html.erb
Labels: PR: unreviewed

#6992 Refactor listings/listings.jsx
  app/javascript/article-form/elements/__tests__/__snapshots__/description.test.jsx.snap
  app/javascript/article-form/elements/__tests__/description.test.jsx
  app/javascript/listings/__tests__/AllListings.test.jsx
  app/javascript/listings/__tests__/BodyMarkdown.test.jsx
  app/javascript/listings/__tests__/ClassifiedFilterTags.test.jsx
  app/javascript/listings/__tests__/ClassifiedFilters.test.jsx
  app/javascript/listings/__tests__/ClassifiedFiltersCategories.test.jsx
  app/javascript/listings/__tests__/ClearQueryButton.test.jsx
  app/javascript/listings/__tests__/ContactViaConnect.test.jsx
  app/javascript/listings/__tests__/ListingDashboard.test.jsx
  app/javascript/listings/__tests__/MessageModal.test.jsx
  app/javascript/listings/__tests__/Modal.test.jsx
  app/javascript/listings/__tests__/ModalBackground.test.jsx
  app/javascript/listings/__tests__/NextPageButton.test.jsx
  app/javascript/listings/__tests__/SelectedTags.test.jsx
  app/javascript/listings/__tests__/SingleListing.test.jsx
  app/javascript/listings/__tests__/__snapshots__/AllListings.test.jsx.snap
  app/javascript/listings/__tests__/__snapshots__/BodyMarkdown.test.jsx.snap
  app/javascript/listings/__tests__/__snapshots__/ClassifiedFilters.test.jsx.snap
  app/javascript/listings/__tests__/__snapshots__/ClearQueryButton.test.jsx.snap
  app/javascript/listings/__tests__/__snapshots__/ListingDashboard.test.jsx.snap
  app/javascript/listings/__tests__/__snapshots__/ModalBackground.test.jsx.snap
  app/javascript/listings/__tests__/__snapshots__/NextPageButton.test.jsx.snap
  app/javascript/listings/__tests__/__snapshots__/SelectedTags.test.jsx.snap
  app/javascript/listings/__tests__/__snapshots__/SingleListing.test.jsx.snap
  app/javascript/listings/__tests__/utils.test.js
  app/javascript/listings/components/AllListings.jsx
  app/javascript/listings/components/BodyMarkdown.jsx
  app/javascript/listings/components/Categories.jsx
  app/javascript/listings/components/CategoryLinks.jsx
  app/javascript/listings/components/ClassifiedFilters.jsx
  app/javascript/listings/components/ClassifiedFiltersCategories.jsx
  app/javascript/listings/components/ClassifiedFiltersTags.jsx
  app/javascript/listings/components/ClearQueryButton.jsx
  app/javascript/listings/components/ContactViaConnect.jsx
  app/javascript/listings/components/ExpireDate.jsx
  app/javascript/listings/components/MessageModal.jsx
  app/javascript/listings/components/Modal.jsx
  app/javascript/listings/components/ModalBackground.jsx
  app/javascript/listings/components/NextPageButton.jsx
  app/javascript/listings/components/SelectedTags.jsx
  app/javascript/listings/components/Title.jsx
  app/javascript/listings/listingForm.jsx
  app/javascript/listings/listings.jsx
  app/javascript/listings/utils.js
  app/javascript/src/components/common-prop-types/index.js
  app/javascript/src/components/common-prop-types/selected-tags-prop-types.js
Labels: PR: partially-approved

#7778 Return the First 300 characters for Redis Commands
  config/initializers/honeycomb.rb
Labels: PR: partially-approved

#7776 Ensure Users are Authorized Before Checking Reaction Rate Limit
  app/controllers/reactions_controller.rb
  spec/requests/reactions_spec.rb
Labels: PR: partially-approved

#7780 Bug Fix: Only Throttle Confirmation Emails for Existing Users
  app/models/user.rb
  spec/models/user_spec.rb
Labels: PR: partially-approved

#7738 Shorten page title for unauthenticated traffic
  app/helpers/application_helper.rb
  spec/requests/stories_show_spec.rb
  spec/system/organization/user_views_an_organization_spec.rb
  spec/system/user/view_user_index_spec.rb
Labels: PR: unreviewed

#7767 Fixed alignment
  app/assets/stylesheets/widgets.scss
Labels: PR: reviewed-approved

#7785 Fix flaky organization helper spec
  spec/helpers/organization_helper_spec.rb
Labels: PR: partially-approved

#7764 Refactoring GitHub Repos functionality - step 1
  app/assets/stylesheets/settings.scss
  app/controllers/github_repos_controller.rb
  app/controllers/stories_controller.rb
  app/controllers/users_controller.rb
  app/javascript/githubRepos/__tests__/__snapshots__/singleRepo.test.jsx.snap
  app/javascript/githubRepos/__tests__/singleRepo.test.jsx
  app/javascript/githubRepos/githubRepos.jsx
  app/javascript/githubRepos/singleRepo.jsx
  app/models/github_repo.rb
  app/models/user.rb
  app/policies/github_repo_policy.rb
  app/views/github_repos/index.json.jbuilder
  app/views/users/_github_repositories_area.html.erb
  app/views/users/_integrations.html.erb
  app/views/users/_integrations_github_repositories.html.erb
  app/views/users/_response_templates.html.erb
  app/views/users/_sidebar_additional.html.erb
  app/views/users/show.html.erb
  config/routes.rb
  spec/models/github_repo_spec.rb
  spec/models/user_spec.rb
  spec/policies/github_repo_policy_spec.rb
  spec/requests/github_repos_spec.rb
  spec/requests/internal/negative_reactions_spec.rb
  spec/requests/user/user_profile_spec.rb
  spec/requests/user/user_settings_spec.rb
Labels: PR: unreviewed

#7781 Allow to specify view parameter for codesandbox
  app/liquid_tags/codesandbox_tag.rb
  spec/liquid_tags/codesandbox_tag_spec.rb
Labels: PR: partially-approved

#7788 Removed feedIcons.js.erb as the file is no longer being used.
  app/javascript/packs/feedIcons.js.erb
Labels: PR: partially-approved, tech: javascript

#7771 Decrease General Site Request Limit
  config/initializers/rack/attack.rb
Labels: PR: unreviewed

#7795 Include crayons style in index view for redundency
  app/views/articles/index.html.erb
Labels: PR: partially-approved

#7796 Fix podcast styling
  app/assets/stylesheets/components/stories.scss
  app/controllers/stories_controller.rb
  app/javascript/podcasts/PodcastEpisode.jsx
  app/javascript/podcasts/__tests__/__snapshots__/PodcastEpisode.test.jsx.snap
  app/javascript/podcasts/__tests__/__snapshots__/TodaysPodcasts.test.jsx.snap
Labels: PR: partially-approved

#7782 Raise an Error If Trying to Rate Limit with a Missing User ID
  app/services/rate_limit_checker.rb
  spec/services/rate_limit_checker_spec.rb
Labels: PR: partially-approved

#7799 Adjust overflow in comments and revert inline css
  app/assets/stylesheets/components/comments.scss
  app/assets/stylesheets/components/stories.scss
  app/javascript/articles/__tests__/__snapshots__/Article.test.jsx.snap
  app/javascript/articles/components/CommentListItem.jsx
  app/javascript/articles/components/__tests__/__snapshots__/CommentsList.test.jsx.snap
  app/views/articles/index.html.erb
Labels: PR: partially-approved

#7802 Fix inline/box issue in story feed comments
  app/assets/stylesheets/components/comments.scss
  app/assets/stylesheets/themes/hacker.scss
  app/assets/stylesheets/themes/minimal.scss
  app/assets/stylesheets/themes/night.scss
Labels: PR: unreviewed

#7800 Delay RemoveFromIndex Job to Fix Callback Race Conditions
  app/models/comment.rb
  app/models/concerns/searchable.rb
Labels: PR: partially-approved

#7804 fetchSearch now uses @utilities/http/request under the hood now.
  app/javascript/article-form/elements/__tests__/tags.test.jsx
  app/javascript/src/utils/__tests__/search.test.js
  app/javascript/src/utils/search.js
Labels: PR: partially-approved, tech: javascript

#7807 Update Article snapshots
  app/javascript/articles/__tests__/__snapshots__/Article.test.jsx.snap
Labels: PR: partially-approved

#7806 Specify background for content row in onboarding
  app/assets/stylesheets/preact/onboarding-modal.scss
Labels: PR: unreviewed

#7809 Remove hard-coded published_at_int
  app/javascript/articles/__tests__/__snapshots__/Article.test.jsx.snap
  app/javascript/articles/__tests__/utilities/articleUtilities.js
Labels: PR: reviewed-approved

#7787 Fix profile page rendering when a username contains spaces
  app/controllers/users_controller.rb
  app/lib/url.rb
  app/views/users/_profile.html.erb
  app/views/users/edit.html.erb
  spec/system/user/user_edits_profile_spec.rb
Labels: PR: reviewed-approved

#7812 Fix connect runtime error
  app/javascript/chat/channels.jsx
  app/javascript/chat/chat.jsx
Labels: PR: reviewed-approved

#7810 Make a constant for long inline regexp
  app/liquid_tags/codesandbox_tag.rb
Labels: PR: partially-approved

#7822 Removed code related to /live_articles
  app/controllers/internal/articles_controller.rb
  app/controllers/internal/events_controller.rb
  app/controllers/live_articles_controller.rb
  config/routes.rb
  spec/requests/live_articles_spec.rb
Labels: PR: partially-approved

#7819 Feed: Flare tag alignment
  app/assets/stylesheets/components/stories.scss
  app/assets/stylesheets/components/tags.scss
  app/assets/stylesheets/config/_variables.scss
Labels: PR: partially-approved, tech: html/css

#7805 Handle negative reactions on comments
  app/views/internal/negative_reactions/index.html.erb
  spec/factories/reactions.rb
  spec/requests/internal/negative_reactions_spec.rb
Labels: PR: partially-approved

#7811 Limit Suggestions for Social Service Posts to 3 Per Article Per Service
  app/models/buffer_update.rb
  spec/models/buffer_update_spec.rb
Labels: PR: partially-approved

#7792 Hotfix video icon in feed
  app/assets/javascripts/utilities/buildArticleHTML.js.erb
Labels: PR: partially-approved

#7742 Adapt dev env to use remote box
  Procfile.dev
  docs/.gitdocs.json
  docs/installation/linux.md
  docs/installation/mac.md
  docs/installation/windows.md
Labels: PR: partially-approved

#6500 Fixes some html_safe in Articles
  .erb-lint.yml
  app/views/articles/_block.html.erb
  app/views/articles/_single_sponsor.html.erb
  app/views/articles/_sticky_nav.html.erb
  app/views/articles/show.html.erb
  app/views/articles/tags/_sidebar.html.erb
  app/views/comments/index.html.erb
Labels: PR: reviewed-approved

#7823 Added tests.
  app/javascript/articles/__tests__/Article.test.jsx
  app/javascript/articles/__tests__/__snapshots__/Article.test.jsx.snap
  app/javascript/articles/__tests__/utilities/articleUtilities.js
Labels: PR: partially-approved, tech: javascript

#4756 Show Empty State in Badges List for Mobile Views
  app/views/articles/_badges_area.html.erb
Labels: PR: reviewed-approved

#7829 Remove logging of image data to Datadog
  app/controllers/concerns/image_uploads.rb
  app/controllers/image_uploads_controller.rb
  app/controllers/organizations_controller.rb
  app/controllers/podcasts_controller.rb
  app/controllers/users_controller.rb
  spec/requests/image_uploads_spec.rb
  spec/requests/organizations_update_spec.rb
  spec/requests/podcasts/podcast_create_spec.rb
  spec/requests/user/user_organization_spec.rb
  spec/requests/user/user_settings_spec.rb
Labels: PR: partially-approved

#7826 Expose Article Update Rate Limit on Config Page
  app/controllers/application_controller.rb
  app/helpers/rate_limit_checker_helper.rb
  app/services/articles/creator.rb
  app/services/articles/updater.rb
Labels: PR: partially-approved

#7794 Add query-friendly article additions (Initial step)
  app/assets/stylesheets/article-show.scss
  app/dashboards/article_dashboard.rb
  app/decorators/article_decorator.rb
  app/views/articles/show.html.erb
  db/migrate/20200511224704_add_query_friendly_admin_fields_to_articles.rb
  db/schema.rb
  spec/decorators/article_decorator_spec.rb
  spec/requests/stories_show_spec.rb
Labels: PR: reviewed-approved

#7833 filter/sample noisy spans
  config/initializers/honeycomb.rb
Labels: PR: reviewed-approved

#7837 Revert "filter/sample noisy spans"
  config/initializers/honeycomb.rb
Labels: PR: unreviewed

#7827 Use build_stubbed where possible
  spec/liquid_tags/classified_listing_tag_spec.rb
  spec/liquid_tags/link_tag_spec.rb
  spec/requests/articles/articles_spec.rb
  spec/requests/articles/articles_update_spec.rb
  spec/requests/internal/buffer_updates_spec.rb
  spec/requests/internal/moderator_logs_spec.rb
  spec/requests/internal/sponsorships_spec.rb
  spec/system/admin/admin_dashboard_presented_spec.rb
Labels: PR: partially-approved

#7836 Add max height to content images to ensure they can't over-eat vertical space
  app/assets/stylesheets/article-show.scss
  app/assets/stylesheets/comments.scss
Labels: PR: reviewed-approved

#7842 Remove temporary Rake task
  lib/tasks/temporary/classified_listings.rake
Labels: PR: reviewed-approved

#7737 NOT MERGE Add tabs to Crayons and to the notifications page
  app/assets/javascripts/initializers/initNotifications.js
  app/assets/stylesheets/components/forms.scss
  app/assets/stylesheets/components/navigation.scss
  app/assets/stylesheets/components/tabs.scss
  app/assets/stylesheets/config/_colors.scss
  app/assets/stylesheets/crayons.scss
  app/assets/stylesheets/notifications.scss
  app/assets/stylesheets/themes/hacker.scss
  app/assets/stylesheets/themes/minimal.scss
  app/assets/stylesheets/themes/night.scss
  app/assets/stylesheets/themes/pink.scss
  app/views/notifications/index.html.erb
  app/views/pages/crayons.html.erb
Labels: Crayons, PR: draft, PR: partially-approved, PR: unreviewed

#7844 Fix schema.rb order
  db/schema.rb
Labels: PR: partially-approved

#7480 Fix the height of new post text area and add scrollbar
  app/assets/stylesheets/preact/article-form.scss
  app/javascript/article-form/__tests__/__snapshots__/articleForm.test.jsx.snap
  app/javascript/article-form/elements/bodyMarkdown.jsx
Labels: PR: partially-approved, area: publishing experience, tech: javascript

#7573 Add twitter hashtag to the site config
  app/controllers/internal/configs_controller.rb
  app/models/site_config.rb
  app/views/internal/configs/show.html.erb
  spec/requests/internal/configs_spec.rb
Labels: PR: partially-approved, action: post deployment

#7831 Enforce Uniq Abuse Reports from Reporters
  app/models/feedback_message.rb
  spec/factories/feedback_messages.rb
  spec/models/feedback_message_spec.rb
Labels: PR: reviewed-approved

#7834 Create write_articles oauth scope
  app/controllers/api/v0/articles_controller.rb
  config/initializers/doorkeeper.rb
  config/locales/doorkeeper.en.yml
  spec/requests/api/v0/articles_spec.rb
Labels: PR: reviewed-approved

#7849 Use bulk_show Endpoint for Follow Buttons on Followers Dashboard
  app/views/dashboards/followers.html.erb
  spec/system/dashboards/user_followers_display_spec.rb
Labels: PR: partially-approved

#7832 Rate Limit Feedback Message Creation By User ID or IP
  app/controllers/application_controller.rb
  app/controllers/feedback_messages_controller.rb
  app/helpers/rate_limit_checker_helper.rb
  app/models/site_config.rb
  app/models/user.rb
  app/services/rate_limit_checker.rb
  spec/requests/feedback_messages_spec.rb
  spec/services/rate_limit_checker_spec.rb
Labels: PR: reviewed-approved

#7854 Return boolean value instead of undefined for listings open modal
  app/javascript/listings/__tests__/AllListings.test.jsx
  app/javascript/listings/__tests__/utils.test.js
  app/javascript/listings/listings.jsx
Labels: PR: reviewed-approved

#7846 Ignore articles.live_now column
  app/controllers/internal/articles_controller.rb
  app/models/article.rb
  app/views/articles/show.html.erb
Labels: PR: partially-approved

#7847 Track and Limit API writes by IP Address + Rack Attack Refactor
  config/initializers/rack/attack.rb
  spec/initializers/rack/attack_spec.rb
Labels: PR: partially-approved

#7867 Add a section about what the admin panel is
  docs/backend/admin.md
Labels: PR: reviewed-approved

#7868 Add Back Tracking API-keys in Honeycomb
  config/initializers/rack/attack.rb
  spec/initializers/rack/attack_spec.rb
Labels: PR: reviewed-approved

#6146 Add docs for tallying timeseries metrics
  docs/backend/metrics.md
  docs/backend/readme.md
Labels: PR: partially-approved

#7869 Moved search components our of src/ folder.
  app/javascript/Search/Search.jsx
  app/javascript/Search/SearchForm.jsx
  app/javascript/Search/__stories__/SearchForm.stories.jsx
  app/javascript/Search/__tests__/Search.test.jsx
  app/javascript/Search/__tests__/SearchForm.test.jsx
  app/javascript/Search/__tests__/__snapshots__/Search.test.jsx.snap
  app/javascript/Search/__tests__/__snapshots__/SearchForm.test.jsx.snap
  app/javascript/Search/index.js
  app/javascript/packs/Search.jsx
Labels: PR: partially-approved, tech: html/css, tech: javascript

#7871 Moved common-prop-types out of src/ folder
  app/javascript/Snackbar/SnackbarItem.jsx
  app/javascript/articles/Article.jsx
  app/javascript/articles/PodcastArticle.jsx
  app/javascript/articles/__stories__/articleDecorator.jsx
  app/javascript/articles/components/ArticleCoverImage.jsx
  app/javascript/articles/components/ContentTitle.jsx
  app/javascript/articles/components/Meta.jsx
  app/javascript/articles/components/ReactionsCount.jsx
  app/javascript/articles/components/SaveButton.jsx
  app/javascript/articles/components/SearchSnippet.jsx
  app/javascript/articles/components/TagList.jsx
  app/javascript/articles/components/Video.jsx
  app/javascript/common-prop-types/article-prop-types.js
  app/javascript/common-prop-types/default-children-prop-types.js
  app/javascript/common-prop-types/index.js
  app/javascript/common-prop-types/organization-prop-type.js
  app/javascript/common-prop-types/selected-tags-prop-types.js
  app/javascript/common-prop-types/tag-prop-types.js
  app/javascript/common-prop-types/user-prop-types.js
  app/javascript/crayons/Button/Button.jsx
  app/javascript/crayons/ButtonGroup/ButtonGroup.jsx
  app/javascript/crayons/Dropdown/Dropdown.jsx
  app/javascript/crayons/Modal/Modal.jsx
  app/javascript/crayons/formElements/FormField/FormField.jsx
  app/javascript/crayons/storybook-utilities/Fieldset.jsx
  app/javascript/leftSidebar/TagsFollowed.jsx
  app/javascript/listings/components/ClassifiedFilters.jsx
  app/javascript/listings/components/ClassifiedFiltersTags.jsx
  app/javascript/listings/components/SelectedTags.jsx
  app/javascript/organization/OrganizationPicker.jsx
  app/javascript/packs/homePageFeed.jsx
  app/javascript/podcasts/PodcastEpisode.jsx
  app/javascript/podcasts/TodaysPodcasts.jsx
  app/javascript/sidebar-widget/sidebarUser.jsx
  app/javascript/src/components/__stories__/GlobalModalWrapper.jsx
Labels: PR: partially-approved

#7841 Credit refactoring
  app/controllers/concerns/classified_listings_toolkit.rb
  app/controllers/internal/organizations_controller.rb
  app/controllers/internal/users_controller.rb
  app/models/credit.rb
  spec/models/credit_spec.rb
  spec/requests/internal/organizations_spec.rb
  spec/requests/internal/users_manage_spec.rb
  spec/requests/partnerships_spec.rb
Labels: PR: partially-approved

#7874 Return if there is no ip_address from Method
  config/initializers/rack/attack.rb
Labels: PR: partially-approved

#7870 Limit the Number of API Keys a User Can Have
  app/models/api_secret.rb
  spec/models/api_secret_spec.rb
  spec/queries/internal/moderators_query_spec.rb
Labels: PR: reviewed-approved

#7872 Expand webhook API request specs
  spec/requests/api/v0/webhooks_spec.rb
  spec/requests/internal/negative_reactions_spec.rb
  spec/support/api_analytics_shared_examples.rb
Labels: PR: partially-approved

#7814 Open in new window properly on ctrl+click etc
  app/javascript/articles/Article.jsx
  app/javascript/articles/components/CommentListItem.jsx
Labels: PR: reviewed-approved, area: homepage

#7593 Sanitizing and rendering html entities in article title
  app/helpers/application_helper.rb
  app/javascript/src/components/ItemList/ItemListItem.jsx
  app/javascript/src/components/ItemList/__tests__/ItemListItem.test.jsx
  app/javascript/src/components/ItemList/__tests__/__snapshots__/ItemListItem.test.jsx.snap
  app/views/articles/show.html.erb
  app/views/dashboards/_dashboard_article.html.erb
  spec/helpers/application_helper_spec.rb
Labels: PR: partially-approved

#6767 Fix Runkit tags not being activated when comment is added
  app/assets/javascripts/initializers/initializeCommentPreview.js
  app/assets/javascripts/initializers/initializeCommentsPage.js.erb
  app/assets/javascripts/utilities/dynamicallyLoadScript.js
  app/javascript/article-form/articleForm.jsx
  app/liquid_tags/runkit_tag.rb
  app/views/articles/_v2_form.html.erb
  app/views/articles/show.html.erb
  app/views/liquids/_runkit.html.erb
  spec/fixtures/files/article_with_runkit_tag.txt
  spec/support/fixtures/approvals/runkit_liquid_tag_spec.approved.html
  spec/support/runkit_tag_context.rb
  spec/system/articles/user_creates_an_article_spec.rb
  spec/system/comments/user_fills_out_comment_spec.rb
Labels: PR: partially-approved

#7875 Moved src/utils out of src/ folder to utilities/ folder.
  app/javascript/Search/Search.jsx
  app/javascript/analytics/client.js
  app/javascript/chat/actions.js
  app/javascript/chat/chat.jsx
  app/javascript/listings/listings.jsx
  app/javascript/packs/Onboarding.jsx
  app/javascript/packs/onboardingRedirectCheck.jsx
  app/javascript/readingList/readingList.jsx
  app/javascript/searchableItemList/searchableItemList.js
  app/javascript/shared/components/tags.jsx
  app/javascript/sidebar-widget/SidebarWidget.jsx
  app/javascript/utilities/__tests__/search.test.js
  app/javascript/utilities/connect/getUnopenedChannels.jsx
  app/javascript/utilities/connect/index.js
  app/javascript/utilities/connect/pusher.js
  app/javascript/utilities/debounceAction.js
  app/javascript/utilities/http/errors.js
  app/javascript/utilities/http/index.js
  app/javascript/utilities/search/index.js
  app/javascript/utilities/sendFollowUser.js
Labels: PR: partially-approved, tech: javascript
