Repository forem/forem, pull requests merged in 2020-03, with the labels that each got.

#6389 Extra padding on tags
  app/assets/stylesheets/articles.scss
Labels: area: homepage, tech: html/css

#6335 Add EmailAuthorization model
  app/models/email_authorization.rb
  app/models/user.rb
  db/migrate/20200226205549_create_email_authorization_table.rb
  db/migrate/20200226210111_validate_create_email_authorization_table.rb
  db/schema.rb
  spec/factories/email_authorizations.rb
  spec/models/email_authorization_spec.rb
Labels: PR: unreviewed

#6418 Create Feed Content index for Articles and Podcast Episodes and User Index
  app/services/search/cluster.rb
  app/services/search/feed_content.rb
  app/services/search/user.rb
  config/elasticsearch/mappings/feed_content.json
  config/elasticsearch/mappings/users.json
  spec/services/search/base_spec.rb
  spec/services/search/feed_content_spec.rb
  spec/services/search/user_spec.rb
Labels: PR: reviewed-approved

#6419 Bump reverse_markdown to 2.0
  Gemfile
  Gemfile.lock
Labels: PR: reviewed-approved

#6420 Bump omniauth to 1.9.1
  Gemfile.lock
Labels: PR: reviewed-approved

#6302 Add .present? check
  app/models/article.rb
  spec/models/article_spec.rb
Labels: PR: reviewed-approved

#6374 Create fetchSearch helper
  app/javascript/chat/actions.js
  app/javascript/shared/components/tags.jsx
  app/javascript/src/utils/__tests__/search.test.js
  app/javascript/src/utils/search.js
Labels: PR: reviewed-approved

#6421 Remove Redundant Search specs
  spec/services/search/chat_channel_membership_spec.rb
  spec/services/search/classified_listing_spec.rb
  spec/services/search/tag_spec.rb
Labels: PR: reviewed-approved

#6424 Remove console log
  app/javascript/articles/Feed.jsx
Labels: PR: reviewed-approved

#6426 Organize Article Callbacks
  app/models/article.rb
Labels: PR: reviewed-approved

#6428 Fix invalid ERB in featured author link.
  app/javascript/articles/FeaturedArticle.jsx
  app/javascript/articles/__tests__/__snapshots__/FeaturedArticle.test.jsx.snap
Labels: PR: reviewed-approved

#6431 Check presence of auth_data_dump
  app/views/internal/users/edit.html.erb
Labels: PR: reviewed-approved

#6433 Don't Repeatedly Hit the Cache for User Data
  app/services/articles/feed.rb
Labels: PR: reviewed-approved

#6432 Skip vomit reactions on banned users
  app/views/internal/feedback_messages/index.html.erb
Labels: PR: reviewed-approved

#6422 Fixes html_safe issues from comment domain
  .erb-lint.yml
  app/liquid_tags/liquid_tag_base.rb
  app/liquid_tags/podcast_tag.rb
  app/liquid_tags/tweet_tag.rb
  app/models/comment.rb
  app/views/comments/_comment_proper.html.erb
  app/views/comments/_liquid.html.erb
  app/views/comments/delete_confirm.html.erb
  app/views/comments/index.html.erb
Labels: PR: reviewed-approved

#6372 Search ClassifiedListings frontend code
  app/controllers/search_controller.rb
  app/javascript/listings/listings.jsx
  config/routes.rb
  spec/requests/search_spec.rb
Labels: PR: unreviewed

#6429 Do not render or link to empty rss feeds
  app/controllers/articles_controller.rb
  app/helpers/application_helper.rb
  app/views/articles/index.html.erb
  app/views/users/_meta.html.erb
  spec/requests/articles/articles_spec.rb
  spec/requests/rss_feed_spec.rb
  spec/requests/user/user_profile_spec.rb
Labels: PR: reviewed-approved

#6423 Invert the text color for social icons in case of dark themes
  app/assets/stylesheets/scaffolds.scss
Labels: PR: reviewed-approved

#6441 Update ES docs for min/max versions and macOS brew
  docs/installation/linux.md
  docs/installation/mac.md
  docs/installation/windows.md
Labels: PR: reviewed-approved

#6435 Remove Algolia for ClassifiedListings
  app/controllers/concerns/classified_listings_toolkit.rb
  app/models/classified_listing.rb
  db/seeds.rb
Labels: PR: reviewed-approved

#6427 Restore featured story on timeframe pages for logged out users
  app/controllers/stories_controller.rb
  app/services/articles/feed.rb
  spec/services/articles/feed_spec.rb
  spec/system/articles/user_visits_articles_by_timeframe_spec.rb
Labels: PR: reviewed-approved

#6413 Improve API docs for articles, add listings to it and fix bugs
  app/controllers/api/v0/api_controller.rb
  app/controllers/api/v0/classified_listings_controller.rb
  app/controllers/classified_listings_controller.rb
  app/controllers/concerns/classified_listings_toolkit.rb
  app/models/classified_listing.rb
  app/views/classified_listings/_form.html.erb
  app/views/classified_listings/_form_errors.html.erb
  app/views/classified_listings/edit.html.erb
  docs/api_v0.yml
  docs/contributing_api.md
  spec/models/classified_listing_spec.rb
  spec/requests/api/v0/classified_listings_spec.rb
  spec/requests/classified_listings_spec.rb
Labels: PR: reviewed-approved

#6434 Remove Global Feed cache key
  app/services/articles/feed.rb
Labels: PR: reviewed-approved

#6446 Removed file for feed that is no longer used.
  app/javascript/packs/Feed.jsx.erb
Labels: PR: reviewed-approved, area: homepage, tech: fullstack

#6445 Fix style issues on liquid tag embed page
  app/views/layouts/_styles.html.erb
  app/views/liquid_embeds/show.html.erb
  spec/requests/liquid_embeds_spec.rb
Labels: PR: reviewed-approved

#6443 Bump min version of PostgreSQL from 9.4 to 9.5
  README.md
  docs/installation/linux.md
  docs/installation/mac.md
  docs/installation/windows.md
Labels: PR: reviewed-approved

#6442 Enable caching in Redis in development
  config/environments/development.rb
Labels: PR: reviewed-approved

#6448 Fix tags autocomplete deleting input with fast typing
  app/javascript/shared/components/tags.jsx
Labels: PR: reviewed-approved

#6451 Add more tag weight/more random variant
  app/controllers/stories/feeds_controller.rb
  app/services/articles/feed.rb
  config/field_test.yml
  spec/services/articles/feed_spec.rb
Labels: PR: reviewed-approved

#6455 Revert 6395 dependabot/bundler/twilio ruby 5.31.5
  Gemfile
  Gemfile.lock
Labels: PR: reviewed-approved

#6453 Remove Greetings workflows
  .github/workflows/greetings.yml
Labels: PR: reviewed-approved

#6456 Now reactions are always shown
  app/javascript/articles/__tests__/FeaturedArticle.test.jsx
  app/javascript/articles/__tests__/__snapshots__/Article.test.jsx.snap
  app/javascript/articles/__tests__/__snapshots__/FeaturedArticle.test.jsx.snap
  app/javascript/articles/components/ReactionsCount.jsx
Labels: PR: reviewed-approved, area: homepage, tech: javascript

#6437 Added nickytonline.dev-to-extension-pack to the VSCode recommendations
  .vscode/extensions.json
Labels: PR: reviewed-approved

#6450 Create Searchable Specs and Remove Redundant specs from AR models
  spec/models/chat_channel_membership_spec.rb
  spec/models/classified_listing_spec.rb
  spec/models/concerns/searchable_spec.rb
  spec/models/tag_spec.rb
Labels: PR: reviewed-approved

#6449 Add field test variant info to Honeycomb
  app/controllers/stories/feeds_controller.rb
Labels: PR: reviewed-approved

#6458 API: Access unpublished listings only if you are the owner
  app/controllers/api/v0/api_controller.rb
  app/controllers/api/v0/classified_listings_controller.rb
  docs/api_v0.yml
  spec/requests/api/v0/classified_listings_spec.rb
Labels: PR: reviewed-approved

#6470 Getting rid of min-height on saved articles contianer
  app/assets/stylesheets/item-list.scss
Labels: PR: reviewed-approved, area: reading list/history, tech: html/css

#6459 Install Blazer for Querying the Database Via Admin
  Gemfile
  Gemfile.lock
  config/blazer.yml
  config/routes.rb
  db/migrate/20200304164719_install_blazer.rb
  db/schema.rb
Labels: PR: reviewed-approved

#6463 Remove more Algolia from ClassifiedListing
  config/initializers/algoliasearch.rb
  lib/tasks/fetch.rake
Labels: PR: reviewed-approved

#6151 Fixing doesn't exist thumbs down image
  app/labor/reaction_image.rb
  spec/factories/reactions.rb
  spec/requests/notifications_spec.rb
Labels: PR: reviewed-approved

#6439 Fix notification cannot be clicked in notifications page
  app/assets/stylesheets/notifications.scss
Labels: PR: reviewed-approved

#6477 Remove Shipping Fields from Users
  app/labor/mailchimp_bot.rb
  app/models/user.rb
  db/migrate/20200304220534_remove_user_shipping_fields.rb
  db/schema.rb
  spec/labor/mailchimp_bot_spec.rb
Labels: PR: reviewed-approved

#6464 Remove Algolia from Comments
  app/javascript/article-form/elements/__mocks__/algoliasearch.js
  app/javascript/chat/__mocks__/algoliasearchUsers.js
  app/models/comment.rb
  app/workers/search/index_worker.rb
  config/initializers/algoliasearch.rb
  db/seeds.rb
  spec/models/comment_spec.rb
  spec/workers/search/index_worker_spec.rb
Labels: PR: reviewed-approved

#6483 Add a mascot_user_id to SiteConfig
  app/controllers/internal/configs_controller.rb
  app/models/site_config.rb
  app/views/internal/configs/show.html.erb
  spec/requests/internal/configs_spec.rb
Labels: PR: reviewed-approved

#6487 Fix Spelling for Elasticsearch User Field
  config/elasticsearch/mappings/users.json
Labels: PR: reviewed-approved

#6496 Cookie Expiry for the Campaign Hero Banner and Event Listener update
  app/assets/javascripts/initializers/initializeHeroBannerClose.js
Labels: PR: reviewed-approved

#6492 Fixed app/javascript/chat/channels.jsx eslint error
  app/javascript/chat/channels.jsx
Labels: PR: reviewed-approved

#6498 Switch from cookies to localstorage for hero banner
  app/assets/javascripts/initializers/initializeHeroBannerClose.js
  app/controllers/stories_controller.rb
  app/views/layouts/application.html.erb
Labels: PR: reviewed-approved

#6501 Small fixes/adjustments
  app/controllers/stories_controller.rb
  app/views/articles/_sidebar_campaign.html.erb
  app/views/layouts/application.html.erb
Labels: PR: reviewed-approved

#6504 Run Elasticsearch update before DataUpdateScripts
  bin/update
Labels: PR: reviewed-approved

#6490 Guarantee articles in main article feed
  app/services/articles/feed.rb
  spec/services/articles/feed_spec.rb
Labels: PR: reviewed-approved

#6494 Move followings to internal API
  app/assets/javascripts/initializers/initScrolling.js.erb
  app/controllers/api/v0/followings_controller.rb
  app/controllers/followings_controller.rb
  app/views/followings/organizations.json.jbuilder
  app/views/followings/podcasts.json.jbuilder
  app/views/followings/tags.json.jbuilder
  app/views/followings/users.json.jbuilder
  config/routes.rb
  spec/requests/followings_spec.rb
Labels: PR: reviewed-approved

#6329 Move onboarding tags from public to internal API
  app/controllers/api/v0/tags_controller.rb
  app/controllers/internal/configs_controller.rb
  app/controllers/tags_controller.rb
  app/javascript/onboarding/components/FollowTags.jsx
  app/views/tags/onboarding.json.jbuilder
  config/routes.rb
  spec/requests/api/v0/tags_spec.rb
  spec/requests/tags_spec.rb
Labels: PR: reviewed-approved

#6503 Add explicit note about `cd`ing into Elasticsearch before starting
  docs/installation/mac.md
Labels: PR: reviewed-approved

#6486 Convert internal listing table view to bootstrap
  app/controllers/internal/classified_listings_controller.rb
  app/views/internal/classified_listings/index.html.erb
Labels: PR: reviewed-approved

#6476 fixed some eslint errors
  app/javascript/article-form/elements/errors.jsx
  app/javascript/articles/Feed.jsx
  app/javascript/articles/LoadingArticle.jsx
  app/javascript/chat/article.jsx
  app/javascript/chat/channelDetails.jsx
Labels: PR: reviewed-approved

#6489 Index Users into Elasticsearch
  app/models/user.rb
  app/serializers/search/user_serializer.rb
  config/elasticsearch/mappings/users.json
  lib/data_update_scripts/20200305201627_index_users_to_elasticsearch.rb
  spec/lib/data_update_scripts/index_users_to_elasticsearch_spec.rb
  spec/models/user_spec.rb
  spec/serializers/search/user_serializer_spec.rb
Labels: PR: reviewed-approved

#6502 Change sponsorClickHandler to standard function declaration
  app/assets/javascripts/initializers/initializeSponsorshipVisibility.js
Labels: PR: reviewed-approved

#6507 Hide banished users vomit confirmations and delete vomit reactions on banish
  app/models/user.rb
  app/services/moderator/banish_user.rb
  app/views/internal/feedback_messages/index.html.erb
  spec/services/moderator/banish_user_spec.rb
Labels: PR: reviewed-approved

#6493 Show hidden comments on article mod page
  app/controllers/moderations_controller.rb
  app/views/moderations/mod.html.erb
  spec/system/articles/moderator_moderates_an_article.rb
Labels: PR: reviewed-approved

#6509 Error message & bad request on failed user update
  app/controllers/users_controller.rb
Labels: PR: reviewed-approved

#6495 Use cache_key_heroku_slug helper more consistently
  app/views/articles/_sidebar.html.erb
  app/views/feedback_messages/index.html.erb
  app/views/moderations/mod.html.erb
  app/views/pages/live.html.erb
  app/views/pages/onboarding.html.erb
  app/views/partnerships/index.html.erb
  app/views/partnerships/show.html.erb
  app/views/pro_memberships/show.html.erb
Labels: PR: reviewed-approved

#6488 Index Articles and Podcast Episodes to Elasticsearch
  app/models/article.rb
  app/models/podcast_episode.rb
  app/serializers/search/article_serializer.rb
  app/serializers/search/nested_user_serializer.rb
  app/serializers/search/podcast_episode_serializer.rb
  config/elasticsearch/mappings/feed_content.json
  lib/data_update_scripts/20200305201642_index_feed_content_to_elasticsearch.rb
  spec/lib/data_update_scripts/index_feed_content_to_elasticsearch_spec.rb
  spec/models/article_spec.rb
  spec/models/podcast_episode_spec.rb
  spec/serializers/search/article_serializer_spec.rb
  spec/serializers/search/podcast_episode_serializer_spec.rb
Labels: PR: reviewed-approved

#6515 Dont Run Indexing Sidekiq Jobs to Fix Banish User Spec
  spec/services/moderator/banish_user_spec.rb
Labels: PR: reviewed-approved

#6513 Let mods mark articles that require approval as approved.
  app/assets/stylesheets/moderators.scss
  app/controllers/article_approvals_controller.rb
  app/views/moderations/mod.html.erb
  config/routes.rb
  spec/requests/article_approvals_spec.rb
Labels: PR: unreviewed

#6516 Convert Flare Tag to json string before indexing
  app/serializers/search/article_serializer.rb
Labels: PR: reviewed-approved

#6482 Comments API: hide deleted and hidden comments (plus docs)
  app/controllers/api/v0/comments_controller.rb
  app/models/comment.rb
  app/views/api/v0/comments/_comment.json.jbuilder
  docs/api_v0.yml
  spec/requests/api/v0/comments_spec.rb
Labels: PR: reviewed-approved, area: api-v0

#6505 Fix 404 page css
  public/404.html
Labels: PR: reviewed-approved

#6524 removes negative margin and adds backgroundcolor to next element instead
  app/assets/stylesheets/dashboard.scss
Labels: PR: reviewed-approved

#6525 Allow tag mods to approve posts even if they mod just one tag
  app/controllers/article_approvals_controller.rb
  spec/requests/article_approvals_spec.rb
Labels: PR: unreviewed

#6527 Add CodeNewbie podcast to seeds
  db/seeds.rb
Labels: PR: reviewed-approved

#6514 API Specification: Change type 'date' to 'string' on Create/Update Listings
  docs/api_v0.yml
Labels: PR: reviewed-approved

#6461 Create Hypershield Schema to Shield Sensitive data in Production
  Gemfile
  Gemfile.lock
  config/initializers/hypershield.rb
Labels: PR: reviewed-approved

#6531 Keeping your forked branch up to date
  docs/getting-started/syncing.md
  scripts/sync_fork.sh
Labels: PR: reviewed-approved

#6517 destroy_all classified_listings when deleting User activity
  app/services/users/delete_activity.rb
Labels: PR: reviewed-approved

#6484 Use mascot_account in place of welcoming_account
  Envfile
  app/models/user.rb
  app/services/notifications/welcome_notification/send.rb
  config/environments/production.rb
  spec/requests/notifications_spec.rb
  spec/services/notifications/welcome_notification/send_spec.rb
Labels: PR: reviewed-approved

#6541 Only Activate Hypershield in Production
  Gemfile
  config/initializers/hypershield.rb
Labels: PR: reviewed-approved

#6519 Validate API OpenAPI 3 spec
  .validaterc
  docs/api_v0.yml
  docs/contributing_api.md
  package.json
  yarn.lock
Labels: PR: reviewed-approved, area: api-v0

#6538 Store Flare Tag as a Hash in Elasticsearch
  app/serializers/search/article_serializer.rb
  config/elasticsearch/mappings/feed_content.json
  spec/serializers/search/article_serializer_spec.rb
Labels: PR: reviewed-approved

#6035 Podcast playback update for iOS app native implementation
  app/assets/javascripts/initializers/initializePodcastPlayback.js
  app/views/shell/_top.html.erb
Labels: PR: unreviewed

#6520 Fix scripts startup check for development mode
  app/models/data_update_script.rb
  spec/models/data_update_script_spec.rb
Labels: PR: reviewed-approved

#6547 Skip /ahoy/ in serviceworkers
  app/views/service_worker/index.js.erb
Labels: PR: reviewed-approved

#6473 Re-enable correct operation of liquid tags with scripts in articles
  app/liquid_tags/liquid_tag_base.rb
  app/liquid_tags/podcast_tag.rb
  app/liquid_tags/poll_tag.rb
  app/liquid_tags/runkit_tag.rb
  app/liquid_tags/tweet_tag.rb
  app/views/articles/show.html.erb
Labels: PR: reviewed-approved

#6532 Removed unused campaign settings
  app/controllers/internal/configs_controller.rb
  app/models/site_config.rb
  app/views/internal/configs/show.html.erb
Labels: PR: reviewed-approved

#6554 remove Hypershield
  Gemfile
  Gemfile.lock
  config/initializers/hypershield.rb
Labels: PR: reviewed-approved

#6553 [honeycomb] make error reporting concise
  app/controllers/users_controller.rb
Labels: PR: reviewed-approved

#6511 Create comment ranking feed experiment
  app/controllers/stories/feeds_controller.rb
  app/services/articles/feed.rb
  config/field_test.yml
  spec/services/articles/feed_spec.rb
Labels: PR: unreviewed

#6540 Prune old field tests for ongoing experiments
  app/workers/field_tests/prune_old_experiments_worker.rb
  lib/tasks/fetch.rake
  spec/factories/field_test_memberships.rb
  spec/workers/field_tests/prune_old_experiments_worker_spec.rb
Labels: PR: reviewed-approved

#6557 Rename feed method to correct name
  app/services/articles/feed.rb
  spec/services/articles/feed_spec.rb
Labels: PR: unreviewed

#6558 Rename one more method
  app/services/articles/feed.rb
Labels: PR: unreviewed

#6506 Refactor debounce usage into debounceAction util
  app/javascript/chat/chat.jsx
  app/javascript/listings/listings.jsx
  app/javascript/readingList/readingList.jsx
  app/javascript/shared/components/tags.jsx
  app/javascript/src/utils/debounceAction.js
Labels: PR: reviewed-approved

#6491 Fixed listings/dashboard/rowElements/location.jsx eslint error
  app/javascript/listings/dashboard/rowElements/location.jsx
Labels: PR: reviewed-approved

#6237 Implement KatexTag
  Gemfile
  Gemfile.lock
  app/assets/config/manifest.js
  app/assets/stylesheets/ltags/KatexTag.scss
  app/liquid_tags/katex_tag.rb
  app/views/liquids/_katex.html.erb
  app/views/pages/_editor_guide_text.html.erb
  config/initializers/redcarpet.rb
  spec/fixtures/approvals/katextag/render/generates_katex_output.approved.html
  spec/liquid_tags/katex_tag_spec.rb
  spec/support/fixtures/approvals/user_preview_article_body.approved.html
Labels: PR: unreviewed

#6556 Dont Issue Destroy Call to Chat Channel Memberships Multiple Times
  app/services/users/cleanup_chat_channels.rb
Labels: PR: reviewed-approved

#6560 Allow preview image URL form to be visible for articles with videos
  app/assets/stylesheets/preact/article-form.scss
Labels: PR: reviewed-approved

#6561 Skip /welcome in serviceworkers
  app/views/service_worker/index.js.erb
Labels: PR: reviewed-approved

#6529 API: Remove reactions onboarding
  app/controllers/api/v0/reactions_controller.rb
  app/workers/reactions/create_worker.rb
  config/routes.rb
  spec/workers/reactions/create_worker_spec.rb
Labels: PR: reviewed-approved, area: api-v0

#6566 Make bin/setup predictable and repeatable and remove bin/update
  bin/setup
  bin/update
  docs/backend/data-update-scripts.md
Labels: PR: reviewed-approved

#6522 Create implicit experience level rating vote upon creating of readinglist reaction
  app/controllers/comments_controller.rb
  app/controllers/rating_votes_controller.rb
  app/controllers/reactions_controller.rb
  app/models/rating_vote.rb
  app/workers/rating_votes/assign_rating_worker.rb
  db/migrate/20200303222558_add_context_to_rating_votes.rb
  db/migrate/20200308144606_add_intdex_to_rating_votes.rb
  db/schema.rb
  spec/models/rating_vote_spec.rb
  spec/requests/reactions_spec.rb
  spec/workers/rating_votes/assign_rating_worker_spec.rb
Labels: PR: reviewed-approved

#5687 Allow `cover_image` of an article to be removed
  app/models/article.rb
  spec/factories/articles.rb
  spec/fixtures/files/article_published_empty_cover_image.txt
  spec/models/article_spec.rb
  spec/requests/api/v0/articles_spec.rb
Labels: PR: reviewed-approved

#6568 use beeline 2.0
  Gemfile
  Gemfile.lock
  spec/lib/sidekiq/honeycomb_middleware_spec.rb
Labels: PR: unreviewed

#6570 Remove flash notice to avoid cache leak
  app/views/comments/_form.html.erb
Labels: PR: reviewed-approved

#6521 fixed some eslint errors
  app/javascript/.eslintrc.js
  app/javascript/onboarding/components/IntroSlide.jsx
  app/javascript/packs/homePage.jsx
  app/javascript/podcasts/PodcastFeed.jsx
  app/javascript/sidebar-widget/SidebarWidget.jsx
Labels: PR: reviewed-approved

#6569 Move math around parenthases in score_experience_level
  app/services/articles/feed.rb
  spec/services/articles/feed_spec.rb
Labels: PR: unreviewed

#6565 Improved the podcasts seeds
  .gitignore
  db/seeds.rb
Labels: PR: reviewed-approved

#6562 Disallow /mod/ in robots.txt
  app/views/articles/tags/_sidebar.html.erb
  app/views/pages/robots.text.erb
Labels: PR: reviewed-approved

#6528 Add .slugignore
  .slugignore
Labels: PR: reviewed-approved

#6564 Set user, password and db for postgres docker
  docker-compose.yml
Labels: PR: reviewed-approved

#6530 Allow admins to delete users without emails
  app/controllers/internal/users_controller.rb
  app/models/user.rb
  app/workers/users/delete_worker.rb
  spec/requests/internal/users_spec.rb
  spec/system/internal/admin_deletes_user_spec.rb
Labels: PR: reviewed-approved

#6440 Search::Client refactor
  app/services/search/client.rb
Labels: PR: reviewed-approved

#6573 Remove extra HoneycombClient
  config/initializers/honeycomb.rb
Labels: PR: reviewed-approved

#6551 API: add docs for /followers/users and remove organizations endpoint
  app/controllers/api/v0/followers_controller.rb
  app/models/follow.rb
  app/views/api/v0/followers/_follows.json.jbuilder
  app/views/api/v0/followers/organizations.json.jbuilder
  docs/api_v0.yml
  spec/requests/api/v0/followers_spec.rb
Labels: PR: reviewed-approved, area: api-v0

#6575 Add internal and admin to robots.txt disallow
  app/views/pages/robots.text.erb
Labels: PR: reviewed-approved

#6581 Move chat_channel info to internal API
  app/controllers/api/v0/chat_channels_controller.rb
  app/controllers/chat_channels_controller.rb
  app/javascript/chat/chat.jsx
  app/views/chat_channels/channel_info.json.jbuilder
  config/routes.rb
  spec/requests/api/v0/chat_channels_spec.rb
  spec/requests/chat_channels_spec.rb
Labels: PR: reviewed-approved

#6555 API: add docs for podcast episodes endpoint
  docs/api_v0.yml
  spec/requests/api/v0/podcasts_episodes_spec.rb
Labels: PR: unreviewed, area: api-v0

#6583 Added docs for tags API
  docs/api_v0.yml
Labels: PR: draft, area: api-v0

#6580 Github Liquid tag: Fix error when repository has no README + refactor
  app/liquid_tags/github_tag/github_readme_tag.rb
  app/views/liquids/_github_readme.html.erb
  spec/liquid_tags/github_tag/github_readme_tag_spec.rb
Labels: PR: reviewed-approved

#6577 Keep old listings visible until the new ones populated
  app/javascript/listings/listings.jsx
Labels: PR: reviewed-approved

#6572 Remove redundant yarn step for Docker
  docs/installation/docker.md
Labels: PR: reviewed-approved

#5788 Don't escape markup sensitive characters in <title>
  app/views/shell/_bottom.html.erb
Labels: PR: unreviewed

#6582 Fix Github repo pin and and unpin
  app/controllers/github_repos_controller.rb
  spec/requests/github_repos_spec.rb
Labels: PR: reviewed-approved

#6574 Allow Blazer to be queried by Tech Admins
  config/routes.rb
Labels: PR: unreviewed

#6539 added spec for chat_channels_memberships_controller.rb
  app/controllers/chat_channel_memberships_controller.rb
  app/controllers/chat_channels_controller.rb
  app/views/chat_channel_memberships/edit.html.erb
  spec/requests/chat_channel_memberships_spec.rb
  spec/requests/chat_channels_spec.rb
Labels: PR: unreviewed

#6334 CSS Components, Variables + Utility classes
  app/assets/stylesheets/_colors.scss
  app/assets/stylesheets/_spacing-units.scss
  app/assets/stylesheets/base/boxes.scss
  app/assets/stylesheets/base/colors.scss
  app/assets/stylesheets/base/decorations.scss
  app/assets/stylesheets/base/flexbox.scss
  app/assets/stylesheets/base/grid.scss
  app/assets/stylesheets/base/icons.scss
  app/assets/stylesheets/base/layout.scss
  app/assets/stylesheets/base/positioning.scss
  app/assets/stylesheets/base/reset.scss
  app/assets/stylesheets/base/sizing.scss
  app/assets/stylesheets/base/spacing.scss
  app/assets/stylesheets/base/typography.scss
  app/assets/stylesheets/components/avatars.scss
  app/assets/stylesheets/components/buttons.scss
  app/assets/stylesheets/components/dropdowns.scss
  app/assets/stylesheets/components/forms.scss
  app/assets/stylesheets/components/indicators.scss
  app/assets/stylesheets/components/modals.scss
  app/assets/stylesheets/components/navigation.scss
  app/assets/stylesheets/components/notices.scss
  app/assets/stylesheets/item-list.scss
  app/assets/stylesheets/minimal.scss
  app/assets/stylesheets/scaffolds.scss
  app/assets/stylesheets/vars/_colors.scss
  app/assets/stylesheets/vars/_spacing-units.scss
  app/assets/stylesheets/vars/_typography.scss
  app/assets/stylesheets/vars/_utils.scss
  app/assets/stylesheets/vars/_variables.scss
  app/controllers/pages_controller.rb
  app/views/layouts/_styles.html.erb
  app/views/pages/crayons.html.erb
  config/routes.rb
Labels: PR: unreviewed, tech: html/css

#6621 Remove unused JavaScript
  app/views/internal/mods/index.html.erb
Labels: PR: reviewed-approved

#6611 API: add users and videos docs
  app/controllers/api/v0/videos_controller.rb
  docs/api_v0.yml
  docs/contributing_api.md
Labels: PR: reviewed-approved, area: api-v0

#6601 Move user following suggestions to internal API
  app/controllers/api/v0/users_controller.rb
  app/controllers/users_controller.rb
  app/javascript/onboarding/components/FollowUsers.jsx
  app/javascript/sidebar-widget/SidebarWidget.jsx
  app/views/users/index.json.jbuilder
  config/routes.rb
  spec/requests/api/v0/users_spec.rb
  spec/requests/user/user_suggestions_spec.rb
Labels: PR: reviewed-approved

#6626 Search Users for Chat Channels Frontend
  app/javascript/chat/__mocks__/algoliasearchUsers.js
  app/javascript/chat/__tests__/__snapshots__/channelDetails.test.jsx.snap
  app/javascript/chat/__tests__/channelDetails.test.jsx
  app/javascript/chat/channelDetails.jsx
  lib/data_update_scripts/20200313123108_index_users_to_elasticsearch.rb
  spec/lib/data_update_scripts/index_users_to_elasticsearch_spec.rb
Labels: PR: reviewed-approved

#6629 Fix wonky line-heights on titles
  app/assets/stylesheets/article-show.scss
  app/assets/stylesheets/articles.scss
Labels: PR: unreviewed

#6624 Upgrade rspec-rails, ruby-prof and webmock
  Gemfile.lock
Labels: PR: reviewed-approved

#6623 Upgrade octokit and rouge
  Gemfile.lock
Labels: PR: reviewed-approved

#6465 Render DEV's ASCII art as stdout
  db/seeds.rb
Labels: PR: reviewed-approved

#6635 Fix editor jump
  app/assets/stylesheets/preact/article-form.scss
  app/views/articles/_v2_form.html.erb
Labels: PR: unreviewed

#6637 Fix a couple margins
  app/assets/stylesheets/comments.scss
  app/views/devise/shared/_authorization_error.html.erb
Labels: PR: unreviewed

#6615 Add response templates model and table
  app/models/response_template.rb
  app/models/user.rb
  app/services/users/delete_activity.rb
  db/migrate/20200311170959_create_response_templates_table.rb
  db/schema.rb
  spec/factories/response_templates.rb
  spec/models/response_template_spec.rb
Labels: PR: reviewed-approved

#6625 API docs: cleanup parameters
  docs/api_v0.yml
Labels: PR: reviewed-approved, area: api-v0

#6636 fix cannot read privacy policy redirect to onboarding
  app/javascript/packs/onboardingRedirectCheck.jsx
Labels: PR: reviewed-approved

#6641 Allow admins to define core sidebar tags in config
  app/controllers/internal/configs_controller.rb
  app/models/article.rb
  app/models/site_config.rb
  app/views/articles/_sidebar_additional.html.erb
  app/views/internal/configs/show.html.erb
  spec/requests/internal/configs_spec.rb
Labels: PR: reviewed-approved

#6648 Rubocop fixes
  spec/system/admin/admin_dashboard_presented_spec.rb
  spec/workers/comments/calculate_score_worker_spec.rb
Labels: PR: reviewed-approved

#6628 Enable Hypershield in Production Take 2
  Gemfile
  Gemfile.lock
  config/initializers/hypershield.rb
Labels: PR: reviewed-approved

#6620 Extract Onboarding into it's own controller
  app/controllers/onboardings_controller.rb
  app/controllers/pages_controller.rb
  app/views/onboardings/show.html.erb
  config/routes.rb
  spec/requests/onboardings_spec.rb
Labels: PR: reviewed-approved

#6666 Only Enable Hypershield if ENV variable is present
  config/initializers/hypershield.rb
Labels: PR: reviewed-approved

#6662 Allow community admins to alter site description
  app/controllers/internal/configs_controller.rb
  app/models/site_config.rb
  app/views/articles/feed.rss.builder
  app/views/articles/index.html.erb
  app/views/articles/search/_meta.html.erb
  app/views/classified_listings/index.html.erb
  app/views/internal/configs/show.html.erb
  app/views/service_worker/manifest.json.erb
  app/views/videos/index.html.erb
  spec/requests/internal/configs_spec.rb
  spec/requests/stories_index_spec.rb
Labels: PR: reviewed-approved

#6633 Add two new experiments and one new conversion event
  app/controllers/stories/feeds_controller.rb
  app/models/page_view.rb
  app/services/articles/feed.rb
  app/workers/users/record_field_test_event_worker.rb
  config/field_test.yml
  spec/services/articles/feed_spec.rb
  spec/workers/users/record_field_test_event_worker_spec.rb
Labels: PR: reviewed-approved

#6619 Denote previously reported and suspended users in vomit reactions
  app/models/user.rb
  app/views/internal/feedback_messages/_abuse_reports.html.erb
  app/views/internal/feedback_messages/_feedback_message.html.erb
  app/views/internal/feedback_messages/_latest_articles.html.erb
  app/views/internal/feedback_messages/_potential_spam_users.html.erb
  app/views/internal/feedback_messages/index.html.erb
Labels: PR: reviewed-approved

#6670 Allow KaTeX to render inline
  app/liquid_tags/katex_tag.rb
  app/views/liquids/_katex.html.erb
  app/views/pages/_editor_guide_text.html.erb
  spec/liquid_tags/katex_tag_spec.rb
Labels: PR: reviewed-approved

#6664 Upgrade to webpacker/webpack 4 and Babel 7
  .babelrc
  .travis.yml
  Gemfile
  Gemfile.lock
  app/javascript/articles/__stories__/Article.stories.jsx
  app/javascript/articles/__stories__/FeaturedArticle.stories.jsx
  app/javascript/articles/__stories__/LoadingArticle.stories.jsx
  app/javascript/chat/__tests__/__snapshots__/channelDetails.test.jsx.snap
  app/javascript/chat/__tests__/__snapshots__/githubRepo.test.jsx.snap
  app/javascript/designSystem/__stories__/avatarsAndLogos.stories.jsx
  app/javascript/designSystem/__stories__/boxes.stories.jsx
  app/javascript/designSystem/__stories__/buttons.stories.jsx
  app/javascript/designSystem/__stories__/dropdowns.stories.jsx
  app/javascript/designSystem/__stories__/formElements.stories.jsx
  app/javascript/designSystem/__stories__/indicators.stories.jsx
  app/javascript/designSystem/__stories__/mainNavigation.stories.jsx
  app/javascript/designSystem/__stories__/modals.stories.jsx
  app/javascript/designSystem/__stories__/navigationTabs.stories.jsx
  app/javascript/designSystem/__stories__/notices.stories.jsx
  app/javascript/designSystem/__stories__/typography.stories.jsx
  app/javascript/listings/__tests__/__snapshots__/singleListing.test.jsx.snap
  app/javascript/podcasts/__stories__/PodcastEpisode.stories.jsx
  app/javascript/podcasts/__stories__/TodaysPodcasts.stories.jsx
  app/javascript/src/components/Search/__stories__/SearchForm.stories.jsx
  app/views/articles/_actions.html.erb
  app/views/articles/edit.html.erb
  app/views/articles/index.html.erb
  app/views/articles/new.html.erb
  app/views/articles/show.html.erb
  app/views/articles/stats.html.erb
  app/views/articles/tags/_sidebar_additional.html.erb
  app/views/chat_channels/index.html.erb
  app/views/classified_listings/_form.html.erb
  app/views/classified_listings/dashboard.html.erb
  app/views/classified_listings/index.html.erb
  app/views/dashboards/pro.html.erb
  app/views/layouts/internal.html.erb
  app/views/moderations/index.html.erb
  app/views/onboardings/show.html.erb
  app/views/pages/live.html.erb
  app/views/reading_list_items/index.html.erb
  app/views/shell/_top.html.erb
  app/views/tags/edit.html.erb
  app/views/users/_integrations.html.erb
  app/views/users/_org_admin.html.erb
  app/views/users/_org_non_member.html.erb
  app/views/users/_profile.html.erb
  app/views/users/show.html.erb
  babel.config.js
  config/webpack/environment.js
  config/webpacker.yml
  docs/frontend/preact.md
  docs/frontend/webpacker.md
  package.json
  yarn.lock
Labels: PR: unreviewed

#6669 Remove Unused algoliaFollowedArticles Function
  app/assets/javascripts/initializePage.js.erb
  app/assets/javascripts/initializers/initializeFetchFollowedArticles.js.erb
Labels: PR: reviewed-approved

#6671 Remove leading whitespace in tags during RSS import
  app/services/rss_reader/assembler.rb
Labels: PR: reviewed-approved

#6672 Fix VCR warnings and use initializers
  spec/models/tweet_spec.rb
  spec/rails_helper.rb
  spec/requests/liquid_embeds_spec.rb
  spec/support/initializers/doorkeeper.rb
  spec/support/initializers/vcr.rb
Labels: PR: reviewed-approved
