Repository forem/forem, pull requests merged in 2020-01, with the labels that each got.

#5324 Clear Sidekiq jobs between tests
  spec/rails_helper.rb
Labels: PR: reviewed-approved

#5320 Remove Article cache bust Delayed Job
  app/jobs/articles/bust_cache_job.rb
  spec/jobs/articles/bust_cache_job_spec.rb
Labels: PR: reviewed-approved

#5312 Change MentionJob to MentionWorker and move to sidekiq
  app/models/notification.rb
  app/workers/notifications/mention_worker.rb
  spec/requests/notifications_spec.rb
  spec/workers/notifications/mention_worker_spec.rb
Labels: PR: reviewed-approved

#5330 Enable cache logging in development if requested
  config/initializers/cache_logger.rb
  config/initializers/silence_cache_log.rb
Labels: PR: reviewed-approved

#5326 Sidekiq: add test helpers
  spec/rails_helper.rb
  spec/support/sidekiq_test_helpers.rb
  spec/workers/rate_limit_checker_worker_spec.rb
Labels: PR: reviewed-approved

#5329 Rails 5.2 features: enable cache versioning (recyclable keys)
  config/initializers/new_framework_defaults_5_2.rb
Labels: PR: reviewed-approved

#5299 Allow language-xxx class detection on pre tags in ReverseMarkdown
  app/lib/reverse_markdown/converters/custom_pre.rb
  spec/lib/reverse_markdown/converters/custom_pre_spec.rb
Labels: PR: reviewed-approved

#5280 Fix event propagation for click on tag rules in editor
  app/javascript/article-form/elements/__tests__/__snapshots__/tags.test.jsx.snap
  app/javascript/article-form/elements/__tests__/tags.test.jsx
  app/javascript/shared/components/tags.jsx
Labels: PR: reviewed-approved

#5331 Create UpdateAnalyticsWorker to replace UpdateAnalyticsJob
  app/controllers/async_info_controller.rb
  app/controllers/dashboards_controller.rb
  app/workers/articles/update_analytics_worker.rb
  spec/workers/articles/update_analytics_worker_spec.rb
Labels: PR: reviewed-approved

#5327 Change create first reaction job to worker
  app/models/comment.rb
  app/workers/comments/create_first_reaction_worker.rb
  spec/models/comment_spec.rb
  spec/workers/comments/create_first_reaction_worker_spec.rb
Labels: PR: reviewed-approved

#5322 Refactors ActiveJob to SidekiqWorker: Follows::SendEmailNotificationWorker
  app/jobs/follows/send_email_notification_job.rb
  app/mailers/notify_mailer.rb
  app/models/follow.rb
  app/models/user.rb
  app/workers/follows/send_email_notification_worker.rb
  spec/models/follow_spec.rb
  spec/models/user_spec.rb
  spec/workers/follows/send_email_notification_worker_spec.rb
Labels: PR: reviewed-approved

#5338 pages bust cache job sidekiq refactor
  app/jobs/pages/bust_cache_job.rb
  app/models/page.rb
  app/workers/pages/bust_cache_worker.rb
  spec/jobs/pages/bust_cache_job_spec.rb
  spec/models/page_spec.rb
  spec/workers/pages/bust_cache_worker_spec.rb
Labels: PR: reviewed-approved

#5336 Handle missing commentable for user_is_commentable_author? check
  app/policies/comment_policy.rb
Labels: PR: reviewed-approved

#5341 Change from after_create to after_create_commit
  app/models/comment.rb
Labels: PR: unreviewed

#5343 Fixed a typo in a filename in docs.
  docs/design/branding.md
Labels: PR: reviewed-approved

#5337 Correctly Define InvalidAuthenticityToken error in helper module
  app/controllers/concerns/valid_request.rb
Labels: PR: reviewed-approved

#5347 Remove old create first reaction job
  app/jobs/comments/create_first_reaction_job.rb
  spec/jobs/comments/create_first_reaction_job_spec.rb
Labels: PR: reviewed-approved

#5349 delete unused mention job, update spec with helper
  app/jobs/notifications/mention_job.rb
  spec/jobs/notifications/mention_job_spec.rb
  spec/requests/notifications_spec.rb
Labels: PR: reviewed-approved

#5335 Remove unused UpdateAnalyticsJob code
  app/jobs/articles/update_analytics_job.rb
  spec/jobs/articles/update_analytics_job_spec.rb
Labels: PR: reviewed-approved

#5334 Sidekiq test helpers: retrieve jobs by worker
  spec/support/sidekiq_test_helpers.rb
Labels: PR: reviewed-approved

#5339 Refactor/internal ui update
  app/assets/stylesheets/internal/layout.scss
  app/controllers/internal/permissions_controller.rb
  app/views/internal/articles/_article_script.html.erb
  app/views/internal/articles/_individual_article.html.erb
  app/views/internal/articles/index.html.erb
  app/views/internal/badges/index.html.erb
  app/views/internal/broadcasts/_form.html.erb
  app/views/internal/broadcasts/edit.html.erb
  app/views/internal/broadcasts/index.html.erb
  app/views/internal/broadcasts/new.html.erb
  app/views/internal/chat_channels/index.html.erb
  app/views/internal/classified_listings/edit.html.erb
  app/views/internal/classified_listings/index.html.erb
  app/views/internal/comments/index.html.erb
  app/views/internal/configs/show.html.erb
  app/views/internal/events/_event_form.html.erb
  app/views/internal/events/index.html.erb
  app/views/internal/feedback_messages/_feedback_message.html.erb
  app/views/internal/feedback_messages/_style.html.erb
  app/views/internal/feedback_messages/index.html.erb
  app/views/internal/feedback_messages/show.html.erb
  app/views/internal/growth/_results.html.erb
  app/views/internal/growth/index.html.erb
  app/views/internal/mods/index.html.erb
  app/views/internal/organizations/_activity.html.erb
  app/views/internal/organizations/index.html.erb
  app/views/internal/organizations/show.html.erb
  app/views/internal/pages/_form.html.erb
  app/views/internal/pages/edit.html.erb
  app/views/internal/pages/index.html.erb
  app/views/internal/pages/new.html.erb
  app/views/internal/permissions/index.html.erb
  app/views/internal/podcasts/edit.html.erb
  app/views/internal/podcasts/index.html.erb
  app/views/internal/shared/_navbar.html.erb
  app/views/internal/tags/index.html.erb
  app/views/internal/tags/show.html.erb
  app/views/internal/tools/index.html.erb
  app/views/internal/users/_activity.erb
  app/views/internal/users/_credits.erb
  app/views/internal/users/_notes.erb
  app/views/internal/users/_user_organizations.html.erb
  app/views/internal/users/edit.html.erb
  app/views/internal/users/index.html.erb
  app/views/internal/users/show.html.erb
  app/views/internal/webhook_endpoints/index.html.erb
  app/views/internal/welcome/index.html.erb
  app/views/layouts/internal.html.erb
  config/initializers/assets.rb
Labels: PR: reviewed-approved

#5357 removes job moved to worker: follows send email notification
  app/jobs/follows/send_email_notification_job.rb
  spec/jobs/follows/send_email_notification_job_spec.rb
Labels: PR: reviewed-approved

#5354 Ignore dynotype run since that is used for console access
  datadog/prerun.sh
Labels: PR: reviewed-approved

#5375 Scope error message correctly for InvalidAuthenticityToken error
  app/controllers/concerns/valid_request.rb
Labels: PR: reviewed-approved

#5309 Migrate Articles/BustMultipleCachesJob to Sidekiq
  app/models/article.rb
  app/workers/articles/bust_multiple_caches_worker.rb
  spec/models/article_destroy_spec.rb
  spec/workers/articles/bust_multiple_caches_worker_spec.rb
Labels: PR: reviewed-approved

#5360 Refactor method in user_decorator.rb
  app/decorators/user_decorator.rb
Labels: PR: reviewed-approved

#5379 Move Events::BustCacheJob to Sidekiq and rename
  app/jobs/events/bust_cache_job.rb
  app/models/event.rb
  app/workers/events/bust_cache_worker.rb
  spec/jobs/events/bust_cache_job_spec.rb
  spec/models/event_spec.rb
  spec/workers/events/bust_cache_worker_spec.rb
Labels: PR: reviewed-approved

#5377 Record db table sizes in Datadog
  lib/tasks/fetch.rake
Labels: PR: reviewed-approved

#5378 Remove Comment user_touch Job and Do it Inline During Comment Creation
  app/jobs/comments/touch_user_job.rb
  app/models/comment.rb
  spec/jobs/comments/touch_user_job_spec.rb
  spec/models/comment_spec.rb
Labels: PR: reviewed-approved

#5376 Handle Missing article_id When Loading additional_content_boxes
  app/controllers/additional_content_boxes_controller.rb
  spec/requests/additional_content_boxes_spec.rb
Labels: PR: reviewed-approved

#5383 Fix internal/reports email form
  app/views/internal/feedback_messages/_feedback_message.html.erb
Labels: PR: reviewed-approved

#5358 use new_badge_achievement_worker instead of active job
  app/models/badge_achievement.rb
  app/models/notification.rb
  app/workers/notifications/new_badge_achievement_worker.rb
  spec/models/badge_achievement_spec.rb
  spec/models/notification_spec.rb
  spec/requests/notifications_spec.rb
  spec/system/internal/admin_awards_badges_spec.rb
  spec/workers/notifications/new_badge_achievement_worker_spec.rb
Labels: PR: reviewed-approved

#5380 Fix suggested tweets UI
  app/views/internal/articles/_article_script.html.erb
  app/views/internal/articles/index.html.erb
Labels: PR: reviewed-approved

#5388 Remove Articles/BustMultipleCachesJob
  app/jobs/articles/bust_multiple_caches_job.rb
  spec/jobs/articles/bust_multiple_caches_job_spec.rb
Labels: PR: reviewed-approved

#5356 Limit ALL Upload file sizes to 25 MB
  app/uploaders/base_uploader.rb
Labels: PR: reviewed-approved

#5352 Track Queue sizes and latency for Sidekiq
  app/labor/loggers/log_worker_queue_stats.rb
  lib/tasks/fetch.rake
  spec/labor/loggers/log_worker_queue_stats_spec.rb
Labels: PR: reviewed-approved

#5393 Remove SiteConfig From Org Validation
  app/models/organization.rb
Labels: PR: reviewed-approved

#5394 Set default email in application mailer using ENV variable
  app/mailers/application_mailer.rb
  app/mailers/digest_mailer.rb
  app/mailers/pro_membership_mailer.rb
  app/models/site_config.rb
Labels: PR: reviewed-approved

#5395 Fix erblint errors
  .rubocop_todo.yml
Labels: PR: reviewed-approved

#5386 Routine rubocop fixes
  .rubocop_todo.yml
  lib/tasks/fetch.rake
Labels: PR: reviewed-approved

#5390 Set type for user_selects_looking_for_work_spec to system
  spec/system/user_selects_looking_for_work_spec.rb
Labels: PR: reviewed-approved

#5404 Update Heroku Release to Migrate and Load App
  Procfile
  docs/deployment.md
  release-tasks.sh
Labels: PR: reviewed-approved

#5405 Add wait_for_javascript to flaky system tests
  spec/support/initializers/capybara.rb
  spec/system/articles/user_edits_an_article_spec.rb
  spec/system/articles/user_visits_articles_by_tag_spec.rb
  spec/system/comments/user_delete_a_comment_spec.rb
  spec/system/comments/user_edits_a_comment_spec.rb
  spec/system/comments/user_fills_out_comment_spec.rb
Labels: PR: reviewed-approved

#5382 Migrate delayed job that calculates comment score to sidekiq
  app/models/comment.rb
  app/workers/comments/calculate_score_worker.rb
  spec/models/comment_spec.rb
  spec/workers/comments/calculate_score_worker_spec.rb
Labels: PR: reviewed-approved

#5391 Remove TouchFollowerJob and do User update inline
  app/jobs/follows/touch_follower_job.rb
  app/models/follow.rb
  spec/jobs/follows/touch_follower_job_spec.rb
  spec/models/follow_spec.rb
Labels: PR: reviewed-approved

#5403 Migrate Users/FollowJob to Sidekiq
  app/controllers/api/v0/follows_controller.rb
  app/controllers/users_controller.rb
  app/workers/users/follow_worker.rb
  spec/requests/api/v0/follows_spec.rb
  spec/system/user_selects_looking_for_work_spec.rb
  spec/workers/users/follow_worker_spec.rb
Labels: PR: reviewed-approved

#5406 moving org bust cache job to sidekiq
  app/jobs/organizations/bust_cache_job.rb
  app/models/organization.rb
  app/workers/organizations/bust_cache_worker.rb
  spec/jobs/organizations/bust_cache_job_spec.rb
  spec/models/organization_spec.rb
  spec/workers/organizations/bust_cache_worker_spec.rb
Labels: PR: reviewed-approved

#5402 Fix Time flacky test
  spec/services/pro_memberships/expiration_notifier_spec.rb
Labels: PR: reviewed-approved

#5399 Restore default email from SiteConfig for mailers
  app/mailers/application_mailer.rb
  app/mailers/digest_mailer.rb
  app/mailers/pro_membership_mailer.rb
  app/views/service_worker/index.js.erb
  spec/mailers/digest_mailer_spec.rb
  spec/mailers/notify_mailer_spec.rb
  spec/mailers/previews/notify_mailer_preview.rb
  spec/mailers/pro_membership_mailer_spec.rb
  spec/mailers/scholarship_mailer_spec.rb
Labels: PR: reviewed-approved

#3730 Creating podcasts by users
  app/assets/stylesheets/articles.scss
  app/assets/stylesheets/minimal.scss
  app/assets/stylesheets/podcast-form.scss
  app/assets/stylesheets/scaffolds.scss
  app/controllers/podcasts_controller.rb
  app/models/podcast.rb
  app/models/user.rb
  app/views/internal/podcasts/edit.html.erb
  app/views/podcast_episodes/_meta.html.erb
  app/views/podcast_episodes/_sidebar.html.erb
  app/views/podcast_episodes/admin.html.erb
  app/views/podcasts/_form.html.erb
  app/views/podcasts/new.html.erb
  config/routes.rb
  db/migrate/20191220120243_add_create_by_user_id_to_podcasts.rb
  db/schema.rb
  spec/fixtures/files/podcast.png
  spec/models/podcast_spec.rb
  spec/models/user_spec.rb
  spec/requests/podcasts/podcast_create_spec.rb
  spec/requests/podcasts/podcast_episodes_index_spec.rb
Labels: PR: reviewed-approved

#5348 Change the way that id_code was created
  app/models/comment.rb
  spec/models/comment_spec.rb
Labels: PR: reviewed-approved

#5409 Remove Chat Channels Index Job
  app/jobs/chat_channels/index_job.rb
  app/models/message.rb
  spec/jobs/chat_channels/index_job_spec.rb
Labels: PR: reviewed-approved

#4803 User profile details fix
  app/assets/stylesheets/user-profile-header.scss
Labels: PR: reviewed-approved

#5294 Fix (some) n+1/eager loading issues
  app/controllers/additional_content_boxes_controller.rb
  app/controllers/dashboards_controller.rb
  app/controllers/notifications_controller.rb
  app/services/article_api_index_service.rb
  app/views/additional_content_boxes/boxes.html.erb
  spec/requests/additional_content_boxes_spec.rb
  spec/requests/api/v0/articles_spec.rb
Labels: PR: reviewed-approved

#5412 Remove delayed job that calculates comment score
  app/jobs/comments/calculate_score_job.rb
  spec/jobs/comments/calculate_score_job_spec.rb
Labels: PR: reviewed-approved

#5355 Remove Audit::SaveToPersistentStorageJob and Save Inline
  app/jobs/audit/save_to_persistent_storage_job.rb
  app/services/audit/notification.rb
  spec/services/audit/notification_spec.rb
Labels: PR: reviewed-approved

#5106 Add a pull request checklist to the PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: PR: reviewed-approved

#5359 Reading list count becomes "empty" when selecting a tag
  app/javascript/searchableItemList/searchableItemList.js
Labels: PR: reviewed-approved

#5401 Migrate new reaction job 5305
  app/models/notification.rb
  app/workers/notifications/new_reaction_worker.rb
  spec/models/notification_spec.rb
  spec/workers/notifications/new_reaction_worker_spec.rb
Labels: PR: reviewed-approved

#5392 Internal feedback: skip negative reactions for unpublished content
  app/views/internal/feedback_messages/index.html.erb
Labels: PR: reviewed-approved

#5415 Remove notifiable access from articles and comments notifications
  app/controllers/notifications_controller.rb
  app/services/notifications.rb
  app/services/notifications/update.rb
  app/views/notifications/_article.html.erb
  app/views/notifications/_comment.html.erb
  spec/services/notifications/new_comment/send_spec.rb
Labels: PR: reviewed-approved

#5314 No longer hide reactions and follows after 24 hours
  app/controllers/notifications_controller.rb
  app/models/notification.rb
Labels: PR: reviewed-approved

#5374 Updated application_helper.rb with Cloudinary env variable
  app/helpers/application_helper.rb
Labels: PR: reviewed-approved

#5418 Remove call to published method on non-articles
  app/views/internal/feedback_messages/index.html.erb
Labels: PR: reviewed-approved

#5410 Change TouchJob to TouchWorker and move to sidekiq
  app/jobs/users/touch_job.rb
  app/models/reaction.rb
  spec/jobs/users/touch_job_spec.rb
  spec/models/reaction_spec.rb
Labels: PR: reviewed-approved

#5408 Move Classified Listing Cache Buster to Sidekiq
  app/controllers/concerns/classified_listings_toolkit.rb
  app/jobs/classified_listings/bust_cache_job.rb
  app/workers/classified_listings/bust_cache_worker.rb
  spec/jobs/classified_listings/bust_cache_job_spec.rb
  spec/requests/internal/classified_listings_spec.rb
  spec/workers/classified_listings/bust_cache_worker_spec.rb
Labels: PR: reviewed-approved

#5420 Internal articles: resize textarea to fill parent
  app/views/internal/articles/index.html.erb
Labels: PR: reviewed-approved

#5428 Internal users edit: fix typo
  app/views/internal/users/edit.html.erb
Labels: PR: reviewed-approved

#5423 Migrate subscribe to mailchimp newsletter job to sidekiq worker
  app/models/user.rb
  app/workers/users/subscribe_to_mailchimp_newsletter_worker.rb
  spec/models/user_spec.rb
  spec/system/internal/admin_awards_badges_spec.rb
  spec/workers/users/subscribe_to_mailchimp_newsletter_worker_spec.rb
Labels: PR: reviewed-approved

#5422 Remove New Reaction Job and Spec
  app/jobs/notifications/new_reaction_job.rb
  spec/jobs/notifications/new_reaction_job_spec.rb
Labels: PR: reviewed-approved

#5304 Remove password verification in admin user controller
  app/controllers/admin/users_controller.rb
Labels: PR: reviewed-approved

#5437 remove unused active job worker
  app/jobs/notifications/new_badge_achievement_job.rb
  spec/jobs/notifications/new_badge_achievement_job_spec.rb
Labels: PR: reviewed-approved

#5416 Refactored Podcast Episode Bust Cache Job
  app/jobs/podcast_episodes/bust_cache_job.rb
  app/models/podcast_episode.rb
  app/workers/podcast_episodes/bust_cache_worker.rb
  spec/jobs/podcast_episodes/bust_cache_job_spec.rb
  spec/models/podcast_episode_spec.rb
  spec/workers/podcast_episodes/bust_cache_worker_spec.rb
Labels: PR: reviewed-approved

#5400 Remove env variables handled by SiteConfig
  Envfile
Labels: PR: reviewed-approved

#5426 Add suggested tags to SiteConfig
  app/controllers/api/v0/tags_controller.rb
  app/controllers/internal/configs_controller.rb
  app/models/site_config.rb
  app/models/tag.rb
  app/views/internal/configs/show.html.erb
  spec/requests/internal/configs_spec.rb
  spec/requests/tags_api_spec.rb
Labels: PR: reviewed-approved

#5441 Add oauth to list of skipped paths for service workers
  app/views/service_worker/index.js.erb
Labels: PR: reviewed-approved

#5398 Add Resave Articles Worker
  app/models/pro_membership.rb
  app/models/user.rb
  app/workers/users/resave_articles_worker.rb
  spec/models/user_spec.rb
  spec/requests/pro_memberships_spec.rb
  spec/services/pro_memberships/biller_spec.rb
  spec/workers/users/resave_articles_worker_spec.rb
Labels: PR: reviewed-approved

#5427 Migrate delayed job to send notification email on comment creation
  app/models/comment.rb
  app/workers/comments/send_email_notification_worker.rb
  spec/models/comment_spec.rb
  spec/workers/comments/send_email_notification_worker_spec.rb
Labels: PR: reviewed-approved

#5438 Check for follow before trying to send a notification
  app/models/notification.rb
Labels: PR: reviewed-approved

#5452 Fix hex color in seeds
  db/seeds.rb
Labels: PR: reviewed-approved

#5449 Add @jacobherrington to CODEOWNERS
  .github/CODEOWNERS
Labels: PR: reviewed-approved

#5486 Fix a bug when user tries to delete an account while not having an email
  app/controllers/users_controller.rb
  app/views/users/_account.html.erb
  spec/requests/user/user_destroy_spec.rb
Labels: PR: reviewed-approved

#5424 Change DestroyJob to DestroyWorker and move to sidekiq
  app/controllers/oauth/tokens_controller.rb
  app/jobs/webhook/destroy_job.rb
  app/workers/webhook/destroy_worker.rb
  spec/requests/oauth/tokens_spec.rb
  spec/workers/webhook/destroy_worker_spec.rb
Labels: PR: reviewed-approved

#5446 Remove delayed job that sends email notification on comment creation
  app/jobs/comments/send_email_notification_job.rb
  spec/jobs/comments/send_email_notification_job_spec.rb
Labels: PR: reviewed-approved

#5463 Add mentions create all worker
  app/models/mention.rb
  app/workers/mentions/create_all_worker.rb
  spec/models/mention_spec.rb
  spec/workers/mentions/create_all_worker_spec.rb
Labels: PR: reviewed-approved

#5465 Move welcome notification job to worker
  app/models/notification.rb
  app/models/user.rb
  app/workers/notifications/welcome_notification_worker.rb
  spec/requests/notifications_spec.rb
  spec/workers/notifications/welcome_notification_worker_spec.rb
Labels: PR: reviewed-approved

#5501 Add self to codeowners
  .github/CODEOWNERS
Labels: PR: reviewed-approved

#5506 Fixed rubocop issues
  spec/models/organization_spec.rb
  spec/models/user_spec.rb
  spec/workers/comments/calculate_score_worker_spec.rb
  spec/workers/comments/send_email_notification_worker_spec.rb
  spec/workers/notifications/new_reaction_worker_spec.rb
  spec/workers/podcast_episodes/bust_cache_worker_spec.rb
Labels: PR: reviewed-approved

#5498 Destroy messages if chat channels are destroyed
  app/models/chat_channel.rb
  spec/models/chat_channel_spec.rb
Labels: PR: reviewed-approved

#5455 Remove temporary site config script and unused env
  Envfile
  app/views/users/_account.html.erb
  lib/tasks/temporary/migrate_environment_variables_site_config.rake
Labels: PR: reviewed-approved

#5504 Return 429 Too Many Requests instead of raising
  app/controllers/comments_controller.rb
  spec/requests/comments_create_spec.rb
Labels: PR: reviewed-approved

#5414 Move Twitch webhook registration from ActiveJob to Sidekiq
  app/controllers/users_controller.rb
  app/jobs/streams/twitch_webhook_registration_job.rb
  app/workers/streams/twitch_webhook_registration_worker.rb
  lib/tasks/twitch.rake
  spec/jobs/streams/twitch_webhook_registration_job_spec.rb
  spec/requests/user/user_settings_spec.rb
  spec/workers/streams/twitch_webhook_registration_worker_spec.rb
Labels: PR: reviewed-approved, type: refactor

#5478 ActiveRecord count optimizations
  app/labor/email_logic.rb
  app/models/application_record.rb
  app/views/internal/users/_notes.erb
  app/views/moderations/mod.html.erb
  app/views/partnerships/index.html.erb
  app/views/stories/_sign_in_invitation.html.erb
  app/views/users/_account.html.erb
  lib/tasks/fetch.rake
  spec/labor/email_logic_spec.rb
  spec/models/application_record_spec.rb
Labels: PR: reviewed-approved

#5411 Add visual indication for listing buffer actions
  app/views/internal/articles/_article_script.html.erb
Labels: PR: reviewed-approved

#5474 Remove unused Envfile variables
  Envfile
  config/sample_application.yml
  docker-run.sh
  docs/backend/auth-github.md
  docs/backend/auth-twitter.md
Labels: PR: reviewed-approved

#5509 Use .execute to avoid any possibility of prepared statements
  app/models/application_record.rb
Labels: PR: reviewed-approved

#5472 Modify podcast design details and functionality
  app/assets/javascripts/initializePage.js.erb
  app/assets/javascripts/initializers/initializeFetchFollowedArticles.js.erb
  app/assets/javascripts/initializers/initializePodcastPlayback.js
  app/assets/stylesheets/articles.scss
  app/assets/stylesheets/ltags/PodcastTag.scss
  app/assets/stylesheets/podcast-episodes-show.scss
  app/assets/stylesheets/scaffolds.scss
  app/assets/stylesheets/shared.scss
  app/controllers/stories_controller.rb
  app/models/podcast.rb
  app/views/articles/index.html.erb
  app/views/podcast_episodes/_liquid.html.erb
  app/views/podcast_episodes/_podcast_bar.html.erb
  app/views/podcast_episodes/show.html.erb
  app/views/stories/_main_stories_feed.html.erb
Labels: PR: unreviewed

#5485 Handle liquid tag errors in comments form
  app/assets/javascripts/initializers/initializeCommentsPage.js.erb
  app/controllers/comments_controller.rb
Labels: PR: reviewed-approved

#5513 Fix podcast NaN time issue
  app/assets/javascripts/initializers/initializePodcastPlayback.js
  app/views/podcast_episodes/_liquid.html.erb
  app/views/podcast_episodes/_podcast_bar.html.erb
Labels: PR: unreviewed

#5514 Adding section for switching to free plan on Algolia
  docs/backend/algolia.md
Labels: PR: reviewed-approved

#5505 Currect .menubg top position
  app/assets/stylesheets/top-bar.scss
Labels: PR: reviewed-approved

#4744 Comments API: fix caching issues
  app/controllers/api/v0/comments_controller.rb
  app/jobs/comments/bust_cache_job.rb
  app/views/api/v0/comments/_comment.json.jbuilder
  app/views/api/v0/comments/_comment_with_children.json.jbuilder
  app/views/api/v0/comments/_comments_with_children.json.jbuilder
  app/views/api/v0/comments/index.json.jbuilder
  app/views/api/v0/comments/show.json.jbuilder
  spec/requests/api/v0/comments_spec.rb
Labels: PR: reviewed-approved

#5512 Scrub Unused data sent to Honeycomb to save space
  config/initializers/honeycomb.rb
Labels: PR: reviewed-approved

#5529 Fix spec that broke after we merged #4744
  spec/jobs/comments/bust_cache_job_spec.rb
Labels: PR: reviewed-approved

#5518 Log DB Table sizes in a Sidekiq Worker
  app/workers/metrics/record_db_table_counts_worker.rb
  lib/tasks/fetch.rake
  spec/workers/metrics/record_db_table_counts_worker_spec.rb
Labels: PR: reviewed-approved

#5451 Change RemoveAllJob to RemoveAllWorker and move to sidekiq
  app/models/notification.rb
  app/workers/notifications/remove_all_worker.rb
  spec/jobs/notifications/remove_all_job_spec.rb
  spec/models/comment_spec.rb
  spec/models/notification_spec.rb
  spec/requests/articles/articles_destroy_spec.rb
  spec/services/articles/destroyer_spec.rb
  spec/workers/notifications/remove_all_worker_spec.rb
Labels: PR: reviewed-approved

#5524 Remove unnecessary heroku slug commit values in cache keys
  app/views/articles/index.html.erb
  app/views/stories/_main_stories_feed.html.erb
Labels: PR: reviewed-approved

#5510 Raise an error if the ENV variable DEPLOY_STATUS is set to blocked
  docs/deployment.md
  release-tasks.sh
Labels: PR: reviewed-approved

#5527 Enable Bullet in development mode
  config/environments/development.rb
Labels: PR: reviewed-approved

#5454 Change MilestoneJob to MilestoneWorker and move to sidekiq (Watch DJs when Deployed!)
  app/jobs/notifications/milestone_job.rb
  app/models/notification.rb
  app/workers/notifications/milestone_worker.rb
  spec/workers/notifications/milestone_worker_spec.rb
Labels: PR: reviewed-approved

#5533 Record Background Queue stats in a Sidekiq Worker
  app/workers/metrics/record_background_queue_stats_worker.rb
  lib/tasks/fetch.rake
  spec/workers/metrics/record_background_queue_stats_worker_spec.rb
Labels: PR: reviewed-approved

#5528 Fix missing redis server to gitpod configuration
  .gitpod.dockerfile
  .gitpod.yml
Labels: PR: reviewed-approved

#5534 Add Alex Smith to core team members [ci skip]
  README.md
Labels: PR: reviewed-approved

#5473 Update settings links + descriptions in editor guide
  app/views/pages/_editor_guide_text.html.erb
  app/views/pages/_v1_editor_guide_preamble.html.erb
Labels: PR: reviewed-approved

#5532 Changed user-metadata-details to overflow-y: auto
  app/assets/stylesheets/user-profile-header.scss
Labels: PR: reviewed-approved

#5535 remove unused welcome notification job
  app/jobs/notifications/welcome_notification_job.rb
  spec/jobs/notifications/welcome_notification_job_spec.rb
Labels: PR: reviewed-approved

#5537 Send Travis screenshots to s3 After A Failed Master Build
  .travis.yml
Labels: PR: reviewed-approved

#5538 Fix typo in Skipping CI docs [ci skip]
  docs/tests/skip-ci.md
Labels: PR: reviewed-approved

#5540 Add myself to core team in README
  README.md
Labels: PR: reviewed-approved

#5536 Remove Comments::CreateIdCodeJob which is now done inline
  app/jobs/comments/create_id_code_job.rb
  spec/factories/comments.rb
  spec/jobs/comments/create_id_code_job_spec.rb
  spec/system/comments/user_edits_a_comment_spec.rb
Labels: PR: reviewed-approved

#5502 Migrate delayed job to bust comment cache
  app/models/comment.rb
  app/workers/comments/bust_cache_worker.rb
  spec/models/comment_spec.rb
  spec/workers/comments/bust_cache_worker_spec.rb
Labels: PR: reviewed-approved

#5407 Add let_it_be_readonly to avoid updating variables
  spec/models/notification_spec.rb
  spec/support/initializers/test_prof.rb
Labels: PR: reviewed-approved

#5517 Send Sidekiq data to Honeycomb
  config/initializers/sidekiq.rb
  lib/sidekiq/honeycomb_middleware.rb
  spec/lib/sidekiq/honeycomb_middleware_spec.rb
Labels: PR: reviewed-approved

#5544 Add initial usage metrics for datatog
  app/workers/metrics/record_daily_usage_worker.rb
  lib/tasks/fetch.rake
  spec/workers/metrics/record_daily_usage_worker_spec.rb
Labels: PR: unreviewed

#5467 Refactor userDetails
  app/javascript/.eslintrc.js
  app/javascript/chat/__tests__/__snapshots__/userDetails.test.jsx.snap
  app/javascript/chat/userDetails.jsx
Labels: PR: reviewed-approved

#5447 Internal Reports: Searching and sorting with Ransack
  Gemfile
  Gemfile.lock
  app/controllers/internal/feedback_messages_controller.rb
  app/views/internal/feedback_messages/index.html.erb
  spec/factories/feedback_messages.rb
  spec/system/internal/admin_manages_reports_spec.rb
Labels: PR: reviewed-approved

#5541 Add more info to architecture.md doc
  docs/technical-overview/architecture.md
Labels: PR: reviewed-approved

#5543 Add article's record key to Fastly Surrogate-Key to separate caches
  app/controllers/api/v0/comments_controller.rb
  app/jobs/comments/bust_cache_job.rb
  app/workers/comments/bust_cache_worker.rb
  spec/jobs/comments/bust_cache_job_spec.rb
  spec/requests/api/v0/comments_spec.rb
  spec/workers/comments/bust_cache_worker_spec.rb
Labels: PR: reviewed-approved

#5523 Adding info about disappearing tokens
  docs/backend/auth-twitter.md
Labels: PR: reviewed-approved

#5553 Send past week aggregate x day active user data to datadog
  app/workers/metrics/record_daily_usage_worker.rb
  spec/workers/metrics/record_daily_usage_worker_spec.rb
Labels: PR: unreviewed

#5525 Improved BadgeRewarder
  app/labor/badge_rewarder.rb
  spec/labor/badge_rewarder_spec.rb
Labels: PR: reviewed-approved

#5522 Add strong_migrations gem
  Gemfile
  Gemfile.lock
  config/initializers/strong_migrations.rb
Labels: PR: reviewed-approved

#5547 Remove old RemoveAll job
  app/jobs/notifications/remove_all_job.rb
Labels: PR: reviewed-approved

#5562 Only setup StrongMigrations in dev or test
  config/initializers/strong_migrations.rb
Labels: PR: reviewed-approved

#5561 Disable Beeline on Schedulers and in Console
  datadog/prerun.sh
Labels: PR: reviewed-approved

#5550 Remove Mentions create all job
  app/jobs/mentions/create_all_job.rb
  spec/jobs/mentions/create_all_job_spec.rb
Labels: PR: reviewed-approved

#5554 Add guide for Ransack to docs
  docs/internal/internal-search.md
  docs/internal/readme.md
  docs/technical-overview/stack.md
Labels: PR: reviewed-approved

#5548 Remove migrated job to bust comment cache
  app/jobs/comments/bust_cache_job.rb
  spec/jobs/comments/bust_cache_job_spec.rb
Labels: PR: reviewed-approved

#5556 Create new NewFollowerWorker and start sending jobs to it
  app/models/notification.rb
  app/services/notifications/new_follower/send.rb
  app/workers/notifications/new_follower_worker.rb
  spec/models/notification_spec.rb
  spec/services/notifications/new_follower/send_spec.rb
  spec/workers/notifications/new_follower_worker_spec.rb
Labels: PR: reviewed-approved

#5471 Increase cache TTL for social preview images
  app/lib/html_css_to_image.rb
  spec/lib/html_css_to_image_spec.rb
Labels: PR: reviewed-approved

#5568 Update Travis Artifacts Path
  .travis.yml
Labels: PR: reviewed-approved

#5572 Change font size for search and message input
  app/assets/stylesheets/chat.scss
  app/assets/stylesheets/top-bar.scss
  app/views/service_worker/index.js.erb
Labels: PR: unreviewed

#5552 Internal Reports: Add eager loading based on Bullet
  app/controllers/internal/feedback_messages_controller.rb
Labels: PR: reviewed-approved

#5575 Add onboarding sanitization
  app/javascript/onboarding/components/ClosingSlide.jsx
Labels: PR: unreviewed

#5579 Remove flaky edit button spec
  spec/system/articles/user_edits_an_article_spec.rb
Labels: PR: unreviewed

#5576 Move Chart.js to dynamic import
  app/javascript/analytics/dashboard.js
Labels: PR: unreviewed

#5587 Bump assets version
  config/initializers/assets.rb
Labels: PR: reviewed-approved

#5458 Add create chat channel worker
  app/models/follow.rb
  app/workers/follows/create_chat_channel_worker.rb
  spec/models/follow_spec.rb
  spec/workers/follows/create_chat_channel_worker_spec.rb
Labels: PR: reviewed-approved

#5549 Add mentions send email notifications worker
  app/models/mention.rb
  app/workers/mentions/send_email_notification_worker.rb
  spec/workers/mentions/send_email_notification_worker_spec.rb
Labels: PR: reviewed-approved

#5569 Remove NewFollowerJob and spec
  app/jobs/notifications/new_follower_job.rb
  spec/jobs/notifications/new_follower_job_spec.rb
  spec/models/notification_spec.rb
Labels: PR: reviewed-approved
