Repository forem/forem, pull requests merged in 2020-04, with the labels that each got.

#6991 Create alias for User's welcome_notification
  app/models/user.rb
  app/services/broadcasts/welcome_notification/generator.rb
  spec/requests/user/user_settings_spec.rb
Labels: PR: partially-approved

#6944 Add rel noopener, noreferrer, nofollow to docs header links
  docs/.gitdocs.json
Labels: PR: partially-approved

#6931 Avoid requesting reaction counts for draft articles
  app/assets/javascripts/initializers/initializeArticleReactions.js
  app/views/articles/_actions.html.erb
Labels: PR: partially-approved

#6978 Remove non unique SVG ids
  app/assets/images/cancel.svg
  app/assets/images/external-link-logo.svg
  app/assets/images/facebook-logo.svg
  app/assets/images/favorite-heart-outline-button.svg
  app/assets/images/image-upload.svg
  app/assets/images/info.svg
  app/assets/images/keyboard-left-arrow-button.svg
  app/assets/images/keyboard-right-arrow-button.svg
  app/assets/images/lightning.svg
  app/assets/images/link.svg
  app/assets/images/refresh-button.svg
  app/assets/images/ribbon.svg
  app/assets/images/star.svg
  app/assets/images/three-dots.svg
  app/assets/images/video-camera.svg
Labels: PR: reviewed-approved, accessibility

#6954 Ignore unused users columns
  app/dashboards/user_dashboard.rb
  app/models/user.rb
  app/views/fields/user_scholar_field/_form.html.erb
  app/views/fields/user_scholar_field/_index.html.erb
  app/views/fields/user_scholar_field/_show.html.erb
Labels: PR: reviewed-approved

#6999 Replaced themeable with body-color
  app/assets/stylesheets/notifications.scss
Labels: PR: reviewed-approved

#7003 Index Articles to Elasticsearch when adding Comments and Syncing Scores
  app/services/edge_cache/commentable/bust.rb
  app/services/moderator/delete_user.rb
  app/workers/articles/score_calc_worker.rb
  spec/requests/internal/users_manage_spec.rb
  spec/services/edge_cache/commentable/bust_spec.rb
  spec/services/moderator/delete_user_spec.rb
  spec/workers/articles/score_calc_worker_spec.rb
Labels: PR: partially-approved

#6903 Connect: move settings to sidecar iframe, improve invitations and remove experimental features
  app/assets/stylesheets/chat.scss
  app/assets/stylesheets/scaffolds.scss
  app/assets/stylesheets/settings.scss
  app/controllers/chat_channel_memberships_controller.rb
  app/controllers/chat_channels_controller.rb
  app/controllers/internal/chat_channels_controller.rb
  app/javascript/chat/__tests__/__snapshots__/codeEditor.test.jsx.snap
  app/javascript/chat/__tests__/__snapshots__/githubRepo.test.jsx.snap
  app/javascript/chat/__tests__/__snapshots__/userDetails.test.jsx.snap
  app/javascript/chat/__tests__/__snapshots__/view.test.jsx.snap
  app/javascript/chat/__tests__/codeEditor.test.jsx
  app/javascript/chat/__tests__/githubRepo.test.jsx
  app/javascript/chat/__tests__/userDetails.test.jsx
  app/javascript/chat/__tests__/view.test.jsx
  app/javascript/chat/chat.jsx
  app/javascript/chat/codeEditor.jsx
  app/javascript/chat/content.jsx
  app/javascript/chat/githubRepo.jsx
  app/javascript/chat/userDetails.jsx
  app/javascript/chat/view.jsx
  app/labor/assign_tag_moderator.rb
  app/mailers/notify_mailer.rb
  app/models/chat_channel.rb
  app/models/chat_channel_membership.rb
  app/models/message.rb
  app/policies/chat_channel_policy.rb
  app/views/chat_channel_memberships/edit.html.erb
  app/views/chat_channel_memberships/index.html.erb
  app/views/mailers/notify_mailer/channel_invite_email.html.erb
  app/views/mailers/notify_mailer/channel_invite_email.text.erb
  app/workers/follows/create_chat_channel_worker.rb
  config/routes.rb
  db/seeds.rb
  package.json
  spec/mailers/notify_mailer_spec.rb
  spec/models/chat_channel_spec.rb
  spec/requests/chat_channel_memberships_spec.rb
  spec/requests/chat_channels_spec.rb
  spec/requests/internal/chat_channel_spec.rb
  spec/requests/internal/users_manage_spec.rb
  spec/services/users/cleanup_chat_channels_spec.rb
  spec/services/users/delete_spec.rb
  spec/workers/moderator/banish_user_worker_spec.rb
  yarn.lock
Labels: PR: partially-approved

#7005 Organize rake tasks
  lib/tasks/badges.rake
  lib/tasks/cache.rake
  lib/tasks/fetch.rake
  lib/tasks/metrics.rake
  lib/tasks/notifications.rake
Labels: PR: reviewed-approved

#6989 Delete non-existing method "organization" from user_dashboard model
  app/dashboards/user_dashboard.rb
Labels: PR: partially-approved

#7009 Fix erb output on sitemaps
  app/views/sitemaps/show.xml.erb
Labels: PR: unreviewed

#7001 Reindex Articles in Elasticsearch When touched by Reactions
  app/models/article.rb
  spec/models/article_spec.rb
Labels: PR: partially-approved

#7007 Prompt users to ask a question/start a discussion
  app/models/article.rb
  app/services/broadcasts/welcome_notification/generator.rb
  db/seeds.rb
  spec/factories/broadcasts.rb
  spec/services/broadcasts/welcome_notification/generator_spec.rb
Labels: PR: partially-approved

#7008 Remove Comment and Article docs From Elasticsearch During User Delete
  app/services/users/delete_articles.rb
  app/services/users/delete_comments.rb
  spec/services/moderator/banish_user_spec.rb
  spec/services/users/delete_articles_spec.rb
  spec/services/users/delete_comments_spec.rb
Labels: PR: partially-approved

#7006 Delegate Podcast Episode published in Elasticsearch to Podcast
  app/serializers/search/podcast_episode_serializer.rb
Labels: PR: partially-approved

#6993 Add .gitattributes
  .gitattributes
Labels: PR: partially-approved

#7011 Update to Docs after Technical Overview with Ben
  docs/technical-overview/architecture.md
  docs/technical-overview/stack.md
Labels: PR: partially-approved

#6945 Ignore unused polls and poll_options columns
  app/models/poll.rb
  app/models/poll_option.rb
Labels: PR: partially-approved

#7016 Avoid clobbering user attributes with empty params during onboarding
  app/controllers/users_controller.rb
  spec/requests/users_onboarding_spec.rb
Labels: PR: partially-approved

#7015 Remove User Search Chat Channel Code
  app/javascript/chat/__tests__/__snapshots__/channelDetails.test.jsx.snap
  app/javascript/chat/__tests__/channelDetails.test.jsx
  app/javascript/chat/channelDetails.jsx
Labels: PR: reviewed-approved

#6997 Crayons Cards and Links
  app/assets/javascripts/initializers/initializeBaseUserData.js
  app/assets/stylesheets/_mixins.scss
  app/assets/stylesheets/article-form-needed-legacy.scss
  app/assets/stylesheets/article-show.scss
  app/assets/stylesheets/articles.scss
  app/assets/stylesheets/base/boxes.scss
  app/assets/stylesheets/chat.scss
  app/assets/stylesheets/classified_listings.scss
  app/assets/stylesheets/comments.scss
  app/assets/stylesheets/components/avatars.scss
  app/assets/stylesheets/components/cards.scss
  app/assets/stylesheets/components/navigation.scss
  app/assets/stylesheets/config/_colors.scss
  app/assets/stylesheets/crayons.scss
  app/assets/stylesheets/credits.scss
  app/assets/stylesheets/dashboard.scss
  app/assets/stylesheets/index-comments.scss
  app/assets/stylesheets/item-list.scss
  app/assets/stylesheets/ltags/ClassifiedListingTag.scss
  app/assets/stylesheets/ltags/DevCommentTag.scss
  app/assets/stylesheets/ltags/GithubReadmeTag.scss
  app/assets/stylesheets/ltags/GithubTag.scss
  app/assets/stylesheets/ltags/LinkTag.scss
  app/assets/stylesheets/ltags/StackexchangeTag.scss
  app/assets/stylesheets/ltags/TagTag.scss
  app/assets/stylesheets/ltags/UserTag.scss
  app/assets/stylesheets/moderators.scss
  app/assets/stylesheets/more-articles.scss
  app/assets/stylesheets/notifications.scss
  app/assets/stylesheets/partnerships.scss
  app/assets/stylesheets/preact/article-form.scss
  app/assets/stylesheets/preact/onboarding-modal.scss
  app/assets/stylesheets/scaffolds.scss
  app/assets/stylesheets/settings.scss
  app/assets/stylesheets/sidebar-data.scss
  app/assets/stylesheets/sticky-nav.scss
  app/assets/stylesheets/theme-selector.scss
  app/assets/stylesheets/themes/hacker.scss
  app/assets/stylesheets/themes/minimal.scss
  app/assets/stylesheets/themes/night.scss
  app/assets/stylesheets/themes/pink.scss
  app/assets/stylesheets/user-profile-header.scss
  app/assets/stylesheets/video-collection.scss
  app/assets/stylesheets/widgets.scss
  app/views/layouts/_nav_menu.html.erb
  app/views/pages/crayons.html.erb
Labels: Crayons, PR: partially-approved, PR: unreviewed

#7012 Topbar icons states
  .gitattributes
  app/assets/stylesheets/config/_colors.scss
  app/assets/stylesheets/themes/hacker.scss
  app/assets/stylesheets/themes/minimal.scss
  app/assets/stylesheets/themes/night.scss
  app/assets/stylesheets/themes/pink.scss
  app/assets/stylesheets/top-bar.scss
Labels: PR: partially-approved, tech: html/css

#7023 Removed unused scholarships code
  app/mailers/scholarship_mailer.rb
  app/views/mailers/scholarship_mailer/scholarship_awarded_email.html.erb
  app/views/mailers/scholarship_mailer/scholarship_awarded_email.text.erb
  spec/mailers/previews/scholarship_mailer_preview.rb
  spec/mailers/scholarship_mailer_spec.rb
Labels: PR: partially-approved

#7017 Update style for tag social preview
  app/views/social_previews/tag.html.erb
Labels: PR: reviewed-approved

#7039 Storybook Add-on Upgrades to v5.3.18
  package.json
  yarn.lock
Labels: PR: reviewed-approved

#7000 Strengthen badge achievement code and fix badge email
  app/mailers/application_mailer.rb
  app/models/badge_achievement.rb
  app/views/mailers/notify_mailer/new_badge_email.html.erb
  app/views/mailers/notify_mailer/new_badge_email.text.erb
  db/seeds.rb
  spec/mailers/notify_mailer_spec.rb
Labels: PR: partially-approved, area: generalization

#6986 Return Fields needed to Populate the Feed for Podcast Episodes
  app/services/search/feed_content.rb
  app/services/search/query_builders/feed_content.rb
  spec/services/search/feed_content_spec.rb
Labels: PR: partially-approved

#7022 Removed unused pages routes
  config/routes.rb
Labels: PR: partially-approved

#7018 Remove hardcoded banner exit code
  app/assets/javascripts/initializers/initializeHeroBannerClose.js
  app/controllers/stories_controller.rb
  app/views/layouts/application.html.erb
Labels: PR: unreviewed

#7014 Index User Roles to use to Filter out banned users
  app/models/user.rb
  app/serializers/search/user_serializer.rb
  config/elasticsearch/mappings/users.json
  spec/rails_helper.rb
  spec/serializers/search/user_serializer_spec.rb
Labels: PR: partially-approved

#7041 Remove mutationobserver-shim
  app/javascript/internal/__mocks__/mutationObserver.js
  app/javascript/internal/__tests__/controllers/article_controller.test.js
  app/javascript/internal/__tests__/controllers/buffer_controller.test.js
  docs/internal/internal-user-interface.md
  package.json
  yarn.lock
Labels: PR: partially-approved

#7045 Allow published/approved campaign html variant to be edited
  app/models/html_variant.rb
Labels: PR: reviewed-approved

#7010 Create Broadcasts.rake
  .rubocop.yml
  app/models/site_config.rb
  lib/tasks/broadcasts.rake
  spec/services/broadcasts/welcome_notification/generator_spec.rb
  spec/tasks/broadcasts_spec.rb
Labels: PR: unreviewed

#7050 Index Articles after Ratings are Updated
  app/workers/rating_votes/assign_rating_worker.rb
  spec/workers/rating_votes/assign_rating_worker_spec.rb
Labels: PR: reviewed-approved

#7053 Serialize search_score for Articles For Sorting
  app/models/article.rb
  app/serializers/search/article_serializer.rb
  spec/serializers/search/article_serializer_spec.rb
Labels: PR: reviewed-approved

#7046 Disable Travis alert on pull request
  .travis.yml
Labels: PR: partially-approved

#7043 Make sure there is no empty <p> in the badge email
  app/views/mailers/notify_mailer/new_badge_email.html.erb
  spec/mailers/notify_mailer_spec.rb
Labels: PR: partially-approved

#7054 Add set_up_profile notification, check for active broadcasts
  app/models/user.rb
  app/services/broadcasts/welcome_notification/generator.rb
  db/seeds.rb
  spec/factories/broadcasts.rb
  spec/models/user_spec.rb
  spec/requests/notifications_spec.rb
  spec/services/broadcasts/welcome_notification/generator_spec.rb
  spec/workers/notifications/welcome_notification_worker_spec.rb
Labels: PR: unreviewed

#7055 Share your project instead of story
  app/views/articles/_sidebar_campaign.html.erb
Labels: PR: partially-approved

#7013 Delete all Users via the DeleteWorker for Consistency and use Destroy in Worker
  app/services/moderator/delete_user.rb
  app/services/moderator/merge_user.rb
  app/services/users/delete.rb
  spec/services/moderator/merge_user_spec.rb
  spec/services/users/delete_spec.rb
Labels: PR: partially-approved

#7051 Fix up connect group issues
  app/mailers/notify_mailer.rb
  app/models/chat_channel.rb
  app/views/mailers/notify_mailer/channel_invite_email.html.erb
  spec/mailers/notify_mailer_spec.rb
  spec/mailers/previews/notify_mailer_preview.rb
Labels: PR: unreviewed

#7061 Fix flaky credits buyer spec
  spec/services/credits/buyer_spec.rb
Labels: PR: reviewed-approved

#7059 Unset DATABASE_URL in .gitpod.yml
  .gitpod.yml
  bin/setup
Labels: PR: partially-approved

#7065 Revert "Serialize search_score for Articles For Sorting"
  app/models/article.rb
  app/serializers/search/article_serializer.rb
  spec/serializers/search/article_serializer_spec.rb
Labels: PR: unreviewed

#7049 Setup User Elasticsearch Doc Syncing
  app/models/concerns/searchable.rb
  app/models/podcast_episode.rb
  app/models/user.rb
  app/services/data_sync/elasticsearch/user.rb
  spec/models/user_spec.rb
  spec/services/data_sync/elasticsearch/user_spec.rb
Labels: PR: reviewed-approved

#7062 Limiting number of items in sidebar widgets
  app/views/articles/_sidebar_additional.html.erb
Labels: PR: reviewed-approved, design, tech: html/css

#6977 Remove unused tags columns
  app/models/tag.rb
  db/migrate/20200331155903_remove_unused_columns_from_tags.rb
  db/schema.rb
Labels: PR: reviewed-approved

#7002 Refactor internal mods page
  app/controllers/internal/mods_controller.rb
  app/queries/internal/moderators_query.rb
  app/views/internal/mods/index.html.erb
  app/views/kaminari/internal/_first_page.html.erb
  app/views/kaminari/internal/_gap.html.erb
  app/views/kaminari/internal/_last_page.html.erb
  app/views/kaminari/internal/_next_page.html.erb
  app/views/kaminari/internal/_page.html.erb
  app/views/kaminari/internal/_paginator.html.erb
  app/views/kaminari/internal/_prev_page.html.erb
  spec/queries/internal/moderators_query_spec.rb
Labels: PR: partially-approved

#6987 Created Crayons Button Preact component
  app/assets/stylesheets/components/buttons.scss
  app/assets/stylesheets/scaffolds.scss
  app/javascript/crayons/Button/Button.jsx
  app/javascript/crayons/Button/__stories__/Button.stories.jsx
  app/javascript/crayons/Button/__stories__/button.html.stories.jsx
  app/javascript/crayons/Button/__tests__/Button.test.jsx
  app/javascript/crayons/Button/__tests__/__snapshots__/Button.test.jsx.snap
  app/javascript/crayons/Button/index.js
  app/javascript/crayons/Dropdown/__stories__/Dropdown.stories.jsx
  app/javascript/crayons/index.js
Labels: PR: partially-approved

#7052 By Default Search for Users that are not Banned
  app/services/search/query_builders/user.rb
  spec/services/search/query_builders/user_spec.rb
  spec/services/search/user_spec.rb
Labels: PR: unreviewed

#7048 Created the <ButtonGroup /> Preact Component
  app/javascript/crayons/ButtonGroup/ButtonGroup.jsx
  app/javascript/crayons/ButtonGroup/__stories__/ButtonGroup.stories.jsx
  app/javascript/crayons/ButtonGroup/__tests__/ButtonGroup.test.jsx
  app/javascript/crayons/ButtonGroup/__tests__/__snapshots__/ButtonGroup.test.jsx.snap
  app/javascript/crayons/ButtonGroup/index.js
  app/javascript/crayons/index.js
Labels: PR: partially-approved

#5281 Upgrade to Ruby 2.7.0
  .ruby-version
  .travis.yml
  Dockerfile
  Gemfile.lock
  README.md
  config/environments/development.rb
  config/environments/test.rb
  docs/.ruby-version
  docs/Gemfile
  docs/installation/linux.md
  docs/installation/mac.md
  docs/installation/windows.md
Labels: PR: reviewed-approved

#7044 Misc rubocop fixes
  .rubocop_todo.yml
  db/seeds.rb
  spec/requests/internal/chat_channel_spec.rb
Labels: PR: partially-approved

#7072 Add text-decoration: none back in for anchor
  app/assets/stylesheets/scaffolds.scss
Labels: PR: unreviewed

#7071 Prevent AR Unique errors with find_or_create for ChatChannelMembership
  app/models/chat_channel.rb
Labels: PR: partially-approved

#7063 Fix copy to clipboard buttons colors
  app/assets/stylesheets/preact/article-form.scss
  app/assets/stylesheets/themes/hacker.scss
  app/assets/stylesheets/themes/night.scss
Labels: PR: partially-approved

#7075 Fix various small style issues
  app/assets/stylesheets/base/reset.scss
  app/assets/stylesheets/chat.scss
  app/assets/stylesheets/comments.scss
Labels: PR: unreviewed

#7067 Remove onboarding type broadcasts
  app/models/broadcast.rb
  app/services/broadcasts/welcome_notification/generator.rb
  spec/factories/broadcasts.rb
  spec/requests/internal/broadcasts_spec.rb
  spec/services/notifications/welcome_notification/send_spec.rb
Labels: PR: partially-approved

#7084 Fix sidebar colors on dark themes
  app/assets/stylesheets/themes/hacker.scss
  app/assets/stylesheets/themes/night.scss
Labels: PR: reviewed-approved

#7079 Move fragment cache to more efficient location
  app/views/shell/_top.html.erb
Labels: PR: reviewed-approved

#7077 Move create PodcastEpisode callbacks to create Podcast Service
  app/models/podcast_episode.rb
  app/services/podcasts/create_episode.rb
  spec/services/podcasts/create_episode_spec.rb
Labels: PR: reviewed-approved

#7083 Fix some typos
  app/assets/stylesheets/config/_colors.scss
  app/assets/stylesheets/config/_import.scss
Labels: PR: partially-approved

#7092 Update Ruby version for Gitpod
  .gitpod.dockerfile
Labels: PR: partially-approved

#7096 Fixed moderators page color
  app/assets/stylesheets/moderators.scss
Labels: PR: reviewed-approved

#7098 Remove unused stripe_subscriptions/create view
  app/views/stripe_subscriptions/create.html.erb
Labels: PR: partially-approved

#7080 Skip updating a root comment if it doesnt exist
  app/models/comment.rb
  app/workers/comments/calculate_score_worker.rb
  spec/workers/comments/calculate_score_worker_spec.rb
Labels: PR: reviewed-approved

#7056 Add community_member_description, tagline and mascot_image_url to SiteConfig. Enable Cloudinary for primary_sticker_image
  app/assets/stylesheets/articles.scss
  app/assets/stylesheets/signup-modal.scss
  app/controllers/internal/configs_controller.rb
  app/models/site_config.rb
  app/views/internal/configs/show.html.erb
  app/views/layouts/_signup_modal.html.erb
  app/views/stories/_sign_in_invitation.html.erb
  spec/requests/internal/configs_spec.rb
  spec/views/layouts/signup_modal.html.erb_spec.rb
  spec/views/stories/sign_in_invitation.html.erb_spec.rb
Labels: PR: partially-approved

#7097 Upgrade Ruby to 2.7.1
  .gitpod.dockerfile
  .ruby-version
  .travis.yml
  Dockerfile
  Gemfile.lock
  README.md
  docs/Gemfile
  docs/installation/linux.md
  docs/installation/mac.md
  docs/installation/windows.md
Labels: PR: partially-approved

#7099 Connect Video Chat Experiment
  app/controllers/video_chats_controller.rb
  app/javascript/packs/videoChat.jsx
  app/models/message.rb
  app/views/video_chats/show.html.erb
  config/routes.rb
  spec/requests/video_chats_spec.rb
Labels: PR: unreviewed

#7070 Copy set_cache_control_headers from fastly-rails
  app/controllers/application_controller.rb
  app/controllers/concerns/fastly_headers.rb
Labels: PR: partially-approved

#7107 Change /settings/misc to /settings/ux
  docs/.ruby-version
  docs/design/theming.md
Labels: PR: partially-approved

#7101 Make root_exists Method Public and Use In Other Callbacks
  app/models/comment.rb
  spec/models/comment_spec.rb
Labels: PR: partially-approved

#7110 A bit more video experimentation
  app/controllers/video_chats_controller.rb
  app/javascript/packs/videoChat.jsx
  app/views/video_chats/show.html.erb
Labels: PR: unreviewed

#7116 Remove variants from frontend portion of onboarding
  app/javascript/onboarding/Onboarding.jsx
  app/javascript/onboarding/components/ClosingSlide.jsx
  app/javascript/onboarding/components/IntroSlide.jsx
  app/javascript/onboarding/components/SlideContent.jsx
Labels: PR: partially-approved

#7102 Refactor Stories::FeedsController
  app/controllers/stories/feeds_controller.rb
  spec/requests/stories/feeds_spec.rb
Labels: PR: reviewed-approved

#7100 Add ARIA checked attribute to article reaction buttons
  app/assets/javascripts/initializers/initializeArticleReactions.js
  app/views/articles/_actions.html.erb
  app/views/articles/_reaction_button.html.erb
Labels: PR: partially-approved, accessibility

#7118 Remove variants from backend portion of onboarding
  app/controllers/async_info_controller.rb
  app/controllers/internal/growth_controller.rb
  app/models/user.rb
  app/services/authorization_service.rb
  app/views/internal/growth/_results.html.erb
  app/views/internal/growth/index.html.erb
Labels: PR: partially-approved

#7078 Made typography styles while in Storybook more specific.
  app/javascript/crayons/typography/__stories__/typography.scss
  app/javascript/crayons/typography/__stories__/typography.stories.jsx
  app/javascript/crayons/typography/__stories__/typographyAccented.stories.jsx
Labels: PR: reviewed-approved, tech: html/css

#7120 Add authorization and new styles for sidecar video
  app/controllers/video_chats_controller.rb
  app/javascript/chat/chat.jsx
  app/javascript/packs/videoChat.jsx
  app/models/message.rb
  app/views/video_chats/show.html.erb
  spec/requests/video_chats_spec.rb
Labels: PR: unreviewed

#7115 Hook up Elasticsearch Data Syncing for Articles
  app/models/article.rb
  app/models/concerns/searchable.rb
  app/services/data_sync/elasticsearch/article.rb
  app/services/data_sync/elasticsearch/user.rb
  spec/models/article_spec.rb
  spec/services/data_sync/elasticsearch/article_spec.rb
  spec/services/data_sync/elasticsearch/user_spec.rb
Labels: PR: reviewed-approved

#7113 Use force redirects for docs to follow legacy functionality
  netlify.toml
Labels: PR: reviewed-approved

#7132 Remove /swagnets
  app/views/pages/swagnets.html.erb
  config/routes.rb
Labels: PR: partially-approved

#7125 Remove unused columns from polls
  app/models/poll.rb
  db/migrate/20200407083405_remove_unused_columns_from_polls.rb
  db/schema.rb
Labels: PR: reviewed-approved

#6802 Add name to tags component
  app/javascript/article-form/__tests__/__snapshots__/articleForm.test.jsx.snap
  app/javascript/article-form/elements/__tests__/__snapshots__/tags.test.jsx.snap
  app/javascript/shared/components/tags.jsx
  app/views/classified_listings/_form.html.erb
Labels: PR: partially-approved

#7130 Remove dynamic /live page
  .erb-lint.yml
  app/controllers/pages_controller.rb
  app/views/pages/live.html.erb
  config/routes.rb
  spec/requests/pages_spec.rb
Labels: PR: partially-approved

#7121 Adds Pusher Beams docs for Android PN
  docs/backend/pusher.md
Labels: PR: partially-approved

#7131 Remove unused columns from users
  app/models/user.rb
  db/migrate/20200407091449_remove_unused_columns_from_users.rb
  db/schema.rb
Labels: PR: unreviewed

#7104 Index Tags on Creation to via ActsAsTaggableOn in Elasticsearch
  app/lib/acts_as_taggable_on/tag.rb
  app/models/tag.rb
  spec/lib/acts_as_taggable_on/tag_spec.rb
Labels: PR: unreviewed

#7122 Introduce URL.sanitized_referer helper
  app/controllers/pages_controller.rb
  app/helpers/application_helper.rb
  app/lib/url.rb
  app/views/comments/_form.html.erb
  spec/helpers/application_helper_spec.rb
Labels: PR: unreviewed

#7108 Copy set_surrogate_key_header from fastly-rails
  app/controllers/concerns/fastly_headers.rb
Labels: PR: partially-approved

#7133 Replace /downloads with a dynamic page
  app/controllers/downloads_controller.rb
  app/views/downloads/index.html.erb
  config/routes.rb
  spec/system/user_visits_downloads_page_spec.rb
Labels: PR: partially-approved

#7135 Send auth failures to Datadog
  app/controllers/omniauth_callbacks_controller.rb
  spec/system/user_logs_in_with_twitter_spec.rb
Labels: PR: reviewed-approved, area: auth

#7137 Rescue invalid URL errors and Mark as Unreachable for Podcast Episodes
  app/services/podcasts/get_media_url.rb
  spec/services/podcasts/get_media_url_spec.rb
Labels: PR: reviewed-approved

#7129 Remove unused columns from organizations
  app/models/organization.rb
  db/migrate/20200407090914_remove_unused_columns_from_organizations.rb
  db/schema.rb
Labels: PR: unreviewed

#7124 Remove unused columns from poll options
  app/models/poll_option.rb
  db/migrate/20200407081312_remove_unused_columns_from_poll_options.rb
  db/schema.rb
Labels: PR: unreviewed

#7123 Add new user attributes to elasticsearch
  app/serializers/search/user_serializer.rb
  app/services/search/user.rb
  config/elasticsearch/mappings/users.json
  lib/data_update_scripts/20200406213152_re_index_users_to_elasticsearch.rb
Labels: PR: reviewed-approved

#7128 Remove unused columns from tweets
  app/models/tweet.rb
  db/migrate/20200407090218_remove_unused_columns_from_tweets.rb
  db/schema.rb
Labels: PR: partially-approved

#7094 Fix comment hiding
  app/assets/javascripts/initializers/initializeBaseUserData.js
Labels: PR: partially-approved

#7119 Update manual Fastly header assignments
  app/controllers/articles_controller.rb
  app/controllers/sitemaps_controller.rb
  app/controllers/stories_controller.rb
  spec/requests/articles/articles_spec.rb
  spec/requests/stories_index_spec.rb
Labels: PR: partially-approved

#7138 Added some space between wave emoji and text
  app/javascript/chat/chat.jsx
Labels: PR: partially-approved, tech: javascript

#7141 Account for scenario without `test_variant`
  app/controllers/stories/feeds_controller.rb
  spec/requests/stories/feeds_spec.rb
Labels: PR: partially-approved

#7126 Remove unused columns from podcast_episodes
  app/models/podcast_episode.rb
  db/migrate/20200407083732_remove_unused_columns_from_podcast_episodes.rb
  db/schema.rb
Labels: PR: unreviewed

#7144 Updated jest code coverage configuration.
  jest.config.js
Labels: PR: reviewed-approved, tech: javascript

#7127 Remove unused columns from pages
  app/models/page.rb
  db/migrate/20200407084807_remove_unused_columns_from_pages.rb
  db/schema.rb
Labels: PR: unreviewed

#7149 Remove Makefile
  Makefile
Labels: PR: reviewed-approved

#7082 Async Vomit Confirmations & Invalidations in Internal
  app/controllers/internal/reactions_controller.rb
  app/views/internal/feedback_messages/_abuse_reports.html.erb
  spec/requests/internal/reactions_spec.rb
Labels: PR: unreviewed

#7154 Keep Articles Updated in Elasticsearch when Organization is Updated
  app/models/organization.rb
  app/services/data_sync/elasticsearch/organization.rb
  spec/models/organization_spec.rb
  spec/services/data_sync/elasticsearch/organization_spec.rb
Labels: PR: reviewed-approved

#7156 Add exceptions to the serviceworker code to fix redirects
  app/views/service_worker/index.js.erb
Labels: PR: reviewed-approved

#7158 Removed unused views
  app/views/events/_widget_events_item.html.erb
  app/views/pages/twitter_monitor.html.erb
Labels: PR: partially-approved

#7090 Make force_ssl an environment variable to make sure new communities can get proper ssl config.
  Envfile
  config/environments/production.rb
  config/initializers/session_store.rb
Labels: PR: partially-approved

#7161 Upgraded to eslint 6 and fixed barrel file issue for codeclimate
  .codeclimate.yml
  app/assets/javascripts/initializers/initializeBaseUserData.js
Labels: PR: reviewed-approved

#7112 Created the <RadioButton /> and <FormField /> components.
  app/javascript/crayons/formElements/FormField/FormField.jsx
  app/javascript/crayons/formElements/FormField/index.js
  app/javascript/crayons/formElements/RadioButton/RadioButton.jsx
  app/javascript/crayons/formElements/RadioButton/index.js
  app/javascript/crayons/formElements/__stories__/FormField.stories.jsx
  app/javascript/crayons/formElements/__stories__/RadioButton.stories.jsx
  app/javascript/crayons/formElements/__tests__/FormField.test.jsx
  app/javascript/crayons/formElements/__tests__/RadioButton.test.jsx
  app/javascript/crayons/formElements/__tests__/__snapshots__/FormField.test.jsx.snap
  app/javascript/crayons/formElements/__tests__/__snapshots__/RadioButton.test.jsx.snap
  app/javascript/crayons/formElements/index.js
  app/javascript/crayons/index.js
Labels: PR: reviewed-approved

#7153 Make the site config togglable
  app/views/internal/configs/_card_header.html.erb
  app/views/internal/configs/show.html.erb
Labels: PR: partially-approved

#7164 Adds number_with_delimiter for friendlier visualization in /parternships
  app/views/partnerships/index.html.erb
Labels: PR: partially-approved

#7157 Return cloudinary url from Elasticsearch to show Videos in Feed
  app/services/search/query_builders/feed_content.rb
  spec/services/search/feed_content_spec.rb
Labels: PR: partially-approved

#7105 🚀Feature: chat action messages if a member added, left or removed from the group
  app/assets/stylesheets/chat.scss
  app/controllers/chat_channel_memberships_controller.rb
  app/controllers/messages_controller.rb
  app/helpers/messages_helper.rb
  app/javascript/chat/actionMessage.jsx
  app/javascript/chat/chat.jsx
  app/views/chat_channels/show.json.jbuilder
  db/migrate/20200405103927_add_column_chat_action_to_messages.rb
  db/schema.rb
  spec/requests/chat_channel_memberships_spec.rb
Labels: PR: partially-approved

#7167 Throttle API get and write Endpoints
  config/initializers/rack/attack.rb
  spec/initializers/rack/attack_spec.rb
Labels: PR: partially-approved

#7168 Enforce Uniqueness for Certain Sidekiq Jobs
  Gemfile
  Gemfile.lock
  app/workers/articles/bust_cache_worker.rb
  app/workers/comments/calculate_score_worker.rb
  app/workers/notifications/update_worker.rb
  app/workers/search/index_to_elasticsearch_worker.rb
  app/workers/search/remove_from_elasticsearch_index_worker.rb
  config/initializers/sidekiq_unique_jobs.rb
  config/routes.rb
Labels: PR: partially-approved

#7150 Fix Datadog auth failure payload and add tests
  app/controllers/omniauth_callbacks_controller.rb
  config/initializers/omniauth.rb
  spec/system/user_logs_in_with_twitter_spec.rb
Labels: PR: reviewed-approved

#7165 Fix typo in credits/new
  app/views/credits/new.html.erb
Labels: PR: reviewed-approved

#7166 Add rate limit for article updates
  app/labor/rate_limit_checker.rb
  app/models/site_config.rb
  app/services/articles/updater.rb
Labels: PR: unreviewed

#7174 Remove hardcoded now page
  app/controllers/pages_controller.rb
  app/views/pages/now.html.erb
  config/routes.rb
Labels: PR: partially-approved

#7171 Add Solargraph gem for Gitpod
  .gitpod.yml
  Dockerfile
  bin/docker-setup
Labels: PR: partially-approved

#7192 Remove unused variable oops
  app/labor/rate_limit_checker.rb
Labels: PR: reviewed-approved

#7194 Revert refactor of increment back to read/write
  app/labor/rate_limit_checker.rb
Labels: PR: reviewed-approved

#7196 Silence Ruby 2.7 warnings in Travis
  config/environments/test.rb
Labels: PR: reviewed-approved

#7162 Onboarding intro slide tweaks
  app/assets/stylesheets/preact/onboarding-modal.scss
  app/javascript/onboarding/__tests__/Onboarding.test.jsx
  app/javascript/onboarding/__tests__/__snapshots__/Onboarding.test.jsx.snap
  app/javascript/onboarding/components/EmailListTermsConditionsForm.jsx
  app/javascript/onboarding/components/IntroSlide.jsx
  app/javascript/onboarding/utilities.js
Labels: PR: partially-approved

#7163 Combine profile onboarding slide
  app/assets/stylesheets/preact/onboarding-modal.scss
  app/javascript/onboarding/Onboarding.jsx
  app/javascript/onboarding/__tests__/Onboarding.test.jsx
  app/javascript/onboarding/__tests__/__snapshots__/Onboarding.test.jsx.snap
  app/javascript/onboarding/components/BioForm.jsx
  app/javascript/onboarding/components/PersonalInfoForm.jsx
  app/javascript/onboarding/components/ProfileForm.jsx
  app/views/onboardings/show.html.erb
Labels: PR: reviewed-approved

#7173 Split out social media options (Important: post deployment task to be run)
  app/controllers/internal/configs_controller.rb
  app/models/site_config.rb
  app/views/articles/_sidebar.html.erb
  app/views/articles/index.html.erb
  app/views/articles/manage.html.erb
  app/views/articles/search/_meta.html.erb
  app/views/articles/show.html.erb
  app/views/articles/tags/_meta.html.erb
  app/views/classified_listings/index.html.erb
  app/views/comments/index.html.erb
  app/views/events/index.html.erb
  app/views/events/show.html.erb
  app/views/internal/articles/_individual_article.html.erb
  app/views/internal/configs/show.html.erb
  app/views/moderations/mod.html.erb
  app/views/notifications/index.html.erb
  app/views/pages/about.html.erb
  app/views/pages/badges.html.erb
  app/views/pages/bounty.html.erb
  app/views/pages/code_of_conduct.html.erb
  app/views/pages/contact.html.erb
  app/views/pages/faq.html.erb
  app/views/pages/generator.html.erb
  app/views/pages/information.html.erb
  app/views/pages/privacy.html.erb
  app/views/pages/report-abuse.html.erb
  app/views/pages/rlyweb.html.erb
  app/views/pages/show.html.erb
  app/views/pages/terms.html.erb
  app/views/podcast_episodes/_meta.html.erb
  app/views/podcast_episodes/show.html.erb
  app/views/reading_list_items/index.html.erb
  app/views/tags/index.html.erb
  app/views/users/_meta.html.erb
  app/views/videos/index.html.erb
  lib/tasks/temporary/social_media_handles.rake
  spec/requests/internal/configs_spec.rb
Labels: PR: partially-approved

#7146 Account for falsey test_variant in FeedsController
  app/controllers/stories/feeds_controller.rb
Labels: PR: partially-approved

#7203 Fixed generation of z-index utility CSS classes
  app/assets/stylesheets/config/_generator.scss
Labels: PR: reviewed-approved, tech: html/css

#7197 Enhance Site Config Togglability
  app/assets/stylesheets/internal/layout.scss
  app/views/internal/configs/_card_header.html.erb
  app/views/internal/configs/show.html.erb
Labels: PR: partially-approved

#7200 Log image data to Datadog for file name too long error
  app/controllers/application_controller.rb
  app/controllers/image_uploads_controller.rb
  app/controllers/users_controller.rb
  spec/requests/image_uploads_spec.rb
  spec/requests/user/user_settings_spec.rb
Labels: PR: partially-approved

#7199 Add Custom Sorting and Scoring For Feed Content from Elasticsearch
  app/services/search/feed_content.rb
  app/services/search/query_builders/feed_content.rb
  app/services/search/query_builders/query_base.rb
  spec/services/search/feed_content_spec.rb
  spec/services/search/query_builders/feed_content_spec.rb
Labels: PR: partially-approved

#7195 Allow img to use data-src in RSS
  app/services/rss_reader/assembler.rb
Labels: PR: reviewed-approved

#7208 Upgrade twilio-ruby to 5.33.0 and elasticsearch to 7.6.0
  Gemfile
  Gemfile.lock
  app/services/search/client.rb
Labels: PR: reviewed-approved

#7213 Remove /sponsorship-info
  app/views/pages/sponsorship_faq.html.erb
  config/routes.rb
  spec/requests/pages_spec.rb
Labels: PR: partially-approved

#7215 Remove a temporary script
  lib/tasks/temporary/social_media_handles.rake
Labels: PR: partially-approved

#7211 Replace DEV with the community name... almost everywhere
  app/views/articles/search/_meta.html.erb
  app/views/articles/show.html.erb
  app/views/chat_channels/index.html.erb
  app/views/classified_listings/edit.html.erb
  app/views/classified_listings/index.html.erb
  app/views/comments/_login_cta_comment.html.erb
  app/views/comments/index.html.erb
  app/views/credits/new.html.erb
  app/views/dashboards/followers.html.erb
  app/views/dashboards/following_organizations.html.erb
  app/views/dashboards/following_podcasts.html.erb
  app/views/dashboards/following_tags.html.erb
  app/views/dashboards/following_users.html.erb
  app/views/events/_event.html.erb
  app/views/events/index.html.erb
  app/views/events/show.html.erb
  app/views/internal/articles/_individual_article.html.erb
  app/views/moderations/index.html.erb
  app/views/pages/_terms_text.html.erb
  app/views/pages/badge.html.erb
  app/views/pages/badges.html.erb
  app/views/pages/crayons.html.erb
  app/views/pages/privacy.html.erb
  app/views/pages/terms.html.erb
  app/views/partnerships/_bronze_sponsor_copy.html.erb
  app/views/partnerships/_devrel_consult_copy.html.erb
  app/views/partnerships/_form.html.erb
  app/views/partnerships/_gold_sponsor_copy.html.erb
  app/views/partnerships/_media_sponsor_copy.html.erb
  app/views/partnerships/_silver_sponsor_copy.html.erb
  app/views/partnerships/_tag_sponsor_copy.html.erb
  app/views/partnerships/index.html.erb
  app/views/pro_memberships/show.html.erb
  app/views/users/_account.html.erb
  app/views/users/_integrations.html.erb
  app/views/users/_meta.html.erb
  app/views/users/_profile.html.erb
  app/views/users/_publishing_from_rss.html.erb
  app/views/videos/index.html.erb
  spec/requests/events_spec.rb
  spec/requests/videos_spec.rb
Labels: PR: unreviewed

#7204 Refactor Elasticsearch DataSync Classes
  app/models/concerns/searchable.rb
  app/models/organization.rb
  app/services/data_sync/elasticsearch/article.rb
  app/services/data_sync/elasticsearch/base.rb
  app/services/data_sync/elasticsearch/organization.rb
  app/services/data_sync/elasticsearch/user.rb
  spec/services/data_sync/elasticsearch/article_spec.rb
  spec/services/data_sync/elasticsearch/base_spec.rb
  spec/services/data_sync/elasticsearch/organization_spec.rb
  spec/services/data_sync/elasticsearch/user_spec.rb
Labels: PR: reviewed-approved

#7210 Replaced overriden pages with placeholders
  app/views/pages/_placeholder.html.erb
  app/views/pages/about.html.erb
  app/views/pages/bounty.html.erb
  app/views/pages/faq.html.erb
  spec/requests/pages_spec.rb
Labels: PR: partially-approved

#7216 Update all the static (i.e. DEV or dev.to) text on mailers to be dynamic
  app/views/mailers/digest_mailer/digest_email.html.erb
  app/views/mailers/notify_mailer/account_deleted_email.html.erb
  app/views/mailers/notify_mailer/account_deleted_email.text.erb
  app/views/mailers/notify_mailer/account_deletion_requested_email.html.erb
  app/views/mailers/notify_mailer/account_deletion_requested_email.txt.erb
  app/views/mailers/notify_mailer/new_follower_email.html.erb
  app/views/mailers/notify_mailer/new_mention_email.html.erb
  app/views/mailers/notify_mailer/new_message_email.html.erb
  app/views/mailers/notify_mailer/new_reply_email.html.erb
  app/views/mailers/notify_mailer/tag_moderator_confirmation_email.html.erb
  app/views/mailers/notify_mailer/tag_moderator_confirmation_email.text.erb
  app/views/mailers/notify_mailer/trusted_role_email.html.erb
  app/views/mailers/notify_mailer/trusted_role_email.text.erb
Labels: PR: partially-approved

#7206 Add canonical url to /new
  app/views/articles/new.html.erb
  spec/requests/articles/articles_spec.rb
Labels: PR: partially-approved

#7202 Add single resource admin roles for a few internal pages
  app/models/feedback_message.rb
  app/models/response_template.rb
  spec/requests/internal/feedback_messages_spec.rb
  spec/requests/internal/moderator_actions_spec.rb
  spec/requests/internal/negative_reactions_spec.rb
  spec/requests/internal/response_templates_spec.rb
Labels: PR: partially-approved

#7217 Remove old Connect video code and clean up some functionality
  app/assets/stylesheets/chat.scss
  app/controllers/video_chats_controller.rb
  app/javascript/chat/__tests__/__snapshots__/chat.test.jsx.snap
  app/javascript/chat/__tests__/__snapshots__/video.test.jsx.snap
  app/javascript/chat/__tests__/video.test.jsx
  app/javascript/chat/actions.js
  app/javascript/chat/channels.jsx
  app/javascript/chat/chat.jsx
  app/javascript/chat/video.jsx
  app/javascript/chat/videoContent.jsx
  app/javascript/packs/videoChat.jsx
  app/javascript/src/utils/pusher.js
  app/views/video_chats/show.html.erb
Labels: PR: unreviewed

#7220 Fix typo in videochat
  app/javascript/packs/videoChat.jsx
Labels: PR: unreviewed

#7221 Fix video chat typo
  app/javascript/chat/chat.jsx
Labels: PR: reviewed-approved

#7232 Revert generalization of meta content in offline.html
  app/views/tags/index.html.erb
  public/offline.html
Labels: PR: partially-approved

#7219 Upgrade Rubocop to 0.81
  .rubocop.yml
  .rubocop_todo.yml
  Gemfile.lock
  app/controllers/api/v0/api_controller.rb
  app/controllers/internal/configs_controller.rb
  app/controllers/internal/users_controller.rb
  app/lib/redcarpet/render/html_rouge.rb
  app/models/html_variant.rb
  app/models/podcast_episode.rb
  app/services/article_with_video_creation_service.rb
  app/services/articles/updater.rb
  app/services/notifications/new_comment/send.rb
  app/services/rss_reader/assembler.rb
  app/services/users/estimate_default_language.rb
  app/workers/metrics/record_daily_usage_worker.rb
  config/initializers/doorkeeper.rb
  docs/Gemfile
  spec/requests/internal/configs_spec.rb
  spec/requests/internal/reactions_spec.rb
  spec/services/broadcasts/welcome_notification/generator_spec.rb
Labels: PR: partially-approved

#7234 Small design and functionality touches to /connect
  app/assets/javascripts/initializers/initNotifications.js
  app/assets/stylesheets/chat.scss
  app/assets/stylesheets/top-bar.scss
  app/controllers/chat_channels_controller.rb
  app/javascript/chat/__tests__/__snapshots__/chat.test.jsx.snap
  app/javascript/chat/channels.jsx
  app/javascript/chat/chat.jsx
  app/javascript/packs/videoChat.jsx
  app/models/message.rb
  app/views/chat_channels/index.html.erb
  app/views/video_chats/show.html.erb
  spec/models/message_spec.rb
Labels: PR: unreviewed
