Repository forem/forem, pull requests merged in 2020-06, with the labels that each got.

#8209 Upgrade node to 12.17.0
  .nvmrc
  package.json
Labels: PR: partially-approved

#8149 Add feature flag support to Pages
  app/controllers/pages_controller.rb
  app/controllers/stories_controller.rb
  app/helpers/feature_flag.rb
  app/models/page.rb
  app/views/internal/pages/_form.html.erb
  spec/helpers/feature_flag_spec.rb
Labels: PR: partially-approved

#8177 Optimization:Use Scope and current_user to Get Notification Count
  app/controllers/notifications/counts_controller.rb
  app/models/notification.rb
  app/services/get_unseen_notifications_service.rb
  spec/requests/notification_counts_spec.rb
  spec/system/notifications/notifications_page_spec.rb
Labels: PR: partially-approved

#8217 Now jest-axe matchers for expect are imported for via the jest setupFilesAfterEnv config property
  app/javascript/onboarding/__tests__/Onboarding.test.jsx
  jest.config.js
  testSetup.js
Labels: PR: partially-approved, tech: javascript

#8174 Optimization: Remove Comment Count From Aysnc user_data
  app/assets/javascripts/initializers/initializeCommentsPage.js.erb
  app/controllers/async_info_controller.rb
  app/javascript/chat/__tests__/util.test.js
Labels: PR: partially-approved

#8219 Revert "Upgrade nvm to use node 12.17 (#8209)"
  .nvmrc
  package.json
Labels: PR: reviewed-approved

#8181 Add timestamps to broadcasts
  db/migrate/20200530084533_add_timestamps_to_broadcasts.rb
  db/schema.rb
  lib/data_update_scripts/20200530085153_backfill_broadcasts_timestamps.rb
Labels: PR: partially-approved

#8220 Temporarily raise read_timeout of Github::OauthClient
  app/services/github/oauth_client.rb
Labels: PR: partially-approved

#8213 Generalize DEV Digest
  app/controllers/internal/configs_controller.rb
  app/models/site_config.rb
  app/views/internal/configs/show.html.erb
  app/views/mailers/digest_mailer/digest_email.html.erb
  app/views/mailers/notify_mailer/trusted_role_email.html.erb
  app/views/mailers/notify_mailer/trusted_role_email.text.erb
  spec/requests/internal/configs_spec.rb
Labels: PR: partially-approved

#8210 Fix badge count update after merge
  app/controllers/internal/users_controller.rb
  app/services/moderator/merge_user.rb
  spec/services/moderator/merge_user_spec.rb
Labels: PR: partially-approved

#8222 Add Health Check Endpoint for Cache
  app/controllers/api/v0/health_checks_controller.rb
  config/routes.rb
  spec/requests/api/v0/health_checks_spec.rb
Labels: PR: reviewed-approved

#8227 Set Redis URL that will not be reused in specs
  spec/requests/api/v0/health_checks_spec.rb
Labels: PR: reviewed-approved

#8226 Change default fetch format in cloudinary links
  app/helpers/application_helper.rb
Labels: PR: reviewed-approved

#8111 Add Reddit Liquid Tag
  app/assets/images/reddit-icon.svg
  app/assets/stylesheets/ltags/LiquidTags.scss
  app/assets/stylesheets/ltags/RedditTag.scss
  app/liquid_tags/reddit_tag.rb
  app/views/liquids/_reddit.html.erb
  app/views/pages/_editor_guide_text.html.erb
  docs/frontend/liquid-tags.md
  spec/liquid_tags/reddit_tag_spec.rb
Labels: PR: partially-approved

#8229 Set --disable-march-tune-native when building sassc.
  .dockerignore
  Containerfile
Labels: PR: reviewed-approved

#8228 Swap sponsorships link
  app/views/articles/_sidebar.html.erb
  app/views/pages/sponsors.html.erb
Labels: PR: reviewed-approved

#8190 pages:sync rake task for easier local coding of HTML Page
  Gemfile
  Gemfile.lock
  docs/technical-overview/architecture.md
  lib/tasks/pages.rake
Labels: PR: partially-approved, area: developer experience

#8214 Add unique index to comments - part 6
  app/models/comment.rb
  db/migrate/20200601121243_add_unique_indexes_to_comments_body_markdown_user_id_ancestry_commentable.rb
  db/schema.rb
Labels: PR: reviewed-approved

#8225 Ignore Unfound Elasticsearch Docs and Records
  app/workers/search/index_worker.rb
  app/workers/search/remove_from_index_worker.rb
  spec/workers/search/index_worker_spec.rb
  spec/workers/search/remove_from_index_worker_spec.rb
Labels: PR: partially-approved

#8233 Only load Pages Rake in Development
  lib/tasks/pages.rake
Labels: PR: reviewed-approved

#8221 Remove All Notification Count Helper Classes
  app/controllers/notifications/reads_controller.rb
  app/labor/notification_counter.rb
  app/mailers/notify_mailer.rb
  app/services/read_notifications_service.rb
  spec/requests/notifications/reads_spec.rb
  spec/services/read_notifications_service_spec.rb
Labels: PR: partially-approved

#8231 Allow localhost or 127.0.0.1 to access api/health_checks without health-check-token
  app/controllers/api/v0/health_checks_controller.rb
  spec/requests/api/v0/health_checks_spec.rb
Labels: PR: partially-approved

#8235 Flaky Spec Fix: Stub pro? on user instead of using real role
  spec/system/articles/user_visits_article_stats_spec.rb
Labels: PR: reviewed-approved

#8236 Add If Statements to Skip Migrations If Index Exists
  db/migrate/20200601121243_add_unique_indexes_to_comments_body_markdown_user_id_ancestry_commentable.rb
Labels: PR: partially-approved

#7904 🚀 Feature: Chat Channel Request manager for mods
  app/assets/stylesheets/chat.scss
  app/controllers/chat_channel_memberships_controller.rb
  app/controllers/chat_channels_controller.rb
  app/javascript/chat/__tests__/__snapshots__/content.test.jsx.snap
  app/javascript/chat/__tests__/__snapshots__/requestManager.test.jsx.snap
  app/javascript/chat/__tests__/content.test.jsx
  app/javascript/chat/__tests__/requestManager.test.jsx
  app/javascript/chat/actions/actions.js
  app/javascript/chat/actions/requestActions.js
  app/javascript/chat/channels.jsx
  app/javascript/chat/chat.jsx
  app/javascript/chat/content.jsx
  app/javascript/chat/requestManager.jsx
  app/javascript/chat/util.js
  app/views/chat_channels/index.json.jbuilder
  spec/requests/chat_channels_spec.rb
Labels: PR: partially-approved

#8239 Enforce Uniqueness for Broadcast Titles
  .rubocop_todo.yml
  app/models/broadcast.rb
  db/schema.rb
  spec/models/broadcast_spec.rb
  spec/requests/internal/broadcasts_spec.rb
Labels: PR: partially-approved

#8242 CI Speed Up: Use Gems in Vendor Cache for Travis
  .travis.yml
Labels: PR: reviewed-approved

#8250 Generalize search.xml
  app/assets/config/manifest.js
  app/assets/xml/search.xml.erb
  app/views/shell/_top.html.erb
  config/initializers/assets.rb
  public/search.xml
Labels: PR: partially-approved

#8237 Attempt to fix rack protection issue with flipper UI
  config/routes.rb
Labels: PR: partially-approved

#8252 Editor overflow fix
  app/assets/stylesheets/views/article-form.scss
  app/views/articles/_v2_form.html.erb
Labels: PR: partially-approved, area: publishing experience

#8254 Joshpuetz/flipper ui fix attempt 2
  config/routes.rb
Labels: PR: partially-approved

#8253 Fixes Cloudinary helper calls that specify custom format
  app/controllers/stories_controller.rb
  app/views/service_worker/manifest.json.erb
  spec/requests/articles/articles_show_spec.rb
Labels: PR: partially-approved

#8258 Allow Admins to Delete Broadcasts
  app/controllers/internal/broadcasts_controller.rb
  app/views/internal/broadcasts/edit.html.erb
  config/routes.rb
  spec/requests/internal/broadcasts_spec.rb
Labels: PR: unreviewed

#8257 Small update to Test Coverage docs
  docs/tests/code-coverage.md
Labels: PR: partially-approved

#8151 Updated docs for debugging frontend tests
  docs/tests/frontend-tests.md
Labels: PR: partially-approved

#8259 Display Jobs Banner if User searches jobs or job
  app/controllers/internal/configs_controller.rb
  app/models/site_config.rb
  app/views/articles/search.html.erb
  app/views/internal/configs/show.html.erb
  spec/requests/internal/configs_spec.rb
Labels: PR: unreviewed

#8265 Add ApplicationRecord#errors_as_sentence
  app/controllers/api/v0/articles_controller.rb
  app/controllers/api_secrets_controller.rb
  app/controllers/chat_channels_controller.rb
  app/controllers/comments_controller.rb
  app/controllers/internal/reactions_controller.rb
  app/controllers/internal/response_templates_controller.rb
  app/controllers/internal/sponsorships_controller.rb
  app/controllers/omniauth_callbacks_controller.rb
  app/controllers/reactions_controller.rb
  app/controllers/response_templates_controller.rb
  app/controllers/user_blocks_controller.rb
  app/models/application_record.rb
Labels: PR: partially-approved

#8272 Add Migration File to Enforce Broadcast Title Uniqueness
  db/migrate/20200602174329_add_unique_index_to_broadcasts.rb
Labels: PR: partially-approved

#8107 Layout updates
  app/assets/javascripts/initializers/initializeAllFollowButts.js
  app/assets/javascripts/initializers/initializeBaseUserData.js
  app/assets/javascripts/initializers/initializeSettings.js
  app/assets/stylesheets/articles.scss
  app/assets/stylesheets/base/layout.scss
  app/assets/stylesheets/components/cards.scss
  app/assets/stylesheets/components/stories.scss
  app/assets/stylesheets/config/_colors.scss
  app/assets/stylesheets/onboarding.scss
  app/assets/stylesheets/themes/hacker.scss
  app/assets/stylesheets/themes/minimal.scss
  app/assets/stylesheets/themes/night.scss
  app/assets/stylesheets/themes/pink.scss
  app/assets/stylesheets/top-bar.scss
  app/assets/stylesheets/views/article-form.scss
  app/assets/stylesheets/views/article.scss
  app/assets/stylesheets/widgets.scss
  app/javascript/article-form/__tests__/__snapshots__/articleForm.test.jsx.snap
  app/javascript/article-form/articleForm.jsx
  app/javascript/article-form/components/Form.jsx
  app/javascript/article-form/components/Header.jsx
  app/javascript/article-form/components/Help.jsx
  app/javascript/article-form/components/PageTitle.jsx
  app/javascript/article-form/components/Preview.jsx
  app/javascript/article-form/components/__tests__/Help.test.jsx
  app/javascript/article-form/components/__tests__/__snapshots__/Form.test.jsx.snap
  app/javascript/article-form/components/__tests__/__snapshots__/Help.test.jsx.snap
  app/javascript/article-form/components/__tests__/__snapshots__/Preview.test.jsx.snap
  app/javascript/leftSidebar/TagsFollowed.jsx
  app/javascript/leftSidebar/__tests__/__snapshots__/TagsFollowed.test.jsx.snap
  app/javascript/onboarding/__tests__/__snapshots__/Onboarding.test.jsx.snap
  app/javascript/onboarding/components/FollowTags.jsx
  app/javascript/sidebar-widget/SidebarWidget.jsx
  app/javascript/sidebar-widget/__tests__/__snapshots__/sidebarUser.test.jsx.snap
  app/javascript/sidebar-widget/__tests__/sidebarUser.test.jsx
  app/javascript/sidebar-widget/sidebarUser.jsx
  app/views/articles/_sidebar.html.erb
  app/views/articles/_sidebar_additional.html.erb
  app/views/articles/_sidebar_campaign.html.erb
  app/views/articles/_sidebar_nav.html.erb
  app/views/articles/_v2_form.html.erb
  app/views/articles/_widget_list_item.html.erb
  app/views/articles/index.html.erb
  app/views/shared/authentication/_providers_sidebar.html.erb
  app/views/users/edit.html.erb
  spec/system/articles/user_visits_articles_by_tag_spec.rb
  spec/system/dashboards/user_followers_display_spec.rb
  spec/system/homepage/user_visits_homepage_spec.rb
  spec/system/notifications/notifications_page_spec.rb
  spec/system/organization/user_views_an_organization_spec.rb
  spec/system/search/display_users_search_spec.rb
  spec/system/search/user_searches_users_spec.rb
  spec/system/user/view_user_index_spec.rb
Labels: PR: partially-approved

#8269 Fix app_initializer:setup for Rails 6
  db/schema.rb
  lib/tasks/app_initializer.rake
Labels: PR: reviewed-approved

#8280 Bug Fix: Change Cache Key to Bust Cache
  app/controllers/reactions_controller.rb
Labels: PR: partially-approved

#8279 Bug Fix: Add Safety Operator When Handling params[:q]
  app/views/articles/search.html.erb
Labels: PR: partially-approved

#8284 Document the usage of Audit:Logger
  docs/backend/audit-log.md
  docs/backend/readme.md
Labels: PR: partially-approved

#8287 Remove Explict Gemfile from travis.yml to Allow vendor/cache to be used
  .travis.yml
Labels: PR: reviewed-approved

#8273 Add missing unique indexes to notifications
  .rubocop_todo.yml
  db/migrate/20200604133925_add_unique_index_to_notifications_user_id_organization_id_notifiable_action.rb
  db/schema.rb
Labels: PR: partially-approved

#8286 Stub Percy.snapshot During Specs
  spec/rails_helper.rb
Labels: PR: reviewed-approved

#8175 Streamline Tag parsing for both editors
  app/models/article.rb
  app/models/listing.rb
  app/models/tag.rb
  app/services/rss_reader/assembler.rb
  config/initializers/acts_as_taggable_on.rb
  spec/factories/articles.rb
  spec/liquid_tags/link_tag_spec.rb
  spec/models/article_spec.rb
  spec/models/tag_adjustment_spec.rb
  spec/models/tag_spec.rb
  spec/requests/articles/articles_create_spec.rb
  spec/system/user_uses_the_editor_spec.rb
Labels: PR: unreviewed

#8288 Also allow Asciinema URLs, not only IDs
  app/liquid_tags/asciinema_tag.rb
  app/views/pages/_editor_guide_text.html.erb
  spec/liquid_tags/asciinema_tag_spec.rb
Labels: PR: partially-approved

#8285 Resourcify ChatChannel
  app/models/chat_channel.rb
Labels: PR: partially-approved

#8161 Add path_redirects table and internal view
  app/controllers/internal/application_controller.rb
  app/controllers/internal/path_redirects_controller.rb
  app/models/path_redirect.rb
  app/views/internal/path_redirects/edit.html.erb
  app/views/internal/path_redirects/index.html.erb
  app/views/internal/path_redirects/new.html.erb
  app/views/internal/shared/_navbar.html.erb
  config/routes.rb
  db/migrate/20200527161505_create_path_redirect.rb
  db/schema.rb
  db/seeds.rb
  spec/factories/path_redirects.rb
  spec/models/path_redirect_spec.rb
  spec/requests/internal/path_redirects_spec.rb
Labels: PR: unreviewed

#8297 Remove STAFF_USER_ID from Envfile
  Envfile
Labels: PR: reviewed-approved

#8290 Update docs to shine more light on bin/setup and bin/startup
  docs/getting-started/syncing.md
  docs/getting-started/workflow.md
Labels: PR: partially-approved

#8205 Fix gists sometimes rendered in wrong order (attempt)
  app/views/articles/show.html.erb
Labels: PR: partially-approved

#8299 Enable ActsAsTaggableOn.strict_case_match
  config/initializers/acts_as_taggable_on.rb
Labels: PR: partially-approved

#8296 Replace defunct Algorithmia with Miro for color detection
  Gemfile
  Gemfile.lock
  app/labor/color_from_image.rb
  spec/labor/color_from_image_spec.rb
  spec/rails_helper.rb
  vendor/cache/algorithmia-1.1.0.gem
  vendor/cache/chunky_png-1.3.11.gem
  vendor/cache/climate_control-0.2.0.gem
  vendor/cache/cocaine-0.6.0.gem
  vendor/cache/color-1.8.gem
  vendor/cache/miro-0.4.0.gem
  vendor/cache/oily_png-1.2.1.gem
  vendor/cache/terrapin-0.6.0.gem
Labels: PR: reviewed-approved

#8307 Remove miro gem
  Gemfile
  Gemfile.lock
  app/labor/color_from_image.rb
  vendor/cache/chunky_png-1.3.11.gem
  vendor/cache/climate_control-0.2.0.gem
  vendor/cache/cocaine-0.6.0.gem
  vendor/cache/color-1.8.gem
  vendor/cache/miro-0.4.0.gem
  vendor/cache/oily_png-1.2.1.gem
  vendor/cache/terrapin-0.6.0.gem
Labels: PR: partially-approved

#8306 Remove unnecessary bulk from image assets
  app/assets/images/1.png
  app/assets/images/10.png
  app/assets/images/11.png
  app/assets/images/12.png
  app/assets/images/13.png
  app/assets/images/14.png
  app/assets/images/15.png
  app/assets/images/16.png
  app/assets/images/17.png
  app/assets/images/18.png
  app/assets/images/19.png
  app/assets/images/2.png
  app/assets/images/20.png
  app/assets/images/21.png
  app/assets/images/22.png
  app/assets/images/23.png
  app/assets/images/24.png
  app/assets/images/3.png
  app/assets/images/4.png
  app/assets/images/5.png
  app/assets/images/6.png
  app/assets/images/7.png
  app/assets/images/8.png
  app/assets/images/9.png
  app/assets/images/ben.jpg
  app/assets/images/clock.png
  app/assets/images/onboarding-background-white.png
  app/assets/images/onboarding-background.png
  app/assets/images/sloan.png
  app/javascript/articles/__tests__/__snapshots__/Article.test.jsx.snap
  app/javascript/articles/__tests__/utilities/articleUtilities.js
  app/javascript/crayons/avatarsAndLogos/Avatar/__stories__/avatars.html.stories.jsx
  app/javascript/onboarding/__tests__/Onboarding.test.jsx
  app/javascript/onboarding/__tests__/__snapshots__/Onboarding.test.jsx.snap
  app/models/site_config.rb
  app/views/comments/_comment_proper.html.erb
  app/views/comments/deleted_commentable_comment.html.erb
  app/views/dashboards/show.html.erb
  app/views/pages/crayons.html.erb
  public/catmeme.png
  spec/system/comments/user_fills_out_comment_spec.rb
Labels: PR: unreviewed

#8293 Routine Rubocop fixes
  .rubocop_todo.yml
  app/controllers/follows_controller.rb
  app/services/podcasts/episode_rss_item.rb
  db/seeds.rb
  lib/tasks/app_initializer.rake
  lib/tasks/pages.rake
  spec/helpers/feature_flag_spec.rb
Labels: PR: partially-approved

#8308 Nothing to see here....rollback master push 😬
  spec/decorators/user_decorator_spec.rb
  spec/factories/users.rb
  spec/labor/assign_tag_moderator_spec.rb
  spec/labor/mailchimp_bot_spec.rb
  spec/models/article_spec.rb
  spec/models/block_spec.rb
  spec/models/comment_spec.rb
  spec/models/notification_spec.rb
  spec/models/podcast_spec.rb
  spec/models/reaction_spec.rb
  spec/models/tag_adjustment_spec.rb
  spec/models/user_spec.rb
  spec/policies/article_policy_spec.rb
  spec/policies/chat_channel_policy_spec.rb
  spec/policies/comment_policy_spec.rb
  spec/policies/follow_policy_spec.rb
  spec/policies/internal_policy_spec.rb
  spec/policies/reaction_policy_spec.rb
  spec/policies/user_policy_spec.rb
  spec/rails_helper.rb
  spec/requests/api/v0/articles_spec.rb
  spec/requests/article_approvals_spec.rb
  spec/requests/articles/articles_spec.rb
  spec/requests/articles/articles_update_spec.rb
  spec/requests/buffer_updates_spec.rb
  spec/requests/chat_channel_memberships_spec.rb
  spec/requests/chat_channels_spec.rb
  spec/requests/dashboard_spec.rb
  spec/requests/html_variants_spec.rb
  spec/requests/internal/buffer_updates_spec.rb
  spec/requests/internal/chat_channel_spec.rb
  spec/requests/internal/podcasts_spec.rb
  spec/requests/internal/reactions_spec.rb
  spec/requests/internal/users_manage_spec.rb
  spec/requests/listings_spec.rb
  spec/requests/notifications_spec.rb
  spec/requests/shared_examples/internal_policy_dependant_request.rb
  spec/requests/tag_adjustments_spec.rb
  spec/requests/tags_spec.rb
  spec/requests/user/user_profile_spec.rb
  spec/services/moderator/manage_activity_and_roles_spec.rb
  spec/services/notifications/tag_adjustment_notification/send_spec.rb
  spec/services/search/user_spec.rb
  spec/services/slack/messengers/comment_user_warned_spec.rb
  spec/services/tag_adjustment_creation_service_spec.rb
  spec/services/tag_adjustment_update_service_spec.rb
  spec/system/internal/admin_bans_or_warns_user_spec.rb
  spec/system/notifications/notifications_page_spec.rb
  spec/workers/rating_votes/assign_rating_worker_spec.rb
Labels: PR: reviewed-approved

#8282 Feed Layout Fix
  app/assets/stylesheets/components/comments.scss
Labels: Crayons, PR: partially-approved, PR: unreviewed, area: homepage, tech: html/css

#8314 Flaky Spec Fixes: User Block and Sitemap Specs
  spec/requests/sitemaps_spec.rb
  spec/requests/user_blocks_spec.rb
Labels: PR: partially-approved

#8246 Make Devise.mailer_sender configurable
  Envfile
  app/controllers/internal/configs_controller.rb
  app/models/site_config.rb
  app/views/internal/configs/show.html.erb
  config/initializers/devise.rb
  spec/requests/internal/configs_spec.rb
Labels: PR: partially-approved, action: post deployment

#8211 Clean up BadgeRewarder
  app/labor/badge_rewarder.rb
Labels: PR: partially-approved

#8332 Flaky Spec Fix: Bulk Delete SQL Spec
  spec/services/bulk_sql_delete_spec.rb
Labels: PR: partially-approved

#8333 Make Video Permission a Valid Role
  app/models/role.rb
  spec/models/role_spec.rb
Labels: PR: partially-approved

#8341 Replace whitelisted_ips with permissions in Docker init
  config/initializers/docker.rb
Labels: PR: partially-approved

#8305 Spec Speed Up: Memoize Feed objects and Combine some Tests
  spec/services/articles/feed_spec.rb
Labels: PR: partially-approved

#8344 Remove video_permissions Role Reference From Specs and Code
  app/models/role.rb
  app/services/moderator/manage_activity_and_roles.rb
  spec/factories/users.rb
  spec/models/role_spec.rb
  spec/requests/api/v0/videos_spec.rb
  spec/requests/videos_spec.rb
  spec/system/internal/admin_bans_or_warns_user_spec.rb
Labels: PR: partially-approved

#8295 Adds config.hosts option in development environment
  config/environments/development.rb
Labels: PR: partially-approved, area: developer experience

#8263 Fix text out of bounds in Search results feed
  app/assets/stylesheets/components/stories.scss
Labels: PR: partially-approved

#8346 Routine rubocop fixes
  .rubocop.yml
  .rubocop_todo.yml
  app/controllers/concerns/valid_request.rb
  app/controllers/internal/articles_controller.rb
  app/helpers/application_helper.rb
  app/labor/markdown_fixer.rb
  app/lib/redcarpet/render/html_rouge.rb
  app/liquid_tags/codepen_tag.rb
  app/liquid_tags/codesandbox_tag.rb
  app/liquid_tags/gist_tag.rb
  app/liquid_tags/glitch_tag.rb
  app/liquid_tags/reddit_tag.rb
  app/liquid_tags/replit_tag.rb
  app/liquid_tags/soundcloud_tag.rb
  app/liquid_tags/wikipedia_tag.rb
  app/liquid_tags/youtube_tag.rb
  app/models/chat_channel.rb
  config/routes.rb
  db/seeds.rb
Labels: PR: partially-approved

#8347 Spec Speed Up: Comment Out Percy Only Specs
  spec/system/dashboards/user_scrolls_down_dashboard_follows_spec.rb
  spec/system/homepage/user_visits_homepage_spec.rb
  spec/system/user/view_user_index_spec.rb
  spec/system/user_uses_the_editor_spec.rb
Labels: PR: partially-approved

#7777 New Feature: Mod Actions Panel
  app/assets/images/book.svg
  app/assets/images/chevron-right.svg
  app/assets/images/chevron-toggle.svg
  app/assets/images/emoji/emoji-one-thumbs-up-gray.png
  app/assets/images/emoji/emoji-one-thumbs-up.png
  app/assets/images/mod-filled.svg
  app/assets/images/plus.svg
  app/assets/images/subtract.svg
  app/assets/javascripts/initializers/initializeBaseUserData.js
  app/assets/stylesheets/article-show.scss
  app/assets/stylesheets/moderators.scss
  app/controllers/internal/application_controller.rb
  app/controllers/internal/negative_reactions_controller.rb
  app/controllers/internal/privileged_reactions_controller.rb
  app/controllers/moderations_controller.rb
  app/controllers/rating_votes_controller.rb
  app/controllers/reactions_controller.rb
  app/controllers/tag_adjustments_controller.rb
  app/javascript/actionsPanel/__tests__/actionsPanel.test.js
  app/javascript/actionsPanel/__tests__/initializeActionsPanelToggle.test.js
  app/javascript/actionsPanel/actionsPanel.js
  app/javascript/actionsPanel/initializeActionsPanelToggle.js
  app/javascript/packs/actionsPanel.js
  app/javascript/packs/articleModerationTools.js
  app/javascript/packs/articlePage.jsx
  app/javascript/packs/flagUserModal.js
  app/models/privileged_reaction.rb
  app/models/reaction.rb
  app/policies/user_policy.rb
  app/views/articles/show.html.erb
  app/views/internal/mods/index.html.erb
  app/views/internal/privileged_reactions/index.html.erb
  app/views/moderations/actions_panel.html.erb
  app/views/moderations/index.html.erb
  app/views/moderations/mod.html.erb
  config/routes.rb
  config/webpack/environment.js
  db/schema.rb
  docs/backend/metrics.md
  jsconfig.json
  spec/policies/user_policy_spec.rb
  spec/requests/internal/privileged_reactions_spec.rb
  spec/requests/moderations_spec.rb
Labels: PR: unreviewed

#8301 Display site-wide announcements
  app/assets/javascripts/initializePage.js
  app/assets/javascripts/initializers/initializeBodyData.js
  app/assets/javascripts/initializers/initializeBroadcast.js
  app/assets/stylesheets/scaffolds.scss
  app/controllers/async_info_controller.rb
  app/views/internal/broadcasts/_form.html.erb
  app/views/shell/_top.html.erb
  spec/factories/broadcasts.rb
  spec/requests/async_info_spec.rb
  spec/system/homepage/user_visits_homepage_spec.rb
Labels: PR: partially-approved

#8348 Spec Speedup: Comment Out More Percy Only Specs
  spec/system/articles/user_creates_an_article_spec.rb
  spec/system/articles/user_deletes_an_article_spec.rb
  spec/system/articles/user_edits_an_article_spec.rb
  spec/system/articles/user_visits_an_article_spec.rb
  spec/system/articles/user_visits_articles_by_timeframe_spec.rb
  spec/system/comments/user_edits_a_comment_spec.rb
  spec/system/internal/admin_awards_badges_spec.rb
  spec/system/internal/admin_bans_or_warns_user_spec.rb
  spec/system/internal/admin_creates_new_event_spec.rb
  spec/system/internal/admin_manages_reports_spec.rb
  spec/system/organization/user_updates_org_settings_spec.rb
  spec/system/user/user_edits_integrations_spec.rb
  spec/system/user/user_settings_response_templates_spec.rb
  spec/system/user_selects_looking_for_work_spec.rb
  spec/system/user_uses_the_editor_spec.rb
Labels: PR: partially-approved

#8342 Use Rails 6 new features in the code
  app/models/broadcast.rb
  app/models/chat_channel.rb
  app/models/collection.rb
  app/models/data_update_script.rb
  app/services/analytics_service.rb
  app/workers/webhook/destroy_worker.rb
  config/initializers/active_support/cache/redis_cache_store.rb
  db/seeds.rb
  lib/tasks/fetch.rake
  spec/models/collection_spec.rb
Labels: PR: reviewed-approved

#8359 Shrink mod button on narrow screens
  app/assets/stylesheets/article-show.scss
Labels: PR: partially-approved

#8303 Use Javascript to Display Jobs Banner
  app/controllers/search_controller.rb
  app/views/articles/_search.html.erb
  app/views/articles/search.html.erb
  spec/requests/search_spec.rb
  spec/system/search/display_jobs_banner_spec.rb
Labels: PR: partially-approved

#8298 fix footnote anchor tag misposition
  app/assets/stylesheets/article-show.scss
Labels: PR: reviewed-approved

#8360 Upgrade rubocop to 0.85.1
  Gemfile
  Gemfile.lock
  vendor/cache/rubocop-0.85.0.gem
  vendor/cache/rubocop-0.85.1.gem
Labels: PR: partially-approved

#8315 Replace querySelector and getElementsByTagName when selecting for head and body
  app/assets/javascripts/initializers/initializeArticleReactions.js
  app/assets/javascripts/initializers/initializeBodyData.js
  app/assets/javascripts/initializers/initializeCommentsPage.js.erb
  app/assets/javascripts/initializers/initializeEllipsisMenu.js
  app/assets/javascripts/initializers/initializeLocalStorageRender.js
  app/assets/javascripts/initializers/initializeReadingListIcons.js
  app/assets/javascripts/initializers/initializeStylesheetAppend.js.erb
  app/assets/javascripts/initializers/initializeTouchDevice.js
  app/assets/javascripts/utilities/checkUserLoggedIn.js
  app/assets/javascripts/utilities/showModal.js
  app/assets/javascripts/utilities/slideSidebar.js
  app/javascript/Search/Search.jsx
  app/javascript/packs/notificationSubscriptionHandler.js
  app/views/articles/_fitvids.html.erb
  app/views/layouts/_user_config.html.erb
  app/views/pages/badge.html.erb
  app/views/twitch_live_streams/show.html.erb
Labels: PR: unreviewed

#8349 apply word break fix to title as well
  app/assets/stylesheets/components/stories.scss
Labels: PR: reviewed-approved

#8354 Flaky Spec Fixes: Dont Assume No Elasticsearch Data, Refresh before delete_by_query
  spec/support/elasticsearch_helpers.rb
  spec/workers/metrics/record_data_counts_worker_spec.rb
Labels: PR: partially-approved

#8363 Rewrite GithubRepos with async/await for better debugging
  app/javascript/githubRepos/githubRepos.jsx
Labels: PR: reviewed-approved

#8358 Fix Vomit Button text bug upon click
  app/assets/stylesheets/moderators.scss
  app/views/moderations/actions_panel.html.erb
Labels: PR: reviewed-approved

#8350 Flaky Spec Fix: Set Profile Image to Nil to Avoid Server Errors in js Specs
  .travis.yml
  spec/system/articles/user_visits_articles_by_tag_spec.rb
  spec/system/homepage/user_visits_homepage_articles_spec.rb
Labels: PR: partially-approved

#8366 Fix bug in db/seeds that may blow up while assigning fake user roles
  db/schema.rb
  db/seeds.rb
Labels: PR: reviewed-approved

#8367 Rainbow loader
  app/assets/stylesheets/shared.scss
Labels: PR: partially-approved, tech: html/css

#8364 Improve accessibility in moderation panel
  app/javascript/actionsPanel/initializeActionsPanelToggle.js
  app/views/moderations/actions_panel.html.erb
Labels: PR: partially-approved, accessibility

#8361 Provide default crayon styles when creating banners
  app/assets/javascripts/initializers/initializeBroadcast.js
  app/assets/stylesheets/internal/layout.scss
  app/controllers/async_info_controller.rb
  app/controllers/internal/broadcasts_controller.rb
  app/helpers/broadcasts_helper.rb
  app/models/broadcast.rb
  app/views/internal/broadcasts/_form.html.erb
  app/views/internal/broadcasts/edit.html.erb
  db/migrate/20200608175130_add_banner_style_to_broadcasts.rb
  db/schema.rb
  spec/models/broadcast_spec.rb
Labels: PR: unreviewed

#8343 Allow Users to Opt-out of Announcements
  app/controllers/async_info_controller.rb
  app/policies/user_policy.rb
  app/views/users/_misc.html.erb
  db/migrate/20200605183117_add_display_announcements_boolean_to_users.rb
  db/schema.rb
  spec/requests/user/user_settings_spec.rb
Labels: PR: partially-approved

#8304 Allow users to set a payment pointer for their content
  app/assets/javascripts/initializePage.js
  app/assets/javascripts/initializers/initializePaymentPointers.js
  app/policies/user_policy.rb
  app/views/articles/show.html.erb
  app/views/comments/index.html.erb
  app/views/layouts/application.html.erb
  app/views/shared/_payment_pointer.html.erb
  app/views/users/_misc.html.erb
  app/views/users/show.html.erb
  db/migrate/20200605170430_add_payment_pointer_to_users.rb
  db/schema.rb
  spec/requests/comments_spec.rb
  spec/requests/stories_show_spec.rb
  spec/requests/user/user_profile_spec.rb
Labels: PR: unreviewed

#8381 HOTFIX text wrapping
  app/assets/stylesheets/components/stories.scss
Labels: PR: partially-approved, tech: html/css

#8368 Improve GithubRepos component error handling
  app/assets/stylesheets/settings.scss
  app/javascript/githubRepos/__tests__/__snapshots__/githubRepos.test.jsx.snap
  app/javascript/githubRepos/__tests__/githubRepos.test.jsx
  app/javascript/githubRepos/githubRepos.jsx
Labels: PR: reviewed-approved

#8339 Use official Asciinema player embed
  app/javascript/article-form/articleForm.jsx
  app/views/liquids/_asciinema.html.erb
Labels: PR: partially-approved

#8193 Implement chronological sorting of search results
  app/controllers/stories_controller.rb
  app/javascript/utilities/search/index.js
  app/views/articles/_search.html.erb
  app/views/articles/search.html.erb
  spec/services/search/feed_content_spec.rb
  spec/services/search/query_builders/feed_content_spec.rb
Labels: PR: partially-approved, area: design, area: search/indexing

#8397 Update example code
  docs/design/theming.md
Labels: PR: reviewed-approved

#8401 Fix erblint errors on the `app/views/pages` folder
  app/controllers/feedback_messages_controller.rb
  app/controllers/pages_controller.rb
  app/views/pages/_terms_text.html.erb
  app/views/pages/generator.html.erb
  app/views/pages/report_abuse.html.erb
  app/views/pages/rlyweb.html.erb
Labels: PR: partially-approved

#8400 Fix erblint errors on the `app/views/layouts` folder
  app/views/layouts/application.html.erb
  app/views/layouts/doorkeeper/admin.html.erb
  app/views/layouts/doorkeeper/application.html.erb
Labels: PR: reviewed-approved

#8396 Allow users to dismiss announcements
  app/assets/javascripts/initializers/initializeBroadcast.js
  app/assets/stylesheets/internal/layout.scss
  app/assets/stylesheets/scaffolds.scss
  app/views/internal/broadcasts/_form.html.erb
  spec/factories/broadcasts.rb
  spec/system/homepage/user_visits_homepage_spec.rb
  spec/system/homepage/user_visits_homepage_with_announcement_spec.rb
Labels: PR: partially-approved

#8390 Spec Speedup: Use Knapsack to Run Parallel Builds
  .rspec
  .travis.yml
  Gemfile
  Gemfile.lock
  docs/tests/readme.md
  spec/rails_helper.rb
  spec/requests/api/v0/articles_spec.rb
  spec/requests/api/v0/follows_spec.rb
  spec/services/bulk_sql_delete_spec.rb
  spec/support/initializers/vcr.rb
  vendor/cache/knapsack_pro-1.22.2.gem
Labels: PR: partially-approved

#8399 Fix erblint errors on the `app/views/doorkeeper` folder
  app/views/doorkeeper/applications/_delete_form.html.erb
  app/views/doorkeeper/applications/_form.html.erb
  app/views/doorkeeper/applications/edit.html.erb
  app/views/doorkeeper/applications/index.html.erb
  app/views/doorkeeper/applications/new.html.erb
  app/views/doorkeeper/authorizations/error.html.erb
  app/views/doorkeeper/authorizations/new.html.erb
  app/views/doorkeeper/authorizations/show.html.erb
  app/views/doorkeeper/authorized_applications/_delete_form.html.erb
  app/views/doorkeeper/authorized_applications/index.html.erb
Labels: PR: partially-approved

#8402 Fix erblint errors on the `app/views/mailers` folder
  app/views/mailers/notify_mailer/new_message_email.html.erb
  app/views/mailers/notify_mailer/new_reply_email.html.erb
  app/views/mailers/notify_mailer/tag_moderator_confirmation_email.html.erb
  app/views/mailers/notify_mailer/trusted_role_email.html.erb
Labels: PR: partially-approved

#8413 Allow Knapsack to work for Forks
  .travis.yml
  bin/knapsack_pro_rspec
Labels: PR: partially-approved

#8410 Use Preact to load articles for layout
  app/assets/stylesheets/moderators.scss
  app/controllers/moderations_controller.rb
  app/javascript/moderationArticles/moderationArticles.jsx
  app/javascript/moderationArticles/singleArticle/articlePropTypes.js
  app/javascript/moderationArticles/singleArticle/index.jsx
  app/javascript/packs/moderationArticles.jsx
  app/views/moderations/index.html.erb
Labels: PR: reviewed-approved

#8412 Add QA instructions to pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: PR: unreviewed

#8415 Bump top-bar's z-index to allow dropdown to render with announcement
  app/assets/stylesheets/top-bar.scss
Labels: PR: partially-approved

#8405 Fix remaining erblint errors
  app/views/articles/tags/_sidebar.html.erb
  app/views/comments/settings.html.erb
  app/views/internal/listings/index.html.erb
  app/views/partnerships/index.html.erb
  app/views/shared/_payment_pointer.html.erb
  app/views/tags/_liquid.html.erb
  app/views/video_chats/show.html.erb
Labels: PR: unreviewed

#8403 Fix erblint errors on the `app/views/liquids` folder
  app/views/liquids/_github_issue.html.erb
  app/views/liquids/_instagram.html.erb
  app/views/liquids/_kotlin.html.erb
  app/views/liquids/_parler.html.erb
  app/views/liquids/_poll.html.erb
  app/views/liquids/_stackexchange.html.erb
  spec/support/fixtures/approvals/kotlin_liquid_tag.approved.html
Labels: PR: unreviewed

#8382 Clean up inaccessible repositories
  app/controllers/github_repos_controller.rb
  spec/requests/github_repos_spec.rb
Labels: PR: partially-approved

#8394 Update Users::Sidebar not to cache AR object
  app/services/suggester/users/sidebar.rb
  spec/services/suggester/users/sidebar_spec.rb
Labels: PR: unreviewed

#8393 Update ReactionsController not to cache AR Object
  app/controllers/reactions_controller.rb
  spec/requests/reactions_spec.rb
Labels: PR: unreviewed

#8409 Hide site-wide messaging for opted-out users
  app/assets/javascripts/initializers/initializeBroadcast.js
  spec/factories/users.rb
  spec/system/homepage/user_visits_homepage_with_announcement_spec.rb
Labels: PR: partially-approved

#8416 Refactor BroadcastsController
  app/controllers/internal/broadcasts_controller.rb
Labels: PR: partially-approved

#8408 Fix container-setup logic #8255
  bin/container-setup
Labels: PR: partially-approved

#8421 Flaky Spec Fix: Ignore Order For User Suggestion in Sidebar
  spec/services/suggester/users/sidebar_spec.rb
Labels: PR: partially-approved

#8417 [Mod Center] Implement grid layout; format Date
  app/assets/stylesheets/moderators.scss
  app/javascript/moderationArticles/singleArticle/index.jsx
Labels: PR: reviewed-approved

#8422 Spec SpeedUp: Refactor and Combine Assertions for Viewing Articles by Timeframe Spec
  spec/system/articles/user_visits_articles_by_timeframe_spec.rb
Labels: PR: partially-approved

#8426 Flaky Spec Fix: Stub Requests to Elasticsearch For some js: true Specs
  docs/tests/test-flags.md
  spec/rails_helper.rb
  spec/system/articles/user_visits_articles_by_tag_spec.rb
  spec/system/articles/user_visits_articles_by_timeframe_spec.rb
  spec/system/homepage/user_visits_homepage_with_announcement_spec.rb
  spec/system/user/view_user_index_spec.rb
Labels: PR: unreviewed

#8419 Documentation: Add More Knapsack Information to Docs
  README.md
  docs/deployment.md
  docs/tests/readme.md
Labels: PR: unreviewed

#8427 Hide active announcements from logged-in users on the editor
  app/assets/javascripts/initializers/initializeBroadcast.js
  app/assets/stylesheets/scaffolds.scss
  app/javascript/packs/articleForm.jsx
  spec/system/articles/user_creates_an_article_spec.rb
Labels: PR: partially-approved

#8424 Documentation: Document Status of Percy
  docs/tests/readme.md
  docs/tests/regression-tests.md
Labels: PR: partially-approved

#8407 Replace activerecord-import with Rails 6 insert_all and upsert_all
  Gemfile
  Gemfile.lock
  app/controllers/credits_controller.rb
  app/models/credit.rb
  app/services/notifications/notifiable_action/send.rb
  app/services/notifications/reactions/send.rb
  app/services/podcasts/create_episode.rb
  spec/models/notification_spec.rb
  spec/services/notifications/notifiable_action/send_spec.rb
  vendor/cache/activerecord-import-1.0.5.gem
Labels: PR: partially-approved

#8404 Fix erblint errors on the `app/views/stories` folder
  app/views/stories/_narrow_nav_menu.html.erb
  app/views/stories/_sign_in_invitation.html.erb
Labels: PR: partially-approved

#8420 Add margin to the join box for better UI
  app/assets/stylesheets/articles.scss
Labels: PR: partially-approved

#8431 Allow admins to define onboarding images in config
  app/controllers/internal/configs_controller.rb
  app/javascript/onboarding/Onboarding.jsx
  app/javascript/onboarding/__tests__/Onboarding.test.jsx
  app/javascript/onboarding/__tests__/__snapshots__/Onboarding.test.jsx.snap
  app/javascript/onboarding/components/IntroSlide.jsx
  app/javascript/packs/Onboarding.jsx
  app/models/site_config.rb
  app/views/internal/configs/show.html.erb
  app/views/onboardings/show.html.erb
  spec/requests/internal/configs_spec.rb
  spec/requests/onboardings_spec.rb
Labels: PR: partially-approved

#8423 [Mod Center] Add cute mod greeting to right column
  app/assets/stylesheets/moderators.scss
  app/views/moderations/_mod_sidebar_left.html.erb
  app/views/moderations/_mod_sidebar_right.html.erb
  app/views/moderations/index.html.erb
Labels: PR: reviewed-approved

#8444 Modify default size for onboarding graphic
  app/views/onboardings/show.html.erb
Labels: PR: reviewed-approved

#8449 Partially revert "Update ReactionsController not to cache AR Object (#8393)"
  app/controllers/reactions_controller.rb
Labels: PR: unreviewed

#8447 Flaky Spec Fix:Sitemap: Don't assume Database Ordering, Explicitly Set Articles for Assertions
  spec/requests/sitemaps_spec.rb
Labels: PR: partially-approved

#8453 Spec Cleanup: Stub Elasticsearch for js: true Specs that Dont Need it
  spec/system/homepage/user_visits_homepage_articles_spec.rb
  spec/system/organization/user_views_an_organization_spec.rb
  spec/system/search/display_jobs_banner_spec.rb
  spec/system/user/view_user_comments_spec.rb
  spec/system/user_uses_the_editor_spec.rb
Labels: PR: partially-approved

#8675 Remove private reactions from notifictaions
  app/services/notifications/reactions/send.rb
  spec/requests/notifications_spec.rb
Labels: PR: reviewed-approved

#8450 Travis Speed Up/Fixes: Dont Run Deploy Stages for PRs, Fix Notification and Service Warnings
  .travis.yml
Labels: PR: reviewed-approved

#8670 Adding aria-label for featured article
  app/views/articles/_single_story.html.erb
Labels: PR: partially-approved

#8375 Email signups liquid tag backend
  app/models/article.rb
  app/models/user.rb
  app/models/user_subscription.rb
  db/migrate/20200609192545_create_user_subscriptions.rb
  db/schema.rb
  spec/factories/user_subscription.rb
  spec/models/user_subscription_spec.rb
Labels: PR: unreviewed

#8455 [ModCenter] Update view heading and highlight chosen tag, on tag selection
  app/assets/stylesheets/moderators.scss
  app/javascript/modCenter/modCenter.js
  app/javascript/modCenter/moderationArticles.jsx
  app/javascript/modCenter/singleArticle/articlePropTypes.js
  app/javascript/modCenter/singleArticle/index.jsx
  app/javascript/packs/modCenter.jsx
  app/views/moderations/_mod_sidebar_left.html.erb
  app/views/moderations/index.html.erb
Labels: PR: reviewed-approved

#8676 Fix bug in determining if repo is featured
  app/controllers/github_repos_controller.rb
  spec/requests/github_repos_spec.rb
Labels: PR: partially-approved

#8677 Update config.hosts for GitPod
  .gitpod.dockerfile
  .nvmrc
  config/environments/development.rb
Labels: PR: partially-approved

#8448 Add button to unfollow tags and users from dashboard
  app/assets/stylesheets/dashboard.scss
  app/views/dashboards/followers.html.erb
  app/views/dashboards/following_tags.html.erb
  app/views/dashboards/following_users.html.erb
  spec/system/dashboards/user_followers_display_spec.rb
Labels: PR: partially-approved

#8679 Branded authentication buttons
  app/assets/images/apple.svg
  app/assets/stylesheets/components/buttons.scss
  app/assets/stylesheets/signup-modal.scss
  app/views/devise/registrations/_registration_form.html.erb
  app/views/layouts/_nav_menu.html.erb
  app/views/layouts/_signup_modal.html.erb
  app/views/shared/authentication/_providers_nav_menu.html.erb
  app/views/shared/authentication/_providers_registration_form.html.erb
  app/views/shared/authentication/_providers_sidebar.html.erb
  app/views/shared/authentication/_providers_signup_modal.html.erb
  app/views/users/_account.html.erb
  app/views/users/_additional_authentication.html.erb
  app/views/users/_profile.html.erb
  spec/system/authentication/user_logs_in_with_github_spec.rb
  spec/system/authentication/user_logs_in_with_twitter_spec.rb
  spec/system/homepage/user_visits_homepage_spec.rb
Labels: PR: partially-approved, area: auth, tech: html/css

#8445 Remove user_counters table
  app/models/user.rb
  app/models/user_counter.rb
  app/serializers/hash_serializer.rb
  db/migrate/20200612140153_drop_user_counters.rb
  db/schema.rb
  lib/tasks/counters.rake
  spec/factories/user_counters.rb
  spec/models/user_counter_spec.rb
  spec/models/user_spec.rb
Labels: PR: unreviewed

#8436 Small ActiveRecord optimizations: begone race conditions and hello bulk insert
  app/controllers/poll_skips_controller.rb
  app/models/chat_channel.rb
  app/models/data_update_script.rb
  spec/models/chat_channel_spec.rb
  spec/models/data_update_script_spec.rb
  spec/requests/chat_channel_memberships_spec.rb
  spec/requests/poll_skips_spec.rb
Labels: PR: partially-approved

#8369 Fix liquid tags overflow
  app/assets/stylesheets/ltags/CommentTag.scss
  app/assets/stylesheets/ltags/TagTag.scss
  app/assets/stylesheets/ltags/UserTag.scss
  app/views/tags/_liquid.html.erb
Labels: PR: partially-approved

#8452 Update ReactionsController not to cache AR Object (2nd attempt)
  app/controllers/reactions_controller.rb
Labels: PR: partially-approved

#8687 Always set the default email address to ENV variable
  app/controllers/internal/configs_controller.rb
  app/views/internal/configs/show.html.erb
  spec/requests/internal/configs_spec.rb
Labels: PR: partially-approved

#8689 Flaky Spec Fix: Ensure Article Titles are Unique
  spec/factories/articles.rb
Labels: PR: partially-approved

#8513 Skynox/fix eslint and redirection bug
  app/javascript/chat/__tests__/__snapshots__/content.test.jsx.snap
  app/javascript/chat/chat.jsx
  app/javascript/chat/content.jsx
  app/models/message.rb
  app/views/chat_channel_memberships/edit.html.erb
Labels: PR: reviewed-approved

#8686 Remove unnecessary comment links and clean up logic
  app/assets/javascripts/initializers/initializeBaseUserData.js
  app/assets/javascripts/initializers/initializeCommentsPage.js.erb
  app/views/comments/_comment_proper.html.erb
Labels: PR: reviewed-approved

#8696 Update Rack to Fix Bundle Audit Failure
  Gemfile.lock
  vendor/cache/rack-2.2.2.gem
  vendor/cache/rack-2.2.3.gem
Labels: PR: partially-approved

#8685 Routine rubocop fixes
  .rubocop_todo.yml
  app/liquid_tags/github_tag/github_issue_tag.rb
  app/models/feedback_message.rb
  app/models/podcast.rb
  app/models/user.rb
  app/models/user_block.rb
  app/models/user_subscription.rb
  app/models/webhook/endpoint.rb
  app/services/analytics_service.rb
  spec/models/user_spec.rb
  spec/requests/chat_channels_spec.rb
  spec/requests/notifications_spec.rb
Labels: PR: reviewed-approved
