Repository forem/forem, pull requests merged in 2020-08, with the labels that each got.

#9601 Add explicit robots instruction meta tag and adjust cloudinary
  app/view_objects/articles/social_image.rb
  app/view_objects/cloud_cover_url.rb
  app/views/articles/show.html.erb
  spec/helpers/social_image_helper_spec.rb
  spec/services/search/feed_content_spec.rb
  spec/view_objects/cloud_cover_url_spec.rb
Labels: PR: unreviewed

#9602 Remove a few unnecessary css lines
  app/assets/stylesheets/article-show.scss
  app/views/layouts/_styles.html.erb
Labels: PR: unreviewed

#9576 Move Admin interface paths
  app/controllers/resource_admin/application_controller.rb
  app/controllers/resource_admin/articles_controller.rb
  app/controllers/resource_admin/badge_achievements_controller.rb
  app/controllers/resource_admin/badges_controller.rb
  app/controllers/resource_admin/collections_controller.rb
  app/controllers/resource_admin/comments_controller.rb
  app/controllers/resource_admin/display_ads_controller.rb
  app/controllers/resource_admin/email_messages_controller.rb
  app/controllers/resource_admin/feedback_messages_controller.rb
  app/controllers/resource_admin/follows_controller.rb
  app/controllers/resource_admin/html_variant_successes_controller.rb
  app/controllers/resource_admin/html_variant_trials_controller.rb
  app/controllers/resource_admin/html_variants_controller.rb
  app/controllers/resource_admin/listing_categories_controller.rb
  app/controllers/resource_admin/organizations_controller.rb
  app/controllers/resource_admin/podcast_episodes_controller.rb
  app/controllers/resource_admin/podcasts_controller.rb
  app/controllers/resource_admin/reactions_controller.rb
  app/controllers/resource_admin/sponsorships_controller.rb
  app/controllers/resource_admin/tags_controller.rb
  app/controllers/resource_admin/users_controller.rb
  app/views/resouce_admin/application/_collection.html.erb
  app/views/resouce_admin/application/index.html.erb
  app/views/service_worker/index.js.erb
  config/routes.rb
  docs/backend/configuration.md
  docs/backend/readme.md
  docs/backend/resource-admin.md
  docs/backend/roles.md
  spec/requests/admin/podcasts_spec.rb
  spec/system/admin/admin_dashboard_presented_spec.rb
Labels: Forem team, PR: draft, PR: partially-approved, PR: unreviewed, area: internal

#9613 Feature:Show Status For DataUpdateScript Enum Column
  config/blazer.yml
Labels: PR: partially-approved

#9586 Improve accessibility of welcome message
  app/views/onboardings/_task_card.html.erb
Labels: PR: reviewed-approved, cla-not-yet-signed

#9614 Revert "[deploy] Prevent signing up with no email (#9584)"
  app/models/user.rb
  spec/models/user_spec.rb
  spec/requests/user/user_destroy_spec.rb
  spec/services/users/estimate_default_language_spec.rb
Labels: PR: partially-approved

#9580 Add ProfileField model
  app/models/profile_field.rb
  db/migrate/20200731041554_create_profile_fields.rb
  db/schema.rb
  spec/factories/profile_fields.rb
  spec/models/profile_field_spec.rb
Labels: PR: partially-approved

#9611 Update containers: DEV => Forem
  Containerfile
  bin/container-setup
  container-compose.yml
  docker-compose.yml
Labels: PR: unreviewed

#9618 Add redirects from docs.dev.to to docs.forem.com
  docs/netlify.toml
Labels: PR: partially-approved

#9622 Force redirect for docs.dev.to to docs.forem.com
  docs/netlify.toml
Labels: PR: unreviewed

#9528 homepageFeed: Add null checks in cases where there's no featured story present
  app/javascript/packs/homePageFeed.jsx
Labels: PR: reviewed-approved

#9624 Set APP_DOMAIN to rails to fix #9604
  container-compose.yml
  docker-compose.yml
Labels: PR: reviewed-approved

#9616 Bug Fix:Redirect to Direct User Channel for Org Listings
  app/controllers/listings_controller.rb
  app/javascript/listings/__tests__/AllListings.test.jsx
  app/javascript/listings/listings.jsx
Labels: PR: partially-approved

#9625 Add in a VOLUME directive in the Container file.
  Containerfile
Labels: PR: reviewed-approved

#9630 Correct some lingering `/admin` paths
  app/controllers/resource_admin/comments_controller.rb
  app/controllers/resource_admin/tags_controller.rb
  app/controllers/stories_controller.rb
  app/controllers/tags_controller.rb
  spec/requests/user/user_profile_spec.rb
Labels: PR: partially-approved

#9632 CI Optimization:Remove unused ENV variables and Skip install Step
  .travis.yml
Labels: PR: partially-approved

#9605 Seed profile fields
  app/services/profile_fields/add_base_fields.rb
  app/services/profile_fields/add_branding_fields.rb
  app/services/profile_fields/add_link_fields.rb
  app/services/profile_fields/add_work_fields.rb
  app/services/profile_fields/field_definition.rb
  app/services/profile_fields/import_from_csv.rb
  bin/setup
  db/migrate/20200804035648_add_description_to_profile_fields.rb
  db/migrate/20200805050048_add_group_to_profile_fields.rb
  db/schema.rb
  db/seeds.rb
  lib/data/coding_profile_fields.csv
  lib/tasks/forem.rake
  spec/fixtures/files/profile_fields.csv
  spec/services/profile_fields/field_definition_spec.rb
  spec/services/profile_fields/import_from_csv_spec.rb
Labels: PR: partially-approved

#9634 Bug Fix:Hide To Email Field on Ahoy Messages
  config/environments/production.rb
  config/initializers/hypershield.rb
Labels: PR: partially-approved

#9631 Conditionally remove `no-cache` from Fastly headers
  app/controllers/application_controller.rb
  app/controllers/concerns/caching_headers.rb
Labels: PR: partially-approved

#9608 Ensure all elements are contained by landmarks in mod center
  app/views/moderations/_mod_sidebar_left.html.erb
  app/views/moderations/index.html.erb
Labels: PR: partially-approved

#9610 Profile Admin UI Setup Screen (v1)
  app/controllers/internal/application_controller.rb
  app/controllers/internal/profile_fields_controller.rb
  app/models/profile_field.rb
  app/views/internal/profile_fields/_form.html.erb
  app/views/internal/profile_fields/index.html.erb
  config/routes.rb
  spec/factories/profile_fields.rb
  spec/requests/internal/profile_fields_spec.rb
Labels: PR: partially-approved

#9054 Overview of my own series #6938
  app/views/dashboards/_actions.html.erb
Labels: PR: reviewed-approved

#9626 Buttons: Ghost Dimmed
  app/assets/javascripts/utilities/buildArticleHTML.js
  app/assets/stylesheets/components/buttons.scss
  app/assets/stylesheets/config/_colors.scss
  app/assets/stylesheets/themes/hacker.scss
  app/assets/stylesheets/themes/minimal.scss
  app/assets/stylesheets/themes/night.scss
  app/assets/stylesheets/themes/pink.scss
  app/javascript/articles/components/SaveButton.jsx
  app/javascript/crayons/Button/__stories__/Button.stories.jsx
  app/javascript/crayons/Button/__stories__/button.html.stories.jsx
  app/views/articles/_actions.html.erb
  app/views/articles/_v2_form.html.erb
  app/views/dashboards/_dashboard_article_row.html.erb
  app/views/pages/crayons.html.erb
Labels: PR: partially-approved

#9643 Update "/internal/badges" route to "/internal/badge_achievements"
  app/controllers/internal/badges_controller.rb
  config/routes.rb
  spec/requests/internal/badges_spec.rb
  spec/system/internal/admin_awards_badges_spec.rb
Labels: PR: partially-approved

#9641 Cleanup preferred_languages language_settings for users
  app/models/user.rb
  app/views/users/_language_settings.html.erb
  lib/data_update_scripts/20200805171911_clean_up_language_settings.rb
  spec/models/user_spec.rb
Labels: PR: partially-approved

#9653 Add initial language doc page
  docs/design/language.md
  docs/design/readme.md
Labels: PR: unreviewed

#9615 Update Users, Follows, Identities, and Reaction Pks to Bigints
  db/migrate/20200803193841_update_user_follow_identity_reaction_pks_to_bigints.rb
  db/schema.rb
Labels: PR: partially-approved

#9253 refactor chat_channel model - adjust for 20 methods bellow
  app/controllers/chat_channels_controller.rb
  app/controllers/internal/chat_channels_controller.rb
  app/labor/assign_tag_moderator.rb
  app/models/chat_channel.rb
  app/models/organization_membership.rb
  app/services/chat_channel_creation_service.rb
  app/services/chat_channel_update_service.rb
  app/services/chat_channels/create_with_users.rb
  app/services/chat_channels/find_or_create.rb
  app/workers/follows/create_chat_channel_worker.rb
  spec/mailers/notify_mailer_spec.rb
  spec/models/chat_channel_spec.rb
  spec/requests/chat_channels_spec.rb
  spec/requests/internal/users_manage_spec.rb
  spec/requests/video_chats_spec.rb
  spec/services/chat_channels/create_with_users_spec.rb
  spec/services/chat_channels/find_or_create_spec.rb
  spec/services/users/cleanup_chat_channels_spec.rb
  spec/services/users/delete_spec.rb
  spec/workers/moderator/banish_user_worker_spec.rb
Labels: PR: partially-approved

#9651 Hypershield: use per column table hide for specificity
  config/initializers/hypershield.rb
Labels: PR: reviewed-approved

#9661 Fix Footer Page render for unauthorised users
  app/views/devise/registrations/_registration_form.html.erb
Labels: PR: reviewed-approved

#9663 Upgrade erb_lint to support latest Rubocop and fix violations
  Gemfile.lock
  app/views/articles/tags/_meta.html.erb
  app/views/dashboards/_actions.html.erb
  app/views/dashboards/show.html.erb
  app/views/devise/passwords/edit.html.erb
  app/views/devise/passwords/new.html.erb
  app/views/doorkeeper/applications/_form.html.erb
  app/views/doorkeeper/authorizations/new.html.erb
  app/views/internal/configs/show.html.erb
  app/views/internal/feedback_messages/index.html.erb
  app/views/internal/moderator_actions/index.html.erb
  app/views/internal/users/_credits.erb
  app/views/internal/users/_notes.erb
  app/views/kaminari/internal/_page.html.erb
  app/views/listings/index.html.erb
  app/views/mailers/notify_mailer/account_deletion_requested_email.text.erb
  app/views/mailers/notify_mailer/channel_invite_email.text.erb
  app/views/mailers/notify_mailer/feedback_message_resolution_email.text.erb
  app/views/mailers/notify_mailer/tag_moderator_confirmation_email.text.erb
  app/views/notifications/_broadcast.html.erb
  app/views/onboardings/show.html.erb
  app/views/shared/authentication/_providers_registration_form.html.erb
  app/views/shared/authentication/_providers_signup_modal.html.erb
  vendor/cache/erb_lint-0.0.34.gem
  vendor/cache/erb_lint-0.0.35.gem
  vendor/cache/rubocop-ast-0.2.0.gem
  vendor/cache/rubocop-ast-0.3.0.gem
Labels: PR: partially-approved

#9664 Base Documentation for Forem Site Configuration
  docs/creators/configure-forem.md
  docs/creators/readme.md
  docs/readme.md
Labels: PR: partially-approved

#9665 Added a link to a visual guide to Webpacker in the Webpacker documentation
  docs/frontend/webpacker.md
Labels: PR: partially-approved

#9652 Implement ImageResizer module
  app/labor/profile_image.rb
  app/lib/image_resizer.rb
  app/models/html_variant.rb
  app/models/message.rb
  app/models/podcast_episode.rb
  app/view_objects/articles/social_image.rb
  app/view_objects/cloud_cover_url.rb
  spec/helpers/social_image_helper_spec.rb
  spec/labor/profile_image_spec.rb
  spec/models/html_variant_spec.rb
  spec/models/message_spec.rb
  spec/models/podcast_episode_spec.rb
  spec/view_objects/cloud_cover_url_spec.rb
Labels: PR: reviewed-approved

#9666 Updated docs.dev.to to docs.forem.com in documentation
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  app/javascript/crayons/guidelines/__stories__/components.md
  config/routes.rb
Labels: PR: partially-approved

#9668 dev.docs spec fix
  spec/requests/pages_spec.rb
Labels: PR: partially-approved

#9669 Update left over internal_user_path ref
  app/views/admin/users/_credits.erb
Labels: PR: unreviewed

#9672 Change /internal/ to /admin/ in vcl param safelist
  config/fastly/snippets/safe_params_list.vcl
Labels: PR: partially-approved

#9667 Make read next area work for smaller communities
  app/labor/article_suggester.rb
Labels: PR: partially-approved

#9662 Rubocop: Fix Rails/HasManyOrHasOneDependent for Broadcast and Collection
  .rubocop_todo.yml
  app/models/broadcast.rb
  app/models/collection.rb
  spec/models/broadcast_spec.rb
  spec/models/collection_spec.rb
Labels: PR: partially-approved

#9675 Remove DEV-only badge link
  app/views/users/_profile.html.erb
Labels: PR: unreviewed

#9649 Profile Admin UI Setup Screen Refactor (v1.5)
  app/controllers/admin/profile_fields_controller.rb
  app/models/profile_field.rb
  app/views/admin/profile_fields/_form.html.erb
  app/views/admin/profile_fields/index.html.erb
  config/blazer.yml
  spec/rails_helper.rb
  spec/requests/admin/chat_channel_spec.rb
  spec/requests/admin/profile_fields_spec.rb
Labels: PR: unreviewed

#9678 Remove Forward Slashes from <br> Tags in Pages Partial
  app/views/admin/pages/_form.html.erb
Labels: PR: partially-approved

#9681 Add new support admin role
  app/models/role.rb
  app/policies/application_policy.rb
  app/views/admin/users/edit.html.erb
  spec/models/role_spec.rb
Labels: PR: unreviewed

#9682 Migrate serialization to jsonapi/serializer
  Gemfile
  Gemfile.lock
  app/serializers/application_serializer.rb
  app/serializers/search/article_serializer.rb
  app/serializers/search/chat_channel_membership_serializer.rb
  app/serializers/search/comment_serializer.rb
  app/serializers/search/listing_author_serializer.rb
  app/serializers/search/listing_serializer.rb
  app/serializers/search/nested_user_serializer.rb
  app/serializers/search/podcast_episode_serializer.rb
  app/serializers/search/reaction_serializer.rb
  app/serializers/search/tag_serializer.rb
  app/serializers/search/user_serializer.rb
  app/serializers/webhook/article_destroyed_serializer.rb
  app/serializers/webhook/article_serializer.rb
  app/serializers/webhook/event_serializer.rb
  app/serializers/webhook/user_serializer.rb
  vendor/cache/fast_jsonapi-1.5.gem
  vendor/cache/jsonapi-serializer-2.0.0.gem
Labels: PR: reviewed-approved

#9680 Migration Optimization: Async Handle Notifications for Comments When Saved
  app/controllers/comments_controller.rb
  app/models/article.rb
  app/models/comment.rb
  app/models/notification.rb
  app/workers/comments/create_notification_subscription_worker.rb
  app/workers/comments/send_new_comment_notifications_worker.rb
  app/workers/comments/update_commentable_last_comment_at_worker.rb
  spec/requests/comments_create_spec.rb
  spec/requests/comments_spec.rb
  spec/workers/comments/create_notification_subscription_worker_spec.rb
  spec/workers/comments/send_new_comment_notifications_worker_spec.rb
  spec/workers/comments/update_commentable_last_comment_at_worker_spec.rb
Labels: PR: partially-approved

#9476 Optimization: Change Large Table Primary Keys to Bigints
  db/migrate/20200806193438_large_table_primary_keys_to_bigints.rb
  db/schema.rb
  release-tasks.sh
Labels: PR: unreviewed

#9686 Revert "Migration Optimization: Async Handle Notifications for Comments When Saved"
  app/controllers/comments_controller.rb
  app/models/article.rb
  app/models/comment.rb
  app/models/notification.rb
  app/workers/comments/create_notification_subscription_worker.rb
  app/workers/comments/send_new_comment_notifications_worker.rb
  app/workers/comments/update_commentable_last_comment_at_worker.rb
  spec/requests/comments_create_spec.rb
  spec/requests/comments_spec.rb
  spec/workers/comments/create_notification_subscription_worker_spec.rb
  spec/workers/comments/send_new_comment_notifications_worker_spec.rb
  spec/workers/comments/update_commentable_last_comment_at_worker_spec.rb
Labels: PR: unreviewed

#9687 Optimization:Set Honeybadger send_data_at_exit to False
  config/initializers/honeybadger.rb
Labels: PR: unreviewed

#9705 Travis Optimization:Bundle from Bash File to Use Cache
  .travis.yml
  bin/ci-bundle
Labels: PR: partially-approved

#9708 Flaky Spec Fix:HTML Escape Special Characters in Assertion like Template
  spec/requests/dashboard_spec.rb
Labels: PR: partially-approved

#9709 Enable Rubocop 0.89 cops and fix Lint/ violations
  .rubocop.yml
  app/controllers/comments_controller.rb
  app/controllers/notifications_controller.rb
  app/controllers/video_chats_controller.rb
  app/liquid_tags/null_tag.rb
  app/services/moderator/banish_user.rb
  app/services/moderator/delete_user.rb
  app/services/moderator/merge_user.rb
  app/services/rate_limit_checker.rb
  app/services/search/query_builders/chat_channel_membership.rb
  app/services/search/query_builders/feed_content.rb
  app/services/search/query_builders/listing.rb
  app/services/search/query_builders/reaction.rb
  app/services/search/query_builders/user.rb
  config/environments/development.rb
  config/environments/production.rb
  config/initializers/carrierwave.rb
  config/initializers/docker.rb
  spec/helpers/social_image_helper_spec.rb
  spec/models/html_variant_spec.rb
  spec/requests/admin/chat_channel_spec.rb
  spec/requests/admin/configs_spec.rb
  spec/requests/admin/podcasts_spec.rb
  spec/requests/admin/profile_fields_spec.rb
  spec/requests/admin/users_spec.rb
  spec/view_objects/cloud_cover_url_spec.rb
Labels: PR: partially-approved

#9704 Bug Fix:Dont Set Active Channel if ChatChannel Does Not Exist
  app/controllers/chat_channels_controller.rb
  spec/requests/chat_channels_spec.rb
Labels: PR: partially-approved

#9711 Rubocop: Enable and fix Style/OptionalBooleanParameter cop
  .rubocop.yml
  app/controllers/follows_controller.rb
  app/helpers/comments_helper.rb
  app/models/notification.rb
  app/services/github/oauth_client.rb
  app/services/notifications/new_follower/send.rb
  app/services/podcasts/feed.rb
  app/services/rss_reader.rb
  app/services/search/client.rb
  app/services/twitter_client/client.rb
  app/views/comments/_comment_proper.html.erb
  app/workers/notifications/new_follower_worker.rb
  app/workers/users/delete_worker.rb
  lib/tasks/fetch.rake
  spec/requests/user/user_settings_spec.rb
  spec/services/notifications/new_follower/send_spec.rb
  spec/system/notifications/notifications_page_spec.rb
Labels: PR: partially-approved

#9717 Fix Netlify catch all redirections
  docs/netlify.toml
Labels: PR: partially-approved

#9718 Upgrade Chartkick to fix CVE-2020-16254 Vulnerability
  Gemfile.lock
  vendor/cache/chartkick-3.3.2.gem
  vendor/cache/chartkick-3.4.0.gem
Labels: PR: partially-approved

#9716 Redirect /internal to /admin
  .rubocop.yml
  config/routes.rb
Labels: PR: unreviewed

#9670 Update docs with details on where to install Elasticsearch
  docs/installation/mac.md
  docs/installation/windows.md
Labels: PR: unreviewed

#9671 Improve clean up of user language settings
  lib/data_update_scripts/20200805171911_clean_up_language_settings.rb
Labels: PR: reviewed-approved

#9722 Check for the meta payment pointer before loading author payment pointer
  app/assets/javascripts/initializers/initializePaymentPointers.js
Labels: PR: partially-approved

#9648 Add profile model
  Gemfile
  Gemfile.lock
  app/models/profile.rb
  app/models/profile_field.rb
  app/models/user.rb
  db/migrate/20200806052718_create_profiles.rb
  db/schema.rb
  spec/factories/profiles.rb
  spec/factories/users.rb
  spec/models/profile_spec.rb
  vendor/cache/store_attribute-0.5.3.gem
Labels: PR: unreviewed

#9736 Github's bug report template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: PR: partially-approved

#9710 Cleanup orphaned Ahoy rows in the DB
  lib/data_update_scripts/20200810083831_remove_orphaned_ahoy_rows.rb
Labels: PR: reviewed-approved

#9729 Refactoring constants reduce lines
  app/lib/constants.rb
  app/lib/constants/mastodon.rb
  app/lib/constants/site_config.rb
  app/models/user.rb
  app/views/admin/configs/show.html.erb
Labels: PR: partially-approved

#9739 Add proper defaults to user invites
  app/controllers/admin/invitations_controller.rb
Labels: PR: reviewed-approved

#9636 Add foreign keys to Ahoy models
  db/migrate/20200805100552_add_missing_foreign_keys_to_ahoy_models.rb
  db/migrate/20200805102249_validate_add_missing_foreign_keys_to_ahoy_models.rb
  db/schema.rb
  lib/data_update_scripts/20200729120730_remove_orphaned_ahoy_events.rb
Labels: PR: reviewed-approved

#9735 Create option for calculating score without external black box
  app/black_box/black_box.rb
  spec/black_box/black_box_spec.rb
Labels: PR: partially-approved

#9706 Optimization:Migrate Final Small Table PKs to Bigints
  db/migrate/20200809200631_final_bigint_migration.rb
  db/schema.rb
Labels: PR: partially-approved

#9745 Ignore Flaky Blackbox Spec
  spec/black_box/black_box_spec.rb
Labels: PR: partially-approved

#9633 Auto-generate CSS utility classes documentation in Storybook
  .gitignore
  .vscode/launch.json
  bin/__tests__/generate-css-utility-classes-docs.test.js
  bin/generate-css-utility-classes-docs.js
  jest.config.js
  package.json
Labels: PR: partially-approved, area: developer experience, tech: html/css

#9744 v1 of adding the groups to the profile fields admin interface
  app/controllers/admin/profile_fields_controller.rb
  app/views/admin/profile_fields/_form.html.erb
  app/views/admin/profile_fields/index.html.erb
  spec/factories/profile_fields.rb
  spec/requests/admin/profile_fields_spec.rb
Labels: PR: partially-approved

#9621 Refactor:Remove ENVied Gem, Use dotenv Instead for Test and Development
  .gitignore
  .gitpod.yml
  .travis.yml
  Envfile
  Gemfile
  Gemfile.lock
  app/views/admin/configs/show.html.erb
  bin/setup
  config/.env_sample
  config/application.rb
  config/environments/production.rb
  config/initializers/0_application_config.rb
  config/initializers/aws_sdk.rb
  config/initializers/carrierwave.rb
  config/initializers/pusher.rb
  config/initializers/slack_notifier.rb
  config/sample_application.yml
  docs/backend/configuration.md
  docs/faqs.md
  docs/getting-started/config-env.md
  docs/installation/containers.md
  docs/installation/linux.md
  docs/installation/mac.md
  docs/installation/postgresql.md
  docs/installation/vault.md
  docs/installation/windows.md
  docs/troubleshooting.md
  lib/tasks/temporary/env_variables.rake
  spec/initializers/application_config_spec.rb
  vendor/cache/dotenv-2.7.6.gem
  vendor/cache/dotenv-rails-2.7.6.gem
  vendor/cache/envied-0.9.3.gem
Labels: PR: partially-approved

#9753 Update Netlify config to handle stylesheet changes for Storybook
  app/javascript/netlify.toml
Labels: PR: partially-approved

#9757 Revert "[deploy] Refactor:Remove ENVied Gem, Use dotenv Instead for T…
  .gitignore
  .gitpod.yml
  .travis.yml
  Envfile
  Gemfile
  Gemfile.lock
  app/views/admin/configs/show.html.erb
  bin/setup
  config/.env_sample
  config/application.rb
  config/environments/production.rb
  config/initializers/0_application_config.rb
  config/initializers/aws_sdk.rb
  config/initializers/carrierwave.rb
  config/initializers/pusher.rb
  config/initializers/slack_notifier.rb
  config/sample_application.yml
  docs/backend/configuration.md
  docs/faqs.md
  docs/getting-started/config-env.md
  docs/installation/containers.md
  docs/installation/linux.md
  docs/installation/mac.md
  docs/installation/postgresql.md
  docs/installation/vault.md
  docs/installation/windows.md
  docs/troubleshooting.md
  lib/tasks/temporary/env_variables.rake
  spec/initializers/application_config_spec.rb
  vendor/cache/dotenv-2.7.6.gem
  vendor/cache/dotenv-rails-2.7.6.gem
  vendor/cache/envied-0.9.3.gem
Labels: PR: partially-approved

#9760 Update repository links in PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: PR: partially-approved

#9764 Upgrade Node JS to latest 12.18 LTS to fix container setup
  .nvmrc
  package.json
Labels: PR: partially-approved, area: containers

#9628 [Moderation] Allow admins to delete comments
  app/controllers/comments_controller.rb
  app/javascript/packs/commentModPage.js
  app/policies/comment_policy.rb
  app/views/articles/show.html.erb
  app/views/moderations/mod.html.erb
  config/routes.rb
  spec/policies/comment_policy_spec.rb
Labels: PR: partially-approved

#9752 Account deletion email: serialize only user's details
  app/mailers/notify_mailer.rb
  app/workers/users/delete_worker.rb
  spec/mailers/notify_mailer_spec.rb
  spec/mailers/previews/notify_mailer_preview.rb
  spec/workers/users/delete_worker_spec.rb
Labels: PR: partially-approved

#9768 Remove flash message from article show page
  app/views/articles/show.html.erb
Labels: PR: partially-approved

#9772 Use .errors_as_sentece in Admin::Badges::Controller
  app/controllers/admin/badges_controller.rb
Labels: PR: partially-approved

#9771 Generalize liquid tag docs
  app/views/pages/_editor_guide_text.html.erb
  app/views/pages/_editor_liquid_help.html.erb
Labels: PR: partially-approved

#9655 Add X-Accel-Expires header to support Nginx caching
  app/controllers/concerns/caching_headers.rb
  spec/requests/api/v0/listings_spec.rb
  spec/requests/articles/articles_spec.rb
  spec/requests/reactions_spec.rb
  spec/requests/stories_index_spec.rb
Labels: PR: partially-approved

#9778 Comment out flaky Blackbox Spec
  spec/black_box/black_box_spec.rb
Labels: PR: reviewed-approved

#9391 Fix broken urls with IDNs in Cloudinary helper
  Gemfile
  Gemfile.lock
  app/helpers/application_helper.rb
  spec/helpers/application_helper_spec.rb
  vendor/cache/simpleidn-0.1.1.gem
Labels: PR: partially-approved

#9765 Remove orphaned DisplayAdEvent rows
  app/models/display_ad.rb
  lib/data_update_scripts/20200813072205_remove_orphaned_display_ad_events.rb
  spec/models/display_ad_spec.rb
Labels: PR: partially-approved

#9720 Migrate ImageResizer to Images::Optimizer
  app/helpers/application_helper.rb
  app/labor/generated_image.rb
  app/labor/markdown_parser.rb
  app/labor/profile_image.rb
  app/lib/image_resizer.rb
  app/liquid_tags/podcast_tag.rb
  app/models/html_variant.rb
  app/models/message.rb
  app/models/podcast_episode.rb
  app/services/images/optimizer.rb
  app/view_objects/articles/social_image.rb
  app/view_objects/cloud_cover_url.rb
  app/views/comments/_comment_proper.html.erb
  app/views/comments/deleted_commentable_comment.html.erb
  app/views/dashboards/show.html.erb
  app/views/podcast_episodes/_liquid.html.erb
  app/views/podcast_episodes/_sidebar.html.erb
  app/views/podcast_episodes/index.html.erb
  app/views/podcast_episodes/show.html.erb
  spec/helpers/application_helper_spec.rb
  spec/labor/generated_image_spec.rb
  spec/services/images/optimizer_spec.rb
Labels: PR: partially-approved

#9762 Update styling of authentication feed card for logged out users
  app/assets/stylesheets/articles.scss
  app/assets/stylesheets/signin.scss
  app/views/stories/_sign_in_invitation.html.erb
  spec/system/articles/user_visits_articles_by_timeframe_spec.rb
Labels: Forem team, PR: partially-approved, PR: unreviewed, area: auth, tech: html/css

#9767 Remove ENVied Gem, Use dotenv Take 2
  .gitignore
  .gitpod.yml
  .travis.yml
  Envfile
  Gemfile
  Gemfile.lock
  app/views/admin/configs/show.html.erb
  bin/setup
  config/.env_sample
  config/application.rb
  config/environments/production.rb
  config/initializers/0_application_config.rb
  config/initializers/aws_sdk.rb
  config/initializers/carrierwave.rb
  config/initializers/pusher.rb
  config/initializers/slack_notifier.rb
  config/sample_application.yml
  docs/backend/configuration.md
  docs/faqs.md
  docs/getting-started/config-env.md
  docs/installation/containers.md
  docs/installation/linux.md
  docs/installation/mac.md
  docs/installation/postgresql.md
  docs/installation/vault.md
  docs/installation/windows.md
  docs/troubleshooting.md
  lib/tasks/temporary/env_variables.rake
  spec/initializers/application_config_spec.rb
  vendor/cache/dotenv-2.7.6.gem
  vendor/cache/dotenv-rails-2.7.6.gem
  vendor/cache/envied-0.9.3.gem
Labels: PR: partially-approved

#9789 Feature:Use Sidekiq to Run Scheduled Jobs
  Gemfile
  Gemfile.lock
  config/initializers/sidekiq.rb
  config/routes.rb
  config/schedule.yml
  vendor/cache/et-orbi-1.2.4.gem
  vendor/cache/fugit-1.3.8.gem
  vendor/cache/raabro-1.3.1.gem
  vendor/cache/sidekiq-cron-1.2.0.gem
Labels: PR: partially-approved

#9791 Add missing `.call`
  app/views/comments/_comment_proper.html.erb
Labels: PR: reviewed-approved

#9805 Add missing .dataset for comment mod page
  app/javascript/packs/commentModPage.js
Labels: PR: unreviewed

#9806 Add error handling for comment mod page reactions
  app/javascript/packs/commentModPage.js
Labels: PR: unreviewed

#9724 Start using profile model
  app/models/profile_field.rb
  app/services/profile_fields/add_link_fields.rb
  db/migrate/20200811044202_add_attribute_name_to_profile_field.rb
  db/schema.rb
  lib/data/coding_profile_fields.csv
  lib/data/dev_profile_fields.csv
  lib/tasks/temporary/create_profile_fields.rake
  spec/models/profile_field_spec.rb
Labels: PR: reviewed-approved, action: post deployment

#9766 Bump storybook to version 6
  app/javascript/.storybook/main.js
  app/javascript/.storybook/preview.js
  app/javascript/CommentSubscription/__stories__/CommentSubscription.stories.jsx
  app/javascript/articles/__stories__/Article.stories.jsx
  app/javascript/articles/__stories__/podcastArticle.stories.jsx
  app/javascript/articles/__stories__/userArticle.stories.jsx
  app/javascript/articles/__stories__/videoArticles.stories.jsx
  app/javascript/crayons/Button/__stories__/Button.stories.jsx
  app/javascript/crayons/Dropdown/__stories__/Dropdown.stories.jsx
  app/javascript/crayons/Modal/__stories__/Modal.stories.jsx
  app/javascript/crayons/formElements/RadioButton/__stories__/RadioButton.stories.jsx
  package.json
  yarn.lock
Labels: PR: partially-approved

#9795 Add button to clear the whiteboard
  public/offline.html
Labels: PR: reviewed-approved

#9808 Changing Preact version to 10.x in docs
  docs/frontend/debugging.md
Labels: PR: partially-approved

#9803 Fixing broken link to dynamic imports in docs
  docs/technical-overview/architecture.md
Labels: PR: partially-approved

#9802 Changing rails version to 6.0.3 in docs
  README.md
  docs/backend/resource-admin.md
  docs/technical-overview/architecture.md
Labels: PR: reviewed-approved

#9790 Add "autofocus" and "required" attributes to the email field
  app/views/devise/passwords/new.html.erb
Labels: PR: reviewed-approved

#9786 Add missing foreign keys to DisplayAdEvent
  db/migrate/20200814142425_add_missing_foreign_keys_to_display_ad_events.rb
  db/migrate/20200814142648_validate_add_missing_foreign_keys_to_display_ad_events.rb
  db/schema.rb
Labels: PR: partially-approved

#9797 Bug Fix:Increase look back time for Cron jobs to 120 seconds
  config/initializers/sidekiq.rb
Labels: PR: unreviewed

#9794 Feature:Move Metric Rake Tasks to Sidekiq Cron
  config/schedule.yml
  lib/tasks/metrics.rake
Labels: PR: unreviewed

#9825 Add PUBLIC_CONTROLLERS constant
  app/controllers/application_controller.rb
Labels: PR: partially-approved

#9831 Refactor:Remove User Roles From Elasticsearch Returned Data
  app/services/search/user.rb
Labels: PR: partially-approved

#9832 Documenation: Update API Article Update Rate Limit Value to 30
  app/helpers/rate_limit_checker_helper.rb
  docs/api_v0.yml
Labels: PR: partially-approved

#9833 Flaky Spec Fix:Ensure We Find Articles With Tags and Dont Cache Count for Class Method
  app/labor/article_suggester.rb
  spec/labor/article_suggester_spec.rb
Labels: PR: partially-approved

#9838 Add Logging Statements to Debug Hypershield Refresh Not Working on Heroku
  lib/tasks/app_initializer.rake
Labels: PR: reviewed-approved

#9835 Comments out the USER directive due to issues with podman-compose.
  Containerfile
Labels: PR: reviewed-approved

#9837 Social Auth generalization refactor
  app/controllers/omniauth_callbacks_controller.rb
  app/helpers/authentication_helper.rb
  app/models/user.rb
  app/services/authentication/authenticator.rb
  app/services/authentication/providers.rb
  app/services/authentication/providers/github.rb
  app/services/authentication/providers/provider.rb
  app/services/authentication/providers/twitter.rb
  app/services/broadcasts/welcome_notification/generator.rb
  app/services/users/estimate_default_language.rb
  app/views/users/_account.html.erb
  app/views/users/_account_providers_settings.html.erb
  spec/models/identity_spec.rb
  spec/models/user_spec.rb
  spec/system/authentication/user_logs_in_with_github_spec.rb
  spec/system/authentication/user_logs_in_with_twitter_spec.rb
  spec/system/homepage/user_visits_homepage_spec.rb
  spec/system/link_for_tags_in_posts_in_notifications_spec.rb
Labels: PR: partially-approved

#9829 API: add created_at datetime to comments
  app/controllers/api/v0/comments_controller.rb
  app/views/api/v0/comments/_comment.json.jbuilder
  docs/api_v0.yml
  spec/requests/api/v0/comments_spec.rb
Labels: PR: partially-approved

#9836 Refactor:Move Yearly Badge Awarder to Sidekiq Cron
  app/labor/badge_rewarder.rb
  app/workers/badge_achievements/badge_award_worker.rb
  config/schedule.yml
  lib/tasks/badges.rake
  spec/labor/badge_rewarder_spec.rb
  spec/workers/badge_achievements/badge_award_worker_spec.rb
Labels: PR: partially-approved

#9839 Revert "Add Logging Statements to Debug Hypershield Refresh Not Working on Heroku"
  lib/tasks/app_initializer.rake
Labels: PR: reviewed-approved

#9777 Create details liquid tag
  app/liquid_tags/details_tag.rb
  app/views/liquids/_details.html.erb
  app/views/pages/_editor_guide_text.html.erb
  app/views/pages/_editor_liquid_help.html.erb
  spec/liquid_tags/details_tag_spec.rb
  spec/support/fixtures/approvals/details_liquid_tag_spec.approved.html
Labels: PR: partially-approved

#9792 Add "required" attribute to the login form
  app/views/devise/registrations/_registration_form.html.erb
Labels: PR: reviewed-approved

#9796 Populate options from javascript instead of hardcoding
  public/offline.html
Labels: PR: partially-approved

#9844 Rubocop: Enable and fix Style/StringConcatenation
  .rubocop.yml
  app/controllers/admin/welcome_controller.rb
  app/controllers/articles_controller.rb
  app/controllers/video_chats_controller.rb
  app/controllers/videos_controller.rb
  app/helpers/application_helper.rb
  app/labor/bufferizer.rb
  app/labor/cache_buster.rb
  app/labor/language_detector.rb
  app/labor/markdown_parser.rb
  app/liquid_tags/github_tag/github_readme_tag.rb
  app/liquid_tags/kotlin_tag.rb
  app/models/article.rb
  app/models/chat_channel.rb
  app/models/chat_channel_membership.rb
  app/models/message.rb
  app/models/tweet.rb
  app/models/user.rb
  app/services/chat_channels/create_with_users.rb
  app/services/users/profile_image_generator.rb
  config/initializers/sprockets_uglifier_with_source_maps_compressor.rb
  spec/labor/bufferizer_spec.rb
  spec/labor/markdown_parser_spec.rb
  spec/liquid_tags/glitch_tag_spec.rb
  spec/liquid_tags/link_tag_spec.rb
  spec/liquid_tags/next_tech_tag_spec.rb
  spec/liquid_tags/podcast_tag_spec.rb
  spec/liquid_tags/youtube_tag_spec.rb
  spec/models/article_spec.rb
  spec/requests/api/v0/articles_spec.rb
  spec/requests/articles/articles_show_spec.rb
  spec/requests/comments_destroy_spec.rb
  spec/requests/moderations_spec.rb
  spec/requests/stories_index_spec.rb
  spec/requests/user/user_organization_spec.rb
  spec/requests/user/user_show_spec.rb
  spec/services/chat_channels/find_or_create_spec.rb
  spec/system/comments/user_delete_a_comment_spec.rb
  spec/system/dashboards/user_scrolls_down_dashboard_follows_spec.rb
  spec/workers/articles/bust_multiple_caches_worker_spec.rb
Labels: PR: partially-approved

#9845 Nullify article_id for HtmlVariantTrials linked to non existing articles
  lib/data_update_scripts/20200818103028_nullify_orphaned_by_article_html_variant_trials.rb
Labels: PR: reviewed-approved

#9804 🐞Bug Fix: Room that has been left still shows up in URL [Fixes: #9501]
  app/helpers/chat_channel_memberships_helper.rb
  app/javascript/chat/ChatChannelSettings/ChatChannelSettings.jsx
  app/javascript/chat/RequestManager/PersonalInvitationListItem.jsx
  app/javascript/chat/chat.jsx
  app/javascript/chat/content.jsx
Labels: PR: partially-approved

#9842 Rubocop: Enable and fix Style/SingleArgumentDig
  .rubocop.yml
  app/controllers/api/v0/articles_controller.rb
  app/controllers/image_uploads_controller.rb
  app/services/search/base.rb
  app/services/search/feed_content.rb
  app/services/search/tag.rb
  app/services/search/user.rb
  spec/serializers/search/reaction_serializer_spec.rb
  spec/services/search/chat_channel_membership_spec.rb
  spec/services/search/feed_content_spec.rb
  spec/services/search/listing_spec.rb
  spec/services/search/query_builders/chat_channel_membership_spec.rb
  spec/services/search/query_builders/feed_content_spec.rb
  spec/services/search/query_builders/listing_spec.rb
  spec/services/search/query_builders/reaction_spec.rb
  spec/services/search/query_builders/user_spec.rb
  spec/services/search/reaction_spec.rb
  spec/services/search/user_spec.rb
Labels: PR: partially-approved

#9846 Add relations and foreign keys between HtmlVariant related models
  .rubocop_todo.yml
  app/models/article.rb
  app/models/html_variant.rb
  app/models/html_variant_success.rb
  app/models/html_variant_trial.rb
  app/models/user.rb
  db/migrate/20200818101637_add_missing_foreign_keys_to_html_variants_models.rb
  db/migrate/20200818101700_validate_add_missing_foreign_keys_to_html_variants_models.rb
  db/schema.rb
  spec/models/article_spec.rb
  spec/models/html_variant_spec.rb
  spec/models/user_spec.rb
Labels: PR: partially-approved

#9827 Style logged-out authentication modal
  app/assets/javascripts/utilities/showModal.js
  app/assets/stylesheets/signin.scss
  app/assets/stylesheets/signup-modal.scss
  app/views/layouts/_signup_modal.html.erb
  app/views/stories/_sign_in_invitation.html.erb
Labels: PR: partially-approved, area: auth, tech: html/css

#9793 Reduce arguments method buff! at model buffer_update
  app/labor/bufferizer.rb
  app/models/buffer_update.rb
  spec/models/buffer_update_spec.rb
  spec/services/users/delete_articles_spec.rb
Labels: PR: partially-approved

#9769 Add Options to "Invalidate" and "Mark as Valid" Vomit Reactions
  app/javascript/admin/controllers/reaction_controller.js
  app/views/admin/feedback_messages/_abuse_reports.html.erb
Labels: PR: partially-approved

#9858 Bug Fix:Execute Hypershield Refresh Task
  lib/tasks/app_initializer.rake
Labels: PR: reviewed-approved

#9851 Apply fixes for axe issues in admin interfaces
  app/views/admin/articles/index.html.erb
  app/views/admin/badges/award.html.erb
  app/views/admin/badges/edit.html.erb
  app/views/admin/badges/index.html.erb
  app/views/admin/badges/new.html.erb
  app/views/admin/broadcasts/_form.html.erb
  app/views/admin/broadcasts/edit.html.erb
  app/views/admin/broadcasts/index.html.erb
  app/views/admin/broadcasts/new.html.erb
  app/views/admin/broadcasts/show.html.erb
  app/views/layouts/admin.html.erb
Labels: PR: partially-approved

#9860 Warning Fix: Rename Unused application.yml File to Prevent Warnings
  .gitignore
  bin/setup
Labels: PR: reviewed-approved

#9801 🐞Bug Fix: Chat doesn't extend to its frame on Firefox iOS [ Fixes #4024 ]
  app/assets/stylesheets/chat.scss
  app/javascript/chat/chat.jsx
  app/views/chat_channels/index.html.erb
Labels: PR: partially-approved

#9834 Create optimized_image_tag helper
  app/helpers/application_helper.rb
  app/liquid_tags/podcast_tag.rb
  app/views/articles/_bottom_content.html.erb
  app/views/podcast_episodes/_episodes_feed.html.erb
  app/views/podcast_episodes/_liquid.html.erb
  app/views/podcast_episodes/_podcast_bar.html.erb
  app/views/podcast_episodes/show.html.erb
  spec/helpers/application_helper_spec.rb
Labels: PR: reviewed-approved

#9861 Refactor: Move beloved comment Badge to Sidekiq Cron
  app/labor/badge_rewarder.rb
  config/schedule.yml
  lib/tasks/badges.rake
Labels: PR: partially-approved

#9865 Update suggested tweet copy on manage page
  app/views/articles/manage.html.erb
Labels: PR: partially-approved

#9866 Check for heroku url presence before working with it
  config/environments/production.rb
Labels: PR: partially-approved

#9863 Move community_copyright_start_year to SiteConfig
  app/controllers/admin/configs_controller.rb
  app/helpers/application_helper.rb
  app/labor/badge_rewarder.rb
  app/lib/constants/site_config.rb
  app/models/site_config.rb
  app/views/admin/configs/show.html.erb
  config/.env_sample
  config/sample_application.yml
  spec/helpers/application_helper_spec.rb
  spec/labor/badge_rewarder_spec.rb
  spec/requests/admin/configs_spec.rb
Labels: PR: partially-approved

#9868 Move .env_sample out of /config directory
  .env_sample
  .gitpod.yml
  .travis.yml
  docs/getting-started/config-env.md
  docs/installation/containers.md
  docs/installation/linux.md
  docs/installation/mac.md
  docs/installation/windows.md
Labels: PR: partially-approved

#9853 Rubocop: Fix ListingCategory has_many relation to Listing
  .rubocop_todo.yml
  app/models/listing_category.rb
  spec/models/listing_category_spec.rb
Labels: PR: unreviewed

#9869 Allow staff_user_id to be modified
  app/controllers/admin/configs_controller.rb
  app/lib/constants/site_config.rb
  app/models/site_config.rb
  app/views/admin/configs/show.html.erb
  spec/requests/admin/configs_spec.rb
Labels: PR: reviewed-approved

#9867 Use ApplicationController for liquid render
  app/liquid_tags/asciinema_tag.rb
  app/liquid_tags/blogcast_tag.rb
  app/liquid_tags/codepen_tag.rb
  app/liquid_tags/codesandbox_tag.rb
  app/liquid_tags/comment_tag.rb
  app/liquid_tags/details_tag.rb
  app/liquid_tags/gist_tag.rb
  app/liquid_tags/git_pitch_tag.rb
  app/liquid_tags/github_tag/github_issue_tag.rb
  app/liquid_tags/github_tag/github_readme_tag.rb
  app/liquid_tags/glitch_tag.rb
  app/liquid_tags/instagram_tag.rb
  app/liquid_tags/js_fiddle_tag.rb
  app/liquid_tags/jsitor_tag.rb
  app/liquid_tags/katex_tag.rb
  app/liquid_tags/kotlin_tag.rb
  app/liquid_tags/link_tag.rb
  app/liquid_tags/listing_tag.rb
  app/liquid_tags/medium_tag.rb
  app/liquid_tags/next_tech_tag.rb
  app/liquid_tags/organization_tag.rb
  app/liquid_tags/parler_tag.rb
  app/liquid_tags/poll_tag.rb
  app/liquid_tags/reddit_tag.rb
  app/liquid_tags/replit_tag.rb
  app/liquid_tags/runkit_tag.rb
  app/liquid_tags/slideshare_tag.rb
  app/liquid_tags/soundcloud_tag.rb
  app/liquid_tags/speakerdeck_tag.rb
  app/liquid_tags/spotify_tag.rb
  app/liquid_tags/stackblitz_tag.rb
  app/liquid_tags/stackery_tag.rb
  app/liquid_tags/stackexchange_tag.rb
  app/liquid_tags/tag_tag.rb
  app/liquid_tags/tweet_tag.rb
  app/liquid_tags/user_tag.rb
  app/liquid_tags/vimeo_tag.rb
  app/liquid_tags/wikipedia_tag.rb
  app/liquid_tags/youtube_tag.rb
  docs/frontend/liquid-tags.md
Labels: PR: reviewed-approved

#9872 Refactor:Move Streak Badges to Sidekiq Cron
  app/labor/badge_rewarder.rb
  config/schedule.yml
  lib/tasks/badges.rake
  spec/labor/badge_rewarder_spec.rb
Labels: PR: partially-approved

#9871 Fix axe warnings on admin/chat_channels
  app/views/admin/chat_channels/index.html.erb
Labels: PR: partially-approved

#9864 Add community_name to site config
  app/controllers/admin/configs_controller.rb
  app/controllers/admin/welcome_controller.rb
  app/controllers/concerns/verify_setup_completed.rb
  app/controllers/email_subscriptions_controller.rb
  app/controllers/stories_controller.rb
  app/controllers/users_controller.rb
  app/helpers/application_helper.rb
  app/helpers/feedback_messages_helper.rb
  app/labor/badge_rewarder.rb
  app/lib/constants/site_config.rb
  app/liquid_tags/reddit_tag.rb
  app/mailers/application_mailer.rb
  app/mailers/digest_mailer.rb
  app/mailers/notify_mailer.rb
  app/mailers/verification_mailer.rb
  app/models/site_config.rb
  app/views/admin/configs/show.html.erb
  app/views/html_variants/_form.html.erb
  app/views/moderations/_mod_sidebar_right.html.erb
  app/workers/follows/send_email_notification_worker.rb
  db/seeds.rb
  spec/helpers/application_helper_spec.rb
  spec/helpers/feedback_messages_helper_spec.rb
  spec/mailers/digest_mailer_spec.rb
  spec/mailers/notify_mailer_spec.rb
  spec/mailers/previews/notify_mailer_preview.rb
  spec/mailers/verification_mailer_spec.rb
  spec/requests/admin/configs_spec.rb
  spec/requests/admin/users_spec.rb
  spec/requests/articles/articles_show_spec.rb
  spec/requests/pages_spec.rb
  spec/requests/service_worker_spec.rb
  spec/requests/user/user_settings_spec.rb
  spec/system/authentication/user_logs_in_with_github_spec.rb
  spec/system/authentication/user_logs_in_with_twitter_spec.rb
  spec/system/organization/user_views_an_organization_spec.rb
  spec/system/user/view_user_index_spec.rb
  spec/views/email_subscriptions/unsubscribe.html.erb_spec.rb
Labels: PR: partially-approved

#9875 Bug Fix:Run Badge Award Job Twice a Day
  config/schedule.yml
Labels: PR: partially-approved

#9852 Remove unneeded Analytics update script
  app/controllers/admin/configs_controller.rb
  app/controllers/async_info_controller.rb
  app/controllers/dashboards_controller.rb
  app/lib/constants/site_config.rb
  app/models/site_config.rb
  app/services/articles/analytics_updater.rb
  app/views/admin/configs/show.html.erb
  app/workers/articles/update_analytics_worker.rb
  spec/requests/admin/configs_spec.rb
  spec/services/articles/analytics_updater_spec.rb
  spec/workers/articles/update_analytics_worker_spec.rb
Labels: PR: partially-approved

#9879 Optimization:Locally Cache any_admin? For User Instance
  app/models/user.rb
Labels: PR: partially-approved

#9878 Flaky Spec Fix:Use Comment created_at in Expectation
  spec/requests/api/v0/comments_spec.rb
Labels: PR: partially-approved

#9882 Optimization:Collect More Specific Data From Sidekiq Jobs
  lib/sidekiq/honeycomb_middleware.rb
  lib/sidekiq/worker_retries_exhausted_reporter.rb
  spec/lib/sidekiq/worker_retries_exhausted_reporter_spec.rb
Labels: PR: partially-approved

#9862 Set Stripe dynamically instead of at boot
  .env_sample
  app/controllers/admin/configs_controller.rb
  app/controllers/application_controller.rb
  app/controllers/credits_controller.rb
  app/controllers/stripe_active_cards_controller.rb
  app/controllers/users_controller.rb
  app/lib/constants/site_config.rb
  app/models/site_config.rb
  app/views/admin/configs/show.html.erb
  app/views/credits/new.html.erb
  app/views/users/_billing.html.erb
  config/initializers/stripe.rb
  spec/requests/admin/configs_spec.rb
Labels: PR: partially-approved

#9843 Automatically refresh profile accessors
  app/controllers/admin/profile_fields_controller.rb
  app/models/profile.rb
  app/services/profile_fields/add.rb
  app/services/profile_fields/remove.rb
  spec/models/profile_spec.rb
  spec/requests/admin/profile_fields_spec.rb
  spec/services/profile_fields/add_spec.rb
  spec/services/profile_fields/remove_spec.rb
Labels: PR: partially-approved

#9750 Migrate profile data
  app/models/profile.rb
  app/models/user.rb
  app/services/profiles/extract_data.rb
  config/environments/development.rb
  config/environments/test.rb
  db/migrate/20200813031851_add_unique_index_to_profiles.rb
  db/schema.rb
  lib/data_update_scripts/20200819025131_migrate_profile_data.rb
  lib/tasks/temporary/create_profile_fields.rake
  spec/factories/profiles.rb
  spec/factories/users.rb
  spec/lib/data_update_scripts/migrate_profile_data_spec.rb
  spec/models/profile_spec.rb
  spec/models/user_spec.rb
Labels: PR: unreviewed, action: post deployment

#9855 Remove orphaned polls related rows
  lib/data_update_scripts/20200818170410_remove_orphaned_poll_votes.rb
  lib/data_update_scripts/20200818170433_remove_orphaned_poll_skips.rb
  lib/data_update_scripts/20200818170505_remove_orphaned_poll_options.rb
  lib/data_update_scripts/20200818170523_remove_orphaned_polls.rb
Labels: PR: partially-approved

#9841 Listing endorsements: models setup
  app/models/listing.rb
  app/models/listing_endorsement.rb
  app/models/user.rb
  db/migrate/20200817205048_create_listing_endorsements.rb
  db/schema.rb
  db/seeds.rb
  spec/factories/listing_endorsements.rb
  spec/models/listing_endorsement_spec.rb
  spec/models/listing_spec.rb
  spec/models/user_spec.rb
Labels: PR: unreviewed

#9854 Add relations and foreign keys between Poll related models
  .rubocop_todo.yml
  app/models/article.rb
  app/models/poll.rb
  app/models/poll_option.rb
  db/migrate/20200818163445_add_missing_foreign_keys_to_poll_models.rb
  db/migrate/20200818163834_validate_add_missing_foreign_keys_to_poll_models.rb
  db/schema.rb
  spec/models/article_spec.rb
  spec/models/poll_option_spec.rb
  spec/models/poll_spec.rb
Labels: PR: reviewed-approved
