Repository forem/forem, pull requests merged in 2020-02, with the labels that each got.

#5777 Remove BustHomepageCacheJob and spec
  app/jobs/reactions/bust_homepage_cache_job.rb
  spec/jobs/reactions/bust_homepage_cache_job_spec.rb
Labels: PR: reviewed-approved

#5797 Track stripe errors in Datadog so we can alert on them
  app/controllers/stripe_active_cards_controller.rb
  spec/requests/stripe_active_cards_spec.rb
Labels: PR: reviewed-approved

#5762 Introduce Elasticsearch to DEV env
  Envfile
  Gemfile
  Gemfile.lock
  config/initializers/elasticsearch.rb
  docs/installation/linux.md
  docs/installation/mac.md
  docs/installation/windows.md
Labels: PR: reviewed-approved

#5780 One less place you need to bump the ruby version
  Gemfile
Labels: PR: reviewed-approved

#5373 User counters using PostgreSQL JSON
  app/models/user.rb
  app/models/user_counter.rb
  app/serializers/hash_serializer.rb
  db/migrate/20200106074859_create_user_counters.rb
  db/schema.rb
  lib/tasks/counters.rake
  spec/factories/user_counters.rb
  spec/models/user_counter_spec.rb
  spec/models/user_spec.rb
Labels: PR: reviewed-approved

#5863 Add missing sha512 to ES mac docs
  docs/installation/mac.md
Labels: PR: reviewed-approved

#5812 chore: add a core team member
  README.md
Labels: PR: reviewed-approved

#5834 Fix typo in ReactionObserver
  app/observers/reaction_observer.rb
Labels: PR: reviewed-approved

#5798 Fix/events show 404
  app/controllers/events_controller.rb
  spec/requests/events_spec.rb
Labels: PR: reviewed-approved

#5865 Replace the initial migration for strong_migrations gem
  config/initializers/strong_migrations.rb
Labels: PR: reviewed-approved

#5840 Add whitespace to internal users edit page
  app/views/internal/users/edit.html.erb
Labels: PR: reviewed-approved

#5867 Remove old Users::ResaveArticlesJob and spec
  app/jobs/users/resave_articles_job.rb
  spec/jobs/users/resave_articles_job_spec.rb
Labels: PR: reviewed-approved

#5868 Remove old Users::SubscribeToMailchimpNewsletterJob & spec
  app/jobs/users/subscribe_to_mailchimp_newsletter_job.rb
  spec/jobs/users/subscribe_to_mailchimp_newsletter_job_spec.rb
Labels: PR: reviewed-approved

#5869 Remove old BadgeAchievements::SendEmailNotificationJob & spec
  app/jobs/badge_achievements/send_email_notification_job.rb
  spec/jobs/badge_achievements/send_email_notification_job_spec.rb
Labels: PR: reviewed-approved

#5873 Render main image in article preview for v2 editor
  app/javascript/article-form/elements/__tests__/__snapshots__/bodyPreview.test.jsx.snap
  app/javascript/article-form/elements/__tests__/bodyPreview.test.jsx
  app/javascript/article-form/elements/bodyPreview.jsx
Labels: PR: reviewed-approved

#5823 Footer in `shecoded` rendered twice
  app/views/pages/shecoded.html.erb
Labels: PR: reviewed-approved

#5874 Some Proptypes cleanup
  app/javascript/sidebar-widget/sidebarUser.jsx
  app/javascript/src/components/common-prop-types/default-children-prop-types.js
  app/javascript/src/components/common-prop-types/index.js
  app/javascript/src/components/common-prop-types/user-prop-types.js
Labels: PR: reviewed-approved

#5871 Hookup Elasticsearch in Travis
  .travis.yml
  spec/initializers/elasticsearch_spec.rb
Labels: PR: reviewed-approved

#5866 Add signin=true as a param correctly if the URL already has params
  app/controllers/application_controller.rb
Labels: PR: reviewed-approved

#5822 Update contributor guide with new tag name
  CONTRIBUTING.md
Labels: PR: reviewed-approved

#5894 Add comment around previewing with v1 vs. v2 editors
  app/javascript/article-form/elements/bodyPreview.jsx
Labels: PR: reviewed-approved

#5880 Improve dropdown UX for internal/badges
  app/controllers/internal/badges_controller.rb
  app/controllers/internal/tools_controller.rb
  app/views/internal/badges/index.html.erb
  spec/requests/internal/badges_spec.rb
  spec/system/internal/admin_awards_badges_spec.rb
Labels: PR: reviewed-approved

#5870 Move Tags::BustCacheJob to Sidekiq
  app/models/tag.rb
  app/workers/tags/bust_cache_worker.rb
  spec/models/tag_spec.rb
  spec/workers/tags/bust_cache_worker_spec.rb
Labels: PR: reviewed-approved

#5841 Add documentation for ENVied & SiteConfig
  docs/backend/configuration.md
  docs/backend/readme.md
Labels: PR: reviewed-approved

#5875 Move Articles::ScoreCalcJob to Sidekiq
  app/models/article.rb
  app/workers/articles/score_calc_worker.rb
  spec/jobs/reactions/update_reactable_job_spec.rb
  spec/models/article_destroy_spec.rb
  spec/models/article_spec.rb
  spec/models/reaction_spec.rb
  spec/workers/articles/score_calc_worker_spec.rb
Labels: PR: reviewed-approved

#5879 Move HtmlVariantSuccessesCreate from background job to inline
  app/controllers/html_variant_successes_controller.rb
  app/jobs/html_variant_success_create_job.rb
  spec/jobs/html_variant_success_create_job_spec.rb
Labels: PR: reviewed-approved

#5888 Move Articles::DetectHumanLanguage from background job to inline
  app/jobs/articles/detect_human_language_job.rb
  app/models/article.rb
  spec/jobs/articles/detect_human_language_job_spec.rb
  spec/models/article_spec.rb
Labels: PR: reviewed-approved

#5662 Add readonly ApplicationConfig to /internal/config
  app/views/internal/configs/show.html.erb
Labels: PR: reviewed-approved

#5904 Remove quotes from broadcast options in internal form
  app/views/internal/broadcasts/_form.html.erb
Labels: PR: reviewed-approved

#5784 Remove direct chat channels when banishing user
  app/services/moderator/banish_user.rb
  app/services/users/cleanup_chat_channels.rb
  app/services/users/delete_articles.rb
  spec/requests/internal/users_banish_spec.rb
  spec/services/users/cleanup_chat_channels_spec.rb
  spec/services/users/delete_articles_spec.rb
Labels: PR: reviewed-approved

#5908 Allow broadcasts to be created from internal/broadcasts
  app/controllers/internal/broadcasts_controller.rb
  spec/requests/internal/broadcasts_spec.rb
Labels: PR: reviewed-approved

#5897 Remove Tags::BustCacheJob and spec
  app/jobs/tags/bust_cache_job.rb
  spec/jobs/tags/bust_cache_job_spec.rb
Labels: PR: reviewed-approved

#5898 Remove Articles::ScoreCalcJob and spec
  app/jobs/articles/score_calc_job.rb
  spec/jobs/articles/score_calc_job_spec.rb
Labels: PR: reviewed-approved

#5903 Remove Notifications::UpdateJob & spec
  app/jobs/notifications/update_job.rb
  spec/jobs/notifications/update_job_spec.rb
Labels: PR: reviewed-approved

#5905 Remove Notifications::ModerationNotificationJob & spec
  app/jobs/notifications/moderation_notification_job.rb
  spec/jobs/notifications/moderation_notification_job_spec.rb
Labels: PR: reviewed-approved

#5901 Move HtmlVariantTrialCreateJob from background job to inline
  app/controllers/html_variant_trials_controller.rb
Labels: PR: reviewed-approved

#5345 Migrate update main image background job to sidekiq
  app/models/article.rb
  app/workers/articles/update_main_image_background_hex_worker.rb
  spec/models/article_spec.rb
  spec/workers/articles/update_main_image_background_hex_worker_spec.rb
Labels: PR: reviewed-approved

#5893 Add user as reactable
  app/models/reaction.rb
  app/models/user.rb
Labels: PR: reviewed-approved

#5833 Use cleverer patterns to fetch/iterate AR objects when checking presence
  app/services/notifications/update.rb
  app/services/users/delete_articles.rb
  app/views/additional_content_boxes/boxes.html.erb
  app/views/articles/_sidebar.html.erb
  app/views/articles/_sidebar_additional.html.erb
  app/views/articles/tag_index.html.erb
  app/views/articles/tags/_sidebar_additional.html.erb
  app/views/internal/articles/index.html.erb
  app/views/internal/podcasts/edit.html.erb
  app/views/moderations/mod.html.erb
  app/views/organizations/_sidebar_additional.html.erb
  app/views/organizations/show.html.erb
  app/views/partnerships/_form.html.erb
  app/views/users/_comments_section.html.erb
  app/views/users/_main_feed.html.erb
  app/views/users/_organizations_area.html.erb
Labels: PR: reviewed-approved

#5887 Move user deletion by moderator to worker
  app/controllers/internal/users_controller.rb
  app/controllers/users_controller.rb
  app/services/moderator/delete_user.rb
  app/workers/users/delete_worker.rb
  spec/requests/internal/users_banish_spec.rb
  spec/requests/user/user_destroy_spec.rb
  spec/services/moderator/delete_user_spec.rb
  spec/system/user/user_self_destroy_spec.rb
  spec/workers/users/delete_worker_spec.rb
Labels: PR: reviewed-approved

#5806 Return NotFound error if ChatChannelMembership is not found
  app/controllers/chat_channel_memberships_controller.rb
  spec/requests/chat_channel_memberships_spec.rb
Labels: PR: reviewed-approved

#5826 Fix raising validation if followable already exist(race condition)
  app/controllers/follows_controller.rb
Labels: PR: reviewed-approved

#5912 Have counters:update_users use a transaction per user and customizable batch size
  lib/tasks/counters.rake
Labels: PR: reviewed-approved

#5913 Ignore `html_safe` in erb files
  .erb-lint.yml
Labels: PR: reviewed-approved

#5909 Move Notifications::TagAdjustmentNotificationJob to Sidekiq
  app/models/notification.rb
  app/workers/notifications/tag_adjustment_notification_worker.rb
  spec/services/notifications/tag_adjustment_notification/send_spec.rb
  spec/services/tag_adjustment_creation_service_spec.rb
  spec/workers/notifications/tag_adjustment_notification_worker_spec.rb
Labels: PR: reviewed-approved

#5910 Remove HtmlVariantTrialCreateJob & spec
  app/jobs/html_variant_trial_create_job.rb
  spec/jobs/html_variant_trial_create_job_spec.rb
Labels: PR: reviewed-approved

#5911 Remove Articles::UpdateMainImageBackgroundHexJob & spec
  app/jobs/articles/update_main_image_background_hex_job.rb
  spec/jobs/articles/update_main_image_background_hex_job_spec.rb
Labels: PR: reviewed-approved

#5915 Remove Notifications::TagAdjustmentNotificationJob & spec
  app/jobs/notifications/tag_adjustment_notification_job.rb
  spec/jobs/notifications/tag_adjustment_notification_job_spec.rb
Labels: PR: reviewed-approved

#5881 Adds core team member
  README.md
Labels: PR: reviewed-approved

#5821 Remove Foreman gem
  Gemfile
  Gemfile.lock
  docs/getting-started/start-app.md
  docs/installation/others.md
  docs/installation/readme.md
Labels: PR: reviewed-approved

#5889 Allow deleting comments if article has already been deleted
  app/controllers/comments_controller.rb
  spec/requests/comments_spec.rb
Labels: PR: reviewed-approved

#5884 Preact/React developer tools documentation.
  docs/frontend/debugging.md
Labels: PR: reviewed-approved

#5900 Created documenation for Common PropTypes.
  docs/frontend/preact.md
Labels: PR: reviewed-approved

#5842 Upgrade gemoji to support disability emojis
  Gemfile
  Gemfile.lock
  spec/labor/emoji_converter_spec.rb
  spec/labor/markdown_parser_spec.rb
Labels: PR: reviewed-approved, area: publishing experience

#5882 Added tag prop types to common prop types
  app/javascript/src/components/common-prop-types/index.js
  app/javascript/src/components/common-prop-types/tag-prop-types.js
Labels: PR: reviewed-approved

#5902 Removed isRequired for whole user entity as this is done in component…
  app/javascript/src/components/common-prop-types/user-prop-types.js
Labels: PR: reviewed-approved

#5891 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: PR: reviewed-approved

#5805 Improve API controllers efficiency by selecting only columns needed for serialization
  app/controllers/api/v0/articles_controller.rb
  app/controllers/api/v0/chat_channels_controller.rb
  app/controllers/api/v0/classified_listings_controller.rb
  app/controllers/api/v0/comments_controller.rb
  app/controllers/api/v0/followers_controller.rb
  app/controllers/api/v0/followings_controller.rb
  app/controllers/api/v0/github_repos_controller.rb
  app/controllers/api/v0/reactions_controller.rb
  app/controllers/api/v0/tags_controller.rb
  app/controllers/api/v0/users_controller.rb
  app/controllers/api/v0/webhooks_controller.rb
  app/models/chat_channel.rb
  app/services/article_api_index_service.rb
  app/services/suggester/users/recent.rb
  app/services/suggester/users/sidebar.rb
  app/views/api/v0/articles/_article.json.jbuilder
  app/views/api/v0/articles/index.json.jbuilder
  app/views/api/v0/articles/show.json.jbuilder
  app/views/api/v0/classified_listings/_listing.json.jbuilder
  app/views/api/v0/followers/_follows.json.jbuilder
  app/views/api/v0/followings/tags.json.jbuilder
  app/views/api/v0/users/me.json.jbuilder
  config/routes.rb
  spec/requests/api/v0/chat_channels_spec.rb
  spec/requests/api/v0/classified_listings_spec.rb
  spec/requests/api/v0/followers_spec.rb
  spec/requests/api/v0/followings_spec.rb
  spec/requests/api/v0/follows_spec.rb
  spec/requests/api/v0/github_repos_spec.rb
  spec/requests/api/v0/reactions_spec.rb
  spec/requests/api/v0/users_spec.rb
  spec/requests/api/v0/webhooks_spec.rb
  spec/requests/reactions_api_spec.rb
  spec/requests/users_api_spec.rb
  spec/services/suggester/users/sidebar_spec.rb
Labels: PR: reviewed-approved

#5920 Log Notification db table size
  app/workers/metrics/record_db_table_counts_worker.rb
Labels: PR: reviewed-approved

#5933 Fix serialization error with video_thumbnail_url
  app/controllers/api/v0/articles_controller.rb
  spec/requests/api/v0/articles_spec.rb
Labels: PR: reviewed-approved

#5721 Add an internal user interface guide
  docs/internal/internal-user-interface.md
  docs/internal/readme.md
Labels: PR: reviewed-approved

#5919 Add Code To Setup the Elasticsearch Tag Index
  .travis.yml
  app/services/search/cluster.rb
  app/services/search/tag.rb
  lib/tasks/search.rake
  spec/rails_helper.rb
  spec/services/search/cluster_spec.rb
  spec/services/search/tag_spec.rb
Labels: PR: reviewed-approved

#5921 Add index to notifications table to optimize query
  db/migrate/20200205225813_add_notifiable_id_notifiable_type_action_index_to_notifications.rb
  db/schema.rb
Labels: PR: reviewed-approved

#5925 Use Node lts/erbium (v12) for Netlify builds
  docs/.nvmrc
Labels: PR: reviewed-approved

#5443 Move Podcasts::GetEpisodesJob to Sidekiq
  app/controllers/admin/podcasts_controller.rb
  app/jobs/podcasts/get_episodes_job.rb
  app/workers/podcasts/get_episodes_worker.rb
  lib/tasks/fetch.rake
  spec/requests/admin/podcasts_spec.rb
  spec/workers/podcasts/get_episodes_worker_spec.rb
Labels: PR: reviewed-approved

#5802 Adjust cloning example to use SSH rather than HTTPS
  docs/installation/mac.md
Labels: PR: reviewed-approved

#5916 Refactored userData while working on hompage makeover.
  app/assets/javascripts/utilities/userData.js
Labels: PR: reviewed-approved

#5818 Style: update height of speakerdeck tag to be avoid scaling
  app/views/liquids/_speakerdeck.html.erb
Labels: PR: reviewed-approved

#5906 Use simpler messaging for ghost account deletion
  app/views/users/_account.html.erb
  app/views/users/confirm_destroy.html.erb
Labels: PR: reviewed-approved

#5924 Remove extra whitespace from text inputs in Buffer share
  app/views/internal/articles/_individual_article.html.erb
Labels: PR: reviewed-approved

#5564 Onboarding JS: refactor function out of repetitive blocks
  app/javascript/onboarding/components/BioForm.jsx
  app/javascript/onboarding/components/ClosingSlide.jsx
  app/javascript/onboarding/components/EmailListTermsConditionsForm.jsx
  app/javascript/onboarding/components/IntroSlide.jsx
  app/javascript/onboarding/utilities.js
Labels: PR: reviewed-approved

#5731 Add mod channel automation to tags
  app/labor/assign_tag_moderator.rb
  app/models/role.rb
  app/models/tag.rb
  db/migrate/20200125204226_add_moderator_chat_channel_id_to_tags.rb
  db/schema.rb
  spec/labor/assign_tag_moderator_spec.rb
  spec/models/role_spec.rb
  spec/models/tag_spec.rb
Labels: PR: unreviewed

#5864 Properly rename Podcasts::BustCacheWorker spec
  spec/workers/podcasts/bust_cache_worker_spec.rb
Labels: PR: reviewed-approved

#5940 Correct startup script and docs
  bin/startup
  docs/getting-started/start-app.md
Labels: PR: reviewed-approved

#5941 Include instructions to set Algolia plan
  docs/backend/algolia.md
Labels: PR: reviewed-approved

#5931 Add various badges to README [skip ci]
  README.md
Labels: PR: reviewed-approved

#5935 Fixes the link 'Other tools' in docs (on /getting-started/start-app/)
  docs/getting-started/start-app.md
Labels: PR: reviewed-approved

#5803 Refactor ProfileImage
  app/controllers/async_info_controller.rb
  app/controllers/comments_controller.rb
  app/controllers/live_articles_controller.rb
  app/controllers/messages_controller.rb
  app/labor/profile_image.rb
  app/models/article.rb
  app/models/chat_channel.rb
  app/models/chat_channel_membership.rb
  app/models/classified_listing.rb
  app/models/comment.rb
  app/models/message.rb
  app/models/organization.rb
  app/models/podcast.rb
  app/models/podcast_episode.rb
  app/models/user.rb
  app/serializers/webhook/user_serializer.rb
  app/views/additional_content_boxes/_article_content_area.html.erb
  app/views/additional_content_boxes/_article_followable_area.html.erb
  app/views/api/v0/articles/onboarding.json.jbuilder
  app/views/api/v0/shared/_follows.json.jbuilder
  app/views/api/v0/shared/_organization.json.jbuilder
  app/views/api/v0/shared/_user.json.jbuilder
  app/views/api/v0/users/index.json.jbuilder
  app/views/api/v0/users/show.json.jbuilder
  app/views/articles/_about_author.html.erb
  app/views/articles/_liquid.html.erb
  app/views/articles/_single_story.html.erb
  app/views/articles/_special_sidebar.html.erb
  app/views/articles/_sticky_nav.html.erb
  app/views/articles/index.html.erb
  app/views/articles/show.html.erb
  app/views/articles/tags/_sidebar.html.erb
  app/views/chat_channels/show.json.jbuilder
  app/views/comments/_comment_proper.html.erb
  app/views/comments/_liquid.html.erb
  app/views/comments/deleted_commentable_comment.html.erb
  app/views/dashboards/followers.html.erb
  app/views/dashboards/following_organizations.html.erb
  app/views/dashboards/following_users.html.erb
  app/views/internal/comments/index.html.erb
  app/views/moderations/index.html.erb
  app/views/organizations/_liquid.html.erb
  app/views/organizations/_sidebar_additional.html.erb
  app/views/pages/shecoded.html.erb
  app/views/partnerships/_form.html.erb
  app/views/social_previews/article.html.erb
  app/views/social_previews/comment.html.erb
  app/views/social_previews/shecoded.html.erb
  app/views/social_previews/user.html.erb
  app/views/users/_liquid.html.erb
  app/views/users/_organizations_area.html.erb
  app/views/users/_profile.html.erb
  app/views/users/_profile_header.html.erb
  app/views/users/show.html.erb
  spec/liquid_tags/link_tag_spec.rb
  spec/requests/api/v0/chat_channels_spec.rb
  spec/requests/api/v0/followers_spec.rb
  spec/requests/api/v0/followings_spec.rb
  spec/requests/api/v0/users_spec.rb
  spec/requests/api/v0/webhooks_spec.rb
Labels: PR: reviewed-approved

#5943 Remove .first query in services/notifications/update to fix dying jobs
  app/services/notifications/update.rb
Labels: PR: reviewed-approved

#5939 Setup Elasticsearch indexes during Deploy and Local App Setup
  bin/setup
  bin/update
  docs/deployment.md
  release-tasks.sh
Labels: PR: reviewed-approved

#5930 Enable bullet during tests to catch N+1 early (and some cleanups)
  app/controllers/internal/mods_controller.rb
  app/controllers/podcasts_controller.rb
  app/models/comment.rb
  app/models/html_variant.rb
  app/models/message.rb
  app/models/reaction.rb
  app/models/tweet.rb
  config/environments/test.rb
Labels: PR: reviewed-approved

#5937 Ensure user is authenticated before doing onboarding Actions
  app/controllers/users_controller.rb
  spec/requests/users_onboarding_spec.rb
Labels: PR: reviewed-approved

#5922 Fix logging for dev and test environments
  app/controllers/omniauth_callbacks_controller.rb
  config/environments/development.rb
  config/environments/test.rb
  spec/services/rss_reader_spec.rb
  spec/system/user_logs_in_with_twitter_spec.rb
  spec/workers/metrics/record_db_table_counts_worker_spec.rb
Labels: PR: reviewed-approved

#5948 Updated DB Prep Documentation with Seed Data Section
  docs/getting-started/db.md
Labels: PR: reviewed-approved

#5949 Removing border-box from SheCoded landing page
  app/views/pages/shecoded.html.erb
Labels: PR: reviewed-approved, area: shecoded, tech: html/css

#5936 Refactor API Reactions controller and add specs
  app/controllers/api/v0/reactions_controller.rb
  spec/requests/api/v0/reactions_spec.rb
Labels: PR: reviewed-approved

#5907 Remove Unused ChatChannel Indexing
  app/controllers/chat_channel_memberships_controller.rb
  app/controllers/chat_channels_controller.rb
  app/models/chat_channel.rb
  app/models/message.rb
  app/services/users/cleanup_chat_channels.rb
Labels: PR: reviewed-approved

#5954 Eager load users when handling chat channel memberships
  app/services/user_blocks/channel_handler.rb
Labels: PR: reviewed-approved

#5697 Worker/estimate default language
  app/models/user.rb
  app/workers/users/estimate_default_language_worker.rb
  spec/models/user_spec.rb
  spec/workers/users/estimate_default_language_worker_spec.rb
Labels: PR: reviewed-approved

#5944 Add low-value landing pages to robots.txt disallow
  app/views/pages/robots.text.erb
Labels: PR: reviewed-approved

#5820 Handle Reactions Without Users When Sending Notifications
  app/services/notifications/reactions/send.rb
  spec/models/notification_spec.rb
Labels: PR: reviewed-approved

#5952 Added template select to the pages admin form
  app/models/page.rb
  app/views/internal/pages/_form.html.erb
Labels: PR: reviewed-approved

#5956 Remove Users::EstimateDefaultLanguageJob & spec
  app/jobs/users/estimate_default_language_job.rb
  spec/jobs/users/estimate_default_language_job_spec.rb
Labels: PR: reviewed-approved

#5960 Update queue_adapter to Sidekiq
  config/application.rb
Labels: PR: reviewed-approved

#5961 Revert "Update queue_adapter to Sidekiq"
  config/application.rb
Labels: PR: reviewed-approved

#5942 Log in Datadog When Sidekiq Worker Fails for Final Time
  config/initializers/sidekiq.rb
  lib/sidekiq/worker_retries_exhausted_reporter.rb
  spec/lib/sidekiq/worker_retries_exhausted_reporter_spec.rb
Labels: PR: reviewed-approved

#5971 Fix indentation in search.rake
  lib/tasks/search.rake
Labels: PR: reviewed-approved

#5816 Replace ban/banned with suspend/suspended in user facing text
  CODE_OF_CONDUCT.md
  app/controllers/application_controller.rb
  app/controllers/articles_controller.rb
  app/controllers/chat_channels_controller.rb
  app/controllers/classified_listings_controller.rb
  app/controllers/messages_controller.rb
  app/controllers/users_controller.rb
  app/views/pages/_coc_text.html.erb
  app/views/users/_org_non_member.html.erb
  config/initializers/honeybadger.rb
  spec/requests/classified_listings_spec.rb
  spec/system/banned_user_interactions_spec.rb
Labels: PR: reviewed-approved

#5963 Validate that API article params are a Hash
  app/controllers/api/v0/articles_controller.rb
  spec/requests/api/v0/articles_spec.rb
Labels: PR: reviewed-approved

#5929 Removed unused special_sidebar
  app/views/articles/_special_sidebar.html.erb
Labels: PR: reviewed-approved

#6001 Remove Indexing Helpers from ChatChannel model in seed script
  db/seeds.rb
Labels: PR: reviewed-approved

#6003 Add multiplier for seeds and use it for articles and users
  db/seeds.rb
  docs/getting-started/db.md
Labels: PR: reviewed-approved

#6000 Sort reserved words
  config/initializers/reserved_words.rb
Labels: PR: reviewed-approved

#6007 Add foreman to setup script
  bin/setup
Labels: PR: reviewed-approved

#5962 Soft save notification_subscription and then check persisted
  app/controllers/notification_subscriptions_controller.rb
Labels: PR: reviewed-approved

#5981 Removed full_page from the Page TEMPLATE_OPTIONS
  app/models/page.rb
Labels: PR: reviewed-approved

#5976 Copy .ruby-version into Dockerfile
  Dockerfile
Labels: PR: reviewed-approved

#6009 Do not allow staff_user_id to be mutated
  app/controllers/internal/configs_controller.rb
  app/views/internal/configs/show.html.erb
  spec/requests/internal/configs_spec.rb
Labels: PR: reviewed-approved

#6005 Fixed false negative of a frontend test suite failing.
  jest.config.js
Labels: PR: reviewed-approved

#6019 Add `/embed` to list of disallowed path matches
  app/views/service_worker/index.js.erb
Labels: PR: reviewed-approved

#5978 Add ElasticSearch to Docker Compose
  .gitignore
  docker-compose.yml
  docs/installation/docker.md
Labels: PR: reviewed-approved

#5958 Index Tags to Elasticsearch after they are created
  app/models/tag.rb
  app/serializers/search/tag_serializer.rb
  app/services/search/tag.rb
  app/workers/search/tag_es_index_worker.rb
  spec/models/tag_spec.rb
  spec/services/search/tag_spec.rb
  spec/workers/search/tag_es_index_worker_spec.rb
Labels: PR: reviewed-approved

#6020 Assign teams to files and directories
  .github/CODEOWNERS
Labels: PR: reviewed-approved

#5918 Homepage left side bar tags followed
  app/assets/javascripts/initializers/initializeBaseUserData.js
  app/assets/stylesheets/articles.scss
  app/javascript/leftSidebar/TagsFollowed.jsx
  app/javascript/leftSidebar/__tests__/TagsFollowed.test.jsx
  app/javascript/leftSidebar/__tests__/__snapshots__/TagsFollowed.test.jsx.snap
  app/javascript/leftSidebar/index.js
  app/javascript/packs/homePage.js
  app/javascript/packs/homePage.jsx
  app/views/articles/_sidebar.html.erb
  spec/system/homepage/user_visits_homepage_spec.rb
Labels: PR: reviewed-approved, area: homepage

#5804 Mailchimp unsubscribe webhook
  app/controllers/incoming_webhooks/mailchimp_unsubscribes_controller.rb
  app/models/site_config.rb
  config/routes.rb
  spec/requests/incoming_webhooks/mailchimp/unsubscribe_spec.rb
Labels: PR: reviewed-approved

#6022 Upgrade omniauth-github to fix Github login deprecation notice
  Gemfile.lock
Labels: PR: reviewed-approved

#6008 Replace dev.to with ApplicationConfig in a few locations
  app/controllers/feedback_messages_controller.rb
  app/controllers/internal/tools_controller.rb
  app/controllers/internal/welcome_controller.rb
  app/controllers/users_controller.rb
  app/labor/badge_rewarder.rb
  app/labor/cache_buster.rb
Labels: PR: reviewed-approved

#5999 Return a 404 not found error if moderatable is not found
  app/controllers/moderations_controller.rb
  spec/requests/moderations_spec.rb
Labels: PR: reviewed-approved

#6011 Update doorkeeper initializer with new (disabled) features
  config/initializers/doorkeeper.rb
Labels: PR: reviewed-approved

#6012 Gemfile should be installable from wherever
  Gemfile
Labels: PR: reviewed-approved

#6026 Use POST instead of GET for CSRF protection
  app/controllers/users_controller.rb
  app/views/users/_account.html.erb
  config/routes.rb
  spec/requests/user/user_destroy_spec.rb
Labels: PR: reviewed-approved

#6029 Flaky Spec Fix: Article Decorator Spec Remove extra period if name ends with it
  spec/decorators/article_decorator_spec.rb
Labels: PR: reviewed-approved

#6028 Fixed an issue with dev shop logos not being styled properly.
  app/assets/stylesheets/articles.scss
Labels: PR: reviewed-approved

#5979 Update PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: PR: reviewed-approved

#5953 Consolidate server side main article feed logic
  app/assets/javascripts/initializers/initializeFetchFollowedArticles.js.erb
  app/controllers/stories_controller.rb
  app/services/articles/feed.rb
  app/views/articles/index.html.erb
  app/views/stories/_main_stories_feed.html.erb
  spec/services/articles/feed_spec.rb
  spec/system/homepage/user_visits_homepage_articles_spec.rb
Labels: PR: reviewed-approved, area: homepage, type: refactoring

#6027 Add unsubscribe option to badge and connect emails
  app/controllers/email_subscriptions_controller.rb
  app/mailers/notify_mailer.rb
Labels: PR: reviewed-approved

#5582 Change BustReactableCacheJob to BustReactableCacheWorker and move to sidekiq
  app/models/reaction.rb
  app/workers/reactions/bust_reactable_cache_worker.rb
  spec/models/reaction_spec.rb
  spec/workers/reactions/bust_reactable_cache_worker_spec.rb
Labels: PR: unreviewed

#6021 Small API controllers refactoring
  app/controllers/api/v0/api_controller.rb
  app/controllers/api/v0/articles_controller.rb
  app/controllers/api/v0/classified_listings_controller.rb
  app/controllers/api/v0/comments_controller.rb
  app/controllers/api/v0/github_repos_controller.rb
  app/controllers/api/v0/podcast_episodes_controller.rb
  app/controllers/api/v0/tags_controller.rb
  app/controllers/api/v0/videos_controller.rb
  app/controllers/api/v0/webhooks_controller.rb
  app/controllers/application_controller.rb
Labels: PR: reviewed-approved

#6004 Change error styling from syntax highlighting for a better UI in all themes
  app/assets/stylesheets/syntax.scss
Labels: PR: reviewed-approved

#6034 Add health check endpoint for Mailchimp unsubscribe webhook
  app/controllers/incoming_webhooks/mailchimp_unsubscribes_controller.rb
  config/routes.rb
  spec/requests/incoming_webhooks/mailchimp/unsubscribe_spec.rb
Labels: PR: unreviewed

#5551 Change UpdateReactableJob to UpdateReactableWorker and move to sidekiq
  app/models/reaction.rb
  app/workers/reactions/update_reactable_worker.rb
  spec/models/reaction_spec.rb
  spec/workers/reactions/update_reactable_worker_spec.rb
Labels: PR: unreviewed

#6069 Enable bread crumbs for Honeybadger
  config/initializers/honeybadger.rb
Labels: PR: reviewed-approved

#6064 Add additional safeguards for config write access
  app/controllers/internal/configs_controller.rb
  app/views/internal/configs/show.html.erb
  app/views/internal/permissions/index.html.erb
  app/views/layouts/internal.html.erb
  spec/factories/users.rb
  spec/requests/internal/configs_spec.rb
Labels: PR: reviewed-approved

#6024 Search Tags in Elasticsearch from Classified Listing and Post Creation
  app/controllers/search_controller.rb
  app/javascript/article-form/elements/__tests__/__snapshots__/tags.test.jsx.snap
  app/javascript/article-form/elements/__tests__/tags.test.jsx
  app/javascript/shared/components/tags.jsx
  app/services/search/tag.rb
  config/routes.rb
  spec/factories/tags.rb
  spec/requests/search_spec.rb
  spec/services/search/tag_spec.rb
Labels: PR: reviewed-approved

#6083 Made changes to timeAgo function for Preact component usage
  app/assets/javascripts/initializers/initializeFetchFollowedArticles.js.erb
  app/assets/javascripts/utilities/buildArticleHTML.js.erb
  app/assets/javascripts/utilities/timeAgo.js
  app/javascript/utilities/__tests__/timeAgo.test.js
Labels: area: homepage, tech: javascript

#6006 Add sink user service and specs for mass vomits
  app/controllers/internal/reactions_controller.rb
  app/controllers/reactions_controller.rb
  app/models/article.rb
  app/models/reaction.rb
  app/models/user.rb
  app/services/moderator/sink_articles.rb
  app/workers/moderator/sink_articles_worker.rb
  db/migrate/20200212164359_add_reactable_type_reactable_id_index_to_reactions.rb
  db/schema.rb
  spec/services/moderator/sink_articles_spec.rb
Labels: PR: unreviewed

#6013 Removed !important from some CSS properties set on body tag
  app/assets/stylesheets/scaffolds.scss
Labels: PR: reviewed-approved

#6128 Updates/adds to prop-types for homepage feed makeover.
  app/javascript/src/components/common-prop-types/article-prop-types.js
  app/javascript/src/components/common-prop-types/index.js
  app/javascript/src/components/common-prop-types/organization-prop-type.js
Labels: PR: reviewed-approved, area: developer experience, area: homepage

#6130 Updates to Storybook for home page makeover.
  app/javascript/.storybook/assets/images/storm-trooper-33x33.png
  app/javascript/.storybook/config.js
  app/javascript/.storybook/storybook.scss
  package.json
Labels: area: developer experience, area: homepage

#6116 Enable CORS on public API endpoints
  Gemfile
  Gemfile.lock
  app/controllers/api/v0/api_controller.rb
  app/controllers/api/v0/articles_controller.rb
  app/controllers/api/v0/podcast_episodes_controller.rb
  app/controllers/api/v0/videos_controller.rb
  config/application.rb
  docs/api_v0.yml
  spec/requests/api/v0/articles_spec.rb
Labels: PR: reviewed-approved

#6138 Routine rubocop fixes
  .rubocop_todo.yml
  config/environments/development.rb
  config/initializers/docker.rb
  db/seeds.rb
  lib/tasks/fetch.rake
  spec/factories/users.rb
  spec/lib/data_update_scripts/re_index_existing_articles_with_approved_spec.rb
  spec/requests/api/v0/chat_channels_spec.rb
  spec/requests/classified_listings_spec.rb
  spec/requests/internal/configs_spec.rb
  spec/requests/shared_examples/comment_hide_or_unhide_request.rb
  spec/requests/user/user_profile_spec.rb
  spec/services/articles/creator_spec.rb
  spec/support/api_analytics_shared_examples.rb
Labels: PR: unreviewed

#6079 Stop using legacy user's organization_id and remove followers unused code
  app/assets/javascripts/initializers/initScrolling.js.erb
  app/controllers/api/v0/followers_controller.rb
  app/controllers/dashboards_controller.rb
  app/controllers/notifications_controller.rb
  app/views/api/v0/followers/organizations.json.jbuilder
  config/routes.rb
  spec/requests/api/v0/followers_spec.rb
  spec/requests/notifications_spec.rb
Labels: PR: reviewed-approved

#6141 Campaign settings
  app/controllers/internal/configs_controller.rb
  app/controllers/stories_controller.rb
  app/models/html_variant.rb
  app/models/site_config.rb
  app/views/articles/_sidebar_additional.html.erb
  app/views/articles/_sidebar_campaign.html.erb
  app/views/html_variants/_form.html.erb
  app/views/html_variants/index.html.erb
  app/views/internal/configs/show.html.erb
  app/views/layouts/application.html.erb
  spec/requests/stories_index_spec.rb
Labels: PR: reviewed-approved

#5938 [docs] Add a maintainers document
  docs/maintainers/readme.md
  docs/readme.md
  docs/tests/readme.md
  docs/tests/skip-ci.md
Labels: PR: reviewed-approved

#4727 Create greeter
  .github/workflows/greetings.yml
Labels: PR: reviewed-approved

#6153 Enable CORS preflight caching for API
  config/application.rb
  spec/requests/api/v0/articles_spec.rb
Labels: PR: reviewed-approved, area: api-v0

#6154 Added jest config to support test utility modules.
  docs/tests/frontend-tests.md
  docs/tests/preact-tests.md
  docs/tests/readme.md
  jest.config.js
Labels: area: developer experience, tech: javascript

#4184 Add dropdown menu to listings
  app/assets/stylesheets/classified_listings.scss
  app/javascript/listings/__tests__/__snapshots__/singleListing.test.jsx.snap
  app/javascript/listings/__tests__/singleListing.test.jsx
  app/javascript/listings/listings.jsx
  app/javascript/listings/singleListing.jsx
  app/javascript/listings/singleListing/AuthorInfo.jsx
  app/javascript/listings/singleListing/DropdownMenu.jsx
  app/javascript/listings/singleListing/Header.jsx
  app/javascript/listings/singleListing/TagLinks.jsx
  app/javascript/listings/singleListing/index.jsx
  app/javascript/listings/singleListing/listingPropTypes.js
  db/schema.rb
Labels: PR: reviewed-approved

#6159 Add heroku slug commit to some cache keys
  app/views/articles/_sidebar_additional.html.erb
  app/views/articles/index.html.erb
  app/views/stories/_main_stories_feed.html.erb
Labels: PR: reviewed-approved

#6171 Upgrade gems
  Gemfile
  Gemfile.lock
Labels: PR: unreviewed
