Repository forem/forem, pull requests merged in 2020-07, with the labels that each got.

#9042 change the connect Scrolling
  app/assets/stylesheets/chat.scss
Labels: PR: partially-approved

#8929 Fetch article by slug
  app/controllers/api/v0/articles_controller.rb
  config/routes.rb
  spec/requests/api/v0/articles_spec.rb
Labels: PR: reviewed-approved

#9041 Added upload spinner for cover image in editor
  app/javascript/article-form/components/ArticleCoverImage.jsx
  app/javascript/article-form/components/__tests__/ArticleCoverImage.test.jsx
Labels: PR: partially-approved, area: publishing experience, tech: html/css, tech: javascript

#9048 Unique IDs for hidden article_archived fields
  app/views/dashboards/_dashboard_article_row.html.erb
Labels: PR: reviewed-approved

#9006 Stop allowing accented characters in tags
  app/javascript/shared/components/tags.jsx
  app/models/tag.rb
  spec/models/tag_spec.rb
Labels: PR: partially-approved

#9051 Added pragmaFrag so terse Fragment syntax, `<></>`, can be used in Preact
  app/javascript/article-form/components/ArticleCoverImage.jsx
  babel.config.js
Labels: PR: partially-approved, area: frontend infrastructure

#9049 Word-break utility-first class
  app/assets/stylesheets/config/_generator.scss
  app/views/articles/_sticky_nav.html.erb
Labels: Crayons, PR: partially-approved, PR: unreviewed, tech: html/css

#9047 Fixing scrollbar for small screens in the profile page
  app/assets/stylesheets/index-comments.scss
  app/views/users/_comments_section.html.erb
Labels: PR: reviewed-approved

#9003 Update styling of user subscription liquid tag
  app/assets/stylesheets/ltags/UserSubscriptionTag.scss
  app/liquid_tags/user_subscription_tag.rb
  app/views/liquids/_user_subscription.html.erb
Labels: DEV team, PR: partially-approved, PR: reviewed-changes-requested, PR: unreviewed, area: liquid tags, tech: html/css

#8942 Only include community sponsors header if sponsors truly exist
  app/views/articles/_sidebar.html.erb
Labels: PR: unreviewed

#9053 fix blockquote render error windows docs
  docs/installation/windows.md
Labels: PR: partially-approved

#9033 [ModCenter] Make formatDate function more robust for intl date-time formats
  app/javascript/modCenter/singleArticle/util.js
Labels: PR: reviewed-approved

#9021 Feature: Enable KnapsackPro Queue Mode Take 2
  .travis.yml
  bin/knapsack_pro_rspec
Labels: PR: reviewed-approved

#9059 Remove report-abuse link from base HTML document into JavaScript
  app/assets/javascripts/initializers/initializeCommentDropdown.js
  app/assets/javascripts/initializers/initializeUserProfilePage.js
  app/views/comments/_comment_proper.html.erb
  app/views/users/show.html.erb
Labels: PR: reviewed-approved

#9064 Refactor Flare Tag Class
  app/services/flare_tag.rb
Labels: PR: partially-approved

#9062 Add null safety to handleLoggedOut()
  app/javascript/responseTemplates/responseTemplates.js
Labels: PR: partially-approved

#9018 Enable Automatic Rebase: Fix #8927
  .github/workflows/rebase.yml
Labels: PR: partially-approved

#9071 🐞Hotfix: Connect page is showing discoverable channels
  app/javascript/chat/channels.jsx
Labels: PR: reviewed-approved

#9069 Show org dropdown for postless users
  app/views/dashboards/show.html.erb
Labels: PR: reviewed-approved

#9050 Add collapsible panel to markdown help in editor
  app/assets/stylesheets/components/tables.scss
  app/assets/stylesheets/config/_generator.scss
  app/javascript/article-form/components/Help.jsx
Labels: PR: partially-approved, area: publishing experience, tech: html/css

#9073 Fixed <RequestManager /> skipped test
  app/javascript/chat/__tests__/requestManager.test.jsx
Labels: PR: partially-approved, area: tests, tech: javascript

#9068 Add secondary_logo_url to SiteConfig
  app/models/site_config.rb
Labels: PR: reviewed-approved

#9063 Add Stackery liquid tag
  app/liquid_tags/stackery_tag.rb
  app/views/liquids/_stackery.html.erb
  app/views/pages/_editor_guide_text.html.erb
  app/views/pages/_editor_liquid_help.html.erb
  docs/frontend/liquid-tags.md
  spec/liquid_tags/stackery_tag_spec.rb
Labels: PR: partially-approved

#9060 UserSubscription backend refactor
  app/controllers/user_subscriptions_controller.rb
  app/models/user_subscription.rb
  app/services/user_subscriptions/create_from_controller_params.rb
  app/services/user_subscriptions/is_subscribed_cache_checker.rb
  spec/factories/articles.rb
  spec/factories/user_subscription.rb
  spec/models/shared_examples/user_subscription_sourceable_spec.rb
  spec/models/user_subscription_spec.rb
  spec/requests/user_subscriptions_spec.rb
  spec/services/user_subscriptions/create_from_controller_params_spec.rb
  spec/services/user_subscriptions/is_subscribed_cache_checker_spec.rb
Labels: PR: partially-approved

#9057 Update Honeybadger to ignore ResizeObserver
  app/assets/javascripts/base.js.erb
Labels: PR: partially-approved

#9080 Standardize capitalization of JavaScript
  docs/frontend/plain-js.md
  docs/frontend/webpacker.md
  docs/installation/windows.md
  docs/maintainers/deploying.md
  docs/tests/test-flags.md
Labels: PR: unreviewed

#9070 fix node install windows docs
  docs/installation/windows.md
Labels: PR: reviewed-approved

#9088 Fixed the three dot menu on the article page.
  app/assets/javascripts/initializers/initializeCommentDropdown.js
Labels: PR: partially-approved, area: articles, tech: javascript

#9094 Update yarn lock
  yarn.lock
Labels: PR: reviewed-approved

#9095 Slight fix in dropdown menu code
  app/assets/javascripts/initializers/initializeCommentDropdown.js
  app/views/articles/_actions.html.erb
Labels: PR: unreviewed

#9093 Fixed remaining lint issues in the frontend.
  app/assets/javascripts/initializers/initNotifications.js
  app/assets/javascripts/initializers/initializeAllFollowButts.js
  app/assets/javascripts/initializers/initializeDrawerSliders.js
Labels: PR: partially-approved, tech: javascript

#9097 Search highlight text
  app/assets/stylesheets/components/stories.scss
Labels: PR: partially-approved, area: search/indexing, tech: html/css

#9096 Add a workflow to greet new contributors
  .github/workflows/welcome.yml
Labels: PR: reviewed-approved

#9090 Allow organization owners to use the Automatic Rebase workflow
  .github/workflows/rebase.yml
Labels: PR: unreviewed

#9098 Change Highlight Tags to mark instead of em
  app/services/search/query_builders/feed_content.rb
  spec/services/broadcasts/welcome_notification/generator_spec.rb
  spec/services/search/feed_content_spec.rb
  spec/system/search/display_comments_search_spec.rb
Labels: PR: partially-approved

#9104 update: add mastodon.online to the whitelist
  app/lib/constants.rb
Labels: PR: partially-approved

#9087 Update PollTag
  app/liquid_tags/poll_tag.rb
  app/models/article.rb
  app/models/user_subscription.rb
  spec/models/article_spec.rb
Labels: PR: partially-approved

#9099 Added node.js internals to list of skipped files for debugging jest in VS Code
  .vscode/launch.json
Labels: PR: partially-approved, area: tests

#9102 Remove unused test for Redis cache store
  spec/initializers/active_support/cache/redis_cache_store_spec.rb
Labels: PR: reviewed-approved

#8972 fix lint errors in initializeSwipeGestures
  app/assets/javascripts/initializers/initializeSwipeGestures.js
Labels: PR: reviewed-approved

#8881 Hide notification when comment is hidden
  app/controllers/comments_controller.rb
  spec/requests/comments_spec.rb
Labels: PR: reviewed-approved

#9100 Now frontend code is linted before running tests
  package.json
Labels: PR: unreviewed, area: frontend infrastructure

#9113 🐞 Hotfix: Sidecar's Design issues on Small screens
  app/assets/stylesheets/chat.scss
Labels: PR: partially-approved

#9112 Remove first interaction workflow
  .github/workflows/welcome.yml
Labels: PR: reviewed-approved

#9144 Fix pro link for organization users
  app/views/dashboards/_actions.html.erb
  app/views/dashboards/_actions_mobile.html.erb
  config/routes.rb
  spec/requests/dashboard_spec.rb
Labels: PR: partially-approved

#9146 Sass loader 9.0.1 upgrade
  app/assets/stylesheets/article-show.scss
  app/assets/stylesheets/connect/_channel-details.scss
  app/assets/stylesheets/ltags/CommentTag.scss
  app/assets/stylesheets/ltags/GithubReadmeTag.scss
  app/assets/stylesheets/ltags/GithubTag.scss
  app/assets/stylesheets/ltags/LinkTag.scss
  app/assets/stylesheets/ltags/ListingTag.scss
  app/assets/stylesheets/ltags/PodcastTag.scss
  app/assets/stylesheets/ltags/PollTag.scss
  app/assets/stylesheets/ltags/RedditTag.scss
  app/assets/stylesheets/ltags/StackexchangeTag.scss
  app/assets/stylesheets/ltags/TagTag.scss
  app/assets/stylesheets/ltags/TweetTag.scss
  app/assets/stylesheets/ltags/UserSubscriptionTag.scss
  app/assets/stylesheets/ltags/UserTag.scss
  app/assets/stylesheets/ltags/WikipediaTag.scss
  app/assets/stylesheets/preact/article-form.scss
  app/assets/stylesheets/preact/onboarding-modal.scss
  app/assets/stylesheets/preact/sidebar-widget.scss
  app/javascript/.storybook/main.js
  package.json
  yarn.lock
Labels: PR: partially-approved, area: frontend infrastructure, tech: html/css

#9120 Delete box-shadow to .github-repos class
  app/assets/stylesheets/settings.scss
Labels: PR: reviewed-approved

#9072 Tags index design update
  app/assets/javascripts/initializers/initScrolling.js
  app/assets/javascripts/initializers/initializeAllFollowButts.js
  app/assets/stylesheets/base/helpers.scss
  app/assets/stylesheets/components/tags.scss
  app/assets/stylesheets/crayons.scss
  app/assets/stylesheets/views/dashboard.scss
  app/views/articles/_sticky_nav.html.erb
  app/views/dashboards/following_tags.html.erb
  app/views/tags/index.html.erb
  spec/requests/tags_spec.rb
Labels: Crayons, PR: partially-approved, PR: unreviewed, area: tags, tech: html/css

#9155 Routine rubocop fixes
  .rubocop_todo.yml
  spec/requests/articles/articles_spec.rb
Labels: PR: partially-approved

#9085 Cleanup existing liquid tags
  app/liquid_tags/asciinema_tag.rb
  app/liquid_tags/blogcast_tag.rb
  app/liquid_tags/codepen_tag.rb
  app/liquid_tags/codesandbox_tag.rb
  app/liquid_tags/comment_tag.rb
  app/liquid_tags/gist_tag.rb
  app/liquid_tags/git_pitch_tag.rb
  app/liquid_tags/github_tag.rb
  app/liquid_tags/glitch_tag.rb
  app/liquid_tags/instagram_tag.rb
  app/liquid_tags/js_fiddle_tag.rb
  app/liquid_tags/jsitor_tag.rb
  app/liquid_tags/katex_tag.rb
  app/liquid_tags/kotlin_tag.rb
  app/liquid_tags/link_tag.rb
  app/liquid_tags/listing_tag.rb
  app/liquid_tags/medium_tag.rb
  app/liquid_tags/next_tech_tag.rb
  app/liquid_tags/organization_tag.rb
  app/liquid_tags/parler_tag.rb
  app/liquid_tags/podcast_tag.rb
  app/liquid_tags/reddit_tag.rb
  app/liquid_tags/replit_tag.rb
  app/liquid_tags/runkit_tag.rb
  app/liquid_tags/slideshare_tag.rb
  app/liquid_tags/soundcloud_tag.rb
  app/liquid_tags/speakerdeck_tag.rb
  app/liquid_tags/spotify_tag.rb
  app/liquid_tags/stackblitz_tag.rb
  app/liquid_tags/stackery_tag.rb
  app/liquid_tags/stackexchange_tag.rb
  app/liquid_tags/tag_tag.rb
  app/liquid_tags/tweet_tag.rb
  app/liquid_tags/user_tag.rb
  app/liquid_tags/vimeo_tag.rb
  app/liquid_tags/wikipedia_tag.rb
  app/liquid_tags/youtube_tag.rb
Labels: PR: reviewed-approved

#9082 UserSubscription liquid tag update & re-enable JS
  app/liquid_tags/user_subscription_tag.rb
  app/views/articles/show.html.erb
  app/views/liquids/_user_subscription.html.erb
  spec/liquid_tags/user_subscription_tag_spec.rb
Labels: PR: reviewed-approved

#9159 Remove unnecessary fragment cache
  app/views/articles/show.html.erb
Labels: PR: partially-approved

#9107 LiquidTagBase spec
  spec/liquid_tags/liquid_tag_base_spec.rb
Labels: PR: partially-approved

#8215 Add unique indexes to follows - part 7
  app/models/follow.rb
  db/migrate/20200702143618_add_unique_index_to_follows_followable_follower.rb
  db/schema.rb
  spec/models/follow_spec.rb
Labels: PR: unreviewed, action: post deployment

#9145 Update acts_as_follower to 06393d3693a1 to avoid race condition
  Gemfile.lock
  vendor/cache/acts_as_follower-06393d3693a1/.bundlecache
  vendor/cache/acts_as_follower-06393d3693a1/.gitignore
  vendor/cache/acts_as_follower-06393d3693a1/.travis.yml
  vendor/cache/acts_as_follower-06393d3693a1/Gemfile
  vendor/cache/acts_as_follower-06393d3693a1/MIT-LICENSE
  vendor/cache/acts_as_follower-06393d3693a1/README.rdoc
  vendor/cache/acts_as_follower-06393d3693a1/Rakefile
  vendor/cache/acts_as_follower-06393d3693a1/acts_as_follower.gemspec
  vendor/cache/acts_as_follower-06393d3693a1/init.rb
  vendor/cache/acts_as_follower-06393d3693a1/lib/acts_as_follower.rb
  vendor/cache/acts_as_follower-06393d3693a1/lib/acts_as_follower/follow_scopes.rb
  vendor/cache/acts_as_follower-06393d3693a1/lib/acts_as_follower/followable.rb
  vendor/cache/acts_as_follower-06393d3693a1/lib/acts_as_follower/follower.rb
  vendor/cache/acts_as_follower-06393d3693a1/lib/acts_as_follower/follower_lib.rb
  vendor/cache/acts_as_follower-06393d3693a1/lib/acts_as_follower/railtie.rb
  vendor/cache/acts_as_follower-06393d3693a1/lib/acts_as_follower/version.rb
  vendor/cache/acts_as_follower-06393d3693a1/lib/generators/USAGE
  vendor/cache/acts_as_follower-06393d3693a1/lib/generators/acts_as_follower_generator.rb
  vendor/cache/acts_as_follower-06393d3693a1/lib/generators/templates/migration.rb
  vendor/cache/acts_as_follower-06393d3693a1/lib/generators/templates/model.rb
  vendor/cache/acts_as_follower-06393d3693a1/test/README
  vendor/cache/acts_as_follower-06393d3693a1/test/acts_as_followable_test.rb
  vendor/cache/acts_as_follower-06393d3693a1/test/acts_as_follower_test.rb
  vendor/cache/acts_as_follower-06393d3693a1/test/dummy30/Gemfile
  vendor/cache/acts_as_follower-06393d3693a1/test/dummy30/Rakefile
  vendor/cache/acts_as_follower-06393d3693a1/test/dummy30/app/models/application_record.rb
  vendor/cache/acts_as_follower-06393d3693a1/test/dummy30/app/models/band.rb
  vendor/cache/acts_as_follower-06393d3693a1/test/dummy30/app/models/band/punk.rb
  vendor/cache/acts_as_follower-06393d3693a1/test/dummy30/app/models/band/punk/pop_punk.rb
  vendor/cache/acts_as_follower-06393d3693a1/test/dummy30/app/models/custom_record.rb
  vendor/cache/acts_as_follower-06393d3693a1/test/dummy30/app/models/some.rb
  vendor/cache/acts_as_follower-06393d3693a1/test/dummy30/app/models/user.rb
  vendor/cache/acts_as_follower-06393d3693a1/test/dummy30/config.ru
  vendor/cache/acts_as_follower-06393d3693a1/test/dummy30/config/application.rb
  vendor/cache/acts_as_follower-06393d3693a1/test/dummy30/config/boot.rb
  vendor/cache/acts_as_follower-06393d3693a1/test/dummy30/config/database.yml
  vendor/cache/acts_as_follower-06393d3693a1/test/dummy30/config/environment.rb
  vendor/cache/acts_as_follower-06393d3693a1/test/dummy30/config/environments/development.rb
  vendor/cache/acts_as_follower-06393d3693a1/test/dummy30/config/environments/test.rb
  vendor/cache/acts_as_follower-06393d3693a1/test/dummy30/config/initializers/backtrace_silencers.rb
  vendor/cache/acts_as_follower-06393d3693a1/test/dummy30/config/initializers/inflections.rb
  vendor/cache/acts_as_follower-06393d3693a1/test/dummy30/config/initializers/secret_token.rb
  vendor/cache/acts_as_follower-06393d3693a1/test/dummy30/config/initializers/session_store.rb
  vendor/cache/acts_as_follower-06393d3693a1/test/dummy30/config/locales/en.yml
  vendor/cache/acts_as_follower-06393d3693a1/test/dummy30/config/routes.rb
  vendor/cache/acts_as_follower-06393d3693a1/test/factories/bands.rb
  vendor/cache/acts_as_follower-06393d3693a1/test/factories/somes.rb
  vendor/cache/acts_as_follower-06393d3693a1/test/factories/users.rb
  vendor/cache/acts_as_follower-06393d3693a1/test/follow_test.rb
  vendor/cache/acts_as_follower-06393d3693a1/test/schema.rb
  vendor/cache/acts_as_follower-06393d3693a1/test/test_helper.rb
  vendor/cache/acts_as_follower-288690cd99bc/test/dummy30/Gemfile
Labels: PR: partially-approved, blocked

#9103 Upgraded to preact testing library 2.0.0
  app/javascript/CommentSubscription/__tests__/CommentSubscription.test.jsx
  app/javascript/Search/__tests__/Search.test.jsx
  app/javascript/article-form/components/__tests__/ArticleCoverImage.test.jsx
  app/javascript/article-form/components/__tests__/ImageUploader.test.jsx
  app/javascript/githubRepos/__tests__/githubRepos.test.jsx
  app/javascript/onboarding/__tests__/Onboarding.test.jsx
  app/javascript/onboarding/components/__tests__/FollowTags.test.jsx
  app/javascript/onboarding/components/__tests__/FollowUsers.test.jsx
  app/javascript/onboarding/components/__tests__/IntroSlide.test.jsx
  app/javascript/onboarding/components/__tests__/ProfileForm.test.jsx
  app/javascript/shared/components/__tests__/tags.test.jsx
  package.json
  yarn.lock
Labels: PR: partially-approved, area: tests

#9166 Refactoring articles_controller reduce lines
  app/controllers/articles_controller.rb
Labels: PR: reviewed-approved

#9169 Bug Fix: Prevent Duplicate Follow Attempts by Preventing Multiple Workers
  app/workers/users/follow_worker.rb
Labels: PR: partially-approved

#9083 Resoucify Page and Badge models
  app/models/badge.rb
  app/models/page.rb
  spec/requests/internal/badges_spec.rb
  spec/requests/internal/pages_spec.rb
Labels: PR: partially-approved

#9176 Code highlighter fix
  app/assets/stylesheets/syntax.scss
  app/javascript/article-form/components/Help.jsx
Labels: PR: partially-approved, tech: html/css

#9178 Indicator placement in Navigation
  app/assets/stylesheets/components/navigation.scss
Labels: PR: partially-approved, tech: html/css

#9177 Fix action icons in dark themes
  app/views/articles/_actions.html.erb
Labels: PR: partially-approved, area: articles, tech: html/css

#8435 Display banner if site hasn't been configured (PRE DEPLOYMENT TASKS)
  app/assets/images/onboarding-background-white.png
  app/assets/javascripts/initializers/initializePaymentPointers.js
  app/assets/stylesheets/articles.scss
  app/assets/stylesheets/preact/onboarding-modal.scss
  app/controllers/application_controller.rb
  app/controllers/buffer_updates_controller.rb
  app/controllers/concerns/verify_setup_completed.rb
  app/controllers/internal/configs_controller.rb
  app/helpers/application_helper.rb
  app/javascript/onboarding/Onboarding.jsx
  app/labor/bufferizer.rb
  app/models/buffer_update.rb
  app/models/site_config.rb
  app/views/articles/_actions.html.erb
  app/views/articles/_search.html.erb
  app/views/dashboards/show.html.erb
  app/views/internal/configs/show.html.erb
  app/views/layouts/_signup_modal.html.erb
  app/views/layouts/application.html.erb
  app/views/layouts/internal.html.erb
  app/views/onboardings/_task_card.html.erb
  app/views/onboardings/show.html.erb
  app/views/shell/_top.html.erb
  app/views/stories/_sign_in_invitation.html.erb
  spec/rails_helper.rb
  spec/requests/articles/articles_show_spec.rb
  spec/requests/internal/configs_spec.rb
  spec/requests/onboardings_spec.rb
  spec/requests/pages_spec.rb
  spec/requests/stories_index_spec.rb
  spec/requests/tags_spec.rb
  spec/routing/all_routes_spec.rb
  spec/system/internal/admin_manages_configuration_spec.rb
  spec/system/search/display_jobs_banner_spec.rb
  spec/views/stories/sign_in_invitation.html.erb_spec.rb
Labels: PR: unreviewed, action: post deployment

#9175 Add crayons to pages
  app/assets/stylesheets/article-show.scss
  app/assets/stylesheets/typography.scss
  app/assets/stylesheets/views/article.scss
  app/javascript/article-form/components/Preview.jsx
  app/javascript/chat/__tests__/chat.test.jsx
  app/javascript/chat/chat.jsx
  app/views/articles/show.html.erb
  app/views/feedback_messages/_form.html.erb
  app/views/pages/_editor_frontmatter_help.html.erb
  app/views/pages/_editor_liquid_help.html.erb
  app/views/pages/_editor_markdown_help.html.erb
  app/views/pages/_placeholder.html.erb
  app/views/pages/code_of_conduct.html.erb
  app/views/pages/contact.html.erb
  app/views/pages/information.html.erb
  app/views/pages/markdown_basics.html.erb
  app/views/pages/privacy.html.erb
  app/views/pages/report_abuse.html.erb
  app/views/pages/rlyweb.html.erb
  app/views/pages/show.html.erb
  app/views/pages/sponsors.html.erb
  app/views/pages/terms.html.erb
Labels: Crayons, PR: draft, PR: partially-approved, PR: unreviewed, tech: html/css

#9181 Feature: Filter Sensitive Data From Production Logs
  config/environments/production.rb
Labels: PR: partially-approved

#9180 Feature: Label Honeybadger Env with Community Name
  config/initializers/honeybadger.rb
Labels: PR: partially-approved

#9182 Fix sign in flow for user subscription liquid tag
  app/liquid_tags/user_subscription_tag.rb
  spec/liquid_tags/user_subscription_tag_spec.rb
Labels: PR: partially-approved

#9191 Only run UserSubscription JS on appropriate Articles
  app/liquid_tags/user_subscription_tag.rb
Labels: PR: partially-approved

#9188 Use custom UglifierCompressor to enable source-maps
  config/environments/production.rb
  config/initializers/sprockets_uglifier_with_source_maps_compressor.rb
Labels: PR: partially-approved

#9190 Ignore MetaMask errors on Honeybadger
  app/assets/javascripts/base.js.erb
Labels: PR: partially-approved

#9192 Remove /rly code (to be replaced with "page")
  app/assets/stylesheets/generator.scss
  app/assets/stylesheets/rlyweb.scss
  app/controllers/pages_controller.rb
  app/views/pages/generator.html.erb
  app/views/pages/rlyweb.html.erb
  app/views/service_worker/index.js.erb
  config/routes.rb
  spec/requests/pages_spec.rb
Labels: PR: reviewed-approved, action: post deployment

#9161 Add subscriptions to the dashboard
  app/controllers/dashboards_controller.rb
  app/models/user_subscription.rb
  app/policies/article_policy.rb
  app/views/dashboards/_dashboard_article_row.html.erb
  app/views/dashboards/subscriptions.html.erb
  config/routes.rb
  db/migrate/20200706184804_add_user_subscriptions_count_to_articles.rb
  db/schema.rb
  spec/models/shared_examples/user_subscription_sourceable_spec.rb
  spec/requests/dashboard_spec.rb
Labels: PR: unreviewed

#9203 Remove unnecessary ?url= param from report-abuse
  app/views/articles/_conduct_and_abuse_actions.html.erb
Labels: PR: partially-approved

#9205 Refactor: Remove Omniauth Error Logs, Send to Honeybadger
  app/controllers/omniauth_callbacks_controller.rb
  spec/system/authentication/user_logs_in_with_github_spec.rb
  spec/system/authentication/user_logs_in_with_twitter_spec.rb
Labels: PR: partially-approved

#9207 Refactor: Remove Unnecessary logging from Video States, Stripe, and GA Events
  app/controllers/ga_events_controller.rb
  app/controllers/stripe_active_cards_controller.rb
  app/controllers/video_states_controller.rb
Labels: PR: reviewed-approved

#9170 Add role and docs for user subscription liquid tag
  app/controllers/articles_controller.rb
  app/liquid_tags/user_subscription_tag.rb
  app/models/liquid_tags/user_subscription_tag.rb
  app/models/role.rb
  app/views/pages/_editor_liquid_help.html.erb
  docs/frontend/liquid-tags.md
  spec/factories/articles.rb
  spec/factories/users.rb
  spec/liquid_tags/user_subscription_tag_spec.rb
  spec/models/role_spec.rb
  spec/policies/liquid_tag_policy_spec.rb
  spec/requests/dashboard_spec.rb
Labels: PR: unreviewed

#9056 Make the mobile Navigation icons configurable
  app/assets/images/lightning.svg
  app/assets/images/stack.svg
  app/assets/stylesheets/articles.scss
  app/controllers/internal/configs_controller.rb
  app/models/site_config.rb
  app/views/articles/index.html.erb
  app/views/articles/tag_index.html.erb
  app/views/internal/configs/show.html.erb
  app/views/users/show.html.erb
  spec/requests/internal/configs_spec.rb
Labels: PR: partially-approved

#9208 Refactor: Report Pusher Errors to Honeybadger, Remove Comment Error Logging
  app/controllers/comments_controller.rb
  app/controllers/messages_controller.rb
  app/helpers/messages_helper.rb
Labels: PR: partially-approved

#9216 Create SECURITY.md file
  SECURITY.md
Labels: PR: partially-approved

#9219 Replace hardcoded logo with secondary logo config
  app/assets/stylesheets/article-form-needed-legacy.scss
  app/views/devise/registrations/_registration_form.html.erb
Labels: PR: partially-approved

#9218 Rubocop: fix additional violations in todo file
  .rubocop.yml
  .rubocop_todo.yml
  app/controllers/api/v0/api_controller.rb
  app/controllers/incoming_webhooks/mailchimp_unsubscribes_controller.rb
  app/controllers/internal/application_controller.rb
  app/controllers/internal/articles_controller.rb
  app/controllers/internal/badges_controller.rb
  app/controllers/internal/broadcasts_controller.rb
  app/controllers/internal/buffer_updates_controller.rb
  app/controllers/internal/chat_channels_controller.rb
  app/controllers/internal/comments_controller.rb
  app/controllers/internal/configs_controller.rb
  app/controllers/internal/feedback_messages_controller.rb
  app/controllers/internal/growth_controller.rb
  app/controllers/internal/listings_controller.rb
  app/controllers/internal/moderator_actions_controller.rb
  app/controllers/internal/mods_controller.rb
  app/controllers/internal/organization_memberships_controller.rb
  app/controllers/internal/organizations_controller.rb
  app/controllers/internal/pages_controller.rb
  app/controllers/internal/path_redirects_controller.rb
  app/controllers/internal/permissions_controller.rb
  app/controllers/internal/podcasts_controller.rb
  app/controllers/internal/privileged_reactions_controller.rb
  app/controllers/internal/reactions_controller.rb
  app/controllers/internal/response_templates_controller.rb
  app/controllers/internal/secrets_controller.rb
  app/controllers/internal/sponsorships_controller.rb
  app/controllers/internal/tags_controller.rb
  app/controllers/internal/tools_controller.rb
  app/controllers/internal/users_controller.rb
  app/controllers/internal/webhook_endpoints_controller.rb
  app/controllers/internal/welcome_controller.rb
  app/controllers/notifications/counts_controller.rb
  app/controllers/notifications/reads_controller.rb
  app/controllers/stories/feeds_controller.rb
  app/helpers/application_helper.rb
  app/models/ahoy/event.rb
  app/models/ahoy/visit.rb
  app/models/role.rb
  config/initializers/ahoy.rb
  config/initializers/rack/attack.rb
  spec/initializers/rack/attack_spec.rb
  spec/liquid_tags/user_subscription_tag_spec.rb
  spec/models/article_spec.rb
  spec/models/comment_spec.rb
  spec/requests/display_ad_events_spec.rb
  spec/requests/internal/configs_spec.rb
Labels: PR: partially-approved

#9222 Bug Fix: Remove Rails Validation for Follow Uniqueness, Guard against dup Follow Jobs
  app/controllers/users_controller.rb
  app/models/follow.rb
  spec/models/follow_spec.rb
Labels: PR: partially-approved

#9223 Refactor:Send a Couple More Errors to Honeybadger
  app/labor/email_digest.rb
  app/lib/release_phase_notifier.rb
Labels: PR: partially-approved

#9217 Add Github CodeQL code scanner for JavaScript
  .github/workflows/codeql-analysis.yml
Labels: PR: reviewed-approved

#9226 Log instantClick errors
  app/assets/javascripts/base.js.erb
Labels: PR: reviewed-approved

#9225 Add number_with_delimiter to post count on tags page
  app/views/tags/index.html.erb
Labels: PR: partially-approved

#9227 Add markdown version for DEV badge link
  app/views/pages/badges.html.erb
Labels: PR: reviewed-approved

#9237 Hotfix: Disable Article Sinking
  app/services/moderator/sink_articles.rb
  spec/services/moderator/sink_articles_spec.rb
Labels: PR: partially-approved

#9204 Fix Style/SingleLineBlockParams, RSpec/MultipleExpectations and remaining Layout/LineLength
  .rubocop.yml
  .rubocop_todo.yml
  app/labor/markdown_fixer.rb
  spec/lib/data_update_scripts/re_index_feed_content_and_users_to_elasticsearch_spec.rb
  spec/services/broadcasts/welcome_notification/generator_spec.rb
Labels: PR: partially-approved

#9239 Add metrics around welcome notifications + their click events
  app/services/notifications/welcome_notification/send.rb
  app/workers/metrics/record_daily_notifications_worker.rb
  app/workers/metrics/record_daily_usage_worker.rb
  lib/tasks/metrics.rake
  spec/factories/ahoy.rb
  spec/factories/ahoy_message.rb
  spec/services/notifications/welcome_notification/send_spec.rb
  spec/workers/metrics/record_daily_notifications_worker_spec.rb
Labels: PR: partially-approved

#9221 Rubocop: fix Metrics/CyclomaticComplexity and disable Metrics/AbcSize
  .rubocop.yml
  .rubocop_todo.yml
  app/controllers/articles_controller.rb
  app/controllers/notifications_controller.rb
  app/services/articles/builder.rb
  spec/services/articles/builder_spec.rb
Labels: PR: partially-approved

#9242 Revert "Add number_with_delimiter to post count on tags page"
  app/views/tags/index.html.erb
Labels: PR: partially-approved

#9236 Remove arrow-left-... from github issue embed
  app/assets/stylesheets/ltags/GithubTag.scss
  app/views/liquids/_github_issue.html.erb
Labels: PR: partially-approved

#9162 Refactoring comments_controller#create reducing lines
  app/controllers/comments_controller.rb
  app/views/comments/_comment.json.jbuilder
Labels: PR: partially-approved

#9230 Article page: edit and manage button spacing
  app/assets/javascripts/initializers/initializeBaseUserData.js
  app/views/articles/show.html.erb
Labels: PR: partially-approved

#9224 Refactor:Use if/else When Selecting Production Log Strategy
  config/environments/production.rb
Labels: PR: reviewed-approved

#9246 Rubocop: Address Metrics/BlockLength violations
  .rubocop.yml
  .rubocop_todo.yml
  app/models/message.rb
  app/views/api/v0/articles/me.json.jbuilder
  config/environments/production.rb
  config/environments/test.rb
  config/initializers/honeycomb.rb
  lib/tasks/pages.rake
  package.json
Labels: PR: reviewed-approved

#9256 Bug Fix: Setup STDOUT Logger bc we need it
  config/environments/production.rb
Labels: PR: partially-approved

#9255 Update RssReader::Assembler#get_content hash syntax
  app/services/rss_reader/assembler.rb
Labels: PR: reviewed-approved

#9257 Optimization:Change Log Level in Prod to Info
  config/environments/production.rb
Labels: PR: partially-approved

#9241 Rubocop: fix Performance/OpenStruct
  .rubocop_todo.yml
  app/models/article.rb
  app/models/organization.rb
  app/services/notifications/reactions/send.rb
  app/views/stories/feeds/show.json.jbuilder
  spec/models/github_repo_spec.rb
  spec/requests/github_repos_spec.rb
Labels: PR: unreviewed

#9244 Rubocop: Address Rails/OutputSafety violations
  .rubocop_todo.yml
  app/helpers/application_helper.rb
  app/helpers/comments_helper.rb
  app/liquid_tags/github_tag/github_issue_tag.rb
  app/liquid_tags/liquid_tag_base.rb
  app/models/comment.rb
  app/models/display_ad.rb
  app/models/message.rb
Labels: PR: unreviewed

#9260 Fixed some minor typos
  docs/tests/readme.md
Labels: PR: reviewed-approved

#9232 Update Docs, Travis, and Containers to Use Postgres 11
  .travis.yml
  README.md
  container-compose.yml
  docker-compose.yml
  docs/installation/linux.md
  docs/installation/mac.md
  docs/installation/windows.md
Labels: PR: partially-approved

#9261 API: add docs for get published article by path
  docs/api_v0.yml
Labels: PR: partially-approved, area: api-v0

#9291 Revert "Rubocop: fix Performance/OpenStruct (#9241)"
  .rubocop_todo.yml
  app/models/article.rb
  app/models/organization.rb
  app/services/notifications/reactions/send.rb
  app/views/stories/feeds/show.json.jbuilder
  spec/models/github_repo_spec.rb
  spec/requests/github_repos_spec.rb
Labels: PR: reviewed-approved

#9231 Add Polymorphism to Broadcasts (Part 1)
  app/models/announcement.rb
  app/models/welcome_notification.rb
  db/migrate/20200707170245_add_polymorphism_to_broadcasts.rb
  db/migrate/20200707173316_create_announcements.rb
  db/migrate/20200707173524_create_welcome_notifications.rb
  db/migrate/20200710174257_add_index_to_broadcasts.rb
  db/schema.rb
  lib/data_update_scripts/20200708163323_backfill_broadcastable_type_for_broadcasts.rb
Labels: PR: partially-approved, action: post deployment

#9292 Hotfix: Fix Typo in backfill_broadcastable_type_for_broadcasts
  lib/data_update_scripts/20200708163323_backfill_broadcastable_for_broadcasts.rb
  lib/data_update_scripts/20200708163323_backfill_broadcastable_type_for_broadcasts.rb
Labels: PR: partially-approved

#9271 GitPod: Use node version 12.16.3
  .gitpod.dockerfile
Labels: PR: partially-approved

#9286 SiteConfig view refactoring
  app/views/layouts/_social_media.html.erb
  app/views/shell/_top.html.erb
Labels: PR: reviewed-approved

#9250 Service Worker default value to cached shell version
  app/views/service_worker/index.js.erb
Labels: PR: partially-approved

#9293 🐞 Hotfix Real time chat was broken
  app/javascript/chat/chat.jsx
Labels: PR: partially-approved

#9299 Fix TypeError: userData is null in blockButton.js
  app/javascript/profileDropdown/blockButton.js
Labels: PR: partially-approved

#9298 Fix TypeError: userData is null in initializeOnboardingTaskCard.js
  app/assets/javascripts/initializers/initializeOnboardingTaskCard.js
Labels: PR: unreviewed

#9297 Fix TypeError: null is not an object in initializeArticleReactions.js
  app/assets/javascripts/initializers/initializeArticleReactions.js
Labels: PR: partially-approved

#9302 Routine Rubocop fixes
  .rubocop.yml
  .rubocop_todo.yml
  app/controllers/organizations_controller.rb
  app/labor/mailchimp_bot.rb
  app/lib/reverse_markdown/converters/custom_text.rb
  app/models/message.rb
  app/models/tag.rb
  app/services/exporter/articles.rb
  app/services/exporter/comments.rb
  app/services/notifications/tag_adjustment_notification/send.rb
  app/services/suggester/users/recent.rb
  config.ru
  package.json
Labels: PR: partially-approved

#9304 Rubocop: activate Layout/ClassStructure
  .rubocop.yml
  app/controllers/api/v0/articles_controller.rb
  app/controllers/api/v0/comments_controller.rb
  app/controllers/api/v0/followers_controller.rb
  app/controllers/api/v0/listings_controller.rb
  app/controllers/api/v0/tags_controller.rb
  app/controllers/api/v0/users_controller.rb
  app/controllers/api/v0/videos_controller.rb
  app/controllers/api/v0/webhooks_controller.rb
  app/controllers/chat_channels_controller.rb
  app/controllers/followings_controller.rb
  app/controllers/internal/listings_controller.rb
  app/controllers/tags_controller.rb
  app/labor/markdown_traverser.rb
  app/models/reaction.rb
  app/models/tag.rb
  app/view_objects/articles/social_image.rb
Labels: PR: partially-approved

#9247 Change Label Follow Weight Scale for Tags in Dashboard
  app/views/dashboards/following_tags.html.erb
Labels: PR: partially-approved

#9306 Fix TypeError: Cannot set property 'innerHTML' of null
  app/views/articles/_search.html.erb
Labels: PR: unreviewed

#9251 Make sidebar sponsor headline configurable
  app/controllers/internal/configs_controller.rb
  app/models/site_config.rb
  app/views/articles/_sidebar.html.erb
  app/views/internal/configs/show.html.erb
  spec/requests/internal/configs_spec.rb
Labels: PR: partially-approved

#8695 Create profile image generator
  app/services/users/profile_image_generator.rb
  spec/services/users/profile_image_generator_spec.rb
Labels: PR: unreviewed

#8995 [ModCenter] Fix "FlagUser" Modal functionality
  app/controllers/moderations_controller.rb
  app/javascript/modCenter/__tests__/moderationArticles.test.jsx
  app/javascript/modCenter/moderationArticles.jsx
  app/javascript/modCenter/singleArticle/__tests__/singleArticle.test.jsx
  app/javascript/modCenter/singleArticle/index.jsx
  app/javascript/packs/articleModerationTools.js
  app/javascript/packs/flagUserModal.js
  app/javascript/packs/flagUserModal.jsx
  app/views/articles/show.html.erb
  app/views/moderations/index.html.erb
Labels: PR: unreviewed

#9285 Add local_date helper to handle dates with respect of user timezone
  app/assets/javascripts/initializePage.js
  app/assets/javascripts/initializers/initializeDateTimeHelpers.js
  app/helpers/date_helper.rb
  app/views/articles/_user_metadata.html.erb
  app/views/articles/show.html.erb
  spec/helpers/date_helper_spec.rb
  spec/system/articles/user_visits_an_article_spec.rb
Labels: PR: unreviewed

#9172 Restrict tags input regex
  app/javascript/article-form/components/TagsField.jsx
  app/javascript/listings/listingForm.jsx
  app/javascript/shared/components/tags.jsx
Labels: PR: reviewed-changes-requested

#8945 🚀 Feature: Chat channel membership manager component
  SECURITY.md
  app/assets/stylesheets/chat.scss
  app/controllers/chat_channel_memberships_controller.rb
  app/helpers/chat_channel_membership_helper.rb
  app/javascript/chat/ChatChannelSettings/ActiveMembershipsSection.jsx
  app/javascript/chat/ChatChannelSettings/ChatChannelMembershipSection.jsx
  app/javascript/chat/ChatChannelSettings/ChatChannelSettings.jsx
  app/javascript/chat/ChatChannelSettings/ChatChannelSettingsSection.jsx
  app/javascript/chat/ChatChannelSettings/InviteForm.jsx
  app/javascript/chat/ChatChannelSettings/LeaveMembershipSection.jsx
  app/javascript/chat/ChatChannelSettings/Membership.jsx
  app/javascript/chat/ChatChannelSettings/MembershipManager/InvitationLinkManager.jsx
  app/javascript/chat/ChatChannelSettings/MembershipManager/ManageActiveMembership.jsx
  app/javascript/chat/ChatChannelSettings/MembershipManager/Membership.jsx
  app/javascript/chat/ChatChannelSettings/MembershipManager/MembershipSection.jsx
  app/javascript/chat/ChatChannelSettings/ModFaqSection.jsx
  app/javascript/chat/ChatChannelSettings/ModSection.jsx
  app/javascript/chat/ChatChannelSettings/PendingMembershipSection.jsx
  app/javascript/chat/ChatChannelSettings/PersonalSetting.jsx
  app/javascript/chat/ChatChannelSettings/RequestedMembershipSection.jsx
  app/javascript/chat/ChatChannelSettings/SettingsForm.jsx
  app/javascript/chat/__tests__/ManageActiveMembership.test.jsx
  app/javascript/chat/__tests__/Membership.test.jsx
  app/javascript/chat/__tests__/chatChannelSettingActions.test.js
  app/javascript/chat/__tests__/invitationLinkManager.test.jsx
  app/javascript/chat/__tests__/leaveMembershipSection.test.jsx
  app/javascript/chat/__tests__/membership.test.jsx
  app/javascript/chat/actions/chat_channel_setting_actions.js
  app/javascript/chat/chat.jsx
  app/javascript/chat/content.jsx
  app/javascript/common-prop-types/membership-prop-type.js
  app/javascript/utilities/validateAndroidNative.js
  app/policies/chat_channel_policy.rb
  app/presenters/chat_channel_detail_presenter.rb
  app/presenters/membership_user_presenter.rb
  app/views/chat_channel_memberships/chat_channel_info.json.jbuilder
  app/views/chat_channel_memberships/join_channel_invitation.html.erb
  config/fastly/snippets/safe_params_list.vcl
  config/routes.rb
  spec/requests/chat_channel_memberships_spec.rb
Labels: PR: unreviewed, tech: fullstack

#9300 Introduce domain model for campaigns
  app/controllers/stories_controller.rb
  app/decorators/campaign_decorator.rb
  app/models/campaign.rb
  app/views/articles/_sidebar_additional.html.erb
  app/views/articles/_sidebar_campaign.html.erb
  app/views/social_previews/articles/shecoded.html.erb
  spec/requests/stories_index_spec.rb
Labels: PR: draft

#9303 Native bridge video support
  app/assets/javascripts/initializePage.js
  app/assets/javascripts/initializers/initializeVideoPlayback.js
  app/assets/stylesheets/minimal.scss
  app/assets/stylesheets/video-player.scss
  app/decorators/article_decorator.rb
  app/views/articles/_video_player.html.erb
  spec/decorators/article_decorator_spec.rb
Labels: PR: unreviewed

#9401 Change from presence to private pusher channels
  app/controllers/pusher_controller.rb
  app/javascript/chat/chat.jsx
  app/models/chat_channel.rb
Labels: area: connect

#8845 Unflake system user_settings_response_templates_spec.rb
  spec/system/user/user_settings_response_templates_spec.rb
Labels: PR: draft

#9305 🚀 Feature: Chat channel request manager
  app/assets/images/users.svg
  app/assets/stylesheets/chat.scss
  app/controllers/chat_channel_memberships_controller.rb
  app/helpers/chat_channel_memberships_helper.rb
  app/javascript/chat/RequestManager/ChannelRequestSection.jsx
  app/javascript/chat/RequestManager/HeaderSection.jsx
  app/javascript/chat/RequestManager/PersonalInvitationListItem.jsx
  app/javascript/chat/RequestManager/PersonalInvitationSection.jsx
  app/javascript/chat/RequestManager/RequestListItem.jsx
  app/javascript/chat/RequestManager/RequestManager.jsx
  app/javascript/chat/__tests__/PersonalInvitationListItem.test.jsx
  app/javascript/chat/__tests__/PersonalInvitationSection.test.jsx
  app/javascript/chat/__tests__/RequestListItem.test.jsx
  app/javascript/chat/__tests__/channelRequestSection.test.jsx
  app/javascript/chat/__tests__/requestManager.test.jsx
  app/javascript/chat/actions/actions.js
  app/javascript/chat/actions/requestActions.js
  app/javascript/chat/chat.jsx
  app/javascript/chat/content.jsx
  app/javascript/chat/requestManager.jsx
  app/labor/markdown_parser.rb
  app/models/chat_channel_membership.rb
  app/policies/chat_channel_membership_policy.rb
  app/views/chat_channel_memberships/request_details.json.jbuilder
  config/routes.rb
  spec/labor/markdown_parser_spec.rb
  spec/requests/chat_channel_memberships_spec.rb
  spec/requests/shells_spec.rb
Labels: PR: unreviewed

#9235 Ability for admins to remove user from internal chat channels
  app/controllers/internal/chat_channels_controller.rb
  app/models/chat_channel.rb
  app/views/internal/chat_channels/index.html.erb
  config/routes.rb
  spec/requests/internal/chat_channel_spec.rb
Labels: PR: partially-approved

#9272 Bug Fix: Article Posted Date and Author Card Posted Date do not match
  app/decorators/article_decorator.rb
  app/views/articles/_about_author.html.erb
  app/views/articles/show.html.erb
  spec/decorators/article_decorator_spec.rb
  spec/system/articles/user_visits_an_article_spec.rb
Labels: PR: unreviewed

#9044 Fix archived readinglist reactions affecting count
  app/controllers/reactions_controller.rb
  app/labor/reading_list.rb
  spec/requests/reactions_spec.rb
Labels: PR: partially-approved, action: post deployment

#9369 Update `<ImageUploader />` class component to use hooks
  app/javascript/article-form/components/ImageUploader.jsx
Labels: tech: javascript

#9563 Make <Modal /> component more accessible
  app/javascript/crayons/Modal/Modal.jsx
  app/javascript/crayons/Modal/__tests__/Modal.test.jsx
Labels: accessibility, tech: html/css

#9349 Listings redesign
  app/assets/stylesheets/crayons.scss
  app/assets/stylesheets/listings.scss
  app/assets/stylesheets/views/listings.scss
  app/javascript/listings/__tests__/AllListings.test.jsx
  app/javascript/listings/__tests__/ListingFiltersCategories.test.jsx
  app/javascript/listings/__tests__/MessageModal.test.jsx
  app/javascript/listings/__tests__/NextPageButton.test.jsx
  app/javascript/listings/__tests__/SingleListing.test.jsx
  app/javascript/listings/components/AllListings.jsx
  app/javascript/listings/components/CategoryLinks.jsx
  app/javascript/listings/components/CategoryLinksMobile.jsx
  app/javascript/listings/components/ClearQueryButton.jsx
  app/javascript/listings/components/ListingFilters.jsx
  app/javascript/listings/components/ListingFiltersCategories.jsx
  app/javascript/listings/components/ListingFiltersTags.jsx
  app/javascript/listings/components/MessageModal.jsx
  app/javascript/listings/components/Modal.jsx
  app/javascript/listings/components/ModalBackground.jsx
  app/javascript/listings/components/NextPageButton.jsx
  app/javascript/listings/components/SelectedTags.jsx
  app/javascript/listings/listings.jsx
  app/javascript/listings/singleListing/AuthorInfo.jsx
  app/javascript/listings/singleListing/DropdownMenu.jsx
  app/javascript/listings/singleListing/Header.jsx
  app/javascript/listings/singleListing/SingleListing.jsx
  app/javascript/listings/singleListing/TagLinks.jsx
  app/javascript/listings/singleListing/index.jsx
  app/javascript/listings/utils.js
  app/views/listings/index.html.erb
  spec/requests/listings_spec.rb
Labels: Crayons, area: listings

#9557 Search: replace replaceState with pushState to fix the back button
  app/views/articles/_search.html.erb
Labels: PR: partially-approved

#9579 Remove UserOptionalField
  app/models/user.rb
  app/models/user_optional_field.rb
  db/migrate/20200731033002_drop_user_optional_fields.rb
  db/schema.rb
  spec/factories/user_optional_fields.rb
  spec/factories/users.rb
  spec/models/user_optional_field_spec.rb
  spec/models/user_spec.rb
Labels: PR: partially-approved

#9504 Update modal padding to improve visual balance
  app/assets/stylesheets/components/modals.scss
  app/assets/stylesheets/moderators.scss
  app/javascript/packs/flagUserModal.jsx
Labels: Crayons, Forem team, PR: partially-approved, PR: unreviewed, tech: html/css

#9584 Prevent signing up with no email
  app/models/user.rb
  spec/models/user_spec.rb
  spec/requests/user/user_destroy_spec.rb
  spec/services/users/estimate_default_language_spec.rb
Labels: PR: partially-approved

#9582 Award badges asynchronously in internal
  app/controllers/internal/badges_controller.rb
  app/workers/badge_achievements/badge_award_worker.rb
  spec/requests/internal/badges_spec.rb
  spec/system/internal/admin_awards_badges_spec.rb
  spec/workers/badge_achievements/badge_award_worker_spec.rb
Labels: PR: unreviewed
