Repository forem/forem, pull requests merged in 2021-02, with the labels that each got.

#12496 Optimization:Add Index to collection_id on Articles
  db/migrate/20210131000458_add_index_to_articles_collection_id.rb
  db/schema.rb
Labels: PR: partially-approved

#12500 Optimization: Set ForemInstance.deployed_at Locally to Better Mirror Production
  app/models/forem_instance.rb
  spec/models/forem_instance_spec.rb
Labels: PR: partially-approved

#12495 Remove Hacktoberfest Badge Rake Task
  lib/tasks/temporary/hacktoberfest_badges.rake
Labels: PR: partially-approved

#12516 Add Message to the postgres.db_table_size dataset on Datadog
  app/workers/metrics/record_data_counts_worker.rb
Labels: PR: reviewed-approved

#12517 override disabled for comment like use case
  app/assets/stylesheets/views/article.scss
Labels: PR: reviewed-approved

#12482 Ignore feed_admin_publish_permission column
  app/models/user.rb
Labels: PR: reviewed-approved

#12529 Remove flakey failing test + code on Forem Instance
  app/views/admin/admin_portals/index.html.erb
  spec/requests/admin/admin_portals_spec.rb
Labels: PR: partially-approved

#12534 Fix typo for buffer updates
  app/controllers/admin/articles_controller.rb
Labels: PR: reviewed-approved

#12518 feature added : add-discussion-length-in-brackets #12324
  app/assets/javascripts/initializers/initializeCommentsPage.js.erb
  app/views/articles/_full_comment_area.html.erb
Labels: PR: reviewed-approved

#12424 Add ability to re-run a data script from the the data update script page
  app/assets/stylesheets/admin.scss
  app/controllers/admin/data_update_scripts_controller.rb
  app/javascript/admin/__tests__/controllers/data_update_script_controller.test.js
  app/javascript/admin/controllers/data_update_script_controller.js
  app/models/data_update_script.rb
  app/views/admin/data_update_scripts/index.html.erb
  app/workers/data_update_worker.rb
  config/routes.rb
  spec/requests/admin/data_update_scripts_spec.rb
  spec/workers/data_update_worker_spec.rb
Labels: PR: partially-approved

#12479 Don't redirect to /serviceworker.js on sign in.
  app/controllers/registrations_controller.rb
Labels: PR: partially-approved

#12541 remove default import for onboarding
  app/javascript/packs/Onboarding.jsx
Labels: PR: reviewed-approved, merge by any core

#12543 Stimulus controllers needed to be default exports.
  app/javascript/admin/__tests__/controllers/article_controller.test.js
  app/javascript/admin/__tests__/controllers/buffer_controller.test.js
  app/javascript/admin/__tests__/controllers/config_controller.test.js
  app/javascript/admin/__tests__/controllers/data_update_script_controller.test.js
  app/javascript/admin/controllers/article_controller.js
  app/javascript/admin/controllers/buffer_controller.js
  app/javascript/admin/controllers/config_controller.js
  app/javascript/admin/controllers/data_update_script_controller.js
  app/javascript/admin/controllers/image_upload_controller.js
  app/javascript/admin/controllers/modal_controller.js
  app/javascript/admin/controllers/reaction_controller.js
Labels: PR: reviewed-approved, area: admin, merge by any core, tech: frontend

#12555 Change counter value
  app/javascript/admin/controllers/data_update_script_controller.js
Labels: PR: partially-approved

#12530 Routine rubocop fixes
  .rubocop.yml
  app/controllers/stories_controller.rb
  config/initializers/cors.rb
  spec/requests/admin/admin_portals_spec.rb
  spec/requests/api/v0/articles_spec.rb
  spec/services/articles/feeds/basic_spec.rb
  spec/services/articles/feeds/large_forem_experimental_spec.rb
Labels: PR: unreviewed

#12520 Optimization:Throttle Tag Index Endpoints
  config/initializers/rack/attack.rb
  spec/initializers/rack/attack_spec.rb
Labels: PR: reviewed-approved

#12480 Fix tag alias problems
  app/controllers/admin/tags_controller.rb
  app/workers/tags/alias_retag_worker.rb
  spec/requests/admin/tags_spec.rb
Labels: PR: reviewed-approved, merge by any core

#10887 Refactoring SidebarWidget and sidebarUser
  app/javascript/sidebar-widget/SidebarWidget.jsx
  app/javascript/sidebar-widget/sidebarUser.jsx
Labels: PR: unreviewed

#12559 Provide default authentication providers in seed.rb
  db/seeds.rb
Labels: PR: partially-approved

#12557 Email confirmation to abuse reports
  app/controllers/feedback_messages_controller.rb
  app/mailers/notify_mailer.rb
  app/views/mailers/notify_mailer/feedback_response_email.html.erb
  app/views/mailers/notify_mailer/feedback_response_email.text.erb
  spec/mailers/notify_mailer_spec.rb
  spec/requests/feedback_messages_spec.rb
Labels: PR: reviewed-approved

#12539 Cypress tests for `/admin/config` Authentication Section
  app/views/admin/configs/show.html.erb
  bin/e2e
  bin/e2e-setup
  cypress/fixtures/users/adminUser.json
  cypress/integration/adminFlows/config/authenticationSection.spec.js
  cypress/support/commands.js
Labels: PR: partially-approved, merge by any core

#12560 Don't allow invites to users who are already registered
  app/controllers/admin/invitations_controller.rb
  spec/requests/admin/invitations_spec.rb
Labels: PR: reviewed-approved

#12558 Update verbiage around connect invitations
  app/javascript/chat/RequestManager/RequestManager.jsx
Labels: PR: reviewed-approved

#12502 Remove language settings
  Gemfile
  Gemfile.lock
  app/controllers/stories_controller.rb
  app/controllers/users_controller.rb
  app/models/article.rb
  app/models/languages.rb
  app/models/user.rb
  app/serializers/search/article_serializer.rb
  app/services/articles/detect_language.rb
  app/services/articles/feeds/large_forem_experimental.rb
  app/services/exporter/articles.rb
  app/services/users/estimate_default_language.rb
  app/views/stories/feeds/show.json.jbuilder
  app/views/users/_customization.html.erb
  app/views/users/_language_settings.html.erb
  app/workers/users/estimate_default_language_worker.rb
  config/elasticsearch/mappings/feed_content.json
  docs/backend/internationalization.md
  lib/data_update_scripts/20200805171911_clean_up_language_settings.rb
  spec/factories/articles.rb
  spec/models/article_spec.rb
  spec/models/user_spec.rb
  spec/requests/user/user_settings_spec.rb
  spec/services/articles/detect_language_spec.rb
  spec/services/articles/feeds/large_forem_experimental_spec.rb
  spec/services/exporter/articles_spec.rb
  spec/services/users/estimate_default_language_spec.rb
  spec/workers/users/estimate_default_language_worker_spec.rb
  vendor/cache/cld-0.8.0.gem
Labels: PR: partially-approved

#11743 Text styles
  app/assets/stylesheets/base/typography.scss
  app/javascript/article-form/components/Preview.jsx
  app/javascript/article-form/components/Title.jsx
  app/javascript/crayons/typography/__stories__/typography.md
  app/views/articles/_v2_form.html.erb
  app/views/articles/show.html.erb
  app/views/pages/crayons.html.erb
Labels: PR: reviewed-approved, area: articles

#12501 ✨ Add link to existing username in uniqueness validation error message
  app/models/user.rb
  spec/models/user_spec.rb
Labels: PR: partially-approved

#12563 Add a tip for the SKIP_SERVICEWORKERS env variable
  docs/frontend/tips.md
Labels: PR: partially-approved

#12483 Remove feed admin publish permission
  app/policies/user_policy.rb
  app/views/admin/articles/_individual_article.html.erb
  app/views/admin/articles/rss_articles.html.erb
  db/migrate/20210129074823_remove_feed_admin_publish_permission_from_users.rb
  db/schema.rb
Labels: PR: partially-approved

#12568 Data Update Scripts: Use filename on error messages instead of ID's
  app/javascript/admin/__tests__/controllers/data_update_script_controller.test.js
  app/javascript/admin/controllers/data_update_script_controller.js
  app/views/admin/data_update_scripts/index.html.erb
Labels: PR: partially-approved

#12388 Add icon uploader in admin navigation links
  app/javascript/admin/controllers/svg_icon_upload_controller.js
  app/views/admin/navigation_links/_form.html.erb
Labels: PR: partially-approved, area: admin

#12570 fix typo in nav links form
  app/views/admin/navigation_links/_form.html.erb
Labels: PR: reviewed-approved

#12537 Don't update last_buffered timestamp when creating a suggested tweet
  app/controllers/admin/invitations_controller.rb
  app/controllers/buffer_updates_controller.rb
Labels: PR: unreviewed

#10212 Add paste image
  app/javascript/article-form/components/EditorBody.jsx
  app/javascript/article-form/components/__tests__/pasteImageHelpers.test.jsx
  app/javascript/article-form/components/pasteImageHelpers.js
  app/javascript/utilities/__tests__/pasteImage.test.js
  app/javascript/utilities/pasteImage.js
Labels: PR: partially-approved, area: publishing experience, tech: frontend

#12574 Add `has_many: articles` to Tag model
  app/models/tag.rb
Labels: PR: reviewed-approved

#12576 /new form title fix font font-size
  app/assets/stylesheets/base/typography.scss
  app/javascript/article-form/components/Title.jsx
  app/views/articles/_v2_form.html.erb
  app/views/articles/show.html.erb
Labels: PR: partially-approved, area: publishing experience, tech: frontend

#12308 Declare winner in feed_top_articles_query test
  app/models/comment.rb
  app/models/page_view.rb
  app/services/articles/feeds/large_forem_experimental.rb
  app/workers/users/record_field_test_event_worker.rb
  config/field_test.yml
  spec/rails_helper.rb
  spec/requests/comments_spec.rb
  spec/requests/page_views_spec.rb
  spec/services/articles/feeds/large_forem_experimental_spec.rb
  spec/workers/users/record_field_test_event_worker_spec.rb
Labels: PR: partially-approved, merge by any core

#12577 Delete all notifications instead of destroying
  app/models/organization.rb
  spec/models/organization_spec.rb
Labels: PR: partially-approved

#12581 Optimize StoriesController's tagged article count
  app/controllers/stories_controller.rb
  spec/initializers/rack/attack_spec.rb
Labels: PR: partially-approved

#12564 Rubocop fixes
  spec/requests/admin/data_update_scripts_spec.rb
  spec/workers/data_update_worker_spec.rb
Labels: PR: reviewed-approved

#12580 Added yarn install to bin/e2e
  bin/e2e
Labels: PR: partially-approved, area: tests, merge by any core

#12585 Fix bug when trying to preview a blank draft article
  app/controllers/articles_controller.rb
  app/javascript/article-form/actions.js
  app/javascript/article-form/articleForm.jsx
Labels: PR: unreviewed, merge by any core

#12592 Remove feed_admin_publish_permission from ignored_columns
  app/models/user.rb
Labels: PR: reviewed-approved

#12579 Update article published Slack notifications
  app/models/site_config.rb
  app/services/slack/messengers/article_published.rb
  spec/services/slack/messengers/article_published_spec.rb
Labels: PR: partially-approved

#12584 Optimize published_articles_by_tag fetch speed
  app/services/articles/feeds/large_forem_experimental.rb
  spec/services/articles/feeds/large_forem_experimental_spec.rb
Labels: PR: reviewed-approved

#12459 Documentation for End to End Testing
  docs/.static/cypress-test-runner.png
  docs/tests/e2e-tests.md
  docs/tests/readme.md
Labels: PR: reviewed-approved

#12597 Added E2E tests for #12585.
  app/javascript/article-form/articleForm.jsx
  cypress/fixtures/users/articleEditorV1User.json
  cypress/fixtures/users/articleEditorV2User.json
  cypress/integration/publishingFlows/previewArticle.js
  spec/support/seeds/seeds_e2e.rb
Labels: PR: partially-approved, area: tests, merge by any core

#12567 Remove old code for feedback messages email to the reporter
  app/helpers/feedback_messages_helper.rb
  app/views/admin/feedback_messages/_feedback_message.html.erb
  spec/helpers/feedback_messages_helper_spec.rb
Labels: PR: partially-approved

#12573 Add Storybook as an option for PR documentation
  .github/PULL_REQUEST_TEMPLATE.md
Labels: PR: reviewed-approved

#12601 Fix incorrect datetime format
  app/views/articles/index.html.erb
Labels: PR: partially-approved

#12602 fix dropdown-menu not closing when click outside or click on a item on mobile
  app/javascript/topNavigation/utilities.js
Labels: PR: reviewed-approved

#12561 Fix a false positive test
  app/javascript/chat/__tests__/requestManager.test.jsx
Labels: PR: reviewed-approved

#12118 Simplify onboarding images and centralize config around primary/secondary logos
  app/controllers/admin/configs_controller.rb
  app/lib/constants/site_config.rb
  app/models/site_config.rb
  app/views/admin/configs/show.html.erb
  app/views/articles/tag_index.html.erb
  app/views/onboardings/_task_card.html.erb
  app/views/onboardings/show.html.erb
  spec/models/site_config_spec.rb
  spec/requests/admin/configs_spec.rb
  spec/requests/onboardings_spec.rb
Labels: PR: partially-approved

#11511 Fix broken Podcast liquid tag
  app/views/podcast_episodes/_liquid.html.erb
  app/views/podcast_episodes/_podcast_bar.html.erb
  app/views/podcast_episodes/show.html.erb
Labels: PR: partially-approved

#12614 Fix flakiness in Follows::UpdatePointsWorker
  spec/workers/follows/update_points_worker_spec.rb
Labels: PR: unreviewed

#12616 Replace liquid's hardcoded image path with #asset_path
  app/views/podcast_episodes/_liquid.html.erb
Labels: PR: partially-approved

#12617 Enable eslint in chat.jsx
  app/javascript/chat/chat.jsx
Labels: PR: partially-approved

#12615 Fix broken doc links
  docs/getting-started/config-env.md
  docs/installation/linux.md
  docs/installation/windows.md
  docs/readme.md
Labels: PR: unreviewed

#12626 Update Bundler to 2.2.9
  .travis.yml
  Gemfile.lock
Labels: PR: partially-approved

#12292 Navigation Items and Role access for Data Update Scripts
  README.md
  app/controllers/admin/data_update_scripts_controller.rb
  app/helpers/admin_helper.rb
  app/lib/constants/role.rb
  app/models/data_update_script.rb
  app/services/moderator/manage_activity_and_roles.rb
  app/views/admin/admin_portals/index.html.erb
  app/views/admin/shared/_navbar.html.erb
  app/views/layouts/admin.html.erb
  config/routes.rb
  lib/data_update_scripts/20210203104631_add_single_resource_admin_role_to_users_with_tech_admin.rb
  spec/lib/data_update_scripts/add_single_resource_admin_role_to_users_with_tech_admin_spec.rb
  spec/services/moderator/manage_activity_and_roles_spec.rb
Labels: PR: reviewed-approved, merge by any core

#12613 Replace redundant div with Fragment
  app/javascript/leftSidebar/TagsFollowed.jsx
  app/javascript/leftSidebar/__tests__/TagsFollowed.test.jsx
  app/javascript/packs/homePage.jsx
Labels: PR: partially-approved

#12628 Fix erroring data update script
  lib/data_update_scripts/20210203104631_add_single_resource_admin_role_to_users_with_tech_admin.rb
  lib/data_update_scripts/20210209185037_add_single_resource_role_to_tech_admins.rb
  spec/lib/data_update_scripts/add_single_resource_admin_role_to_users_with_tech_admin_spec.rb
  spec/lib/data_update_scripts/add_single_resource_role_to_tech_admins_spec.rb
Labels: PR: partially-approved

#12634 Ignore two Carrierwave CVEs
  .travis.yml
Labels: PR: partially-approved

#12644 Revert "fix dropdown-menu not closing when click outside or click on a item on mobile"
  app/javascript/topNavigation/utilities.js
Labels: PR: unreviewed

#12598 GitHub auth docs used the wrong url
  docs/backend/auth-github.md
Labels: PR: partially-approved

#12642 Remove unused podcast episode related code
  app/controllers/podcast_episodes_controller.rb
  app/views/podcast_episodes/edit.html.erb
  public/tinymcestyles.css
Labels: PR: partially-approved

#12630 Extract ChannelFilterButton from Chat.jsx
  app/javascript/chat/chat.jsx
  app/javascript/chat/components/ChannelFilterButton.jsx
Labels: PR: unreviewed

#12603 Update PR template with communicating changes section
  .github/PULL_REQUEST_TEMPLATE.md
Labels: PR: partially-approved

#12649 Revert "Bump husky from 4.3.8 to 5.0.9"
  .husky/.gitignore
  .husky/pre-commit
  package.json
  yarn.lock
Labels: PR: partially-approved

#12651 Update to Rails 6.0.3.5
  Gemfile.lock
  vendor/cache/actioncable-6.0.3.4.gem
  vendor/cache/actioncable-6.0.3.5.gem
  vendor/cache/actionmailbox-6.0.3.4.gem
  vendor/cache/actionmailbox-6.0.3.5.gem
  vendor/cache/actionmailer-6.0.3.4.gem
  vendor/cache/actionmailer-6.0.3.5.gem
  vendor/cache/actionpack-6.0.3.4.gem
  vendor/cache/actionpack-6.0.3.5.gem
  vendor/cache/actiontext-6.0.3.4.gem
  vendor/cache/actiontext-6.0.3.5.gem
  vendor/cache/actionview-6.0.3.4.gem
  vendor/cache/actionview-6.0.3.5.gem
  vendor/cache/activejob-6.0.3.4.gem
  vendor/cache/activejob-6.0.3.5.gem
  vendor/cache/activemodel-6.0.3.4.gem
  vendor/cache/activemodel-6.0.3.5.gem
  vendor/cache/activerecord-6.0.3.4.gem
  vendor/cache/activerecord-6.0.3.5.gem
  vendor/cache/activestorage-6.0.3.4.gem
  vendor/cache/activestorage-6.0.3.5.gem
  vendor/cache/activesupport-6.0.3.4.gem
  vendor/cache/activesupport-6.0.3.5.gem
  vendor/cache/rails-6.0.3.4.gem
  vendor/cache/rails-6.0.3.5.gem
  vendor/cache/railties-6.0.3.4.gem
  vendor/cache/railties-6.0.3.5.gem
Labels: PR: partially-approved, PR: unreviewed, merge by any core

#12503 Prevent suspended users from self-deleting and returning
  app/controllers/concerns/verify_setup_completed.rb
  app/controllers/omniauth_callbacks_controller.rb
  app/errors/authentication/errors.rb
  app/models/users/suspended_username.rb
  app/services/authentication/authenticator.rb
  app/services/authentication/errors.rb
  app/services/users/delete.rb
  db/migrate/20210201055410_create_users_suspended_usernames.rb
  db/schema.rb
  spec/factories/suspended_usernames.rb
  spec/models/users/suspended_username_spec.rb
  spec/services/users/delete_spec.rb
  spec/system/authentication/user_with_suspended_username_spec.rb
Labels: PR: reviewed-approved, merge by any core

#12632 Prevent exception in Tags::AliasRetagWorker
  app/workers/tags/alias_retag_worker.rb
Labels: PR: unreviewed

#12646 Add feature flags docs
  app/views/layouts/_footer.html.erb
  docs/.static/admin_feature_flags.png
  docs/technical-overview/compatibility.md
  docs/technical-overview/feature_flags.md
  docs/technical-overview/readme.md
Labels: PR: partially-approved

#12015 Fix profile field production display area functionality and remove SiteConfig.dev_to? hacks for better generalization
  app/assets/images/website.svg
  app/decorators/profile_decorator.rb
  app/models/profile.rb
  app/models/user.rb
  app/views/admin/profile_fields/index.html.erb
  app/views/users/_metadata.html.erb
  app/views/users/_sidebar.html.erb
  app/views/users/show.html.erb
  lib/data_update_scripts/20201223013903_set_proper_display_area_for_profile_fields.rb
  spec/lib/data_update_scripts/set_proper_display_area_for_profile_fields_spec.rb
  spec/requests/user/user_profile_spec.rb
  spec/services/profile_fields/import_from_csv_spec.rb
Labels: PR: partially-approved

#12665 Fix edge cases in profile field UI migration
  app/assets/images/git_lab.svg
  app/assets/images/linked_in.svg
  app/assets/images/stack_overflow.svg
  app/models/profile.rb
  lib/data_update_scripts/20210211164634_fix_profile_field_edge_cases.rb
  spec/lib/data_update_scripts/fix_profile_field_edge_cases_spec.rb
Labels: PR: partially-approved

#12669 Update Ruby Section and Add Additional Error
  docs/installation/mac.md
Labels: PR: reviewed-approved

#12677 Hero overflow fix
  app/views/layouts/application.html.erb
Labels: PR: reviewed-approved, tech: frontend

#12647 Add JSDoc comments to Chat components
  app/javascript/chat/components/ChannelButton.jsx
  app/javascript/chat/components/ChannelFilterButton.jsx
  app/javascript/chat/components/ChannelImage.jsx
  app/javascript/chat/components/CreateChatModal.jsx
Labels: PR: unreviewed

#12681 Move yarn install to after potential bundle check failure in bin/e2e
  bin/e2e
Labels: area: tests, merge by any core

#12542 Fixed twitter timeline display in comments preview
  app/assets/javascripts/initializers/initializeCommentPreview.js
  spec/system/comments/user_fills_out_comment_spec.rb
Labels: PR: partially-approved

#12668 Refactor:Change Image Article Upload Path to uploads/articles
  app/uploaders/article_image_uploader.rb
  spec/requests/image_uploads_spec.rb
  spec/uploaders/article_image_uploader_spec.rb
Labels: PR: reviewed-approved

#12661 Parenthesis consistency for add_role and remove_role
  app/controllers/chat_channels_controller.rb
  app/services/moderator/manage_activity_and_roles.rb
  docs/admin/readme.md
  docs/backend/roles.md
  spec/factories/users.rb
  spec/policies/comment_policy_spec.rb
  spec/requests/admin/tags/moderators_spec.rb
  spec/requests/admin/users_manage_spec.rb
  spec/requests/chat_channels_spec.rb
  spec/requests/moderations_spec.rb
  spec/requests/notifications_spec.rb
  spec/services/mailchimp/bot_spec.rb
  spec/services/moderator/manage_activity_and_roles_spec.rb
  spec/system/admin/admin_bans_or_warns_user_spec.rb
Labels: PR: reviewed-approved

#12685 Remove language columns
  app/models/article.rb
  app/models/user.rb
Labels: PR: partially-approved

#12625 CSS size reduce + cleanups.
  app/assets/stylesheets/base/layout.scss
  app/assets/stylesheets/components/avatars.scss
  app/assets/stylesheets/config/_generator.scss
  app/assets/stylesheets/config/_import.scss
  app/assets/stylesheets/crayons.scss
  app/assets/stylesheets/views/mod-actions.scss
  app/controllers/pages_controller.rb
  app/javascript/.storybook/preview.js
  app/javascript/actionsPanel/initializeActionsPanelToggle.js
  app/views/admin/navigation_links/_edit_navigation_link_modal.html.erb
  app/views/layouts/_asset_reconciliation.html.erb
  app/views/layouts/_styles.html.erb
  app/views/notifications/_badgeachievement.html.erb
  app/views/pages/crayons.html.erb
  bin/__tests__/generate-css-utility-classes-docs.test.js
  bin/generate-css-utility-classes-docs.js
  config/routes.rb
Labels: Crayons, PR: partially-approved, PR: unreviewed

#12703 Connect styles issues
  app/javascript/chat/chat.jsx
  app/javascript/chat/components/ChannelButton.jsx
Labels: PR: partially-approved, area: connect, tech: frontend

#12699 Drop language settings columns
  app/models/article.rb
  app/models/user.rb
  db/migrate/20210216023520_drop_language_columns.rb
  db/schema.rb
Labels: PR: partially-approved

#12696 Redirect users to sign up path after they self-delete their account
  app/controllers/users_controller.rb
  spec/requests/user/user_destroy_spec.rb
Labels: PR: partially-approved, merge by any core

#12582 Remove Roles via Admin
  app/controllers/admin/users_controller.rb
  app/views/admin/users/_activity.html.erb
  app/views/admin/users/_current_roles.html.erb
  app/views/admin/users/edit.html.erb
  config/routes.rb
  spec/requests/admin/users_manage_spec.rb
  spec/requests/admin/users_spec.rb
Labels: PR: unreviewed

#12652 Fix infinite redirect loop for articles
  app/controllers/stories_controller.rb
  spec/requests/articles/org_redirect_spec.rb
Labels: PR: partially-approved

#12686 Extract page view updates into workers
  app/controllers/page_views_controller.rb
  app/workers/articles/update_organic_page_views_worker.rb
  app/workers/articles/update_page_views_worker.rb
  spec/requests/page_views_spec.rb
Labels: PR: partially-approved

#12694 Provide skip links: Tweak skip link style, refactor main area ID
  app/assets/javascripts/initializers/initScrolling.js
  app/assets/javascripts/lib/pulltorefresh.js
  app/assets/stylesheets/components/header.scss
  app/javascript/packs/homePageFeedShortcuts.jsx
  app/views/articles/index.html.erb
  app/views/layouts/_top_bar.html.erb
  spec/system/articles/user_visits_articles_by_timeframe_spec.rb
Labels: PR: partially-approved

#12667 Fixing `gap` property for all occurrences of `flex` to work in Safari
  app/assets/javascripts/utilities/showUserAlertModal.js
  app/assets/stylesheets/admin.scss
  app/assets/stylesheets/components/buttons.scss
  app/assets/stylesheets/components/modals.scss
  app/assets/stylesheets/listings.scss
  app/assets/stylesheets/views/article.scss
  app/assets/stylesheets/views/signin.scss
  app/javascript/admin/adminModal.js
  app/javascript/listings/dashboard/rowElements/actionButtons.jsx
  app/views/admin/configs/_apple_auth_provider_settings.html.erb
  app/views/admin/configs/_auth_provider_settings.html.erb
  app/views/admin/configs/show.html.erb
  app/views/articles/tag_index.html.erb
  app/views/users/_comments_section.html.erb
  app/views/users/_extensions.html.erb
  app/views/users/_integrations.html.erb
  app/views/users/_notifications.html.erb
  app/views/users/_response_templates.html.erb
  app/views/users/_sidebar.html.erb
  app/views/users/confirm_destroy.html.erb
Labels: PR: partially-approved, tech: frontend

#12709 Change fetch to our request utility function.
  app/javascript/readingList/readingList.jsx
Labels: PR: partially-approved, merge by any core

#12717 Ghost textarea fixes
  app/assets/stylesheets/views/article-form.scss
  app/assets/stylesheets/views/comments.scss
  app/javascript/article-form/components/EditorBody.jsx
Labels: PR: partially-approved, merge by any core, tech: frontend

#12714 Update CarrierWave to 2.1.1
  .travis.yml
  Gemfile.lock
  spec/rails_helper.rb
  vendor/cache/carrierwave-2.1.0.gem
  vendor/cache/carrierwave-2.1.1.gem
  vendor/cache/i18n-1.8.8.gem
  vendor/cache/i18n-1.8.9.gem
  vendor/cache/ssrf_filter-1.0.7.gem
Labels: PR: partially-approved

#12723 Close hamburger menu on click
  app/assets/stylesheets/components/hamburger.scss
  app/javascript/packs/base.js
  app/javascript/topNavigation/__tests__/utilities.test.js
  app/javascript/topNavigation/utilities.js
Labels: PR: partially-approved, merge by any core, tech: frontend

#12710 Reading List 15 minute fixes to prepare for #11983
  app/javascript/readingList/readingList.jsx
  app/javascript/searchableItemList/searchableItemList.js
Labels: PR: partially-approved, merge by any core, tech: frontend

#12735 Removed bundle exec rake data_updates:run for E2E on CI
  .travis.yml
Labels: PR: partially-approved, area: tests

#12729 Remove asset reconciliation
  app/views/layouts/_asset_reconciliation.html.erb
  app/views/layouts/application.html.erb
  spec/requests/stories_index_spec.rb
Labels: PR: partially-approved

#12730 Prevent banned users from using API
  app/controllers/api/v0/api_controller.rb
  app/policies/api_secret_policy.rb
  app/services/users/delete_activity.rb
  spec/policies/api_secret_policy_spec.rb
  spec/requests/api/v0/articles_spec.rb
Labels: PR: partially-approved

#12728 Add data update script for backfilling usernames
  lib/data_update_scripts/20210218041143_backfill_usernames.rb
  spec/lib/data_update_scripts/backfill_usernames_spec.rb
Labels: PR: partially-approved

#12738 [15 mins fix] Title clipping on /new view for `prefers-reduced-motion: reduce` settings.
  app/assets/stylesheets/base/reset.scss
Labels: PR: partially-approved, area: publishing experience, bug, merge by any core, tech: frontend

#12491 Changing text from 'Create account' to 'Join' for smaller screens
  app/views/layouts/_top_bar.html.erb
Labels: PR: partially-approved, area: design, bug

#12753 Profile navigation menu dropdown fix in mobile
  app/javascript/topNavigation/utilities.js
Labels: PR: partially-approved, merge by any core

#12766 Specs for article collection update
  spec/requests/articles/articles_update_spec.rb
Labels: PR: partially-approved

#12747 Make sure skip link scroll accounts for sticky header
  app/assets/stylesheets/base/main.scss
Labels: PR: reviewed-approved

#12547 Routes: more modern and consistent syntax
  config/routes.rb
Labels: PR: partially-approved

#12750 Add flaky tags & retry in specs
  spec/rails_helper.rb
  spec/services/articles/suggest_spec.rb
  spec/system/articles/user_creates_an_article_spec.rb
  spec/system/podcasts/user_visits_podcast_episode_spec.rb
Labels: PR: reviewed-approved

#12724 Fix irregular comment count buttons
  app/assets/javascripts/utilities/buildArticleHTML.js
  app/views/articles/_single_story.html.erb
  spec/system/articles/user_visits_articles_by_tag_spec.rb
  spec/system/homepage/user_visits_homepage_articles_spec.rb
Labels: PR: partially-approved

#12757 Optimization:Sync Smaller Subset of Github Repos Hourly
  config/schedule.yml
Labels: PR: partially-approved

#12741 Add check constraint for users.username
  db/migrate/20210219043102_add_check_constraint_for_username.rb
  db/schema.rb
Labels: PR: partially-approved

#12769 Add skip links to readinglist, podcasts, and listings
  app/assets/javascripts/initializers/initScrolling.js
  app/javascript/listings/components/AllListings.jsx
  app/javascript/readingList/readingList.jsx
  app/views/podcast_episodes/index.html.erb
  spec/system/podcasts/user_visits_podcasts_root_page_spec.rb
Labels: PR: partially-approved

#12790 Make Skip to Content button hide higher up outside of view
  app/assets/stylesheets/components/header.scss
Labels: PR: partially-approved

#12796 Fix regression in Honeybadger.config.exceptions.ignore
  config/initializers/honeybadger.rb
  spec/initializers/honeybadger_spec.rb
Labels: PR: reviewed-approved

#12770 [15 Min. Fix] Update Default bg_color and text_color Hexes on Tag Edit Page
  app/views/tags/edit.html.erb
  spec/system/tags/user_updates_a_tag_spec.rb
Labels: PR: partially-approved

#11308 Database config #11273
  .env_sample
  .travis.yml
  config/database.yml
Labels: PR: unreviewed

#12795 Remove canonical_url from API Article Create/Update examples
  docs/api_v0.yml
Labels: PR: reviewed-approved

#12760 Update credit purchase button on submit
  app/views/credits/new.html.erb
Labels: PR: partially-approved, merge by any core

#12808 Added the @shared webpack alias to the project
  app/javascript/.eslintrc.js
  app/javascript/.storybook/main.js
  config/webpack/environment.js
  docs/frontend/webpacker.md
  jest.config.js
  jsconfig.json
Labels: PR: unreviewed, merge by any core

#12511 improve keyboard accessibility of modals 12427 10610
  app/assets/javascripts/initializers/initializeAllFollowButts.js
  app/assets/javascripts/initializers/initializeArticleReactions.js
  app/assets/javascripts/initializers/initializeCommentsPage.js.erb
  app/assets/javascripts/initializers/initializeReadingListIcons.js
  app/assets/javascripts/utilities/showLoginModal.js
  app/assets/javascripts/utilities/showModal.js
  app/assets/stylesheets/components/modals.scss
  app/assets/stylesheets/views/listings.scss
  app/assets/stylesheets/views/signup-modal.scss
  app/javascript/admin/controllers/modal_controller.js
  app/javascript/article-form/articleForm.jsx
  app/javascript/article-form/components/Help.jsx
  app/javascript/articles/Feed.jsx
  app/javascript/crayons/Modal/Modal.jsx
  app/javascript/crayons/Modal/__stories__/Modal.stories.jsx
  app/javascript/crayons/Modal/__stories__/modals.md
  app/javascript/crayons/Modal/__tests__/Modal.test.jsx
  app/javascript/listings/components/Modal.jsx
  app/javascript/listings/listings.jsx
  app/javascript/listings/utils.js
  app/javascript/onboarding/Onboarding.jsx
  app/javascript/onboarding/components/EmailPreferencesForm.jsx
  app/javascript/onboarding/components/FollowUsers.jsx
  app/javascript/packs/base.jsx
  app/javascript/packs/notificationSubscriptionHandler.js
  app/javascript/responseTemplates/responseTemplates.js
  app/javascript/shared/components/focusTrap.jsx
  app/liquid_tags/poll_tag.rb
  app/liquid_tags/user_subscription_tag.rb
  app/views/admin/navigation_links/_add_navigation_link_modal.html.erb
  app/views/admin/navigation_links/_edit_navigation_link_modal.html.erb
  app/views/admin/profile_fields/_add_group_modal.html.erb
  app/views/admin/profile_fields/_add_profile_field_modal.html.erb
  app/views/admin/profile_fields/_edit_group_modal.html.erb
  app/views/articles/_search.html.erb
  app/views/layouts/_signup_modal.html.erb
  cypress/integration/adminFlows/navigationLinks/navigationLinks.spec.js
  cypress/integration/listingFlows/viewListing.spec.js
  cypress/integration/loggedOutFlows/showLoginModal.spec.js
  spec/liquid_tags/user_subscription_tag_spec.rb
  spec/support/seeds/seeds_e2e.rb
Labels: PR: unreviewed

#12697 Add username to onboarding
  app/controllers/users_controller.rb
  app/javascript/onboarding/__tests__/Onboarding.test.jsx
  app/javascript/onboarding/components/ProfileForm.jsx
  app/javascript/onboarding/components/ProfileForm/TextInput.jsx
  app/javascript/onboarding/components/__tests__/ProfileForm.test.jsx
  spec/requests/users_onboarding_spec.rb
Labels: PR: partially-approved

#12816 Added the MDX extension for VS Code.
  .vscode/extensions.json
Labels: PR: partially-approved, area: developer experience, merge by any core

#12791 Don't sub mailchimp if mailchimp is not enabled
  app/models/user.rb
  spec/models/user_spec.rb
Labels: PR: partially-approved, actual_size:XS, area: email, bug, merge by any core

#12819 Grammar fixes on /admin/config
  app/views/admin/configs/show.html.erb
Labels: PR: partially-approved

#12823 Return Additional Data Needed for Autocomplete
  app/services/search/user.rb
  app/views/service_worker/index.js.erb
  spec/requests/search_spec.rb
  spec/services/search/user_spec.rb
Labels: PR: partially-approved

#12809 Created the <MediaQuery /> component and useMediaQuery hook.
  app/assets/stylesheets/config/_import.scss
  app/javascript/readingList/components/__stories__/MediaQuery.stories.mdx
  app/javascript/shared/components/MediaQuery.jsx
  app/javascript/shared/components/__tests__/MediaQuery.test.jsx
  app/javascript/shared/components/__tests__/useMediaQuery.test.js
  app/javascript/shared/components/useMediaQuery.js
Labels: Crayons, PR: partially-approved, PR: unreviewed, merge by any core

#12824 Fix typo
  app/javascript/onboarding/components/ProfileForm.jsx
Labels: PR: partially-approved

#12825 Added react aliases in Storybook webpack configuration
  app/javascript/.storybook/main.js
Labels: PR: partially-approved, merge by any core

#12376 Try yarn instead over npm for storybook deploys
  app/javascript/netlify.toml
  docs/netlify.toml
Labels: PR: partially-approved

#12826 Add search/feed_content to robots.text
  app/views/pages/robots.text.erb
Labels: PR: reviewed-approved

#12827 Fix flaky comment timestamp spec
  spec/system/user/view_user_index_spec.rb
Labels: PR: partially-approved

#12832 Resourcify Badge Achievements
  app/lib/constants/role.rb
  app/models/badge_achievement.rb
  spec/requests/admin/badge_achievements_spec.rb
Labels: PR: partially-approved
