Repository forem/forem, pull requests merged in 2021-12, with the labels that each got.

#15543 markdown toolbar: refactor formatting insert to allow for undo queue
  app/javascript/crayons/MarkdownToolbar/MarkdownToolbar.jsx
  app/javascript/crayons/MarkdownToolbar/__tests__/markdownSyntaxFormatters.test.js
  app/javascript/crayons/MarkdownToolbar/markdownSyntaxFormatters.js
Labels: PR: partially-approved

#15596 Remove z-index from liquid tags
  app/assets/stylesheets/ltags/GithubReadmeTag.scss
  app/assets/stylesheets/ltags/GithubTag.scss
  app/assets/stylesheets/ltags/TwitterTimelineTag.scss
Labels: PR: unreviewed

#15610 Refactoring spec
  spec/system/articles/user_visits_articles_by_timeframe_spec.rb
Labels: PR: reviewed-approved, merge by any core

#15609 Avoid email reassignment when connecting OAuth provider
  app/services/authentication/authenticator.rb
  spec/services/authentication/authenticator_spec.rb
Labels: PR: partially-approved, merge by any core

#15619 Remove Italics from Community Name Field on Creator Settings Form
  app/views/admin/creator_settings/_form.html.erb
Labels: PR: partially-approved

#15621 Fixed test that breaks once upgraded to Node 16.
  app/javascript/shared/components/__tests__/tags.test.jsx
Labels: area: tests, PR: partially-approved, merge by any core

#15622 Revert "Bump @storybook/builder-webpack5 from 6.3.12 to 6.4.1 (#15533)"
  package.json
  yarn.lock
Labels: PR: partially-approved, merge by any core

#15614 Remove some README badges
  README.md
Labels: PR: partially-approved

#15623 quote localized strings in credits/purchase embedded script
  app/views/credits/new.html.erb
  spec/views/credits/new.html.erb_spec.rb
Labels: PR: partially-approved

#15131 views/shared/authentication etc i18n
  app/views/shared/_auth_widget.html.erb
  app/views/shared/_authentication_actions.html.erb
  app/views/shared/_authentication_description.html.erb
  app/views/shared/_authentication_title.html.erb
  app/views/shared/authentication/_email_login_form.html.erb
  app/views/shared/authentication/_email_registration_form.html.erb
  app/views/shared/authentication/_forem_creator_signup.html.erb
  app/views/shared/authentication/_initial_account_wizard.html.erb
  app/views/shared/authentication/_providers_registration_form.html.erb
  config/locales/views/auth/en.yml
  config/locales/views/auth/fr.yml
  spec/requests/registrations_spec.rb
Labels: PR: partially-approved

#15612 Extracting Article.featured scope
  app/controllers/admin/articles_controller.rb
  app/controllers/articles_controller.rb
  app/models/article.rb
  app/services/article_api_index_service.rb
  app/services/articles/feeds/find_featured_story.rb
  app/services/email_digest_article_collector.rb
  app/workers/reactions/bust_homepage_cache_worker.rb
Labels: PR: reviewed-approved, merge by any core

#15626 Block more bots
  config/fastly/snippets/bad_bot_detection.vcl
Labels: PR: reviewed-approved

#15628 Replacing `User#warned` with `User#warned?`
  app/models/user.rb
  app/services/moderator/manage_activity_and_roles.rb
  app/services/slack/messengers/comment_user_warned.rb
  app/views/admin/users/edit.html.erb
  spec/services/moderator/manage_activity_and_roles_spec.rb
  spec/system/admin/admin_bans_or_warns_user_spec.rb
Labels: PR: partially-approved

#15625 Refactoring to use scope
  app/models/organization_membership.rb
  app/models/user.rb
Labels: PR: partially-approved

#15611 Fixing logic error for feed
  app/services/articles/feeds/weighted_query_strategy.rb
  spec/services/articles/feeds/weighted_query_strategy_spec.rb
Labels: PR: reviewed-approved, merge by any core

#15632 Renaming method to reduce surprise
  app/controllers/notifications_controller.rb
  app/models/user.rb
  config/initializers/doorkeeper.rb
Labels: PR: partially-approved

#15550 First Few Unified Embed implementations (Liquid Tags)
  app/liquid_tags/asciinema_tag.rb
  app/liquid_tags/codepen_tag.rb
  app/liquid_tags/gist_tag.rb
  app/liquid_tags/js_fiddle_tag.rb
  app/liquid_tags/next_tech_tag.rb
  app/liquid_tags/reddit_tag.rb
  app/liquid_tags/soundcloud_tag.rb
  app/liquid_tags/twitter_timeline_tag.rb
  app/liquid_tags/unified_embed.rb
  app/liquid_tags/unified_embed_tag.rb
  app/liquid_tags/wikipedia_tag.rb
  app/liquid_tags/youtube_tag.rb
  spec/liquid_tags/unified_embed_spec.rb
  spec/liquid_tags/unified_embed_tag_spec.rb
Labels: PR: unreviewed

#15600 Factoring code to define Article.approved
  app/controllers/sidebars_controller.rb
  app/controllers/stories/tagged_articles_controller.rb
  app/controllers/stories_controller.rb
  app/models/article.rb
  app/services/article_api_index_service.rb
Labels: PR: partially-approved, merge by any core

#15631 Fixed lint:frontend npm script
  app/javascript/.eslintrc.js
  app/javascript/articles/components/CommentsList.jsx
  app/javascript/listings/components/Categories.jsx
  app/javascript/listings/components/CategoryLinks.jsx
  app/javascript/listings/components/CategoryLinksMobile.jsx
  app/javascript/listings/dashboard/rowElements/tags.jsx
  app/javascript/onboarding/components/FollowUsers.jsx
  app/javascript/podcasts/__stories__/TodaysPodcasts.stories.jsx
  app/javascript/utilities/color/WCAGColorContrast.js
  package.json
Labels: PR: partially-approved, merge by any core, tech: javascript

#15499 Forem Creation: Logo Upload & Resizing
  app/assets/stylesheets/base/main.scss
  app/controllers/admin/creator_settings_controller.rb
  app/models/settings/general.rb
  app/uploaders/base_uploader.rb
  app/uploaders/logo_uploader.rb
  app/views/admin/creator_settings/_form.html.erb
  app/views/admin/creator_settings/new.html.erb
  app/views/layouts/_logo.html.erb
  cypress/integration/creatorOnboardingFlows/creatorSettings.spec.js
  spec/uploaders/logo_uploader_spec.rb
Labels: PR: unreviewed, type: forem creation, merge by any core, tech: fullstack

#15643 Revert SVG Logo to using logo_svg
  app/views/layouts/_logo.html.erb
Labels: PR: partially-approved

#15647 Remove max height on logo
  app/assets/stylesheets/base/main.scss
Labels: PR: partially-approved

#15650 announce image upload success via aria live
  app/javascript/article-form/components/ImageUploader.jsx
Labels: PR: partially-approved, merge by any core

#15639 Deprecating User#trusted in favor of User#trusted?
  app/controllers/async_info_controller.rb
  app/models/reaction.rb
  app/models/response_template.rb
  app/models/user.rb
  app/services/mailchimp/bot.rb
  app/services/moderator/manage_activity_and_roles.rb
  app/services/re_captcha/check_enabled.rb
  app/views/admin/users/edit.html.erb
  app/views/users/_notifications.html.erb
Labels: PR: partially-approved

#15641 Refactoring to use StringAttributeCleaner
  app/lib/string_attribute_cleaner.rb
  app/models/article.rb
  app/models/user.rb
  spec/lib/string_attribute_cleaner_spec.rb
Labels: PR: reviewed-approved

#15636 Remove beta tag from mobile notification settings
  app/views/users/_notifications.html.erb
Labels: PR: reviewed-approved

#15634 Ensure COC and TOS Links Open on the Creator Settings Form
  app/javascript/packs/onboardingRedirectCheck.jsx
  app/views/admin/creator_settings/_form.html.erb
Labels: PR: partially-approved

#15644 pullToRefresh adjustments - fixing scrolling hijacking
  app/assets/javascripts/lib/pulltorefresh.js
  app/assets/stylesheets/views/article-form.scss
  app/javascript/article-form/components/Toolbar.jsx
  app/javascript/crayons/MarkdownToolbar/MarkdownToolbar.jsx
Labels: area: mobile, PR: partially-approved, tech: frontend

#15098 user settings i18n
  app/controllers/users_controller.rb
  app/lib/constants/settings.rb
  app/lib/settings.rb
  app/views/users/_account.html.erb
  app/views/users/_account_providers_emails.html.erb
  app/views/users/_account_providers_settings.html.erb
  app/views/users/_account_set_password.html.erb
  app/views/users/_additional_authentication.html.erb
  app/views/users/_billing.html.erb
  app/views/users/_customization.html.erb
  app/views/users/_editor_selector.html.erb
  app/views/users/_extensions.html.erb
  app/views/users/_integrations.html.erb
  app/views/users/_integrations_github_repositories.html.erb
  app/views/users/_navbar_selector.html.erb
  app/views/users/_notifications.html.erb
  app/views/users/_org_admin.html.erb
  app/views/users/_org_member.html.erb
  app/views/users/_org_non_member.html.erb
  app/views/users/_profile.html.erb
  app/views/users/_publishing_from_rss.html.erb
  app/views/users/_response_templates.html.erb
  app/views/users/confirm_destroy.html.erb
  app/views/users/edit.html.erb
  config/locales/en.yml
  config/locales/fr.yml
  config/locales/helpers/en.yml
  config/locales/helpers/fr.yml
  config/locales/views/settings/en.yml
  config/locales/views/settings/fr.yml
  spec/requests/user/user_settings_spec.rb
Labels: PR: unreviewed

#15541 Update Android PN integration fixes
  app/assets/javascripts/initializePage.js
  app/javascript/mobile/foremMobile.js
  app/models/device.rb
Labels: PR: partially-approved, merge by any core

#15657 add some missing i18n strings & keys in views/comments
  app/views/comments/_hide_comments_modal.html.erb
  config/locales/views/comments/en.yml
  config/locales/views/comments/fr.yml
Labels: PR: partially-approved

#15637 Save article (to cache tags) before updating follow points
  spec/workers/follows/update_points_worker_spec.rb
Labels: PR: partially-approved

#15661 Replaces Hardcoded URL with Path Helper in Terms Partial
  app/views/pages/_terms_text.html.erb
Labels: PR: partially-approved

#15665 Fixing blank home page for anonymous/visitor
  app/services/articles/feeds/find_featured_story.rb
  app/services/articles/feeds/weighted_query_strategy.rb
  spec/services/articles/feeds/weighted_query_strategy_spec.rb
  spec/services/articles/feeds_spec.rb
Labels: PR: reviewed-approved

#15662 Creator Settings: Removed SVG files as an option for logo upload
  app/controllers/admin/creator_settings_controller.rb
  app/uploaders/base_uploader.rb
  app/uploaders/logo_uploader.rb
  app/views/admin/creator_settings/_form.html.erb
  spec/uploaders/logo_uploader_spec.rb
Labels: PR: partially-approved, type: forem creation, merge by any core, tech: backend

#15659 Don't write a \n at the end of the release version
  scripts/release
Labels: PR: reviewed-approved

#15629 Validate payment info present before attempting to process
  app/services/payments/process_credit_purchase.rb
  config/locales/services/payments/en.yml
  config/locales/services/payments/fr.yml
  spec/services/payments/process_credit_purchase_spec.rb
Labels: PR: reviewed-approved

#15638 Use the tag_list method, rather than the cached_tag_list attribute
  app/workers/follows/update_points_worker.rb
Labels: PR: partially-approved

#15680 Disable failing test cases
  spec/requests/stories_index_spec.rb
Labels: PR: reviewed-approved, merge by any core

#15670 Spelling
  app/assets/javascripts/initializers/initializePodcastPlayback.js
  app/assets/javascripts/utilities/buildCommentFormHTML.js.erb
  app/assets/javascripts/utilities/buildCommentHTML.js.erb
  app/assets/javascripts/utilities/showUserAlertModal.js
  app/controllers/admin/organizations_controller.rb
  app/controllers/articles_controller.rb
  app/controllers/comments_controller.rb
  app/javascript/Search/__tests__/SearchFormSync.test.jsx
  app/javascript/crayons/Buttons/__stories__/Buttons.mdx
  app/javascript/crayons/CTAs/__stories__/CTAs.mdx
  app/javascript/crayons/Indicator/__stories__/indicators.md
  app/javascript/crayons/Links/__stories__/Links.mdx
  app/javascript/crayons/typography/__stories__/accented-typography.md
  app/javascript/readingList/components/__stories__/MediaQuery.stories.mdx
  app/lib/constants/settings/user_experience.rb
  app/lib/reverse_markdown/converters/custom_text.rb
  app/models/user.rb
  app/services/mailchimp/bot.rb
  app/services/re_captcha/check_enabled.rb
  app/views/admin/feedback_messages/_abuse_reports.html.erb
  app/views/admin/html_variants/show.html.erb
  app/views/admin/organizations/show.html.erb
  app/views/dashboards/_analytics.html.erb
  app/views/listings/_form.html.erb
  app/views/pages/_privacy_text.html.erb
  app/views/users/confirm_destroy.html.erb
  bin/untranslated_erb
  config/initializers/devise.rb
  config/schedule.yml
Labels: PR: partially-approved

#15667 Moving engine mount points to admin
  config/routes.rb
  config/routes/admin.rb
Labels: PR: partially-approved

#15678 Specify a single base image for builder and production
  Containerfile
Labels: PR: partially-approved

#15640 Extracting cross-model uniqueness validator
  app/models/organization.rb
  app/models/page.rb
  app/models/podcast.rb
  app/models/user.rb
  app/validators/unique_cross_model_slug_validator.rb
  spec/validators/unique_cross_model_slug_validator_spec.rb
Labels: PR: partially-approved

#15688 Creator Settings: Fixed the resizing of the preview logo
  app/javascript/admin/controllers/creator_settings_controller.js
Labels: PR: partially-approved, type: forem creation, merge by any core, tech: javascript

#15654 Pulls Creator Onboarding Redirect Links Into a Creator Onboarding-Specific Function
  app/javascript/packs/onboardingRedirectCheck.jsx
Labels: PR: reviewed-approved

#15706 Fix markup for API key metadata
  app/views/users/_account.html.erb
Labels: PR: partially-approved

#15708 Renaming constant to reflect intention
  app/queries/admin/moderators_query.rb
Labels: PR: partially-approved

#15701 Removing the stackbit integration
  app/decorators/user_decorator.rb
  app/views/users/_extensions.html.erb
  app/views/users/_integrations.html.erb
  config/locales/views/settings/en.yml
  config/locales/views/settings/fr.yml
  lib/data_update_scripts/20211206222716_remove_stackbit_page.rb
  spec/decorators/user_decorator_spec.rb
  spec/lib/data_update_scripts/remove_stackbit_page_spec.rb
  spec/requests/user/user_settings_spec.rb
  spec/system/user/user_edits_extensions_spec.rb
Labels: PR: partially-approved

#15136 I18nize views misc & non-HTML templates
  app/views/api/v0/shared/_user_show.json.jbuilder
  app/views/articles/feed.rss.builder
  app/views/articles/stats.html.erb
  app/views/email_subscriptions/invalid_token.html.erb
  app/views/email_subscriptions/unsubscribe.html.erb
  app/views/layouts/mailer.html.erb
  app/views/open_search/show.xml.erb
  app/views/shared/_stats.html.erb
  app/views/users/index.json.jbuilder
  config/locales/en.yml
  config/locales/fr.yml
  config/locales/utils/en.yml
  config/locales/utils/fr.yml
  config/locales/views/misc/en.yml
  config/locales/views/misc/fr.yml
Labels: PR: partially-approved

#15713 Fix Fastly bot block for Ruby `Net::HTTP` clients
  config/fastly/snippets/bad_bot_detection.vcl
Labels: PR: partially-approved

#15690 Remove manual require of view_component from gemfile
  Gemfile
Labels: PR: reviewed-approved

#15698 Don't test for article score filtering in home feed
  spec/requests/stories_index_spec.rb
Labels: PR: partially-approved

#15715 Blocking subdomains of domains marked as spam
  app/models/settings/authentication.rb
  spec/models/settings/authentication_spec.rb
Labels: PR: reviewed-approved

#15699 Implement Unified Embed for Vimeo URLs
  app/liquid_tags/liquid_tag_base.rb
  app/liquid_tags/unified_embed_tag.rb
  app/liquid_tags/vimeo_tag.rb
  app/liquid_tags/youtube_tag.rb
  spec/liquid_tags/unified_embed_spec.rb
  spec/liquid_tags/vimeo_tag_spec.rb
  spec/liquid_tags/youtube_tag_spec.rb
Labels: PR: unreviewed

#15712 Adjust Spacing Beneath Logo Upload Field on the Creator Settings Page
  app/assets/stylesheets/setup-mode.scss
Labels: PR: partially-approved

#15705 Extracted the logo uploader into its own partial
  app/javascript/admin/controllers/creator_settings_controller.js
  app/javascript/admin/controllers/logo_upload_controller.js
  app/javascript/packs/base.jsx
  app/views/admin/creator_settings/_form.html.erb
  app/views/admin/shared/_logo_upload.html.erb
Labels: PR: unreviewed, type: forem creation, merge by any core, tech: fullstack

#15692 Conditionally Renders Links Within the COC During Creator Onboarding
  app/helpers/application_helper.rb
  app/views/pages/_coc_text.html.erb
Labels: PR: partially-approved

#15653 Updating header with new Crayons buttons
  app/assets/javascripts/initializers/initializeSpecialNavigationFunctionality.js
  app/assets/stylesheets/components/buttons.scss
  app/assets/stylesheets/components/ctas.scss
  app/assets/stylesheets/components/forms.scss
  app/assets/stylesheets/components/header.scss
  app/assets/stylesheets/components/links.scss
  app/assets/stylesheets/config/_colors.scss
  app/assets/stylesheets/config/_generator.scss
  app/assets/stylesheets/config/_variables.scss
  app/assets/stylesheets/themes/dark.scss
  app/javascript/Search/SearchForm.jsx
  app/javascript/crayons/Buttons/Button.jsx
  app/javascript/crayons/CTAs/CTA.jsx
  app/javascript/crayons/CTAs/__stories__/CTAs.mdx
  app/javascript/crayons/CTAs/__stories__/CTAs.stories.jsx
  app/javascript/crayons/CTAs/__tests__/__snapshots__/CTA.test.jsx.snap
  app/javascript/crayons/Icons/Icon.jsx
  app/javascript/crayons/Links/Link.jsx
  app/javascript/crayons/Links/__stories__/Links.stories.jsx
  app/javascript/packs/base.jsx
  app/javascript/topNavigation/__tests__/utilities.test.js
  app/javascript/topNavigation/utilities.js
  app/views/layouts/_nav_menu.html.erb
  app/views/layouts/_top_bar.html.erb
  cypress/integration/seededFlows/topNavigationFlows/MemberDropDownButton.spec.js
Labels: PR: partially-approved, tech: frontend

#15497 Use the rss item's url when handling relative image links
  app/services/feeds/assemble_article_markdown.rb
  spec/services/feeds/assemble_article_markdown_spec.rb
Labels: PR: partially-approved

#15373 Revisit tag validation script
  lib/data_update_scripts/20211115154021_nullify_invalid_tag_fields.rb
  spec/lib/data_update_scripts/nullify_invalid_tag_fields_spec.rb
Labels: PR: partially-approved

#15249 Don't show reactions to missing reactables
  app/views/admin/privileged_reactions/index.html.erb
Labels: PR: partially-approved

#15717 role deprecation cleanup
  app/controllers/moderations_controller.rb
  app/decorators/user_decorator.rb
  app/models/rating_vote.rb
  app/models/user.rb
  app/views/admin/articles/_individual_article.html.erb
  app/views/moderations/index.html.erb
  spec/decorators/user_decorator_spec.rb
  spec/models/user_spec.rb
  spec/requests/admin/tags/moderators_spec.rb
Labels: PR: partially-approved

#15704 Removed resaving users' articles in a before_validation callback
  app/models/user.rb
  spec/services/users/update_spec.rb
Labels: PR: partially-approved

#15684 Using a Form Object that will persist for the Creator Settings Form
  app/assets/javascripts/initializers/initializePodcastPlayback.js
  app/controllers/admin/creator_settings_controller.rb
  app/forms/creator_settings_form.rb
  app/javascript/onboarding/components/Navigation.jsx
  app/models/settings/community.rb
  app/models/settings/user_experience.rb
  app/views/admin/creator_settings/_form.html.erb
  app/views/admin/creator_settings/new.html.erb
  app/views/admin/shared/_logo_upload.html.erb
  cypress/integration/creatorOnboardingFlows/creatorSettings.spec.js
  spec/forms/creator_settings_form_spec.rb
  spec/requests/admin/creator_settings_spec.rb
Labels: PR: partially-approved, merge by any core

#15725 Adjust Creator Settings Form Width
  app/views/admin/creator_settings/_form.html.erb
Labels: PR: partially-approved

#15724 Remove reactions to a user when deleting the user
  app/models/reaction.rb
  app/models/user.rb
  app/services/users/delete_activity.rb
  lib/data_update_scripts/20211209213849_remove_dangling_user_reactions.rb
  spec/factories/reactions.rb
  spec/lib/data_update_scripts/remove_dangling_user_reactions_spec.rb
  spec/services/users/delete_spec.rb
Labels: PR: reviewed-approved

#15728 Ignore MtPopUpList on Honeybadger
  app/assets/javascripts/base.js.erb
Labels: PR: unreviewed

#15703 Spelling db migrate
  db/migrate/20160104221355_add_url_to_advertisements.rb
  db/migrate/20170206214820_add_secret_to_sponsors.rb
  db/migrate/20190327090030_add_indexes_to_identities.rb
  db/migrate/20190401100844_add_unique_index_to_users_twitter_username.rb
  db/migrate/20190401100850_add_unique_index_to_users_github_username.rb
  db/migrate/20200308144606_add_index_to_rating_votes.rb
  db/migrate/20200820055018_add_display_columns_to_profile_fields.rb
  db/migrate/20210428190634_add_tsvector_index_on_searchable_columns_to_podcast_episodes.rb
  db/migrate/20210917023320_drop_connect_tables.rb
Labels: PR: partially-approved

#15734 resolve storybook upgrades
  package.json
  yarn.lock
Labels: PR: partially-approved

#15737 Wait for async data in forem mobile cypress test
  cypress/integration/seededFlows/mobileFlows/namespacedForemMobile.spec.js
  cypress/support/commands.js
Labels: PR: unreviewed

#15733 Removing feed experiment for non-logged in user
  app/controllers/stories_controller.rb
Labels: PR: reviewed-approved

#15731 clean up views i18n entries
  app/views/users/edit.html.erb
  config/locales/en.yml
  config/locales/fr.yml
  config/locales/views/main/fr.yml
  config/locales/views/settings/en.yml
  config/locales/views/settings/fr.yml
  config/locales/views/users/en.yml
  config/locales/views/users/fr.yml
  spec/system/homepage/user_visits_homepage_spec.rb
Labels: PR: reviewed-approved

#15744 Adjust Width of Creator Settings Form Fields
  app/views/admin/creator_settings/new.html.erb
Labels: PR: unreviewed

#15746 Clear changes to settings after checking form saves them
  spec/forms/creator_settings_form_spec.rb
Labels: PR: reviewed-approved

#15756 add cypress-pipe, fix flaky test
  app/javascript/actionsPanel/initializeActionsPanelToggle.js
  cypress/integration/seededFlows/moderationFlows/adjustPostTags.spec.js
  cypress/support/index.js
  package.json
  yarn.lock
Labels: PR: partially-approved, merge by any core

#15732 Logo style updates
  app/assets/stylesheets/base/main.scss
  app/views/layouts/_logo.html.erb
Labels: PR: partially-approved

#15776 Strip surrounding whitespace from HTMLVariant name
  app/models/html_variant.rb
  spec/models/html_variant_spec.rb
Labels: PR: partially-approved

#15745 Implement Unified Embed for Forem Article/Post URLs
  app/liquid_tags/link_tag.rb
  spec/lib/liquid/raw_spec.rb
  spec/liquid_tags/unified_embed_spec.rb
Labels: PR: unreviewed

#15770 Replace honeybadger-js with @honeybadger-io/js
  app/assets/javascripts/base.js.erb
  package.json
  yarn.lock
Labels: PR: partially-approved

#15784 Bump Rails to 6.1.4.3
  Gemfile.lock
  vendor/cache/actioncable-6.1.4.1.gem
  vendor/cache/actioncable-6.1.4.3.gem
  vendor/cache/actionmailbox-6.1.4.1.gem
  vendor/cache/actionmailbox-6.1.4.3.gem
  vendor/cache/actionmailer-6.1.4.1.gem
  vendor/cache/actionmailer-6.1.4.3.gem
  vendor/cache/actionpack-6.1.4.1.gem
  vendor/cache/actionpack-6.1.4.3.gem
  vendor/cache/actiontext-6.1.4.1.gem
  vendor/cache/actiontext-6.1.4.3.gem
  vendor/cache/actionview-6.1.4.1.gem
  vendor/cache/actionview-6.1.4.3.gem
  vendor/cache/activejob-6.1.4.1.gem
  vendor/cache/activejob-6.1.4.3.gem
  vendor/cache/activemodel-6.1.4.1.gem
  vendor/cache/activemodel-6.1.4.3.gem
  vendor/cache/activerecord-6.1.4.1.gem
  vendor/cache/activerecord-6.1.4.3.gem
  vendor/cache/activestorage-6.1.4.1.gem
  vendor/cache/activestorage-6.1.4.3.gem
  vendor/cache/activesupport-6.1.4.1.gem
  vendor/cache/activesupport-6.1.4.3.gem
  vendor/cache/marcel-1.0.1.gem
  vendor/cache/marcel-1.0.2.gem
  vendor/cache/minitest-5.14.4.gem
  vendor/cache/minitest-5.15.0.gem
  vendor/cache/rails-6.1.4.1.gem
  vendor/cache/rails-6.1.4.3.gem
  vendor/cache/railties-6.1.4.1.gem
  vendor/cache/railties-6.1.4.3.gem
  vendor/cache/sprockets-rails-3.2.2.gem
  vendor/cache/sprockets-rails-3.4.2.gem
Labels: PR: partially-approved

#15773 Consolidating role query logic
  app/models/user.rb
  app/services/mailchimp/bot.rb
Labels: PR: reviewed-approved

#15687 Refactoring instance variable usage in tagged articles controller
  app/controllers/stories/tagged_articles_controller.rb
  app/views/stories/tagged_articles/_meta.html.erb
  app/views/stories/tagged_articles/_sidebar.html.erb
  app/views/stories/tagged_articles/_sidebar_additional.html.erb
  app/views/stories/tagged_articles/index.html.erb
Labels: PR: partially-approved

#15787 Automatically create user profile if it's missing
  app/services/users/update.rb
  spec/services/users/update_spec.rb
Labels: PR: partially-approved

#15729 Added the logo upload to the admin -> customization -> config -> images section.
  app/controllers/admin/creator_settings_controller.rb
  app/controllers/admin/settings/general_settings_controller.rb
  app/controllers/admin/settings_controller.rb
  app/javascript/admin/controllers/config_controller.js
  app/javascript/admin/controllers/logo_upload_controller.js
  app/services/settings/general/upsert.rb
  app/uploaders/logo_uploader.rb
  app/views/admin/creator_settings/_form.html.erb
  app/views/admin/settings/_update_setting_button.html.erb
  app/views/admin/settings/forms/_images.html.erb
  app/views/admin/settings/show.html.erb
  app/views/admin/shared/_logo_upload.html.erb
  cypress/integration/creatorOnboardingFlows/creatorSettings.spec.js
Labels: PR: reviewed-approved, area: admin, PR: partially-approved, merge by any core, tech: fullstack

#15783 CSS Generator Fix
  app/assets/stylesheets/config/_generator.scss
Labels: PR: reviewed-approved, tech: frontend

#15781 ✂️✂️✂️ Drop PWA
  app/assets/javascripts/initializePage.js
  app/assets/javascripts/initializers/initializePWAFunctionality.js
  app/assets/javascripts/initializers/runtime.js
  app/assets/stylesheets/components/header.scss
  app/assets/stylesheets/runtime.scss
  app/lib/constants/settings/general.rb
  app/views/layouts/_top_bar.html.erb
Labels: PR: unreviewed

#15779 Error message after authentication failure due to email address not being whitelisted
  app/services/authentication/authenticator.rb
Labels: PR: unreviewed, area: auth, PR: partially-approved, tech: frontend

#15792 Implement Unified Embed for Instagram Post URLs
  app/liquid_tags/instagram_tag.rb
  app/liquid_tags/liquid_tag_base.rb
  app/liquid_tags/youtube_tag.rb
  spec/liquid_tags/unified_embed_spec.rb
Labels: PR: partially-approved

#15793 Disabled Spring for E2E databse when run locally
  bin/e2e
Labels: area: tests, PR: partially-approved, merge by any core

#15795 Changed members only copy for radio button label to invite only.
  app/views/admin/creator_settings/_form.html.erb
  cypress/integration/creatorOnboardingFlows/creatorSettings.spec.js
Labels: PR: partially-approved, type: forem creation, merge by any core

#15750 Remove Doorkeeper from API
  app/controllers/api/v0/api_controller.rb
  app/controllers/api/v0/articles_controller.rb
  app/controllers/api/v0/readinglist_controller.rb
  app/controllers/api/v0/users_controller.rb
  app/controllers/api/v0/webhooks_controller.rb
  spec/requests/api/v0/articles_spec.rb
  spec/requests/api/v0/listings_spec.rb
  spec/requests/api/v0/readinglist_spec.rb
  spec/requests/api/v0/users_spec.rb
  spec/requests/api/v0/webhooks_spec.rb
Labels: PR: reviewed-approved, merge by any core

#15780 Mobile mention notifications
  app/controllers/users/notification_settings_controller.rb
  app/services/notifications/new_mention/send.rb
  app/views/users/_notifications.html.erb
  config/locales/helpers/en.yml
  config/locales/helpers/fr.yml
  config/locales/views/notifications/en.yml
  config/locales/views/notifications/fr.yml
  db/migrate/20211209225729_add_mobile_mention_notification_to_user_notification_settings.rb
  db/schema.rb
  spec/factories/users_notification_settings.rb
  spec/services/notifications/new_mention/send_spec.rb
Labels: PR: partially-approved

#15338 Extracting container for allowed tags & attrs
  app/controllers/articles_controller.rb
  app/helpers/application_helper.rb
  app/models/badge_achievement.rb
  app/models/display_ad.rb
  app/sanitizers/rendered_markdown_scrubber.rb
  app/services/markdown_processor.rb
  app/services/markdown_processor/parser.rb
  app/views/podcast_episodes/show.html.erb
Labels: PR: reviewed-approved

#15799 Skip notification interaction with replies spec
  spec/system/notifications/notifications_page_spec.rb
Labels: PR: reviewed-approved

#15801 Implement Unified Embed for Blogcast URLs
  app/liquid_tags/blogcast_tag.rb
  app/liquid_tags/vimeo_tag.rb
  app/views/liquids/_blogcast.html.erb
  spec/liquid_tags/unified_embed_spec.rb
Labels: PR: partially-approved

#15794 Add article and comment count to instance API
  app/controllers/api/v0/instances_controller.rb
  spec/requests/api/v0/instances_spec.rb
Labels: PR: reviewed-approved

#15798 Added some retries to cookie clearing
  cypress/support/commands.js
Labels: area: tests, PR: partially-approved, merge by any core

#15807 Add DISABLE_SPRING environment variable to gitpod forem server task
  .gitpod.yml
Labels: PR: reviewed-approved

#15723 Don't raise error when empty community emoji setting submitted
  app/validators/emoji_only_validator.rb
  spec/validators/emoji_only_validator_spec.rb
Labels: PR: partially-approved

#15808 Implement Unified Embed for CodeSandbox URLs
  app/liquid_tags/codesandbox_tag.rb
  spec/liquid_tags/codesandbox_tag_spec.rb
  spec/liquid_tags/unified_embed_spec.rb
Labels: PR: unreviewed

#15816 Add me (Dwight) to readme :)
  README.md
Labels: PR: reviewed-approved

#15817 Disallow null user agent and obsolete browser
  config/fastly/snippets/bad_bot_detection.vcl
Labels: PR: partially-approved

#15818 Remove profile when banish
  app/services/users/delete_activity.rb
  spec/services/moderator/banish_user_spec.rb
Labels: PR: reviewed-approved

#15819 Escape periods and display the group name properly
  app/helpers/admin_helper.rb
  app/views/admin/profile_fields/_add_profile_field_modal.html.erb
  app/views/admin/profile_fields/_edit_group_modal.html.erb
  app/views/admin/profile_fields/_grouped_profile_fields.html.erb
Labels: PR: reviewed-approved

#15757 Update left sidebar links with new Crayons components
  app/assets/stylesheets/articles.scss
  app/assets/stylesheets/components/hamburger.scss
  app/assets/stylesheets/components/indicators.scss
  app/assets/stylesheets/components/links.scss
  app/assets/stylesheets/widgets.scss
  app/javascript/crayons/Indicator/__stories__/indicator.html.stories.jsx
  app/javascript/leftSidebar/TagsFollowed.jsx
  app/views/layouts/_main_nav.html.erb
  app/views/layouts/_sidebar_nav_link.html.erb
  app/views/layouts/_sidebar_tags.html.erb
  app/views/layouts/_social_media.html.erb
  app/views/shared/_auth_widget.html.erb
  app/views/shared/_hamburger.html.erb
  config/locales/views/auth/en.yml
  config/locales/views/auth/fr.yml
  spec/system/homepage/user_visits_homepage_spec.rb
Labels: PR: partially-approved, tech: frontend

#15782 Moved setting old_username from before_validation to Users::Update
  app/models/user.rb
  app/services/users/update.rb
  spec/models/user_spec.rb
  spec/requests/stories_show_spec.rb
  spec/requests/user/user_profile_spec.rb
Labels: PR: partially-approved

#15829 Logo bug fix
  app/assets/stylesheets/base/main.scss
Labels: PR: partially-approved, tech: frontend

#15828 CSS Variables cleanup
  app/assets/stylesheets/components/skip-link.scss
  app/assets/stylesheets/config/_colors.scss
  app/assets/stylesheets/preact/onboarding-modal.scss
  app/assets/stylesheets/themes/dark.scss
  app/assets/stylesheets/views/article-form.scss
  app/assets/stylesheets/views/footer.scss
  app/views/layouts/_footer.html.erb
  config/locales/views/main/en.yml
  config/locales/views/main/fr.yml
Labels: PR: partially-approved, tech: frontend

#15839 Disable dash replacement filter in markdown fixer
  app/services/markdown_processor/fixer/base.rb
  app/services/markdown_processor/fixer/fix_all.rb
  app/services/markdown_processor/fixer/fix_for_comment.rb
  app/services/markdown_processor/fixer/fix_for_preview.rb
  spec/services/markdown_processor/fixer/base_spec.rb
  spec/services/markdown_processor/fixer/fix_all_spec.rb
  spec/services/markdown_processor/fixer/fix_for_comment_spec.rb
  spec/services/markdown_processor/fixer/fix_for_preview_spec.rb
Labels: PR: partially-approved

#15831 restore an i18n key in _footer.html.erb
  app/views/layouts/_footer.html.erb
  config/locales/views/main/en.yml
  config/locales/views/main/fr.yml
Labels: PR: reviewed-approved

#15749 Remove Doorkeeper gem
  Gemfile
  Gemfile.lock
  app/controllers/oauth/tokens_controller.rb
  app/models/user.rb
  app/models/webhook/endpoint.rb
  app/services/users/delete_activity.rb
  app/views/doorkeeper/applications/_delete_form.html.erb
  app/views/doorkeeper/applications/_form.html.erb
  app/views/doorkeeper/applications/edit.html.erb
  app/views/doorkeeper/applications/index.html.erb
  app/views/doorkeeper/applications/new.html.erb
  app/views/doorkeeper/applications/show.html.erb
  app/views/doorkeeper/authorizations/error.html.erb
  app/views/doorkeeper/authorizations/new.html.erb
  app/views/doorkeeper/authorizations/show.html.erb
  app/views/doorkeeper/authorized_applications/_delete_form.html.erb
  app/views/doorkeeper/authorized_applications/index.html.erb
  app/views/layouts/doorkeeper/admin.html.erb
  app/views/layouts/doorkeeper/application.html.erb
  config/i18n-tasks.yml
  config/initializers/doorkeeper.rb
  config/locales/doorkeeper.en.yml
  config/routes.rb
  spec/factories/doorkeeper_access_grants.rb
  spec/factories/doorkeeper_access_tokens.rb
  spec/factories/doorkeeper_applications.rb
  spec/models/user_spec.rb
  spec/models/webhook/endpoint_spec.rb
  spec/requests/oauth/tokens_spec.rb
  spec/support/initializers/doorkeeper.rb
  spec/workers/webhook/destroy_worker_spec.rb
  vendor/cache/doorkeeper-5.5.4.gem
Labels: PR: partially-approved

#15840 add badge to tags suggest response
  app/controllers/tags_controller.rb
  spec/requests/tags_spec.rb
Labels: PR: partially-approved

#15830 i18n fix for character limit counter
  app/javascript/packs/userProfileSettings.js
  app/views/users/_profile.html.erb
  config/locales/views/settings/en.yml
  config/locales/views/settings/fr.yml
Labels: PR: partially-approved

#15842 Add comment notification test to Cypress, including a11y improvements to notification page
  app/assets/javascripts/initializers/initNotifications.js
  app/views/notifications/index.html.erb
  app/views/notifications/shared/_comment_box.html.erb
  cypress/integration/seededFlows/notificationsFlows/commentNotifications.spec.js
  spec/support/seeds/seeds_e2e.rb
  spec/system/notifications/notifications_page_spec.rb
Labels: PR: partially-approved

#15762 Refactoring questions asked of user
  app/controllers/admin/creator_settings_controller.rb
  app/controllers/admin/settings/base_controller.rb
  app/controllers/api/v0/api_controller.rb
  app/controllers/api/v0/articles_controller.rb
  app/controllers/moderations_controller.rb
  app/liquid_tags/liquid_tag_base.rb
  app/liquid_tags/poll_tag.rb
  app/liquid_tags/user_subscription_tag.rb
  app/models/tag_adjustment.rb
  app/models/user.rb
  app/policies/application_policy.rb
  app/policies/authorizer.rb
  app/policies/internal_policy.rb
  app/policies/liquid_tag_policy.rb
  app/policies/tag_policy.rb
  app/policies/user_policy.rb
  app/services/mailchimp/bot.rb
  app/services/moderator/manage_activity_and_roles.rb
  app/services/tag_moderators/add_trusted_role.rb
  app/services/users/approved_liquid_tags.rb
  app/views/admin/pages/_form.html.erb
  app/views/admin/settings/_update_setting_button.html.erb
  app/views/admin/settings/show.html.erb
  app/views/admin/users/edit.html.erb
  app/views/moderations/mod.html.erb
  app/views/notifications/shared/_comment_box.html.erb
  app/views/tags/edit.html.erb
  app/views/users/_notifications.html.erb
  app/views/videos/new.html.erb
  spec/lib/data_update_scripts/backfill_creator_role_for_first_super_admin_spec.rb
  spec/liquid_tags/liquid_tag_base_spec.rb
  spec/liquid_tags/poll_tag_spec.rb
  spec/liquid_tags/user_subscription_tag_spec.rb
  spec/models/user_spec.rb
  spec/policies/authorizer_spec.rb
  spec/policies/internal_policy_spec.rb
  spec/policies/liquid_tag_policy_spec.rb
  spec/requests/admin/mods_spec.rb
  spec/requests/admin/tags/moderators_spec.rb
  spec/requests/admin/users_manage_spec.rb
  spec/requests/podcasts/podcast_create_spec.rb
  spec/requests/registrations_spec.rb
  spec/services/moderator/manage_activity_and_roles_spec.rb
  spec/system/admin/admin_bans_or_warns_user_spec.rb
  spec/workers/moderator/banish_user_worker_spec.rb
Labels: PR: partially-approved

#15855 Favoring common method not previously available
  app/queries/articles/active_threads_query.rb
Labels: PR: reviewed-approved

#15861 User correct username in mobile mention notifications
  app/services/notifications/new_mention/send.rb
  spec/services/notifications/new_mention/send_spec.rb
Labels: PR: partially-approved

#15864 Add catch to trackAdImpression()
  app/assets/javascripts/initializers/initializeBaseTracking.js.erb
Labels: PR: partially-approved

#15865 Favoring single SQL and computation over enum
  app/models/tag.rb
Labels: PR: partially-approved

#15868 Favor `destroy_by` over `where.first&.destroy`
  app/controllers/profile_pins_controller.rb
Labels: PR: partially-approved

#15852 Favoring constant over magic string
  app/controllers/admin/moderator_actions_controller.rb
  app/models/audit_log.rb
  spec/requests/admin/moderator_actions_spec.rb
Labels: PR: reviewed-approved

#15879 When returning a json error, don't use a raw unescaped string
  app/controllers/application_controller.rb
Labels: PR: reviewed-approved

#15867 Remove slash characters from user name search term
  app/models/user.rb
  spec/services/search/username_spec.rb
Labels: PR: partially-approved

#15890 Require parameter string before matching time for youtube video ids
  app/liquid_tags/youtube_tag.rb
Labels: PR: reviewed-approved

#15827 Remove webhooks and related code
  Gemfile
  Gemfile.lock
  app/controllers/admin/webhook_endpoints_controller.rb
  app/controllers/api/v0/webhooks_controller.rb
  app/models/admin_menu.rb
  app/models/user.rb
  app/models/webhook/endpoint.rb
  app/models/webhook/event.rb
  app/models/webhook_endpoint.rb
  app/serializers/webhook/article_destroyed_serializer.rb
  app/serializers/webhook/article_serializer.rb
  app/serializers/webhook/event_serializer.rb
  app/serializers/webhook/user_serializer.rb
  app/services/articles/creator.rb
  app/services/articles/destroyer.rb
  app/services/articles/updater.rb
  app/services/secrets/generator.rb
  app/services/users/delete_activity.rb
  app/services/webhook/dispatch_event.rb
  app/services/webhook/payload_adapter.rb
  app/views/api/v0/webhooks/index.json.jbuilder
  app/views/api/v0/webhooks/show.json.jbuilder
  app/workers/webhook/destroy_worker.rb
  app/workers/webhook/dispatch_event_worker.rb
  config/routes.rb
  config/routes/admin.rb
  spec/factories/webhook_endpoints.rb
  spec/models/user_spec.rb
  spec/models/webhook/endpoint_spec.rb
  spec/models/webhook/event_spec.rb
  spec/requests/api/v0/webhooks_spec.rb
  spec/requests/articles/articles_create_spec.rb
  spec/requests/articles/articles_update_spec.rb
  spec/services/articles/creator_spec.rb
  spec/services/articles/destroyer_spec.rb
  spec/services/articles/updater_spec.rb
  spec/services/secrets/generator_spec.rb
  spec/services/webhook/dispatch_event_spec.rb
  spec/services/webhook/payload_adapter_spec.rb
  spec/workers/webhook/destroy_worker_spec.rb
  spec/workers/webhook/dispatch_event_worker_spec.rb
  vendor/cache/ulid-1.3.0.gem
Labels: PR: partially-approved

#15874 Fixed setting Identity#auth_data_dump in seeds and factory
  db/seeds.rb
  spec/factories/identities.rb
  spec/models/identity_spec.rb
Labels: PR: partially-approved

#15893 Mock omniauth payload before creating identities
  spec/requests/admin/users_manage_spec.rb
Labels: PR: partially-approved, merge by any core

#15892 Rubocop fixes
  app/controllers/application_controller.rb
  app/liquid_tags/codepen_tag.rb
  app/liquid_tags/glitch_tag.rb
  app/liquid_tags/js_fiddle_tag.rb
  app/liquid_tags/stackblitz_tag.rb
  app/services/articles/destroyer.rb
  app/services/color/compare_hex.rb
  app/services/loggers/log_worker_queue_stats.rb
  spec/system/admin/admin_bans_or_warns_user_spec.rb
  spec/workers/organizations/bust_cache_worker_spec.rb
  spec/workers/podcast_episodes/bust_cache_worker_spec.rb
  spec/workers/users/bust_cache_worker_spec.rb
  spec/workers/users/subscribe_to_mailchimp_newsletter_worker_spec.rb
Labels: PR: reviewed-approved

#15886 Add catch to trackFifteenSecondsOnPage()
  app/assets/javascripts/initializers/initializeBaseTracking.js.erb
Labels: PR: partially-approved

#15854 Remove Doorkeeper and webhook tables
  db/migrate/20211222040359_remove_doorkeeper.rb
  db/schema.rb
Labels: PR: partially-approved

#15850 Refactoring to leverage an Article scope
  app/controllers/articles_controller.rb
  app/controllers/stories/tagged_articles_controller.rb
  app/models/article.rb
  app/services/articles/feeds/large_forem_experimental.rb
Labels: PR: reviewed-approved

#15898 Load article before creating a page view for an invalid one
  app/workers/articles/update_page_views_worker.rb
  spec/workers/articles/update_page_views_worker_spec.rb
Labels: PR: partially-approved

#15851 Refactoring to consolidate logic
  app/controllers/sidebars_controller.rb
  app/controllers/stories_controller.rb
  app/models/campaign.rb
Labels: PR: partially-approved

#15905 delete and add back i18n keys
  app/views/articles/show.html.erb
  app/views/users/_profile.html.erb
  config/locales/views/actions/en.yml
  config/locales/views/actions/fr.yml
  config/locales/views/listings/en.yml
  config/locales/views/listings/fr.yml
  config/locales/views/main/en.yml
  config/locales/views/main/fr.yml
  config/locales/views/misc/en.yml
  config/locales/views/misc/fr.yml
  config/locales/views/tags/en.yml
  config/locales/views/tags/fr.yml
Labels: PR: reviewed-approved

#15903 Update trusted user welcome email copy with Discord link
  app/views/mailers/notify_mailer/trusted_role_email.html.erb
  app/views/mailers/notify_mailer/trusted_role_email.text.erb
Labels: PR: unreviewed
