Repository forem/forem, pull requests merged in 2021-03, with the labels that each got.

#12779 Spike: Add ThrottledCall utility class
  app/lib/throttled_call.rb
  app/workers/reactions/update_relevant_scores_worker.rb
  spec/lib/throttled_call_spec.rb
  spec/workers/reactions/update_relevant_scores_worker_spec.rb
Labels: PR: partially-approved

#11778 Update .env_sample
  .env_sample
Labels: PR: partially-approved

#12833 Improve ActionController::InvalidAuthenticityToken error handling
  app/controllers/application_controller.rb
Labels: PR: reviewed-approved

#12812 Refactor: Extract Role Removal Into a Service
  app/controllers/admin/users_controller.rb
  app/helpers/application_helper.rb
  app/services/users/remove_role.rb
  app/views/admin/users/_current_roles.html.erb
  spec/services/users/remove_role_spec.rb
Labels: PR: reviewed-approved

#12670 Part 1: Shows Relevant #help Posts in Homepage Sidebar
  app/models/article.rb
  spec/models/article_spec.rb
Labels: PR: partially-approved

#12853 Bug Fix:Update updated_at Timestamp Every time We Run Repo Sync Worker
  app/workers/github_repos/repo_sync_worker.rb
  spec/workers/github_repos/repo_sync_worker_spec.rb
Labels: PR: partially-approved

#12834 Reduce service worker functionality to minimal offline page
  app/controllers/application_controller.rb
  app/controllers/async_info_controller.rb
  app/controllers/shell_controller.rb
  app/views/service_worker/index.js.erb
  app/views/shell/_bottom.html.erb
  app/views/shell/_top.html.erb
  docs/backend/internationalization.md
  docs/technical-overview/architecture.md
  lib/tasks/cache.rake
  public/offline.html
  spec/requests/service_worker_spec.rb
Labels: PR: unreviewed

#12726 Add admin overview page
  app/controllers/admin/admin_portals_controller.rb
  app/controllers/admin/overview_controller.rb
  app/helpers/admin_helper.rb
  app/javascript/admin/controllers/ahoy_controller.js
  app/models/overview.rb
  app/views/admin/admin_portals/index.html.erb
  app/views/admin/overview/index.html.erb
  app/views/admin/shared/_navbar.html.erb
  app/views/layouts/admin.html.erb
  config/routes.rb
  docs/getting-started/start-app.md
  spec/requests/admin/overview_spec.rb
  spec/system/admin/admin_visits_overview_spec.rb
Labels: PR: partially-approved

#10524 Publicly indicate if someone edits their comments
  app/decorators/comment_decorator.rb
  app/views/comments/_comment_date.erb
  spec/system/comments/user_edits_a_comment_spec.rb
Labels: PR: unreviewed, include in changelog

#12851 RFC#50-P1 Restructuring some routes and adding a feature flag
  config/routes.rb
Labels: PR: partially-approved

#12857 Fix double render of Overview in admin navbar
  app/views/admin/shared/_navbar.html.erb
  app/views/layouts/admin.html.erb
Labels: PR: reviewed-approved

#12854 Remove unused CSS
  app/assets/stylesheets/base/helpers.scss
Labels: PR: partially-approved

#12811 Refactor cache purging
  app/controllers/admin/tools_controller.rb
  app/controllers/application_controller.rb
  app/controllers/profile_pins_controller.rb
  app/models/article.rb
  app/models/badge.rb
  app/models/github_repo.rb
  app/models/user.rb
  app/services/edge_cache/bust.rb
  app/services/edge_cache/bust_article.rb
  app/services/edge_cache/bust_comment.rb
  app/services/edge_cache/bust_commentable.rb
  app/services/edge_cache/bust_events.rb
  app/services/edge_cache/bust_listings.rb
  app/services/edge_cache/bust_organization.rb
  app/services/edge_cache/bust_page.rb
  app/services/edge_cache/bust_podcast.rb
  app/services/edge_cache/bust_podcast_episode.rb
  app/services/edge_cache/bust_sidebar.rb
  app/services/edge_cache/bust_tag.rb
  app/services/edge_cache/bust_user.rb
  app/workers/articles/bust_multiple_caches_worker.rb
  app/workers/reactions/bust_homepage_cache_worker.rb
  app/workers/reactions/bust_reactable_cache_worker.rb
  spec/models/badge_spec.rb
  spec/models/github_repo_spec.rb
  spec/services/edge_cache/bust_article_spec.rb
  spec/services/edge_cache/bust_comment_spec.rb
  spec/services/edge_cache/bust_commentable_spec.rb
  spec/services/edge_cache/bust_events_spec.rb
  spec/services/edge_cache/bust_listings_spec.rb
  spec/services/edge_cache/bust_organization_spec.rb
  spec/services/edge_cache/bust_page_spec.rb
  spec/services/edge_cache/bust_podcast_episode_spec.rb
  spec/services/edge_cache/bust_podcast_spec.rb
  spec/services/edge_cache/bust_sidebar_spec.rb
  spec/services/edge_cache/bust_spec.rb
  spec/services/edge_cache/bust_tag_spec.rb
  spec/services/edge_cache/bust_user_spec.rb
  spec/services/users/delete_spec.rb
  spec/workers/articles/bust_multiple_caches_worker_spec.rb
  spec/workers/bust_cache_path_worker_spec.rb
  spec/workers/reactions/bust_homepage_cache_worker_spec.rb
  spec/workers/reactions/bust_reactable_cache_worker_spec.rb
Labels: PR: partially-approved

#12856 Remove superfluous title attribute from sidebar SVGs
  app/views/layouts/_sidebar_nav_link.html.erb
Labels: PR: unreviewed

#12852 Optimization:Enforce Uniqueness for Follows::UpdatePointsWorker and RatingVotes::AssignRatingWorker
  app/workers/follows/update_points_worker.rb
  app/workers/rating_votes/assign_rating_worker.rb
Labels: PR: reviewed-approved

#12861 [15 minute fix] Remove disambiguatingDescription from user profile
  app/controllers/stories_controller.rb
  spec/requests/user/user_show_spec.rb
Labels: PR: partially-approved

#12859 Remove single resource admin config from seed data
  db/seeds.rb
Labels: PR: partially-approved

#12876 Update style guide link
  docs/getting-started/committing.md
Labels: PR: reviewed-approved

#12858 Add tech admin to seeded admin user
  db/seeds.rb
Labels: PR: unreviewed

#12877 [15 Minute Fix]: Update email footer copy to account for email authentication
  app/helpers/authentication_helper.rb
  app/views/layouts/mailer.html.erb
  spec/helpers/authentication_helper_spec.rb
Labels: PR: unreviewed

#12797 Fix Markdown parsing of <code> tag
  app/services/markdown_processor/parser.rb
  spec/services/markdown_processor/parser_spec.rb
Labels: PR: partially-approved

#12883 Update seeds.rb ASCII output to Forem
  db/seeds.rb
Labels: PR: partially-approved

#12837 Fix subscribe to discussion button when user is not logged in
  app/javascript/CommentSubscription/CommentSubscription.jsx
  app/javascript/CommentSubscription/__tests__/CommentSubscription.test.jsx
  app/javascript/packs/articlePage.jsx
  cypress/integration/loggedOutFlows/showLoginModal.spec.js
Labels: PR: partially-approved

#12907 Disable serviceworkers on Safari browsers
  app/assets/javascripts/serviceworker-companion.js
Labels: PR: partially-approved

#12909 Disable serviceworkers in Safari part2
  app/assets/javascripts/serviceworker-companion.js
Labels: PR: partially-approved

#11268 Exclude code highlight panel markup from RSS description
  app/models/article.rb
  app/views/articles/feed.rss.builder
  spec/models/article_spec.rb
Labels: PR: partially-approved

#12885 Fix twitter liquid tag buttons misaligned
  app/assets/stylesheets/ltags/TweetTag.scss
Labels: PR: partially-approved

#12831 Create mention autocomplete: initial storybook component
  app/assets/stylesheets/components/autocomplete.scss
  app/assets/stylesheets/crayons.scss
  app/javascript/crayons/MentionAutocomplete/MentionAutocomplete.jsx
  app/javascript/crayons/MentionAutocomplete/MentionAutocompleteCombobox.jsx
  app/javascript/crayons/MentionAutocomplete/__stories__/MentionAutocomplete.stories.jsx
  app/javascript/crayons/MentionAutocomplete/__stories__/mention-autocomplete.md
  app/javascript/crayons/MentionAutocomplete/__tests__/MentionAutocomplete.test.jsx
  app/javascript/crayons/MentionAutocomplete/__tests__/MentionAutocompleteCombobox.test.jsx
  app/javascript/crayons/MentionAutocomplete/__tests__/__snapshots__/MentionAutocompleteCombobox.test.jsx.snap
  app/javascript/crayons/MentionAutocomplete/index.js
  app/javascript/utilities/textAreaUtils.js
  jest.config.js
  package.json
  yarn.lock
Labels: PR: partially-approved

#12906 Remove mod button from top nav bar in mobile
  app/views/layouts/_nav_menu.html.erb
  app/views/layouts/_top_bar.html.erb
Labels: PR: partially-approved, actual_size:XS, area: moderation, include in changelog, team members:1

#12910 [15 minute fix] Remove outdated language from RSS import
  app/views/users/_publishing_from_rss.html.erb
Labels: PR: reviewed-approved

#12905 Setup pg_search
  Gemfile
  Gemfile.lock
  db/migrate/20210304195203_pg_search_extensions.rb
  db/schema.rb
  vendor/cache/pg_search-2.3.5.gem
Labels: PR: partially-approved

#12908 Expand Datadog instrumentation
  app/lib/forem_stats_drivers/datadog_driver.rb
Labels: PR: unreviewed

#12918 Mitigate service explosion in Datadog
  app/lib/forem_stats_drivers/datadog_driver.rb
Labels: PR: reviewed-approved

#12886 RFC#50-P2 Restructuring the sidebar to add nested nav items + tabbed nav items
  app/helpers/admin_helper.rb
  app/lib/menu.rb
  app/models/admin_menu.rb
  app/views/admin/badges/index.html.erb
  app/views/admin/secrets/index.html.erb
  app/views/admin/shared/_nested_sidebar.erb
  app/views/admin/shared/_tabbed_navbar.erb
  app/views/layouts/admin.html.erb
  config/routes.rb
  spec/requests/admin/nested_sidebar_spec.rb
Labels: PR: partially-approved

#12935 [Hotfix] Restore article content in RSS feed
  app/models/article.rb
  spec/models/article_spec.rb
Labels: PR: partially-approved

#12941 Fix ddtrace warnings at app start
  app/lib/forem_stats_drivers/datadog_driver.rb
Labels: PR: partially-approved

#12915 Hide mod button in mobile
  app/views/layouts/_top_bar.html.erb
Labels: PR: partially-approved

#12950 Add myself as a core contributor in the readme
  README.md
Labels: PR: reviewed-approved

#12838 Adding note about crayons design system in forem docs
  docs/frontend/styles.md
Labels: PR: reviewed-approved

#12951 Update README core team
  README.md
Labels: PR: unreviewed

#12919 [15 Minute Fix]: Ensure crayons banners are accessible
  app/views/chat_channel_memberships/index.html.erb
  app/views/layouts/application.html.erb
  app/views/moderations/mod.html.erb
  app/views/partnerships/_flashes.html.erb
  app/views/users/edit.html.erb
Labels: PR: reviewed-approved

#12953 Add exceptions to service worker navigation preload
  app/views/service_worker/index.js.erb
Labels: PR: partially-approved, merge by any core

#12913 Articles update refactoring
  app/controllers/api/v0/articles_controller.rb
  app/controllers/articles_controller.rb
  app/services/articles/attributes.rb
  app/services/articles/updater.rb
  spec/requests/api/v0/articles_spec.rb
  spec/requests/articles/articles_update_spec.rb
  spec/services/articles/attributes_spec.rb
  spec/services/articles/updater_spec.rb
Labels: PR: reviewed-approved

#12938 [15 min fix] Adopt session cookie configuration for remember me cookie
  config/initializers/devise.rb
Labels: PR: reviewed-approved

#12963 Bump imgproxy to 2.0
  Gemfile
  Gemfile.lock
  app/services/images/optimizer.rb
  config/initializers/1_imgproxy.rb
  lib/data_update_scripts/20210305222641_resave_users_for_imgproxy_update.rb
  spec/services/images/optimizer_spec.rb
  vendor/cache/anyway_config-2.1.0.gem
  vendor/cache/imgproxy-1.2.0.gem
  vendor/cache/imgproxy-2.0.0.gem
  vendor/cache/ruby-next-core-0.12.0.gem
Labels: PR: partially-approved

#12970 Revert "Adopt session cookie configuration for remember me cookie"
  config/initializers/devise.rb
Labels: PR: reviewed-approved

#12964 Improve UI design through small spacing tweaks
  app/views/admin/overview/index.html.erb
Labels: PR: partially-approved

#12971 Adds more exceptions to SW paths
  app/views/service_worker/index.js.erb
Labels: PR: partially-approved

#12972 Bump MAX_USER_MENTION_LIVE_AT in comment model
  app/models/comment.rb
Labels: PR: partially-approved

#12937 [Search 2.0] Add Search::Postgres::Tag behind a feature flag
  app/controllers/search_controller.rb
  app/models/tag.rb
  app/services/search/postgres/tag.rb
  db/migrate/20210310154630_add_index_to_tags_supported.rb
  db/schema.rb
  spec/requests/search_spec.rb
  spec/services/search/postgres/tag_spec.rb
Labels: PR: partially-approved

#12920 Fix : background box of the button on profile via chat section issue 2nd PR: #12879
  app/assets/stylesheets/chat.scss
  app/javascript/chat/content.jsx
  app/javascript/chat/videoContent.jsx
Labels: PR: partially-approved

#12982 Add SENDGRID_API_KEY to .env_sample
  .env_sample
Labels: PR: partially-approved

#12419 Add mobile push notifications to Forem
  .env_sample
  .gitignore
  Gemfile
  Gemfile.lock
  app/controllers/api/v0/health_checks_controller.rb
  app/controllers/devices_controller.rb
  app/lib/forem_stats_drivers/datadog_driver.rb
  app/models/device.rb
  app/models/site_config.rb
  app/models/user.rb
  app/services/push_notifications/send.rb
  app/workers/push_notifications/cleanup_worker.rb
  app/workers/push_notifications/deliver_worker.rb
  config/initializers/rpush.rb
  config/routes.rb
  config/schedule.yml
  db/migrate/20210120192313_create_devices.rb
  db/schema.rb
  spec/factories/devices.rb
  spec/routing/devices_routes_spec.rb
  spec/services/push_notifications/send_spec.rb
  vendor/cache/hiredis-0.6.3.gem
  vendor/cache/hkdf-0.3.0.gem
  vendor/cache/http-2-0.11.0.gem
  vendor/cache/modis-3.3.0.gem
  vendor/cache/net-http-persistent-4.0.1.gem
  vendor/cache/net-http2-0.18.4.gem
  vendor/cache/rpush-5.3.0.gem
  vendor/cache/rpush-redis-1.1.0.gem
  vendor/cache/webpush-1.1.0.gem
Labels: PR: unreviewed

#12925 Add rate limit for new user comments
  app/controllers/comments_controller.rb
  app/helpers/rate_limit_checker_helper.rb
  app/models/site_config.rb
  app/services/rate_limit_checker.rb
  spec/requests/comments_create_spec.rb
  spec/services/rate_limit_checker_spec.rb
  spec/system/comments/user_fills_out_comment_spec.rb
Labels: PR: partially-approved

#12986 Turned off the deprecated no-onchange rule of the jsx-a11y eslint plugin.
  app/javascript/.eslintrc.js
Labels: PR: partially-approved, merge by any core, tech: javascript

#12985 Add test for DevicesController
  app/controllers/devices_controller.rb
  spec/requests/devices_spec.rb
Labels: PR: unreviewed

#12952 Update the UI for Low-Quality-Comments Notice
  app/assets/stylesheets/views/comments.scss
  app/views/comments/_comment_proper.html.erb
  app/views/comments/_comment_quality_marker.html.erb
  app/views/comments/deleted_commentable_comment.html.erb
  spec/views/comments/_comment.html.erb_spec.rb
Labels: PR: unreviewed

#12988 Nullify fetch_format for Imgproxy
  app/services/images/optimizer.rb
Labels: PR: partially-approved

#12983 reenable article rescoring when moderators flag users
  app/services/moderator/sink_articles.rb
  app/workers/moderator/sink_articles_worker.rb
  spec/services/moderator/sink_articles_spec.rb
Labels: PR: partially-approved

#12974 Removed service worker
  .env_sample
  app/assets/javascripts/base.js.erb
  app/assets/javascripts/serviceworker-companion.js
  app/controllers/application_controller.rb
  app/controllers/pages_controller.rb
  app/controllers/registrations_controller.rb
  app/controllers/service_worker_controller.rb
  app/helpers/application_helper.rb
  app/lib/url.rb
  app/views/articles/show.html.erb
  app/views/layouts/application.html.erb
  app/views/service_worker/index.js.erb
  app/views/service_worker/manifest.json.erb
  app/views/shell/_bottom.html.erb
  app/views/shell/_top.html.erb
  config/routes.rb
  docs/frontend/tips.md
  docs/technical-overview/architecture.md
  lib/tasks/cache.rake
  public/offline.html
  spec/helpers/application_helper_spec.rb
  spec/requests/pages_spec.rb
  spec/requests/service_worker_spec.rb
  spec/requests/shells_spec.rb
Labels: PR: unreviewed, area: service worker, merge by any core, tech: fullstack

#13014 Revert "Removed service worker"
  .env_sample
  app/assets/javascripts/base.js.erb
  app/assets/javascripts/serviceworker-companion.js
  app/controllers/application_controller.rb
  app/controllers/pages_controller.rb
  app/controllers/registrations_controller.rb
  app/controllers/service_worker_controller.rb
  app/helpers/application_helper.rb
  app/lib/url.rb
  app/views/articles/show.html.erb
  app/views/layouts/application.html.erb
  app/views/service_worker/index.js.erb
  app/views/service_worker/manifest.json.erb
  app/views/shell/_bottom.html.erb
  app/views/shell/_top.html.erb
  config/routes.rb
  docs/frontend/tips.md
  docs/technical-overview/architecture.md
  lib/tasks/cache.rake
  public/offline.html
  spec/helpers/application_helper_spec.rb
  spec/requests/pages_spec.rb
  spec/requests/service_worker_spec.rb
  spec/requests/shells_spec.rb
Labels: PR: partially-approved

#13010 Only check cache or database once
  app/models/user.rb
  spec/models/user_spec.rb
Labels: PR: reviewed-approved

#12839 Fix github issue liquid tag styles
  app/assets/stylesheets/ltags/GithubTag.scss
Labels: PR: partially-approved

#13015 Revert "Revert "Removed service worker (#12974)" (#13014)"
  .env_sample
  app/assets/javascripts/base.js.erb
  app/assets/javascripts/serviceworker-companion.js
  app/controllers/application_controller.rb
  app/controllers/pages_controller.rb
  app/controllers/registrations_controller.rb
  app/controllers/service_worker_controller.rb
  app/helpers/application_helper.rb
  app/lib/url.rb
  app/views/articles/show.html.erb
  app/views/layouts/application.html.erb
  app/views/service_worker/index.js.erb
  app/views/service_worker/manifest.json.erb
  app/views/shell/_bottom.html.erb
  app/views/shell/_top.html.erb
  config/routes.rb
  docs/frontend/tips.md
  docs/technical-overview/architecture.md
  lib/tasks/cache.rake
  public/offline.html
  spec/helpers/application_helper_spec.rb
  spec/requests/pages_spec.rb
  spec/requests/service_worker_spec.rb
  spec/requests/shells_spec.rb
Labels: PR: partially-approved, area: service worker, tech: fullstack

#13013 Add and document COVERAGE environment variable in the sample
  .env_sample
Labels: PR: partially-approved

#12980 Update storybook autocomplete component
  app/assets/stylesheets/base/helpers.scss
  app/assets/stylesheets/components/autocomplete.scss
  app/javascript/crayons/MentionAutocomplete/MentionAutocomplete.jsx
  app/javascript/crayons/MentionAutocomplete/MentionAutocompleteCombobox.jsx
  app/javascript/crayons/MentionAutocomplete/__stories__/MentionAutocomplete.stories.jsx
  app/javascript/crayons/MentionAutocomplete/__stories__/mention-autocomplete.md
  app/javascript/crayons/MentionAutocomplete/__tests__/MentionAutocomplete.test.jsx
  app/javascript/crayons/MentionAutocomplete/__tests__/MentionAutocompleteCombobox.test.jsx
  app/javascript/crayons/MentionAutocomplete/__tests__/__snapshots__/MentionAutocompleteCombobox.test.jsx.snap
  app/javascript/crayons/MentionAutocomplete/index.js
  app/javascript/crayons/MentionAutocompleteTextArea/MentionAutocompleteTextArea.jsx
  app/javascript/crayons/MentionAutocompleteTextArea/__stories__/MentionAutocompleteTextArea.stories.jsx
  app/javascript/crayons/MentionAutocompleteTextArea/__stories__/mention-autocomplete.md
  app/javascript/crayons/MentionAutocompleteTextArea/__tests__/MentionAutocompleteTextArea.test.jsx
  app/javascript/crayons/MentionAutocompleteTextArea/__tests__/__snapshots__/MentionAutocompleteTextArea.test.jsx.snap
  app/javascript/crayons/MentionAutocompleteTextArea/index.js
  app/javascript/utilities/__tests__/textAreaUtils.test.js
  app/javascript/utilities/textAreaUtils.js
  config/webpack/environment.js
Labels: PR: reviewed-approved

#13025 Configure bundler to ignore Rpush install message
  bin/setup
Labels: PR: partially-approved

#12979 Remove experimental /call functionality from Connect ✂️✂️✂️
  Gemfile
  Gemfile.lock
  app/controllers/twilio_tokens_controller.rb
  app/controllers/video_chats_controller.rb
  app/javascript/chat/__tests__/VideoContent.test.jsx
  app/javascript/chat/chat.jsx
  app/javascript/chat/content.jsx
  app/javascript/chat/videoContent.jsx
  app/javascript/packs/videoChat.jsx
  app/models/message.rb
  app/services/twilio/get_jwt_token.rb
  app/views/video_chats/show.html.erb
  config/routes.rb
  package.json
  spec/models/message_spec.rb
  spec/requests/twilio_tokens_spec.rb
  spec/requests/video_chats_spec.rb
  spec/services/twilio/get_jwt_token_spec.rb
  vendor/cache/twilio-ruby-5.48.0.gem
  yarn.lock
Labels: PR: partially-approved, merge by any core

#12836 Fix github readme liquid tag
  app/assets/stylesheets/ltags/GithubReadmeTag.scss
Labels: PR: partially-approved

#12975 [Search 2.0] Add Search::Postgres::Username behind a feature flag
  app/controllers/search_controller.rb
  app/models/user.rb
  app/services/search/postgres/username.rb
  app/services/search/user.rb
  db/migrate/20210312191925_add_username_tsvector_index_to_users.rb
  db/schema.rb
  spec/requests/search_spec.rb
  spec/services/search/postgres/username_spec.rb
  spec/services/search/user_spec.rb
Labels: PR: unreviewed

#13027 Revert "Update storybook autocomplete component (#12980)"
  app/assets/stylesheets/base/helpers.scss
  app/assets/stylesheets/components/autocomplete.scss
  app/javascript/crayons/MentionAutocomplete/MentionAutocomplete.jsx
  app/javascript/crayons/MentionAutocomplete/MentionAutocompleteCombobox.jsx
  app/javascript/crayons/MentionAutocomplete/__stories__/MentionAutocomplete.stories.jsx
  app/javascript/crayons/MentionAutocomplete/__stories__/mention-autocomplete.md
  app/javascript/crayons/MentionAutocomplete/__tests__/MentionAutocomplete.test.jsx
  app/javascript/crayons/MentionAutocomplete/__tests__/MentionAutocompleteCombobox.test.jsx
  app/javascript/crayons/MentionAutocomplete/__tests__/__snapshots__/MentionAutocompleteCombobox.test.jsx.snap
  app/javascript/crayons/MentionAutocomplete/index.js
  app/javascript/crayons/MentionAutocompleteTextArea/MentionAutocompleteTextArea.jsx
  app/javascript/crayons/MentionAutocompleteTextArea/__stories__/MentionAutocompleteTextArea.stories.jsx
  app/javascript/crayons/MentionAutocompleteTextArea/__stories__/mention-autocomplete.md
  app/javascript/crayons/MentionAutocompleteTextArea/__tests__/MentionAutocompleteTextArea.test.jsx
  app/javascript/crayons/MentionAutocompleteTextArea/__tests__/__snapshots__/MentionAutocompleteTextArea.test.jsx.snap
  app/javascript/crayons/MentionAutocompleteTextArea/index.js
  app/javascript/utilities/__tests__/textAreaUtils.test.js
  app/javascript/utilities/textAreaUtils.js
  config/webpack/environment.js
Labels: PR: unreviewed, merge by any core

#13032 Disabled 'no default exports' rule for Storybook files and Stimulus controllers
  .eslintrc.js
  app/javascript/admin/controllers/ahoy_controller.js
  app/javascript/admin/controllers/article_controller.js
  app/javascript/admin/controllers/buffer_controller.js
  app/javascript/admin/controllers/config_controller.js
  app/javascript/admin/controllers/data_update_script_controller.js
  app/javascript/admin/controllers/image_upload_controller.js
  app/javascript/admin/controllers/modal_controller.js
  app/javascript/admin/controllers/reaction_controller.js
Labels: PR: partially-approved, area: developer experience, merge by any core, tech: javascript

#13022 Use faster serializers for Search::Postgres::Tag
  app/services/search/postgres/tag.rb
  spec/services/search/postgres/tag_spec.rb
Labels: PR: partially-approved

#13034 Get the correct episode by finding the given podcast's episodes
  app/controllers/stories_controller.rb
  spec/requests/podcasts/podcast_episodes_index_spec.rb
  spec/requests/podcasts/podcast_episodes_show_spec.rb
Labels: PR: partially-approved, area: podcasts

#13035 Use normal db transactions around tests
  Gemfile
  Gemfile.lock
  spec/services/feeds/import_spec.rb
  spec/support/database_cleaner.rb
  spec/system/dashboards/user_sorts_dashboard_articles_spec.rb
  vendor/cache/database_cleaner-active_record-2.0.0.gem
  vendor/cache/database_cleaner-core-2.0.0.gem
Labels: PR: partially-approved

#13009 When updating article scores, use new score for blackbox
  app/models/article.rb
  spec/models/article_spec.rb
Labels: PR: partially-approved

#13003 Add settings model generator
  config/initializers/zeitwerk.rb
  lib/generators/settings_model/USAGE
  lib/generators/settings_model/settings_model_generator.rb
  lib/generators/settings_model/templates/migration.erb
  lib/generators/settings_model/templates/model.erb
Labels: PR: partially-approved, merge by any core

#13050 Fix async useEffect warning
  app/javascript/crayons/MentionAutocompleteTextArea/MentionAutocompleteTextArea.jsx
Labels: PR: partially-approved

#13053 Add missing CSS class
  app/javascript/article-form/components/Options.jsx
Labels: PR: partially-approved

#13062 Removed the start-server-and-test npm package as it's no longer used
  package.json
  yarn.lock
Labels: PR: partially-approved

#13045 Add skip link functionality to article page
  app/views/articles/show.html.erb
Labels: PR: partially-approved

#13029 Use faster serializers for Search::Postgres::Username
  app/serializers/search/username_serializer.rb
  app/services/search/postgres/username.rb
  spec/services/search/postgres/username_spec.rb
Labels: PR: partially-approved

#13036 Change PushNotifications::Send to use user_ids
  app/controllers/devices_controller.rb
  app/services/notifications/new_comment/send.rb
  app/services/push_notifications/send.rb
  spec/requests/devices_spec.rb
  spec/services/notifications/new_comment/send_spec.rb
  spec/services/push_notifications/send_spec.rb
Labels: PR: unreviewed

#12978 ✂️ Remove the approvals gem ✂️
  .travis.yml
  Gemfile
  Gemfile.lock
  docs/tests/approvals-tests.md
  docs/tests/readme.md
  spec/fixtures/approvals/katextag/render/generates_katex_output.approved.html
  spec/fixtures/approvals/parlertag/id/accepts_a_valid_parler_url.approved.html
  spec/liquid_tags/codepen_tag_spec.rb
  spec/liquid_tags/comment_tag_spec.rb
  spec/liquid_tags/details_tag_spec.rb
  spec/liquid_tags/dotnet_fiddle_tag_spec.rb
  spec/liquid_tags/instagram_tag_spec.rb
  spec/liquid_tags/js_fiddle_tag_spec.rb
  spec/liquid_tags/jsitor_tag_spec.rb
  spec/liquid_tags/katex_tag_spec.rb
  spec/liquid_tags/kotlin_tag_spec.rb
  spec/liquid_tags/next_tech_tag_spec.rb
  spec/liquid_tags/parler_tag_spec.rb
  spec/liquid_tags/runkit_tag_spec.rb
  spec/liquid_tags/soundcloud_tag_spec.rb
  spec/liquid_tags/tweet_tag_spec.rb
  spec/liquid_tags/user_tag_spec.rb
  spec/liquid_tags/wikipedia_tag_spec.rb
  spec/liquid_tags/youtube_tag_spec.rb
  spec/models/github_issue_spec.rb
  spec/services/feeds/import_spec.rb
  spec/support/fixtures/approvals/codepen_liquid_tag.approved.html
  spec/support/fixtures/approvals/details_liquid_tag_spec.approved.html
  spec/support/fixtures/approvals/dotnetfiddle_liquid_tag.approved.html
  spec/support/fixtures/approvals/email_subscriptionsunsubscribe.approved.html
  spec/support/fixtures/approvals/instagram_liquid_tag.approved.html
  spec/support/fixtures/approvals/jsfiddle_liquid_tag.approved.html
  spec/support/fixtures/approvals/jsitor_liquid_tag.approved.html
  spec/support/fixtures/approvals/jsitor_liquid_tag_with_hyphen.approved.html
  spec/support/fixtures/approvals/jsitor_liquid_tag_with_params.approved.html
  spec/support/fixtures/approvals/kotlin_liquid_tag.approved.html
  spec/support/fixtures/approvals/nexttech_liquid_tag.approved.html
  spec/support/fixtures/approvals/runkit_liquid_tag_spec.approved.html
  spec/support/fixtures/approvals/soundcloud_liquid_tag.approved.html
  spec/support/fixtures/approvals/user_preview_article_body.approved.html
  spec/support/fixtures/approvals/user_submit_article.approved.html
  spec/support/fixtures/approvals/youtube_liquid_tag_no_time.approved.html
  spec/support/fixtures/approvals/youtube_liquid_tag_no_time_trailing_space.approved.html
  spec/support/fixtures/approvals/youtube_liquid_tag_with_time.approved.html
  spec/support/initializers/approvals.rb
  spec/system/user_uses_the_editor_spec.rb
  spec/views/email_subscriptions/unsubscribe.html.erb_spec.rb
  vendor/cache/approvals-0.0.24.gem
Labels: PR: unreviewed

#13061 Add (updated) mention autocomplete to post comments
  app/assets/javascripts/initializers/initializeCommentsPage.js.erb
  app/javascript/crayons/MentionAutocompleteTextArea/MentionAutocompleteTextArea.jsx
  app/javascript/crayons/MentionAutocompleteTextArea/__tests__/__snapshots__/MentionAutocompleteTextArea.test.jsx.snap
  app/javascript/packs/base.jsx
  app/javascript/utilities/textAreaUtils.js
  app/views/notifications/shared/_comment_box.html.erb
  cypress/fixtures/search/emptyUsernamesSearch.json
  cypress/fixtures/search/usernames.json
  cypress/integration/articleFlows/commentOnArticle.spec.js
Labels: PR: partially-approved

#13065 15 min fix - update closing tag in podcast episodes
  app/views/podcast_episodes/index.html.erb
Labels: PR: reviewed-approved

#13082 Refactor reach UI style import
  app/assets/stylesheets/components/autocomplete.scss
  app/javascript/crayons/MentionAutocompleteTextArea/MentionAutocompleteTextArea.jsx
Labels: PR: partially-approved

#13011 Re-Add Reporter Email Form to /admin/reports
  app/helpers/feedback_messages_helper.rb
  app/views/admin/feedback_messages/_feedback_message.html.erb
  spec/helpers/feedback_messages_helper_spec.rb
Labels: PR: partially-approved

#13083 small fix to import of reach styles
  app/assets/stylesheets/components/autocomplete.scss
Labels: PR: partially-approved

#13081 Remove deprecated Sidekiq::Web commands
  config/routes.rb
Labels: PR: reviewed-approved

#13046 Add skip link functionality to tags page
  app/views/tags/index.html.erb
Labels: PR: partially-approved

#13067 Upgrade gitdocs's axios dependency
  package.json
  yarn.lock
Labels: PR: unreviewed

#13086 Update http-parser and ffi gems so Forem can load on an Apple M1
  Gemfile.lock
  vendor/cache/ffi-1.14.2.gem
  vendor/cache/ffi-1.15.0.gem
  vendor/cache/http-parser-1.2.2.gem
  vendor/cache/http-parser-1.2.3.gem
Labels: PR: partially-approved

#13087 [15 Minute Fix] Adjust Inline Comment in /admin/tools
  app/views/admin/shared/_image_uploader.html.erb
Labels: PR: partially-approved

#12999 Make definition of new user configurable
  app/controllers/comments_controller.rb
  app/decorators/user_decorator.rb
  app/helpers/rate_limit_checker_helper.rb
  app/lib/constants/site_config.rb
  app/models/site_config.rb
  app/services/articles/creator.rb
  app/views/admin/configs/show.html.erb
  spec/decorators/user_decorator_spec.rb
Labels: PR: unreviewed, merge by any core

#12967 RFC#50-P4: Feature Flagged Routes and Interaction Design
  app/assets/stylesheets/admin.scss
  app/javascript/admin/__tests__/controllers/sidebar_controller.test.js
  app/javascript/admin/controllers/sidebar_controller.js
  app/lib/menu.rb
  app/models/admin_menu.rb
  app/views/admin/shared/_nested_sidebar.html.erb
  app/views/admin/shared/_tabbed_navbar.html.erb
  app/views/layouts/admin.html.erb
  config/routes.rb
  spec/requests/admin/nested_sidebar_spec.rb
Labels: PR: unreviewed

#13024 Ensure user data is unset if no user is logged in
  app/assets/javascripts/initializers/initializeBodyData.js
  cypress/integration/loginFlows/userLogout.spec.js
Labels: PR: partially-approved

#13071 Optimize `Article.published` scope to use an index
  app/models/article.rb
  spec/factories/articles.rb
  spec/models/article_spec.rb
  spec/requests/api/v0/articles_spec.rb
  spec/requests/articles/articles_update_spec.rb
  spec/services/articles/updater_spec.rb
Labels: PR: partially-approved

#13100 Destroy user's sponsorships when destroying the user
  app/models/user.rb
  spec/services/users/delete_spec.rb
Labels: PR: reviewed-approved

#13102 Add an index to users.old_username
  db/migrate/20210323190443_add_indexes_to_old_usernames.rb
  db/schema.rb
Labels: PR: partially-approved

#13103 Disable the User Fills Out Comment system spec
  spec/system/comments/user_fills_out_comment_spec.rb
Labels: PR: partially-approved

#13098 [15 Minute Fix] Added the prefer-const eslint rule
  app/javascript/.eslintrc.js
  app/javascript/admin/controllers/ahoy_controller.js
  app/javascript/admin/controllers/data_update_script_controller.js
  app/javascript/admin/controllers/image_upload_controller.js
  app/javascript/chat/chat.jsx
  app/javascript/packs/dashboardTagsDisableUnchangedButtons.js
  app/javascript/shared/components/useKeyboardShortcuts.js
  app/javascript/topNavigation/utilities.js
  app/javascript/utilities/codeFullscreenModeSwitcher.js
  cypress/.eslintrc.js
Labels: PR: partially-approved, area: developer experience, merge by any core, tech: javascript

#12993 Remove buffer gem and related code: step 1
  Gemfile
  Gemfile.lock
  app/assets/stylesheets/admin.scss
  app/controllers/admin/articles_controller.rb
  app/controllers/admin/buffer_updates_controller.rb
  app/controllers/articles_controller.rb
  app/controllers/buffer_updates_controller.rb
  app/javascript/admin/__tests__/controllers/buffer_controller.test.js
  app/javascript/admin/__tests__/controllers/sidebar_controller.test.js
  app/javascript/admin/controllers/buffer_controller.js
  app/javascript/admin/controllers/sidebar_controller.js
  app/javascript/crayons/MentionAutocompleteTextArea/__stories__/mention-autocomplete.md
  app/lib/constants/role.rb
  app/models/article.rb
  app/models/listing.rb
  app/models/tag.rb
  app/models/user.rb
  app/policies/buffer_update_policy.rb
  app/services/bufferizer/facebook_post.rb
  app/services/bufferizer/listings_tweet.rb
  app/services/bufferizer/main_tweet.rb
  app/services/bufferizer/satellite_tweet.rb
  app/services/users/delete_articles.rb
  app/views/admin/articles/_individual_article.html.erb
  app/views/admin/articles/index.html.erb
  app/views/admin/listings/index.html.erb
  app/views/admin/shared/_nested_sidebar.html.erb
  app/views/admin/shared/_tabbed_navbar.html.erb
  app/views/articles/manage.html.erb
  app/views/layouts/admin.html.erb
  app/views/moderations/mod.html.erb
  config/routes.rb
  lib/data_update_scripts/20200825095213_remove_orphaned_buffer_updates_by_article.rb
  lib/data_update_scripts/20200910140109_cleanup_published_articles_with_duplicate_user_id_title_body_markdown.rb
  lib/data_update_scripts/20200917135847_nullify_orphan_rows_from_buffer_updates_by_composer_user_id.rb
  spec/factories/buffer_updates.rb
  spec/models/article_spec.rb
  spec/models/buffer_update_spec.rb
  spec/models/tag_spec.rb
  spec/models/user_spec.rb
  spec/policies/buffer_update_policy_spec.rb
  spec/rails_helper.rb
  spec/requests/admin/buffer_updates_spec.rb
  spec/requests/buffer_updates_spec.rb
  spec/services/bufferizer/facebook_post_spec.rb
  spec/services/bufferizer/listings_tweet_spec.rb
  spec/services/bufferizer/main_tweet_spec.rb
  spec/services/bufferizer/satellite_tweet_spec.rb
  spec/services/users/delete_articles_spec.rb
  spec/services/users/delete_spec.rb
  vendor/cache/buffer-0.1.3.gem
  vendor/cache/environs-1.1.0.gem
  vendor/cache/faraday_middleware-1.0.0.gem
  vendor/cache/yajl-ruby-1.4.1.gem
Labels: PR: unreviewed, merge by any core

#13073 Added credits_awarded to badges
  db/migrate/20210312095649_add_credits_awarded_to_badges.rb
  db/schema.rb
  lib/data_update_scripts/20210322092753_fill_badges_credits_awarded.rb
  spec/lib/data_update_scripts/fill_badges_credits_awarded_spec.rb
Labels: PR: reviewed-approved

#12633 Save valid attributes with ignoring the invalid ones
  app/controllers/profiles_controller.rb
Labels: PR: reviewed-approved

#13112 Add skip link functionality to code of conduct, terms and privacy pages
  app/views/pages/code_of_conduct.html.erb
  app/views/pages/privacy.html.erb
  app/views/pages/terms.html.erb
Labels: PR: partially-approved, merge by any core

#13026 Update shortcut code with best practices
  app/javascript/shared/components/useKeyboardShortcuts.js
Labels: PR: partially-approved

#13052 [Search 2.0] Reading list
  app/controllers/search_controller.rb
  app/javascript/readingList/readingList.jsx
  app/javascript/searchableItemList/searchableItemList.js
  app/models/article.rb
  app/models/tag.rb
  app/serializers/search/reading_list_article_serializer.rb
  app/services/search/postgres/reading_list.rb
  db/migrate/20210319185315_add_index_to_reactions_status.rb
  db/migrate/20210322152837_add_index_to_articles_cached_tag_list.rb
  db/schema.rb
  spec/requests/search_spec.rb
  spec/services/search/postgres/reading_list_spec.rb
Labels: PR: partially-approved

#13104 Remove buffer columns and buffer_updates table
  app/models/buffer_update.rb
  db/migrate/20210324031252_remove_buffer_columns.rb
  db/migrate/20210324031738_remove_buffer_updates.rb
  db/schema.rb
Labels: PR: partially-approved, merge by any core

#13117 Revert "Bump dogstatsd-ruby from 4.8.3 to 4.9.0 (#13110)"
  Gemfile
  Gemfile.lock
  vendor/cache/dogstatsd-ruby-4.8.3.gem
  vendor/cache/dogstatsd-ruby-4.9.0.gem
Labels: PR: partially-approved

#13023 Add rake task to collect admin overview metrics
  app/models/ahoy/event.rb
  lib/tasks/metrics.rake
Labels: PR: partially-approved

#9561 Connect room name overflow
  app/assets/stylesheets/chat.scss
  app/javascript/chat/ChatChannelSettings/ChannelDescriptionSection.jsx
Labels: PR: reviewed-approved

#13111 Add skip link to notifications page
  app/views/notifications/index.html.erb
Labels: PR: partially-approved, merge by any core

#13115 Add skip link functionality to dashboard pages
  app/views/collections/index.html.erb
  app/views/dashboards/followers.html.erb
  app/views/dashboards/following_organizations.html.erb
  app/views/dashboards/following_podcasts.html.erb
  app/views/dashboards/following_tags.html.erb
  app/views/dashboards/following_users.html.erb
  app/views/dashboards/show.html.erb
  app/views/listings/dashboard.html.erb
Labels: PR: partially-approved, merge by any core

#13120 Add a GIN index on `comments.ancestry`
  db/migrate/20210325040245_add_trigram_index_to_comments_ancestry.rb
  db/schema.rb
Labels: PR: partially-approved, merge by any core

#12942 Part 2: Shows Relevant Posts in Homepage Sidebar
  app/helpers/articles_helper.rb
  app/models/article.rb
  app/queries/articles/active_threads_query.rb
  app/views/articles/tags/_sidebar_additional.html.erb
  app/views/sidebars/_homepage_content.html.erb
  spec/queries/articles/active_threads_query_spec.rb
Labels: PR: reviewed-approved

#13116 Revert "Add (updated) mention autocomplete to post comments (#13061)"
  app/assets/javascripts/initializers/initializeCommentsPage.js.erb
  app/javascript/crayons/MentionAutocompleteTextArea/MentionAutocompleteTextArea.jsx
  app/javascript/crayons/MentionAutocompleteTextArea/__tests__/__snapshots__/MentionAutocompleteTextArea.test.jsx.snap
  app/javascript/packs/base.jsx
  app/javascript/utilities/textAreaUtils.js
  app/views/notifications/shared/_comment_box.html.erb
  cypress/fixtures/search/emptyUsernamesSearch.json
  cypress/fixtures/search/usernames.json
  cypress/integration/articleFlows/commentOnArticle.spec.js
Labels: PR: partially-approved, area: comments, merge by any core, tech: fullstack

#12612 Fix more button not working after navigating back to the home page
  app/javascript/packs/base.jsx
  app/javascript/topNavigation/utilities.js
  cypress/integration/adminFlows/navigationLinks/navigationLinks.spec.js
  cypress/integration/navigationFlows/homePageLeftSidebar.spec.js
  spec/support/seeds/seeds_e2e.rb
Labels: PR: unreviewed

#13132 [15-Minute Fix] Adds Flash Messages to Indicate Successful Actions for Pages
  app/controllers/admin/pages_controller.rb
Labels: PR: partially-approved

#13129 Sanitize Rpush iOS PEM certificate
  app/models/device.rb
Labels: PR: partially-approved

#13007 Feature: Runtime Content Filter
  app/assets/javascripts/initializePage.js
  app/assets/javascripts/initializers/runtime.js
  app/assets/stylesheets/minimal.scss
  app/assets/stylesheets/runtime-banner.scss
  app/assets/stylesheets/runtime.scss
  app/views/layouts/application.html.erb
  cypress/integration/loggedOutFlows/runtimeContext.spec.js
  spec/requests/registrations_spec.rb
  spec/system/user/user_edits_profile_spec.rb
Labels: PR: partially-approved

#13138 [15 Min Fix]: Fix incorrect scope used by metrics:overview rake task
  app/models/ahoy/event.rb
  lib/tasks/metrics.rake
  spec/tasks/metrics_spec.rb
Labels: PR: partially-approved

#13113 Add skip link functionality to videos
  app/assets/javascripts/initializers/initScrolling.js
  app/views/videos/index.html.erb
Labels: PR: reviewed-approved, merge by any core

#13130 Shortcuts: Fix search confusion
  app/javascript/Search/Search.jsx
Labels: PR: partially-approved

#13126 Re-add mention autocomplete to comments, fixing bugs
  app/assets/javascripts/initializers/initializeCommentsPage.js.erb
  app/assets/stylesheets/components/autocomplete.scss
  app/javascript/crayons/MentionAutocompleteTextArea/MentionAutocompleteTextArea.jsx
  app/javascript/crayons/MentionAutocompleteTextArea/__tests__/MentionAutocompleteTextArea.test.jsx
  app/javascript/crayons/MentionAutocompleteTextArea/__tests__/__snapshots__/MentionAutocompleteTextArea.test.jsx.snap
  app/javascript/packs/base.jsx
  app/javascript/utilities/textAreaUtils.js
  app/views/notifications/shared/_comment_box.html.erb
  cypress/fixtures/search/emptyUsernamesSearch.json
  cypress/fixtures/search/usernames.json
  cypress/integration/articleFlows/commentOnArticle.spec.js
Labels: PR: unreviewed

#13135 RFC #74, Pt.1: Add landing_page to the Pages Table
  db/migrate/20210325183834_add_landing_page_to_pages.rb
  db/schema.rb
Labels: PR: partially-approved

#13147 15 min fix - improve reliability of autocomplete cypress test
  app/views/articles/_full_comment_area.html.erb
  cypress/integration/articleFlows/commentOnArticle.spec.js
Labels: PR: partially-approved, merge by any core

#13139 Remove ignored Buffer columns
  app/models/article.rb
  app/models/listing.rb
  app/models/tag.rb
Labels: PR: partially-approved

#13152 [15 minute fix] Rename previewArticle.js to previewArticle.spec.js
  cypress/integration/publishingFlows/previewArticle.spec.js
Labels: PR: partially-approved, area: tests, merge by any core

#13153 Instrument EmailDigestArticleCollector
  app/services/email_digest_article_collector.rb
  app/services/instrumentation.rb
Labels: PR: partially-approved

#13163 make clean_fork script executable
  scripts/clean_fork.sh
Labels: PR: reviewed-approved

#13169 Enable instrumentation for Heroku scheduler
  datadog/prerun.sh
Labels: PR: partially-approved

#13136 Update to use Node 14.x
  .nvmrc
  package.json
Labels: PR: partially-approved

#13167 [15 Min Fix] Added the custom Cypress command, createResponseTemplate, to create comment templates.
  cypress/support/commands.js
  docs/tests/e2e-tests.md
Labels: PR: partially-approved, area: tests, merge by any core, tech: javascript

#13172 Skip a flaky e2e spec
  cypress/integration/articleFlows/commentOnArticle.spec.js
Labels: PR: reviewed-approved

#13133 [Search 2.0] Listings
  app/controllers/search_controller.rb
  app/models/listing.rb
  app/serializers/search/listing_result_serializer.rb
  app/services/search/postgres/listing.rb
  db/migrate/20210326172406_add_published_index_to_listings.rb
  db/schema.rb
  spec/requests/search_spec.rb
  spec/services/search/postgres/listing_spec.rb
Labels: PR: partially-approved

#13145 Configure badge credits by admins
  app/controllers/admin/badges_controller.rb
  app/models/badge_achievement.rb
  app/services/notifications/new_badge_achievement/send.rb
  app/views/admin/badges/edit.html.erb
  app/views/admin/badges/new.html.erb
  app/views/mailers/notify_mailer/new_badge_email.html.erb
  app/views/mailers/notify_mailer/new_badge_email.text.erb
  app/views/notifications/_badgeachievement.html.erb
  spec/mailers/notify_mailer_spec.rb
  spec/models/badge_achievement_spec.rb
  spec/requests/admin/badges_spec.rb
  spec/requests/notifications_spec.rb
  spec/services/notifications/new_badge_achievement/send_spec.rb
Labels: PR: partially-approved

#13149 [15 minute fix] Fixed bug with templates not being inserted for comments.
  app/assets/javascripts/initializers/initializeCommentsPage.js.erb
  app/javascript/responseTemplates/responseTemplates.js
  app/views/articles/_full_comment_area.html.erb
  cypress/integration/articleFlows/commentOnArticle.spec.js
  spec/support/seeds/seeds_e2e.rb
Labels: PR: partially-approved, area: comments, merge by any core, tech: frontend

#13146 [15 minute fix] Now mention auto-complete dynamic imports are cached.
  app/javascript/packs/base.jsx
Labels: PR: partially-approved, area: comments, merge by any core, tech: javascript

#13181 reinstate reply to comment e2e test
  app/javascript/crayons/MentionAutocompleteTextArea/MentionAutocompleteTextArea.jsx
  app/javascript/crayons/MentionAutocompleteTextArea/__tests__/__snapshots__/MentionAutocompleteTextArea.test.jsx.snap
  cypress/integration/articleFlows/commentOnArticle.spec.js
Labels: PR: unreviewed

#13186 [15 Min Fix]: Fix template error in badge achievement notification view
  app/views/notifications/_badgeachievement.html.erb
Labels: PR: unreviewed

#13187 [15 Min Fix] Got rid of some E2E test flakiness
  cypress/integration/articleFlows/commentOnArticle.spec.js
Labels: PR: partially-approved, area: comments, area: tests, merge by any core, tech: javascript

#13188 Bug Fix:Remove Suggest a Tweet since we no longer have that feature
  app/views/articles/manage.html.erb
Labels: PR: reviewed-approved

#13192 Doc Update: Remove no longer used tech from overview docs ✂️ ✂️ ✂️
  docs/technical-overview/stack.md
Labels: PR: partially-approved

#12768 User Settings Step 1: Add user_settings and user_notification_settings tables (rfc#32)
  app/models/user.rb
  app/models/users/notification_setting.rb
  app/models/users/setting.rb
  app/views/users/_customization.html.erb
  app/views/users/_navbar_selector.html.erb
  app/views/users/_theme_selector.html.erb
  db/migrate/20210222102503_create_users_settings.rb
  db/migrate/20210222102602_create_users_notification_settings.rb
  db/schema.rb
  spec/factories/users_setting.rb
  spec/models/user_spec.rb
  spec/models/users/setting_spec.rb
Labels: PR: unreviewed, merge by any core

#13101 Add mention autocomplete to posts
  app/javascript/article-form/components/EditorBody.jsx
  app/javascript/article-form/components/__tests__/Form.test.jsx
  app/javascript/crayons/MentionAutocompleteTextArea/MentionAutocompleteTextArea.jsx
  app/javascript/crayons/MentionAutocompleteTextArea/UserListItemContent.jsx
  app/javascript/crayons/MentionAutocompleteTextArea/__tests__/__snapshots__/MentionAutocompleteTextArea.test.jsx.snap
  app/javascript/utilities/calculateTextAreaHeight.js
  app/javascript/utilities/textAreaUtils.js
  cypress/integration/publishingFlows/mentionUser.js
Labels: PR: unreviewed, area: publishing experience, tech: frontend

#13196 Optimization:✂️ Remove Unused Twitter Counts from User ✂️
  app/models/user.rb
  app/services/authentication/providers/twitter.rb
  spec/models/user_spec.rb
  spec/services/authentication/authenticator_spec.rb
Labels: PR: partially-approved

#13191 [15 Min Fix] Added the no-only-tests eslint rule to the cypress eslint config
  cypress/.eslintrc.js
  package.json
  yarn.lock
Labels: PR: partially-approved, area: tests, merge by any core, tech: javascript

#13176 Remove pro role from database + pro users
  lib/data_update_scripts/20210329172336_remove_pro_roles.rb
Labels: PR: unreviewed

#13208 Optimization:Remove Twitter Counts From User Table in db
  app/models/user.rb
  db/migrate/20210331181505_remove_twitter_counts_from_user.rb
  db/schema.rb
Labels: PR: partially-approved
