Repository forem/forem, pull requests merged in 2021-10, with the labels that each got.

#14849 Modify capitalization of default navigation link
  lib/tasks/add_navigation_links.rake
Labels: PR: reviewed-approved, merge by any core

#14865 Add Forem Discover registration worker and service
  app/services/discover/register.rb
  app/workers/discover/register_worker.rb
  spec/services/discover/register_spec.rb
  spec/workers/discover/register_worker_spec.rb
Labels: PR: partially-approved

#14883 Added the creator method to the user model
  app/models/user.rb
Labels: PR: partially-approved, merge by any core

#14878 dont show rules for top tags
  app/javascript/shared/components/tags.jsx
  cypress/integration/seededFlows/publishingFlows/addTagsToArticle.spec.js
Labels: PR: partially-approved, merge by any core

#14884 Translate notification filters
  app/views/notifications/_nav_menu.html.erb
  config/locales/en.yml
  config/locales/fr.yml
Labels: PR: partially-approved

#14862 Heavy Confirmation Flow for DisplayAd-Destroy
  app/controllers/admin/display_ads_controller.rb
  app/javascript/admin/controllers/confirmation_modal_controller.js
  app/views/admin/display_ads/index.html.erb
  cypress/integration/seededFlows/adminFlows/displayAds/displayAds.spec.js
  spec/requests/admin/display_ads_spec.rb
  spec/support/seeds/seeds_e2e.rb
Labels: PR: unreviewed, include in changelog

#14912 Add DISABLE_SPRING to .travis.yml
  .travis.yml
Labels: PR: partially-approved

#14870 Add real release version into the running code
  app/controllers/api/v0/instances_controller.rb
  scripts/release
Labels: PR: partially-approved

#14855 Automatically log a creator in after they confirm their email
  app/controllers/confirmations_controller.rb
Labels: PR: partially-approved

#14887 Make dashboard left side nav an unordered list
  app/views/dashboards/_actions.html.erb
Labels: PR: partially-approved

#14890 Update some words already translated
  config/locales/fr.yml
Labels: PR: unreviewed

#14896 Replace main tag inside another main tag with div
  app/views/notifications/index.html.erb
Labels: PR: unreviewed

#14899 use complementary landmarks on Tags page
  app/views/stories/tagged_articles/_sidebar.html.erb
  app/views/stories/tagged_articles/_sidebar_additional.html.erb
Labels: PR: partially-approved

#14898 Translate Following users page and loading text in sublist
  app/views/dashboards/_sublist.html.erb
  app/views/dashboards/following_users.html.erb
  config/locales/en.yml
  config/locales/fr.yml
Labels: PR: partially-approved

#14902 Eager-load comment user data
  app/models/comment.rb
  app/views/comments/index.html.erb
Labels: PR: partially-approved

#14915 ✂️ Remove dead app shell code
  app/assets/stylesheets/scaffolds.scss
  app/controllers/application_controller.rb
  app/views/layouts/application.html.erb
Labels: PR: partially-approved, merge by any core

#14889 Fix Prop Types Error #14837
  app/javascript/CommentSubscription/CommentSubscription.jsx
  app/javascript/common-prop-types/default-children-prop-types.js
  app/javascript/crayons/ButtonGroup/ButtonGroup.jsx
  app/javascript/crayons/Modal/Modal.jsx
  app/javascript/packs/articlePage.jsx
Labels: PR: partially-approved

#14852 Misc i18n fixes
  config/i18n-tasks.yml
  config/locales/devise.en.yml
  config/locales/devise_invitable.en.yml
  config/locales/devise_invitable.fr.yml
  config/locales/doorkeeper.en.yml
  config/locales/en.yml
  config/locales/fr.yml
  config/locales/kaminari.fr.yml
  spec/i18n_spec.rb
Labels: PR: unreviewed

#14913 Remove organization dependency and improve display ad UX
  app/controllers/admin/display_ads_controller.rb
  app/models/display_ad.rb
  app/views/admin/display_ads/_form.html.erb
  app/views/admin/display_ads/edit.html.erb
  app/views/admin/display_ads/index.html.erb
  app/views/admin/display_ads/new.html.erb
  app/views/layouts/admin.html.erb
  spec/models/display_ad_spec.rb
  spec/requests/admin/display_ads_spec.rb
Labels: PR: partially-approved

#14895 Use constants for Permitted params in controller
  app/controllers/admin/articles_controller.rb
  app/controllers/admin/chat_channels_controller.rb
  app/controllers/admin/events_controller.rb
  app/controllers/feedback_messages_controller.rb
  app/controllers/organizations_controller.rb
  app/controllers/podcasts_controller.rb
  app/controllers/poll_skips_controller.rb
  app/controllers/poll_votes_controller.rb
  app/controllers/stripe_active_cards_controller.rb
  app/controllers/tags_controller.rb
Labels: PR: partially-approved

#14858 Add conditional autovomits to user name and improve user score recalc
  app/models/organization.rb
  app/models/user.rb
  app/views/users/_meta.html.erb
  app/views/users/show.html.erb
  app/workers/reactions/update_relevant_scores_worker.rb
  spec/models/user_spec.rb
  spec/workers/reactions/update_relevant_scores_worker_spec.rb
Labels: PR: partially-approved

#14916 Optimize `Article` query in `EdgeCache::BustArticle`
  app/services/edge_cache/bust_article.rb
Labels: PR: partially-approved

#14954 Fixed lint issue
  app/javascript/chat/chat.jsx
Labels: PR: partially-approved, tech: frontend, merge by any core

#14869 Upgrade Stimulus to 3.0
  app/controllers/admin/articles_controller.rb
  app/controllers/admin/display_ads_controller.rb
  app/javascript/admin/__tests__/controllers/article_controller.test.js
  app/javascript/admin/__tests__/controllers/config_controller.test.js
  app/javascript/admin/__tests__/controllers/data_update_script_controller.test.js
  app/javascript/admin/__tests__/controllers/sidebar_controller.test.js
  app/javascript/admin/controllers/ahoy_controller.js
  app/javascript/admin/controllers/alert_controller.js
  app/javascript/admin/controllers/article_controller.js
  app/javascript/admin/controllers/config_controller.js
  app/javascript/admin/controllers/consumer_app_controller.js
  app/javascript/admin/controllers/data_update_script_controller.js
  app/javascript/admin/controllers/image_upload_controller.js
  app/javascript/admin/controllers/modal_controller.js
  app/javascript/admin/controllers/reaction_controller.js
  app/javascript/admin/controllers/sidebar_controller.js
  app/javascript/admin/controllers/snackbar_controller.js
  app/javascript/admin/controllers/svg_icon_upload_controller.js
  app/javascript/admin/controllers/user_controller.js
  app/javascript/admin/controllers/users/tools/ajax_controller.js
  app/javascript/packs/admin.js
  app/views/admin/display_ads/_form.html.erb
  app/views/admin/display_ads/edit.html.erb
  app/views/users/_meta.html.erb
  app/workers/reactions/update_relevant_scores_worker.rb
  package.json
  yarn.lock
Labels: PR: unreviewed

#14947 Adding jeremyf to core team
  README.md
Labels: PR: reviewed-approved

#14226 Subscribe the newsletter if email_newsletter is changed
  app/models/users/notification_setting.rb
  spec/models/users/notification_setting_spec.rb
  spec/requests/user/user_notification_settings_spec.rb
Labels: PR: partially-approved

#14964 Change preview card hover delay
  app/assets/stylesheets/profile-preview-card.scss
Labels: PR: partially-approved

#14962 Auto register Forems on Discover
  app/controllers/api/v0/instances_controller.rb
  app/controllers/registrations_controller.rb
  spec/requests/api/v0/instances_spec.rb
  spec/requests/registrations_spec.rb
Labels: PR: partially-approved

#14873 Use section instead of header in dashboard pages
  app/views/dashboards/followers.html.erb
  app/views/dashboards/following_organizations.html.erb
  app/views/dashboards/following_podcasts.html.erb
  app/views/dashboards/following_tags.html.erb
  app/views/dashboards/following_users.html.erb
  app/views/dashboards/show.html.erb
  app/views/dashboards/subscriptions.html.erb
  spec/system/dashboards/user_visits_dashboard_spec.rb
Labels: PR: reviewed-approved

#14905 tokenize settings menu and add French translations
  app/controllers/users_controller.rb
  app/lib/constants/settings.rb
  app/lib/settings.rb
  app/views/users/edit.html.erb
  config/locales/en.yml
  config/locales/fr.yml
  spec/requests/user/user_settings_spec.rb
Labels: PR: reviewed-approved

#15226 Media Cards - CSS fix for border radius
  app/assets/stylesheets/components/media-cards.scss
Labels: PR: partially-approved, tech: frontend
