Repository forem/forem, pull requests merged in 2021-11, with the labels that each got.

#15133 [15-minute fix] Add js-routes gem
  Gemfile
  Gemfile.lock
  app/javascript/routes.js.erb
  config/initializers/js_routes.rb
  vendor/cache/js-routes-2.1.1.gem
Labels: PR: unreviewed

#15232 Escape the backslash in the regex string so the backslash is preserved
  app/views/admin/navigation_links/_form.html.erb
Labels: PR: partially-approved, merge by any core

#15154 locales/views/editor - added FR translation
  config/locales/views/editor/fr.yml
Labels: PR: partially-approved

#15243 Show reactions to the user, rather than user created reactions to other users
  app/controllers/admin/users_controller.rb
Labels: PR: partially-approved

#14728 Creator Onboarding: Creator Setup View
  app/assets/javascripts/initializers/initializeBodyData.js
  app/controllers/admin/creator_settings_controller.rb
  app/controllers/async_info_controller.rb
  app/javascript/packs/onboardingRedirectCheck.jsx
  app/models/creator_setting.rb
  app/views/admin/creator_settings/_form.html.erb
  app/views/admin/creator_settings/new.html.erb
  app/views/admin/users/edit.html.erb
  app/views/podcast_episodes/_episodes_feed.html.erb
  config/locales/views/misc/en.yml
  config/locales/views/misc/fr.yml
  config/routes/admin.rb
  cypress/integration/creatorOnboardingFlows/creatorSettings.spec.js
  cypress/integration/creatorOnboardingFlows/creatorSignup.spec.js
  cypress/support/commands.js
  spec/requests/admin/creator_settings_spec.rb
  spec/requests/async_info_spec.rb
Labels: PR: unreviewed, merge by any core

#15256 Compare the utc offset from the timestamp, not now
  spec/views/articles_spec.rb
Labels: PR: reviewed-approved

#15238 Fix typo
  config/webpack/development.js
Labels: PR: partially-approved

#15198 CSS cleanups
  app/assets/stylesheets/article-show.scss
  app/assets/stylesheets/articles.scss
  app/assets/stylesheets/components/profile-preview-card.scss
  app/assets/stylesheets/crayons.scss
  app/assets/stylesheets/live.scss
  app/assets/stylesheets/minimal.scss
  app/assets/stylesheets/scaffolds.scss
  app/assets/stylesheets/snackbars.scss
  app/assets/stylesheets/variables.scss
  app/javascript/readingList/readingList.jsx
Labels: PR: partially-approved, tech: frontend

#15273 Update the config/settings link for the help icon
  app/controllers/admin/application_controller.rb
Labels: PR: reviewed-approved, merge by any core

#15229 Refactoring to extract common interface
  app/controllers/stories/feeds_controller.rb
  app/services/articles/feeds/basic.rb
Labels: PR: partially-approved

#15090 Fix: cannot unpin articles using checkbox
  app/controllers/admin/articles_controller.rb
  app/javascript/admin/controllers/article_controller.js
  app/javascript/admin/controllers/article_pinned_modal_controller.js
  app/views/admin/articles/_individual_article.html.erb
  config/routes/admin.rb
  cypress/integration/seededFlows/adminFlows/articles/pinArticle.spec.js
  cypress/integration/seededFlows/adminFlows/articles/unpinArticle.spec.js
  spec/requests/admin/articles_spec.rb
Labels: PR: partially-approved

#15260 Disable all providers when `providers_to_enable` param is blank
  app/services/settings/authentication/upsert.rb
  spec/services/settings/authentication/upsert_spec.rb
Labels: PR: partially-approved

#14018 Added collapsed hidden comments to author's article/podcast episode view
  app/assets/javascripts/initializers/initializeCommentsPage.js.erb
  app/views/articles/show.html.erb
  app/views/comments/_comment.html.erb
  app/views/comments/_comment_quality_marker.html.erb
  app/views/comments/index.html.erb
  app/views/podcast_episodes/show.html.erb
  config/locales/views/comments/en.yml
  cypress/integration/seededFlows/articleFlows/hideArticleComments.spec.js
  cypress/integration/seededFlows/articleFlows/viewArticleDiscussion.spec.js
  spec/requests/comments_spec.rb
  spec/support/seeds/seeds_e2e.rb
Labels: PR: partially-approved

#15091 HTML tag and attribute matcher
  bin/untranslated_erb
Labels: PR: unreviewed

#15265 treat cmd and ctrl key shortcuts separately on macOS
  app/assets/javascripts/initializers/runtime.js
  app/javascript/.storybook/preview-head.html
  app/javascript/article-form/articleForm.jsx
  app/javascript/crayons/MarkdownToolbar/MarkdownToolbar.jsx
  app/javascript/crayons/MarkdownToolbar/__tests__/MarkdownToolbar.test.jsx
  app/javascript/crayons/MarkdownToolbar/markdownSyntaxFormatters.js
  app/javascript/shared/components/useKeyboardShortcuts.js
Labels: PR: unreviewed

#15277 Remove optional chaining syntax from comments page initializer
  app/assets/javascripts/initializers/initializeCommentsPage.js.erb
Labels: PR: partially-approved

#15280 Add assets precompile check to the miscellaneous tasks node
  .travis.yml
Labels: PR: reviewed-approved

#15278 Add collection cache in articles/full_comment_area
  app/views/articles/_comment_tree.html.erb
  app/views/articles/_full_comment_area.html.erb
Labels: PR: reviewed-approved

#15255 [Small Wins] Show character limits for profile inputs
  app/helpers/profile_helper.rb
  app/javascript/packs/userProfileSettings.js
  app/views/users/_profile.html.erb
  spec/helpers/profile_helper_spec.rb
Labels: PR: reviewed-approved, area: profile, PR: partially-approved, include in changelog

#15073 Add PGHero for more insights into the DB
  Gemfile
  Gemfile.lock
  app/workers/capture_query_stats_worker.rb
  config/routes/admin.rb
  config/schedule.yml
  db/migrate/20211013153230_create_pghero_query_stats.rb
  db/schema.rb
  vendor/cache/google-protobuf-3.18.1-universal-darwin.gem
  vendor/cache/google-protobuf-3.18.1-x86_64-linux.gem
  vendor/cache/google-protobuf-3.18.1.gem
  vendor/cache/pg_query-2.1.1.gem
  vendor/cache/pghero-2.8.1.gem
Labels: PR: partially-approved

#15283 Caching sum privileged reaction scores
  db/migrate/20211104161101_add_privileged_users_reaction_sum.rb
  db/schema.rb
Labels: area: caching, PR: partially-approved

#15093 Bug Fix: Following an organization from article's sidebar creates an incorrect `follow` record
  app/controllers/follows_controller.rb
  app/helpers/application_helper.rb
  cypress/integration/seededFlows/articleFlows/followFromArticleLiquidTag.spec.js
  cypress/integration/seededFlows/articleFlows/followOrganization.spec.js
  spec/support/seeds/seeds_e2e.rb
Labels: PR: partially-approved

#14387 Only permit valid class names as sponsorable type
  app/models/sponsorship.rb
  spec/models/sponsorship_spec.rb
Labels: PR: reviewed-approved

#15281 Cooldown Project: Introduce `StringAttributeCleaner`
  app/lib/string_attribute_cleaner.rb
  app/models/discussion_lock.rb
  spec/lib/string_attribute_cleaner_spec.rb
  spec/models/discussion_lock_spec.rb
Labels: PR: partially-approved

#15288 [Quick Fix] Fixed a couple of warnings in specs
  spec/requests/stories/tagged_articles_spec.rb
  spec/services/articles/enrich_image_attributes_spec.rb
Labels: PR: reviewed-approved

#15293 [Quick fix] Characters counter layout fix
  app/views/users/_profile.html.erb
Labels: area: settings, PR: partially-approved, tech: frontend

#15284 CSS Generator Cleanup
  app/assets/stylesheets/config/_generator.scss
  app/assets/stylesheets/config/_import.scss
  app/javascript/article-form/components/Help/EditorFormattingHelp.jsx
Labels: PR: partially-approved, tech: frontend

#15225 Theme data update script, remove theme choices from UI
  app/views/users/_customization.html.erb
  db/migrate/20211021063645_add_prefer_os_color_scheme_to_user_settings.rb
  db/schema.rb
  lib/data_update_scripts/20211019063703_migrate_themes.rb
  spec/lib/data_update_scripts/migrate_themes_spec.rb
  spec/spec_helper.rb
  spec/system/user/user_edits_customization_spec.rb
Labels: PR: unreviewed, merge by any core

#15299 Caching sum privileged reaction scores
  app/controllers/admin/privileged_reactions_controller.rb
  app/models/article.rb
  app/models/reaction.rb
  lib/data_update_scripts/20211104200856_update_each_articles_privileged_user_point_count.rb
  spec/lib/data_update_scripts/update_each_articles_privileged_user_point_count_spec.rb
  spec/models/article_spec.rb
Labels: PR: partially-approved

#15295 Update the Creator Settings Page
  app/assets/stylesheets/setup-mode.scss
  app/assets/stylesheets/views.scss
  app/assets/stylesheets/views/confirm-email.scss
  app/views/admin/creator_settings/_form.html.erb
  app/views/admin/creator_settings/new.html.erb
Labels: PR: partially-approved

#15309 Remove chars-count from user fields; fix inconsistent loading
  app/javascript/packs/userProfileSettings.js
  app/views/users/_profile.html.erb
Labels: PR: unreviewed

#15312 Rerun migrate themes script
  lib/data_update_scripts/20211109161231_migrate_themes_again.rb
Labels: PR: reviewed-approved

#15340 Added a skip link for the admin area
  app/views/layouts/admin.html.erb
Labels: area: accessibility, PR: unreviewed, area: admin, PR: partially-approved, merge by any core

#15239 Markdown toolbar: add 'undo' functionality
  app/javascript/crayons/MarkdownToolbar/MarkdownToolbar.jsx
  app/javascript/crayons/MarkdownToolbar/__tests__/markdownSyntaxFormatters.test.js
  app/javascript/crayons/MarkdownToolbar/markdownSyntaxFormatters.js
  app/javascript/utilities/__tests__/textAreaUtils.test.js
  app/javascript/utilities/textAreaUtils.js
  cypress/integration/seededFlows/articleFlows/followFromArticleLiquidTag.spec.js
Labels: PR: partially-approved

#15083 views/stories, views/layouts and other homepage i18n
  app/views/articles/index.html.erb
  app/views/layouts/_footer.html.erb
  app/views/layouts/_logo.html.erb
  app/views/layouts/_main_nav.html.erb
  app/views/layouts/_nav_menu.html.erb
  app/views/layouts/_sidebar_nav_link.html.erb
  app/views/layouts/_sidebar_tags.html.erb
  app/views/layouts/_signup_modal.html.erb
  app/views/layouts/_top_bar.html.erb
  app/views/shared/_hamburger.html.erb
  app/views/sidebars/_homepage_content.html.erb
  app/views/stories/articles_search/_meta.html.erb
  app/views/stories/articles_search/_nav_menu.html.erb
  app/views/stories/articles_search/index.html.erb
  app/views/stories/tagged_articles/_meta.html.erb
  app/views/stories/tagged_articles/_sidebar_additional.html.erb
  app/views/stories/tagged_articles/index.html.erb
  app/views/users/_meta.html.erb
  config/locales/en.yml
  config/locales/fr.yml
  config/locales/views/main/en.yml
  config/locales/views/main/fr.yml
  config/locales/views/misc/en.yml
  config/locales/views/misc/fr.yml
  config/locales/views/stories/en.yml
  config/locales/views/stories/fr.yml
  spec/requests/stories/articles_search_spec.rb
Labels: PR: unreviewed

#15314 Fix some prop type errors on the home page
  app/javascript/articles/components/Meta.jsx
  app/javascript/common-prop-types/article-prop-types.js
  app/javascript/common-prop-types/index.js
  app/javascript/common-prop-types/organization-prop-type.js
  app/javascript/leftSidebar/TagsFollowed.jsx
  app/javascript/organization/OrganizationPicker.jsx
Labels: PR: reviewed-approved, merge by any core

#15134 views/credits i18n
  app/views/credits/_ledger.html.erb
  app/views/credits/_ledger_sponsorship.html.erb
  app/views/credits/index.html.erb
  app/views/credits/new.html.erb
  config/locales/views/credits/en.yml
  config/locales/views/credits/fr.yml
Labels: PR: partially-approved

#15344 Skip badge awards for spam accounts
  app/services/badges/award.rb
  spec/services/badges/award_spec.rb
Labels: PR: partially-approved

#15346 Let users purchase credits
  app/views/credits/new.html.erb
  spec/views/credits/new.html.erb_spec.rb
Labels: PR: partially-approved, merge by any core

#15298 Redirect to creator settings page where necessary
  app/controllers/confirmations_controller.rb
  app/controllers/registrations_controller.rb
  cypress/integration/creatorOnboardingFlows/creatorSettings.spec.js
  cypress/integration/creatorOnboardingFlows/creatorSignup.spec.js
Labels: PR: partially-approved

#15308 Provide "Help" on the Creator Onboarding Setup Page
  app/assets/stylesheets/admin.scss
  app/assets/stylesheets/scaffolds.scss
  app/controllers/admin/application_controller.rb
  app/views/admin/creator_settings/new.html.erb
  app/views/layouts/admin.html.erb
  app/views/shared/_help_icon.html.erb
Labels: PR: partially-approved, merge by any core

#15351 handle deleted article's comments page with a 404 response
  app/controllers/comments_controller.rb
  spec/requests/comments_spec.rb
Labels: PR: reviewed-approved

#15266 Tags style
  app/assets/javascripts/utilities/buildArticleHTML.js
  app/assets/stylesheets/components/stories.scss
  app/assets/stylesheets/components/tags.scss
  app/assets/stylesheets/views/listings.scss
  app/helpers/application_helper.rb
  app/javascript/actionsPanel/actionsPanel.js
  app/javascript/article-form/components/Preview.jsx
  app/javascript/articles/__tests__/__snapshots__/Article.test.jsx.snap
  app/javascript/articles/components/TagList.jsx
  app/javascript/listings/singleListing/TagLinks.jsx
  app/javascript/readingList/components/ItemListItem.jsx
  app/views/admin/tags/_form.html.erb
  app/views/admin/tags/edit.html.erb
  app/views/articles/_single_story.html.erb
  app/views/articles/_sticky_nav.html.erb
  app/views/articles/show.html.erb
  app/views/dashboards/following_tags.html.erb
  app/views/notifications/shared/_article_preview.html.erb
  app/views/stories/tagged_articles/index.html.erb
  app/views/tags/edit.html.erb
  app/views/tags/index.html.erb
  cypress/integration/seededFlows/moderationFlows/adjustPostTags.spec.js
  spec/system/search/display_users_search_spec.rb
Labels: PR: partially-approved

#15356 Check for presence rather than falsey when detecting tag color
  app/helpers/application_helper.rb
Labels: PR: reviewed-approved

#15360 Tags wrapping fix
  app/assets/stylesheets/components/stories.scss
  app/views/articles/show.html.erb
  app/views/notifications/shared/_article_preview.html.erb
Labels: PR: reviewed-approved, tech: frontend

#15341 Discussion: Using same markdown config as other instances
  app/models/display_ad.rb
Labels: type: refactoring, PR: partially-approved

#15361 Nullify invalid tag colors
  lib/data_update_scripts/20211112173720_nullify_empty_tag_colors.rb
  spec/lib/data_update_scripts/nullify_empty_tag_colors_spec.rb
Labels: PR: unreviewed

#15235 Add Snackbar component on reading list
  app/javascript/packs/readingList.jsx
  app/javascript/readingList/readingList.jsx
Labels: PR: partially-approved

#15368 Now labels with the CSS class crayons-btn that wrap inputs of type file have focus states
  app/assets/stylesheets/components/buttons.scss
Labels: area: accessibility, PR: unreviewed, PR: partially-approved, merge by any core

#15369 [15 min fix] Fix timestamp error in Preact story cards
  app/javascript/articles/__tests__/__snapshots__/Article.test.jsx.snap
  app/javascript/articles/components/Meta.jsx
Labels: PR: partially-approved

#15382 Don't permit changing tag names in admin
  app/controllers/admin/tags_controller.rb
  spec/requests/admin/tags_spec.rb
Labels: PR: reviewed-approved

#15326 Normalizing feed page size
  app/models/article.rb
  app/services/articles/feeds/basic.rb
  app/services/articles/feeds/large_forem_experimental.rb
  app/services/articles/feeds/latest.rb
  app/services/articles/feeds/tag.rb
  app/services/articles/feeds/timeframe.rb
Labels: PR: reviewed-approved

#15397 Adding ability to block domains from registration
  app/controllers/registrations_controller.rb
  app/lib/constants/settings/authentication.rb
  app/models/settings/authentication.rb
  app/views/admin/settings/forms/_authentication.html.erb
  spec/models/settings/authentication_spec.rb
Labels: PR: partially-approved

#15342 Issue #9077 has already been resolved, added specs
  app/services/mentions/create_all.rb
  spec/services/mentions/create_all_spec.rb
Labels: PR: partially-approved

#15403 Moving blocked registration domains up
  app/views/admin/settings/forms/_authentication.html.erb
Labels: PR: unreviewed

#15407 Remove broken link "events" from the admin sidebar
  app/models/admin_menu.rb
Labels: PR: reviewed-approved

#15310 Remove Setup Banner from Creator Onboarding Flow
  app/assets/stylesheets/setup-mode.scss
  app/views/layouts/application.html.erb
  cypress/integration/creatorOnboardingFlows/creatorSettings.spec.js
Labels: PR: unreviewed

#15408 Fixed issue where element didn't exist in the config Stimulus controller.
  app/javascript/admin/controllers/config_controller.js
Labels: area: admin, PR: partially-approved, tech: frontend, merge by any core

#15399 Refactoring and extending article spam behavior
  app/models/article.rb
  app/models/reaction.rb
  app/models/settings/rate_limit.rb
  app/services/spam/article_handler.rb
  spec/models/article_spec.rb
  spec/models/reaction_spec.rb
  spec/models/settings/rate_limit_spec.rb
  spec/services/spam/article_handler_spec.rb
Labels: PR: unreviewed

#15178 Hiding comments: an option to hide or keep children
  app/assets/javascripts/initializers/initializeCommentsPage.js.erb
  app/controllers/comments_controller.rb
  app/helpers/comments_helper.rb
  app/javascript/contentDisplayPolicy/initHiddenComments.js
  app/views/articles/_full_comment_area.html.erb
  app/views/comments/_comment.html.erb
  app/views/comments/_comment_header.html.erb
  app/views/comments/_comment_proper.html.erb
  app/views/comments/_comment_quality_marker.html.erb
  app/views/comments/_hide_comments_modal.html.erb
  app/views/comments/index.html.erb
  cypress/integration/seededFlows/articleFlows/hideArticleComments.spec.js
  cypress/integration/seededFlows/articleFlows/viewArticleDiscussion.spec.js
  spec/requests/comments_spec.rb
  spec/requests/shared_examples/comment_hide_or_unhide_request.rb
  spec/support/seeds/seeds_e2e.rb
Labels: PR: partially-approved

#15401 Revise skip link behaviour
  app/assets/javascripts/base.js.erb
  app/assets/stylesheets/admin.scss
  app/assets/stylesheets/components/header.scss
  app/assets/stylesheets/components/skip-link.scss
  app/javascript/packs/admin.js
  app/views/layouts/_top_bar.html.erb
  app/views/layouts/admin.html.erb
  cypress/integration/seededFlows/searchFlows/skipToContent.spec.js
Labels: PR: partially-approved

#15416 Update the periodic email description to reflect the period
  app/lib/constants/settings/general.rb
Labels: PR: partially-approved

#15419 Unfreeze models in RecordDataCountsWorker
  app/workers/metrics/record_data_counts_worker.rb
Labels: PR: reviewed-approved

#15363 Add logo preview to creator settings form
  app/assets/stylesheets/setup-mode.scss
  app/javascript/.eslintrc.js
  app/javascript/admin/controllers/creator_settings_controller.js
  app/javascript/packs/base.jsx
  app/views/admin/creator_settings/_form.html.erb
  app/views/admin/creator_settings/new.html.erb
  config/webpack/environment.js
  cypress/integration/creatorOnboardingFlows/creatorSettings.spec.js
  jsconfig.json
Labels: PR: unreviewed, type: forem creation, merge by any core

#15426 Remove Pusher route
  config/routes.rb
Labels: PR: partially-approved

#15420 Update Youtube Liquid Tag to accept seconds in timestamp query
  app/liquid_tags/youtube_tag.rb
  spec/liquid_tags/youtube_tag_spec.rb
Labels: PR: partially-approved, tech: backend, area: media

#15427 Increase Blazer's timeout
  config/blazer.yml
Labels: PR: reviewed-approved

#15404 Guarding against spam from OAuth Sources
  app/controllers/omniauth_callbacks_controller.rb
  app/errors/authentication/errors.rb
  app/services/authentication/authenticator.rb
  spec/services/authentication/authenticator_spec.rb
Labels: PR: partially-approved

#15333 Parameterizing featured story requiring main image
  app/services/articles/feeds/find_featured_story.rb
  app/services/articles/feeds/large_forem_experimental.rb
  spec/services/articles/feeds/find_featured_story_spec.rb
Labels: PR: reviewed-approved

#15343 Markdown toolbar - update new line logic for block syntaxes
  app/javascript/crayons/MarkdownToolbar/__tests__/markdownSyntaxFormatters.test.js
  app/javascript/crayons/MarkdownToolbar/markdownSyntaxFormatters.js
  app/javascript/utilities/__tests__/textAreaUtils.test.js
  app/javascript/utilities/textAreaUtils.js
Labels: PR: reviewed-approved

#15436 Updating valid domain registration
  app/models/settings/authentication.rb
  app/validators/valid_domain_csv_validator.rb
  spec/requests/admin/configs_spec.rb
  spec/validators/valid_domain_csv_validator_spec.rb
Labels: PR: unreviewed

#15429 Gitpod: wait for postgresql to be listening before startup
  .gitpod.yml
Labels: PR: reviewed-approved

#15400 Mod tools trigger
  app/assets/stylesheets/views/article.scss
  app/assets/stylesheets/views/mod-actions.scss
  app/javascript/actionsPanel/__tests__/actionsPanel.test.js
  app/javascript/actionsPanel/__tests__/initializeActionsPanelToggle.test.js
  app/javascript/actionsPanel/actionsPanel.js
  app/javascript/actionsPanel/initializeActionsPanelToggle.js
  app/views/articles/_actions.html.erb
  app/views/articles/show.html.erb
Labels: area: moderation, PR: partially-approved, tech: frontend

#15434 Reflect search query in page title
  app/views/stories/articles_search/_meta.html.erb
  config/locales/views/misc/en.yml
  config/locales/views/misc/fr.yml
  spec/system/search/search_title_spec.rb
Labels: PR: reviewed-approved

#15430 Provide COC and TOS Checkboxes During Creator Onboarding
  app/controllers/admin/creator_settings_controller.rb
  app/views/admin/creator_settings/_form.html.erb
  cypress/integration/creatorOnboardingFlows/creatorSettings.spec.js
Labels: PR: partially-approved

#15431 Adding program language lens for Code Ownership
  .github/CODEOWNERS
Labels: PR: reviewed-approved

#15440 Guarding against missing experiments
  app/workers/users/record_field_test_event_worker.rb
  spec/workers/users/record_field_test_event_worker_spec.rb
Labels: PR: unreviewed

#15459 Adding debug gem
  Gemfile
  Gemfile.lock
  vendor/cache/debug-1.3.4.gem
  vendor/cache/io-console-0.5.9.gem
  vendor/cache/irb-1.3.7.gem
  vendor/cache/reline-0.2.7.gem
Labels: PR: partially-approved

#15417 Update knapsack-pro/cypress to 4.5.0
  package.json
  yarn.lock
Labels: PR: partially-approved

#15453 Use tap instead of a temporary variable to modify after create
  spec/services/feeds/assemble_article_markdown_spec.rb
Labels: PR: reviewed-approved

#15432 Dynamically update the brand colors
  app/assets/images/forem-background.svg
  app/assets/stylesheets/shared.scss
  app/javascript/admin/controllers/creator_settings_controller.js
  app/javascript/utilities/__tests__/color/accentCalculator.test.js
  app/javascript/utilities/color/accentCalculator.js
  app/views/admin/creator_settings/_form.html.erb
  app/views/devise/confirmations/new.html.erb
  app/views/listings/edit.html.erb
  app/views/shared/authentication/_forem_creator_signup.html.erb
  app/views/users/show.html.erb
  cypress/integration/creatorOnboardingFlows/creatorSettings.spec.js
Labels: PR: partially-approved

#15443 Favoring delete_all on user relationships
  app/models/ahoy/event.rb
  app/models/ahoy/visit.rb
  app/models/api_secret.rb
  app/models/badge_achievement.rb
  app/models/discussion_lock.rb
  app/models/display_ad_event.rb
  app/models/identity.rb
  app/models/mention.rb
  app/models/note.rb
  app/models/notification.rb
  app/models/notification_subscription.rb
  app/models/organization_membership.rb
  app/models/podcast_episode_appearance.rb
  app/models/podcast_ownership.rb
  app/models/poll_skip.rb
  app/models/poll_vote.rb
  app/models/profile.rb
  app/models/response_template.rb
  app/models/user.rb
  app/models/users/notification_setting.rb
  app/models/users/setting.rb
  spec/models/user_spec.rb
Labels: PR: partially-approved

#15466 Fix TOS Link on Creator Settings Form
  app/views/admin/creator_settings/_form.html.erb
Labels: PR: partially-approved

#15461 Added the babel-inline-react-svg plugin
  app/javascript/.eslintrc.js
  app/javascript/.storybook/main.js
  babel.config.js
  config/webpack/environment.js
  jsconfig.json
  package.json
  yarn.lock
Labels: PR: unreviewed, PR: partially-approved, tech: frontend, merge by any core

#15476 Adjust "Public" Radio Buttons on the Creator Settings Form
  app/views/admin/creator_settings/_form.html.erb
Labels: PR: partially-approved

#15141 Enable Forem (Passport) Auth
  app/helpers/authentication_helper.rb
  app/views/admin/settings/forms/_authentication.html.erb
  app/views/admin/settings/forms/authentication/_auth_provider_settings.html.erb
  app/views/shared/authentication/_providers_registration_form.html.erb
  lib/data_update_scripts/20211020145958_remove_passport_feature_flag.rb
  spec/helpers/authentication_helper_spec.rb
  spec/lib/data_update_scripts/remove_passport_feature_flag_spec.rb
  spec/models/user_spec.rb
  spec/services/authentication/providers/forem_spec.rb
  spec/system/authentication/conditional_registration_spec.rb
  spec/system/authentication/creator_config_edit_spec.rb
  spec/system/authentication/omniauth_redirect_uri_spec.rb
  spec/system/authentication/user_logs_in_with_forem_spec.rb
Labels: PR: partially-approved

#15212 ForemMobile namespaced functions
  app/assets/javascripts/initializers/initializePodcastPlayback.js
  app/assets/javascripts/initializers/initializeVideoPlayback.js
  app/controllers/devices_controller.rb
  app/javascript/article-form/components/ArticleCoverImage.jsx
  app/javascript/article-form/components/ImageUploader.jsx
  app/javascript/article-form/components/__tests__/ArticleCoverImage.test.jsx
  app/javascript/article-form/components/__tests__/ImageUploader.test.jsx
  app/javascript/mobile/foremMobile.js
  app/javascript/packs/base.jsx
  app/javascript/packs/runtimeBanner.jsx
  app/javascript/utilities/waitOnBaseData.js
  app/models/consumer_app.rb
  app/views/layouts/application.html.erb
  cypress/integration/seededFlows/mobileFlows/namespacedForemMobile.spec.js
  cypress/integration/seededFlows/mobileFlows/runtimeBannerDeepLinking.spec.js
  cypress/integration/seededFlows/mobileFlows/runtimeContext.spec.js
  spec/models/consumer_app_spec.rb
  spec/requests/devices_spec.rb
Labels: PR: unreviewed

#15462 Accessibility improvements for hide comments modal
  app/javascript/contentDisplayPolicy/initHiddenComments.js
  app/views/comments/_comment_header.html.erb
  app/views/comments/_hide_comments_modal.html.erb
  cypress/integration/seededFlows/articleFlows/hideArticleComments.spec.js
Labels: PR: partially-approved

#15478 Preventing author profile from going transparent
  app/assets/stylesheets/components/dropdowns.scss
  app/assets/stylesheets/components/profile-preview-card.scss
  app/assets/stylesheets/views/article-form.scss
  app/javascript/CommentSubscription/CommentSubscription.jsx
  app/javascript/article-form/components/Options.jsx
  app/views/articles/_actions.html.erb
Labels: PR: reviewed-approved

#15489 Automatically run DataUpdateScripts in development
  config/environments/development.rb
Labels: PR: partially-approved

#15490 Ensuring reading list excludes unpublished articles
  app/models/reaction.rb
  app/services/search/reading_list.rb
  spec/services/search/reading_list_spec.rb
Labels: PR: unreviewed

#15442 Favoring dependent: :delete_all over :destroy
  app/models/article.rb
  app/models/discussion_lock.rb
  app/models/mention.rb
  app/models/notification_subscription.rb
  app/models/page_view.rb
  app/models/poll.rb
  app/models/poll_option.rb
  app/models/poll_skip.rb
  app/models/poll_vote.rb
  app/models/profile_pin.rb
  spec/models/article_spec.rb
  spec/models/poll_spec.rb
Labels: PR: unreviewed

#15347 Add markdown toolbar to V2 editor
  app/assets/stylesheets/components/editor-toolbar.scss
  app/assets/stylesheets/views/article-form.scss
  app/javascript/.storybook/preview-head.html
  app/javascript/article-form/actions.js
  app/javascript/article-form/components/ArticleCoverImage.jsx
  app/javascript/article-form/components/EditorBody.jsx
  app/javascript/article-form/components/ImageUploader.jsx
  app/javascript/article-form/components/Toolbar.jsx
  app/javascript/article-form/components/__tests__/Form.test.jsx
  app/javascript/article-form/components/__tests__/ImageUploader.test.jsx
  app/javascript/crayons/MarkdownToolbar/MarkdownToolbar.jsx
  app/javascript/crayons/MarkdownToolbar/__tests__/MarkdownToolbar.test.jsx
  app/javascript/utilities/dragAndUpload.js
  cypress/integration/seededFlows/publishingFlows/markdownToolbar.spec.js
  cypress/integration/seededFlows/publishingFlows/uploadImage.spec.js
Labels: PR: partially-approved

#15435 Rename feeds + update feeds' tabs UI
  app/views/articles/index.html.erb
  app/views/stories/tagged_articles/index.html.erb
  config/locales/views/stories/en.yml
  config/locales/views/stories/fr.yml
  cypress/integration/seededFlows/homeFeedFlows/feedNavigation.spec.js
  cypress/integration/seededFlows/tagsFlows/tagIndexNavigation.spec.js
  spec/requests/stories/tagged_articles_spec.rb
  spec/system/articles/user_visits_articles_by_tag_spec.rb
Labels: PR: unreviewed

#15069 views/dashboards i18n
  app/views/dashboards/_actions.html.erb
  app/views/dashboards/_actions_mobile.html.erb
  app/views/dashboards/_analytics.html.erb
  app/views/dashboards/_dashboard_article.html.erb
  app/views/dashboards/_dashboard_article_row.html.erb
  app/views/dashboards/_sublist.html.erb
  app/views/dashboards/analytics.erb
  app/views/dashboards/followers.html.erb
  app/views/dashboards/following_organizations.html.erb
  app/views/dashboards/following_podcasts.html.erb
  app/views/dashboards/following_tags.html.erb
  app/views/dashboards/following_users.html.erb
  app/views/dashboards/show.html.erb
  app/views/dashboards/subscriptions.html.erb
  app/views/listings/dashboard.html.erb
  config/locales/en.yml
  config/locales/fr.yml
  config/locales/views/dashboard/en.yml
  config/locales/views/dashboard/fr.yml
  spec/requests/dashboard_spec.rb
Labels: PR: partially-approved

#15501 Update the User Invitation email copy
  app/views/devise/mailer/invitation_instructions.html.erb
  app/views/devise/mailer/invitation_instructions.text.erb
  config/locales/devise_invitable.en.yml
  config/locales/devise_invitable.fr.yml
  spec/mailers/previews/devise_invitable/mailer_preview.rb
Labels: PR: partially-approved, merge by any core

#15509 prevent default on keyboard shortcut presses
  app/javascript/crayons/MarkdownToolbar/MarkdownToolbar.jsx
Labels: PR: partially-approved, merge by any core

#15240 Configurable weighted feed strategy
  app/controllers/stories/feeds_controller.rb
  app/controllers/stories_controller.rb
  app/models/ab_experiment.rb
  app/services/articles/feeds/weighted_query_strategy.rb
  config/field_test.yml
  lib/data_update_scripts/20211117204333_add_feature_flag_for_feed_experiment.rb
  spec/lib/data_update_scripts/add_feature_flag_for_feed_experiment_spec.rb
  spec/models/ab_experiment_spec.rb
  spec/rails_helper.rb
  spec/requests/stories/feeds_spec.rb
  spec/services/articles/feeds/weighted_query_strategy_spec.rb
  spec/system/homepage/user_visits_homepage_articles_spec.rb
Labels: PR: unreviewed, include in changelog

#15441 Refactoring poll/vote/skip logic
  app/models/poll.rb
  app/models/poll_skip.rb
  app/models/poll_vote.rb
  spec/models/poll_skip_spec.rb
  spec/models/poll_spec.rb
  spec/models/poll_vote_spec.rb
Labels: PR: reviewed-approved

#15482 Validating community does not include < nor >
  app/models/settings/community.rb
  spec/models/settings/community_spec.rb
Labels: PR: reviewed-approved

#15510 Fix Buildkite builds for versioning
  scripts/build_containers.sh
Labels: PR: reviewed-approved

#15517 Instrumentation: adding tags to data tracing
  app/controllers/stories/feeds_controller.rb
  app/controllers/stories_controller.rb
Labels: PR: unreviewed

#14674 Remove extra script tag from embedded gists to prevent them from mixing up
  app/javascript/utilities/gist.js
Labels: PR: partially-approved

#15520 Adding ugc role to untrusted profile URLs
  app/models/user.rb
  app/views/users/show.html.erb
Labels: PR: reviewed-approved

#15492 Updating documentation on FeatureFlag.accessible?
  app/services/feature_flag.rb
Labels: PR: reviewed-approved

#15529 Fix Rpush app when creating Android notification
  app/models/device.rb
  spec/services/push_notifications/send_spec.rb
Labels: PR: partially-approved, merge by any core

#15508 maintain cursor position while inserting an image
  app/javascript/article-form/components/ImageUploader.jsx
  app/javascript/crayons/MarkdownToolbar/MarkdownToolbar.jsx
  cypress/integration/seededFlows/publishingFlows/uploadImage.spec.js
Labels: PR: partially-approved

#15534 Markdown toolbar: open editor guide in new tab
  app/javascript/crayons/MarkdownToolbar/MarkdownToolbar.jsx
Labels: PR: partially-approved, merge by any core

#15544 Add single view count translation
  config/locales/views/dashboard/en.yml
  config/locales/views/dashboard/fr.yml
Labels: PR: partially-approved

#15527 Update the COC and TOS Description on the Creator Settings Form
  app/views/admin/creator_settings/_form.html.erb
Labels: PR: partially-approved

#15545 Add translations for one credit
  config/locales/views/credits/en.yml
  config/locales/views/credits/fr.yml
Labels: PR: reviewed-approved

#15412 Refactoring Spam Handler
  app/decorators/user_decorator.rb
  app/models/article.rb
  app/models/comment.rb
  app/models/reaction.rb
  app/models/settings/rate_limit.rb
  app/models/user.rb
  app/services/spam/handler.rb
  spec/decorators/user_decorator_spec.rb
  spec/models/article_spec.rb
  spec/models/comment_spec.rb
  spec/models/reaction_spec.rb
  spec/models/settings/rate_limit_spec.rb
  spec/models/user_spec.rb
  spec/services/spam/article_handler_spec.rb
  spec/services/spam/handler_spec.rb
Labels: PR: unreviewed

#15528 Fixing weighted query hotness grab logic
  app/controllers/stories/feeds_controller.rb
  app/services/articles/feeds.rb
  app/services/articles/feeds/large_forem_experimental.rb
  app/services/articles/feeds/weighted_query_strategy.rb
  spec/requests/stories/feeds_spec.rb
  spec/services/articles/feeds_spec.rb
Labels: PR: unreviewed

#15549 Fixing broken logic
  app/models/reaction.rb
Labels: PR: reviewed-approved

#15579 Update the Spacing Between the Title and Subtitle on the Creator Settings Form
  app/views/admin/creator_settings/new.html.erb
Labels: PR: partially-approved

#15538 Enabling scrolling for onboarding, attempt 2.
  app/assets/stylesheets/preact/onboarding-modal.scss
Labels: area: new user experience, PR: partially-approved, tech: frontend

#15311 Crayons: Buttons vs CTAs
  app/assets/stylesheets/components/buttons.scss
  app/assets/stylesheets/components/ctas.scss
  app/assets/stylesheets/components/links.scss
  app/assets/stylesheets/config/_colors.scss
  app/assets/stylesheets/config/_variables.scss
  app/assets/stylesheets/crayons.scss
  app/assets/stylesheets/themes/dark.scss
  app/javascript/.storybook/main.js
  app/javascript/.storybook/preview.js
  app/javascript/.storybook/storybook.scss
  app/javascript/actionsPanel/initializeActionsPanelToggle.js
  app/javascript/crayons/Buttons/Button.jsx
  app/javascript/crayons/Buttons/__stories__/Buttons.mdx
  app/javascript/crayons/Buttons/__stories__/Buttons.stories.jsx
  app/javascript/crayons/Buttons/__tests__/Buttons.test.jsx
  app/javascript/crayons/Buttons/__tests__/__snapshots__/Buttons.test.jsx.snap
  app/javascript/crayons/Buttons/index.js
  app/javascript/crayons/CTAs/CTA.jsx
  app/javascript/crayons/CTAs/__stories__/CTAs.mdx
  app/javascript/crayons/CTAs/__stories__/CTAs.stories.jsx
  app/javascript/crayons/CTAs/__tests__/CTA.test.jsx
  app/javascript/crayons/CTAs/__tests__/__snapshots__/CTA.test.jsx.snap
  app/javascript/crayons/CTAs/index.js
  app/javascript/crayons/Icons/Icon.jsx
  app/javascript/crayons/Icons/__stories__/Icons.mdx
  app/javascript/crayons/Icons/__stories__/Icons.stories.jsx
  app/javascript/crayons/Icons/index.js
  app/javascript/crayons/Links/Link.jsx
  app/javascript/crayons/Links/__stories__/Links.mdx
  app/javascript/crayons/Links/__stories__/Links.stories.jsx
  app/javascript/crayons/Links/__tests__/Link.test.jsx
  app/javascript/crayons/Links/__tests__/__snapshots__/Link.test.jsx.snap
  app/javascript/crayons/Links/index.js
  app/javascript/crayons/index.js
  app/javascript/packs/Search.jsx
  app/javascript/packs/base.jsx
  jest.config.js
  package.json
  yarn.lock
Labels: PR: unreviewed, tech: frontend

#15574 Now radio buttons in creator settings are on the same line in fieldsets
  app/views/admin/creator_settings/_form.html.erb
Labels: PR: partially-approved, type: forem creation, merge by any core
