Repository forem/forem, pull requests merged in 2021-01, with the labels that each got.

#12053 Enable new Rubocop 1.7.0 cops
  .rubocop.yml
Labels: PR: reviewed-approved, merge by any core

#12078 Dropdown CSS fix on /new view
  app/javascript/article-form/components/Options.jsx
Labels: PR: partially-approved, tech: html/css

#12079 Setting constraints for resizing comment textarea in notifications
  app/assets/stylesheets/config/_generator.scss
  app/views/notifications/shared/_comment_box.html.erb
Labels: PR: reviewed-approved, area: notifications, tech: html/css

#12098 Use anchor tag instead of button for edit/delete links
  app/javascript/listings/__tests__/ListingDashboard.test.jsx
  app/javascript/listings/dashboard/rowElements/actionButtons.jsx
  app/views/listings/delete_confirm.html.erb
Labels: PR: partially-approved

#12081 Move EmojiConverter to service
  app/labor/code_block_parser.rb
  app/labor/emoji_converter.rb
  app/services/html/parse_emoji.rb
  app/views/users/_github_repositories_area.html.erb
  spec/services/html/parse_emoji_spec.rb
Labels: PR: reviewed-approved, merge by any core

#12077 Optimization: Convert tags/_main_feed and widget_list_item partial loads to collections
  app/views/articles/tags/_main_feed.html.erb
  app/views/articles/tags/_sidebar_additional.html.erb
Labels: PR: partially-approved

#12100 Bug Fix:Update Article Cached Org and Docs When Org is Deleted
  app/models/article.rb
  app/models/organization.rb
  spec/lib/data_update_scripts/update_articles_cached_entities_spec.rb
  spec/models/organization_spec.rb
Labels: PR: partially-approved

#12110 Add `max_bytes` to imgproxy.
  app/services/images/optimizer.rb
  spec/services/images/optimizer_spec.rb
  spec/views/dashboards/show.html.erb_spec.rb
Labels: PR: unreviewed

#12111 Adjust animation on /connect mobile room open-close
  app/assets/stylesheets/chat.scss
Labels: PR: partially-approved

#12076 Override specified line break behaviour on the ID column
  app/assets/stylesheets/admin.scss
  app/views/admin/badge_achievements/index.html.erb
  app/views/admin/moderator_actions/index.html.erb
  app/views/admin/mods/index.html.erb
  app/views/admin/organizations/index.html.erb
  app/views/admin/permissions/index.html.erb
  app/views/admin/podcasts/index.html.erb
  app/views/admin/privileged_reactions/index.html.erb
  app/views/admin/sponsorships/index.html.erb
  app/views/admin/users/index.html.erb
Labels: PR: partially-approved

#12062 Update .env_sample
  .env_sample
Labels: PR: partially-approved

#12116 Update bundle-audit to ignore CVE-2020-26247
  .travis.yml
Labels: PR: partially-approved

#12035 Move LanguageDetector to service
  app/labor/language_detector.rb
  app/models/article.rb
  app/services/articles/detect_language.rb
  spec/labor/language_detector_spec.rb
  spec/models/article_spec.rb
  spec/services/articles/detect_language_spec.rb
Labels: PR: partially-approved, merge by any core

#12101 Use wait-retry-interval parameter for dockerize
  docker-compose.yml
Labels: PR: partially-approved

#12113 Small clean ups in post form
  app/javascript/shared/components/tags.jsx
  app/views/articles/_v2_form.html.erb
Labels: PR: partially-approved

#12127 Turn off "preview" mode after adding comment
  app/assets/javascripts/initializers/initializeCommentsPage.js.erb
Labels: PR: partially-approved, area: comments, javascript

#12096 Use yarn in scripts
  docs/netlify.toml
  package.json
Labels: PR: partially-approved

#11454 Update all followed tag with one click
  app/assets/javascripts/initializers/initScrolling.js
  app/controllers/follows_controller.rb
  app/javascript/packs/dashboardTagsDisableUnchangedButtons.js
  app/policies/follow_policy.rb
  app/views/dashboards/following_tags.html.erb
  config/routes.rb
  spec/requests/follows_bulk_update_spec.rb
  spec/requests/follows_update_spec.rb
  spec/system/dashboards/user_scrolls_down_dashboard_follows_spec.rb
Labels: PR: partially-approved

#11982 Test variants for which posts are fetched on initial "hot articles" home feed query.
  app/models/comment.rb
  app/models/page_view.rb
  app/models/reaction.rb
  app/services/articles/feeds/large_forem_experimental.rb
  app/workers/follows/update_points_worker.rb
  app/workers/users/record_field_test_event_worker.rb
  config/field_test.yml
  spec/requests/comments_spec.rb
  spec/requests/page_views_spec.rb
  spec/requests/reactions_spec.rb
  spec/services/articles/feeds/large_forem_experimental_spec.rb
  spec/workers/follows/update_points_worker_spec.rb
  spec/workers/users/record_field_test_event_worker_spec.rb
Labels: PR: partially-approved

#12128 "Copied!" label no longer wrapping to the next line
  app/javascript/article-form/components/ClipboardButton.jsx
Labels: PR: partially-approved, area: publishing experience

#12139 Adds ratio param to Cover Image native bridge image picker
  app/javascript/article-form/components/ArticleCoverImage.jsx
Labels: PR: partially-approved

#12140 [Travis] Use directories cache for Bundle and Yarn
  .travis.yml
Labels: PR: partially-approved

#12136 Rollback Listing Endorsements implementation
  app/models/listing.rb
  app/models/listing_endorsement.rb
  app/models/user.rb
  db/migrate/20210105183127_drop_listing_endorsements_table.rb
  db/schema.rb
  db/seeds.rb
  spec/factories/listing_endorsements.rb
  spec/models/listing_endorsement_spec.rb
  spec/models/listing_spec.rb
  spec/models/user_spec.rb
Labels: PR: partially-approved, merge by any core

#11956 Add ability to get latest articles on RSS feed
  app/controllers/articles_controller.rb
  config/routes.rb
  spec/requests/articles/articles_spec.rb
Labels: PR: partially-approved

#12155 Update Travis's Slack config
  .travis.yml
Labels: PR: reviewed-approved

#12069 Remove Collective Noun-Related Fields from SiteConfig
  lib/data_update_scripts/20201229230456_remove_collective_noun_from_site_config.rb
  spec/lib/data_update_scripts/remove_collective_noun_from_site_config_spec.rb
Labels: PR: reviewed-approved

#12153 Update Recent Reactions + Recent Reports Buttons
  app/views/admin/users/_negative_reactions.html.erb
  app/views/admin/users/_reports.html.erb
Labels: PR: partially-approved

#12112 Move CodeBlockParse and MarkdownParser to service
  app/labor/code_block_parser.rb
  app/models/display_ad.rb
  app/services/html/parse_emoji.rb
  app/services/html/parser.rb
  app/services/markdown_parser.rb
  app/views/users/_github_repositories_area.html.erb
  spec/services/html/parse_emoji_spec.rb
  spec/services/html/parser_spec.rb
  spec/services/markdown_parser_spec.rb
Labels: PR: partially-approved

#12167 Basic MVP version of data update script page
  app/controllers/admin/data_update_scripts_controller.rb
  app/views/admin/data_update_scripts/index.html.erb
  config/routes.rb
  spec/factories/users.rb
  spec/requests/admin/data_update_scripts_spec.rb
Labels: PR: partially-approved, merge by any core

#12147 Break StickyArticleCollection into services
  app/labor/sticky_article_collection.rb
  app/services/articles/get_user_stickies.rb
  app/services/articles/suggest_stickies.rb
  app/views/articles/_sticky_nav.html.erb
  spec/system/articles/user_visits_an_article_spec.rb
Labels: PR: partially-approved

#12172 Feature:Add ability to add a Tag Resource Admin through Admin
  app/lib/constants/role.rb
Labels: PR: reviewed-approved

#12149 Add application deployment information to the admin page
  .env_sample
  app/views/admin/admin_portals/index.html.erb
  spec/helpers/application_helper_spec.rb
  spec/requests/admin/admin_portals_spec.rb
Labels: PR: unreviewed, merge by any core

#12182 Change HEROKU_SLUG_COMMIT to HEROKU_RELEASE_CREATED_AT
  config/initializers/set_release_footprint.rb
Labels: PR: partially-approved

#12171 Move Bufferizer to services
  app/controllers/admin/buffer_updates_controller.rb
  app/labor/bufferizer.rb
  app/services/bufferizer/facebook_post.rb
  app/services/bufferizer/listings_tweet.rb
  app/services/bufferizer/main_tweet.rb
  app/services/bufferizer/satellite_tweet.rb
  spec/labor/bufferizer_spec.rb
  spec/requests/admin/buffer_updates_spec.rb
  spec/services/bufferizer/facebook_post_spec.rb
  spec/services/bufferizer/listings_tweet_spec.rb
  spec/services/bufferizer/main_tweet_spec.rb
  spec/services/bufferizer/satellite_tweet_spec.rb
Labels: PR: partially-approved, merge by any core

#12169 Remove RssReader
  app/controllers/users_controller.rb
  app/models/user.rb
  app/services/feature_flag.rb
  app/services/feeds/assemble_article_markdown.rb
  app/services/feeds/import.rb
  app/services/rss_reader.rb
  app/workers/articles/rss_reader_worker.rb
  app/workers/feeds/import_articles_worker.rb
  app/workers/rss_reader_fetch_user_worker.rb
  config/initializers/honeybadger.rb
  config/schedule.yml
  lib/data_update_scripts/20210107151449_remove_feeds_import_feature_flag.rb
  lib/tasks/fetch.rake
  spec/lib/data_update_scripts/remove_feeds_import_feature_flag_spec.rb
  spec/models/user_spec.rb
  spec/requests/user/user_settings_spec.rb
  spec/services/rss_reader_spec.rb
  spec/workers/articles/rss_reader_worker_spec.rb
  spec/workers/feeds/import_articles_worker_spec.rb
  spec/workers/rss_reader_fetch_user_worker_spec.rb
Labels: PR: partially-approved, action: post deployment

#12184 Show comment posting errors
  app/assets/javascripts/initializers/initializeCommentsPage.js.erb
  spec/system/comments/user_fills_out_comment_spec.rb
Labels: PR: partially-approved

#12173 Remove looking for work columns
  app/javascript/onboarding/components/__tests__/ProfileForm.test.jsx
  app/models/profile.rb
  app/policies/user_policy.rb
  app/services/profile_fields/add_work_fields.rb
  app/views/articles/_user_metadata.html.erb
  app/views/pages/_privacy_text.html.erb
  app/views/users/_metadata.html.erb
  db/migrate/20210108031718_remove_looking_for_work_from_users.rb
  db/schema.rb
  lib/data/dev_profile_fields.csv
  lib/data_update_scripts/20210108033107_remove_looking_for_work_profile_fields.rb
  spec/lib/data_update_scripts/create_profile_fields_spec.rb
  spec/services/profiles/update_spec.rb
Labels: PR: partially-approved, merge by any core

#12192 Bug Fix:Use permitted_origins Instead of Deprecated origin_whitelist
  config/routes.rb
Labels: PR: partially-approved

#12191 Bug Fix:Fix development.rb to Correctly Detect Rails command
  config/environments/development.rb
Labels: PR: unreviewed

#12183 Admin: Change label of toggle buttons in Configuration panel
  app/javascript/admin/controllers/config_controller.js
  app/views/admin/configs/show.html.erb
  app/views/admin/shared/_card_header.html.erb
Labels: PR: partially-approved

#12201 Feeds::Import: add index to users.feed_fetched_at
  db/migrate/20210111151630_add_index_to_users_feed_fetched_at.rb
  db/schema.rb
Labels: PR: partially-approved

#12186 Use an updated version of adding trusted for admins
  app/services/moderator/manage_activity_and_roles.rb
Labels: PR: partially-approved

#12200 Use SiteConfig twitter keys before env
  app/services/twitter_client/client.rb
  spec/services/twitter_client/client_spec.rb
Labels: PR: partially-approved

#12203 Update to add Community section.
  README.md
Labels: PR: unreviewed

#12210 Ben/new branch noindex spam comments
  app/models/podcast_episode.rb
  app/views/comments/index.html.erb
  spec/requests/comments_spec.rb
Labels: PR: partially-approved

#12195 Remove looking for work columns from ignore list
  app/models/user.rb
Labels: PR: reviewed-approved

#12213 Bug Fix:Update Admin Route in View to go to Edit page
  app/views/articles/tags/_sidebar.html.erb
Labels: PR: reviewed-approved

#12208 Add scroll back to the top to README
  README.md
Labels: PR: reviewed-approved

#12166 Bug fix #11402 - Very wide code blocks overflow in comment preview
  app/assets/stylesheets/views/comments.scss
  app/views/comments/edit.html.erb
Labels: PR: partially-approved

#12205 Move MailchimpBot to Mailchimp::Bot service
  app/models/user.rb
  app/services/mailchimp/bot.rb
  app/services/moderator/manage_activity_and_roles.rb
  app/services/tag_moderators/add.rb
  app/services/tag_moderators/add_trusted_role.rb
  app/services/tag_moderators/remove.rb
  app/workers/users/subscribe_to_mailchimp_newsletter_worker.rb
  spec/services/mailchimp/bot_spec.rb
  spec/workers/users/subscribe_to_mailchimp_newsletter_worker_spec.rb
Labels: PR: partially-approved

#12202 Move HexComparer to Hex::Comparer service
  app/decorators/listing_decorator.rb
  app/decorators/organization_decorator.rb
  app/decorators/user_decorator.rb
  app/helpers/application_helper.rb
  app/labor/hex_comparer.rb
  app/liquid_tags/tag_tag.rb
  app/models/message.rb
  app/services/color/compare_hex.rb
  app/views/articles/_sticky_nav.html.erb
  app/views/articles/tag_index.html.erb
  app/views/dashboards/following_tags.html.erb
  app/views/followings/tags.json.jbuilder
  app/views/shell/_top.html.erb
  app/views/social_previews/articles/article.html.erb
  app/views/social_previews/comment.html.erb
  app/views/social_previews/tag.html.erb
  app/views/social_previews/user.html.erb
  app/views/tags/edit.html.erb
  app/views/tags/index.html.erb
  app/views/users/_profile_header.html.erb
  app/views/users/show.html.erb
  spec/decorators/listing_decorator_spec.rb
  spec/helpers/application_helper_spec.rb
  spec/services/color/compare_hex_spec.rb
Labels: PR: partially-approved

#12238 Only show user count for large userbases
  app/views/shared/_auth_widget.html.erb
Labels: PR: partially-approved

#12236 [Travis] Create after_deploy Honeycomb script
  .slugignore
  .travis.yml
  scripts/after_deploy.sh
Labels: PR: unreviewed

#12196 Remove contact_consent from users
  app/models/profile.rb
  app/policies/user_policy.rb
  app/services/profile_fields/add_work_fields.rb
  db/migrate/20210111045049_drop_contact_consent_from_user.rb
  db/schema.rb
  lib/data/dev_profile_fields.csv
  spec/lib/data_update_scripts/create_profile_fields_spec.rb
Labels: PR: partially-approved

#12243 add katie(me) to list of core team members 🎉
  README.md
Labels: PR: partially-approved

#12197 Standardize bot meta tags
  app/views/articles/show.html.erb
  app/views/users/_meta.html.erb
  spec/requests/user/user_profile_spec.rb
Labels: PR: reviewed-approved

#12237 API: Endpoint to get an organization's articles
  app/controllers/api/v0/organizations_controller.rb
  app/views/api/v0/articles/index.json.jbuilder
  config/routes.rb
  docs/api_v0.yml
  spec/requests/api/v0/organizations_spec.rb
Labels: PR: partially-approved

#12010 Code snippet fullscreen icon - setting constraints for size.
  app/assets/images/fullscreen-off.svg
  app/assets/images/fullscreen-on.svg
  app/assets/stylesheets/components/syntax.scss
  app/services/html/parser.rb
  lib/data_update_scripts/20210104170542_resave_articles_for_code_snippet_fullscreen_icon.rb
  spec/support/fixtures/approvals/user_preview_article_body.approved.html
Labels: PR: unreviewed, tech: html/css

#12224 Refactor deployed_at and latest_commit_id code
  app/controllers/async_info_controller.rb
  app/helpers/application_helper.rb
  app/models/forem_instance.rb
  app/views/admin/admin_portals/index.html.erb
  app/views/layouts/admin.html.erb
  app/views/liquid_embeds/show.html.erb
  app/views/shell/_bottom.html.erb
  app/views/shell/_top.html.erb
  config/initializers/set_release_footprint.rb
  spec/models/forem_instance_spec.rb
  spec/requests/admin/admin_portals_spec.rb
Labels: PR: partially-approved

#12248 Rename MarkdownParser to MarkdownProcessor::Parser
  app/controllers/articles_controller.rb
  app/controllers/comments_controller.rb
  app/models/article.rb
  app/models/badge_achievement.rb
  app/models/comment.rb
  app/models/event.rb
  app/models/listing.rb
  app/models/message.rb
  app/models/organization.rb
  app/models/page.rb
  app/models/poll.rb
  app/models/poll_option.rb
  app/models/tag.rb
  app/models/user_subscription.rb
  app/services/markdown_parser.rb
  app/services/markdown_processor/parser.rb
  spec/services/markdown_processor/parser_spec.rb
Labels: PR: partially-approved, merge by any core

#12262 Fix shell version logic in async info controller
  app/controllers/async_info_controller.rb
  spec/models/forem_instance_spec.rb
Labels: PR: partially-approved, ci, merge by any core

#12252 Log onboarding_checkbox_update Params
  app/controllers/users_controller.rb
Labels: PR: reviewed-approved

#12135 [2020 EOY Issue] Modal alert when enabling Auth Provider without keys
  app/assets/stylesheets/admin.scss
  app/helpers/authentication_helper.rb
  app/javascript/admin/adminModal.js
  app/javascript/admin/controllers/config_controller.js
  app/views/admin/configs/_apple_auth_provider_settings.html.erb
  app/views/admin/configs/_auth_provider_settings.html.erb
  app/views/admin/configs/show.html.erb
  spec/helpers/authentication_helper_spec.rb
Labels: PR: unreviewed, merge by any core

#12244 Remove old MailchimpBot
  app/labor/mailchimp_bot.rb
  spec/labor/mailchimp_bot_spec.rb
Labels: PR: partially-approved

#12211 Encode emails properly before sending to /confirm-email
  app/controllers/registrations_controller.rb
  cypress/integration/loginFlows/initialAdminLogin.spec.js
  spec/system/authentication/user_logs_in_with_email_spec.rb
Labels: PR: partially-approved

#12209 Fixed punctuation mistakes
  README.md
Labels: PR: partially-approved

#12249 Add sorting feature to /admin/tags
  app/controllers/admin/tags_controller.rb
  app/views/admin/tags/index.html.erb
  spec/system/admin/admin_views_tags_spec.rb
Labels: PR: partially-approved

#12267 Log User Save Error Messages When it Fails
  app/controllers/users_controller.rb
Labels: PR: partially-approved

#12254 Remove contact_consent column from ignore list
  app/models/user.rb
Labels: PR: partially-approved

#12260 Dependabot: disable language/ecosystem labels attached to PRs
  .github/dependabot.yml
Labels: PR: partially-approved

#12272 Update Gemfile.lock for Bundler 2.2
  Gemfile.lock
Labels: PR: reviewed-approved

#12277 add suzanne to list of core team members
  README.md
Labels: PR: reviewed-approved

#12241 Break MarkdownFixer into MarkdownProcessor::Fixer services
  app/controllers/articles_controller.rb
  app/controllers/comments_controller.rb
  app/labor/markdown_fixer.rb
  app/models/article.rb
  app/models/comment.rb
  app/services/markdown_processor/fixer/base.rb
  app/services/markdown_processor/fixer/fix_all.rb
  app/services/markdown_processor/fixer/fix_for_comment.rb
  app/services/markdown_processor/fixer/fix_for_preview.rb
  spec/services/markdown_processor/fixer/base_spec.rb
  spec/services/markdown_processor/fixer/fix_all_spec.rb
  spec/services/markdown_processor/fixer/fix_for_comment_spec.rb
  spec/services/markdown_processor/fixer/fix_for_preview_spec.rb
Labels: PR: partially-approved, merge by any core

#12268 Fix domain list bug
  app/services/site_configs/upsert.rb
  spec/requests/admin/configs_spec.rb
Labels: PR: partially-approved

#12263 Workaround for Apple auth problems (still in beta)
  app/models/user.rb
  app/services/broadcasts/welcome_notification/generator.rb
  app/views/users/_additional_authentication.html.erb
  config/initializers/devise.rb
  spec/models/user_spec.rb
Labels: PR: partially-approved

#12280 Fix outstanding /pod main image problem
  app/views/podcast_episodes/_meta.html.erb
Labels: PR: partially-approved, merge by any core

#12281 Bug Fix:Increase Default Rate Limit for User Updates to 15
  app/controllers/users_controller.rb
  app/models/site_config.rb
  lib/data_update_scripts/20210114174504_update_user_update_rate_limit_default.rb
  spec/lib/data_update_scripts/update_user_update_rate_limit_default_spec.rb
  spec/requests/admin/configs_spec.rb
Labels: PR: partially-approved

#12232 Enable new rules and run Rubocop autocorrect
  .rubocop.yml
  spec/requests/comments_spec.rb
  spec/services/articles/feeds/large_forem_experimental_spec.rb
Labels: PR: reviewed-approved

#12287 Fix creator flow in /admin/config when :apple_auth feature flag is enabled
  app/views/admin/configs/_apple_auth_provider_settings.html.erb
  spec/system/authentication/creator_config_edit_spec.rb
Labels: PR: partially-approved

#12293 Adding Community to the table of contents.
  README.md
Labels: PR: partially-approved

#12294 Attempt to fix random test failures when dealing with the ForemInstance class
  spec/helpers/application_helper_spec.rb
  spec/models/forem_instance_spec.rb
  spec/requests/admin/admin_portals_spec.rb
Labels: PR: partially-approved, merge by any core

#12266 Improve Error Messaging for Self-Deletion Confirmation Flow
  app/controllers/users_controller.rb
  spec/requests/user/user_destroy_spec.rb
  spec/system/user/user_self_destroy_spec.rb
Labels: PR: partially-approved

#12300 Replace URL /settings/misc with /settings/customization
  app/views/mailers/digest_mailer/digest_email.html.erb
Labels: PR: partially-approved

#12313 Remove Liquid::BlockBody patch
  lib/liquid/block_body.rb
  spec/lib/liquid/liquid_spec.rb
Labels: PR: partially-approved

#12276 Optimize loading partials as collections
  app/views/admin/articles/index.html.erb
  app/views/articles/_sidebar.html.erb
  app/views/events/index.html.erb
  app/views/organizations/_main_feed.html.erb
  app/views/users/_main_feed.html.erb
Labels: PR: unreviewed

#12307 Fix and refactor hiding content when a user has blocked someone
  app/controllers/async_info_controller.rb
  app/controllers/stories_controller.rb
  app/javascript/contentDisplayPolicy/hideBlockedContent.js
  app/models/user.rb
  app/models/user_block.rb
  app/services/articles/feeds/basic.rb
  app/services/articles/feeds/large_forem_experimental.rb
  spec/models/user_block_spec.rb
  spec/services/articles/feeds/basic_spec.rb
  spec/services/articles/feeds/large_forem_experimental_spec.rb
Labels: PR: partially-approved

#12328 Fix broken test pre-Preact upgrade
  app/javascript/readingList/components/ItemListItem.jsx
  app/javascript/readingList/components/__tests__/ItemListItem.test.jsx
Labels: PR: partially-approved, area: tests

#12322 secure Identity#email in case of missing auth_data_dump hash (#11936)
  app/models/identity.rb
Labels: PR: reviewed-approved

#12309 Improve cumulative layout shift on comment reactions + optimizations
  app/assets/javascripts/initializers/initializeCommentsPage.js.erb
  app/decorators/article_decorator.rb
  app/helpers/comments_helper.rb
  app/views/articles/_full_comment_area.html.erb
  app/views/comments/_comment_footer.html.erb
  docs/technical-overview/architecture.md
  spec/decorators/article_decorator_spec.rb
Labels: PR: partially-approved, merge by any core

#12295 Storybook dropdown should be accessible 11724
  app/javascript/.storybook/preview.js
  app/javascript/crayons/Dropdown/__stories__/Dropdown.stories.jsx
  app/javascript/crayons/Dropdown/__stories__/dropdown-css-helper.scss
  app/javascript/crayons/Dropdown/__stories__/dropdown.html.stories.jsx
  app/javascript/crayons/Dropdown/__stories__/dropdowns.md
Labels: PR: partially-approved

#12312 BUGFIX: Allow image upload even if no existing image
  app/views/users/_profile.html.erb
  spec/requests/user/user_settings_spec.rb
Labels: PR: partially-approved

#12278 Generalise sidebar campaign published article timeframe
  app/controllers/sidebars_controller.rb
  app/controllers/stories_controller.rb
  app/lib/constants/site_config.rb
  app/models/site_config.rb
  app/views/admin/configs/show.html.erb
  spec/requests/admin/configs_spec.rb
Labels: PR: reviewed-approved

#11711 Display message from the back end when leaving a channel
  app/javascript/chat/ChatChannelSettings/ChatChannelSettings.jsx
Labels: PR: unreviewed

#12327 Fix image assets in tweets and remove like/retweet counts
  app/views/liquids/_tweet.html.erb
  spec/support/fixtures/approvals/liquid_tweet_tag_spec.approved.html
Labels: PR: partially-approved

#12229 Report a Message in Connect
  app/assets/stylesheets/chat.scss
  app/controllers/feedback_messages_controller.rb
  app/javascript/chat/ReportAbuse/index.jsx
  app/javascript/chat/__tests__/reportAbuse.test.jsx
  app/javascript/chat/actions/requestActions.js
  app/javascript/chat/chat.jsx
  app/javascript/chat/content.jsx
  app/javascript/chat/message.jsx
  app/javascript/onboarding/components/FollowUsers.jsx
  app/javascript/packs/base.js
  app/javascript/packs/homePage.jsx
  app/views/admin/feedback_messages/_feedback_message.html.erb
  app/views/admin/feedback_messages/_style.html.erb
  app/views/layouts/_nav_menu.html.erb
  docs/technical-overview/ab_testing.md
  spec/requests/feedback_messages_spec.rb
  spec/system/feedback_message_spec.rb
Labels: PR: partially-approved, area: connect

#12334 Load campaign articles in a widget as a collection
  app/views/articles/_sidebar_campaign.html.erb
Labels: PR: partially-approved

#12339 Fix deprecation warnings
  app/services/images/optimizer.rb
  app/services/slack/messengers/article_published.rb
Labels: PR: reviewed-approved

#12338 Fix autoloading deprecation
  config/initializers/audit_events.rb
  config/initializers/carrierwave.rb
  config/initializers/honeybadger.rb
  config/initializers/reverse_markdown.rb
Labels: PR: partially-approved

#12347 Add permalink to editor guide headings
  app/views/pages/_editor_guide_text.html.erb
  app/views/pages/_v1_editor_guide_preamble.html.erb
Labels: PR: partially-approved

#12330 Reindex comments' Elasticsearch doc when commentable is updated
  app/models/article.rb
  app/serializers/search/comment_serializer.rb
  app/services/data_sync/elasticsearch/article.rb
  lib/data_update_scripts/20210118194138_resync_unpublished_articles_comments_elasticsearch_document.rb
  spec/lib/data_update_scripts/resync_unpublished_articles_comments_elasticsearch_document_spec.rb
  spec/models/article_spec.rb
  spec/services/data_sync/elasticsearch/article_spec.rb
Labels: PR: reviewed-approved

#12345 Add descriptions to scheduled tasks
  config/schedule.yml
Labels: PR: partially-approved

#12282 Move MarkdownTraverser to MarkdownProcessor::Traverser
  app/labor/markdown_traverser.rb
  app/services/markdown_processor/fixer/base.rb
  app/services/markdown_processor/traverser.rb
  spec/services/markdown_processor/traverser_spec.rb
Labels: PR: partially-approved

#12340 Remove OSS team from CODEOWNERS file and add backend team
  .github/CODEOWNERS
Labels: PR: unreviewed

#12331 Don't try to unsub users when destroying if Mailchimp is not enabled
  app/models/site_config.rb
  app/models/user.rb
  app/services/mailchimp/bot.rb
  spec/services/mailchimp/bot_spec.rb
Labels: PR: unreviewed, merge by any core

#12301 Update dev.to/mods for non-logged in users
  app/views/moderations/index.html.erb
  spec/requests/moderations_spec.rb
Labels: PR: partially-approved, merge by any core

#12316 Update NavigationLink handling
  app/models/navigation_link.rb
  app/views/admin/navigation_links/_form.html.erb
  lib/data_update_scripts/20210119060219_make_local_navigation_links_relative.rb
  spec/factories/navigation_links.rb
  spec/lib/data_update_scripts/make_local_navigation_links_relative_spec.rb
  spec/models/navigation_link_spec.rb
Labels: PR: partially-approved, merge by any core

#12174 Verify current password on password change
  app/controllers/passwords_controller.rb
  app/controllers/users_controller.rb
  app/models/user.rb
  app/policies/user_policy.rb
  app/views/users/_account_set_password.html.erb
  config/routes.rb
  spec/requests/user/user_changes_password_spec.rb
Labels: PR: unreviewed, merge by any core

#12348 Save Data Update Script errors to database and show them on http://localhost:3000/admin/data_update_scripts
  app/models/data_update_script.rb
  app/views/admin/data_update_scripts/index.html.erb
  app/workers/data_update_worker.rb
  db/migrate/20210121102114_add_error_to_data_update_script.rb
  db/schema.rb
  spec/models/data_update_script_spec.rb
  spec/support/fixtures/data_update_scripts/20210120141757_failing_data_update_test_script.rb
  spec/workers/data_update_worker_spec.rb
Labels: PR: partially-approved, merge by any core

#12363 Adding aria labels and role to onboarding modal
  app/javascript/onboarding/components/EmailPreferencesForm.jsx
  app/javascript/onboarding/components/FollowTags.jsx
  app/javascript/onboarding/components/FollowUsers.jsx
  app/javascript/onboarding/components/IntroSlide.jsx
  app/javascript/onboarding/components/ProfileForm.jsx
Labels: PR: partially-approved

#12368 Cache only the static badge achievement data for notifications
  app/views/notifications/_badgeachievement.html.erb
Labels: PR: partially-approved, merge by any core

#12373 Remove Extra href from Admin Articles Index
  app/views/admin/articles/index.html.erb
Labels: PR: partially-approved

#12369 Log Relevant Data from Self-Deletion Flow to Honeycomb
  app/controllers/users_controller.rb
  spec/system/user/user_self_destroy_spec.rb
Labels: PR: partially-approved

#12288 Fix accidental publishing of draft articles
  app/javascript/article-form/articleForm.jsx
  spec/system/articles/user_fixes_a_draft_spec.rb
Labels: PR: partially-approved

#12378 Move mini_racer and sassc-rails out of production
  Gemfile
Labels: PR: partially-approved

#12372 Expand slugignore & Add auto remove node_module rake task
  .slugignore
  lib/tasks/assets.rake
Labels: PR: partially-approved

#12379 Replace authentication_enabled_providers.include? with helper method
  app/helpers/authentication_helper.rb
  app/views/admin/configs/_apple_auth_provider_settings.html.erb
  app/views/admin/configs/_auth_provider_settings.html.erb
  app/views/admin/configs/show.html.erb
  spec/helpers/authentication_helper_spec.rb
Labels: PR: reviewed-approved

#12362 Fixing link focus
  app/assets/stylesheets/preact/onboarding-modal.scss
  app/javascript/onboarding/components/IntroSlide.jsx
Labels: PR: reviewed-approved

#12375 Update issue.yml text.
  .github/workflows/issue.yml
Labels: PR: unreviewed

#12323 Refactor magic numbers for `/comments` rendering
  app/controllers/stories_controller.rb
  app/helpers/comments_helper.rb
  app/views/users/_comments_section.html.erb
  spec/system/user/view_user_comments_spec.rb
  spec/system/user/view_user_index_spec.rb
Labels: PR: partially-approved

#12365 fix devise error messages in the dark theme UI
  app/views/devise/shared/_error_messages.html.erb
Labels: PR: partially-approved

#12391 Update Tag Link to Route to Proper Admin Page
  app/views/tags/edit.html.erb
Labels: PR: reviewed-approved

#12385 Fix flash of unstyled content
  app/views/layouts/_asset_reconciliation.html.erb
  app/views/layouts/_styles.html.erb
  app/views/layouts/application.html.erb
  app/views/shell/_top.html.erb
  spec/requests/stories_index_spec.rb
Labels: PR: partially-approved

#12415 Optimize Admin::FeedbackMessagesController by adding proper indexes
  db/migrate/20210125085442_add_indexes_to_ahoy_messages_feedback_message_id_and_feedback_messages_status.rb
  db/schema.rb
Labels: PR: partially-approved

#12422 Prevent text overflow of follow button
  app/helpers/application_helper.rb
Labels: PR: reviewed-approved

#12420 Optimize column selection for articles belonging to "any" given tag
  app/controllers/admin/articles_controller.rb
  app/models/user.rb
  app/services/article_api_index_service.rb
  app/services/articles/feeds/large_forem_experimental.rb
  app/services/articles/get_user_stickies.rb
  app/services/articles/suggest_stickies.rb
Labels: PR: reviewed-approved

#12423 Offline page colors for dark theme
  public/offline.html
Labels: PR: reviewed-approved, accessibility, tech: frontend

#12341 Add validations to SiteConfig model
  app/models/site_config.rb
  app/services/site_configs/upsert.rb
  app/validators/color_contrast_validator.rb
  app/validators/emoji_only_validator.rb
  app/validators/valid_domain_csv_validator.rb
  spec/models/site_config_spec.rb
Labels: PR: partially-approved

#12436 Video max width
  app/assets/stylesheets/base/typography.scss
  app/sanitizers/rendered_markdown_scrubber.rb
Labels: PR: partially-approved, area: articles, tech: frontend

#12428 Close modal on `escape` keypress
  app/javascript/article-form/components/Help.jsx
  app/javascript/crayons/Modal/Modal.jsx
Labels: PR: partially-approved, accessibility, tech: frontend, tech: javascript

#12431 Disable ResaveArticlesForCodeSnippetFullscreenIcon
  lib/data_update_scripts/20210104170542_resave_articles_for_code_snippet_fullscreen_icon.rb
Labels: PR: partially-approved

#12346 Add Crayons classes to the "Destroy your account" page
  app/views/users/confirm_destroy.html.erb
  spec/system/user/user_self_destroy_spec.rb
Labels: PR: reviewed-approved

#12432 Remove fix-db-schema-conflicts
  Gemfile
  Gemfile.lock
  Rakefile
  vendor/cache/fix-db-schema-conflicts-3.0.3.gem
Labels: PR: partially-approved

#12445 Fix Typo: should be "min" not "max"
  app/views/admin/configs/show.html.erb
Labels: PR: reviewed-approved

#12390 Fix failure on blank image URLs passed from oauth
  app/services/authentication/providers/facebook.rb
  app/services/authentication/providers/github.rb
  app/services/authentication/providers/twitter.rb
  app/services/users/safe_remote_profile_image_url.rb
  spec/services/users/safe_remote_profile_image_url_spec.rb
Labels: PR: partially-approved, merge by any core

#11509 Header navigation dropdown accessibility
  app/assets/javascripts/base.js.erb
  app/assets/javascripts/initializePage.js
  app/assets/javascripts/initializers/initializeTouchDevice.js
  app/assets/stylesheets/components/header.scss
  app/assets/stylesheets/config/_colors.scss
  app/assets/stylesheets/tag-edit.scss
  app/assets/stylesheets/themes/hacker.scss
  app/assets/stylesheets/themes/minimal.scss
  app/assets/stylesheets/themes/night.scss
  app/assets/stylesheets/themes/pink.scss
  app/javascript/packs/base.js
  app/javascript/topNavigation/__tests__/utilities.test.js
  app/javascript/topNavigation/utilities.js
  app/views/layouts/_nav_menu.html.erb
  app/views/layouts/_top_bar.html.erb
  docs/frontend/plain-js.md
Labels: PR: partially-approved

#12442 Add a 4th node to Travis
  .travis.yml
Labels: PR: partially-approved

#12441 Explicitly adds the unique jobs middleware
  config/initializers/sidekiq.rb
Labels: PR: reviewed-approved

#12425 Don't display '0 reactions' on article feed
  app/assets/javascripts/utilities/buildArticleHTML.js
  app/javascript/articles/__tests__/__snapshots__/Article.test.jsx.snap
  app/javascript/articles/__tests__/utilities/articleUtilities.js
  app/javascript/articles/components/ReactionsCount.jsx
  app/javascript/articles/components/__tests__/ReactionsCount.test.jsx
  app/views/articles/_single_story.html.erb
  spec/system/search/display_articles_search_spec.rb
Labels: PR: partially-approved, merge by any core

#12304 This change abstracts the DatadogStatsClient into a ForemStatsClient.
  app/controllers/follows_controller.rb
  app/controllers/omniauth_callbacks_controller.rb
  app/controllers/stripe_active_cards_controller.rb
  app/lib/acts_as_forem_stats_driver.rb
  app/lib/forem_stats_driver.rb
  app/lib/forem_stats_drivers/datadog_driver.rb
  app/services/authentication/authenticator.rb
  app/services/edge_cache/bust.rb
  app/services/edge_cache/bust/nginx.rb
  app/services/fastly_config/snippets.rb
  app/services/fastly_config/update.rb
  app/services/feeds/import.rb
  app/services/github/oauth_client.rb
  app/services/loggers/log_worker_queue_stats.rb
  app/services/notifications/welcome_notification/send.rb
  app/services/payments/customer.rb
  app/services/rate_limit_checker.rb
  app/services/search/client.rb
  app/services/twitter_client/client.rb
  app/workers/data_update_worker.rb
  app/workers/metrics/check_data_update_script_statuses.rb
  app/workers/metrics/record_daily_notifications_worker.rb
  app/workers/metrics/record_daily_usage_worker.rb
  app/workers/metrics/record_data_counts_worker.rb
  app/workers/moderator/banish_user_worker.rb
  app/workers/moderator/sink_articles_worker.rb
  app/workers/users/delete_worker.rb
  config/initializers/datadog_apm.rb
  config/initializers/stats.rb
  lib/data_update_scripts/20200901085230_remove_draft_articles_with_duplicate_canonical_url.rb
  lib/sidekiq/worker_retries_exhausted_reporter.rb
  spec/lib/sidekiq/worker_retries_exhausted_reporter_spec.rb
  spec/requests/stripe_active_cards_spec.rb
  spec/services/authentication/authenticator_spec.rb
  spec/services/fastly_config/snippets_spec.rb
  spec/services/fastly_config/update_spec.rb
  spec/services/notifications/welcome_notification/send_spec.rb
  spec/services/payments/customer_spec.rb
  spec/services/rate_limit_checker_spec.rb
  spec/system/authentication/user_logs_in_with_apple_spec.rb
  spec/system/authentication/user_logs_in_with_facebook_spec.rb
  spec/system/authentication/user_logs_in_with_github_spec.rb
  spec/system/authentication/user_logs_in_with_twitter_spec.rb
  spec/workers/data_update_worker_spec.rb
  spec/workers/metrics/check_data_update_script_statuses_spec.rb
  spec/workers/metrics/record_daily_notifications_worker_spec.rb
  spec/workers/metrics/record_daily_usage_worker_spec.rb
  spec/workers/metrics/record_data_counts_worker_spec.rb
Labels: PR: partially-approved

#12457 Add nodejs to the production container
  Containerfile
Labels: PR: reviewed-approved

#12450 Add flash message for email confirmation
  app/controllers/confirmations_controller.rb
  config/routes.rb
  spec/system/authentication/user_request_confirmation_spec.rb
Labels: PR: partially-approved

#12366 Adding focus trap to trap focus within the modal
  app/javascript/onboarding/Onboarding.jsx
  app/javascript/shared/components/__tests__/focusTrap.test.jsx
  app/javascript/shared/components/focusTrap.jsx
  package.json
  yarn.lock
Labels: PR: partially-approved

#12430 updates article form to have warning modal
  app/javascript/article-form/articleForm.jsx
  app/javascript/article-form/components/Close.jsx
  app/javascript/article-form/components/Header.jsx
  app/javascript/article-form/components/__tests__/Close.test.jsx
  app/javascript/crayons/Modal/Modal.jsx
Labels: PR: partially-approved, area: publishing experience, tech: frontend, tech: javascript

#12458 Limit `user.touch` usage in RepoSyncWorker
  app/workers/github_repos/repo_sync_worker.rb
  spec/workers/github_repos/repo_sync_worker_spec.rb
Labels: PR: unreviewed

#12467 [Travis] Remove node_modules from cache
  .travis.yml
Labels: PR: partially-approved

#12472 Update Contributing guide to reflect new processes
  docs/contributing/forem.md
Labels: PR: unreviewed

#12475 Update /contact page with links to filing bug reports + forem.dev
  app/views/pages/contact.html.erb
  spec/requests/pages_spec.rb
Labels: PR: partially-approved, merge by any core

#12474 Remove extra asterisks in contributing guide
  docs/contributing/forem.md
Labels: PR: partially-approved, merge by any core

#12143 Cleaning Test Runs for End to End (E2E) Tests
  .travis.yml
  Gemfile
  Gemfile.lock
  app/lib/seeder.rb
  app/views/users/_account_set_password.html.erb
  app/views/users/_errors.html.erb
  app/views/users/confirm_destroy.html.erb
  bin/e2e
  bin/e2e-ci
  bin/e2e-setup
  config/initializers/cypress_rails.rb
  cypress.dev.json
  cypress.json
  cypress/fixtures/logins/initialAdmin.json
  cypress/fixtures/users/changePasswordUser.json
  cypress/integration/loginFlows/initialAdminLogin.spec.js
  cypress/integration/loginFlows/userChangePassword.spec.js
  cypress/integration/loginFlows/userLogin.spec.js
  cypress/plugins/index.js
  cypress/support/commands.js
  db/seeds.rb
  lib/tasks/e2e_seed.rake
  package.json
  spec/support/seeds/seeds_e2e.rb
  vendor/cache/cypress-rails-0.4.2.gem
  yarn.lock
Labels: PR: unreviewed, area: tests, merge by any core

#12476 Remove feature request issue template
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: PR: partially-approved, merge by any core
