Repository forem/forem, pull requests merged in 2021-07, with the labels that each got.

#14111 [15 min fix] Stub article network requests in pinPost cypress test
  cypress/integration/articleFlows/pinArticle.spec.js
Labels: PR: partially-approved, merge by any core

#14109 Drop profile fields for static attributes
  app/models/profile.rb
  app/validators/profile_validator.rb
  app/views/users/_profile.html.erb
  cypress/integration/profileFlows/userUpdateSettingsProfile.spec.js
  lib/data/dev_profile_fields.csv
  lib/data_update_scripts/20210630063635_drop_profile_fields_for_static_attributes.rb
  spec/lib/data_update_scripts/create_profile_fields_spec.rb
  spec/lib/data_update_scripts/drop_profile_fields_for_static_attributes_spec.rb
  spec/models/profile_spec.rb
Labels: PR: partially-approved, merge by any core

#14110 Provide way to resend comfirmation email via log-in page
  app/controllers/registrations_controller.rb
  app/helpers/authentication_helper.rb
  app/views/devise/confirmations/new.html.erb
  app/views/devise/shared/_authorization_error.html.erb
Labels: PR: unreviewed

#14058 Expire the SHA tag after 2 months.
  scripts/build_containers.sh
Labels: PR: reviewed-approved

#14125 [15-minute fix] Update password reset wording
  app/views/users/_account_set_password.html.erb
Labels: PR: reviewed-approved

#14149 Add some more guidance to E2E docs
  docs/tests/e2e-tests.md
Labels: PR: partially-approved

#14156 ✂️ Remove storybook/addon-storysource ✂️
  package.json
  yarn.lock
Labels: PR: partially-approved

#14128 [15 min fix] Add aria-current attribute to current dashboard link
  app/assets/javascripts/initializers/initScrolling.js
  app/views/dashboards/_actions.html.erb
  cypress/integration/dashboardFlows/dashboardNavigation.spec.js
Labels: PR: partially-approved

#13365 [15 min fix] Fixed regression for reverting changes in the article editor
  app/javascript/article-form/articleForm.jsx
  cypress/integration/publishingFlows/postBrowserPersistence.spec.js
Labels: PR: unreviewed, area: publishing experience, merge by any core, tech: javascript

#13772 Fix collections/series meta tags
  app/views/collections/_meta.html.erb
  app/views/collections/index.html.erb
  app/views/collections/show.html.erb
Labels: PR: partially-approved

#14130 Fix HTML markup in article pages
  app/helpers/application_helper.rb
  app/views/articles/show.html.erb
  app/views/shared/_profile_card_content.html.erb
Labels: PR: partially-approved

#14163 Revert "Bump sidekiq-unique-jobs from 7.0.12 to 7.1.2"
  Gemfile
  Gemfile.lock
  vendor/cache/sidekiq-unique-jobs-7.0.12.gem
  vendor/cache/sidekiq-unique-jobs-7.1.2.gem
Labels: PR: unreviewed

#14162 [15-min-fix] Add org id to admin listings form
  app/controllers/admin/listings_controller.rb
  app/views/admin/listings/edit.html.erb
  spec/requests/admin/listings_spec.rb
Labels: PR: partially-approved

#14167 [Fix] NoMethodError caused because no mascot account exists in a development environment
  db/seeds.rb
Labels: PR: partially-approved

#14154 Explicitly configure libhoney null client when no api key detected
  config/initializers/honeycomb.rb
Labels: PR: reviewed-approved

#14165 add default text to follow button
  app/helpers/application_helper.rb
Labels: PR: partially-approved

#14174 Skip dashboard spec
  cypress/integration/dashboardFlows/dashboardNavigation.spec.js
Labels: PR: reviewed-approved, merge by any core

#14177 Add SocketError to GetMediaUrl's exception rescue
  app/services/podcasts/feed.rb
  app/services/podcasts/get_media_url.rb
  spec/services/podcasts/get_media_url_spec.rb
Labels: PR: reviewed-approved

#14106 Add 'Work' profile field
  app/workers/migrate_data_to_work_field_worker.rb
  lib/data_update_scripts/20210630034523_add_work_profile_field.rb
  lib/data_update_scripts/20210630041322_migrate_data_to_work_field.rb
  spec/lib/data_update_scripts/add_work_profile_field_spec.rb
  spec/lib/data_update_scripts/migrate_data_to_work_field_spec.rb
Labels: PR: partially-approved, merge by any core

#14085 fetch preview card follow buttons in one network call
  app/assets/javascripts/initializers/initializeAllFollowButts.js
  app/helpers/application_helper.rb
  app/javascript/packs/commentDropdowns.js
  app/views/shared/_profile_card_content.html.erb
Labels: PR: unreviewed

#14175 Only update GithubRepos once in RepoSyncWorker
  app/workers/github_repos/repo_sync_worker.rb
Labels: PR: partially-approved

#14173 Boost priority of queue stats worker
  app/workers/metrics/record_background_queue_stats_worker.rb
  spec/workers/metrics/record_background_queue_stats_worker_spec.rb
Labels: PR: reviewed-approved

#14178 [15-minute fix] Update core team in README
  README.md
Labels: PR: partially-approved

#14185 Arrange Datadog Redis integrations more meaningfully
  app/lib/forem_stats_drivers/datadog_driver.rb
Labels: PR: partially-approved

#14186 Filter by user IDs when sending comment notifications
  app/services/notifications/new_comment/send.rb
Labels: PR: reviewed-approved

#14192 Added aria-pressed values to post reaction buttons
  app/assets/javascripts/initializers/initializeArticleReactions.js
  app/views/articles/_reaction_button.html.erb
Labels: PR: partially-approved

#14191 Fix changing mobile feed filters raising errors
  app/assets/javascripts/base.js.erb
Labels: PR: partially-approved

#14171 Fix bug in preview card controller
  app/controllers/profile_preview_card_controller.rb
  app/javascript/packs/commentDropdowns.js
  app/views/profile_preview_card/show.html.erb
Labels: PR: partially-approved

#14208 Temporarily disable preview profile spec pending fixes
  cypress/integration/articleFlows/previewProfile.spec.js
Labels: PR: reviewed-approved

#14187 Add spec to ensure we filter by proper user IDs for mobile push notifications
  spec/services/notifications/new_comment/send_spec.rb
Labels: PR: partially-approved

#14209 [15 min fix] Added a retry for logging in a user for the custom Cypress login command
  cypress/support/commands.js
Labels: PR: partially-approved, merge by any core

#14097 Make smtp "domain" setting explicit
  spec/models/settings/smtp_spec.rb
Labels: PR: partially-approved

#14211 Keep aria-label values static for post reaction buttons
  app/assets/javascripts/initializers/initializeArticleReactions.js
Labels: PR: partially-approved

#14161 [15-Minute Fix] Ensure "Locked Screen" Checkbox Conditionally Renders
  app/helpers/authentication_helper.rb
  app/models/forem_instance.rb
  app/services/authentication/providers.rb
  app/views/admin/settings/forms/_authentication.html.erb
  app/views/devise/registrations/_registration_form.html.erb
  app/views/shared/authentication/_providers_registration_form.html.erb
  cypress/integration/adminFlows/config/authenticationSection.spec.js
  cypress/integration/adminFlows/pages/landingPage.spec.js
  spec/system/admin/admin_manages_pages_spec.rb
  spec/system/authentication/user_logs_in_with_email_spec.rb
  spec/system/authentication/user_logs_in_with_facebook_spec.rb
  spec/system/authentication/user_logs_in_with_github_spec.rb
  spec/system/authentication/user_logs_in_with_twitter_spec.rb
Labels: PR: unreviewed

#14207 Fix data update script for work field migration
  app/workers/migrate_data_to_work_field_worker.rb
  spec/lib/data_update_scripts/migrate_data_to_work_field_spec.rb
Labels: PR: unreviewed

#14184 [15 min fix] Fixed an issue with the moderation button not appearing on some posts
  app/javascript/actionsPanel/initializeActionsPanelToggle.js
  app/javascript/packs/articleModerationTools.js
  app/javascript/utilities/__tests__/moderation.test.js
  app/javascript/utilities/moderation.js
  cypress/fixtures/users/trustedUser.json
  cypress/integration/articleFlows/postModerationTools.spec.js
  spec/support/seeds/seeds_e2e.rb
Labels: PR: partially-approved, merge by any core, tech: frontend

#14196 Enforce Uniqueness for Feed Import and Push Notification Cleanup Workers
  app/workers/feeds/import_articles_worker.rb
  app/workers/push_notifications/cleanup_worker.rb
Labels: PR: reviewed-approved

#14223 Move E2E into it's own node
  .travis.yml
Labels: PR: reviewed-approved

#14194 Move Article Search JavaScript in a separate file
  app/javascript/packs/searchParams.js
  app/views/articles/_search.html.erb
  app/views/articles/search.html.erb
Labels: PR: partially-approved

#14217 Only attach a click listener to a follow button once
  app/assets/javascripts/initializers/initializeAllFollowButts.js
  cypress/integration/articleFlows/previewProfile.spec.js
Labels: PR: partially-approved

#14225 Add constraints that are in the production DB
  db/schema.rb
Labels: PR: partially-approved

#14213 Static Sections for Site Navigation - Pt1
  app/controllers/admin/navigation_links_controller.rb
  app/models/navigation_link.rb
  db/migrate/20210712155135_add_section_to_navigation_links.rb
  db/schema.rb
  lib/data_update_scripts/20210712162220_backfill_section_column_for_navigation_links.rb
  lib/tasks/add_navigation_links.rake
  spec/factories/navigation_links.rb
  spec/lib/data_update_scripts/backfill_section_column_for_navigation_links_spec.rb
  spec/requests/admin/navigation_link_spec.rb
  spec/support/seeds/seeds_e2e.rb
Labels: PR: unreviewed

#14230 Fix dashboard posts lists' border when hovered
  app/assets/stylesheets/views/dashboard.scss
Labels: PR: partially-approved

#14119 Runtime Banner v2
  app/assets/javascripts/initializePage.js
  app/assets/javascripts/initializers/initializeRuntimeBanner.js
  app/javascript/packs/runtimeBanner.jsx
  app/javascript/runtimeBanner/RuntimeBanner.jsx
  app/javascript/runtimeBanner/index.js
  app/views/layouts/application.html.erb
  cypress/integration/loggedOutFlows/runtimeBannerDeepLinking.spec.js
Labels: PR: partially-approved

#14237 Quickfix for duplicate work display
  app/views/users/_metadata.html.erb
Labels: PR: partially-approved, merge by any core

#14233 Add error handling and UI feedback when submitting comment resulting in a 503 error
  app/assets/javascripts/initializers/initializeCommentsPage.js.erb
  cypress/integration/articleFlows/commentOnArticle.spec.js
Labels: PR: partially-approved

#14236 Fix: Modal appears under the navbar #13195
  app/views/articles/_actions.html.erb
Labels: PR: partially-approved

#14241 Add retries for cypress ci tests
  cypress.json
Labels: PR: partially-approved

#14219 [15 min fix] Show pinned article to logged out users
  app/controllers/stories_controller.rb
  app/views/articles/_single_story.html.erb
  app/views/stories/_main_stories_feed.html.erb
  cypress/integration/articleFlows/pinArticle.spec.js
Labels: PR: partially-approved

#14244 Don't try to subscribe users without emails
  app/workers/users/subscribe_to_mailchimp_newsletter_worker.rb
  spec/workers/users/subscribe_to_mailchimp_newsletter_worker_spec.rb
Labels: PR: partially-approved

#14248 Remove useEffect from RuntimeBanner component
  app/javascript/runtimeBanner/RuntimeBanner.jsx
Labels: PR: partially-approved, merge by any core

#14240 Fix shorten_urls to not strip out text formatting in comments
  app/models/comment.rb
  spec/models/comment_spec.rb
Labels: PR: partially-approved

#14249 Escape organization name in LinkTag's spec
  spec/liquid_tags/link_tag_spec.rb
Labels: PR: partially-approved

#14224 add cypress-failed-log
  .gitignore
  cypress/plugins/index.js
  cypress/support/index.js
  package.json
  yarn.lock
Labels: PR: partially-approved, merge by any core

#14258 Revert "Fix shorten_urls to not strip out text formatting in comments…
  app/models/comment.rb
  spec/models/comment_spec.rb
Labels: PR: partially-approved

#14206 Remove unused profile fields
  app/models/users/setting.rb
  app/services/profiles/update.rb
  app/validators/profile_validator.rb
  app/views/users/_profile.html.erb
  lib/data/dev_profile_fields.csv
  lib/data_update_scripts/20210712054300_remove_unused_profile_fields.rb
  spec/lib/data_update_scripts/create_profile_fields_spec.rb
  spec/models/profile_spec.rb
  spec/models/users/setting_spec.rb
  spec/services/profiles/update_spec.rb
Labels: PR: partially-approved, merge by any core

#14250 [15 min fix] Upgraded to Cypress 7.7.0
  package.json
  yarn.lock
Labels: PR: unreviewed, area: tests, merge by any core

#14252 Remove Settings Columns from User
  app/models/user.rb
  db/migrate/20210715205433_remove_settings_from_user.rb
  db/migrate/20210715211923_add_partial_feed_url_index_for_user_settings.rb
  db/schema.rb
Labels: PR: partially-approved, merge by any core

#14255 Bust Content Cache after updation of Settings
  app/controllers/admin/settings/general_settings_controller.rb
Labels: PR: reviewed-approved

#14254 fix podcast page missing skip functionality
  app/views/podcast_episodes/show.html.erb
Labels: PR: partially-approved

#14273 Skip login modal flaky spec
  cypress/integration/loggedOutFlows/showLoginModal.spec.js
Labels: PR: partially-approved, merge by any core

#14239 Remove `color_field` input type from profiles
  app/models/profile_field.rb
  app/validators/profile_validator.rb
  app/views/users/_profile.html.erb
  spec/fixtures/files/profile_fields.csv
  spec/services/profile_fields/import_from_csv_spec.rb
Labels: PR: partially-approved

#14264 Add Rajat to core team list
  README.md
Labels: PR: partially-approved

#14160 Allow multiple users to fetch all articles from the same RSS feed
  app/models/article.rb
  db/migrate/20210707053923_add_unique_index_to_articles_feed_source_url_where_published.rb
  db/migrate/20210712173206_add_unique_index_to_articles_canonical_url_where_published.rb
  db/schema.rb
  spec/models/article_spec.rb
  spec/services/feeds/import_spec.rb
Labels: PR: unreviewed

#14243 Fix Bugs in the "Copy article URL to clipboard" feature #14242
  app/assets/stylesheets/components/dropdowns.scss
  app/javascript/packs/articlePage.jsx
  app/views/articles/_actions.html.erb
  cypress/integration/articleFlows/postSidebarActions.spec.js
Labels: PR: partially-approved, include in changelog

#14262 Fix shorten_urls to not remove formatting and image tags
  app/models/comment.rb
  spec/models/comment_spec.rb
Labels: PR: reviewed-approved

#14228 Allow setting nil value in Settings::Upsert
  app/models/settings/smtp.rb
  app/services/settings/upsert.rb
  app/validators/valid_domain_csv_validator.rb
  spec/requests/admin/configs_spec.rb
Labels: PR: partially-approved

#14290 Update docs on self-host page
  docs/self-hosting.md
Labels: PR: partially-approved

#14222 Delay the hover appearance of preview card
  app/assets/stylesheets/profile-preview-card.scss
  app/javascript/packs/articlePage.jsx
  app/javascript/packs/commentDropdowns.js
Labels: PR: unreviewed

#14234 Remove defer attribute when not needed
  app/views/comments/_form.html.erb
  app/views/events/_event.html.erb
  app/views/layouts/application.html.erb
  app/views/pages/badge.html.erb
Labels: PR: partially-approved

#14296 Add JSON representation of Profile Preview Card info
  app/controllers/profile_preview_card_controller.rb
  app/controllers/profile_preview_cards_controller.rb
  app/javascript/packs/commentDropdowns.js
  app/views/profile_preview_card/show.html.erb
  app/views/profile_preview_cards/show.html.erb
  app/views/profile_preview_cards/show.json.jbuilder
  config/routes.rb
  spec/requests/profile_preview_cards_spec.rb
Labels: PR: partially-approved, merge by any core

#14286 Remove `CustomProfileField`
  app/models/concerns/acts_as_profile_field.rb
  app/models/custom_profile_field.rb
  app/models/profile.rb
  app/models/profile_field.rb
  app/serializers/search/user_serializer.rb
  app/services/profiles/update.rb
  db/migrate/20210720042422_drop_custom_profile_fields.rb
  db/schema.rb
  spec/factories/custom_profile_fields.rb
  spec/models/custom_profile_field_spec.rb
  spec/models/profile_field_spec.rb
  spec/models/profile_spec.rb
  spec/models/shared_examples/a_profile_field.rb
  spec/services/profiles/update_spec.rb
Labels: PR: partially-approved

#14303 [15-minute fix] Fix brand color validation
  app/models/users/setting.rb
  spec/models/users/setting_spec.rb
Labels: PR: partially-approved, merge by any core

#14297 remove use of async attribute on inline scripts
  app/views/articles/_block.html.erb
  app/views/articles/_fitvids.html.erb
  app/views/articles/_v2_form.html.erb
  app/views/articles/show.html.erb
  app/views/comments/index.html.erb
  app/views/layouts/_top_bar.html.erb
Labels: PR: reviewed-approved

#14285 Added support for running E2E tests without seeded data
  .travis.yml
  config/initializers/cypress_rails.rb
  cypress/integration/nonSeededFlows/test.spec.js
  cypress/integration/seededFlows/adminFlows/articles/pinArticle.spec.js
  cypress/integration/seededFlows/adminFlows/articles/unpinArticle.spec.js
  cypress/integration/seededFlows/adminFlows/badges/badgeAchievements.spec.js
  cypress/integration/seededFlows/adminFlows/config/authenticationSection.spec.js
  cypress/integration/seededFlows/adminFlows/config/campaignSection.spec.js
  cypress/integration/seededFlows/adminFlows/config/communitySection.spec.js
  cypress/integration/seededFlows/adminFlows/config/emailDigestFrequencySection.spec.js
  cypress/integration/seededFlows/adminFlows/config/getStartedSection.spec.js
  cypress/integration/seededFlows/adminFlows/config/mascotSection.spec.js
  cypress/integration/seededFlows/adminFlows/config/rateLimitSection.spec.js
  cypress/integration/seededFlows/adminFlows/config/userExperienceSection.spec.js
  cypress/integration/seededFlows/adminFlows/consumerApps/createConsumerApp.spec.js
  cypress/integration/seededFlows/adminFlows/navigationLinks/navigationLinks.spec.js
  cypress/integration/seededFlows/adminFlows/pages/landingPage.spec.js
  cypress/integration/seededFlows/analyticsFlows/analyticsNavigation.spec.js
  cypress/integration/seededFlows/articleFlows/commentOnArticle.spec.js
  cypress/integration/seededFlows/articleFlows/manageFlows/lockDiscussion.spec.js
  cypress/integration/seededFlows/articleFlows/manageFlows/unlockDiscussion.spec.js
  cypress/integration/seededFlows/articleFlows/pinArticle.spec.js
  cypress/integration/seededFlows/articleFlows/postModerationTools.spec.js
  cypress/integration/seededFlows/articleFlows/postShareOptions.spec.js
  cypress/integration/seededFlows/articleFlows/postSidebarActions.spec.js
  cypress/integration/seededFlows/articleFlows/previewProfile.spec.js
  cypress/integration/seededFlows/articleFlows/removeMainImage.spec.js
  cypress/integration/seededFlows/articleFlows/subscribeToArticleComments.spec.js
  cypress/integration/seededFlows/chatFlows/messageOptions.spec.js
  cypress/integration/seededFlows/dashboardFlows/dashboardNavigation.spec.js
  cypress/integration/seededFlows/dashboardFlows/managePost.spec.js
  cypress/integration/seededFlows/dashboardFlows/postsDashboard.spec.js
  cypress/integration/seededFlows/homeFeedFlows/feedNavigation.spec.js
  cypress/integration/seededFlows/listingFlows/deleteListing.spec.js
  cypress/integration/seededFlows/listingFlows/viewListing.spec.js
  cypress/integration/seededFlows/loggedOutFlows/runtimeBannerDeepLinking.spec.js
  cypress/integration/seededFlows/loggedOutFlows/runtimeContext.spec.js
  cypress/integration/seededFlows/loggedOutFlows/showLoginModal.spec.js
  cypress/integration/seededFlows/loginFlows/userChangePassword.spec.js
  cypress/integration/seededFlows/loginFlows/userLogin.spec.js
  cypress/integration/seededFlows/loginFlows/userLogout.spec.js
  cypress/integration/seededFlows/moderationFlows/modNavigation.spec.js
  cypress/integration/seededFlows/navigationFlows/homePageLeftSidebar.spec.js
  cypress/integration/seededFlows/notificationsFlows/notificationNavigation.spec.js
  cypress/integration/seededFlows/profileFlows/followUser.spec.js
  cypress/integration/seededFlows/profileFlows/profileUserActionsMenu.spec.js
  cypress/integration/seededFlows/profileFlows/userUpdateSettingsProfile.spec.js
  cypress/integration/seededFlows/publishingFlows/mentionUser.spec.js
  cypress/integration/seededFlows/publishingFlows/postBrowserPersistence.spec.js
  cypress/integration/seededFlows/publishingFlows/postOptions.spec.js
  cypress/integration/seededFlows/publishingFlows/previewPost.spec.js
  cypress/integration/seededFlows/readingListFlows/readingList.spec.js
  cypress/integration/seededFlows/readingListFlows/readingListArchive.spec.js
  cypress/integration/seededFlows/registrationFlows/emailRegistration.spec.js
  cypress/integration/seededFlows/searchFlows/searchTimeFiltering.spec.js
  cypress/integration/seededFlows/searchFlows/skipToContent.spec.js
  cypress/integration/seededFlows/tagsFlows/tagIndexNavigation.spec.js
  cypress/plugins/index.js
Labels: PR: reviewed-approved, area: tests, merge by any core

#14305 Add ruby platform to Gemfile.lock
  Gemfile.lock
Labels: PR: partially-approved

#14302 Validate profile field "website url" is in fact a url (don't generate local path links).
  app/models/profile.rb
  app/views/users/_profile.html.erb
  lib/data_update_scripts/20210722135549_profile_website_url_format.rb
  spec/lib/data_update_scripts/profile_website_url_format_spec.rb
  spec/models/profile_spec.rb
Labels: PR: partially-approved

#14307 [15 min fix] Added support for the --no-seed argument to bin/e2e command
  bin/e2e
  docs/tests/e2e-tests.md
  package.json
Labels: PR: partially-approved, area: tests, merge by any core

#14301 API: Add instance endpoint and spec
  app/controllers/api/v0/instances_controller.rb
  app/controllers/application_controller.rb
  config/routes.rb
  spec/requests/api/v0/instances_spec.rb
Labels: PR: unreviewed

#14313 [15-min fix] Show the navigation options regardless of screen size
  app/views/layouts/admin.html.erb
Labels: PR: unreviewed

#14292 Static Sections for Site Navigation - Pt2
  app/controllers/admin/navigation_links_controller.rb
  app/views/admin/navigation_links/_form.html.erb
  app/views/admin/navigation_links/index.html.erb
  app/views/layouts/_main_nav.html.erb
  app/views/layouts/_sidebar_nav_link.html.erb
  cypress/integration/seededFlows/navigationFlows/homePageLeftSidebar.spec.js
  spec/system/homepage/user_visits_homepage_spec.rb
Labels: PR: unreviewed

#14298 Clear recent articles cache on updating tags
  app/models/tag.rb
  spec/models/tag_spec.rb
Labels: PR: partially-approved

#14330 Revert "Clear recent articles cache on updating tags (#14298)"
  app/models/tag.rb
  spec/models/tag_spec.rb
Labels: PR: partially-approved

#14320 Fix constant lookup in Admin::WelcomeController
  app/controllers/admin/welcome_controller.rb
  spec/requests/admin/welcome_spec.rb
Labels: PR: partially-approved, merge by any core

#14321 [15-minute fix] Rename User.dev_account to User.staff_account
  app/controllers/admin/welcome_controller.rb
  app/models/user.rb
  app/services/notifications/moderation/send.rb
  db/seeds.rb
  spec/models/user_spec.rb
  spec/requests/moderations_spec.rb
  spec/requests/notifications_spec.rb
  spec/services/notifications/moderation/send_spec.rb
  spec/system/notifications/notifications_page_spec.rb
Labels: PR: partially-approved, merge by any core

#14318 [15 min fix] API: Add reading_time_minutes to /api/articles/me
  app/controllers/api/v0/articles_controller.rb
  app/views/api/v0/articles/me.json.jbuilder
  spec/requests/api/v0/articles_spec.rb
Labels: PR: partially-approved

#14353 Revert "Bump @testing-library/cypress from 7.0.6 to 8.0.0 (#14324)"
  package.json
  yarn.lock
Labels: PR: partially-approved

#14351 Update DiscussionLocksController
  app/controllers/discussion_locks_controller.rb
  spec/requests/discussion_locks_spec.rb
Labels: PR: partially-approved

#14284 Add aria-live announcement to notify users of the route change
  app/assets/javascripts/base.js.erb
  app/views/layouts/application.html.erb
Labels: PR: partially-approved

#14354 Tests: Initialize follow buttons in article liquid tags
  cypress/fixtures/users/liquidTagsUser.json
  cypress/integration/seededFlows/articleFlows/followFromArticleLiquidTag.spec.js
  spec/support/seeds/seeds_e2e.rb
Labels: PR: partially-approved, merge by any core

#14314 fix nested interactive element
  app/javascript/chat/__tests__/content.test.jsx
  app/javascript/chat/content.jsx
Labels: PR: partially-approved

#14365 Revert "Bump erb_lint from 0.0.37 to 0.1.0"
  Gemfile
  Gemfile.lock
  vendor/cache/erb_lint-0.0.37.gem
  vendor/cache/erb_lint-0.1.0.gem
Labels: PR: partially-approved

#14346 [15 min fix] Updated husky package and configuration/pre-commit hook
  .github/dependabot.yml
  .husky/pre-commit
  package.json
  yarn.lock
Labels: PR: partially-approved, merge by any core

#14308 Fix inappropriate landmark nesting dashboard 10873
  app/views/articles/stats.html.erb
  app/views/dashboards/analytics.erb
  app/views/dashboards/followers.html.erb
  app/views/dashboards/following_organizations.html.erb
  app/views/dashboards/following_podcasts.html.erb
  app/views/dashboards/following_tags.html.erb
  app/views/dashboards/following_users.html.erb
  app/views/dashboards/show.html.erb
  spec/system/dashboards/user_visits_dashboard_spec.rb
Labels: PR: partially-approved

#14370 hotfix dashboard spec failures
  spec/system/dashboards/user_visits_dashboard_spec.rb
Labels: PR: partially-approved, merge by any core

#13750 Add support for versioned releases
  .gitattributes
  .github/PULL_REQUEST_TEMPLATE.md
  CHANGELOG.md
  package.json
  scripts/build_containers.sh
  scripts/release
  scripts/stage_release
Labels: PR: unreviewed

#14317 fix member dropdown does not remain open on mouseout when click
  app/javascript/topNavigation/utilities.js
  cypress/integration/seededFlows/topNavigationFlows/MemberDropDownButton.spec.js
Labels: PR: partially-approved

#14360 Create new Issue templates
  .github/ISSUE_TEMPLATE/config.yml
Labels: PR: unreviewed

#14368 Change Travis to use Focal Fossa and Postgresql 12
  .travis.yml
Labels: PR: partially-approved

#14261 Update admin welcome checklist
  app/views/admin/overview/index.html.erb
  spec/system/admin/admin_visits_overview_spec.rb
Labels: PR: unreviewed

#14383 Skip Flaky previewProfile.spec.js Test
  cypress/integration/seededFlows/articleFlows/previewProfile.spec.js
Labels: PR: reviewed-approved, merge by any core

#14385 Minimal Seed Data for Admin Onboarding
  .travis.yml
  bin/e2e
  config/initializers/cypress_rails.rb
  cypress/integration/creatorOnboardingFlows/test.spec.js
  docs/tests/e2e-tests.md
  lib/tasks/e2e_seed.rake
  package.json
  spec/support/seeds/creator_onboarding_seed_e2e.rb
Labels: PR: unreviewed, merge by any core

#14382 hotfix comments with link tags
  app/models/comment.rb
  spec/models/comment_spec.rb
Labels: PR: partially-approved, merge by any core

#14210 Remove duplicated work display from header / profile work
  app/controllers/stories_controller.rb
  app/models/organization.rb
  app/models/profile.rb
  app/models/profile_field.rb
  app/models/user.rb
  app/serializers/search/user_serializer.rb
  app/views/profile_preview_cards/show.json.jbuilder
  app/views/shared/_profile_card_content.html.erb
  app/views/users/_meta.html.erb
  app/views/users/_metadata.html.erb
  app/views/users/show.html.erb
  cypress/integration/seededFlows/articleFlows/previewProfile.spec.js
  db/seeds.rb
  lib/data/dev_profile_fields.csv
  lib/data_update_scripts/20210630041322_migrate_data_to_work_field.rb
  lib/data_update_scripts/20210712044513_work_profile_field_follow_up.rb
  spec/factories/profile_fields.rb
  spec/fixtures/files/profile_fields.csv
  spec/lib/data_update_scripts/add_work_profile_field_spec.rb
  spec/lib/data_update_scripts/create_profile_fields_spec.rb
  spec/lib/data_update_scripts/migrate_data_to_work_field_spec.rb
  spec/lib/data_update_scripts/work_profile_field_follow_up_spec.rb
  spec/models/profile_field_spec.rb
  spec/requests/profile_preview_cards_spec.rb
  spec/requests/user/user_show_spec.rb
  spec/requests/users_onboarding_spec.rb
  spec/services/profile_fields/import_from_csv_spec.rb
  spec/support/seeds/seeds_e2e.rb
  spec/system/user/user_edits_profile_spec.rb
  spec/workers/moderator/banish_user_worker_spec.rb
Labels: PR: unreviewed, merge by any core

#14377 Stories Controller: create separate controller and views for articles by search
  app/controllers/stories/articles_search_controller.rb
  app/controllers/stories_controller.rb
  app/views/stories/articles_search/_meta.html.erb
  app/views/stories/articles_search/_nav_menu.html.erb
  app/views/stories/articles_search/index.html.erb
  config/routes.rb
  spec/requests/stories/articles_search_spec.rb
  spec/requests/stories_index_spec.rb
Labels: PR: reviewed-approved

#14390 expect to forbid, rather than expect not to permit, action for policy
  spec/policies/pinned_article_policy_spec.rb
Labels: PR: partially-approved
