Repository forem/forem, pull requests merged in 2021-08, with the labels that each got.

#14352 Fix GitHub Readme liquid tag relative URLs
  app/liquid_tags/github_tag/github_readme_tag.rb
  spec/liquid_tags/github_tag/github_readme_tag_spec.rb
  spec/support/fixtures/vcr_cassettes/github_client_repository_relative_links.yml
Labels: PR: reviewed-approved

#14345 Create Default Nav Links In New Forem (RFC #237)
  lib/tasks/add_navigation_links.rake
  lib/tasks/forem.rake
  spec/tasks/add_navigation_links_spec.rb
Labels: PR: partially-approved

#14392 ProfilePreviewCard serializes the user's created at, not the profile's
  spec/requests/profile_preview_cards_spec.rb
Labels: PR: reviewed-approved

#14259 Creator Onboarding Confirmation Page
  app/assets/images/forem-background.svg
  app/assets/images/mail.svg
  app/assets/stylesheets/views.scss
  app/assets/stylesheets/views/confirm-email.scss
  app/javascript/packs/base.jsx
  app/javascript/packs/confirmationEmail.js
  app/views/devise/confirmations/new.html.erb
  cypress/integration/creatorOnboardingFlows/confirmEmail.spec.js
Labels: PR: partially-approved

#14404 Add Missing Class Name
  app/views/devise/confirmations/new.html.erb
Labels: PR: partially-approved

#12114 Take Apple Authentication out of Beta
  app/views/admin/settings/forms/_authentication.html.erb
  app/views/shared/authentication/_providers_registration_form.html.erb
  app/views/users/_additional_authentication.html.erb
  docs/backend/auth-apple.md
  lib/data_update_scripts/20210803161945_remove_apple_auth_feature_flag.rb
  spec/lib/data_update_scripts/remove_apple_auth_feature_flag_spec.rb
  spec/requests/registrations_spec.rb
  spec/requests/user/user_settings_spec.rb
  spec/system/authentication/beta_access_providers_spec.rb
  spec/system/authentication/conditional_registration_spec.rb
  spec/system/authentication/creator_config_edit_spec.rb
  spec/system/authentication/omniauth_redirect_uri_spec.rb
  spec/system/authentication/user_logs_in_with_apple_spec.rb
  spec/system/link_for_tags_in_posts_in_notifications_spec.rb
Labels: PR: reviewed-approved

#14416 [15 min fix] Initialize follow buttons on comment index page
  app/views/comments/index.html.erb
  cypress/integration/seededFlows/articleFlows/viewArticleDiscussion.spec.js
  spec/support/seeds/seeds_e2e.rb
Labels: PR: partially-approved

#14407 Fix spacing of Nav Links in Admin
  app/assets/stylesheets/admin.scss
  app/views/admin/navigation_links/index.html.erb
Labels: PR: reviewed-approved

#14393 extend documentation on how to run cypres on wsl2
  docs/installation/windows.md
Labels: PR: partially-approved

#14341 [15-min fix] Small tweaks for small screen usage in Admin
  app/views/admin/overview/index.html.erb
  app/views/layouts/admin.html.erb
Labels: PR: partially-approved

#14421 [15 min fix] move seeded flows into correct folder
  cypress/integration/seededFlows/articleFlows/followAuthor.spec.js
  cypress/integration/seededFlows/notificationsFlows/followUserFromNotifications.spec.js
  cypress/integration/seededFlows/profileFlows/followOrganisation.spec.js
  cypress/integration/seededFlows/searchFlows/followUser.spec.js
  cypress/integration/seededFlows/tagsFlows/followTag.spec.js
Labels: PR: partially-approved, merge by any core

#14420 Separate -v and -z into two separate commands
  scripts/build_containers.sh
Labels: PR: partially-approved

#14430 [15 min fix] Left align social icons in nav
  app/views/layouts/_main_nav.html.erb
Labels: PR: partially-approved, merge by any core

#14263 Improve accessibility of top search bar
  app/assets/stylesheets/components/header.scss
  app/javascript/Search/Search.jsx
  app/javascript/Search/SearchForm.jsx
  app/javascript/Search/__stories__/SearchForm.stories.jsx
  app/javascript/Search/__tests__/Search.test.jsx
  app/javascript/Search/__tests__/SearchFormSync.test.jsx
  app/views/layouts/_top_bar.html.erb
  app/views/stories/articles_search/index.html.erb
  cypress/integration/seededFlows/searchFlows/searchForm.spec.js
Labels: PR: reviewed-approved

#14431 Refactor problematic markup for upload image (#13947)
  app/javascript/article-form/components/ArticleCoverImage.jsx
  app/javascript/article-form/components/ImageUploader.jsx
  app/javascript/article-form/components/__tests__/ArticleCoverImage.test.jsx
  app/javascript/article-form/components/__tests__/Form.test.jsx
  app/javascript/article-form/components/__tests__/ImageUploader.test.jsx
  cypress/integration/seededFlows/publishingFlows/uploadImage.spec.js
Labels: PR: partially-approved

#14438 increase ruby stack depth in travis
  .travis.yml
Labels: PR: reviewed-approved

#14439 handle openssl errors when checking podcast episode for https
  app/services/podcasts/get_media_url.rb
  spec/services/podcasts/get_media_url_spec.rb
Labels: PR: partially-approved

#14460 Tiny Enhancement: Using Optional Chaining
  app/javascript/packs/base.jsx
Labels: PR: partially-approved

#14437 [15-minute fix] Add `created_at` to listings API response
  app/controllers/api/v0/listings_controller.rb
  app/controllers/api/v0/organizations_controller.rb
  app/views/api/v0/shared/_listing.json.jbuilder
  spec/requests/api/v0/listings_spec.rb
Labels: PR: partially-approved

#14450 Handle users in Reaction#skip_notifications_for
  app/models/reaction.rb
  spec/models/reaction_spec.rb
Labels: PR: reviewed-approved

#14423 Fix readline key bindings for comments on macOS
  app/assets/javascripts/initializers/initializeCommentsPage.js.erb
  app/assets/javascripts/initializers/runtime.js
Labels: area: publishing experience, PR: partially-approved

#14461 Commit missed yarn lock changes
  yarn.lock
Labels: PR: partially-approved, merge by any core

#14451 Optimize tagged articles under feature flag
  app/services/articles/feeds/large_forem_experimental.rb
  spec/requests/stories/tagged_articles_spec.rb
Labels: PR: reviewed-approved

#14454 Make header fields in profile preview card dynamic
  app/views/profile_preview_cards/show.json.jbuilder
  spec/factories/profiles.rb
  spec/requests/profile_preview_cards_spec.rb
Labels: PR: partially-approved

#14312 Add separate section for article link to improve accessibility in the mod center
  app/assets/stylesheets/views/mod-center.scss
  app/javascript/modCenter/__tests__/moderationArticles.test.jsx
  app/javascript/modCenter/moderationArticles.jsx
  app/javascript/modCenter/singleArticle/__tests__/singleArticle.test.jsx
  app/javascript/modCenter/singleArticle/index.jsx
Labels: PR: partially-approved

#14427 Delete tag colors cache on updating tags.
  app/models/tag.rb
  spec/models/tag_spec.rb
Labels: PR: reviewed-approved

#14310 Fix Analytics Dashboard Page missing "Back To Dashboard" button
  app/views/dashboards/analytics.erb
  spec/requests/dashboard_spec.rb
Labels: PR: reviewed-approved

#14472 Add horizontal padding on preview card trigger button
  app/assets/javascripts/utilities/buildCommentHTML.js.erb
  app/views/articles/show.html.erb
  app/views/comments/_comment_date.erb
  app/views/comments/_comment_header.html.erb
Labels: PR: partially-approved

#14434 Remove button from allowed tags
  app/sanitizers/rendered_markdown_scrubber.rb
  spec/services/markdown_processor/parser_spec.rb
Labels: PR: partially-approved

#14473 Change preview card position depending on viewport
  app/assets/stylesheets/components/dropdowns.scss
  app/javascript/packs/articlePage.jsx
  app/javascript/packs/commentDropdowns.js
  app/javascript/utilities/dropdownUtils.js
  app/views/shared/_profile_preview_card.html.erb
Labels: PR: partially-approved

#14474 Run `yarn upgrade`
  package.json
  yarn.lock
Labels: PR: partially-approved

#14482 Make sure open preview cards don't collapse on scroll
  app/javascript/utilities/dropdownUtils.js
  app/views/comments/_comment_header.html.erb
  cypress/integration/seededFlows/articleFlows/viewArticleDiscussion.spec.js
Labels: PR: partially-approved

#14485 Revert "Run `yarn upgrade` (#14474)"
  package.json
  yarn.lock
Labels: PR: partially-approved

#14471 Fix reading list item count issue #14469
  app/javascript/readingList/readingList.jsx
  cypress/integration/seededFlows/readingListFlows/readingList.spec.js
  cypress/integration/seededFlows/readingListFlows/readingListArchive.spec.js
Labels: PR: partially-approved

#14488 Remove discussion lock prior to deleting an article
  app/services/users/delete_articles.rb
  spec/services/users/delete_articles_spec.rb
Labels: PR: partially-approved

#14468 Edit buttons styles for Templates responses (Mod)
  app/assets/stylesheets/views/comments.scss
  app/javascript/responseTemplates/responseTemplates.js
  app/views/comments/_form.html.erb
Labels: PR: partially-approved

#14340 Add author profile preview cards to feed
  app/assets/javascripts/utilities/buildArticleHTML.js
  app/assets/stylesheets/profile-preview-card.scss
  app/javascript/articles/__tests__/__snapshots__/Article.test.jsx.snap
  app/javascript/articles/components/Meta.jsx
  app/javascript/packs/feedPreviewCards.jsx
  app/javascript/previewCards/feedPreviewCards.jsx
  app/javascript/profilePreviewCards/MinimalProfilePreviewCard.jsx
  app/javascript/profilePreviewCards/UserMetadata.jsx
  app/views/articles/_single_story.html.erb
  app/views/articles/index.html.erb
  app/views/collections/show.html.erb
  app/views/shared/_profile_card_content.html.erb
  app/views/stories/_main_stories_feed.html.erb
  app/views/stories/articles_search/index.html.erb
  app/views/stories/tagged_articles/index.html.erb
  app/views/users/show.html.erb
  cypress/fixtures/users/seriesUser.json
  cypress/integration/seededFlows/articleFlows/followAuthor.spec.js
  cypress/integration/seededFlows/articleFlows/previewProfile.spec.js
  cypress/integration/seededFlows/articleFlows/seriesFlows/previewProfileFromSeries.spec.js
  cypress/integration/seededFlows/homeFeedFlows/profilePreviewCards.spec.js
  cypress/integration/seededFlows/loggedOutFlows/homeFeed.spec.js
  cypress/integration/seededFlows/loggedOutFlows/tagIndex.spec.js
  cypress/integration/seededFlows/searchFlows/previewProfileFromPostSearchResults.spec.js
  cypress/integration/seededFlows/tagsFlows/previewProfileFromTagIndex.spec.js
  spec/support/seeds/seeds_e2e.rb
  spec/system/search/display_articles_search_spec.rb
Labels: PR: partially-approved

#14481 Navigation Link: fix regex to allow multiline SVG
  app/models/navigation_link.rb
  spec/models/navigation_link_spec.rb
Labels: PR: reviewed-approved

#14491 Fixes #13601 - Storybook redirects off page
  app/javascript/crayons/navigation/NavigationTabs/__stories__/navigationTab.html.stories.jsx
Labels: PR: partially-approved

#14493 Streamline hover delay for preview card
  app/assets/stylesheets/profile-preview-card.scss
Labels: PR: partially-approved, merge by any core

#14495 Create crayons mobile drawer components
  app/assets/stylesheets/components/drawer-navigation.scss
  app/assets/stylesheets/components/drawers.scss
  app/assets/stylesheets/crayons.scss
  app/javascript/crayons/MobileDrawer/MobileDrawer.jsx
  app/javascript/crayons/MobileDrawer/__stories__/MobileDrawer.html.stories.jsx
  app/javascript/crayons/MobileDrawer/__stories__/MobileDrawer.stories.jsx
  app/javascript/crayons/MobileDrawer/__stories__/drawers.md
  app/javascript/crayons/MobileDrawer/__tests__/MobileDrawer.test.jsx
  app/javascript/crayons/MobileDrawer/__tests__/__snapshots__/MobileDrawer.test.jsx.snap
  app/javascript/crayons/MobileDrawer/index.js
  app/javascript/crayons/index.js
  app/javascript/crayons/navigation/MobileDrawerNavigation/MobileDrawerNavigation.jsx
  app/javascript/crayons/navigation/MobileDrawerNavigation/__stories__/MobileDrawerNavigation.stories.jsx
  app/javascript/crayons/navigation/MobileDrawerNavigation/__stories__/mobileDrawerNavigation.html.stories.jsx
  app/javascript/crayons/navigation/MobileDrawerNavigation/__stories__/mobileDrawerNavigation.md
  app/javascript/crayons/navigation/MobileDrawerNavigation/__tests__/MobileDrawerNavigation.spec.js
  app/javascript/crayons/navigation/MobileDrawerNavigation/__tests__/__snapshots__/MobileDrawerNavigation.spec.js.snap
  app/javascript/crayons/navigation/index.js
Labels: PR: unreviewed

#14505 Fix PropTypes folder path typo in documentation for Preact
  docs/frontend/preact.md
Labels: PR: partially-approved

#14506 fix(user-profile): remove duplicate 'display email on profile' checkbox
  app/views/users/_profile.html.erb
Labels: PR: reviewed-approved

#14507 Encapsulate initializer methods in modules
  config/initializers/carrierwave.rb
  config/initializers/slack_notifier.rb
Labels: PR: reviewed-approved, merge by any core

#14521 Bullet: rename deprecated add_whitelist to add_safelist
  config/environments/development.rb
  config/environments/test.rb
Labels: PR: partially-approved

#14524 svgo: update configuration for 2.4 syntax
  svgo.config.js
Labels: PR: partially-approved

#14517 Replace EmojiOne with Twemoji
  app/assets/images/emoji/apple-eyes.png
  app/assets/images/emoji/apple-fire.png
  app/assets/images/emoji/emoji-one-bookmark.png
  app/assets/images/emoji/emoji-one-hands.png
  app/assets/images/emoji/emoji-one-heart.png
  app/assets/images/emoji/emoji-one-nausea-face-gray.png
  app/assets/images/emoji/emoji-one-nausea-face.png
  app/assets/images/emoji/emoji-one-thinking.png
  app/assets/images/emoji/emoji-one-thumbs-down-gray.png
  app/assets/images/emoji/emoji-one-thumbs-down.png
  app/assets/images/emoji/emoji-one-thumbs-up-gray.png
  app/assets/images/emoji/emoji-one-thumbs-up.png
  app/assets/images/emoji/emoji-one-unicorn.png
  app/assets/images/reactions-stack.png
  app/assets/images/readinglist-button.png
  app/assets/images/twemoji/hands.svg
  app/assets/images/twemoji/suspicious.svg
  app/assets/images/twemoji/thinking.svg
  app/assets/images/twemoji/thumb-down.svg
  app/assets/images/twemoji/thumb-up.svg
  app/assets/stylesheets/views/notifications.scss
  app/helpers/notifications_helper.rb
  app/javascript/articles/__stories__/podcastArticle.stories.jsx
  app/javascript/articles/__stories__/userArticle.stories.jsx
  app/javascript/articles/__stories__/videoArticles.stories.jsx
  app/javascript/articles/__tests__/Article.test.jsx
  app/javascript/chat/ChatChannelSettings/MembershipManager/Membership.jsx
  app/views/comments/deleted_commentable_comment.html.erb
  app/views/moderations/_reactions.html.erb
  app/views/moderations/actions_panel.html.erb
  app/views/moderations/mod.html.erb
  app/views/notifications/shared/_comment_box.html.erb
Labels: area: design, PR: partially-approved

#14533 Adjust images used for moderation
  app/views/moderations/_reactions.html.erb
  app/views/moderations/actions_panel.html.erb
Labels: PR: partially-approved, merge by any core

#14079 Remove hardcoded user profile fields
  app/controllers/stories_controller.rb
  app/controllers/users_controller.rb
  app/decorators/user_decorator.rb
  app/models/profile.rb
  app/models/profile_field.rb
  app/models/user.rb
  app/policies/user_policy.rb
  app/services/profiles/update.rb
  app/services/users/suggest_for_sidebar.rb
  app/views/api/v0/shared/_user_show.json.jbuilder
  app/views/articles/feed.rss.builder
  app/views/organizations/_header.html.erb
  app/views/shared/_profile_card_content.html.erb
  app/views/users/_liquid.html.erb
  app/views/users/_meta.html.erb
  app/views/users/_metadata.html.erb
  app/views/users/index.json.jbuilder
  app/views/users/show.html.erb
  config/environments/test.rb
  cypress/integration/seededFlows/profileFlows/userUpdateSettingsProfile.spec.js
  lib/data_update_scripts/20200922072907_backfill_profile_skills_languages.rb
  lib/data_update_scripts/20201223013903_set_proper_display_area_for_profile_fields.rb
  spec/helpers/application_helper_spec.rb
  spec/lib/data_update_scripts/set_proper_display_area_for_profile_fields_spec.rb
  spec/models/profile_field_spec.rb
  spec/models/user_spec.rb
  spec/requests/api/v0/organizations_spec.rb
  spec/requests/api/v0/users_spec.rb
  spec/requests/user/user_profile_spec.rb
  spec/requests/user/user_settings_spec.rb
  spec/requests/user/user_show_spec.rb
  spec/requests/user/user_suggestions_spec.rb
  spec/requests/users_onboarding_spec.rb
  spec/services/profiles/update_spec.rb
  spec/support/seeds/seeds_e2e.rb
Labels: PR: unreviewed, merge by any core

#14534 Mark hero banner html_safe
  app/views/layouts/application.html.erb
Labels: PR: partially-approved

#14532 Fix erblint failures
  app/views/moderations/actions_panel.html.erb
Labels: PR: partially-approved

#14504 Make listing details modal close on internally-triggered navigation
  app/javascript/listings/listings.jsx
  cypress/integration/seededFlows/listingFlows/viewListing.spec.js
Labels: PR: partially-approved

#14538 Articles::DetectAnimatedImages: raise default timeout for FastImage
  app/services/articles/detect_animated_images.rb
Labels: PR: partially-approved

#14542 [15min fix] Show the user's email on their profile when they chose to share
  app/views/users/show.html.erb
Labels: PR: reviewed-approved

#14545 Styling of Definition List
  app/assets/stylesheets/base/typography.scss
Labels: area: design, PR: partially-approved, Crayons, tech: frontend

#14537 Remove ahoy from Share Post dropdown
  app/javascript/packs/articlePage.jsx
Labels: PR: partially-approved

#14543 Add user count to instance API
  app/controllers/api/v0/instances_controller.rb
  spec/requests/api/v0/instances_spec.rb
Labels: PR: partially-approved

#14487 Only print BUILDKITE environment variables when they were present
  scripts/build_containers.sh
Labels: PR: unreviewed

#14547 Look for <html> tags instead of <body> for email viewing
  app/models/email_message.rb
  app/views/admin/email_messages/show.html.erb
  app/views/admin/feedback_messages/_feedback_message.html.erb
Labels: PR: partially-approved

#14544 Add bio to onboarding
  app/javascript/onboarding/components/ProfileForm.jsx
  app/views/users/_profile.html.erb
Labels: PR: partially-approved

#14546 Revise editor publish logic
  app/javascript/article-form/actions.js
  app/javascript/article-form/articleForm.jsx
  cypress/integration/seededFlows/publishingFlows/publishOrSavePost.spec.js
Labels: PR: reviewed-approved

#14139 Make podcast-playback to be controllable via keyboard
  app/assets/javascripts/initializers/initializePodcastPlayback.js
  app/assets/stylesheets/podcast-episodes-show.scss
  app/views/podcast_episodes/show.html.erb
  cypress/integration/seededFlows/podcastFlows/togglePodcastPlayback.spec.js
  public/media/crow-call.mp3
  spec/support/seeds/seeds_e2e.rb
Labels: PR: unreviewed

#14556 [15 min fix] Initialize follow button on podcast page
  app/views/podcast_episodes/index.html.erb
  cypress/integration/seededFlows/loggedOutFlows/showLoginModal.spec.js
  cypress/integration/seededFlows/podcastFlows/followPodcast.spec.js
  spec/support/seeds/seeds_e2e.rb
Labels: PR: partially-approved, merge by any core

#12947 Profile generalization: cleanup
  app/assets/images/forem-background.svg
  app/assets/stylesheets/views/comments.scss
  app/controllers/api/v0/organizations_controller.rb
  app/controllers/api/v0/readinglist_controller.rb
  app/controllers/api/v0/users_controller.rb
  app/controllers/profiles_controller.rb
  app/controllers/registrations_controller.rb
  app/controllers/users_controller.rb
  app/models/user.rb
  app/services/users/suggest_recent.rb
  app/services/users/update.rb
  app/validators/profile_validator.rb
  app/views/users/_metadata.html.erb
  app/views/users/_profile.html.erb
  babel.config.js
  db/migrate/20210309064924_remove_profile_columns_from_user.rb
  db/schema.rb
  docs/frontend/preact.md
  docs/installation/windows.md
  docs/self-hosting.md
  spec/models/navigation_link_spec.rb
  spec/requests/user/user_profile_spec.rb
  spec/services/users/update_spec.rb
Labels: PR: reviewed-approved, merge by any core

#14557 [15 min fix] Stop skip content link flashing on mobile
  app/assets/stylesheets/components/header.scss
Labels: PR: partially-approved, merge by any core

#14559 [15 min fix] Swap position of profile dropdown for users
  app/assets/stylesheets/views/profile.scss
  app/views/users/show.html.erb
Labels: PR: partially-approved

#14565 Remove myself from codeowners
  .github/CODEOWNERS
Labels: PR: reviewed-approved

#14494 Fix Sponsors Image display in homefeed and sponsors page.
  app/views/articles/_single_sponsor.html.erb
  app/views/pages/_sponsor_image.html.erb
  app/views/pages/sponsors.html.erb
Labels: PR: partially-approved

#13875 RFC 190: Forem Creator Signup Page
  app/assets/images/eye-off.svg
  app/assets/images/eye.svg
  app/assets/images/pencil.svg
  app/assets/images/twemoji/hands.svg
  app/assets/images/twemoji/suspicious.svg
  app/assets/images/twemoji/thinking.svg
  app/assets/images/twemoji/thumb-down.svg
  app/assets/images/twemoji/thumb-up.svg
  app/assets/stylesheets/views/confirm-email.scss
  app/controllers/registrations_controller.rb
  app/javascript/packs/foremCreatorSignup.js
  app/models/tweet.rb
  app/views/devise/registrations/by_email.html.erb
  app/views/devise/registrations/new.html.erb
  app/views/notifications/shared/_comment_box.html.erb
  app/views/shared/authentication/_email_registration_form.html.erb
  app/views/shared/authentication/_forem_creator_signup.html.erb
  cypress/integration/creatorOnboardingFlows/creatorSignup.spec.js
  spec/requests/registrations_spec.rb
Labels: PR: unreviewed, merge by any core

#14566 Fix error adding and removing tags as mod
  app/javascript/actionsPanel/actionsPanel.js
  cypress/integration/seededFlows/loggedOutFlows/showLoginModal.spec.js
  cypress/integration/seededFlows/moderationFlows/adjustPostTags.spec.js
  cypress/integration/seededFlows/tagsFlows/followTag.spec.js
  cypress/support/commands.js
  spec/support/seeds/seeds_e2e.rb
Labels: PR: partially-approved

#14558 Admin Member view: add Tools::HeaderComponent to reduce duplication
  app/components/admin/users/tools/credits_component.html.erb
  app/components/admin/users/tools/emails_component.html.erb
  app/components/admin/users/tools/header_component.html.erb
  app/components/admin/users/tools/header_component.rb
  app/components/admin/users/tools/notes_component.html.erb
  app/components/admin/users/tools/organizations_component.html.erb
  app/components/admin/users/tools/reactions_component.html.erb
  app/components/admin/users/tools/reports_component.html.erb
  app/views/admin/users/new/_tools_section_header.html.erb
Labels: PR: partially-approved

#14581 Revert "Bump webpack-dev-server from 3.11.2 to 4.0.0 (#14572)"
  package.json
  yarn.lock
Labels: PR: partially-approved, merge by any core

#14580 Remove API docs packages ✂️ ✂️ ✂️
  Gemfile
  Gemfile.lock
  package.json
  vendor/cache/yard-0.9.26.gem
  vendor/cache/yard-activerecord-0.0.16.gem
  vendor/cache/yard-activesupport-concern-0.0.1.gem
  yarn.lock
Labels: PR: partially-approved

#14588 Fix broken links
  CONTRIBUTING.md
  README.md
Labels: PR: partially-approved

#14589 [15-minute fix] Fix `Users::SuggestRecent#established_user_comment_count`
  app/services/users/suggest_recent.rb
Labels: PR: reviewed-approved

#14590 Unify padding of code blocks
  app/assets/stylesheets/components/syntax.scss
Labels: PR: partially-approved, merge by any core

#14612 Install foreman for procfile and setup appdomain in gitpod
  .gitpod.yml
Labels: PR: partially-approved

#14138 Introduce `Settings::Base`
  Gemfile
  Gemfile.lock
  app/models/settings/authentication.rb
  app/models/settings/base.rb
  app/models/settings/campaign.rb
  app/models/settings/community.rb
  app/models/settings/general.rb
  app/models/settings/rate_limit.rb
  app/models/settings/smtp.rb
  app/models/settings/user_experience.rb
  config/initializers/doorkeeper.rb
  config/initializers/rails_settings.rb
  lib/generators/settings_model/USAGE
  lib/generators/settings_model/templates/model.erb
  spec/models/settings/base_spec.rb
  spec/rails_helper.rb
  vendor/cache/rails-settings-cached-2.6.0.gem
  vendor/cache/with_model-2.1.5.gem
Labels: PR: partially-approved, merge by any core

#14591 Add support for JSX copy paste in Storybook
  app/javascript/.storybook/main.js
  app/javascript/.storybook/preview.js
  app/javascript/crayons/Dropdown/__stories__/Dropdown.stories.jsx
  package.json
  yarn.lock
Labels: PR: partially-approved

#14604 Routine Rubocop autofixes
  config/initializers/liquid.rb
  config/initializers/reverse_markdown.rb
  config/initializers/sidekiq.rb
Labels: PR: partially-approved

#14616 Various cleanups
  app/controllers/async_info_controller.rb
  app/controllers/shell_controller.rb
  app/helpers/application_helper.rb
  app/models/device.rb
  app/models/organization_membership.rb
  app/models/podcast_episode.rb
  app/models/profile.rb
  app/models/settings/general.rb
  app/models/user.rb
  app/queries/admin/moderators_query.rb
  config/routes.rb
  db/migrate/20210830043852_drop_user_title_from_organization_memberships.rb
  db/migrate/20210830062129_drop_duration_in_seconds_from_podcast_episodes.rb
  db/migrate/20210830062627_drop_app_bundle_from_devices.rb
  db/schema.rb
  spec/requests/async_info_spec.rb
Labels: PR: partially-approved

#14617 Fixed "Pin to profile" button styling
  app/assets/stylesheets/dashboard.scss
Labels: PR: partially-approved

#14619 Make sure input can scroll into view on mobile
  app/assets/stylesheets/preact/onboarding-modal.scss
Labels: PR: reviewed-approved

#14633 Update README.md
  README.md
Labels: PR: reviewed-approved

#14639 Remove Database.table_available?
  app/lib/database.rb
  app/models/profile.rb
  app/models/settings/base.rb
Labels: PR: partially-approved

#14618 Only tech admins can manage page feature flags
  app/views/admin/pages/_form.html.erb
  spec/requests/admin/pages_spec.rb
Labels: PR: partially-approved, merge by any core

#14621 Adds validations to avoid creating unnecessary PNs
  app/models/device.rb
  app/queries/consumer_apps/rpush_app_query.rb
  spec/queries/consumer_apps/rpush_app_query_spec.rb
  spec/services/push_notifications/send_spec.rb
  spec/support/rpush_helpers.rb
Labels: PR: partially-approved
