Repository forem/forem, pull requests merged in 2021-04, with the labels that each got.

#12862 Add flag link to profile dropdown view
  app/controllers/stories_controller.rb
  app/javascript/packs/profileDropdown.js
  app/javascript/profileDropdown/flagButton.js
  app/views/users/show.html.erb
  spec/requests/reactions_spec.rb
  spec/system/user/trusted_user_flags_user_spec.rb
Labels: PR: partially-approved, merge by any core

#13219 Make docs reflect code more accurately
  docs/backend/roles.md
Labels: PR: reviewed-approved

#13224 [15-Minute Fix] Fix Flaky trusted_user_flags_user_spec
  spec/system/user/trusted_user_flags_user_spec.rb
Labels: PR: unreviewed

#13137 Add endpoint for articles sorted by published date
  app/services/article_api_index_service.rb
  config/routes.rb
  docs/api_v0.yml
  spec/requests/api/v0/articles_spec.rb
Labels: PR: unreviewed

#13174 User#followed_articles->Article.cached_tagged_with
  app/models/article.rb
  app/models/user.rb
  spec/models/article_spec.rb
Labels: PR: unreviewed

#13225 Skip a flaky e2e spec
  cypress/integration/articleFlows/commentOnArticle.spec.js
Labels: PR: unreviewed

#13177 Fix app/services' ruby 2.7 kwargs warnings
  app/services/articles/builder.rb
  app/services/articles/creator.rb
  app/services/articles/updater.rb
  app/services/authentication/authenticator.rb
  app/services/broadcasts/welcome_notification/generator.rb
  app/services/chat_channels/create_with_users.rb
  app/services/chat_channels/find_or_create.rb
  app/services/chat_channels/send_invitation.rb
  app/services/chat_channels/update_channel.rb
  app/services/credits/buyer.rb
  app/services/credits/ledger.rb
  app/services/exporter/service.rb
  app/services/images/generate_social_image.rb
  app/services/medium_article_retrieval_service.rb
  app/services/mentions/create_all.rb
  app/services/notifications/milestone/send.rb
  app/services/notifications/moderation/send.rb
  app/services/notifications/new_badge_achievement/send.rb
  app/services/notifications/new_comment/send.rb
  app/services/notifications/new_follower/follow_data.rb
  app/services/notifications/new_follower/send.rb
  app/services/notifications/new_mention/send.rb
  app/services/notifications/notifiable_action/send.rb
  app/services/notifications/reactions/reaction_data.rb
  app/services/notifications/reactions/send.rb
  app/services/notifications/remove_all.rb
  app/services/notifications/remove_all_by_action.rb
  app/services/notifications/tag_adjustment_notification/send.rb
  app/services/notifications/update.rb
  app/services/notifications/welcome_notification/send.rb
  app/services/podcasts/create_episode.rb
  app/services/podcasts/get_media_url.rb
  app/services/podcasts/update_episode_media_url.rb
  app/services/slack/announcer.rb
  app/services/slack/messengers/article_fetched_feed.rb
  app/services/slack/messengers/comment_user_warned.rb
  app/services/slack/messengers/feedback.rb
  app/services/slack/messengers/note.rb
  app/services/slack/messengers/potential_spammer.rb
  app/services/slack/messengers/reaction_vomit.rb
  app/services/slack/messengers/sponsorship.rb
  app/services/user_subscriptions/create_from_controller_params.rb
  app/services/user_subscriptions/is_subscribed_cache_checker.rb
  app/services/users/delete.rb
  app/services/users/remove_role.rb
  app/services/webhook/dispatch_event.rb
  bin/knapsack_pro_rspec
  spec/services/articles/suggest_spec.rb
  spec/services/push_notifications/send_spec.rb
  spec/services/slack/announcer_spec.rb
  spec/services/slack/messengers/article_fetched_feed_spec.rb
  spec/services/slack/messengers/article_published_spec.rb
  spec/services/slack/messengers/comment_user_warned_spec.rb
  spec/services/slack/messengers/feedback_spec.rb
  spec/services/slack/messengers/note_spec.rb
  spec/services/slack/messengers/potential_spammer_spec.rb
  spec/services/slack/messengers/reaction_vomit_spec.rb
  spec/services/slack/messengers/sponsorship_spec.rb
  spec/services/users/delete_spec.rb
  spec/services/users/remove_role_spec.rb
Labels: PR: partially-approved

#13237 Change file name to remove ERB suffix
  docs/frontend/plain-js.md
Labels: PR: reviewed-approved

#13234 [15 min fix] ✂️✂️✂️ Remove preact-textarea-autosize library ✂️✂️✂️
  app/javascript/article-form/components/Title.jsx
  app/javascript/chat/compose.jsx
  package.json
  yarn.lock
Labels: PR: partially-approved

#13233 [15 min fix] Link settings profile fields with their labels
  app/views/users/_profile.html.erb
Labels: PR: partially-approved

#13232 [15 min fix] improve accessible names of dashboard post actions
  app/views/dashboards/_dashboard_article_row.html.erb
Labels: PR: partially-approved

#13231 [15 min fix] Ensure home and sign up links in sidebar are announced once to screen…
  app/views/layouts/_main_nav.html.erb
Labels: PR: partially-approved

#13218 [15 minute fix] Fix word wrapping on mobile dashboard
  app/assets/stylesheets/components/buttons.scss
Labels: PR: partially-approved

#13251 Declare DD_VERSION in prerun.sh
  datadog/prerun.sh
Labels: PR: partially-approved

#13255 Downgrade dogstatsd-ruby to 4.8.3
  Gemfile.lock
  vendor/cache/dogstatsd-ruby-4.8.3.gem
  vendor/cache/dogstatsd-ruby-4.9.0.gem
Labels: PR: partially-approved

#13258 Declare DD_VERSION in prerun.sh 2nd try
  datadog/prerun.sh
Labels: PR: partially-approved

#13261 Update bundler from 2.1 to 2.2
  Containerfile
Labels: PR: partially-approved

#13259 Limit mentions in posts
  app/models/article.rb
  app/models/comment.rb
  spec/models/article_spec.rb
  spec/models/comment_spec.rb
Labels: PR: unreviewed

#13265 Change frame limit to match imgproxy
  app/uploaders/base_uploader.rb
Labels: PR: partially-approved

#13269 [15 min fix] Allow resize hook to contrain max-height as well as min
  app/javascript/article-form/components/Title.jsx
  app/javascript/utilities/textAreaUtils.js
Labels: PR: unreviewed

#13253 Fix deprecation warning
  app/controllers/api/v0/organizations_controller.rb
Labels: PR: partially-approved

#13262 Use ActiveModel::Errors#add to fix deprecation warning
  app/controllers/articles_controller.rb
Labels: PR: reviewed-approved

#13246 [15 min fix] Enable Style/StringChars from Rubocop 1.12.0
  .rubocop.yml
Labels: PR: partially-approved, merge by any core

#13247 Adjust default Forem's RSS feed algorithm to allow non featured articles
  app/controllers/articles_controller.rb
  spec/requests/articles/articles_spec.rb
Labels: Forem team, PR: partially-approved, PR: unreviewed, area: syndication

#13085 Upgrade to Ahoy 2.0.x
  Gemfile
  Gemfile.lock
  app/lib/constants/site_config.rb
  app/mailers/notify_mailer.rb
  app/models/email_message.rb
  app/models/site_config.rb
  app/services/email_digest_article_collector.rb
  app/views/admin/configs/show.html.erb
  app/views/admin/email_messages/show.html.erb
  config/initializers/ahoy_email.rb
  db/migrate/20210323145228_drop_ahoy_messages_opened_at.rb
  db/schema.rb
  spec/mailers/digest_mailer_spec.rb
  spec/mailers/notify_mailer_spec.rb
  spec/requests/admin/configs_spec.rb
  spec/requests/admin/feedback_messages_spec.rb
  spec/services/email_digest_article_collector_spec.rb
  vendor/cache/ahoy_email-2.0.2.gem
Labels: PR: unreviewed

#13274 Remove unneeded ahoy version
  vendor/cache/ahoy_email-1.1.1.gem
Labels: PR: partially-approved

#13235 ✂️ Remove search from Connect
  app/controllers/search_controller.rb
  app/javascript/chat/chat.jsx
  app/javascript/chat/util.js
  app/serializers/search/chat_channel_membership_serializer.rb
  app/services/search/postgres/chat_channel_membership.rb
  spec/requests/search_spec.rb
  spec/services/search/postgres/chat_channel_membership_spec.rb
Labels: PR: unreviewed

#13278 Update Bundler version
  Containerfile
Labels: PR: partially-approved

#13276 [15 Min Fix]: Prevent NoMethodError when Html variant is not present
  app/views/pages/badge.html.erb
Labels: PR: partially-approved

#13280 Re-add Darwin-20 to gemfile.lock
  Gemfile.lock
Labels: PR: reviewed-approved, merge by any core

#13256 Fix Ruby 2.7 kwargs' warnings & misc spec warnings
  Gemfile
  Gemfile.lock
  app/controllers/api/v0/organizations_controller.rb
  app/controllers/chat_channels_controller.rb
  app/controllers/comments_controller.rb
  app/controllers/github_repos_controller.rb
  app/helpers/application_helper.rb
  app/helpers/articles_helper.rb
  app/helpers/social_image_helper.rb
  app/mailers/application_mailer.rb
  app/queries/articles/active_threads_query.rb
  app/views/articles/tags/_sidebar_additional.html.erb
  config/initializers/slack_notifier.rb
  lib/slack/notifier/util/link_formatter.rb
  spec/models/github_repo_spec.rb
  spec/models/shared_examples/user_subscription_sourceable.rb
  spec/queries/articles/active_threads_query_spec.rb
  spec/requests/api/v0/listings_spec.rb
  spec/requests/email_subscriptions_spec.rb
  spec/requests/user/user_profile_spec.rb
  spec/system/comments/user_views_podcast_comments_spec.rb
  spec/uploaders/article_image_uploader_spec.rb
  vendor/cache/stripe-ruby-mock-3.0.1.gem
  vendor/cache/stripe-ruby-mock-3.1.0.rc2.gem
Labels: PR: partially-approved

#13154 Fix Wikipedia liquid tag styles
  app/assets/stylesheets/ltags/WikipediaTag.scss
Labels: PR: partially-approved

#13281 Fixed bug with iOS devices that crashed the post editor
  app/javascript/crayons/MentionAutocompleteTextArea/MentionAutocompleteTextArea.jsx
Labels: PR: partially-approved, area: comments, area: publishing experience, merge by any core, tech: javascript

#13283 [15 Min Fix]: Prevent NoMethodError when Html variant is not present, take 2
  app/views/pages/badge.html.erb
Labels: PR: partially-approved, merge by any core

#13288 Remove some HTML errors
  app/views/articles/_single_story.html.erb
  app/views/articles/index.html.erb
  app/views/doorkeeper/authorizations/error.html.erb
  app/views/doorkeeper/authorizations/new.html.erb
  app/views/doorkeeper/authorizations/show.html.erb
  app/views/doorkeeper/authorized_applications/index.html.erb
  app/views/layouts/_top_bar.html.erb
  app/views/layouts/admin.html.erb
Labels: PR: partially-approved

#13270 Update Analytics Dashboard time navigation to tabs
  app/assets/stylesheets/dashboard.scss
  app/javascript/analytics/dashboard.js
  app/views/shared/_stats.html.erb
Labels: PR: partially-approved

#13229 [15 Min Fix]: Extract a post's followers out of service and onto Article model
  app/models/article.rb
  app/services/notifications/notifiable_action/send.rb
  app/workers/notifications/notifiable_action_worker.rb
  spec/models/article_spec.rb
Labels: PR: partially-approved

#13294 [15-min-fix] Use safe navigation in case of nil email messages
  app/views/admin/feedback_messages/_feedback_message.html.erb
Labels: PR: unreviewed

#13282 [15-minute fix] Don't allow markdown to use CSS classes
  app/sanitizers/rendered_markdown_scrubber.rb
  app/services/markdown_processor/parser.rb
  spec/services/markdown_processor/parser_spec.rb
  spec/spec_helper.rb
Labels: PR: partially-approved

#13297 [15-min-fix] Add email type as utm_campaign column
  app/mailers/notify_mailer.rb
  spec/mailers/notify_mailer_spec.rb
Labels: PR: reviewed-approved

#13302 [15-Minute Fix] ✂️ Remove Superfluous app_url From Navigation Links Index
  app/views/admin/navigation_links/index.html.erb
Labels: PR: partially-approved

#13257 Fix "Infinity" dashboard analytics by using 2 digits for hardcoded month and day for JS Date
  app/javascript/analytics/dashboard.js
Labels: PR: partially-approved, include in changelog

#13301 Fix link_formatter.rb's lints
  lib/slack/notifier/util/link_formatter.rb
Labels: PR: partially-approved

#13303 Fix rescue in EdgeCache::Bust
  app/services/edge_cache/bust.rb
Labels: PR: partially-approved

#13279 Ensure we have current user information before deciding how to handle the "flag user" button
  app/javascript/profileDropdown/flagButton.js
  spec/system/user/trusted_user_flags_user_spec.rb
Labels: PR: partially-approved, area: moderation, tech: javascript

#13272 Fix misleading title on svg tag
  app/views/notifications/shared/_comment_box.html.erb
Labels: PR: partially-approved

#12755 Fixed Reading List on Mobile + Small Improvements
  app/javascript/readingList/__tests__/readingList.test.jsx
  app/javascript/readingList/components/ItemListLoadMoreButton.jsx
  app/javascript/readingList/components/ItemListTags.jsx
  app/javascript/readingList/components/TagList.jsx
  app/javascript/readingList/components/__tests__/ItemListLoadMoreButton.test.jsx
  app/javascript/readingList/components/__tests__/ItemListTags.test.jsx
  app/javascript/readingList/readingList.jsx
  app/javascript/searchableItemList/searchableItemList.js
  app/javascript/shared/components/useMediaQuery.js
  cypress/fixtures/search/emptyReadingList.json
  cypress/fixtures/search/readingList.json
  cypress/fixtures/search/readingListFilterByTagProductivity.json
  cypress/fixtures/search/readingListFilterByText.json
  cypress/integration/readingListFlows/readingList.spec.js
  cypress/integration/readingListFlows/readingListArchive.spec.js
  jest.config.js
Labels: PR: partially-approved, area: reading list, merge by any core, tech: frontend

#13290 Small post Rails 6.1 fixes
  Gemfile.lock
  db/schema.rb
  lib/data_update_scripts/20210218041143_backfill_usernames.rb
  spec/lib/data_update_scripts/backfill_usernames_spec.rb
Labels: PR: reviewed-approved, merge by any core

#13305 Remove unused code
  app/sanitizers/rendered_markdown_scrubber.rb
Labels: PR: partially-approved

#13321 [15-Minute Fix] Update Sidebar Tags Placeholder in the SiteConfig
  app/lib/constants/site_config.rb
Labels: PR: partially-approved

#13327 [15 Min Fix] Now the load more button only appears (if necessary) when the reading list is finished loading
  app/javascript/readingList/readingList.jsx
Labels: PR: partially-approved, area: reading list, merge by any core, tech: javascript

#13332 [Rails 6.1] Remove superflous initializer
  config/initializers/feature_policy.rb
Labels: PR: reviewed-approved, merge by any core

#13328 [15-minute fix] Rename unidiomatic methods
  app/controllers/notification_subscriptions_controller.rb
  app/policies/api_secret_policy.rb
  app/policies/application_policy.rb
  app/policies/article_policy.rb
  app/policies/chat_channel_policy.rb
  app/policies/comment_policy.rb
  app/policies/follow_policy.rb
  app/policies/listing_policy.rb
  app/policies/message_policy.rb
  app/policies/response_template_policy.rb
  app/services/broadcasts/welcome_notification/generator.rb
  app/services/users/remove_role.rb
Labels: PR: partially-approved

#13326 [15-Minute Fix] Sidebar Tags Show Relevant Posts on Homepage
  app/helpers/articles_helper.rb
  app/queries/articles/active_threads_query.rb
  app/views/sidebars/_homepage_content.html.erb
  spec/queries/articles/active_threads_query_spec.rb
Labels: PR: partially-approved

#13341 Fix mention autocomplete positioning after scroll
  app/javascript/utilities/textAreaUtils.js
Labels: PR: partially-approved

#13155 Fix Reddit liquid tag styles
  app/assets/stylesheets/ltags/RedditTag.scss
Labels: PR: partially-approved

#13254 [15-min-fix] Improve invalid FeedbackMessage error msg
  app/controllers/feedback_messages_controller.rb
  app/models/feedback_message.rb
  spec/models/feedback_message_spec.rb
Labels: PR: partially-approved

#13355 Added missing entries in Gemfile.lock
  Gemfile.lock
Labels: PR: partially-approved

#13227 [15-min-fix] Fix removing cover img from v2 editor and dashboard link
  app/javascript/article-form/components/ArticleCoverImage.jsx
  app/views/articles/delete_confirm.html.erb
  cypress/integration/articleFlows/removeMainImage.spec.js
  cypress/integration/navigationFlows/homePageLeftSidebar.spec.js
  cypress/support/commands.js
  spec/requests/dashboard_spec.rb
Labels: PR: partially-approved

#13351 [15-min-fix] Don't prevent reaction notifications from being sent
  app/models/reaction.rb
  spec/models/notification_spec.rb
  spec/models/reaction_spec.rb
Labels: PR: partially-approved

#13236 Clean up initializePage
  app/assets/javascripts/initializePage.js
Labels: PR: reviewed-approved

#13344 [15-minute fix] Remove useless system spec ✂️
  spec/system/comments/user_views_podcast_comments_spec.rb
Labels: PR: reviewed-approved

#13346 Add open reports count to admin overview
  app/controllers/admin/overview_controller.rb
  app/models/feedback_message.rb
  app/views/admin/overview/index.html.erb
Labels: PR: unreviewed

#13363 Remove SheCoded Specific Code
  app/assets/images/SheCodedBackground.png
  app/assets/images/shecoded-background.jpg
  app/lib/constants/site_config.rb
  app/views/social_previews/articles/shecoded.html.erb
  lib/data_update_scripts/20200225114328_update_tags_social_preview_templates.rb
  spec/requests/articles/articles_spec.rb
  spec/requests/social_previews_spec.rb
  spec/requests/stories_index_spec.rb
Labels: PR: partially-approved

#13287 Update `GET /followers` API endpoint
  app/controllers/api/v0/followers_controller.rb
  app/controllers/concerns/json_api_sort_param.rb
  app/views/api/v0/followers/users.json.jbuilder
  docs/api_v0.yml
  spec/controllers/concerns/json_api_sort_param_spec.rb
  spec/requests/api/v0/followers_spec.rb
Labels: PR: partially-approved, include in changelog

#13375 [15 min fix] API docs: rename deprecated code samples extension
  docs/api_v0.yml
Labels: PR: reviewed-approved

#13376 [15 minute fix] Cleanup of post preview E2E tests
  app/javascript/article-form/articleForm.jsx
  cypress/integration/publishingFlows/previewPost.spec.js
Labels: PR: partially-approved, area: publishing experience, area: tests, merge by any core

#13379 Simplify CarrierWave's local_storage_config
  config/initializers/carrierwave.rb
Labels: PR: partially-approved

#13263 Rename comment-mentioned-user class added by Html::Parser
  app/assets/stylesheets/chat.scss
  app/models/article.rb
  app/models/comment.rb
  app/models/message.rb
  app/services/html/parser.rb
  app/services/mentions/create_all.rb
  lib/data_update_scripts/20210412183428_resave_all_comment_mentioned_messages.rb
  lib/data_update_scripts/20210412185444_resave_all_comment_mentioned_comments.rb
  lib/data_update_scripts/20210412185449_resave_all_comment_mentioned_articles.rb
  spec/services/markdown_processor/parser_spec.rb
Labels: PR: partially-approved

#11874 Fix feed navigation shortcuts when first article is not 100% visible
  app/javascript/shared/components/useListNavigation.js
  app/javascript/utilities/viewport.js
Labels: PR: partially-approved

#13369 15 minute fix: Add default argument to JsonApiSortParam
  app/controllers/api/v0/followers_controller.rb
  app/controllers/concerns/json_api_sort_param.rb
  spec/controllers/concerns/json_api_sort_param_spec.rb
Labels: PR: partially-approved

#13333 Switch from combobox to plaintextArea on click outside
  app/javascript/crayons/MentionAutocompleteTextArea/MentionAutocompleteTextArea.jsx
  cypress/integration/articleFlows/commentOnArticle.spec.js
Labels: PR: partially-approved

#13350 Remove HTML errors (PR n°2 - fixed)
  app/assets/javascripts/initializers/initializeArticleReactions.js
  app/views/articles/_actions.html.erb
  app/views/articles/_reaction_button.html.erb
  app/views/articles/_single_story.html.erb
  app/views/articles/index.html.erb
  app/views/layouts/_main_nav.html.erb
  cypress/integration/loggedOutFlows/showLoginModal.spec.js
Labels: PR: partially-approved

#13273 `crayons-notice` accessibility improvements
  app/assets/javascripts/initializers/initializeCommentsPage.js.erb
  app/views/admin/badge_achievements/award.html.erb
  app/views/admin/broadcasts/index.html.erb
  app/views/admin/configs/_apple_auth_provider_settings.html.erb
  app/views/admin/configs/show.html.erb
  app/views/admin/feedback_messages/_feedback_message.html.erb
  app/views/admin/pages/index.html.erb
  app/views/admin/tags/edit.html.erb
  app/views/admin/users/_notes.html.erb
  app/views/admin/users/gdpr_delete_requests/index.html.erb
  app/views/articles/_actions.html.erb
  app/views/articles/_search.html.erb
  app/views/articles/show.html.erb
  app/views/articles/tag_index.html.erb
  app/views/comments/_form.html.erb
  app/views/credits/new.html.erb
  app/views/dashboards/following_tags.html.erb
  app/views/devise/invitations/edit.html.erb
  app/views/devise/registrations/new.html.erb
  app/views/devise/shared/_error_messages.html.erb
  app/views/events/index.html.erb
  app/views/feedback_messages/_form.html.erb
  app/views/liquids/_user_subscription.html.erb
  app/views/listings/_form.html.erb
  app/views/listings/_form_errors.html.erb
  app/views/listings/edit.html.erb
  app/views/pages/_editor_frontmatter_help.html.erb
  app/views/shared/authentication/_email_registration_form.html.erb
  app/views/shared/authentication/_initial_account_wizard.html.erb
  app/views/users/_account.html.erb
  app/views/users/_billing.html.erb
  app/views/users/_errors.html.erb
  app/views/users/edit.html.erb
Labels: PR: partially-approved

#13392 [15 min fix] Remove extra key handler on reading list archive button
  app/javascript/readingList/components/ItemListItemArchiveButton.jsx
  app/javascript/readingList/components/__tests__/ItemListItemArchiveButton.test.jsx
Labels: PR: partially-approved

#13380 [15 min fix] Fixed flaky E2E test for comments
  cypress/integration/articleFlows/commentOnArticle.spec.js
Labels: PR: partially-approved, area: comments, area: tests, merge by any core

#13395 [15 min fix] Intercept listings search call in listings cypress test
  cypress/fixtures/search/listings.json
  cypress/integration/listingFlows/viewListing.spec.js
Labels: PR: reviewed-approved

#13398 skip flakey autocomplete test
  cypress/integration/articleFlows/commentOnArticle.spec.js
Labels: PR: reviewed-approved

#13345 [Small fix] Makes stats page responsive
  app/assets/stylesheets/dashboard.scss
  app/javascript/analytics/dashboard.js
  app/views/articles/stats.html.erb
  app/views/dashboards/analytics.erb
  app/views/shared/_stats.html.erb
Labels: PR: unreviewed

#13397 [15 min fix] Used the all browser supported document.body.
  app/assets/javascripts/base.js.erb
Labels: PR: partially-approved, merge by any core, tech: javascript

#13409 Disable reply with autocomplete test due to flakiness
  cypress/integration/articleFlows/commentOnArticle.spec.js
Labels: PR: partially-approved, merge by any core

#13114 RFC#50-P5 Prepares the admin restructure to be tested
  app/controllers/admin/badges_controller.rb
  app/controllers/admin/broadcasts_controller.rb
  app/controllers/admin/display_ads_controller.rb
  app/controllers/admin/events_controller.rb
  app/controllers/admin/html_variants_controller.rb
  app/controllers/admin/listing_categories_controller.rb
  app/controllers/admin/navigation_links_controller.rb
  app/controllers/admin/response_templates_controller.rb
  app/controllers/admin/sponsorships_controller.rb
  app/controllers/admin/tools_controller.rb
  app/helpers/admin_helper.rb
  app/views/admin/badge_achievements/index.html.erb
  app/views/admin/broadcasts/show.html.erb
  app/views/admin/chat_channels/index.html.erb
  app/views/admin/display_ads/index.html.erb
  app/views/admin/listing_categories/index.html.erb
  app/views/admin/overview/index.html.erb
  app/views/admin/response_templates/new.html.erb
  app/views/admin/secrets/index.html.erb
  app/views/admin/shared/_nested_sidebar.html.erb
  app/views/admin/shared/_tabbed_navbar.html.erb
  app/views/admin/sponsorships/edit.html.erb
  app/views/admin/tags/index.html.erb
  config/routes.rb
  config/routes/admin.rb
  config/routes/current_admin.rb
  spec/requests/admin/nested_sidebar_spec.rb
Labels: PR: unreviewed

#13417 When there is no db connection, answer false as though there were no table
  app/lib/database.rb
Labels: PR: partially-approved

#13413 Add x86_64-darwin-20 to PLATFORMS in Gemfile.lock
  Gemfile.lock
Labels: PR: partially-approved

#13410 [15 min fix] Make sure columns in the schema file stay alphabetized after bin/setup
  lib/tasks/app_initializer.rake
Labels: PR: reviewed-approved

#13424 [15 min fix] fix accessible name of listings on dashboard
  app/views/dashboards/_actions.html.erb
Labels: PR: partially-approved

#13426 Rename table_exists? to table_available? to indicate behavior
  app/lib/database.rb
  app/models/profile.rb
  config/routes.rb
Labels: PR: partially-approved

#12325 Switch references to Forem master branch to main
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/codeql-analysis.yml
  .github/workflows/issue.yml
  .travis.yml
  README.md
  config/webpack/environment.js
  docs/admin/admin-user-interface.md
  docs/api_v0.yml
  docs/backend/configuration.md
  docs/backend/data-update-scripts.md
  docs/backend/fastly.md
  docs/backend/roles.md
  docs/contributing/docs.md
  docs/contributing/forem.md
  docs/design/branding.md
  docs/frontend/instant-click.md
  docs/frontend/styles.md
  docs/frontend/webpacker.md
  docs/getting-started/syncing.md
  docs/getting-started/workflow.md
  docs/licensing.md
  docs/maintainers/deploying.md
  docs/technical-overview/ab_testing.md
  scripts/clean_fork.sh
  scripts/sync_fork.sh
Labels: PR: partially-approved, blocked

#13418 [15 min fix] Enforce an upper limit for articles.body_markdown
  app/models/article.rb
  app/validators/bytesize_validator.rb
  spec/models/article_spec.rb
Labels: PR: partially-approved, include in changelog, merge by any core

#13238 Split Settings::Campaign from SiteConfig
  app/controllers/admin/settings/campaigns_controller.rb
  app/controllers/sidebars_controller.rb
  app/controllers/stories_controller.rb
  app/lib/constants/settings/campaign.rb
  app/lib/constants/site_config.rb
  app/models/campaign.rb
  app/models/settings/campaign.rb
  app/models/site_config.rb
  app/services/campaigns/settings_upsert.rb
  app/views/admin/configs/show.html.erb
  config/routes.rb
  cypress/integration/adminFlows/config/campaignSection.spec.js
  db/migrate/20210405032815_create_settings_campaigns.rb
  db/schema.rb
  lib/data_update_scripts/20210405034117_move_campaign_settings.rb
  spec/models/site_config_spec.rb
  spec/requests/admin/configs_spec.rb
  spec/requests/stories_index_spec.rb
Labels: PR: reviewed-approved

#13442 [15 min fix] Dependabot: change npm schedule to weekly
  .github/dependabot.yml
Labels: PR: partially-approved

#13437 [Bug fix] Re-add Email digest frequency to admin config
  app/views/admin/configs/show.html.erb
  cypress/integration/adminFlows/config/emailDigestFrequencySection.js
Labels: PR: partially-approved

#13432 [15 min fix] Document data update scripts best practices
  docs/backend/data-update-scripts.md
Labels: PR: partially-approved

#13427 [15min fix] Return Device ID upon registration
  app/controllers/devices_controller.rb
  spec/requests/devices_spec.rb
Labels: PR: partially-approved

#13118 Push Notification stats instrumentation
  app/models/device.rb
  app/services/notifications/new_comment/send.rb
  config/initializers/rpush.rb
Labels: PR: unreviewed

#13445 Add missing class back in for signed out featured post on feed
  app/views/articles/_single_story.html.erb
  spec/requests/stories_index_spec.rb
Labels: PR: unreviewed

#13388 Asynchronous organization delete
  app/controllers/organizations_controller.rb
  app/mailers/notify_mailer.rb
  app/models/organization.rb
  app/services/organizations/delete.rb
  app/views/mailers/notify_mailer/organization_deleted_email.html.erb
  app/views/mailers/notify_mailer/organization_deleted_email.text.erb
  app/workers/organizations/delete_worker.rb
  spec/mailers/notify_mailer_spec.rb
  spec/requests/user/user_organization_spec.rb
  spec/services/organizations/delete_spec.rb
  spec/workers/organizations/delete_worker_spec.rb
Labels: PR: partially-approved

#13446 Add reading_time to articles api responses
  app/controllers/api/v0/articles_controller.rb
  app/views/api/v0/articles/_article.json.jbuilder
  docs/api_v0.yml
  spec/requests/api/v0/articles_spec.rb
Labels: PR: partially-approved

#13381 Create settings model for rate limits
  app/controllers/admin/settings/rate_limits_controller.rb
  app/decorators/user_decorator.rb
  app/helpers/rate_limit_checker_helper.rb
  app/lib/constants/settings/rate_limit.rb
  app/lib/constants/site_config.rb
  app/models/settings/rate_limit.rb
  app/models/site_config.rb
  app/services/rate_limit_checker.rb
  app/services/rate_limits/settings_upsert.rb
  app/views/admin/configs/show.html.erb
  app/views/dashboards/following_tags.html.erb
  app/views/shared/authentication/_email_registration_form.html.erb
  config/routes.rb
  cypress/integration/adminFlows/config/rateLimitSection.js
  cypress/integration/loggedOutFlows/showLoginModal.spec.js
  db/migrate/20210414033457_create_settings_rate_limits.rb
  db/schema.rb
  docs/backend/configuration.md
  lib/data_update_scripts/20210114174504_update_user_update_rate_limit_default.rb
  lib/data_update_scripts/20210414060839_move_rate_limit_settings.rb
  spec/helpers/rate_limit_checker_helper_spec.rb
  spec/lib/data_update_scripts/move_rate_limit_settings_spec.rb
  spec/lib/data_update_scripts/update_user_update_rate_limit_default_spec.rb
  spec/requests/admin/configs_spec.rb
  spec/requests/follows_create_spec.rb
  spec/services/rate_limit_checker_spec.rb
Labels: PR: unreviewed, merge by any core

#13454 Revert "Bump dogstatsd-ruby from 4.8.3 to 5.0.1"
  Gemfile
  Gemfile.lock
  vendor/cache/dogstatsd-ruby-4.8.3.gem
  vendor/cache/dogstatsd-ruby-5.0.1.gem
Labels: PR: partially-approved

#13401 [Search 2.0] Comments on search page
  app/controllers/search_controller.rb
  app/models/comment.rb
  app/serializers/search/postgres_comment_serializer.rb
  app/services/search/postgres/comment.rb
  spec/requests/search_spec.rb
  spec/services/search/postgres/comment_spec.rb
Labels: PR: reviewed-approved

#13339 [Search 2.0] Homepage query
  app/controllers/search_controller.rb
  app/lib/constants/tags.rb
  app/queries/homepage/articles_query.rb
  app/serializers/homepage/article_serializer.rb
  app/services/flare_tag.rb
  app/services/homepage/fetch_articles.rb
  app/services/homepage/fetch_tag_flares.rb
  app/services/search/postgres/reading_list.rb
  spec/queries/homepage/articles_query_spec.rb
  spec/requests/search_spec.rb
  spec/services/homepage/fetch_articles_spec.rb
  spec/services/homepage/fetch_tag_flares_spec.rb
Labels: PR: unreviewed

#13461 [15 minute fix] Added a timeout before continuing if a dev does not respond to rebuild the E2E DB
  bin/e2e
Labels: PR: partially-approved, area: developer experience, area: tests, merge by any core

#13455 Bust cache after commit, rather than after save
  app/models/user.rb
Labels: PR: partially-approved

#13462 [Search 2.0] Allow mention autocomplete to search users names
  app/models/user.rb
  app/services/search/postgres/username.rb
  db/migrate/20210420135208_add_name_tsvector_index_to_users.rb
  db/schema.rb
  spec/requests/search_spec.rb
  spec/services/search/postgres/username_spec.rb
Labels: PR: partially-approved, include in changelog

#13347 [15-Minute Fix] Refactor code smells
  app/controllers/admin/pages_controller.rb
  app/controllers/concerns/caching_headers.rb
  app/controllers/concerns/development_dependency_checks.rb
  app/controllers/concerns/edge_cache_safety_check.rb
  app/controllers/concerns/image_uploads.rb
  app/controllers/concerns/listings_toolkit.rb
  app/controllers/concerns/session_current_user.rb
  app/controllers/concerns/settings_params.rb
  app/controllers/concerns/valid_request.rb
  app/controllers/concerns/verify_setup_completed.rb
  app/controllers/pages_controller.rb
Labels: PR: unreviewed

#13304 Push Notification multi app support
  app/controllers/admin/consumer_apps_controller.rb
  app/controllers/devices_controller.rb
  app/models/consumer_app.rb
  app/models/device.rb
  app/policies/consumer_app_policy.rb
  app/queries/consumer_apps/find_or_create_all_query.rb
  app/queries/consumer_apps/find_or_create_by_query.rb
  app/queries/consumer_apps/rpush_app_query.rb
  app/views/admin/consumer_apps/_form.html.erb
  app/views/admin/consumer_apps/edit.html.erb
  app/views/admin/consumer_apps/index.html.erb
  app/views/admin/consumer_apps/new.html.erb
  config/routes.rb
  db/migrate/20210411213624_create_consumer_apps.rb
  db/migrate/20210411213625_change_devices_app_bundle_allow_null.rb
  db/migrate/20210411213626_add_devices_reference_and_update_composite_index.rb
  db/migrate/20210411220125_add_devices_foreign_key_to_app_integrations.rb
  db/migrate/20210411221134_validate_add_devices_foreign_key_to_app_integrations.rb
  db/schema.rb
  spec/factories/consumer_apps.rb
  spec/factories/devices.rb
  spec/models/consumer_app_spec.rb
  spec/queries/consumer_apps/find_or_create_all_query_spec.rb
  spec/queries/consumer_apps/find_or_create_by_query_spec.rb
  spec/queries/consumer_apps/rpush_app_query_spec.rb
  spec/requests/admin/consumer_apps_spec.rb
  spec/requests/devices_spec.rb
Labels: PR: unreviewed

#13465 When busting user cache, also clear the api response
  app/services/edge_cache/bust_user.rb
  spec/services/edge_cache/bust_user_spec.rb
Labels: PR: partially-approved

#13456 re-enable skipped tests
  spec/system/comments/user_fills_out_comment_spec.rb
Labels: PR: reviewed-approved

#13469 Add tsvector index to comments.body_markdown
  db/migrate/20210421190438_add_body_markdown_tsvector_index_to_comments.rb
  db/schema.rb
Labels: PR: partially-approved

#13412 re-enable a cypress test, removing use of aliases
  cypress/integration/articleFlows/commentOnArticle.spec.js
Labels: PR: partially-approved, merge by any core

#13474 Use a manual query to find users by their names and usernames
  app/models/user.rb
  spec/services/search/postgres/username_spec.rb
Labels: PR: unreviewed, merge by any core

#13477 Lint script does not need to be a pre test script.
  .travis.yml
  package.json
Labels: PR: partially-approved, merge by any core

#13476 Add indexes to comments
  db/migrate/20210422171642_add_indexes_to_comments.rb
  db/schema.rb
Labels: PR: partially-approved, merge by any core

#13478 Revert "re-enable skipped tests"
  spec/system/comments/user_fills_out_comment_spec.rb
Labels: PR: partially-approved

#13402 [15 minute fix] Fixed issue with member navigation button only working after full page loads but not InstantClick page transitions
  app/javascript/packs/base.jsx
  app/javascript/topNavigation/__tests__/utilities.test.js
  app/javascript/topNavigation/utilities.js
  app/views/layouts/_top_bar.html.erb
Labels: PR: partially-approved, merge by any core, mobile, tech: javascript

#13482 [15 min fix] Removed title attributes from SVGs that are purely decorative
  app/views/comments/_form.html.erb
Labels: PR: partially-approved, merge by any core, type: accessibility

#13425 [15 min fix] Fix following tags input a11y errors
  app/assets/javascripts/initializers/initScrolling.js
  app/views/dashboards/following_tags.html.erb
  spec/system/dashboards/user_scrolls_down_dashboard_follows_spec.rb
Labels: PR: partially-approved

#13467 Cleanup articles cache busting
  app/services/edge_cache/bust_article.rb
Labels: PR: reviewed-approved

#13486 Add skip link to search results page
  app/views/articles/search.html.erb
Labels: PR: partially-approved, merge by any core

#13485 Add skip link to tag page
  app/assets/javascripts/utilities/slideSidebar.js
  app/views/articles/tag_index.html.erb
  app/views/stories/_stories_list_script.html.erb
  spec/system/articles/user_visits_articles_by_tag_spec.rb
Labels: PR: partially-approved, merge by any core

#13483 Add skip link functionality to custom pages
  app/views/pages/show.html.erb
Labels: PR: partially-approved, merge by any core

#13487 Add skip link to stats and analytics pages
  app/views/articles/stats.html.erb
  app/views/dashboards/analytics.erb
Labels: PR: partially-approved, merge by any core

#13481 Modify codepen_tag to parse public and private Pen urls
  app/liquid_tags/codepen_tag.rb
  spec/liquid_tags/codepen_tag_spec.rb
Labels: PR: partially-approved

#13489 Performance improvements to comments search
  app/services/search/postgres/comment.rb
  db/migrate/20210423162805_remove_indexes_from_comments.rb
  db/migrate/20210423162847_add_partial_indexes_from_comments.rb
  db/schema.rb
Labels: PR: partially-approved

#13488 add skip link to settings page
  app/views/users/edit.html.erb
Labels: PR: partially-approved, merge by any core

#13366 Fix bug when responding to listings
  app/javascript/listings/listings.jsx
  cypress/fixtures/search/listings.json
  cypress/integration/listingFlows/viewListing.spec.js
Labels: PR: partially-approved

#13490 Preload users instead of querying separately when searching for comments
  app/serializers/search/postgres_comment_serializer.rb
  app/services/search/postgres/comment.rb
Labels: PR: partially-approved, merge by any core

#13190 Runtime Banner for Mobile Deep Linking
  app/assets/images/logo-forem-app.svg
  app/assets/javascripts/initializePage.js
  app/assets/javascripts/initializers/initializeRuntimeBanner.js
  app/assets/stylesheets/runtime-banner.scss
  app/controllers/deep_links_controller.rb
  app/lib/url.rb
  app/views/deep_links/mobile.html.erb
  app/views/layouts/application.html.erb
  config/routes.rb
  cypress/integration/loggedOutFlows/runtimeBannerDeepLinking.spec.js
  public/apple-app-site-association
  spec/lib/url_spec.rb
  spec/requests/universal_links_spec.rb
Labels: PR: partially-approved

#13492 Homepage query should not fail for nil article's cached tag list
  app/services/homepage/fetch_tag_flares.rb
  spec/services/homepage/fetch_tag_flares_spec.rb
Labels: PR: partially-approved

#13453 [Search 2.0] Users
  app/controllers/search_controller.rb
  app/models/user.rb
  app/models/user_role.rb
  app/serializers/search/postgres_user_serializer.rb
  app/services/search/postgres/user.rb
  spec/models/user_role_spec.rb
  spec/requests/search_spec.rb
  spec/services/search/postgres/user_spec.rb
  spec/services/search/postgres/username_spec.rb
Labels: PR: unreviewed

#13479 Refactor:Remove jobs_url and Display Banner
  app/controllers/search_controller.rb
  app/lib/constants/site_config.rb
  app/models/site_config.rb
  app/views/admin/configs/show.html.erb
  app/views/articles/_search.html.erb
  spec/requests/admin/configs_spec.rb
  spec/requests/search_spec.rb
  spec/system/search/display_jobs_banner_spec.rb
Labels: PR: partially-approved, include in changelog

#13480 15 minute fix: Remove `/partnerships` page ✂️
  app/assets/stylesheets/partnerships.scss
  app/controllers/partnerships_controller.rb
  app/views/credits/index.html.erb
  app/views/partnerships/_bronze_sponsor_copy.html.erb
  app/views/partnerships/_devrel_consult_copy.html.erb
  app/views/partnerships/_flashes.html.erb
  app/views/partnerships/_form.html.erb
  app/views/partnerships/_gold_sponsor_copy.html.erb
  app/views/partnerships/_media_sponsor_copy.html.erb
  app/views/partnerships/_metal_level_form.html.erb
  app/views/partnerships/_not_enough_credits.html.erb
  app/views/partnerships/_silver_sponsor_copy.html.erb
  app/views/partnerships/_tag_form.html.erb
  app/views/partnerships/_tag_sponsor_copy.html.erb
  app/views/partnerships/index.html.erb
  app/views/partnerships/show.html.erb
  config/routes.rb
  spec/requests/partnerships_spec.rb
Labels: PR: partially-approved

#13451 Add Settings::Mascot
  app/controllers/admin/settings/mascots_controller.rb
  app/controllers/chat_channels_controller.rb
  app/controllers/comments_controller.rb
  app/controllers/search_controller.rb
  app/lib/constants/settings/mascot.rb
  app/lib/constants/site_config.rb
  app/models/article.rb
  app/models/comment.rb
  app/models/reaction.rb
  app/models/settings/mascot.rb
  app/models/user.rb
  app/services/authentication/providers/apple.rb
  app/services/users/create_mascot_account.rb
  app/views/admin/configs/show.html.erb
  app/views/admin/feedback_messages/_abuse_reports.html.erb
  app/views/comments/_comment_avatar.html.erb
  app/views/comments/deleted_commentable_comment.html.erb
  app/views/dashboards/show.html.erb
  app/views/layouts/_footer.html.erb
  config/routes.rb
  cypress/integration/adminFlows/config/mascotSection.js
  db/migrate/20210420050243_create_settings_mascots.rb
  db/schema.rb
  lib/data_update_scripts/20210420050256_move_mascot_settings.rb
  spec/lib/data_update_scripts/move_mascot_settings_spec.rb
  spec/models/article_spec.rb
  spec/models/comment_spec.rb
  spec/models/reaction_spec.rb
  spec/models/user_spec.rb
  spec/requests/admin/configs_spec.rb
  spec/requests/comments_create_spec.rb
  spec/requests/registrations_spec.rb
  spec/services/search/query_builders/chat_channel_membership_spec.rb
  spec/services/users/create_mascot_account_spec.rb
  spec/views/dashboards/show.html.erb_spec.rb
Labels: PR: partially-approved

#13473 RFC 50: fix some more hardcoded paths
  app/controllers/admin/chat_channels_controller.rb
  app/controllers/admin/feedback_messages_controller.rb
  app/controllers/admin/users_controller.rb
  app/controllers/stories_controller.rb
  app/controllers/tags_controller.rb
  app/javascript/admin/__tests__/controllers/data_update_script_controller.test.js
  app/javascript/admin/controllers/data_update_script_controller.js
  app/views/admin/data_update_scripts/index.html.erb
  app/views/admin/feedback_messages/_feedback_message.html.erb
  app/views/admin/feedback_messages/_latest_articles.html.erb
  app/views/admin/feedback_messages/_potential_spam_users.html.erb
  app/views/admin/overview/index.html.erb
  app/views/admin/podcasts/index.html.erb
  app/views/articles/tags/_sidebar.html.erb
  app/views/layouts/admin.html.erb
  app/views/moderations/mod.html.erb
  app/views/pages/_placeholder.html.erb
  app/views/shared/authentication/_initial_account_wizard.html.erb
  app/views/tags/edit.html.erb
Labels: PR: unreviewed

#13508 Settings: Fix textarea out of bounds on resize
  app/assets/stylesheets/components/forms.scss
Labels: PR: partially-approved

#13491 Cleanup markup of editor guide
  app/views/pages/_editor_guide_h3.html.erb
  app/views/pages/_editor_guide_text.html.erb
  app/views/pages/_v1_editor_guide_preamble.html.erb
Labels: PR: unreviewed

#13514 [15-min-fix] Set husky explicilty to version 4.x
  .github/dependabot.yml
Labels: PR: partially-approved, merge by any core

#13515 aria-hidden accessibility tweak
  app/views/admin/shared/_nested_sidebar.html.erb
Labels: PR: partially-approved

#13510 [Search 2.0] Add query filters for profile, organization and tag index pages
  app/controllers/search_controller.rb
  app/queries/homepage/articles_query.rb
  app/services/homepage/fetch_articles.rb
  spec/queries/homepage/articles_query_spec.rb
  spec/requests/search_spec.rb
Labels: PR: partially-approved, merge by any core

#13503 Add skip link to connect and manage post
  app/views/articles/manage.html.erb
  app/views/chat_channels/index.html.erb
Labels: PR: reviewed-approved

#13506 Reintroduce autocomplete Cypress test, refactor tests in same suite
  app/javascript/crayons/MentionAutocompleteTextArea/MentionAutocompleteTextArea.jsx
  app/javascript/crayons/MentionAutocompleteTextArea/__tests__/__snapshots__/MentionAutocompleteTextArea.test.jsx.snap
  cypress/integration/articleFlows/commentOnArticle.spec.js
Labels: PR: reviewed-approved

#13526 Enable redis cache store in development
  config/environments/development.rb
Labels: PR: reviewed-approved

#13484 Remove unused attributes from markdown parser
  app/sanitizers/rendered_markdown_scrubber.rb
  app/services/markdown_processor/parser.rb
  spec/services/markdown_processor/parser_spec.rb
Labels: PR: partially-approved, area: publishing experience

#13537 [Hotfix] Serialize tag flares correctly in Homepage::ArticleSerializer
  app/serializers/homepage/article_serializer.rb
  spec/services/homepage/fetch_articles_spec.rb
Labels: PR: partially-approved

#13541 Optimize `Articles::GetUserStickies`
  app/services/articles/get_user_stickies.rb
Labels: PR: partially-approved

#13540 [Search 2.0] Articles
  app/controllers/search_controller.rb
  app/models/article.rb
  app/services/search/postgres/article.rb
  app/services/search/postgres/reading_list.rb
  spec/requests/search_spec.rb
  spec/services/search/postgres/article_spec.rb
Labels: PR: partially-approved

#13475 [Search 2.0] Podcasts on search page
  app/controllers/search_controller.rb
  app/models/podcast_episode.rb
  app/serializers/search/postgres_podcast_episode_serializer.rb
  app/services/search/postgres/podcast_episode.rb
  db/migrate/20210426151459_add_published_partial_index_to_podcasts.rb
  db/migrate/20210426152816_add_tsvector_indexes_to_podcast_episodes.rb
  db/migrate/20210426165234_add_partial_index_on_reachable_to_podcast_episodes.rb
  db/schema.rb
  spec/requests/search_spec.rb
  spec/services/search/postgres/podcast_episode_spec.rb
Labels: PR: partially-approved

#13544 fix flaky Homepage::ArticleQuery spec
  spec/queries/homepage/articles_query_spec.rb
Labels: PR: reviewed-approved

#13548 Optimize `Articles::Suggest` query
  app/services/articles/suggest.rb
Labels: PR: partially-approved
