Repository forem/forem, pull requests merged in 2021-06, with the labels that each got.

#13877 [15 min fix] Show the sidebar on all logged in feed views
  app/javascript/packs/homePage.jsx
  cypress/integration/homeFeedFlows/feedNavigation.spec.js
  spec/support/seeds/seeds_e2e.rb
Labels: PR: partially-approved

#13880 Call `config.action_mailer.perform_caching = false` only once in development.rb
  config/environments/development.rb
Labels: PR: partially-approved

#13891 Remove duplicate jquery import, remove jquery-rails and use @rails/ujs
  Gemfile
  Gemfile.lock
  app/assets/javascripts/application.js
  app/assets/javascripts/internal.js
  app/controllers/listings_controller.rb
  app/javascript/packs/admin.js
  app/views/admin/tags/_form.html.erb
  app/views/admin/tags/edit.html.erb
  app/views/layouts/admin.html.erb
  app/views/listings/delete_confirm.html.erb
  cypress/integration/adminFlows/badges/badgeAchievements.spec.js
  cypress/integration/listingFlows/deleteListing.spec.js
  package.json
  spec/support/seeds/seeds_e2e.rb
  vendor/cache/jquery-rails-4.4.0.gem
  yarn.lock
Labels: PR: unreviewed

#13887 Settings: Correctly display profile field static values
  app/views/users/_profile.html.erb
  cypress/integration/profileFlows/userUpdateSettingsProfile.spec.js
  spec/factories/profile_fields.rb
Labels: PR: partially-approved

#13892 Remove unused cached_tagged_by_approval_with Article scope ✂️ ✂️ ✂️
  app/models/article.rb
Labels: PR: reviewed-approved

#13871 Add margin to feed cards on mobile
  app/assets/stylesheets/components/stories.scss
Labels: PR: partially-approved, area: design

#13896 Revert "Bump jest-watch-typeahead from 0.6.3 to 0.6.4 (#13888)"
  package.json
  yarn.lock
Labels: PR: partially-approved, merge by any core

#13898 [15 min fix] Reduce flake in sidebar navigation spec
  cypress/integration/navigationFlows/homePageLeftSidebar.spec.js
Labels: PR: partially-approved, merge by any core

#13899 [15 min fix] fix flake in delete listing test
  cypress/integration/listingFlows/deleteListing.spec.js
Labels: PR: partially-approved, merge by any core

#13897 [15 min fix] Remove flake in "follow user" spec
  app/assets/javascripts/initializers/initializeAllFollowButts.js
  cypress/integration/profileFlows/followUser.spec.js
Labels: PR: partially-approved, merge by any core

#13900 [Tiny fix] Fix border radius issue on home feed
  app/assets/stylesheets/components/stories.scss
Labels: PR: partially-approved, merge by any core

#13902 [Tiny fix] home page mobile select bug
  app/views/articles/index.html.erb
Labels: PR: reviewed-approved, merge by any core

#13631 Clear asset and vendor caches on deploy
  lib/tasks/assets.rake
Labels: PR: reviewed-approved

#13721 add user friendly error message when a comment is made on a deleted post
  app/controllers/comments_controller.rb
  app/models/comment.rb
  spec/models/comment_spec.rb
Labels: PR: unreviewed

#13868 Optimise dropdowns for accessibility - Post comments and share
  app/assets/javascripts/initializePage.js
  app/assets/javascripts/initializers/initializeCommentDropdown.js
  app/assets/javascripts/initializers/initializeCommentsPage.js.erb
  app/assets/javascripts/utilities/buildCommentHTML.js.erb
  app/javascript/packs/articlePage.jsx
  app/javascript/packs/commentDropdowns.js
  app/javascript/utilities/dropdownUtils.js
  app/views/articles/_actions.html.erb
  app/views/articles/show.html.erb
  app/views/comments/_comment_header.html.erb
  app/views/comments/index.html.erb
  app/views/podcast_episodes/show.html.erb
  cypress/integration/articleFlows/commentOnArticle.spec.js
  cypress/integration/articleFlows/postSidebarActions.spec.js
Labels: PR: partially-approved

#13745 Advise users about potential accessibility failings in their posts - RFC #58
  app/assets/javascripts/markdown-it.min.js
  app/assets/javascripts/markdownlint-browser.min.js
  app/javascript/article-form/articleForm.jsx
  app/javascript/article-form/components/AccessibilitySuggestions.jsx
  app/javascript/article-form/components/Preview.jsx
  app/javascript/article-form/components/__tests__/AccessibilitySuggestions.test.jsx
  app/javascript/utilities/markdown/markdownLintCustomRules.js
  cypress/integration/publishingFlows/previewPost.spec.js
Labels: PR: partially-approved

#13906 Add :detect_animated_images feature flag to guard animated images detection
  app/models/article.rb
  spec/models/article_spec.rb
Labels: PR: partially-approved, merge by any core

#13872 change Dev_favicon to Forem_favicon
  public/favicon.ico
Labels: PR: reviewed-approved

#13807 Pin posts to feed
  app/assets/javascripts/initializers/initializeBaseUserData.js
  app/assets/stylesheets/admin.scss
  app/assets/stylesheets/components/stories.scss
  app/controllers/admin/articles_controller.rb
  app/controllers/stories/feeds_controller.rb
  app/controllers/stories/pinned_articles_controller.rb
  app/controllers/stories_controller.rb
  app/decorators/article_decorator.rb
  app/javascript/admin/controllers/article_controller.js
  app/javascript/admin/controllers/article_pinned_modal_controller.js
  app/javascript/admin/controllers/modal_controller.js
  app/javascript/articles/Article.jsx
  app/javascript/articles/Feed.jsx
  app/javascript/packs/articleForm.jsx
  app/javascript/packs/articlePage.jsx
  app/javascript/packs/homePageFeed.jsx
  app/models/pinned_article.rb
  app/models/settings/general.rb
  app/models/user.rb
  app/policies/pinned_article_policy.rb
  app/services/rate_limit_checker.rb
  app/validators/existing_published_article_id_validator.rb
  app/views/admin/articles/_individual_article.html.erb
  app/views/admin/articles/_pinned_article_modal.html.erb
  app/views/admin/articles/index.html.erb
  app/views/admin/articles/show.html.erb
  app/views/articles/_v2_form.html.erb
  app/views/articles/delete_confirm.html.erb
  app/views/articles/show.html.erb
  app/views/stories/feeds/show.json.jbuilder
  config/routes.rb
  config/routes/admin.rb
  cypress/integration/adminFlows/articles/pinArticle.spec.js
  cypress/integration/adminFlows/articles/upinArticle.spec.js
  cypress/integration/articleFlows/pinArticle.spec.js
  spec/decorators/article_decorator_spec.rb
  spec/models/pinned_article_spec.rb
  spec/models/settings/general_spec.rb
  spec/policies/pinned_article_policy_spec.rb
  spec/requests/admin/articles_spec.rb
  spec/requests/stories/feeds_spec.rb
  spec/requests/stories/pinned_articles_spec.rb
  spec/services/rate_limit_checker_spec.rb
Labels: PR: unreviewed, include in changelog

#13909 Optimise dropdowns for accessibility: Dashboard and Manage pages
  app/assets/javascripts/initializePage.js
  app/assets/javascripts/initializers/initializeEllipsisMenu.js
  app/assets/stylesheets/components/buttons.scss
  app/javascript/packs/dashboardDropdowns.js
  app/javascript/utilities/dropdownUtils.js
  app/views/dashboards/_dashboard_article.html.erb
  app/views/dashboards/_dashboard_article_row.html.erb
  app/views/dashboards/show.html.erb
  cypress/integration/dashboardFlows/managePost.spec.js
  cypress/integration/dashboardFlows/postsDashboard.spec.js
Labels: PR: partially-approved

#13913 Fix flakey test in articleFlows/pinArticle
  cypress/integration/articleFlows/pinArticle.spec.js
Labels: PR: partially-approved

#13919 [15-min-fix] Add quick fix to resolve input events not bubbling up
  app/assets/stylesheets/components/buttons.scss
Labels: PR: reviewed-approved

#13851 Add Admin:Settings controllers
  app/controllers/admin/configs_controller.rb
  app/controllers/admin/settings/authentications_controller.rb
  app/controllers/admin/settings/base_controller.rb
  app/controllers/admin/settings/campaigns_controller.rb
  app/controllers/admin/settings/communities_controller.rb
  app/controllers/admin/settings/general_settings_controller.rb
  app/controllers/admin/settings/mandatory_settings_controller.rb
  app/controllers/admin/settings/rate_limits_controller.rb
  app/controllers/admin/settings/user_experiences_controller.rb
  app/controllers/admin/settings_controller.rb
  app/controllers/api/v0/admin/configs_controller.rb
  app/controllers/concerns/settings_params.rb
  app/services/authentication/settings_upsert.rb
  app/services/campaigns/settings_upsert.rb
  app/services/rate_limits/settings_upsert.rb
  app/services/settings/authentication/upsert.rb
  app/services/settings/general/upsert.rb
  app/services/settings/upsert.rb
  app/views/admin/settings/_apple_auth_provider_settings.html.erb
  app/views/admin/settings/_auth_provider_settings.html.erb
  app/views/admin/settings/_form_submission.html.erb
  app/views/admin/settings/show.html.erb
  config/routes/admin.rb
  spec/requests/admin/configs_spec.rb
Labels: PR: unreviewed

#13934 API: Remove Admin Config endpoint ✂️ ✂️ ✂️ ✂️
  app/controllers/api/v0/admin/configs_controller.rb
  config/routes.rb
  docs/api_v0.yml
  spec/requests/api/v0/admin/configs_spec.rb
Labels: PR: unreviewed

#13903 Refactor RegistrationsController
  app/controllers/registrations_controller.rb
  app/policies/registration_policy.rb
Labels: PR: unreviewed

#13942 [15-min-fix] Deleted unused data update scripts
  lib/data_update_scripts/20201001173841_add_navigation_links.rb
  lib/data_update_scripts/20201218080343_update_default_email_addresses.rb
  lib/data_update_scripts/20210305222641_resave_users_for_imgproxy_update.rb
  lib/data_update_scripts/20210322092753_fill_badges_credits_awarded.rb
  spec/lib/data_update_scripts/fill_badges_credits_awarded_spec.rb
  spec/lib/data_update_scripts/update_default_email_addresses_spec.rb
Labels: PR: reviewed-approved

#13918 Search results: prioritize articles titles
  app/models/article.rb
  app/services/search/article.rb
  db/migrate/20210609103939_create_trigger_articles_insert_update1.rb
  db/schema.rb
  spec/models/hair_trigger_spec.rb
  spec/services/search/article_spec.rb
Labels: PR: unreviewed, include in changelog, merge by any core

#13914 Takeover code for `publishing_from_rss` section in Settings
  app/controllers/users/settings_controller.rb
  app/models/user.rb
  app/services/feeds/assemble_article_markdown.rb
  app/services/feeds/import.rb
  app/views/users/_publishing_from_rss.html.erb
  db/schema.rb
  spec/services/feeds/import_spec.rb
Labels: PR: partially-approved

#13944 [15-minute fix] Remove deprecated route
  config/routes.rb
Labels: PR: partially-approved

#13945 Remove provider created_at columns
  app/models/user.rb
  db/migrate/20210609042710_remove_provider_created_at_columns_from_user.rb
  db/schema.rb
Labels: PR: unreviewed

#13949 Change header name to double quoted string literal
  spec/requests/stories/pinned_articles_spec.rb
Labels: PR: reviewed-approved

#13912 Get a11y lint script paths from rails helper
  app/javascript/article-form/articleForm.jsx
  app/views/articles/edit.html.erb
  app/views/articles/new.html.erb
  config/initializers/assets.rb
  jest.config.js
  vendor/assets/javascripts/markdown-it.min.js
  vendor/assets/javascripts/markdownlint-browser.min.js
Labels: PR: partially-approved

#13905 Create DiscussionLocks
  app/controllers/articles_controller.rb
  app/controllers/discussion_locks_controller.rb
  app/controllers/profile_pins_controller.rb
  app/controllers/stories_controller.rb
  app/models/article.rb
  app/models/comment.rb
  app/models/discussion_lock.rb
  app/models/user.rb
  app/policies/article_policy.rb
  app/policies/discussion_lock_policy.rb
  app/views/articles/_full_comment_area.html.erb
  app/views/articles/discussion_lock_confirm.html.erb
  app/views/articles/discussion_unlock_confirm.html.erb
  app/views/articles/manage.html.erb
  app/views/comments/_comment_footer.html.erb
  app/views/comments/_discussion_lock_reason.html.erb
  app/views/dashboards/_dashboard_article.html.erb
  config/routes.rb
  cypress/integration/articleFlows/manageFlows/lockDiscussion.spec.js
  cypress/integration/articleFlows/manageFlows/unlockDiscussion.spec.js
  db/migrate/20210531152321_create_discussion_locks.rb
  db/schema.rb
  spec/factories/articles.rb
  spec/factories/discussion_locks.rb
  spec/models/article_spec.rb
  spec/models/comment_spec.rb
  spec/models/discussion_lock_spec.rb
  spec/models/user_spec.rb
  spec/policies/discussion_lock_policy_spec.rb
  spec/requests/discussion_locks_spec.rb
  spec/system/articles/user_discussion_locks_spec.rb
Labels: PR: unreviewed

#13911 Point changes to inbox_type and inbox_guidelines attributes to users_settings table
  app/controllers/users/settings_controller.rb
  app/models/user.rb
  app/views/users/_extensions.html.erb
  spec/models/user_spec.rb
  spec/requests/user/user_settings_spec.rb
Labels: PR: unreviewed

#13407 Remove defer attributes from inline scripts - gist embeds
  app/javascript/article-form/articleForm.jsx
  app/javascript/packs/articlePage.jsx
  app/javascript/packs/commentsDisplay.js
  app/javascript/packs/notificationPage.js
  app/javascript/packs/postCommentsPage.js
  app/javascript/utilities/gist.js
  app/views/articles/show.html.erb
  app/views/comments/_form.html.erb
  app/views/comments/edit.html.erb
  app/views/comments/index.html.erb
  app/views/notifications/index.html.erb
  cypress/integration/articleFlows/commentOnArticle.spec.js
  cypress/integration/publishingFlows/previewPost.spec.js
Labels: PR: partially-approved

#13958 Removing Settings::General.email_addresses
  app/controllers/admin/settings/general_settings_controller.rb
  app/controllers/admin/users_controller.rb
  app/controllers/api_secrets_controller.rb
  app/controllers/confirmations_controller.rb
  app/controllers/users_controller.rb
  app/errors/authentication/errors.rb
  app/helpers/application_helper.rb
  app/lib/constants/settings/general.rb
  app/mailers/application_mailer.rb
  app/mailers/devise_mailer.rb
  app/mailers/verification_mailer.rb
  app/models/forem_instance.rb
  app/models/settings/general.rb
  app/services/error_messages/clean.rb
  app/views/admin/settings/show.html.erb
  app/views/admin/users/_data_export.html.erb
  app/views/deep_links/mobile.html.erb
  app/views/events/_event.html.erb
  app/views/mailers/notify_mailer/account_deleted_email.text.erb
  app/views/mailers/notify_mailer/tag_moderator_confirmation_email.text.erb
  app/views/mailers/notify_mailer/trusted_role_email.text.erb
  app/views/moderations/_mod_sidebar_left.html.erb
  app/views/open_search/show.xml.erb
  app/views/users/_org_admin.html.erb
  lib/data_update_scripts/20210509105151_remove_unused_site_config_emails.rb
  lib/data_update_scripts/20210604104735_remove_email_addresses_scripts.rb
  spec/helpers/application_helper_spec.rb
  spec/lib/data_update_scripts/remove_unused_site_config_emails_spec.rb
  spec/mailers/devise_mailer_spec.rb
  spec/mailers/digest_mailer_spec.rb
  spec/mailers/notify_mailer_spec.rb
  spec/mailers/shared_examples/renders_proper_email_headers.rb
  spec/mailers/verification_mailer_spec.rb
  spec/requests/admin/configs_spec.rb
  spec/requests/user/user_settings_spec.rb
  spec/services/exporter/service_spec.rb
  spec/system/authentication/user_request_confirmation_spec.rb
Labels: PR: reviewed-approved

#13961 15 minute fix: Shorten long titles from feed items if needed
  app/services/feeds/assemble_article_markdown.rb
  spec/services/feeds/assemble_article_markdown_spec.rb
Labels: PR: partially-approved

#13965 Simplify logic around generated article description
  app/models/article.rb
Labels: PR: reviewed-approved

#13916 Optimise dropdowns for accessibility - Profile page
  app/assets/javascripts/initializePage.js
  app/assets/javascripts/initializers/initializeUserProfilePage.js
  app/javascript/packs/profileDropdown.js
  app/views/users/show.html.erb
  cypress/integration/profileFlows/profileUserActionsMenu.spec.js
Labels: PR: partially-approved

#13972 Update test section
  .github/PULL_REQUEST_TEMPLATE.md
Labels: PR: reviewed-approved

#13979 [15 min fix] Flakey "change password" spec
  cypress/integration/loginFlows/userChangePassword.spec.js
Labels: PR: partially-approved, merge by any core

#13980 Revert "Bump jest-watch-typeahead from 0.6.3 to 0.6.4"
  package.json
  yarn.lock
Labels: PR: partially-approved

#13969 Call subscribe_to_mailchimp_newsletter after the transaction is commited
  app/models/user.rb
  spec/models/user_spec.rb
Labels: PR: partially-approved

#13943 Create Settings::SMTP
  app/controllers/admin/settings/smtp_settings_controller.rb
  app/lib/constants/settings/smtp.rb
  app/mailers/application_mailer.rb
  app/models/forem_instance.rb
  app/models/settings/smtp.rb
  app/views/admin/settings/show.html.erb
  config/environments/production.rb
  config/initializers/inflections.rb
  config/routes/admin.rb
  db/migrate/20210609164958_create_settings_smtp.rb
  db/schema.rb
  spec/mailers/application_mailer_spec.rb
  spec/mailers/notify_mailer_spec.rb
  spec/models/follow_spec.rb
  spec/models/forem_instance_spec.rb
  spec/models/message_spec.rb
  spec/models/settings/smtp_spec.rb
  spec/requests/admin/chat_channel_spec.rb
  spec/requests/admin/feedback_messages_spec.rb
  spec/requests/admin/users_spec.rb
  spec/requests/feedback_messages_spec.rb
  spec/requests/user/user_settings_spec.rb
  spec/services/exporter/service_spec.rb
  spec/system/admin/user_email_tools_spec.rb
  spec/workers/organizations/delete_worker_spec.rb
  spec/workers/users/delete_worker_spec.rb
Labels: PR: unreviewed

#13981 Ensure seeded page slugs are unique
  spec/support/seeds/seeds_e2e.rb
Labels: PR: partially-approved

#13910 Point changes in notification settings to `users_notification_settings` table
  app/controllers/users/notification_settings_controller.rb
  app/controllers/users_controller.rb
  app/models/user.rb
  app/views/users/_notifications.html.erb
  config/routes.rb
Labels: PR: unreviewed

#13966 [15-min-fix] Remove check for blank mailchimp newsletter ID
  app/models/user.rb
Labels: PR: partially-approved

#13983 Revert Email config changes
  app/mailers/application_mailer.rb
  config/environments/production.rb
  spec/mailers/application_mailer_spec.rb
  spec/models/settings/smtp_spec.rb
  spec/system/user_logs_in_with_password_spec.rb
Labels: PR: partially-approved

#13955 Refactor credit purchasing
  app/controllers/credits_controller.rb
  app/services/payments/process_credit_purchase.rb
Labels: PR: reviewed-approved

#13950 Refactor admin settings view into partials
  app/controllers/admin/settings_controller.rb
  app/views/admin/settings/forms/_api_tokens.html.erb
  app/views/admin/settings/forms/_authentication.html.erb
  app/views/admin/settings/forms/_campaign.html.erb
  app/views/admin/settings/forms/_community.html.erb
  app/views/admin/settings/forms/_credits.html.erb
  app/views/admin/settings/forms/_email_digest_frequency.html.erb
  app/views/admin/settings/forms/_emails.html.erb
  app/views/admin/settings/forms/_google_analytics.html.erb
  app/views/admin/settings/forms/_images.html.erb
  app/views/admin/settings/forms/_mandatory.html.erb
  app/views/admin/settings/forms/_mascot.html.erb
  app/views/admin/settings/forms/_meta_keywords.html.erb
  app/views/admin/settings/forms/_monetization.html.erb
  app/views/admin/settings/forms/_newsletter.html.erb
  app/views/admin/settings/forms/_onboarding.html.erb
  app/views/admin/settings/forms/_rate_limit.html.erb
  app/views/admin/settings/forms/_smtp.html.erb
  app/views/admin/settings/forms/_sponsors.html.erb
  app/views/admin/settings/forms/_tags.html.erb
  app/views/admin/settings/forms/_user_experience.html.erb
  app/views/admin/settings/forms/authentication/_apple_auth_provider_settings.html.erb
  app/views/admin/settings/forms/authentication/_auth_provider_settings.html.erb
  app/views/admin/settings/show.html.erb
  app/views/comments/_form.html.erb
Labels: PR: unreviewed

#13806 Message context menu in connect is not accessible #12250
  app/assets/stylesheets/chat.scss
  app/javascript/chat/chat.jsx
  app/javascript/chat/content.jsx
  app/javascript/chat/message.jsx
  app/javascript/utilities/dropdownUtils.js
  cypress/fixtures/users/chatUser1.json
  cypress/fixtures/users/chatUser2.json
  cypress/integration/chatFlows/messageOptions.spec.js
  spec/support/seeds/seeds_e2e.rb
Labels: PR: unreviewed

#13986 [15 min fix] Improve reliability of profile dropdown test
  cypress/integration/profileFlows/profileUserActionsMenu.spec.js
Labels: PR: partially-approved

#13963 fix usage of aria current - html error
  app/views/articles/index.html.erb
  app/views/stories/tagged_articles/index.html.erb
  cypress/integration/homeFeedFlows/feedNavigation.spec.js
  cypress/integration/tagsFlows/tagIndexNavigation.spec.js
Labels: PR: partially-approved

#13948 Optimise dropdowns for accessibility: Preact component usages
  app/assets/stylesheets/views/listings.scss
  app/javascript/CommentSubscription/CommentSubscription.jsx
  app/javascript/CommentSubscription/__tests__/CommentSubscription.test.jsx
  app/javascript/article-form/components/EditorActions.jsx
  app/javascript/article-form/components/Options.jsx
  app/javascript/crayons/Dropdown/Dropdown.jsx
  app/javascript/crayons/Dropdown/__stories__/Dropdown.stories.jsx
  app/javascript/crayons/Dropdown/__stories__/dropdown.html.stories.jsx
  app/javascript/crayons/Dropdown/__stories__/dropdowns.md
  app/javascript/listings/singleListing/DropdownMenu.jsx
  app/javascript/listings/singleListing/Header.jsx
  app/javascript/listings/singleListing/SingleListing.jsx
  app/javascript/packs/articlePage.jsx
  app/javascript/utilities/dropdownUtils.js
  cypress/integration/articleFlows/subscribeToArticleComments.spec.js
  cypress/integration/publishingFlows/postOptions.spec.js
Labels: PR: unreviewed

#13985 Send Devise emails asynchronously
  app/models/user.rb
  spec/requests/admin/invitations_spec.rb
  spec/system/user_logs_in_with_password_spec.rb
Labels: PR: partially-approved, merge by any core

#13982 [15 min fix] Refactor private landing pages model code
  app/controllers/admin/pages_controller.rb
  app/controllers/application_controller.rb
  app/javascript/admin/controllers/landing_page_modal_controller.js
  app/models/page.rb
  app/views/admin/pages/_form.html.erb
  spec/models/page_spec.rb
Labels: PR: partially-approved

#13953 API: Remove orphan Admin Config jbuilder file ✂️
  app/views/api/v0/admin/configs/show.json.jbuilder
Labels: PR: partially-approved

#13997 Don't use Honeycomb test mode in production
  config/initializers/honeycomb.rb
Labels: PR: reviewed-approved

#14007 15 min fix - only initialise article buttons once
  app/assets/javascripts/initializers/initializeBaseUserData.js
Labels: PR: partially-approved, merge by any core

#14006 [15-minute fix] Remove navigation links from footer on private Forems
  app/models/forem_instance.rb
  app/views/layouts/_footer.html.erb
  spec/system/layout_spec.rb
Labels: PR: partially-approved

#13971 [15-minute fix] Change signature of Feeds::ImportArticlesWorker
  app/controllers/users_controller.rb
  app/workers/feeds/import_articles_worker.rb
  spec/requests/user/user_settings_spec.rb
  spec/workers/feeds/import_articles_worker_spec.rb
Labels: PR: reviewed-approved

#13998 Clean up forem:setup task
  app/services/profile_fields/add_base_fields.rb
  app/services/profile_fields/add_branding_fields.rb
  app/services/profile_fields/add_link_fields.rb
  app/services/profile_fields/add_work_fields.rb
  app/services/profile_fields/field_definition.rb
  lib/tasks/app_initializer.rake
  lib/tasks/forem.rake
  spec/services/profile_fields/field_definition_spec.rb
Labels: PR: partially-approved

#14011 Fixed typo 'SlideSare'
  app/views/pages/_editor_guide_text.html.erb
Labels: PR: reviewed-approved

#13993 stories list script as separate js file - defer attribute
  app/assets/stylesheets/articles.scss
  app/javascript/packs/storiesList.js
  app/views/articles/index.html.erb
  app/views/articles/search.html.erb
  app/views/organizations/show.html.erb
  app/views/podcast_episodes/index.html.erb
  app/views/podcasts/new.html.erb
  app/views/stories/_stories_list_script.html.erb
  app/views/stories/tagged_articles/index.html.erb
  app/views/users/show.html.erb
Labels: PR: partially-approved

#13990 Profile Preview Cards (RFC #222): Article page author byline
  app/assets/stylesheets/config/_variables.scss
  app/assets/stylesheets/minimal.scss
  app/assets/stylesheets/profile-preview-card.scss
  app/javascript/packs/articlePage.jsx
  app/views/articles/_sticky_nav.html.erb
  app/views/articles/show.html.erb
  app/views/shared/_profile_card_content.html.erb
  app/views/shared/_profile_preview_card.html.erb
  app/views/shared/_user_metadata.html.erb
  cypress/integration/articleFlows/previewProfile.spec.js
  spec/support/seeds/seeds_e2e.rb
Labels: PR: partially-approved

#14040 Add container tag expiration
  scripts/build_containers.sh
Labels: PR: partially-approved

#14021 [15-minute fix] Consistently use `ForemInstance.private?`
  app/helpers/application_helper.rb
  app/helpers/authentication_helper.rb
  app/services/authentication/providers.rb
  app/views/admin/settings/forms/_authentication.html.erb
  app/views/devise/registrations/_registration_form.html.erb
  app/views/shared/authentication/_providers_registration_form.html.erb
  spec/helpers/authentication_helper_spec.rb
  spec/system/authentication/creator_config_edit_spec.rb
  spec/system/authentication/user_logs_in_with_email_spec.rb
  spec/system/authentication/user_logs_in_with_facebook_spec.rb
  spec/system/authentication/user_logs_in_with_github_spec.rb
  spec/system/authentication/user_logs_in_with_twitter_spec.rb
Labels: PR: partially-approved

#14031 [15 minute fix] Reading list: fix broken pagination
  app/javascript/searchableItemList/searchableItemList.js
Labels: PR: partially-approved

#14032 Always show preview card on hover
  app/javascript/utilities/dropdownUtils.js
Labels: PR: partially-approved

#14046 [15 min fix] Remove instantclick change listener on analytics dashboard
  app/javascript/packs/analyticsDashboard.js
Labels: PR: reviewed-approved

#14036 Fix sitemap for self host, including memory leak
  .gitignore
  app/workers/sitemap_refresh_worker.rb
  config/sitemap.rb
Labels: PR: unreviewed

#14047 Skip message options spec
  cypress/integration/chatFlows/messageOptions.spec.js
Labels: PR: partially-approved, merge by any core

#14019 [15-minute fix] Remove badge notice from `/settings/profile`
  app/views/pages/badges.html.erb
  app/views/users/_profile.html.erb
  config/routes.rb
Labels: PR: partially-approved

#14038 [15-min-fix] Ensure mention worker delivers email
  app/workers/mentions/send_email_notification_worker.rb
  spec/workers/mentions/send_email_notification_worker_spec.rb
Labels: PR: partially-approved

#14050 Resolve sitemap's undefined variable
  config/sitemap.rb
Labels: PR: reviewed-approved

#13928 LinkTag: correctly display organization avatar
  app/assets/stylesheets/ltags/LinkTag.scss
  app/views/articles/_liquid.html.erb
  spec/liquid_tags/link_tag_spec.rb
Labels: PR: partially-approved

#14051 [15-Minute Fix] Uncomment Expectation from admin_manages_organizations_spec.rb
  spec/system/admin/admin_manages_organizations_spec.rb
Labels: PR: reviewed-approved, merge by any core

#14049 [15-Minute Fix] Fix Broken Admin Tags #create and #update Forms
  app/controllers/admin/tags_controller.rb
  app/views/admin/tags/_form.html.erb
  app/views/admin/tags/edit.html.erb
  spec/system/admin/admin_creates_new_tag_spec.rb
  spec/system/admin/admin_updates_tag_spec.rb
Labels: PR: partially-approved, merge by any core

#13995 add org analytics menu if user has organizations
  app/javascript/packs/analyticsDashboard.js
  app/views/dashboards/analytics.erb
  cypress/integration/analyticsFlows/analyticsNavigation.spec.js
  spec/support/seeds/seeds_e2e.rb
Labels: PR: partially-approved

#14033 Prevent focus stealing caused by dropdown listeners not being cleaned up
  app/javascript/utilities/dropdownUtils.js
  cypress/integration/articleFlows/previewProfile.spec.js
Labels: PR: partially-approved

#14041 Remove navigation links from footer
  app/views/layouts/_footer.html.erb
  cypress/integration/navigationFlows/homePageLeftSidebar.spec.js
  spec/system/layout_spec.rb
Labels: PR: reviewed-approved

#14057 [15-Minute Fix] Fix Broken Admin Tags "Remove" Mod Button
  app/views/admin/tags/edit.html.erb
  spec/system/admin/admin_creates_new_tag_spec.rb
Labels: PR: reviewed-approved, merge by any core

#14048 Add explicit loose configuration for babel plugins
  babel.config.js
Labels: PR: partially-approved

#13967 Replace admin guide links
  .github/PULL_REQUEST_TEMPLATE.md
  app/controllers/admin/application_controller.rb
  app/views/admin/overview/index.html.erb
  app/views/layouts/admin.html.erb
  spec/tasks/metrics_spec.rb
Labels: PR: reviewed-approved

#13994 Re-add dynamic delivery_method for ApplicationMailer
  app/mailers/application_mailer.rb
  app/mailers/concerns/deliverable.rb
  app/mailers/devise_mailer.rb
  app/workers/follows/send_email_notification_worker.rb
  config/environments/production.rb
  spec/mailers/application_mailer_spec.rb
Labels: PR: reviewed-approved

#14015 Make Consumer Apps dictate aasa results
  app/controllers/deep_links_controller.rb
  app/javascript/admin/controllers/consumer_app_controller.js
  app/models/consumer_app.rb
  app/queries/consumer_apps/find_or_create_all_query.rb
  app/queries/consumer_apps/find_or_create_by_query.rb
  app/views/admin/consumer_apps/_form.html.erb
  app/views/admin/consumer_apps/edit.html.erb
  app/views/admin/consumer_apps/new.html.erb
  cypress/integration/adminFlows/consumerApps/createConsumerApp.spec.js
  db/migrate/20210622002941_add_team_id_to_consumer_apps.rb
  db/schema.rb
  lib/data_update_scripts/20210622145212_backfill_forem_consumer_app_team_id.rb
  spec/lib/data_update_scripts/backfill_forem_consumer_app_team_id_spec.rb
  spec/queries/consumer_apps/find_or_create_all_query_spec.rb
  spec/queries/consumer_apps/find_or_create_by_query_spec.rb
  spec/queries/consumer_apps/rpush_app_query_spec.rb
  spec/requests/universal_links_spec.rb
Labels: PR: unreviewed

#14056 Profile Preview Cards (RFC#222) - author name in comments
  app/assets/javascripts/utilities/buildCommentHTML.js.erb
  app/controllers/profile_preview_card_controller.rb
  app/javascript/packs/commentDropdowns.js
  app/views/comments/_comment_header.html.erb
  app/views/profile_preview_card/show.html.erb
  app/views/shared/_profile_card_content.html.erb
  app/views/shared/_profile_preview_card.html.erb
  app/views/shared/_user_metadata.html.erb
  config/routes.rb
  cypress/integration/articleFlows/commentOnArticle.spec.js
  cypress/integration/articleFlows/previewProfile.spec.js
  spec/support/seeds/seeds_e2e.rb
Labels: PR: unreviewed

#14067 [15 min fix] - Add the Comments Nav Item in the Admin Sidebar
  app/models/admin_menu.rb
Labels: PR: partially-approved

#14072 Don't show "Skip to content" link for searches
  app/assets/javascripts/base.js.erb
  cypress/integration/searchFlows/skipToContent.spec.js
Labels: PR: partially-approved

#14068 [15 min fix] ✂️ Remove unnecessary metadata for preview cards and sticky nav ✂️
  app/views/shared/_profile_card_content.html.erb
  app/views/shared/_user_metadata.html.erb
Labels: PR: partially-approved

#14084 [docs] Fix typo in imgproxy.md
  docs/installation/imgproxy.md
Labels: PR: partially-approved

#14087 Prevent occasional matching on random name by specifying one
  spec/services/search/username_spec.rb
Labels: PR: partially-approved

#14063 Change default value for editor version
  app/controllers/admin/invitations_controller.rb
  app/controllers/registrations_controller.rb
  app/services/authentication/authenticator.rb
  db/migrate/20210624153854_change_default_value_for_editor_version.rb
  db/schema.rb
  spec/services/article_with_video_creation_service_spec.rb
  spec/services/articles/builder_spec.rb
  spec/support/seeds/seeds_e2e.rb
  spec/system/articles/user_creates_an_article_spec.rb
  spec/system/articles/user_fixes_a_draft_spec.rb
  spec/system/user_uses_the_editor_spec.rb
Labels: PR: unreviewed

#14086 Fix spacing in comment header broken by preview card work
  app/assets/javascripts/utilities/buildCommentHTML.js.erb
  app/views/comments/_comment_header.html.erb
Labels: PR: partially-approved, merge by any core

#14091 Chat: disconnect IntersectionObserver to avoid leaking memory
  app/javascript/chat/util.js
Labels: PR: reviewed-approved

#14029 [15-minute fix] Disable 'Locked Screen' prompt for public Forems
  app/views/admin/pages/_form.html.erb
  cypress/integration/adminFlows/pages/landingPage.spec.js
  spec/system/admin/admin_creates_new_page_spec.rb
  spec/system/admin/admin_manages_pages_spec.rb
Labels: PR: partially-approved

#14103 Bug Fix: Strikethrough markdown within a link is not rendered in live comments
  app/models/comment.rb
Labels: PR: partially-approved

#14037 HTML error fix - better urlencode - share links
  app/views/articles/_actions.html.erb
Labels: PR: unreviewed

#14112 Apply unstaged yarn.lock changes
  yarn.lock
Labels: PR: partially-approved

#14105 Change default value for saw_onboarding
  app/controllers/admin/invitations_controller.rb
  app/controllers/registrations_controller.rb
  app/services/authentication/authenticator.rb
  db/migrate/20210629174206_change_default_value_for_saw_onboarding.rb
  db/schema.rb
Labels: PR: partially-approved

#14113 Track Profile count in RecordDataCountsWorker
  app/workers/metrics/record_data_counts_worker.rb
Labels: PR: reviewed-approved
