Repository forem/forem, pull requests merged in 2021-09, with the labels that each got.

#14635 Log prop-types warnings to console in development
  app/javascript/article-form/components/Tabs.jsx
  app/javascript/articles/LoadingArticle.jsx
  app/javascript/articles/components/PublishDate.jsx
  app/javascript/articles/components/SearchSnippet.jsx
  app/javascript/articles/components/TagList.jsx
  app/javascript/common-prop-types/article-prop-types.js
  app/javascript/common-prop-types/index.js
  app/javascript/common-prop-types/tag-prop-types.js
  app/javascript/crayons/Button/Button.jsx
  app/javascript/crayons/Modal/Modal.jsx
  app/javascript/leftSidebar/TagsFollowed.jsx
  app/javascript/listings/components/ListingFilters.jsx
  app/javascript/listings/singleListing/Header.jsx
  app/javascript/shared/components/useKeyboardShortcuts.js
  config/webpack/development.js
Labels: PR: partially-approved

#14548 Avoid blank screen in Deep Links Edge cases
  app/javascript/runtimeBanner/RuntimeBanner.jsx
Labels: PR: partially-approved

#14418 Save Confirmation - Admin (Part 1 of 2)
  app/controllers/admin/settings/base_controller.rb
  app/controllers/admin/settings/general_settings_controller.rb
  app/controllers/admin/settings/smtp_settings_controller.rb
  app/javascript/admin/controllers/config_controller.js
  app/views/admin/settings/_form_submission.html.erb
  app/views/admin/settings/_update_setting_button.html.erb
  app/views/admin/settings/forms/_api_tokens.html.erb
  app/views/admin/settings/forms/_authentication.html.erb
  app/views/admin/settings/forms/_campaign.html.erb
  app/views/admin/settings/forms/_community.html.erb
  app/views/admin/settings/forms/_credits.html.erb
  app/views/admin/settings/forms/_email_digest_frequency.html.erb
  app/views/admin/settings/forms/_google_analytics.html.erb
  app/views/admin/settings/forms/_images.html.erb
  app/views/admin/settings/forms/_mandatory.html.erb
  app/views/admin/settings/forms/_mascot.html.erb
  app/views/admin/settings/forms/_meta_keywords.html.erb
  app/views/admin/settings/forms/_monetization.html.erb
  app/views/admin/settings/forms/_newsletter.html.erb
  app/views/admin/settings/forms/_onboarding.html.erb
  app/views/admin/settings/forms/_rate_limit.html.erb
  app/views/admin/settings/forms/_smtp.html.erb
  app/views/admin/settings/forms/_sponsors.html.erb
  app/views/admin/settings/forms/_tags.html.erb
  app/views/admin/settings/forms/_user_experience.html.erb
  cypress/integration/seededFlows/adminFlows/config/authenticationSection.spec.js
  cypress/integration/seededFlows/adminFlows/config/campaignSection.spec.js
  cypress/integration/seededFlows/adminFlows/config/communitySection.spec.js
  cypress/integration/seededFlows/adminFlows/config/emailDigestFrequencySection.spec.js
  cypress/integration/seededFlows/adminFlows/config/getStartedSection.spec.js
  cypress/integration/seededFlows/adminFlows/config/mascotSection.spec.js
  cypress/integration/seededFlows/adminFlows/config/rateLimitSection.spec.js
  cypress/integration/seededFlows/adminFlows/config/userExperienceSection.spec.js
  cypress/integration/seededFlows/adminFlows/pages/landingPage.spec.js
  cypress/support/commands.js
  spec/requests/admin/configs_spec.rb
Labels: PR: unreviewed, merge by any core, include in changelog

#14668 Cache return value of `FeatureFlag.enabled?`
  Gemfile
  Gemfile.lock
  config/initializers/flipper.rb
  vendor/cache/flipper-active_support_cache_store-0.22.1.gem
Labels: PR: partially-approved

#14389 Accessible names for follow buttons
  app/assets/javascripts/utilities/buildArticleHTML.js
  app/helpers/application_helper.rb
  app/javascript/articles/__tests__/__snapshots__/Article.test.jsx.snap
  app/javascript/packs/followButtons.js
  app/javascript/profilePreviewCards/MinimalProfilePreviewCard.jsx
  app/views/articles/_single_story.html.erb
  app/views/layouts/_sidebar_tags.html.erb
  app/views/organizations/_header.html.erb
  app/views/organizations/_liquid.html.erb
  app/views/podcast_episodes/_liquid.html.erb
  app/views/podcast_episodes/index.html.erb
  app/views/podcast_episodes/show.html.erb
  app/views/stories/tagged_articles/index.html.erb
  app/views/tags/index.html.erb
  app/views/users/_liquid.html.erb
  app/views/users/show.html.erb
  cypress/integration/seededFlows/articleFlows/followAuthor.spec.js
  cypress/integration/seededFlows/articleFlows/followFromArticleLiquidTag.spec.js
  cypress/integration/seededFlows/articleFlows/previewProfile.spec.js
  cypress/integration/seededFlows/articleFlows/seriesFlows/previewProfileFromSeries.spec.js
  cypress/integration/seededFlows/articleFlows/viewArticleDiscussion.spec.js
  cypress/integration/seededFlows/homeFeedFlows/profilePreviewCards.spec.js
  cypress/integration/seededFlows/loggedOutFlows/homeFeed.spec.js
  cypress/integration/seededFlows/loggedOutFlows/showLoginModal.spec.js
  cypress/integration/seededFlows/loggedOutFlows/tagIndex.spec.js
  cypress/integration/seededFlows/notificationsFlows/followUserFromNotifications.spec.js
  cypress/integration/seededFlows/podcastFlows/followPodcast.spec.js
  cypress/integration/seededFlows/profileFlows/followOrganisation.spec.js
  cypress/integration/seededFlows/profileFlows/followUser.spec.js
  cypress/integration/seededFlows/searchFlows/followUser.spec.js
  cypress/integration/seededFlows/searchFlows/previewProfileFromPostSearchResults.spec.js
  cypress/integration/seededFlows/tagsFlows/followTag.spec.js
  cypress/integration/seededFlows/tagsFlows/previewProfileFromTagIndex.spec.js
Labels: PR: partially-approved, include in changelog

#14679 Remove outdated notice in authentication config
  app/views/admin/settings/forms/_authentication.html.erb
Labels: PR: partially-approved, merge by any core

#14682 Check for the current version of foreman when deciding to install
  bin/setup
Labels: PR: unreviewed, area: gitpod

#14685 When calling Faker::Markdown, avoid "sandwich" method
  db/seeds.rb
Labels: PR: unreviewed

#14677 In dashboard show api eager load collection with articles
  app/controllers/dashboards_controller.rb
  config/environments/development.rb
  config/environments/test.rb
Labels: PR: reviewed-approved

#14688 Add temporary ahoy stats for tag sidebar clicks
  app/javascript/leftSidebar/TagsFollowed.jsx
  app/javascript/packs/homePage.jsx
  app/views/layouts/_sidebar_tags.html.erb
Labels: PR: partially-approved, merge by any core

#14686 Run yarn upgrade & add resolution for glob-parent
  package.json
  yarn.lock
Labels: PR: partially-approved

#14665 Warmer shades of grey
  app/assets/stylesheets/config/_colors.scss
  app/assets/stylesheets/themes/night.scss
Labels: PR: reviewed-approved, area: themes, PR: draft, PR: partially-approved

#14696 Updated node version in Gitpod
  .gitpod.dockerfile
Labels: PR: partially-approved, area: gitpod, merge by any core

#14697 Fixed awaiting web server command in Gitpod
  .gitpod.yml
Labels: PR: partially-approved, area: gitpod, merge by any core

#14698 Added gitpod-init script
  .gitpod.yml
  gitpod-init.sh
Labels: PR: unreviewed, area: gitpod, merge by any core

#14699 Update rubocop-rails
  Gemfile.lock
  vendor/cache/rubocop-rails-2.12.0.gem
  vendor/cache/rubocop-rails-2.12.1.gem
Labels: PR: partially-approved

#14701 3d drop shadows
  app/assets/javascripts/utilities/buildArticleHTML.js
  app/assets/stylesheets/components/autocomplete.scss
  app/assets/stylesheets/components/dropdowns.scss
  app/assets/stylesheets/components/forms.scss
  app/assets/stylesheets/components/modals.scss
  app/assets/stylesheets/components/notices.scss
  app/assets/stylesheets/components/snackbars.scss
  app/assets/stylesheets/config/_colors.scss
  app/assets/stylesheets/config/_import.scss
  app/assets/stylesheets/config/_variables.scss
  app/assets/stylesheets/ltags/UserSubscriptionTag.scss
  app/assets/stylesheets/signin.scss
  app/assets/stylesheets/signup-modal.scss
  app/assets/stylesheets/themes/hacker.scss
  app/assets/stylesheets/themes/minimal.scss
  app/assets/stylesheets/themes/night.scss
  app/assets/stylesheets/themes/pink.scss
  app/assets/stylesheets/views/article-form.scss
  app/assets/stylesheets/views/comments.scss
  app/assets/stylesheets/views/listings.scss
  app/assets/stylesheets/views/signin.scss
  app/assets/stylesheets/views/signup-modal.scss
  app/javascript/articles/__tests__/__snapshots__/Article.test.jsx.snap
  app/javascript/profilePreviewCards/MinimalProfilePreviewCard.jsx
  app/views/articles/_single_story.html.erb
  app/views/layouts/_nav_menu.html.erb
Labels: area: themes, PR: partially-approved

#14644 Add feature flag for Connect
  app/javascript/chat/chat.jsx
  app/models/admin_menu.rb
  app/views/layouts/_top_bar.html.erb
  app/views/mailers/notify_mailer/tag_moderator_confirmation_email.html.erb
  app/views/mailers/notify_mailer/tag_moderator_confirmation_email.text.erb
  app/views/users/_extensions.html.erb
  app/views/users/show.html.erb
  config/routes.rb
  config/routes/admin.rb
  lib/data_update_scripts/20210831052422_add_connect_feature_flag.rb
  spec/lib/data_update_scripts/add_connect_feature_flag_spec.rb
  spec/rails_helper.rb
  spec/support/seeds/seeds_e2e.rb
Labels: PR: partially-approved, merge by specific delegate

#14695 Handle GibbonError when Mailchimp api key was not set
  app/services/mailchimp/bot.rb
  spec/services/mailchimp/bot_spec.rb
Labels: PR: partially-approved

#14643 Refactor profile refreshing
  .travis.yml
  app/models/profile.rb
  app/services/profile_fields/remove.rb
  spec/models/profile_spec.rb
  spec/requests/admin/profile_fields_spec.rb
  spec/services/profile_fields/remove_spec.rb
Labels: PR: partially-approved

#14725 Update Forem core team only section
  .github/PULL_REQUEST_TEMPLATE.md
Labels: PR: unreviewed

#14706 [15-minute fix] Don't try to create invalid RatingVote
  app/controllers/reactions_controller.rb
  spec/requests/reactions_spec.rb
Labels: PR: reviewed-approved

#14700 Forem background
  app/assets/stylesheets/base/layout.scss
  app/assets/stylesheets/config/_import.scss
  app/assets/stylesheets/views/confirm-email.scss
  app/views/devise/confirmations/new.html.erb
  app/views/shared/authentication/_forem_creator_signup.html.erb
  cypress/integration/creatorOnboardingFlows/confirmEmail.spec.js
Labels: PR: unreviewed

#14729 Rubocop fixes
  .rubocop.yml
  .rubocop_todo.yml
  app/black_box/black_box.rb
  app/controllers/users_controller.rb
  app/models/article.rb
  package.json
Labels: PR: partially-approved

#14731 Add context to Instance API
  app/controllers/api/v0/instances_controller.rb
  spec/requests/api/v0/instances_spec.rb
Labels: PR: reviewed-approved

#14710 Relax tag validation restriction to permit non-ascii strings
  app/controllers/tags_controller.rb
  app/lib/url.rb
  app/models/tag.rb
  spec/models/tag_spec.rb
Labels: PR: partially-approved

#14711 Fix bug where OAuth signups were not pulling in OAuth provider's profile image
  app/services/users/safe_remote_profile_image_url.rb
  spec/services/users/safe_remote_profile_image_url_spec.rb
Labels: area: auth, PR: partially-approved, actual_size:XS

#14732 Ensure ActiveRecord::Base has descendants before checking triggers
  spec/models/hair_trigger_spec.rb
Labels: PR: partially-approved

#14727 Remove ApplicationHelper#sanitize_and_decode
  app/helpers/application_helper.rb
  app/views/articles/show.html.erb
  app/views/comments/index.html.erb
  app/views/dashboards/_dashboard_article.html.erb
  app/views/dashboards/_dashboard_article_row.html.erb
  spec/helpers/application_helper_spec.rb
  spec/system/user_uses_the_editor_spec.rb
Labels: PR: partially-approved

#14733 Add display_in_directory setting
  app/controllers/api/v0/instances_controller.rb
  app/models/settings/user_experience.rb
  app/views/admin/settings/forms/_user_experience.html.erb
  spec/requests/admin/configs_spec.rb
  spec/requests/api/v0/instances_spec.rb
Labels: PR: partially-approved

#14708 Shortcut for "Following tags"
  app/views/tags/index.html.erb
Labels: PR: reviewed-approved, area: design, PR: partially-approved

#14684 Admin Save Confirmation - Removing Badge Achievements
  app/controllers/admin/badge_achievements_controller.rb
  app/javascript/admin/adminModal.js
  app/javascript/admin/controllers/config_controller.js
  app/javascript/admin/controllers/confirmation_modal_controller.js
  app/javascript/admin/controllers/error_controller.js
  app/javascript/admin/messageUtilities.js
  app/views/admin/badge_achievements/index.html.erb
  app/views/layouts/admin.html.erb
  cypress/integration/seededFlows/adminFlows/badges/badgeAchievements.spec.js
  spec/requests/admin/badge_achievements_spec.rb
Labels: PR: unreviewed, include in changelog

#14730 Fix Forem Ownership Field
  .github/PULL_REQUEST_TEMPLATE.md
  app/javascript/chat/chat.jsx
  app/models/forem_instance.rb
  app/views/shared/authentication/_forem_creator_signup.html.erb
Labels: PR: partially-approved, merge by any core

#14744 Use a textarea for apple_pem in admin
  app/views/admin/settings/forms/authentication/_apple_auth_provider_settings.html.erb
Labels: PR: unreviewed

#14738 Tabs
  app/assets/stylesheets/components/tabs.scss
  app/assets/stylesheets/config/_colors.scss
  app/assets/stylesheets/themes/hacker.scss
  app/assets/stylesheets/themes/night.scss
  app/javascript/packs/searchParams.js
  app/views/articles/index.html.erb
  app/views/stories/articles_search/_nav_menu.html.erb
  app/views/stories/articles_search/index.html.erb
  cypress/integration/seededFlows/homeFeedFlows/feedNavigation.spec.js
Labels: PR: partially-approved

#14707 Clean up feed-related code
  app/controllers/articles_controller.rb
  app/controllers/stories/feeds_controller.rb
  app/controllers/stories/tagged_articles_controller.rb
  app/controllers/stories_controller.rb
  app/services/articles/feeds/large_forem_experimental.rb
  app/services/articles/feeds/latest.rb
  app/services/articles/feeds/tag.rb
  app/services/articles/feeds/timeframe.rb
  spec/initializers/rack/attack_spec.rb
  spec/requests/articles/articles_spec.rb
  spec/requests/stories/feeds_spec.rb
  spec/services/articles/feeds/large_forem_experimental_spec.rb
  spec/services/articles/feeds/latest_spec.rb
  spec/services/articles/feeds/tag_spec.rb
  spec/services/articles/feeds/timeframe_spec.rb
Labels: PR: partially-approved

#14736 Style updates
  app/assets/stylesheets/components/stories.scss
  app/assets/stylesheets/profile-preview-card.scss
  app/views/layouts/_main_nav.html.erb
  app/views/layouts/_nav_menu.html.erb
  spec/system/homepage/user_visits_homepage_spec.rb
Labels: PR: partially-approved

#14750 Check required inputs for apple authentication
  app/javascript/admin/controllers/config_controller.js
Labels: PR: partially-approved

#14755 Little frontend refactor
  app/assets/javascripts/utilities/buildCommentHTML.js.erb
  app/assets/stylesheets/components/dropdowns.scss
  app/assets/stylesheets/components/stories.scss
  app/assets/stylesheets/views/profile.scss
  app/javascript/CommentSubscription/CommentSubscription.jsx
  app/views/articles/_actions.html.erb
  app/views/comments/_comment_header.html.erb
  app/views/dashboards/_dashboard_article.html.erb
  app/views/dashboards/_dashboard_article_row.html.erb
  app/views/layouts/_nav_menu.html.erb
  app/views/users/show.html.erb
Labels: PR: partially-approved, tech: frontend

#14739 Move pin post to admin ✂️
  app/assets/javascripts/initializers/initializeBaseUserData.js
  app/javascript/packs/articlePage.jsx
  cypress/integration/seededFlows/adminFlows/articles/pinArticle.spec.js
  cypress/integration/seededFlows/articleFlows/adminButtonArticle.spec.js
  cypress/integration/seededFlows/articleFlows/pinArticle.spec.js
Labels: PR: partially-approved, actual_size:XS

#14763 Added GitHub CLI to Gitpod.
  gitpod-init.sh
Labels: PR: partially-approved, area: gitpod

#14741 Remove Connect from listings
  app/javascript/listings/components/BodyMarkdown.jsx
  app/javascript/listings/listingForm.jsx
Labels: PR: reviewed-approved, merge by any core

#14766 Padding fix for profile preview cards
  app/assets/javascripts/utilities/buildArticleHTML.js
  app/javascript/articles/__tests__/__snapshots__/Article.test.jsx.snap
  app/javascript/profilePreviewCards/MinimalProfilePreviewCard.jsx
  app/views/shared/_profile_preview_card.html.erb
Labels: PR: partially-approved, tech: frontend, merge by any core

#14769 fix error adding removing tags from article mod tools
  app/javascript/actionsPanel/actionsPanel.js
  app/javascript/actionsPanel/initializeActionsPanelToggle.js
  app/javascript/packs/articleModerationTools.js
  cypress/integration/seededFlows/moderationFlows/adjustPostTags.spec.js
  spec/support/seeds/seeds_e2e.rb
Labels: PR: partially-approved

#14737 Fix getComputedStyle issues in jest tests
  app/javascript/organization/__tests__/OrganizationPicker.test.jsx
  testSetup.js
Labels: PR: partially-approved, merge by any core

#14752 Add internal top tags API
  app/controllers/tags_controller.rb
  config/routes.rb
  spec/requests/tags_spec.rb
Labels: PR: partially-approved, merge by any core

#14767 Fix organization's admin unable to view an article's stats
  app/policies/article_policy.rb
  spec/policies/article_policy_spec.rb
Labels: PR: reviewed-approved

#14784 Ensure seeded listings are valid for e2e tests
  spec/support/seeds/seeds_e2e.rb
Labels: PR: partially-approved, merge by any core

#14785 Onboarding fix
  app/javascript/utilities/connect/getUnopenedChannels.jsx
Labels: PR: partially-approved, merge by any core

#14787 Made GitHub CLI install permanent in Gitpod
  .gitpod.dockerfile
  gitpod-init.sh
Labels: PR: partially-approved, area: gitpod, merge by any core

#14777 Add mutable flag to APNS notifcation payload
  app/models/device.rb
  spec/models/device_spec.rb
Labels: PR: unreviewed, mobile, PR: partially-approved

#14788 Use vcr cassette to import rss feed for two users
  spec/services/feeds/import_spec.rb
  spec/support/fixtures/vcr_cassettes/feeds_import_two_users.yml
Labels: PR: partially-approved

#14687 Accessible names for follow buttons
  app/helpers/application_helper.rb
  app/javascript/packs/followButtons.js
  cypress/integration/seededFlows/articleFlows/followAuthor.spec.js
  cypress/integration/seededFlows/articleFlows/followFromArticleLiquidTag.spec.js
  cypress/integration/seededFlows/articleFlows/previewProfile.spec.js
  cypress/integration/seededFlows/articleFlows/seriesFlows/previewProfileFromSeries.spec.js
  cypress/integration/seededFlows/articleFlows/viewArticleDiscussion.spec.js
  cypress/integration/seededFlows/homeFeedFlows/profilePreviewCards.spec.js
  cypress/integration/seededFlows/loggedOutFlows/homeFeed.spec.js
  cypress/integration/seededFlows/loggedOutFlows/tagIndex.spec.js
  cypress/integration/seededFlows/notificationsFlows/followUserFromNotifications.spec.js
  cypress/integration/seededFlows/podcastFlows/followPodcast.spec.js
  cypress/integration/seededFlows/profileFlows/followOrganisation.spec.js
  cypress/integration/seededFlows/profileFlows/followUser.spec.js
  cypress/integration/seededFlows/searchFlows/followUser.spec.js
  cypress/integration/seededFlows/searchFlows/previewProfileFromPostSearchResults.spec.js
  cypress/integration/seededFlows/tagsFlows/followTag.spec.js
  cypress/integration/seededFlows/tagsFlows/previewProfileFromTagIndex.spec.js
Labels: PR: partially-approved

#14609 Zappat0n/add rate limit model everywhere 11500
  app/assets/javascripts/initializers/initNotifications.js
  app/assets/javascripts/initializers/initializeArticleReactions.js
  app/assets/javascripts/initializers/initializeCommentsPage.js.erb
  app/assets/javascripts/utilities/showUserAlertModal.js
  app/controllers/concerns/listings_toolkit.rb
  app/controllers/feedback_messages_controller.rb
  app/controllers/listings_controller.rb
  app/javascript/packs/followButtons.js
  cypress/integration/seededFlows/articleFlows/commentOnArticle.spec.js
  spec/requests/feedback_messages_spec.rb
  spec/requests/listings_spec.rb
  spec/system/articles/user_creates_an_article_spec.rb
  spec/system/articles/user_edits_an_article_spec.rb
  spec/system/feedback_message_spec.rb
Labels: PR: partially-approved, ci

#14795 Check Connect feature flag in more places
  app/models/organization_membership.rb
  app/services/tag_moderators/add.rb
Labels: PR: reviewed-approved

#14790 [15 minute fix] Podcast fixes/clean up
  app/assets/stylesheets/ltags/PodcastTag.scss
  app/assets/stylesheets/user-profile-header.scss
  app/views/organizations/_header.html.erb
  app/views/podcast_episodes/_liquid.html.erb
  app/views/podcast_episodes/index.html.erb
  app/views/podcast_episodes/show.html.erb
  app/views/users/show.html.erb
  cypress/integration/seededFlows/loggedOutFlows/showLoginModal.spec.js
  cypress/integration/seededFlows/podcastFlows/followPodcast.spec.js
Labels: PR: partially-approved

#14799 Fixed article series skipped heading level violation
  app/views/articles/_collection.html.erb
Labels: type: accessibility, PR: unreviewed, PR: partially-approved, merge by any core

#14829 fix installation URL
  README.md
Labels: PR: reviewed-approved

#14816 Remove header and footer from signup/email confirmation pages
  app/assets/stylesheets/setup-mode.scss
  app/views/devise/confirmations/new.html.erb
  app/views/devise/registrations/new.html.erb
Labels: PR: partially-approved

#14833 Fix admin menu when Connect feature flag is disabled
  app/views/admin/shared/_nested_sidebar.html.erb
Labels: PR: reviewed-approved

#14789 Fix inconsistencies with DisplayAd
  app/assets/javascripts/initializers/initializeBaseTracking.js.erb
  app/assets/stylesheets/widgets.scss
  app/helpers/display_ad_helper.rb
  app/models/display_ad.rb
  app/services/html/parser.rb
  app/views/admin/display_ads/_form.html.erb
  app/views/admin/display_ads/index.html.erb
  app/views/articles/_sidebar.html.erb
  app/views/sidebars/_homepage_content.html.erb
  spec/factories/display_ads.rb
  spec/helpers/display_ad_helper_spec.rb
  spec/models/display_ad_spec.rb
  spec/requests/stories_index_spec.rb
  spec/services/html/parser_spec.rb
Labels: PR: unreviewed

#14805 Include search term in title for improved accessibility
  app/views/stories/articles_search/index.html.erb
  spec/requests/stories/articles_search_spec.rb
Labels: PR: partially-approved

#14804 If there is no body of the linked issue or PR, don't render markdown
  app/models/github_issue.rb
Labels: PR: partially-approved

#14844 Add .pryrc to gitignore
  .gitignore
Labels: PR: reviewed-approved

#14801 Remove unneeded checks for code tags when filtering articles from search indexing
  app/controllers/sitemaps_controller.rb
  app/lib/constants/settings/user_experience.rb
  app/models/article.rb
  app/models/settings/user_experience.rb
  app/views/admin/settings/forms/_user_experience.html.erb
  app/views/articles/show.html.erb
  spec/requests/stories_show_spec.rb
Labels: area: admin, PR: partially-approved

#14846 [Tiny fix] Fix a couple small bugs from DisplayAd clean up
  app/assets/javascripts/initializers/initializeBaseTracking.js.erb
  app/services/html/parser.rb
Labels: PR: partially-approved

#14810 Move featured story to separate service
  app/controllers/stories_controller.rb
  app/services/articles/feeds/find_featured_story.rb
  app/services/articles/feeds/large_forem_experimental.rb
  spec/services/articles/feeds/find_featured_story_spec.rb
  spec/services/articles/feeds/large_forem_experimental_spec.rb
Labels: PR: partially-approved

#14856 Allow search endpoint to be used without q param
  app/views/stories/articles_search/index.html.erb
Labels: PR: partially-approved

#14848 Fix search param cache leak
  app/controllers/stories/articles_search_controller.rb
  config/fastly/snippets/safe_params_list.vcl
Labels: PR: partially-approved

#14782 Don't include "anti-followed" tags in email digest
  app/javascript/leftSidebar/TagsFollowed.jsx
  app/models/article.rb
  app/models/user.rb
  app/services/email_digest_article_collector.rb
  app/workers/follows/update_points_worker.rb
  config/routes.rb
  spec/models/article_spec.rb
  spec/services/email_digest_article_collector_spec.rb
Labels: PR: partially-approved, merge by any core

#14817 Suggest top tags when tag search is empty
  app/assets/stylesheets/views/article-form.scss
  app/controllers/tags_controller.rb
  app/javascript/shared/components/__tests__/tags.test.jsx
  app/javascript/shared/components/tags.jsx
  app/models/tag.rb
  app/services/search/tag.rb
  app/views/layouts/_sidebar_tags.html.erb
  app/workers/tags/resave_supported_tags_worker.rb
  cypress/integration/seededFlows/publishingFlows/addTagsToArticle.spec.js
  spec/system/homepage/user_visits_homepage_spec.rb
Labels: PR: partially-approved

#14864 Return 404 if empty and unsupported tag
  app/controllers/stories/tagged_articles_controller.rb
  spec/requests/stories/tagged_articles_spec.rb
Labels: PR: reviewed-approved

#14753 Article layout
  app/assets/javascripts/initializers/initializeBaseUserData.js
  app/assets/stylesheets/base/typography.scss
  app/assets/stylesheets/components/avatars.scss
  app/assets/stylesheets/components/buttons.scss
  app/assets/stylesheets/components/stories.scss
  app/assets/stylesheets/views/article.scss
  app/controllers/stories_controller.rb
  app/decorators/article_decorator.rb
  app/javascript/article-form/components/Preview.jsx
  app/javascript/packs/articlePage.jsx
  app/views/articles/_sticky_nav.html.erb
  app/views/articles/show.html.erb
  cypress/integration/seededFlows/articleFlows/previewProfile.spec.js
  cypress/integration/seededFlows/publishingFlows/postOptions.spec.js
  spec/requests/stories_show_spec.rb
  spec/system/user_uses_the_editor_spec.rb
Labels: PR: reviewed-approved, area: articles, tech: frontend

#14868 Rubocop fixes
  .rubocop.yml
  Gemfile
  app/helpers/display_ad_helper.rb
  app/models/display_ad.rb
  package.json
  spec/helpers/display_ad_helper_spec.rb
  spec/liquid_tags/codesandbox_tag_spec.rb
  spec/models/organization_spec.rb
  spec/requests/pages_spec.rb
  spec/requests/stories/tagged_articles_spec.rb
  spec/requests/stories_index_spec.rb
  spec/services/html/parser_spec.rb
  spec/system/homepage/user_visits_homepage_articles_spec.rb
  spec/system/user/view_user_comments_spec.rb
  spec/workers/github_repos/repo_sync_worker_spec.rb
  spec/workers/notifications/mention_worker_spec.rb
  spec/workers/notifications/milestone_worker_spec.rb
Labels: PR: partially-approved

#14832 Remove `check_box` type from profile fields
  app/models/profile.rb
  app/models/profile_field.rb
  lib/data_update_scripts/20210928044418_remove_checkbox_type_from_profile_fields.rb
  spec/models/profile_spec.rb
  spec/services/profile_fields/add_spec.rb
Labels: PR: partially-approved

#14857 Add recent resource sitemap endpoint for posts
  app/controllers/sitemaps_controller.rb
  spec/requests/sitemaps_spec.rb
Labels: PR: partially-approved
