Repository forem/forem, pull requests merged in 2021-05, with the labels that each got.

#13595 [15 minute fix] Remove secondary logo
  app/helpers/application_helper.rb
  app/lib/constants/site_config.rb
  app/models/site_config.rb
  app/views/admin/configs/show.html.erb
  app/views/layouts/_signup_modal.html.erb
  app/views/onboardings/_task_card.html.erb
  app/views/onboardings/show.html.erb
  app/views/stories/_sign_in_invitation.html.erb
  lib/data_update_scripts/20210430043750_remove_site_config_secondary_logo.rb
  spec/models/site_config_spec.rb
  spec/requests/admin/configs_spec.rb
  spec/requests/onboardings_spec.rb
Labels: PR: partially-approved

#13536 Improve keyboard accessibility of comment rate limit and error modals
  app/assets/javascripts/utilities/showLoginModal.js
  app/assets/javascripts/utilities/showUserAlertModal.js
  app/javascript/crayons/Modal/Modal.jsx
  app/javascript/crayons/Modal/__tests__/Modal.test.jsx
  app/javascript/packs/base.jsx
  cypress/integration/articleFlows/commentOnArticle.spec.js
Labels: PR: partially-approved

#13607 Improve bash info for windows user
  bin/container-setup
Labels: PR: partially-approved

#13609 [15 min fix] Add a step to remove flake in a cypress test
  cypress/integration/loginFlows/userLogout.spec.js
Labels: PR: partially-approved

#13579 RFC 50 - Remove old admin routes and related code
  app/helpers/admin_helper.rb
  app/views/admin/badges/index.html.erb
  app/views/layouts/admin.html.erb
  config/routes.rb
  config/routes/admin.rb
  config/routes/current_admin.rb
  cypress/integration/adminFlows/config/authenticationSection.spec.js
  cypress/integration/adminFlows/config/campaignSection.spec.js
  cypress/integration/adminFlows/config/communitySection.spec.js
  cypress/integration/adminFlows/config/emailDigestFrequencySection.js
  cypress/integration/adminFlows/config/getStartedSection.js
  cypress/integration/adminFlows/config/mascotSection.js
  cypress/integration/adminFlows/config/rateLimitSection.js
  cypress/integration/adminFlows/config/userExperienceSection.js
  cypress/integration/adminFlows/navigationLinks/navigationLinks.spec.js
  spec/requests/admin/nested_sidebar_spec.rb
  spec/requests/admin/overview_spec.rb
  spec/requests/admin/sidebar_spec.rb
Labels: PR: partially-approved

#13252 Remove references to social link profile fields
  app/controllers/stories_controller.rb
  app/helpers/profile_helper.rb
  app/models/profile.rb
  app/policies/user_policy.rb
  app/views/users/_profile.html.erb
  app/views/users/show.html.erb
  lib/data/dev_profile_fields.csv
  spec/factories/profiles.rb
  spec/helpers/profile_helper_spec.rb
  spec/lib/data_update_scripts/create_profile_fields_spec.rb
  spec/lib/data_update_scripts/fix_profile_field_edge_cases_spec.rb
  spec/lib/data_update_scripts/set_proper_display_area_for_profile_fields_spec.rb
  spec/requests/user/user_profile_spec.rb
  spec/support/omniauth_helpers.rb
  spec/system/authentication/user_logs_in_with_facebook_spec.rb
  spec/system/authentication/user_logs_in_with_github_spec.rb
  spec/system/authentication/user_logs_in_with_twitter_spec.rb
Labels: PR: partially-approved

#13184 Fixing dom structure of Tags to follow
  app/javascript/onboarding/components/FollowTags.jsx
Labels: PR: partially-approved, include in changelog

#13630 Add no-op Search::IndexWorker
  app/workers/search/index_worker.rb
Labels: PR: reviewed-approved

#13620 [15 min fix] fix accessible names of sign up options
  app/views/shared/authentication/_providers_registration_form.html.erb
Labels: PR: partially-approved, merge by any core

#13637 `deep_dup` the admin menu before modifying its content
  app/models/admin_menu.rb
Labels: PR: reviewed-approved

#13542 Convert SMTP configs into environments vars
  .env_sample
  config/environments/development.rb
  config/environments/production.rb
  docs/backend/emails.md
Labels: PR: unreviewed

#13633 Specify body and title of listings that shouldn't match a term
  spec/services/search/postgres/listing_spec.rb
Labels: PR: partially-approved

#13638 Disable Cypress's video feature
  cypress.json
Labels: PR: partially-approved

#13639 [15 minute fix] Rename profile header partial
  app/views/organizations/_header.html.erb
  app/views/organizations/show.html.erb
Labels: PR: partially-approved

#13614 Retain registration form data on failed submission
  app/views/shared/authentication/_email_registration_form.html.erb
  cypress/integration/registrationFlows/emailRegistration.spec.js
  spec/support/seeds/seeds_e2e.rb
Labels: PR: partially-approved

#13183 Add prefer object destructuring lint rule
  app/javascript/.eslintrc.js
Labels: PR: reviewed-approved, area: developer experience, tech: javascript

#13640 Cleanup unused DataUpdateScripts
  lib/data_update_scripts/20200214171607_index_tags_to_elasticsearch.rb
  lib/data_update_scripts/20200217131245_re_index_existing_articles_with_approved.rb
  lib/data_update_scripts/20200217215802_index_listings_to_elasticsearch.rb
  lib/data_update_scripts/20200218195023_index_chat_channel_memberships_to_elasticsearch.rb
  lib/data_update_scripts/20200225114328_update_tags_social_preview_templates.rb
  lib/data_update_scripts/20200305201627_index_users_to_elasticsearch.rb
  lib/data_update_scripts/20200326145114_re_index_feed_content_to_elasticsearch.rb
  lib/data_update_scripts/20200406213152_re_index_users_to_elasticsearch.rb
  lib/data_update_scripts/20200410152018_resync_elasticsearch_documents.rb
  lib/data_update_scripts/20200415200651_index_reading_list_reactions.rb
  lib/data_update_scripts/20200518173504_update_public_reactions_count_from_positive_reactions_count.rb
  lib/data_update_scripts/20200519142908_re_index_feed_content_and_users_to_elasticsearch.rb
  lib/data_update_scripts/20200729120730_remove_orphaned_ahoy_events.rb
  lib/data_update_scripts/20200803142830_reindex_listing_search_column.rb
  lib/data_update_scripts/20200805171911_clean_up_language_settings.rb
  lib/data_update_scripts/20200819025131_migrate_profile_data.rb
  lib/data_update_scripts/20200901194251_reindex_reading_list_reactions.rb
  lib/data_update_scripts/20200904132553_remove_draft_articles_with_duplicate_feed_source_url.rb
  lib/data_update_scripts/20200911045602_reindex_articles_with_videos.rb
  lib/data_update_scripts/20200914042434_reindex_users_for_profiles.rb
  lib/data_update_scripts/20200924140813_remove_reaction_index_by_name.rb
  lib/data_update_scripts/20201013205258_resave_articles_and_comments_for_imgproxy.rb
  lib/data_update_scripts/20201014184856_resave_users_for_imgproxy.rb
  lib/data_update_scripts/20201019163242_resave_articles_and_comments_for_imgproxy.rb
  lib/data_update_scripts/20201020215535_resave_articles_and_comments_for_imgproxy.rb
  lib/data_update_scripts/20201030134117_reindex_users_for_username_search.rb
  lib/data_update_scripts/20201103050112_prepare_for_profile_column_drop.rb
  lib/data_update_scripts/20201210163704_set_contact_email_address.rb
  lib/data_update_scripts/20201217184442_append_community_to_community_name.rb
  lib/data_update_scripts/20201218173445_remove_collective_noun_from_config.rb
  lib/data_update_scripts/20210104170542_resave_articles_for_code_snippet_fullscreen_icon.rb
  lib/data_update_scripts/20210118194138_resync_unpublished_articles_comments_elasticsearch_document.rb
  lib/data_update_scripts/20210203104631_add_single_resource_admin_role_to_users_with_tech_admin.rb
  lib/data_update_scripts/20210218041143_backfill_usernames.rb
  lib/data_update_scripts/20210503202046_remove_unused_data_update_scripts.rb
  spec/lib/data_update_scripts/remove_unused_data_update_scripts_spec.rb
Labels: PR: partially-approved

#13636 Add M1 architecture to Gemfile.lock
  Gemfile.lock
Labels: PR: reviewed-approved

#13646 [Hot Fix] Add safe navigation operator to stop 500 errors
  app/helpers/profile_helper.rb
  spec/factories/users.rb
  spec/helpers/profile_helper_spec.rb
Labels: PR: partially-approved

#10895 Refactoring help component (and fragmenting it too)
  app/javascript/article-form/components/Help.jsx
  app/javascript/article-form/components/Help/ArticleFormTitle.jsx
  app/javascript/article-form/components/Help/BasicEditor.jsx
  app/javascript/article-form/components/Help/EditorFormattingHelp.jsx
  app/javascript/article-form/components/Help/TagInput.jsx
  app/javascript/article-form/components/Help/index.jsx
Labels: PR: partially-approved

#13645 Cleanup search classes and serializers
  app/controllers/search_controller.rb
  app/serializers/search/comment_serializer.rb
  app/serializers/search/listing_result_serializer.rb
  app/serializers/search/listing_serializer.rb
  app/serializers/search/podcast_episode_serializer.rb
  app/serializers/search/postgres_comment_serializer.rb
  app/serializers/search/postgres_podcast_episode_serializer.rb
  app/serializers/search/simple_user_serializer.rb
  app/serializers/search/username_serializer.rb
  app/services/search/article.rb
  app/services/search/chat_channel_membership.rb
  app/services/search/comment.rb
  app/services/search/listing.rb
  app/services/search/podcast_episode.rb
  app/services/search/postgres/article.rb
  app/services/search/postgres/chat_channel_membership.rb
  app/services/search/postgres/comment.rb
  app/services/search/postgres/listing.rb
  app/services/search/postgres/podcast_episode.rb
  app/services/search/postgres/reading_list.rb
  app/services/search/postgres/tag.rb
  app/services/search/postgres/user.rb
  app/services/search/postgres/username.rb
  app/services/search/reading_list.rb
  app/services/search/tag.rb
  app/services/search/user.rb
  app/services/search/username.rb
  spec/initializers/rack/attack_spec.rb
  spec/requests/search_spec.rb
  spec/serializers/search/chat_channel_membership_serializer_spec.rb
  spec/serializers/search/comment_serializer_spec.rb
  spec/serializers/search/listing_author_serializer_spec.rb
  spec/serializers/search/listing_serializer_spec.rb
  spec/serializers/search/nested_user_serializer_spec.rb
  spec/serializers/search/podcast_episode_serializer_spec.rb
  spec/serializers/search/reading_list_article_serializer_spec.rb
  spec/serializers/search/simple_user_serializer_spec.rb
  spec/serializers/search/tag_serializer_spec.rb
  spec/services/search/article_spec.rb
  spec/services/search/chat_channel_membership_spec.rb
  spec/services/search/comment_spec.rb
  spec/services/search/listing_spec.rb
  spec/services/search/podcast_episode_spec.rb
  spec/services/search/reading_list_spec.rb
  spec/services/search/tag_spec.rb
  spec/services/search/user_spec.rb
  spec/services/search/username_spec.rb
Labels: PR: partially-approved

#13657 [15-min-fix] Remove data-paths and use inline ERB in the js instead
  app/views/admin/feedback_messages/_feedback_message.html.erb
Labels: PR: partially-approved

#13588 Replace Pusher Beams with Rpush PN delivery ✂️ ✂️
  .env_sample
  Gemfile
  Gemfile.lock
  app/models/admin_menu.rb
  app/services/notifications/new_comment/send.rb
  app/services/push_notifications/send.rb
  app/views/admin/consumer_apps/index.html.erb
  config/initializers/pusher.rb
  config/routes.rb
  config/routes/admin.rb
  docs/backend/push-notifications.md
  docs/backend/pusher.md
  docs/backend/readme.md
  spec/requests/devices_spec.rb
  spec/routing/devices_routes_spec.rb
  spec/services/notifications/new_comment/send_spec.rb
  spec/services/push_notifications/send_spec.rb
  vendor/cache/pusher-push-notifications-2.0.1.gem
Labels: PR: partially-approved

#13635 Auto generate profile image for email signups
  app/controllers/registrations_controller.rb
  app/views/shared/authentication/_email_registration_form.html.erb
  cypress/integration/registrationFlows/emailRegistration.spec.js
  spec/requests/registrations_spec.rb
  spec/system/authentication/user_logs_in_with_email_spec.rb
Labels: PR: partially-approved, actual_size:XS, area: new user experience, merge by any core

#13648 Handle GitHub "Repository access blocked" error
  app/workers/github_repos/repo_sync_worker.rb
Labels: PR: reviewed-approved

#13658 [15-min-fix] Uncomment test in the nested sidebar spec
  spec/requests/admin/nested_sidebar_spec.rb
Labels: PR: reviewed-approved

#13649 [15-min-fix] Remove badge slug field b/c auto-gen by title
  app/controllers/admin/badges_controller.rb
  app/views/admin/badges/edit.html.erb
  app/views/admin/badges/new.html.erb
  spec/requests/admin/badges_spec.rb
Labels: PR: unreviewed, merge by any core

#13671 [15-min-fix] Disabled flaky E2E comment test
  cypress/integration/articleFlows/commentOnArticle.spec.js
Labels: PR: partially-approved, merge by any core

#13669 Clear the cached settings before testing the rate limiter
  spec/requests/follows_create_spec.rb
Labels: PR: partially-approved

#13673 Fix invalid form during Creator onboarding.
  app/controllers/application_controller.rb
  spec/requests/registrations_spec.rb
Labels: PR: reviewed-approved

#13675 [15 Min Fix]: Bump Rails to 6.1.3.2
  Gemfile
  Gemfile.lock
  vendor/cache/actioncable-6.1.3.1.gem
  vendor/cache/actioncable-6.1.3.2.gem
  vendor/cache/actionmailbox-6.1.3.1.gem
  vendor/cache/actionmailbox-6.1.3.2.gem
  vendor/cache/actionmailer-6.1.3.1.gem
  vendor/cache/actionmailer-6.1.3.2.gem
  vendor/cache/actionpack-6.1.3.1.gem
  vendor/cache/actionpack-6.1.3.2.gem
  vendor/cache/actiontext-6.1.3.1.gem
  vendor/cache/actiontext-6.1.3.2.gem
  vendor/cache/actionview-6.1.3.1.gem
  vendor/cache/actionview-6.1.3.2.gem
  vendor/cache/activejob-6.1.3.1.gem
  vendor/cache/activejob-6.1.3.2.gem
  vendor/cache/activemodel-6.1.3.1.gem
  vendor/cache/activemodel-6.1.3.2.gem
  vendor/cache/activerecord-6.1.3.1.gem
  vendor/cache/activerecord-6.1.3.2.gem
  vendor/cache/activestorage-6.1.3.1.gem
  vendor/cache/activestorage-6.1.3.2.gem
  vendor/cache/activesupport-6.1.3.1.gem
  vendor/cache/activesupport-6.1.3.2.gem
  vendor/cache/rails-6.1.3.1.gem
  vendor/cache/rails-6.1.3.2.gem
  vendor/cache/railties-6.1.3.1.gem
  vendor/cache/railties-6.1.3.2.gem
Labels: PR: partially-approved

#13653 [15 minute fix] Add data_updates:status rake task
  lib/tasks/data_updates.rake
Labels: PR: unreviewed

#13674 [15 min fix] Fixed app code that was causing flaky E2E test
  app/assets/javascripts/initializers/initializeCommentDropdown.js
  cypress/integration/articleFlows/commentOnArticle.spec.js
Labels: PR: partially-approved, merge by any core, tech: javascript

#13623 Fix a bug with moderator dropdowns and add aria tags
  app/assets/stylesheets/views/mod-actions.scss
  app/javascript/actionsPanel/actionsPanel.js
  app/views/moderations/actions_panel.html.erb
Labels: PR: partially-approved

#13666 [15-min-fix] Set opacity-0 CSS utility class to 0.00001 for ChromeVox
  app/assets/stylesheets/config/_generator.scss
Labels: PR: unreviewed, merge by any core, type: accessibility

#13661 🐛 Fix new comment dropdown issue
  app/assets/javascripts/initializers/initializeCommentsPage.js.erb
Labels: PR: partially-approved

#13681 [15-min-fix] Remove/Update the last of the admin hardcoded paths
  docs/admin/admin-search.md
  docs/admin/readme.md
  docs/backend/auth-apple.md
  docs/backend/configuration.md
  docs/creators/configure-forem.md
  spec/requests/admin/invitations_spec.rb
  spec/requests/admin/permissions_spec.rb
Labels: PR: unreviewed

#13668 Edited the title on id="article-copy-link-input"
  app/views/articles/_actions.html.erb
Labels: PR: reviewed-approved

#13682 Clarify article link copy title
  app/views/articles/_actions.html.erb
Labels: PR: partially-approved

#13683 Fix svg path error in e2e seed navigation link svg icon
  spec/support/seeds/seeds_e2e.rb
Labels: PR: partially-approved

#13685 Remove inline comments and variable substitution from .env_sample
  .env_sample
Labels: PR: partially-approved

#13647 Have specs run without Redis and refactor ConsumerApp and Device
  .travis.yml
  Gemfile
  Gemfile.lock
  app/controllers/devices_controller.rb
  app/models/consumer_app.rb
  app/models/device.rb
  app/queries/consumer_apps/find_or_create_by_query.rb
  app/queries/consumer_apps/rpush_app_query.rb
  app/services/push_notifications/send.rb
  app/views/admin/consumer_apps/_form.html.erb
  app/views/admin/consumer_apps/index.html.erb
  config/initializers/rpush.rb
  spec/factories/consumer_apps.rb
  spec/factories/devices.rb
  spec/models/consumer_app_spec.rb
  spec/models/device_spec.rb
  spec/queries/consumer_apps/find_or_create_by_query_spec.rb
  spec/queries/consumer_apps/rpush_app_query_spec.rb
  spec/rails_helper.rb
  spec/requests/admin/consumer_apps_spec.rb
  spec/requests/devices_spec.rb
  spec/services/push_notifications/send_spec.rb
  spec/support/rpush_helpers.rb
  vendor/cache/fakeredis-0.8.0.gem
Labels: PR: partially-approved

#13660 Update format specifiers in readable_publish_date
  app/decorators/comment_decorator.rb
  app/decorators/podcast_episode_decorator.rb
  app/helpers/date_helper.rb
  app/models/article.rb
  app/models/comment.rb
  spec/decorators/podcast_episode_decorator_spec.rb
  spec/helpers/date_helper_spec.rb
  spec/models/article_spec.rb
  spec/models/comment_spec.rb
Labels: PR: partially-approved

#13659 Update the CSS of the badge page title
  app/views/badges/show.html.erb
Labels: PR: partially-approved

#13688 [15 min fix] Fixed broken share button on article page.
  app/assets/javascripts/initializers/initializeCommentDropdown.js
  cypress/integration/articleFlows/postSidebarActions.spec.js
Labels: PR: partially-approved, merge by any core

#13680 Updated replit url from repl.it to replit.com
  app/liquid_tags/replit_tag.rb
  app/views/pages/_editor_guide_text.html.erb
  app/views/pages/_editor_liquid_help.html.erb
Labels: PR: partially-approved

#13559 Accessibility enhancements to navigation tabs
  app/assets/stylesheets/components/tabs.scss
  app/assets/stylesheets/dashboard.scss
  app/javascript/analytics/dashboard.js
  app/javascript/article-form/components/Tabs.jsx
  app/javascript/crayons/navigation/NavigationTabs/__stories__/navigation-tab.md
  app/javascript/crayons/navigation/NavigationTabs/__stories__/navigationTab.html.stories.jsx
  app/views/articles/_search.html.erb
  app/views/articles/_v2_form.html.erb
  app/views/articles/index.html.erb
  app/views/articles/search.html.erb
  app/views/articles/tag_index.html.erb
  app/views/moderations/_mod_sidebar_left.html.erb
  app/views/notifications/_nav_menu.html.erb
  app/views/shared/_stats.html.erb
  cypress/integration/analyticsFlows/analyticsNavigation.spec.js
  cypress/integration/homeFeedFlows/feedNavigation.spec.js
  cypress/integration/moderationFlows/modNavigation.spec.js
  cypress/integration/notificationsFlows/notificationNavigation.spec.js
  cypress/integration/publishingFlows/previewPost.spec.js
  cypress/integration/searchFlows/searchTimeFiltering.spec.js
  cypress/integration/tagsFlows/tagIndexNavigation.spec.js
  spec/support/seeds/seeds_e2e.rb
Labels: PR: unreviewed

#13627 Fixing preview button text in comment section
  app/assets/javascripts/initializers/initializeCommentsPage.js.erb
Labels: PR: partially-approved

#13686 Make comment box shrink on submit
  app/assets/javascripts/initializers/initializeCommentsPage.js.erb
Labels: PR: partially-approved

#13710 [15 min fix] Stop adding a false class in editor tabs
  app/javascript/article-form/components/Tabs.jsx
Labels: PR: reviewed-approved

#13610 Organizations delete optimizations and refactoring
  app/models/organization.rb
  app/services/organizations/delete.rb
  spec/models/organization_spec.rb
  spec/services/organizations/delete_spec.rb
Labels: PR: partially-approved

#13642 Remove mascot footer image
  app/controllers/admin/settings/mascots_controller.rb
  app/controllers/chat_channels_controller.rb
  app/controllers/comments_controller.rb
  app/controllers/search_controller.rb
  app/lib/constants/settings/mascot.rb
  app/lib/constants/site_config.rb
  app/models/article.rb
  app/models/comment.rb
  app/models/reaction.rb
  app/models/settings/mascot.rb
  app/models/site_config.rb
  app/models/user.rb
  app/services/authentication/providers/apple.rb
  app/services/users/create_mascot_account.rb
  app/views/admin/configs/show.html.erb
  app/views/admin/feedback_messages/_abuse_reports.html.erb
  app/views/comments/_comment_avatar.html.erb
  app/views/comments/deleted_commentable_comment.html.erb
  app/views/dashboards/show.html.erb
  app/views/layouts/_footer.html.erb
  config/routes/admin.rb
  cypress/integration/adminFlows/config/mascotSection.js
  lib/data_update_scripts/20210420050256_move_mascot_settings.rb
  lib/data_update_scripts/20210504060704_move_mascot_settings_backto_site_config.rb
  spec/lib/data_update_scripts/move_mascot_settings_spec.rb
  spec/models/article_spec.rb
  spec/models/comment_spec.rb
  spec/models/reaction_spec.rb
  spec/models/site_config_spec.rb
  spec/models/user_spec.rb
  spec/requests/admin/configs_spec.rb
  spec/requests/comments_create_spec.rb
  spec/requests/registrations_spec.rb
  spec/services/users/create_mascot_account_spec.rb
  spec/views/dashboards/show.html.erb_spec.rb
Labels: PR: reviewed-approved, merge by any core

#13720 Sanitize tag urls
  app/lib/url.rb
  app/views/admin/tags/edit.html.erb
  app/views/articles/_single_story.html.erb
  app/views/dashboards/following_tags.html.erb
  app/views/tags/_liquid.html.erb
  app/views/tags/edit.html.erb
  app/views/tags/index.html.erb
  spec/lib/url_spec.rb
Labels: PR: unreviewed

#13732 Pass a FlareTag instead of a string to URL.tag
  app/views/articles/_single_story.html.erb
Labels: PR: reviewed-approved

#13724 Add composite index to articles hotness_score and comments_count
  db/migrate/20210511073505_add_index_on_articles_hotness_score_comments_count.rb
  db/schema.rb
Labels: PR: partially-approved

#13733 Hide the correct email PII on Blazer
  config/initializers/hypershield.rb
Labels: PR: reviewed-approved

#13723 Add documentation for Profiles::Update
  app/services/profiles/update.rb
Labels: PR: partially-approved

#13709 Update GitPod setup description
  docs/installation/gitpod.md
Labels: PR: partially-approved

#13727 add accessibility section to editor guide
  app/views/pages/_editor_guide_text.html.erb
Labels: PR: unreviewed

#13367 Expand @-mention functionality to posts
  app/decorators/mention_decorator.rb
  app/mailers/notify_mailer.rb
  app/models/article.rb
  app/models/notification.rb
  app/services/articles/creator.rb
  app/services/articles/updater.rb
  app/services/mentions/create_all.rb
  app/services/notifications/new_mention/send.rb
  app/services/notifications/notifiable_action/send.rb
  app/views/mailers/notify_mailer/new_mention_email.html.erb
  app/views/notifications/_article.html.erb
  app/views/notifications/_mention.html.erb
  app/views/notifications/shared/_article_preview.html.erb
  app/workers/mentions/create_all_worker.rb
  spec/decorators/mention_decorator_spec.rb
  spec/mailers/notify_mailer_spec.rb
  spec/mailers/previews/notify_mailer_preview.rb
  spec/models/article_spec.rb
  spec/models/notification_spec.rb
  spec/requests/notifications_spec.rb
  spec/services/articles/creator_spec.rb
  spec/services/articles/updater_spec.rb
  spec/services/mentions/create_all_spec.rb
  spec/services/notifications/new_mention/send_spec.rb
  spec/services/notifications/notifiable_action/send_spec.rb
  spec/workers/mentions/send_email_notification_worker_spec.rb
Labels: PR: partially-approved

#13736 Replace MAX_USER_MENTIONS with Settings::RateLimit.mention_creation
  app/helpers/rate_limit_checker_helper.rb
  app/models/article.rb
  app/models/comment.rb
  app/models/settings/rate_limit.rb
  app/services/edge_cache/bust/nginx.rb
  app/services/rate_limit_checker.rb
  app/views/devise/registrations/new.html.erb
  app/views/shared/authentication/_email_registration_form.html.erb
  spec/models/article_spec.rb
  spec/models/comment_spec.rb
  spec/requests/admin/configs_spec.rb
  spec/system/onboardings/user_completes_onboarding_spec.rb
Labels: PR: partially-approved

#13300 Fix layout shift on active `crayons-tabs` change.
  app/assets/stylesheets/components/tabs.scss
  app/assets/stylesheets/dashboard.scss
  app/javascript/article-form/components/Tabs.jsx
  app/javascript/crayons/navigation/NavigationTabs/__stories__/navigation-tab.md
  app/javascript/crayons/navigation/NavigationTabs/__stories__/navigationTab.html.stories.jsx
  app/views/admin/shared/_tabbed_navbar.html.erb
  app/views/admin/tags/index.html.erb
  app/views/articles/_v2_form.html.erb
  app/views/articles/index.html.erb
  app/views/articles/search.html.erb
  app/views/articles/tag_index.html.erb
  app/views/moderations/_mod_sidebar_left.html.erb
  app/views/notifications/_nav_menu.html.erb
  app/views/shared/_stats.html.erb
Labels: PR: partially-approved

#13729 Expose aasa for non-private Forems
  app/controllers/application_controller.rb
  app/controllers/deep_links_controller.rb
  spec/requests/universal_links_spec.rb
Labels: PR: unreviewed

#13717 Auto-subscribe to comments on articles from feed
  app/services/feeds/import.rb
  spec/services/feeds/import_spec.rb
Labels: PR: partially-approved

#13749 [15 Min Fix]: Remove any preexisting mention notifications when article is unpublished
  app/services/articles/updater.rb
  spec/services/articles/updater_spec.rb
Labels: PR: partially-approved

#13737 Remove `settings_mascots` table
  db/migrate/20210512025422_remove_settings_mascots_table.rb
  db/schema.rb
  lib/data_update_scripts/20210504060704_move_mascot_settings_backto_site_config.rb
  lib/data_update_scripts/20210512030719_mark_mascot_setting_dus_as_obsolete.rb
Labels: PR: partially-approved

#13739 Fix wrong `SiteConfig` mentions
  app/helpers/rate_limit_checker_helper.rb
  app/lib/constants/settings/rate_limit.rb
Labels: PR: partially-approved

#13756 [15 min fix] Update Publishing from RSS guide with correct instructions
  app/views/pages/_publishing_from_rss_guide_text.html.erb
  app/views/pages/publishing_from_rss_guide.html.erb
  app/views/users/_publishing_from_rss.html.erb
Labels: PR: unreviewed

#13752 Don't show articles from blocked users in the feed
  app/javascript/contentDisplayPolicy/hideBlockedContent.js
  app/javascript/profileDropdown/blockButton.js
  spec/services/articles/feeds/basic_spec.rb
  spec/services/articles/feeds/large_forem_experimental_spec.rb
Labels: PR: partially-approved, merge by any core

#13760 Change article factory to include a flare tag "discuss"
  spec/factories/articles.rb
  spec/services/users/suggest_recent_spec.rb
Labels: PR: partially-approved

#13758 [Travis] Only cache vendor/bundle and node_modules
  .travis.yml
Labels: PR: partially-approved

#13650 Allow sign up without email smtp config
  app/controllers/registrations_controller.rb
  app/models/site_config.rb
  app/models/user.rb
  config/environments/production.rb
  spec/system/authentication/user_logs_in_with_email_spec.rb
Labels: PR: partially-approved

#13765 [15 min fix] Enable and display test-prof report at the end of a test run
  spec/rails_helper.rb
Labels: PR: reviewed-approved

#13769 Remove Vaidehi from Forem Core Team
  README.md
Labels: PR: reviewed-approved

#13771 Fix typo: 'upsteam' -> 'upstream'
  docs/getting-started/workflow.md
Labels: PR: partially-approved

#13774 [15-minute fix] Remove mentions of creators.forem.com
  app/views/admin/overview/index.html.erb
Labels: PR: partially-approved

#13770 Add .yarnclean
  .yarnclean
Labels: PR: partially-approved

#13632 Remove no-op Search::IndexWorker
  app/workers/search/index_worker.rb
Labels: PR: partially-approved, merge by any core

#13694 Fix "Unable to load Comment Subscription component"
  app/liquid_tags/user_subscription_tag.rb
Labels: PR: partially-approved

#13773 ✂✂✂ Remove `shop_url` from `SiteConfig` ✂✂✂
  app/lib/constants/site_config.rb
  app/models/site_config.rb
  app/views/admin/configs/show.html.erb
  app/views/pages/_privacy_text.html.erb
  config/routes.rb
  lib/data_update_scripts/20210517091342_remove_shop_url_from_site_config.rb
  spec/requests/admin/configs_spec.rb
  spec/requests/pages_spec.rb
  spec/routing/all_routes_spec.rb
Labels: PR: partially-approved, include in changelog

#13738 Clean up `SiteConfig`
  app/controllers/admin/welcome_controller.rb
  app/controllers/stories_controller.rb
  app/errors/authentication/errors.rb
  app/mailers/application_mailer.rb
  app/mailers/devise_mailer.rb
  app/mailers/notify_mailer.rb
  app/models/article.rb
  app/models/comment.rb
  app/models/device.rb
  app/models/site_config.rb
  app/views/admin/consumer_apps/index.html.erb
  app/views/devise/invitations/edit.html.erb
  app/views/layouts/_signup_modal.html.erb
  app/views/moderations/_mod_sidebar_right.html.erb
  app/views/shared/_auth_widget.html.erb
  app/views/shared/_authentication_description.html.erb
  lib/data_update_scripts/20201228194641_append_collective_noun_to_community_name.rb
  lib/data_update_scripts/20201229230456_remove_collective_noun_from_site_config.rb
  lib/data_update_scripts/20210316091354_move_authentication_settings.rb
  lib/data_update_scripts/20210405034117_move_campaign_settings.rb
  lib/data_update_scripts/20210414060839_move_rate_limit_settings.rb
  lib/data_update_scripts/20210419063311_move_community_settings.rb
  lib/data_update_scripts/20210426023014_move_user_experience_settings.rb
  lib/data_update_scripts/20210512032437_remove_settings_data_update_scripts.rb
  lib/data_update_scripts/20210512033821_clean_up_site_config.rb
  spec/decorators/user_decorator_spec.rb
  spec/helpers/feedback_messages_helper_spec.rb
  spec/lib/data_update_scripts/append_collective_noun_to_community_name_spec.rb
  spec/lib/data_update_scripts/move_community_settings_spec.rb
  spec/lib/data_update_scripts/move_rate_limit_settings_spec.rb
  spec/lib/data_update_scripts/move_user_experience_settings_spec.rb
  spec/lib/data_update_scripts/remove_collective_noun_from_site_config_spec.rb
  spec/mailers/devise_mailer_spec.rb
  spec/mailers/digest_mailer_spec.rb
  spec/mailers/notify_mailer_spec.rb
  spec/mailers/previews/notify_mailer_preview.rb
  spec/mailers/verification_mailer_spec.rb
  spec/models/article_spec.rb
  spec/models/comment_spec.rb
  spec/models/settings/community_spec.rb
  spec/models/settings/user_experience_spec.rb
  spec/models/site_config_spec.rb
  spec/requests/admin/users_spec.rb
  spec/requests/api/v0/admin/configs_spec.rb
  spec/requests/articles/articles_show_spec.rb
  spec/requests/open_search_spec.rb
  spec/requests/pages_spec.rb
  spec/requests/user/user_settings_spec.rb
  spec/system/admin/admin_manages_configuration_spec.rb
  spec/system/articles/user_visits_an_article_spec.rb
  spec/system/notifications/notifications_page_spec.rb
  spec/system/organization/user_views_an_organization_spec.rb
  spec/system/user/view_user_index_spec.rb
  spec/views/email_subscriptions/unsubscribe.html.erb_spec.rb
  spec/views/layouts/signup_modal.html.erb_spec.rb
Labels: PR: reviewed-approved

#13767 [15 min fix] Fallback to the image URL if Cloudinary/Imgproxy are not configured
  .env_sample
  app/services/images/optimizer.rb
  config/initializers/cloudinary.rb
  spec/helpers/application_helper_spec.rb
  spec/helpers/social_image_helper_spec.rb
  spec/models/html_variant_spec.rb
  spec/models/message_spec.rb
  spec/models/podcast_episode_spec.rb
  spec/services/html/parser_spec.rb
  spec/services/images/generate_social_image_spec.rb
  spec/services/images/optimizer_spec.rb
  spec/services/images/profile_spec.rb
  spec/services/markdown_processor/parser_spec.rb
  spec/support/initializers/image_processing.rb
  spec/system/user_uses_the_editor_spec.rb
  spec/view_objects/cloud_cover_url_spec.rb
Labels: PR: partially-approved

#13803 Update `rbenv-doctor` location in docs
  docs/installation/windows.md
Labels: PR: partially-approved

#13757 Fix UI showing "Following" after unfollowing a user
  app/controllers/follows_controller.rb
  app/services/follows/delete_cached.rb
  cypress/integration/profileFlows/followUser.spec.js
Labels: PR: unreviewed

#13794 #13759 : hide content in print mode
  app/views/articles/_actions.html.erb
  app/views/articles/_full_comment_area.html.erb
  app/views/articles/_sticky_nav.html.erb
  app/views/articles/show.html.erb
  app/views/comments/_comment_footer.html.erb
  app/views/comments/_form.html.erb
Labels: PR: partially-approved

#13798 Add error handling to clipboard promise - post editor
  app/assets/javascripts/initializers/runtime.js
  app/javascript/article-form/components/ImageUploader.jsx
Labels: PR: unreviewed

#13793 [15 min fix] Fix some autoloading deprecation warnings
  app/lib/api_constraints.rb
  app/lib/forem_stats_drivers/datadog_driver.rb
  app/lib/middlewares/set_cookie_domain.rb
  app/lib/middlewares/set_time_zone.rb
  app/middlewares/set_cookie_domain.rb
  app/middlewares/set_time_zone.rb
  config/application.rb
  config/environments/test.rb
  config/initializers/honeybadger.rb
  config/initializers/middlewares.rb
  spec/initializers/honeybadger_spec.rb
Labels: PR: partially-approved

#13821 Move print-hidden to a class attribute
  app/views/articles/show.html.erb
Labels: PR: partially-approved

#13457 Extract tag stories to tag articles controller
  app/controllers/stories/tagged_articles_controller.rb
  app/controllers/stories_controller.rb
  app/views/stories/tagged_articles/_main_feed.html.erb
  app/views/stories/tagged_articles/_meta.html.erb
  app/views/stories/tagged_articles/_sidebar.html.erb
  app/views/stories/tagged_articles/_sidebar_additional.html.erb
  app/views/stories/tagged_articles/index.html.erb
  config/routes.rb
  spec/initializers/rack/attack_spec.rb
  spec/requests/stories/tagged_articles_spec.rb
  spec/requests/stories_index_spec.rb
Labels: PR: partially-approved

#13390 Data Migration Script for users_settings and users_notification_settings
  db/migrate/20210419171609_remove_user_id_index_from_users_settings.rb
  db/migrate/20210419171746_add_unique_user_id_index_to_users_settings.rb
  db/migrate/20210419174909_remove_user_id_index_from_users_notification_settings.rb
  db/migrate/20210419174931_add_unique_user_id_index_to_users_notification_settings.rb
  db/schema.rb
  lib/data_update_scripts/20210423155327_migrate_relevant_fields_from_users_to_users_settings.rb
  lib/data_update_scripts/20210503174302_migrate_relevant_fields_from_users_to_users_notification_settings.rb
  spec/lib/data_update_scripts/migrate_relevant_fields_from_users_to_users_notification_settings_spec.rb
  spec/lib/data_update_scripts/migrate_relevant_fields_from_users_to_users_settings_spec.rb
Labels: PR: partially-approved

#13810 [15-min-fix] Add option for triple tildes for fenced codeblocks
  app/services/markdown_processor/parser.rb
  spec/services/markdown_processor/parser_spec.rb
Labels: PR: partially-approved

#13813 [15 minute fix] Fix accessibility concerns in settings UI
  app/views/layouts/_footer.html.erb
  app/views/shared/_logo_design.html.erb
  app/views/users/_account.html.erb
  app/views/users/_account_set_password.html.erb
  app/views/users/_extensions.html.erb
  app/views/users/_org_admin.html.erb
  app/views/users/_org_member.html.erb
  app/views/users/_org_non_member.html.erb
  app/views/users/_publishing_from_rss.html.erb
  app/views/users/edit.html.erb
Labels: PR: unreviewed

#13799 Show correct number in series truncation.
  app/views/articles/_collection.html.erb
  spec/factories/collections.rb
  spec/requests/collections_spec.rb
Labels: PR: partially-approved

#13792 Update docker-compose.yml to use localhost as app domain
  docker-compose.yml
Labels: PR: partially-approved

#13838 Disable cache while seeding to fix "invalid category error"
  db/seeds.rb
Labels: PR: reviewed-approved

#13820 🚑 Quick fix prevent grammarly from running on chromium based browsers
  app/javascript/article-form/components/Title.jsx
  app/javascript/chat/compose.jsx
  app/javascript/crayons/MentionAutocompleteTextArea/MentionAutocompleteTextArea.jsx
  app/javascript/crayons/MentionAutocompleteTextArea/__tests__/__snapshots__/MentionAutocompleteTextArea.test.jsx.snap
Labels: PR: partially-approved

#13837 Remove IBM openapi-validator
  .validaterc
  package.json
  yarn.lock
Labels: PR: unreviewed, area: api-v0

#13847 [15 minute fix] Highlight "Posts" tab by default in search
  app/views/articles/_search.html.erb
Labels: PR: reviewed-approved

#13855 Rename WRITE A POST to CREATE POST
  app/javascript/article-form/components/PageTitle.jsx
  app/javascript/article-form/components/Title.jsx
  app/views/articles/_v2_form.html.erb
  app/views/layouts/_footer.html.erb
  app/views/layouts/_nav_menu.html.erb
  app/views/layouts/_top_bar.html.erb
  app/views/stories/tagged_articles/_sidebar.html.erb
  db/seeds.rb
  spec/factories/broadcasts.rb
Labels: PR: partially-approved

#13856 Put the user id filter inside the CTEs
  app/workers/migrate_user_notification_settings_worker.rb
  app/workers/migrate_user_settings_worker.rb
Labels: PR: partially-approved

#13860 Enable view annotation in development
  config/environments/development.rb
Labels: PR: partially-approved

#13850 When AWS_ID is the placeholder value, act as though AWS not setup
  .env_sample
Labels: PR: partially-approved

#13641 Migrate "static" profile fields into new columns
  app/controllers/profiles_controller.rb
  app/controllers/stories_controller.rb
  app/models/profile.rb
  app/validators/profile_validator.rb
  db/migrate/20210503205816_add_static_profile_fields_to_profile.rb
  db/schema.rb
  lib/data_update_scripts/20210503175027_move_summary_websiteurl_and_location_to_profile.rb
  spec/factories/profiles.rb
  spec/system/user/user_edits_profile_spec.rb
Labels: PR: partially-approved

#13862 Fix misnamed data update script
  lib/data_update_scripts/20210503175027_move_summary_website_url_and_location_to_profile.rb
Labels: PR: partially-approved

#13828 autofocus Skip Link on keyboard navigation
  app/assets/javascripts/base.js.erb
  app/assets/stylesheets/components/header.scss
Labels: PR: partially-approved

#13719 UsersSettings RFC: Code to Sync User Settings updates to new tables
  app/models/user.rb
  app/models/users/notification_setting.rb
  app/models/users/setting.rb
  spec/factories/users_setting.rb
  spec/lib/data_update_scripts/migrate_relevant_fields_from_users_to_users_notification_settings_spec.rb
  spec/lib/data_update_scripts/migrate_relevant_fields_from_users_to_users_settings_spec.rb
  spec/models/notification_spec.rb
  spec/models/users/setting_spec.rb
  spec/requests/user/user_settings_spec.rb
Labels: PR: unreviewed

#13435 Fix ChromeVox animated elements inaccessible
  app/assets/stylesheets/articles.scss
  app/assets/stylesheets/components/tooltips.scss
  app/assets/stylesheets/config/_variables.scss
  app/assets/stylesheets/scaffolds.scss
  app/assets/stylesheets/views/article-form.scss
  app/assets/stylesheets/views/article.scss
Labels: PR: partially-approved

#13869 Remove assets folder from .yarnclean
  .yarnclean
Labels: PR: reviewed-approved, merge by any core

#13864 Update visual styling of post action bar
  app/assets/stylesheets/views/article.scss
Labels: PR: partially-approved

#10888 Add loading=lazy to image tags
  app/assets/javascripts/utilities/buildArticleHTML.js
  app/javascript/listings/singleListing/AuthorInfo.jsx
  app/javascript/onboarding/components/FollowUsers.jsx
  app/views/admin/articles/_individual_article.html.erb
  app/views/admin/badge_achievements/index.html.erb
  app/views/admin/badges/index.html.erb
  app/views/admin/comments/index.html.erb
  app/views/admin/configs/show.html.erb
  app/views/admin/events/index.html.erb
  app/views/articles/_single_story.html.erb
  app/views/articles/_sticky_nav.html.erb
  app/views/badges/index.html.erb
  app/views/comments/_comment_avatar.html.erb
  app/views/comments/_form.html.erb
  app/views/dashboards/_dashboard_article_row.html.erb
  app/views/dashboards/followers.html.erb
  app/views/dashboards/following_organizations.html.erb
  app/views/dashboards/following_podcasts.html.erb
  app/views/dashboards/following_users.html.erb
  app/views/events/_event.html.erb
  app/views/layouts/_signup_modal.html.erb
  app/views/mailers/notify_mailer/new_badge_email.html.erb
  app/views/notifications/_follow.html.erb
  app/views/organizations/_sidebar_additional.html.erb
  app/views/pages/_editor_guide_text.html.erb
  app/views/pages/_editor_liquid_help.html.erb
  app/views/pages/_editor_markdown_help.html.erb
  app/views/pages/markdown_basics.html.erb
  app/views/podcast_episodes/_episodes_feed.html.erb
  app/views/stories/_sign_in_invitation.html.erb
  app/views/tags/index.html.erb
  app/views/users/_badges_area.html.erb
  app/views/users/_profile.html.erb
  app/views/users/_sidebar.html.erb
Labels: PR: partially-approved

#13863 Remove mentioning lint-openapi completely
  package.json
Labels: PR: partially-approved

#13867 Seeds: update correct CodingBlocks podcast feed URL
  db/seeds.rb
Labels: PR: partially-approved, merge by any core

#13662 Remove :runtime_banner feature flag
  app/assets/images/logo-forem-app.svg
  app/assets/javascripts/initializers/initializeRuntimeBanner.js
  app/assets/stylesheets/runtime-banner.scss
  app/assets/stylesheets/runtime.scss
  app/lib/url.rb
  app/views/layouts/application.html.erb
  lib/data_update_scripts/20210506052235_remove_runtime_banner_feature_flag.rb
  spec/lib/data_update_scripts/remove_runtime_banner_feature_flag_spec.rb
  spec/lib/url_spec.rb
  spec/requests/chat_channels_spec.rb
  spec/requests/registrations_spec.rb
  spec/system/user/user_edits_profile_spec.rb
Labels: PR: unreviewed
