Repository forem/forem, pull requests merged in 2022-03, with the labels that each got.

#16715 Favour fetch to XmlHttpRequest
  app/assets/javascripts/initializers/initializeBodyData.js
Labels: PR: partially-approved

#16717 Refactor markNotificationsAsRead to use getCsrfToken helper
  app/assets/javascripts/initializers/initNotifications.js
Labels: PR: partially-approved

#16618 Removing bootstrap: admin sidebar navigation
  app/assets/stylesheets/components/links.scss
  app/helpers/admin_helper.rb
  app/javascript/admin/__tests__/controllers/sidebar_controller.test.js
  app/lib/menu.rb
  app/models/admin_menu.rb
  app/views/admin/shared/_nested_sidebar.html.erb
  app/views/layouts/admin.html.erb
Labels: PR: unreviewed, tech: frontend

#16735 Ensuring VideoPolicy#new? is canonical
  app/policies/video_policy.rb
  app/views/dashboards/_actions.html.erb
  app/views/dashboards/_actions_mobile.html.erb
  spec/policies/video_policy_spec.rb
  spec/requests/videos_spec.rb
Labels: PR: partially-approved

#16733 Only init mod tools if we're still on article page
  app/javascript/packs/articleModerationTools.js
Labels: PR: partially-approved, merge by any core

#16743 handle getElementById failures in articlePage
  app/javascript/packs/articlePage.jsx
Labels: PR: partially-approved, merge by any core

#16732 Adding ArticlePolicy.scope_users_authorized_to_action
  app/policies/article_policy.rb
  spec/policies/article_policy_spec.rb
Labels: PR: partially-approved

#16238 Filter admin users by status
  app/assets/images/admin.svg
  app/javascript/actionsPanel/actionsPanel.js
  app/javascript/packs/admin/flashMessages.js
  app/views/admin/users/_menu.html.erb
  app/views/admin/users/index.html.erb
  app/views/moderations/actions_panel.html.erb
  spec/requests/admin/users_spec.rb
Labels: PR: unreviewed

#16758 Fix error in feed follow buttons where user name has apostrophe
  app/assets/javascripts/utilities/buildArticleHTML.js
  cypress/integration/seededFlows/homeFeedFlows/profilePreviewCards.spec.js
  spec/support/seeds/seeds_e2e.rb
Labels: PR: partially-approved, merge by any core

#16731 Use the Preact ColorPicker in creator onboarding
  app/javascript/admin/controllers/creator_settings_controller.js
  app/javascript/colorPickers/replaceTextInputWithColorPicker.jsx
  app/javascript/crayons/formElements/ColorPicker/ColorPicker.jsx
  app/javascript/crayons/formElements/ColorPicker/__tests__/ColorPicker.test.jsx
  app/javascript/crayons/formElements/ColorPicker/__tests__/__snapshots__/ColorPicker.test.jsx.snap
  app/javascript/packs/admin/creatorOnboarding.jsx
  app/javascript/packs/base.jsx
  app/javascript/packs/enhanceColorPickers.jsx
  app/javascript/utilities/color/accentCalculator.js
  app/views/admin/creator_settings/_form.html.erb
  app/views/admin/creator_settings/new.html.erb
  app/views/shared/_logo_design.html.erb
  app/views/tags/edit.html.erb
  app/views/users/_profile.html.erb
  cypress/integration/creatorOnboardingFlows/creatorSettings.spec.js
Labels: PR: partially-approved

#16771 Fix grid col overflow in right sidebar in safari
  app/assets/stylesheets/components/cards.scss
  app/views/sidebars/_homepage_content.html.erb
Labels: PR: partially-approved, merge by any core

#16755 Reword Copy within "Delete" Modal in Admin Member Detail View
  app/views/admin/users/show/profile/actions/_delete.html.erb
Labels: PR: unreviewed

#16779 Redirect appended /moderate and /admin to the same page (admin member view)
  app/controllers/stories_controller.rb
  config/routes.rb
  spec/requests/user/user_profile_spec.rb
Labels: PR: unreviewed

#16785 Fix flake in post mod tools spec
  cypress/integration/seededFlows/articleFlows/postModerationTools.spec.js
Labels: PR: partially-approved, merge by any core

#16777 Removing before_action in favor of explicity call
  app/controllers/videos_controller.rb
Labels: PR: partially-approved

#16773 Prevent hidden link skewing layout of home page
  app/assets/stylesheets/components/stories.scss
Labels: PR: partially-approved

#16778 Conditionally removing the "configure" editor
  app/views/users/_customization.html.erb
Labels: PR: partially-approved

#16766 Only fetch RSS of users who can create articles
  app/policies/article_policy.rb
  app/services/feeds/import.rb
  spec/policies/article_policy_spec.rb
  spec/services/feeds/import_spec.rb
Labels: PR: unreviewed

#16792 Fix broken email settings documentation link
  app/views/admin/invitations/new.html.erb
  spec/system/admin/admin_invites_user_spec.rb
Labels: PR: unreviewed, area: admin, PR: partially-approved, merge by any core

#16762 Ensuring the VideoPolicy adheres to article creation
  app/policies/application_policy.rb
  app/policies/article_policy.rb
  app/policies/video_policy.rb
  spec/policies/application_policy_spec.rb
  spec/policies/video_policy_spec.rb
Labels: PR: reviewed-approved

#16786 Adding ArticlePolicy#moderate?
  app/policies/article_policy.rb
  spec/policies/article_policy_spec.rb
Labels: PR: reviewed-approved

#16817 Disable admin brand color picker tests
  cypress/integration/creatorOnboardingFlows/creatorSettings.spec.js
Labels: PR: partially-approved

#16782 Avoid layout funkiness when non-breaking characters are used
  app/assets/stylesheets/base/main.scss
  app/assets/stylesheets/components/cards.scss
  app/assets/stylesheets/components/links.scss
  app/assets/stylesheets/components/profile-preview-card.scss
  app/assets/stylesheets/components/stories.scss
  app/assets/stylesheets/preact/onboarding-modal.scss
  app/assets/stylesheets/views/article.scss
  app/assets/stylesheets/views/dashboard.scss
  app/assets/stylesheets/views/listings.scss
  app/assets/stylesheets/views/signin.scss
  app/views/articles/_sidebar.html.erb
  app/views/articles/_sidebar_additional.html.erb
  app/views/articles/_sidebar_listings.html.erb
  app/views/comments/index.html.erb
  app/views/stories/_sign_in_invitation.html.erb
  app/views/users/_sidebar.html.erb
  app/views/users/show.html.erb
Labels: PR: partially-approved

#16768 Add new color picker to admin tag form
  app/views/admin/tags/_form.html.erb
  cypress/integration/seededFlows/adminFlows/tags/createATag.spec.js
Labels: PR: partially-approved

#16769 Add new color picker to user experience config
  app/helpers/application_helper.rb
  app/views/admin/settings/forms/_user_experience.html.erb
  cypress/integration/seededFlows/adminFlows/config/userExperienceSection.spec.js
Labels: PR: partially-approved

#16770 Implement new color picker in listings category form, cleanup old code
  app/assets/javascripts/initializePage.js
  app/assets/javascripts/initializers/initializeColorPicker.js
  app/assets/stylesheets/components/forms.scss
  app/views/admin/listing_categories/_form.html.erb
  cypress/integration/seededFlows/adminFlows/apps/editListingCategory.spec.js
Labels: PR: partially-approved

#16824 Authorize Web Monetization If User Can Create Article
  app/views/users/_extensions.html.erb
  app/views/users/_web_monetization.html.erb
  config/locales/views/settings/en.yml
  config/locales/views/settings/fr.yml
Labels: PR: partially-approved

#16823 Removing reference to Generate Personal blog
  config/locales/views/settings/en.yml
  config/locales/views/settings/fr.yml
Labels: PR: partially-approved

#16825 Don't suggest author follows for anonymous visitors
  app/services/users/suggest_for_sidebar.rb
  spec/services/users/suggest_for_sidebar_spec.rb
Labels: PR: reviewed-approved

#16826 Removing unused instance variable
  app/controllers/notifications_controller.rb
Labels: PR: reviewed-approved

#16818 Fan out Feeds::ImportArticlesWorker
  app/workers/feeds/import_articles_worker.rb
  spec/workers/feeds/import_articles_worker_spec.rb
Labels: PR: partially-approved

#16834 Update color picker input specs
  cypress/integration/creatorOnboardingFlows/creatorSettings.spec.js
  cypress/integration/seededFlows/adminFlows/apps/editListingCategory.spec.js
  cypress/integration/seededFlows/adminFlows/config/userExperienceSection.spec.js
  cypress/integration/seededFlows/adminFlows/tags/createATag.spec.js
  cypress/integration/seededFlows/settingsFlows/organisationSettings.spec.js
  cypress/integration/seededFlows/settingsFlows/updateProfileSettings.spec.js
  cypress/integration/seededFlows/tagsFlows/editTag.spec.js
  cypress/support/commands.js
Labels: PR: partially-approved

#16831 Limit per-user feed import fanout to users with feed urls set
  app/workers/feeds/import_articles_worker.rb
  spec/workers/feeds/import_articles_worker_spec.rb
Labels: PR: unreviewed

#16787 Allowlist character classes for post titles
  app/models/article.rb
  spec/models/article_spec.rb
Labels: PR: unreviewed

#16835 Remove ForemStatsDriver abstraction
  app/lib/acts_as_forem_stats_driver.rb
  app/lib/forem_stats_driver.rb
  app/lib/forem_stats_drivers/datadog_driver.rb
  config/initializers/datadog.rb
  config/initializers/stats.rb
Labels: PR: partially-approved

#16843 Test Solution for Forem-link Embed issues on Canary2
  app/lib/url.rb
  spec/lib/url_spec.rb
Labels: PR: unreviewed

#16764 Remove admin_member_view Feature Flag-Related Conditionals
  app/controllers/admin/users_controller.rb
  app/views/admin/feedback_messages/_latest_articles.html.erb
  app/views/admin/feedback_messages/_potential_spam_users.html.erb
  app/views/admin/listings/index.html.erb
  app/views/admin/users/_email_tools.html.erb
  app/views/admin/users/show.html.erb
  config/routes/admin.rb
  lib/data_update_scripts/20220309194124_remove_admin_member_view_feature_flag.rb
  spec/lib/data_update_scripts/remove_admin_member_view_feature_flag_spec.rb
  spec/requests/admin/users_spec.rb
  spec/support/seeds/seeds_e2e.rb
  spec/system/admin/admin_bans_or_warns_user_spec.rb
  spec/system/admin/admin_deletes_user_spec.rb
  spec/system/admin/user_email_tools_spec.rb
Labels: PR: partially-approved

#16704 Check validity of embed URLs
  app/javascript/article-form/components/ErrorList.jsx
  app/liquid_tags/loom_tag.rb
  app/liquid_tags/unified_embed/tag.rb
  config/locales/liquid_tags/en.yml
  config/locales/liquid_tags/fr.yml
  spec/liquid_tags/loom_tag_spec.rb
  spec/liquid_tags/unified_embed/tag_spec.rb
  spec/rails_helper.rb
  spec/support/embeds_helpers.rb
Labels: PR: unreviewed

#15487 Re-enable imageUpload native integration
  app/javascript/article-form/components/ArticleCoverImage.jsx
  app/javascript/article-form/components/ImageUploader.jsx
  app/javascript/article-form/components/__tests__/ArticleCoverImage.test.jsx
  app/javascript/article-form/components/__tests__/ImageUploader.test.jsx
  app/javascript/crayons/MarkdownToolbar/MarkdownToolbar.jsx
Labels: PR: partially-approved

#16846 Fix pause button
  app/assets/stylesheets/article-show.scss
Labels: PR: unreviewed

#16852 Removes Unused Admin-User-Related Code
  app/views/admin/users/_activity.html.erb
  app/views/admin/users/_credits.html.erb
  app/views/admin/users/_current_roles.html.erb
  app/views/admin/users/_data_export.html.erb
  app/views/admin/users/_negative_reactions.html.erb
  app/views/admin/users/_notes.html.erb
  app/views/admin/users/_reports.html.erb
  app/views/admin/users/_user_organizations.html.erb
  app/views/admin/users/edit.html.erb
Labels: PR: partially-approved, merge by any core

#16870 chore: Removed unused jest configuration setting
  package.json
Labels: area: tests, PR: partially-approved, merge by any core

#16871 chore: Increased jest test coverage thresholds
  jest.config.js
Labels: PR: unreviewed, area: tests, PR: partially-approved, merge by any core

#16872 Correctly update moderations/fr.yml
  config/locales/views/moderations/fr.yml
Labels: PR: partially-approved

#16887 chore: Removed unused webpack configuration
  config/webpack/custom.js
Labels: PR: partially-approved, tech: frontend, merge by any core

#16898 Fix missing dc:creator on RSS feed
  app/views/articles/feed.rss.builder
  spec/requests/articles/articles_spec.rb
Labels: PR: partially-approved

#16900 Revert "Refactor editor tags selector to fetch all tag info in one network call"
  app/javascript/article-form/components/TagsField.jsx
Labels: PR: partially-approved, merge by any core

#16895 Allow option for "no readme" with GitHub embeds
  app/liquid_tags/github_tag.rb
  app/liquid_tags/github_tag/github_readme_tag.rb
  app/liquid_tags/unified_embed/tag.rb
  config/locales/liquid_tags/en.yml
  config/locales/liquid_tags/fr.yml
  spec/liquid_tags/unified_embed/registry_spec.rb
  spec/liquid_tags/unified_embed/tag_spec.rb
Labels: PR: unreviewed

#16899 Improving Solargraph options
  .gitignore
  .solargraph.yml
  Gemfile
  Gemfile.lock
  vendor/cache/solargraph-rails-0.3.1.gem
  vendor/cache/yard-activerecord-0.0.16.gem
  vendor/cache/yard-activesupport-concern-0.0.1.gem
Labels: PR: partially-approved

#16840 Introduce "extensions"
  app/controllers/admin/extensions_controller.rb
  app/models/admin_menu.rb
  app/models/extension.rb
  app/views/admin/extensions/index.html.erb
  config/locales/controllers/admin/en.yml
  config/locales/controllers/admin/fr.yml
  config/routes/admin.rb
  spec/requests/admin/extensions_spec.rb
Labels: PR: reviewed-approved

#16888 Adding docs and specs to AdminMenu.nested_menu_items
  app/models/admin_menu.rb
  app/views/admin/shared/_tabbed_navbar.html.erb
  spec/models/admin_menu_spec.rb
Labels: PR: partially-approved

#16904 Allow embedding of Instagram profile URLs
  app/assets/stylesheets/ltags/InstagramTag.scss
  app/liquid_tags/glitch_tag.rb
  app/liquid_tags/instagram_tag.rb
  app/liquid_tags/liquid_tag_base.rb
  app/liquid_tags/unified_embed/tag.rb
  app/views/liquids/_instagram.html.erb
  spec/liquid_tags/unified_embed/registry_spec.rb
  spec/liquid_tags/unified_embed/tag_spec.rb
Labels: PR: partially-approved

#16903 Remove fastly http purge feature flag and conditional behavior
  app/services/edge_cache/bust/fastly.rb
  lib/data_update_scripts/20220317151317_remove_fastly_http_purge_flag.rb
  spec/lib/data_update_scripts/remove_fastly_http_purge_flag_spec.rb
Labels: PR: partially-approved

#16912 Remove Duplicate Banish Confirmation Modal from Member Detail View
  app/views/admin/users/show/profile/actions/_banish.html.erb
Labels: PR: partially-approved

#16920 Fix embed link validation failures
  app/liquid_tags/unified_embed/tag.rb
  spec/liquid_tags/loom_tag_spec.rb
  spec/liquid_tags/unified_embed/tag_spec.rb
  spec/support/embeds_helpers.rb
Labels: PR: partially-approved

#16930 Fix typo: Gitpod
  README.md
Labels: PR: reviewed-approved

#16916 Better error upon Tweet embed when Twitter keys missing
  app/models/tweet.rb
  app/services/twitter_client/errors.rb
  config/locales/models/en.yml
  config/locales/models/fr.yml
  spec/liquid_tags/unified_embed/registry_spec.rb
  spec/models/tweet_spec.rb
Labels: PR: partially-approved

#16952 Match error class using case instead of if/elsif/else
  app/services/twitter_client/client.rb
  spec/services/twitter_client/client_spec.rb
Labels: PR: reviewed-approved

#16956 Created a utility function for checking the flash success message for user udpates in the admin
  cypress/integration/seededFlows/adminFlows/users/manageCredits.spec.js
  cypress/integration/seededFlows/adminFlows/users/manageOrganizations.spec.js
  cypress/integration/seededFlows/adminFlows/users/manageRoles.spec.js
  cypress/integration/seededFlows/adminFlows/users/manageUserOptions.spec.js
  cypress/integration/seededFlows/adminFlows/users/userAdminUtilitites.js
Labels: area: tests, PR: partially-approved, merge by any core

#16955 Adding inline documentation
  app/controllers/application_controller.rb
Labels: PR: reviewed-approved

#16942 Removing before actions in favor of explicit method
  app/controllers/dashboards_controller.rb
Labels: PR: partially-approved

#16925 Feeds::ValidateUrl sends "forem feeds importer" user agent
  app/services/feeds/validate_url.rb
Labels: PR: partially-approved

#16958 Updated Member Index View Layout foundation behind a feature flag.
  app/views/admin/users/index.html.erb
  app/views/admin/users/index/_controls.html.erb
  app/views/admin/users/index/_tabs.html.erb
Labels: PR: partially-approved

#16620 Removing bootstrap from Config's collapsable sections
  app/views/admin/profile_fields/_grouped_profile_fields.html.erb
  app/views/admin/profile_fields/_ungrouped_profile_fields.html.erb
  app/views/admin/settings/_update_setting_button.html.erb
  app/views/admin/settings/forms/_api_tokens.html.erb
  app/views/admin/settings/forms/_authentication.html.erb
  app/views/admin/settings/forms/_campaign.html.erb
  app/views/admin/settings/forms/_community.html.erb
  app/views/admin/settings/forms/_credits.html.erb
  app/views/admin/settings/forms/_emails.html.erb
  app/views/admin/settings/forms/_google_analytics.html.erb
  app/views/admin/settings/forms/_images.html.erb
  app/views/admin/settings/forms/_mascot.html.erb
  app/views/admin/settings/forms/_meta_keywords.html.erb
  app/views/admin/settings/forms/_monetization.html.erb
  app/views/admin/settings/forms/_newsletter.html.erb
  app/views/admin/settings/forms/_onboarding.html.erb
  app/views/admin/settings/forms/_rate_limit.html.erb
  app/views/admin/settings/forms/_smtp.html.erb
  app/views/admin/settings/forms/_sponsors.html.erb
  app/views/admin/settings/forms/_tags.html.erb
  app/views/admin/settings/forms/_user_experience.html.erb
  app/views/admin/settings/show.html.erb
  app/views/admin/shared/_card_header.html.erb
  cypress/integration/creatorOnboardingFlows/creatorSettings.spec.js
  cypress/integration/seededFlows/adminFlows/config/authenticationSection.spec.js
  cypress/integration/seededFlows/adminFlows/config/emailServerSettingsSection.spec.js
  cypress/integration/seededFlows/adminFlows/config/userExperienceSection.spec.js
  cypress/integration/seededFlows/adminFlows/pages/landingPage.spec.js
  spec/system/admin/admin_manages_profile_fields_spec.rb
  spec/system/admin/config/admin_updates_smtp_settings_spec.rb
  spec/system/authentication/creator_config_edit_spec.rb
Labels: area: admin, PR: draft, PR: partially-approved, tech: frontend

#16939 symlink .env_sample as .env.test
  .env.test
  .travis.yml
Labels: PR: reviewed-approved

#16967 Remove myself from the core team
  README.md
Labels: PR: reviewed-approved

#16928 Use the canonical URLs to link from sorted pages
  app/views/articles/index.html.erb
  app/views/stories/tagged_articles/index.html.erb
  spec/requests/stories/tagged_articles_spec.rb
  spec/requests/stories_index_spec.rb
  spec/system/articles/user_visits_articles_by_tag_spec.rb
Labels: PR: reviewed-approved

#16873 youtube tag timestamp format fix
  app/liquid_tags/youtube_tag.rb
  spec/liquid_tags/youtube_tag_spec.rb
Labels: PR: partially-approved

#16329 Always show the browse section of podcasts regardless of featured
  app/views/podcast_episodes/index.html.erb
  spec/factories/podcast_episodes.rb
  spec/factories/podcasts.rb
  spec/system/podcasts/user_visits_podcast_episode_spec.rb
  spec/system/podcasts/user_visits_podcast_page_spec.rb
  spec/system/podcasts/user_visits_podcasts_root_page_spec.rb
  spec/views/podcast_episodes/index.html.erb_spec.rb
Labels: PR: reviewed-approved

#16954 Removing instance variable and before action
  app/controllers/dashboards_controller.rb
Labels: PR: unreviewed

#16968 Optimize `URL.database_available?`
  app/lib/url.rb
Labels: PR: unreviewed

#16944 Adding ArticlePolicy#has_existing_articles_or_can_create_new_ones?
  app/policies/article_policy.rb
  spec/policies/article_policy_spec.rb
Labels: PR: reviewed-approved

#16975 Update Member Index View Layout
  app/views/admin/users/_member_index.html.erb
  app/views/admin/users/index.html.erb
  app/views/admin/users/index/_controls.html.erb
Labels: PR: partially-approved

#16951 Adding Admin > Content Manager > Spaces menu item
  app/models/admin_menu.rb
  spec/models/admin_menu_spec.rb
Labels: PR: partially-approved

#16974 Refactoring methods to remove duplication
  app/controllers/dashboards_controller.rb
Labels: PR: partially-approved

#16973 Adjusting article copy to be more general
  app/views/users/_notifications.html.erb
  config/locales/helpers/en.yml
  config/locales/helpers/fr.yml
  config/locales/views/settings/en.yml
  config/locales/views/settings/fr.yml
Labels: PR: unreviewed

#16982 Removing a JS message about connect
  app/javascript/profileDropdown/blockButton.js
  spec/rails_helper.rb
Labels: PR: partially-approved

#16977 Fix redundant slack notifications when article was published
  app/models/article.rb
  spec/models/article_spec.rb
Labels: PR: reviewed-approved

#16992 Favoring re-use of authorization error
  app/controllers/api/v0/analytics_controller.rb
  app/errors/unauthorized_error.rb
Labels: PR: reviewed-approved

#16991 Reducing duplication of knowledge
  app/policies/organization_policy.rb
Labels: PR: reviewed-approved

#16994 Change the admin nav item from "People" to "Members"
  app/models/admin_menu.rb
  app/views/admin/users/_menu.html.erb
Labels: PR: reviewed-approved

#16984 Add unscoped index on articles.feed_source_url
  db/migrate/20220323185428_index_articles_on_feed_source_url.rb
  db/schema.rb
Labels: PR: partially-approved

#17012 Update i18n-tasks to 1.0.4
  Gemfile
  Gemfile.lock
  app/views/notifications/index.html.erb
  app/views/organizations/_sidebar_additional.html.erb
  vendor/cache/i18n-tasks-0.9.37.gem
  vendor/cache/i18n-tasks-1.0.4.gem
  vendor/cache/rails-i18n-7.0.1.gem
  vendor/cache/rails-i18n-7.0.3.gem
Labels: PR: partially-approved

#17011 Improvements to home feed profile preview card cypress spec
  app/javascript/packs/homePageFeed.jsx
  cypress/integration/seededFlows/homeFeedFlows/profilePreviewCards.spec.js
Labels: PR: partially-approved, merge by any core

#16999 Conditionally reducing dashboard chatter for users
  app/controllers/dashboards_controller.rb
  app/views/dashboards/_actions.html.erb
  spec/requests/dashboard_spec.rb
Labels: PR: reviewed-approved

#17010 Adding :internal auditing for admin/spaces#update
  app/controllers/admin/spaces_controller.rb
  app/services/audit/notification.rb
Labels: PR: reviewed-approved

#17014 Skip tests for profile preview cards on the home feed
  cypress/integration/seededFlows/homeFeedFlows/profilePreviewCards.spec.js
Labels: PR: partially-approved, merge by any core

#17019 Add a named blank option to the filter dropdown on the Member Index View
  app/views/admin/users/index/_controls.html.erb
Labels: PR: partially-approved

#17023 Instrument `ActiveSupport::Cache#fetch_multi` in Honeycomb
  config/initializers/honeycomb.rb
Labels: PR: partially-approved

#17021 Prefer "listing" to "classified_listing" in the api
  app/controllers/api/v0/listings_controller.rb
  spec/requests/api/v0/listings_spec.rb
Labels: PR: reviewed-approved

#17024 Avoid using robohash for factory generated article cover images
  spec/factories/articles.rb
  spec/view_objects/cloud_cover_url_spec.rb
Labels: PR: reviewed-approved

#16528 Admin analytics
  app/assets/images/calendar.svg
  app/assets/images/decrease.svg
  app/assets/images/increase.svg
  app/assets/stylesheets/config/_generator.scss
  app/controllers/admin/overview_controller.rb
  app/javascript/packs/admin/overview.jsx
  app/services/admin/charts_data.rb
  app/services/admin/data_counts.rb
  app/views/admin/overview/_analytics.html.erb
  app/views/admin/overview/_health_check.html.erb
  app/views/admin/overview/index.html.erb
  spec/services/admin/charts_data_spec.rb
  spec/services/admin/data_counts_spec.rb
  spec/system/admin/admin_visits_overview_spec.rb
Labels: PR: unreviewed

#17035 Revert ERB comment tag work-around
  app/views/notifications/index.html.erb
  app/views/organizations/_sidebar_additional.html.erb
Labels: PR: reviewed-approved

#17016 Add toggle button to 'New Forem Secret' form
  app/javascript/packs/foremCreatorSignup.js
  app/views/shared/authentication/_forem_creator_signup.html.erb
  config/locales/views/auth/en.yml
  config/locales/views/auth/fr.yml
Labels: PR: partially-approved

#17009 Admin member index: show/hide search and filter controls
  app/assets/images/filter.svg
  app/assets/stylesheets/admin.scss
  app/javascript/packs/admin/users/controls.js
  app/javascript/utilities/dropdownUtils.js
  app/views/admin/users/_member_index.html.erb
  app/views/admin/users/index/_controls.html.erb
  app/views/admin/users/index/_filter_role_field.html.erb
  app/views/admin/users/index/_search_field.html.erb
  cypress/integration/seededFlows/adminFlows/users/userIndexView.spec.js
Labels: PR: partially-approved

#17044 Update github-actions Bot
  .github/workflows/issue.yml
Labels: PR: partially-approved

#17040 Bust cache when changing spaces
  app/controllers/admin/spaces_controller.rb
Labels: PR: partially-approved

#17045 Make onboarding_background_image nullable
  app/models/settings/general.rb
Labels: PR: reviewed-approved

#16606 conditionally render create post button for admins #16490
  app/assets/javascripts/base.js.erb
  app/controllers/authorization/articles_controller.rb
  app/views/authorization/articles/create_post_button.html.erb
  app/views/layouts/_top_bar.html.erb
  config/routes.rb
  package.json
  spec/requests/authorization/articles_spec.rb
  spec/requests/root_page_spec.rb
  yarn.lock
Labels: PR: unreviewed

#17042 Favoring explicit class declaration
  app/services/edge_cache/bust.rb
Labels: PR: reviewed-approved

#17022 Adding some docs for ApplicationHelper
  app/helpers/application_helper.rb
Labels: PR: unreviewed

#17057 Update .gitignore
  .gitignore
Labels: PR: reviewed-approved

#17051 Fixed hiding 'Click to edit' link for drafts
  app/views/articles/show.html.erb
  spec/system/articles/user_visits_an_article_spec.rb
Labels: PR: partially-approved

#17061 Remove the connect feature flag
  lib/data_update_scripts/20220330191441_remove_connect_feature_flag.rb
  spec/lib/data_update_scripts/remove_connect_feature_flag_spec.rb
Labels: PR: reviewed-approved

#17015 Adjusting logic to match intention
  app/controllers/dashboards_controller.rb
Labels: PR: partially-approved

#17062 Update profile admin instructions
  app/views/admin/profile_fields/index.html.erb
Labels: PR: unreviewed

#14381 Award badges for github commits with various milestones
  app/services/badges/award_contributor_from_github.rb
  spec/factories/users.rb
  spec/services/badges/award_contributor_from_github_spec.rb
  spec/support/fixtures/vcr_cassettes/Badges_AwardContributorFromGithub/awards_single_commit_contributors.yml
  spec/support/fixtures/vcr_cassettes/github_client_commits_contributor_badge.yml
  spec/support/fixtures/vcr_cassettes/github_client_commits_contributor_badge_twice.yml
Labels: PR: partially-approved, changelog: rollup
