Repository forem/forem, pull requests merged in 2022-06, with the labels that each got.

#17777 "Empty State" for Result-less Search and Filter
  app/views/admin/users/index.html.erb
  cypress/integration/seededFlows/adminFlows/users/userIndexView.spec.js
Labels: PR: partially-approved

#17791 Add jaw6 to core team
  README.md
Labels: PR: reviewed-approved

#17794 Part 1: Add "Name" Column to GDPR Delete Requests Table
  db/migrate/20220531183553_add_name_to_users_gdpr_delete_requests.rb
  db/schema.rb
Labels: PR: partially-approved

#17763 Reusable user admin modals
  app/javascript/crayons/formElements/DateRangePicker/__stories__/DateRangePicker.stories.jsx
  app/javascript/packs/admin/editUser.jsx
  app/javascript/packs/admin/users/editUserModals.js
  app/javascript/packs/admin/users/memberIndex.js
  app/javascript/utilities/showModal.jsx
  app/views/admin/users/controls/_export.html.erb
  app/views/admin/users/modals/_add_organization_modal.html.erb
  app/views/admin/users/modals/_add_role_modal.html.erb
  app/views/admin/users/modals/_adjust_credits_modal.html.erb
  app/views/admin/users/modals/_banish_modal.html.erb
  app/views/admin/users/modals/_unpublish_modal.html.erb
  app/views/admin/users/show/overview/_credits.html.erb
  app/views/admin/users/show/overview/_organizations.html.erb
  app/views/admin/users/show/overview/_roles.html.erb
  app/views/admin/users/show/profile/_actions.html.erb
  app/views/admin/users/show/profile/actions/_banish.html.erb
  app/views/admin/users/show/profile/actions/_unpublish.html.erb
  cypress/integration/seededFlows/adminFlows/users/manageRoles.spec.js
  spec/system/admin/admin_bans_or_warns_user_spec.rb
Labels: PR: partially-approved

#17808 Banner template
  app/assets/stylesheets/components/banners.scss
  app/assets/stylesheets/config/_colors.css
  app/assets/stylesheets/config/_generator.scss
Labels: PR: partially-approved, tech: frontend, merge by any core

#17812 [Travis] Remove ignore CVE-2022-27311
  .travis.yml
Labels: PR: reviewed-approved

#17779 Add tooltip to cover image button describing optimal image ratio
  app/javascript/article-form/components/ArticleCoverImage.jsx
  app/javascript/article-form/components/__tests__/ArticleCoverImage.test.jsx
  app/javascript/article-form/components/__tests__/Form.test.jsx
  app/services/articles/builder.rb
  cypress/integration/seededFlows/publishingFlows/postBrowserPersistence.spec.js
  cypress/integration/seededFlows/publishingFlows/uploadImage.spec.js
  spec/services/articles/builder_spec.rb
Labels: PR: partially-approved

#17818 Exposing past feed experiments in /admin/abtests
  app/models/ab_experiment.rb
  config/field_test.yml
  spec/models/ab_experiment_spec.rb
Labels: PR: unreviewed

#17821 Adding more context to `/admin/abtests`
  app/models/articles/feeds/variant_assembler.rb
  app/services/articles/feeds/variant_query.rb
  app/views/field_test/experiments/_experiments.html.erb
  spec/models/articles/feeds/variant_assembler_spec.rb
Labels: PR: partially-approved

#17824 Adding feed experiment for 2022-06-03
  config/feed-variants/20220603-variant-a.json
  config/feed-variants/20220603-variant-b.json
  config/field_test.yml
Labels: PR: partially-approved

#17827 Adding ability to "seed" feed's SQL randomization
  app/models/articles/feeds.rb
  app/services/articles/feeds/variant_query.rb
Labels: PR: reviewed-approved

#17828 BETA version of the Storybook Multi Input
  app/assets/stylesheets/components/multi-input.scss
  app/assets/stylesheets/crayons.scss
  app/javascript/crayons/MultiInput/MultiInput.jsx
  app/javascript/crayons/MultiInput/__stories__/MultiInput.mdx
  app/javascript/crayons/MultiInput/__stories__/MultiInput.stories.jsx
Labels: PR: unreviewed

#17764 [listing-dashboard] Refactor class components to be functional component
  app/javascript/listings/__tests__/ListingDashboard.test.jsx
  app/javascript/listings/dashboard/listingRow.jsx
  app/javascript/listings/listingDashboard.jsx
Labels: PR: partially-approved

#17798 Unpin article should behave more like Pin article
  app/controllers/admin/articles_controller.rb
  app/javascript/admin/controllers/article_controller.js
  app/views/admin/articles/_individual_article.html.erb
  config/locales/controllers/admin/en.yml
  config/locales/controllers/admin/fr.yml
  cypress/integration/seededFlows/adminFlows/articles/pinArticle.spec.js
  cypress/integration/seededFlows/adminFlows/articles/unpinArticle.spec.js
Labels: PR: unreviewed

#17831 Enable/remove some Rails 6.1 framework default
  config/initializers/new_framework_defaults_6_1.rb
Labels: PR: partially-approved

#17846 ignore spaminess rating to safely remove database column
  app/models/article.rb
  spec/models/article_spec.rb
Labels: PR: reviewed-approved

#17844 Routine Rubopcop lint fixes
  app/controllers/api/v0/health_checks_controller.rb
  app/lib/app_secrets.rb
  app/lib/release_phase_notifier.rb
  app/models/settings/smtp.rb
  app/models/users/deleted_user.rb
  app/services/mentions/create_all.rb
  app/workers/push_notifications/cleanup_worker.rb
  config/environments/development.rb
  config/environments/production.rb
  config/environments/test.rb
  config/initializers/flipper.rb
  config/initializers/rpush.rb
  config/initializers/s3_direct_upload.rb
  config/initializers/sidekiq.rb
  config/initializers/vault.rb
  lib/sitemap_generator/s3_adapter.rb
  lib/tasks/data_updates.rake
  spec/lib/release_phase_notifier_spec.rb
  spec/lib/url_spec.rb
  spec/liquid_tags/medium_tag_spec.rb
  spec/models/admin_menu_spec.rb
  spec/models/forem_instance_spec.rb
  spec/models/notification_spec.rb
  spec/models/podcast_episode_spec.rb
  spec/models/podcast_spec.rb
  spec/models/settings/smtp_spec.rb
  spec/requests/admin/broadcasts_spec.rb
  spec/requests/admin/overview_spec.rb
  spec/requests/admin/sponsorships_spec.rb
  spec/requests/api/v0/articles_spec.rb
  spec/requests/api/v0/listings_spec.rb
  spec/requests/discussion_locks_spec.rb
  spec/requests/listings_spec.rb
  spec/requests/registrations_spec.rb
  spec/requests/user_subscriptions_spec.rb
  spec/services/broadcasts/welcome_notification/generator_spec.rb
  spec/services/feeds/assemble_article_markdown_spec.rb
  spec/services/notifications/moderation/send_spec.rb
  spec/services/podcasts/episode_rss_item_spec.rb
  spec/services/profile_fields/remove_spec.rb
  spec/services/settings/authentication/upsert_spec.rb
  spec/services/users/delete_spec.rb
  spec/support/initializers/ci_csv_formatter.rb
  spec/system/admin/admin_awards_badges_spec.rb
  spec/tasks/metrics_spec.rb
  spec/workers/data_update_worker_spec.rb
Labels: PR: partially-approved

#17833 Adding caching to our feed's random seed
  app/services/articles/feeds/variant_query.rb
Labels: PR: reviewed-approved

#17845 Fixes `sort_link` specs warning
  app/views/admin/tags/index.html.erb
Labels: PR: reviewed-approved

#17850 Add quick select ranges to date range picker
  app/javascript/crayons/formElements/DateRangePicker/DateRangePicker.jsx
  app/javascript/crayons/formElements/DateRangePicker/__stories__/DateRangePicker.stories.jsx
  app/javascript/crayons/formElements/DateRangePicker/__stories__/DateRangePicker.test.jsx
  app/javascript/crayons/formElements/DateRangePicker/__tests__/DateRangePicker.test.jsx
  app/javascript/crayons/formElements/DateRangePicker/__tests__/dateRangeUtils.test.js
  app/javascript/crayons/formElements/DateRangePicker/dateRangeUtils.js
  app/javascript/crayons/formElements/DateRangePicker/index.js
Labels: PR: partially-approved

#17860 ✂✂✂ Removing Spam::ArticleHandler
  app/services/spam/article_handler.rb
Labels: PR: reviewed-approved

#17875 Enable cookies_same_site_protection :lax
  config/initializers/new_framework_defaults_6_1.rb
Labels: PR: partially-approved

#17781 Feature/add embed icon to editor toolbar
  app/assets/images/lightning.svg
  app/javascript/crayons/MarkdownToolbar/__tests__/MarkdownToolbar.test.jsx
  app/javascript/crayons/MarkdownToolbar/__tests__/markdownSyntaxFormatters.test.js
  app/javascript/crayons/MarkdownToolbar/markdownSyntaxFormatters.jsx
Labels: PR: partially-approved

#17866 Member Index View Actions: "Assign Role"
  app/controllers/admin/users_controller.rb
  app/javascript/packs/admin/users/memberIndex.js
  app/views/admin/users/index.html.erb
  app/views/admin/users/index/_user_actions_dropdown.html.erb
  cypress/integration/seededFlows/adminFlows/users/userIndexView.spec.js
Labels: PR: partially-approved

#17870 Stop recommending deprecated plugins
  .vscode/extensions.json
Labels: PR: reviewed-approved

#17847 Adding additional order by levers
  app/models/articles/feeds.rb
Labels: PR: reviewed-approved

#17885 Enable clickOutsideDeactivates on Onboarding FocusTrap
  app/javascript/onboarding/Onboarding.jsx
Labels: PR: partially-approved, merge by any core

#17877 Change load_defaults to 6.1
  config/application.rb
  config/initializers/new_framework_defaults_6_1.rb
Labels: PR: partially-approved

#17879 Member Index View Actions: "Add Organization"
  app/controllers/admin/organization_memberships_controller.rb
  app/views/admin/users/index.html.erb
  app/views/admin/users/index/_user_actions_dropdown.html.erb
  cypress/integration/seededFlows/adminFlows/users/userIndexView.spec.js
  spec/requests/admin/organization_memberships_spec.rb
Labels: PR: reviewed-approved

#17858 Allow Moderator Role to adjust post tags
  app/controllers/moderations_controller.rb
  app/models/article.rb
  app/models/tag_adjustment.rb
  app/policies/article_policy.rb
  app/policies/user_policy.rb
  app/views/moderations/actions_panel.html.erb
  cypress/integration/seededFlows/articleFlows/postModerationTools.spec.js
  spec/policies/article_policy_spec.rb
  spec/policies/user_policy_spec.rb
Labels: PR: unreviewed

#17919 Allowing UserQuery to filter on multiple roles
  app/controllers/admin/invitations_controller.rb
  app/controllers/admin/users_controller.rb
  app/lib/constants/role.rb
  app/queries/admin/users_query.rb
  spec/queries/admin/users_query_spec.rb
Labels: PR: reviewed-approved

#17884 Admin member index: filter by member roles
  app/javascript/packs/admin/users/filtersModal.js
  app/queries/admin/users_query.rb
  app/views/admin/users/index/_filters_modal.html.erb
  cypress/integration/seededFlows/adminFlows/users/filterUserIndex.spec.js
  spec/support/seeds/seeds_e2e.rb
Labels: PR: partially-approved

#17931 Enable Rails framework 7.0's ActiveStorage & ActionMailer
  config/initializers/new_framework_defaults_7_0.rb
Labels: PR: partially-approved

#17936 Revert "Bump lint-staged from 12.4.1 to 13.0.1"
  package.json
  yarn.lock
Labels: PR: partially-approved, merge by any core

#17935 ✂️ remove storybook addon-links ✂️
  app/javascript/.storybook/main.js
  package.json
  yarn.lock
Labels: PR: partially-approved, merge by any core

#17942 Adding VariantQuery reseed randomization option
  app/models/articles/feeds/variant_assembler.rb
  app/services/articles/feeds/variant_query.rb
  config/feed-variants/20220415-incumbent.json
  config/feed-variants/20220422-variant.json
  config/feed-variants/20220509-variant.json
  config/feed-variants/20220518-variant.json
  config/feed-variants/20220525-variant.json
  config/feed-variants/20220603-variant-a.json
  config/feed-variants/20220603-variant-b.json
  config/feed-variants/README.md
  config/feed-variants/original.json
Labels: PR: reviewed-approved, merge by any core

#17950 Adding 2022-06-17 feed variant
  config/feed-variants/20220617-variant-a.json
  config/feed-variants/20220617-variant-b.json
  config/feed-variants/20220617-variant-c.json
  config/field_test.yml
Labels: PR: partially-approved

#17948 Enable Rails framework 7.0's ActionView & tests
  config/initializers/new_framework_defaults_7_0.rb
Labels: PR: partially-approved

#17944 feat: tagged articles page title can render tag pretty name
  app/views/stories/tagged_articles/_meta.html.erb
Labels: PR: reviewed-approved

#17957 Remove eventmachine to enable guard
  Gemfile
  Gemfile.lock
  Guardfile
  vendor/cache/em-websocket-0.5.2.gem
  vendor/cache/eventmachine-1.2.7.gem
  vendor/cache/guard-livereload-2.5.2.gem
  vendor/cache/guard-rspec-4.7.3.gem
  vendor/cache/rspec-3.11.0.gem
Labels: PR: partially-approved

#17886 Track clicks and views in comments on article page
  app/assets/javascripts/utilities/buildCommentFormHTML.js.erb
  app/assets/javascripts/utilities/buildCommentHTML.js.erb
  app/javascript/CommentSubscription/CommentSubscription.jsx
  app/javascript/packs/articlePage.jsx
  app/views/comments/_comment.html.erb
  app/views/comments/_comment_footer.html.erb
  app/views/comments/_comment_header.html.erb
  app/views/comments/_form.html.erb
Labels: PR: partially-approved

#17954 Member index: Show applied roles filters
  app/javascript/packs/admin/users/memberIndex.js
  app/views/admin/users/index.html.erb
  app/views/admin/users/index/_applied_filters.html.erb
  cypress/integration/seededFlows/adminFlows/users/filterUserIndex.spec.js
Labels: PR: unreviewed

#17965 Refactor userIndexView.spec.js
  cypress/integration/seededFlows/adminFlows/users/userIndexView.spec.js
Labels: PR: partially-approved, merge by any core

#17894 BETA version 2 of the Storybook Multi Input (Editing and Accessibility)
  app/assets/stylesheets/components/multi-input.scss
  app/javascript/crayons/MultiInput/MultiInput.jsx
  app/javascript/crayons/MultiInput/__stories__/MultiInput.stories.jsx
  app/javascript/crayons/MultiSelectAutocomplete/DefaultSelectionTemplate.jsx
  app/javascript/crayons/MultiSelectAutocomplete/MultiSelectAutocomplete.jsx
  app/javascript/shared/components/defaultSelectionTemplate.jsx
Labels: PR: unreviewed

#17970 Enable Rails framework 7.0's isolation_level, partial_inserts, & raise_on_open_redirects
  app/controllers/social_previews_controller.rb
  config/initializers/new_framework_defaults_7_0.rb
Labels: PR: partially-approved

#17878 Fix email confirmation logic when registering via Omniauth
  app/controllers/confirmations_controller.rb
  app/controllers/omniauth_callbacks_controller.rb
  app/services/authentication/authenticator.rb
  spec/services/authentication/authenticator_spec.rb
Labels: PR: partially-approved, merge by any core

#17974 Member Index View Actions: "Adjust Credit Balance"
  app/controllers/admin/users_controller.rb
  app/views/admin/users/index.html.erb
  app/views/admin/users/index/_user_actions_dropdown.html.erb
  cypress/integration/seededFlows/adminFlows/users/userIndexView.spec.js
Labels: PR: partially-approved

#18006 Validate date format and min/max in date range picker component
  app/assets/stylesheets/components/forms.scss
  app/javascript/crayons/formElements/DateRangePicker/DateRangePicker.jsx
  app/javascript/crayons/formElements/DateRangePicker/__tests__/DateRangePicker.test.jsx
Labels: merge by any core
