Repository forem/forem, pull requests merged in 2022-05, with the labels that each got.

#16795 Edit URL deployment to GitPod
  README.md
Labels: PR: partially-approved

#17438 Remove name from invitation flow
  app/controllers/admin/invitations_controller.rb
  app/controllers/application_controller.rb
  app/controllers/invitations_controller.rb
  app/views/admin/invitations/index.html.erb
  app/views/admin/invitations/new.html.erb
  app/views/admin/users/index/_invitation_actions_dropdown.html.erb
  app/views/devise/invitations/edit.html.erb
  app/views/devise/mailer/invitation_instructions.html.erb
  app/views/devise/mailer/invitation_instructions.text.erb
  config/locales/devise_invitable.en.yml
  config/locales/devise_invitable.fr.yml
  cypress/integration/seededFlows/adminFlows/users/invitedUsers.spec.js
  spec/requests/admin/invitations_spec.rb
  spec/system/admin/admin_invites_user_spec.rb
Labels: PR: reviewed-approved

#17537 ✂️✂️✂️: Remove unused partial `menu`
  app/views/admin/users/_menu.html.erb
Labels: PR: partially-approved, merge by any core

#17535 chore: Set permissions for GitHub actions
  .github/workflows/codeql-analysis.yml
  .github/workflows/issue.yml
Labels: PR: partially-approved

#17536 Remove GDPR from the "users" namespace
  app/controllers/admin/gdpr_delete_requests_controller.rb
  app/controllers/admin/users/gdpr_delete_requests_controller.rb
  app/controllers/admin/users_controller.rb
  app/models/gdpr_delete_request.rb
  app/models/users/gdpr_delete_request.rb
  app/views/admin/gdpr_delete_requests/index.html.erb
  app/views/admin/users/index/_tabs.html.erb
  app/workers/users/delete_worker.rb
  config/routes/admin.rb
  spec/factories/gdpr_delete_requests.rb
  spec/requests/admin/gdpr_delete_requests_spec.rb
  spec/workers/users/delete_worker_spec.rb
Labels: PR: unreviewed

#17559 Sanitize URL before parsing
  app/helpers/articles_helper.rb
  spec/helpers/articles_helper_spec.rb
Labels: PR: unreviewed, merge by any core

#17532 Moving Experiments into AbExperiment namespace
  app/models/ab_experiment.rb
  app/models/ab_experiment/goal_conversion_handler.rb
  app/models/comment.rb
  app/models/page_view.rb
  app/workers/users/record_field_test_event_worker.rb
  config/field_test.yml
  spec/models/ab_experiment/goal_conversion_handler_spec.rb
  spec/models/ab_experiment_spec.rb
  spec/rails_helper.rb
  spec/workers/users/record_field_test_event_worker_spec.rb
Labels: PR: unreviewed

#17435 Pass options correctly to chart.js on articles#stats
  app/javascript/analytics/dashboard.js
Labels: PR: partially-approved

#17562 Rename "Invited Member" to "Username"
  app/views/admin/invitations/index.html.erb
Labels: PR: partially-approved

#17567 Add a GDPR inflection
  app/controllers/admin/gdpr_delete_requests_controller.rb
  app/models/gdpr_delete_request.rb
  app/views/admin/users/index/_tabs.html.erb
  app/workers/users/delete_worker.rb
  config/initializers/inflections.rb
  db/migrate/20201012072557_create_users_gdpr_delete_requests.rb
  spec/factories/gdpr_delete_requests.rb
  spec/requests/admin/gdpr_delete_requests_spec.rb
  spec/workers/users/delete_worker_spec.rb
Labels: PR: partially-approved

#17550 Improve Dashboard specs coverage
  spec/system/dashboards/user_visits_dashboard_spec.rb
Labels: PR: partially-approved

#17563 Removing Alex from core member list
  README.md
Labels: PR: reviewed-approved

#17569 Update invitations search aria-label
  app/views/admin/invitations/index.html.erb
  cypress/integration/seededFlows/adminFlows/users/invitedUsers.spec.js
Labels: PR: unreviewed

#17568 Add crayons modal to GDPR confirm delete flow
  app/controllers/admin/gdpr_delete_requests_controller.rb
  app/javascript/packs/admin/users/gdprDeleteRequests.jsx
  app/javascript/utilities/showModal.jsx
  app/views/admin/gdpr_delete_requests/index.html.erb
  config/locales/controllers/admin/en.yml
  config/locales/controllers/admin/fr.yml
  cypress/integration/seededFlows/adminFlows/users/gdprDeleteRequests.spec.js
  spec/support/seeds/seeds_e2e.rb
Labels: PR: unreviewed

#17538 Update the Sidebar to include the Member Manager
  app/models/admin_menu.rb
  app/views/admin/gdpr_delete_requests/index.html.erb
  app/views/admin/invitations/index.html.erb
  app/views/admin/shared/_nested_sidebar.html.erb
  app/views/admin/users/index.html.erb
  app/views/admin/users/index/_tabs.html.erb
  config/routes/admin.rb
  cypress/integration/seededFlows/adminFlows/users/gdprDeleteRequests.spec.js
  cypress/integration/seededFlows/adminFlows/users/invitedUsers.spec.js
  cypress/integration/seededFlows/adminFlows/users/manageCredits.spec.js
  cypress/integration/seededFlows/adminFlows/users/manageOrganizations.spec.js
  cypress/integration/seededFlows/adminFlows/users/manageRoles.spec.js
  cypress/integration/seededFlows/adminFlows/users/manageUserOptions.spec.js
  cypress/integration/seededFlows/adminFlows/users/navigateTabs.spec.js
  cypress/integration/seededFlows/adminFlows/users/userIndexView.spec.js
  cypress/support/commands.js
  spec/requests/admin/gdpr_delete_requests_spec.rb
  spec/requests/admin/invitations_spec.rb
  spec/requests/admin/users_spec.rb
Labels: PR: unreviewed

#17575 Removing Jamie from core
  README.md
Labels: PR: reviewed-approved

#17571 "Empty State" for Invited Members
  app/views/admin/invitations/index.html.erb
  cypress/integration/seededFlows/adminFlows/users/invitedUsers.spec.js
Labels: PR: unreviewed

#17588 Move pack declaration outside of cached rails view
  app/views/users/show.html.erb
Labels: PR: partially-approved, merge by any core

#17591 Refactoring so relevancy levers define expected variables
  app/models/articles/feeds.rb
  app/models/articles/feeds/relevancy_lever.rb
  app/models/articles/feeds/variant_assembler.rb
  app/services/articles/feeds/variant_query.rb
  config/feed-variants/20220415-incumbent.json
  config/feed-variants/20220422-jennie-variant.json
  config/feed-variants/README.md
  config/feed-variants/original.json
  spec/models/articles/feeds/relevancy_lever_spec.rb
Labels: PR: partially-approved

#17589 Adding a field test option for post publishing goals
  app/models/ab_experiment/goal_conversion_handler.rb
  app/models/article.rb
  config/field_test.yml
  spec/models/ab_experiment/goal_conversion_handler_spec.rb
  spec/models/article_spec.rb
  spec/rails_helper.rb
Labels: PR: partially-approved

#17583 "Empty State" for GDPR Delete Requests
  app/views/admin/gdpr_delete_requests/index.html.erb
  cypress/integration/seededFlows/adminFlows/users/gdprDeleteRequests.spec.js
Labels: PR: partially-approved

#17600 Adding ID to API organization response document
  app/views/api/v0/organizations/show.json.jbuilder
  spec/requests/api/v0/organizations_spec.rb
Labels: PR: partially-approved

#17594 Removing link to learn more about spaces
  app/views/admin/spaces/index.html.erb
Labels: PR: partially-approved

#17599 Improves UI unit tests by correcting wrong use of queries
  app/javascript/article-form/components/ArticleCoverImage.jsx
  app/javascript/article-form/components/__tests__/ArticleCoverImage.test.jsx
  app/javascript/article-form/components/__tests__/Close.test.jsx
  app/javascript/article-form/components/__tests__/Form.test.jsx
  app/javascript/article-form/components/__tests__/Help.test.jsx
  app/javascript/article-form/components/__tests__/ImageUploader.test.jsx
  app/javascript/article-form/components/__tests__/Options.test.jsx
  app/javascript/article-form/components/__tests__/PageTitle.test.jsx
  app/javascript/article-form/components/__tests__/Preview.test.jsx
  app/javascript/article-form/components/__tests__/Tabs.test.jsx
Labels: PR: partially-approved

#17597 Fixing variant query specs
  spec/services/articles/feeds/variant_query_spec.rb
Labels: PR: reviewed-approved

#17592 Wellness badge query+service refactor
  app/queries/comments/community_wellness_query.rb
  app/services/badges/award_community_wellness.rb
  spec/queries/comments/community_wellness_query_spec.rb
  spec/services/badges/award_community_wellness_spec.rb
Labels: PR: reviewed-approved

#17626 Replace forem/forem instead of thepracticaldev/dev.to (*.jbuilder)
  app/views/api/v0/articles/index.json.jbuilder
  app/views/api/v0/articles/show.json.jbuilder
Labels: PR: reviewed-approved

#17632 Ensuring only privileged users may give certain reactions
  app/controllers/reactions_controller.rb
  app/models/reaction.rb
  app/policies/reaction_policy.rb
  spec/policies/reaction_policy_spec.rb
  spec/requests/reactions_spec.rb
Labels: PR: reviewed-approved

#17602 Make Follow Buttons in User, Org and Tag Embeds "secondary"
  app/assets/stylesheets/ltags/TagTag.scss
  app/assets/stylesheets/ltags/UserTag.scss
  app/helpers/application_helper.rb
  app/views/organizations/_liquid.html.erb
  app/views/tags/_liquid.html.erb
  app/views/users/_liquid.html.erb
Labels: PR: partially-approved

#17635 Passing --passWithNoTests to jest linter
  .lintstagedrc.js
Labels: PR: reviewed-approved, merge by any core

#17086 I18nize Constants::Settings
  app/lib/constants/settings/authentication.rb
  app/lib/constants/settings/campaign.rb
  app/lib/constants/settings/community.rb
  app/lib/constants/settings/general.rb
  app/lib/constants/settings/rate_limit.rb
  app/lib/constants/settings/smtp.rb
  app/lib/constants/settings/user_experience.rb
  app/views/admin/settings/forms/_api_tokens.html.erb
  app/views/admin/settings/forms/_authentication.html.erb
  app/views/admin/settings/forms/_campaign.html.erb
  app/views/admin/settings/forms/_community.html.erb
  app/views/admin/settings/forms/_credits.html.erb
  app/views/admin/settings/forms/_emails.html.erb
  app/views/admin/settings/forms/_google_analytics.html.erb
  app/views/admin/settings/forms/_images.html.erb
  app/views/admin/settings/forms/_mascot.html.erb
  app/views/admin/settings/forms/_meta_keywords.html.erb
  app/views/admin/settings/forms/_monetization.html.erb
  app/views/admin/settings/forms/_newsletter.html.erb
  app/views/admin/settings/forms/_onboarding.html.erb
  app/views/admin/settings/forms/_rate_limit.html.erb
  app/views/admin/settings/forms/_smtp.html.erb
  app/views/admin/settings/forms/_sponsors.html.erb
  app/views/admin/settings/forms/_tags.html.erb
  app/views/admin/settings/forms/_user_experience.html.erb
  app/views/admin/settings/forms/authentication/_apple_auth_provider_settings.html.erb
  app/views/admin/settings/forms/authentication/_auth_provider_settings.html.erb
  config/locales/lib/en.yml
  config/locales/lib/fr.yml
Labels: PR: partially-approved

#17605 Replacing a potentially expensive query
  app/policies/article_policy.rb
Labels: PR: partially-approved

#17619 Moving from user.trusted tests to policy tests
  app/javascript/packs/articleModerationTools.js
  app/models/async_info.rb
  app/policies/article_policy.rb
  spec/models/async_info_spec.rb
Labels: PR: partially-approved

#17623 Remove Community Wellness badge feature flag
  app/queries/comments/community_wellness_query.rb
  app/services/badges/award_community_wellness.rb
  spec/queries/comments/community_wellness_query_spec.rb
  spec/services/badges/award_community_wellness_spec.rb
Labels: PR: reviewed-approved

#17640 Ensuring we don't render call to action when unauthorized
  app/views/users/onboardings/_task_card.html.erb
  spec/system/onboardings/user_completes_onboarding_spec.rb
Labels: PR: reviewed-approved

#17630 Display "Create Post" button on tag page, regardless of submission template presence
  app/views/stories/tagged_articles/_sidebar.html.erb
Labels: PR: partially-approved

#17665 [Datadog] Simplify ddtrace configuration
  Gemfile
  config/initializers/datadog.rb
Labels: PR: partially-approved

#17667 Update datadog.rb to include env scope
  config/initializers/datadog.rb
Labels: PR: unreviewed

#17673 Adding more goals to feed experiments
  app/models/ab_experiment/goal_conversion_handler.rb
  app/models/reaction.rb
  config/field_test.yml
  spec/models/ab_experiment/goal_conversion_handler_spec.rb
  spec/models/reaction_spec.rb
Labels: PR: reviewed-approved

#17690 Fix spec calc that checks date filter expectation
  spec/queries/comments/community_wellness_query_spec.rb
Labels: PR: partially-approved, merge by any core

#17696 Adding page view goal for experiments
  app/models/ab_experiment/goal_conversion_handler.rb
  config/field_test.yml
  spec/models/ab_experiment/goal_conversion_handler_spec.rb
Labels: PR: partially-approved

#17680 Ensuring that embed fallback renders URL
  app/liquid_tags/open_graph_tag.rb
  app/services/open_graph.rb
  app/views/liquids/_open_graph.html.erb
  spec/fixtures/files/guides.rubyonrails.org-routing.html
  spec/liquid_tags/unified_embed/tag_spec.rb
Labels: PR: reviewed-approved

#17703 Link our contributing guide to developers.forem.com
  CONTRIBUTING.md
  README.md
Labels: PR: partially-approved

#17684 i18n catchup with ProfileDecorator
  app/views/users/_metadata.html.erb
  app/views/users/_profile.html.erb
  app/views/users/_sidebar.html.erb
  config/locales/views/users/en.yml
  config/locales/views/users/fr.yml
Labels: PR: partially-approved

#17685 Updating listings_controller.rb and fixing issue :-> 17683
  app/controllers/admin/listings_controller.rb
  spec/requests/admin/listings_spec.rb
Labels: PR: partially-approved, merge by any core

#17722 new feed variant 20220518
  config/feed-variants/20220518-variant.json
  config/field_test.yml
Labels: PR: partially-approved

#17347 change the object-fit to scale down to retain ratio on cover images
  app/assets/stylesheets/views/article.scss
Labels: PR: partially-approved

#17502 apply same `scale-down` property to preview cover image
  app/assets/stylesheets/views/article-form.scss
Labels: PR: partially-approved

#17512 make feed image consistent with cover image
  app/assets/stylesheets/views/article.scss
  app/javascript/articles/__tests__/__snapshots__/Article.test.jsx.snap
  app/javascript/articles/components/ArticleCoverImage.jsx
  app/views/articles/_single_story.html.erb
  app/views/stories/feeds/show.json.jbuilder
  spec/requests/stories_index_spec.rb
Labels: PR: partially-approved

#17739 Add UI for member index v2 actions dropdown buttons
  app/assets/images/cloud-off.svg
  app/assets/images/note.svg
  app/assets/images/organization2.svg
  app/assets/images/warning.svg
  app/views/admin/users/index/_user_actions_dropdown.html.erb
Labels: PR: partially-approved

#17699 [save-btn] Refactor class components to be functional component
  app/javascript/articles/components/SaveButton.jsx
Labels: PR: partially-approved

#17740 Member index view - collapse other filter sections when one is clicked
  app/javascript/packs/admin/users/controls.js
  app/javascript/packs/admin/users/filtersModal.js
  app/views/admin/users/index/_filters_modal.html.erb
  cypress/integration/seededFlows/adminFlows/users/filterUserIndex.spec.js
Labels: PR: partially-approved

#17742 Initial BETA storybook version of DateRangePicker
  app/assets/stylesheets/components/forms.scss
  app/assets/stylesheets/config/_colors.css
  app/assets/stylesheets/themes/dark.css
  app/javascript/crayons/formElements/DateRangePicker/DateRangePicker.jsx
  app/javascript/crayons/formElements/DateRangePicker/__stories__/DateRangePicker.stories.jsx
  app/javascript/crayons/formElements/DateRangePicker/index.js
  app/javascript/crayons/formElements/index.js
  package.json
  yarn.lock
Labels: PR: unreviewed

#17761 Add missing explicit scopes to Omniauth adapters
  config/initializers/devise.rb
Labels: PR: reviewed-approved

#17758 DateRangePicker component: localize US vs non-US date format
  app/javascript/crayons/formElements/DateRangePicker/DateRangePicker.jsx
  app/javascript/crayons/formElements/DateRangePicker/__stories__/DateRangePicker.test.jsx
  app/javascript/utilities/runtime.js
Labels: PR: reviewed-approved

#17765 Remove warning gem
  Gemfile
  Gemfile.lock
  vendor/cache/warning-1.2.1.gem
Labels: PR: partially-approved

#17541 Fix Stackoverflow liquid embedded styles
  app/assets/stylesheets/ltags/StackexchangeTag.scss
  app/views/liquids/_stackexchange.html.erb
Labels: PR: partially-approved

#17682 [categories] Refactor class components to be functional component
  app/javascript/listings/__tests__/Categories.test.jsx
  app/javascript/listings/components/Categories.jsx
Labels: PR: partially-approved

#17681 [single-article] Refactor class components to be functional component
  app/javascript/modCenter/singleArticle/__tests__/singleArticle.test.jsx
  app/javascript/modCenter/singleArticle/index.jsx
Labels: PR: partially-approved

#17759 added ability to assign moderator role via admin/super admin
  app/models/role.rb
  app/services/moderator/manage_activity_and_roles.rb
  cypress/fixtures/users/moderatorUser.json
  cypress/integration/seededFlows/articleFlows/postModerationTools.spec.js
  spec/models/role_spec.rb
  spec/services/moderator/manage_activity_and_roles_spec.rb
  spec/support/seeds/seeds_e2e.rb
Labels: PR: unreviewed

#17773 Update github-actions Bot Contributing Guide Link
  .github/workflows/issue.yml
Labels: PR: partially-approved

#17778 Implement feed variant 20220525
  config/feed-variants/20220525-variant.json
  config/field_test.yml
Labels: PR: partially-approved

#17771 DateRangePicker: layout tweaks for mobile
  app/assets/stylesheets/components/forms.scss
  app/javascript/crayons/formElements/DateRangePicker/DateRangePicker.jsx
  app/javascript/crayons/formElements/DateRangePicker/__stories__/DateRangePicker.test.jsx
Labels: PR: partially-approved, merge by any core

#17783 Fix typo in runtime.js
  app/javascript/utilities/runtime.js
Labels: PR: partially-approved

#17633 Searchable GDPR Delete Requests Table
  app/controllers/admin/gdpr_delete_requests_controller.rb
  app/queries/admin/gdpr_delete_requests_query.rb
  app/views/admin/gdpr_delete_requests/index.html.erb
  cypress/integration/seededFlows/adminFlows/users/gdprDeleteRequests.spec.js
  spec/queries/admin/gdpr_delete_requests_query_spec.rb
Labels: PR: partially-approved
