Repository forem/forem, pull requests merged in 2022-01, with the labels that each got.

#15878 Add crayons_icon_tag helper
  app/helpers/crayons_helper.rb
  spec/helpers/crayons_helper_spec.rb
Labels: PR: reviewed-approved

#15911 Renaming/rearranging constants for clarity
  app/liquid_tags/gist_tag.rb
  app/liquid_tags/unified_embed.rb
  app/liquid_tags/unified_embed/registry.rb
  app/liquid_tags/unified_embed/tag.rb
  app/liquid_tags/unified_embed_tag.rb
  spec/liquid_tags/unified_embed/registry_spec.rb
  spec/liquid_tags/unified_embed/tag_spec.rb
Labels: PR: reviewed-approved

#15914 Favor repurposing existing scope
  app/models/credit.rb
Labels: PR: partially-approved

#15849 Refactoring and documenting class
  app/services/articles/suggest_stickies.rb
  spec/services/articles/suggest_stickies_spec.rb
Labels: PR: partially-approved

#14909 Prevent whitespace unicode characters from being used in article title and tag
  app/models/article.rb
  app/models/tag.rb
  config/locales/en.yml
  config/locales/fr.yml
  spec/models/article_spec.rb
  spec/models/tag_spec.rb
Labels: PR: reviewed-approved

#15922 Remove sign in/up link from navlinks
  app/views/layouts/_main_nav.html.erb
  config/locales/views/main/en.yml
  config/locales/views/main/fr.yml
  spec/system/homepage/user_visits_homepage_spec.rb
Labels: PR: partially-approved

#15907 Remove Storext gem
  Gemfile
  Gemfile.lock
  app/models/article.rb
  app/models/user.rb
  vendor/cache/axiom-types-0.1.1.gem
  vendor/cache/coercible-1.0.0.gem
  vendor/cache/descendants_tracker-0.0.4.gem
  vendor/cache/ice_nine-0.11.2.gem
  vendor/cache/storext-3.3.0.gem
  vendor/cache/virtus-1.0.5.gem
Labels: PR: partially-approved

#15522 Update to node version 16
  .gitpod.dockerfile
  .nvmrc
  .travis.yml
  Containerfile
  bin/setup
  package.json
Labels: PR: unreviewed

#15933 Updating documentation for LiquidTagBase
  app/liquid_tags/liquid_tag_base.rb
Labels: PR: reviewed-approved

#15789 Proposing a new feed experiment
  .rubocop.yml
  app/controllers/stories/feeds_controller.rb
  app/models/ab_experiment.rb
  app/services/articles/feeds/weighted_query_strategy.rb
  app/workers/users/record_field_test_event_worker.rb
  config/field_test.yml
  spec/models/ab_experiment_spec.rb
  spec/workers/users/record_field_test_event_worker_spec.rb
Labels: PR: unreviewed

#15938 Use newly-built Fedora-35-based quay.io/forem/ruby:3.0.2 container
  Containerfile
Labels: PR: partially-approved

#15942 Send custom user agent string when fetching feeds
  app/services/feeds/import.rb
Labels: PR: unreviewed

#15923 Remove store_attribute gem
  Gemfile
  Gemfile.lock
  app/models/profile.rb
  app/services/users/update.rb
  vendor/cache/store_attribute-0.9.3.gem
Labels: PR: unreviewed

#15947 Update precision config on field test dashboard
  config/field_test.yml
Labels: PR: reviewed-approved, merge by any core

#15951 Add faraday 1.8.0 before deploying
  .travis.yml
Labels: PR: reviewed-approved

#15952 Work around travis deploy (take two)
  .travis.yml
Labels: PR: partially-approved

#15953 Stop removing canvas files from CI build cache
  .travis.yml
Labels: PR: reviewed-approved

#15955 Require UnifiedEmbed Tag for UnifiedEmbed Registry
  app/liquid_tags/unified_embed.rb
Labels: PR: reviewed-approved

#15944 Remove redis-rails gem
  Gemfile
  Gemfile.lock
  vendor/cache/redis-activesupport-5.2.0.gem
  vendor/cache/redis-rails-5.0.2.gem
Labels: PR: partially-approved

#15810 Update tag search and suggest
  app/controllers/tags_controller.rb
  app/serializers/search/tag_serializer.rb
  app/services/search/tag.rb
  spec/requests/tags_spec.rb
  spec/services/search/tag_spec.rb
Labels: PR: reviewed-approved

#15811 Add Storybook entry for tag suggestion item
  app/assets/stylesheets/views/article-form.scss
  app/javascript/article-form/components/TagAutocompleteOption.jsx
  app/javascript/article-form/components/__stories__/TagAutocompleteOption.stories.jsx
Labels: PR: partially-approved

#14395 add missing unique key to fragment created with map
  app/javascript/article-form/components/Preview.jsx
  app/javascript/listings/components/Categories.jsx
Labels: PR: partially-approved

#15946 Extracting constants and tidying tests
  app/assets/javascripts/initializers/initializeBaseTracking.js.erb
  app/controllers/display_ad_events_controller.rb
  app/models/display_ad_event.rb
  spec/factories/display_ad_events.rb
  spec/models/display_ad_event_spec.rb
  spec/requests/display_ad_events_spec.rb
Labels: PR: partially-approved

#15796 Tag autocomplete: storybook multi-select autocomplete component
  app/assets/stylesheets/components/autocomplete.scss
  app/javascript/crayons/MultiSelectAutocomplete/MultiSelectAutocomplete.jsx
  app/javascript/crayons/MultiSelectAutocomplete/__stories__/MultiSelectAutocomplete.stories.jsx
  app/javascript/crayons/MultiSelectAutocomplete/index.js
Labels: PR: partially-approved

#15961 Update deliver worker conflict strategy
  app/workers/push_notifications/deliver_worker.rb
Labels: PR: reviewed-approved

#15968 Implement TwitchTV Unified Embed
  app/liquid_tags/twitch_tag.rb
  app/liquid_tags/youtube_tag.rb
  app/views/liquids/_twitch.html.erb
  spec/liquid_tags/twitch_tag_spec.rb
  spec/liquid_tags/unified_embed/registry_spec.rb
Labels: PR: partially-approved

#15958 Remove htmlentities gem
  Gemfile
  Gemfile.lock
  app/models/comment.rb
  spec/models/comment_spec.rb
  vendor/cache/htmlentities-4.3.4.gem
Labels: PR: partially-approved

#15975 Change contact page to open feature requests as discussions
  app/views/pages/contact.html.erb
Labels: PR: reviewed-approved

#15976 Remove Faraday work-around for deploys
  .travis.yml
Labels: PR: reviewed-approved

#15967 Skip google analytics when ga_tracking_id is nil
  .env_sample
  app/assets/javascripts/initializers/initializeBaseTracking.js.erb
  app/controllers/ga_events_controller.rb
  app/views/pages/badge.html.erb
Labels: PR: partially-approved

#15979 Remove extra faraday install from travis config
  .travis.yml
Labels: PR: reviewed-approved

#15965 Add Logo Size Requirements to the Creator Settings Form
  app/views/admin/shared/_logo_upload.html.erb
Labels: PR: partially-approved

#15977 Implement Spotify Unified Embed
  app/liquid_tags/spotify_tag.rb
  app/views/liquids/_spotify.html.erb
  spec/liquid_tags/spotify_tag_spec.rb
  spec/liquid_tags/unified_embed/registry_spec.rb
Labels: PR: partially-approved

#15985 Fix goal conversion field test typo
  app/workers/users/record_field_test_event_worker.rb
  spec/workers/users/record_field_test_event_worker_spec.rb
Labels: PR: partially-approved

#15505 Add individual forem name to flag user modal
  app/javascript/packs/flagUserModal.jsx
  app/views/layouts/application.html.erb
Labels: PR: reviewed-approved

#15949 Tidying up and documenting Tag model
  app/controllers/tags_controller.rb
  app/models/tag.rb
  lib/data_update_scripts/20220104165348_nullify_empty_string_for_alias_for.rb
  spec/lib/data_update_scripts/nullify_empty_string_for_alias_for_spec.rb
Labels: PR: unreviewed

#15978 Fixes a name conflict in Rpush models
  app/models/consumer_app.rb
  app/queries/consumer_apps/rpush_app_query.rb
  spec/queries/consumer_apps/rpush_app_query_spec.rb
Labels: PR: unreviewed

#15992 Implement Replit Unified Embed
  app/liquid_tags/replit_tag.rb
  app/views/liquids/_replit.html.erb
  spec/liquid_tags/replit_tag_spec.rb
  spec/liquid_tags/unified_embed/registry_spec.rb
Labels: PR: unreviewed

#15966 Stop removing canvas before yarn during bin/setup
  bin/setup
Labels: PR: reviewed-approved

#15987 Update dependabot config
  .github/dependabot.yml
Labels: PR: partially-approved

#15710 Data Update Script to migrate logo_svg contents to png file (Will be merged and deployed on 10/01)
  .travis.yml
  app/uploaders/base_uploader.rb
  app/uploaders/logo_svg_uploader.rb
  app/uploaders/logo_uploader.rb
  lib/data_update_scripts/20220105112823_migrate_logo_svg_data.rb
  spec/lib/data_update_scripts/migrate_logo_svg_data_spec.rb
  spec/uploaders/logo_svg_uploader_spec.rb
  spec/uploaders/logo_uploader_spec.rb
Labels: PR: partially-approved

#15989 Update the images section in preparation for Creator Setup and Onboarding Launch [Will deploy on 10/01]
  app/lib/constants/settings/general.rb
  app/views/admin/settings/forms/_images.html.erb
  app/views/admin/shared/_logo_upload.html.erb
Labels: PR: partially-approved

#16005 Copy `.env_sample` to `.env` in `bin/setup`
  bin/setup
Labels: PR: reviewed-approved

#15969 Remove Setup Banner (VerifySetupCompleted)
  app/assets/stylesheets/setup-mode.scss
  app/controllers/application_controller.rb
  app/controllers/concerns/verify_setup_completed.rb
  app/javascript/admin/controllers/config_controller.js
  app/views/admin/settings/show.html.erb
  cypress/integration/creatorOnboardingFlows/creatorSettings.spec.js
  spec/system/admin/admin_manages_configuration_spec.rb
Labels: PR: partially-approved

#15995 Favor using existing variable over re-parsing
  app/javascript/packs/followButtons.js
Labels: PR: partially-approved

#15988 Update framework defaults
  config/application.rb
  config/initializers/new_framework_defaults_5_2.rb
  config/initializers/new_framework_defaults_6_0.rb
Labels: PR: reviewed-approved, merge by any core

#16034 Updates a Few Config Constants
  app/lib/constants/settings/general.rb
Labels: PR: partially-approved

#16037 Migrate faker dependency to supported upstream
  app/javascript/Snackbar/__stories__/Snackbar.stories.jsx
  package.json
  yarn.lock
Labels: PR: partially-approved

#16004 small non-views ruby i18n
  app/errors/authentication/errors.rb
  app/errors/fastly_config.rb
  app/policies/application_policy.rb
  app/policies/liquid_tag_policy.rb
  app/queries/articles/active_threads_query.rb
  app/services/users/create_mascot_account.rb
  app/uploaders/base_uploader.rb
  config/locales/misc/en.yml
  config/locales/misc/fr.yml
Labels: PR: reviewed-approved

#16002 app/controllers/api i18n
  app/controllers/api/v0/analytics_controller.rb
  app/controllers/api/v0/articles_controller.rb
  app/controllers/api/v0/follows_controller.rb
  app/controllers/api/v0/health_checks_controller.rb
  app/controllers/api/v0/listings_controller.rb
  config/locales/controllers/api/en.yml
  config/locales/controllers/api/fr.yml
Labels: PR: reviewed-approved

#16014 Use crayons_icon_tag for user and org views
  app/views/organizations/_header.html.erb
  app/views/users/_account.html.erb
  app/views/users/_additional_authentication.html.erb
  app/views/users/_main_feed.html.erb
  app/views/users/_org_admin.html.erb
  app/views/users/_sidebar.html.erb
  app/views/users/edit.html.erb
  app/views/users/show.html.erb
Labels: PR: reviewed-approved

#16026 Refactored client-side onboarding redirect logic.
  app/javascript/packs/onboardingRedirectCheck.jsx
Labels: PR: reviewed-approved, area: new user experience, PR: partially-approved, tech: frontend, merge by any core

#15993 Proposing feed experiment 3: More comment count weight
  app/controllers/stories/feeds_controller.rb
  app/models/ab_experiment.rb
  app/services/articles/feeds/weighted_query_strategy.rb
  config/field_test.yml
  spec/models/ab_experiment_spec.rb
Labels: PR: partially-approved

#16051 Raise Error with Invalid UnifiedEmbed URL
  app/liquid_tags/unified_embed/tag.rb
  spec/liquid_tags/unified_embed/tag_spec.rb
Labels: PR: reviewed-approved

#16052 Simplify and label date calculation
  app/workers/broadcasts/send_welcome_notifications_worker.rb
Labels: PR: reviewed-approved

#16060 Modify welcome notification generator to handle errors per-message
  app/services/broadcasts/welcome_notification/generator.rb
  spec/services/broadcasts/welcome_notification/generator_spec.rb
Labels: PR: reviewed-approved

#16063 Add apple_connect welcome notification broadcast
  db/seeds.rb
  lib/data_update_scripts/20220111192031_insert_apple_connect_broadcast_message.rb
  spec/lib/data_update_scripts/insert_apple_connect_broadcast_message_spec.rb
Labels: PR: reviewed-approved

#16065 Add one day to the welcome notification users range
  app/workers/broadcasts/send_welcome_notifications_worker.rb
Labels: PR: partially-approved

#16057 Prefer #after? to numeric time comparisons
  app/services/broadcasts/welcome_notification/generator.rb
Labels: PR: reviewed-approved

#16045 Enable safe Rails 6.1 defaults
  config/initializers/new_framework_defaults_6_1.rb
Labels: PR: reviewed-approved

#16043 Enable AR cache versioning
  config/application.rb
Labels: PR: reviewed-approved

#16068 Adjust in-feed-comment p margin for readability
  app/assets/stylesheets/components/comments.scss
Labels: PR: partially-approved

#16070 Moving the "Null" user object closer to User
  app/helpers/application_helper.rb
  app/liquid_tags/user_tag.rb
  app/models/users/deleted_user.rb
  spec/helpers/application_helper_spec.rb
  spec/liquid_tags/user_tag_spec.rb
  spec/models/users/deleted_user_spec.rb
Labels: PR: reviewed-approved

#16073 Remove IE-specific setting
  config/application.rb
Labels: PR: reviewed-approved

#16074 Don't load ActiveJob railtie
  config/application.rb
  config/environments/production.rb
  config/environments/test.rb
Labels: PR: reviewed-approved

#16069 Allow admin control of auth broadcast messages (was: Don't suggest apple authentication)
  app/services/broadcasts/welcome_notification/generator.rb
Labels: PR: partially-approved

#16064 Refactoring to add helper method
  app/controllers/async_info_controller.rb
  app/controllers/notifications_controller.rb
  app/controllers/stories_controller.rb
  app/models/articles/cached_entity.rb
  app/models/organization.rb
  app/models/podcast.rb
  app/models/user.rb
  app/serializers/search/podcast_episode_serializer.rb
  app/services/images/profile.rb
  app/views/admin/comments/index.html.erb
  app/views/api/v0/articles/onboarding.json.jbuilder
  app/views/api/v0/organizations/show.json.jbuilder
  app/views/api/v0/profile_images/show.json.jbuilder
  app/views/api/v0/shared/_follows.json.jbuilder
  app/views/api/v0/shared/_organization.json.jbuilder
  app/views/api/v0/shared/_user.json.jbuilder
  app/views/api/v0/shared/_user_show.json.jbuilder
  app/views/articles/_liquid.html.erb
  app/views/articles/_single_story.html.erb
  app/views/articles/_sticky_nav.html.erb
  app/views/articles/show.html.erb
  app/views/comments/_comment.json.jbuilder
  app/views/comments/_comment_avatar.html.erb
  app/views/comments/_liquid.html.erb
  app/views/dashboards/followers.html.erb
  app/views/dashboards/following_organizations.html.erb
  app/views/dashboards/following_users.html.erb
  app/views/notifications/_broadcast.html.erb
  app/views/notifications/_notifications_list.html.erb
  app/views/organizations/_header.html.erb
  app/views/organizations/_liquid.html.erb
  app/views/organizations/_sidebar_additional.html.erb
  app/views/shared/_profile_card_content.html.erb
  app/views/social_previews/articles/article.html.erb
  app/views/social_previews/comment.html.erb
  app/views/social_previews/user.html.erb
  app/views/stories/tagged_articles/_sidebar.html.erb
  app/views/users/_liquid.html.erb
  app/views/users/_profile.html.erb
  app/views/users/_sidebar.html.erb
  app/views/users/index.json.jbuilder
  app/views/users/show.html.erb
  spec/liquid_tags/link_tag_spec.rb
  spec/requests/api/v0/followers_spec.rb
  spec/requests/api/v0/organizations_spec.rb
  spec/requests/api/v0/profile_images_spec.rb
  spec/requests/api/v0/users_spec.rb
  spec/requests/articles/articles_show_spec.rb
  spec/requests/followings_spec.rb
  spec/requests/user/user_show_spec.rb
  spec/requests/user/user_suggestions_spec.rb
  spec/serializers/search/podcast_episode_serializer_spec.rb
  spec/services/images/profile_spec.rb
  spec/services/search/podcast_episode_spec.rb
Labels: PR: partially-approved

#16081 Implement Forem Comment Unified Embed
  app/liquid_tags/comment_tag.rb
  spec/liquid_tags/comment_tag_spec.rb
  spec/liquid_tags/unified_embed/registry_spec.rb
Labels: PR: partially-approved

#16079 Adding a convenience/optimiization method.
  app/decorators/application_decorator.rb
  spec/decorators/application_decorator_spec.rb
Labels: PR: partially-approved

#16082 [feed] Change weighted query limit from 50 (default) to 25
  app/controllers/stories/feeds_controller.rb
Labels: PR: partially-approved

#16084 Moving from 'should' syntax to 'expect'
  spec/models/html_variant_spec.rb
Labels: PR: partially-approved

#16062 Now HTML validation works for the adjust tags section of the moderation tools panel
  app/javascript/actionsPanel/actionsPanel.js
  cypress/integration/seededFlows/articleFlows/postModerationTools.spec.js
  cypress/integration/seededFlows/moderationFlows/adjustPostTags.spec.js
Labels: area: moderation, PR: partially-approved, tech: frontend, merge by any core

#16085 Appeasing Rubocop as it sneaks some changes in
  app/models/collection.rb
  app/models/discussion_lock.rb
  app/models/follow.rb
  app/models/html_variant_success.rb
  app/models/html_variant_trial.rb
  app/models/identity.rb
  app/models/listing.rb
  app/models/mention.rb
  app/models/notification_subscription.rb
  app/models/organization_membership.rb
  app/models/podcast_episode_appearance.rb
  app/models/podcast_ownership.rb
  app/models/poll_vote.rb
  app/models/profile_pin.rb
  app/models/sponsorship.rb
  app/models/tag_adjustment.rb
  app/models/user_block.rb
  app/models/user_subscription.rb
  app/models/users/setting.rb
  spec/models/collection_spec.rb
  spec/models/discussion_lock_spec.rb
  spec/models/follow_spec.rb
  spec/models/github_repo_spec.rb
  spec/models/html_variant_success_spec.rb
  spec/models/html_variant_trial_spec.rb
  spec/models/identity_spec.rb
  spec/models/notification_subscription_spec.rb
  spec/models/organization_membership_spec.rb
  spec/models/podcast_episode_appearance_spec.rb
  spec/models/podcast_ownership_spec.rb
  spec/models/rating_vote_spec.rb
  spec/models/sponsorship_spec.rb
  spec/models/tag_adjustment_spec.rb
  spec/models/tweet_spec.rb
  spec/models/user_subscription_spec.rb
Labels: PR: reviewed-approved

#16083 Replacing custom call with existing cached method
  app/models/article.rb
  app/views/articles/_single_story.html.erb
  spec/models/article_spec.rb
  spec/models/articles/cached_entity_spec.rb
Labels: PR: partially-approved, merge by any core

#16086 Remove explicit Zeitwerk config, require hack
  config/application.rb
Labels: PR: partially-approved

#16087 Enable use_cookies_with_metadata option
  config/application.rb
Labels: PR: reviewed-approved

#15986 Login with Google
  Gemfile
  Gemfile.lock
  app/assets/images/google_oauth2.svg
  app/assets/stylesheets/components/buttons.scss
  app/helpers/authentication_helper.rb
  app/lib/constants/settings/authentication.rb
  app/models/settings/authentication.rb
  app/services/authentication/providers.rb
  app/services/authentication/providers/google_oauth2.rb
  app/services/authentication/providers/provider.rb
  app/workers/metrics/record_daily_notifications_worker.rb
  config/initializers/devise.rb
  db/migrate/20211220170907_add_google_o_auth_fields.rb
  db/migrate/20211220171024_add_google_o_auth_fields_index.rb
  db/schema.rb
  db/seeds.rb
  lib/data_update_scripts/20220107215659_insert_google_ouauth2_connect_broadcast_message.rb
  spec/factories/broadcasts.rb
  spec/helpers/authentication_helper_spec.rb
  spec/lib/data_update_scripts/insert_google_ouauth2_connect_broadcast_message_spec.rb
  spec/models/user_spec.rb
  spec/services/authentication/providers_spec.rb
  spec/services/broadcasts/welcome_notification/generator_spec.rb
  spec/support/omniauth_helpers.rb
  spec/system/authentication/creator_config_edit_spec.rb
  vendor/cache/omniauth-google-oauth2-1.0.0.gem
Labels: PR: partially-approved

#16003 app/helpers i18n
  app/helpers/application_helper.rb
  app/helpers/articles_helper.rb
  app/helpers/authentication_helper.rb
  app/helpers/comments_helper.rb
  app/helpers/feedback_messages_helper.rb
  app/helpers/listing_helper.rb
  app/helpers/organization_helper.rb
  app/helpers/rate_limit_checker_helper.rb
  app/helpers/settings_helper.rb
  app/helpers/social_link_helper.rb
  config/locales/helpers/en.yml
  config/locales/helpers/fr.yml
  spec/helpers/application_helper_spec.rb
Labels: PR: reviewed-approved

#16094 Convert admin/config text fields with static options to dropdowns
  app/models/settings/user_experience.rb
  app/views/admin/settings/forms/_user_experience.html.erb
  spec/requests/admin/configs_spec.rb
Labels: PR: partially-approved

#16071 Use crayons_icon_tag for article views
  app/views/articles/_actions.html.erb
  app/views/articles/_reaction_button.html.erb
  app/views/articles/_sidebar.html.erb
  app/views/articles/_single_story.html.erb
  app/views/articles/_sticky_nav.html.erb
  app/views/articles/_v2_form.html.erb
Labels: PR: partially-approved

#16098 Fixing Rubocop's auto-correct recommendations
  db/seeds.rb
  lib/data_update_scripts/20220105112823_migrate_logo_svg_data.rb
  spec/requests/pages_spec.rb
  spec/services/notifications/reactions/send_spec.rb
  spec/services/rate_limit_checker_spec.rb
  spec/system/authentication/user_logs_in_with_apple_spec.rb
  spec/system/authentication/user_logs_in_with_facebook_spec.rb
  spec/system/authentication/user_logs_in_with_forem_spec.rb
  spec/system/authentication/user_logs_in_with_github_spec.rb
  spec/system/authentication/user_logs_in_with_twitter_spec.rb
Labels: PR: partially-approved

#15843 Implementing new buttons
  app/assets/images/bold.svg
  app/assets/images/code.svg
  app/assets/images/codeblock.svg
  app/assets/images/divider.svg
  app/assets/images/heading.svg
  app/assets/images/help.svg
  app/assets/images/italic.svg
  app/assets/images/link.svg
  app/assets/images/list-ordered.svg
  app/assets/images/list-unordered.svg
  app/assets/images/overflow-vertical.svg
  app/assets/images/quote.svg
  app/assets/images/strikethrough.svg
  app/assets/images/underline.svg
  app/assets/stylesheets/components/buttons.scss
  app/javascript/article-form/components/ClipboardButton.jsx
  app/javascript/article-form/components/Close.jsx
  app/javascript/article-form/components/EditorActions.jsx
  app/javascript/article-form/components/ImageUploader.jsx
  app/javascript/article-form/components/Options.jsx
  app/javascript/articles/__tests__/__snapshots__/Article.test.jsx.snap
  app/javascript/crayons/Dropdown/__stories__/Dropdown.stories.jsx
  app/javascript/crayons/MarkdownToolbar/MarkdownToolbar.jsx
  app/javascript/crayons/MarkdownToolbar/icons.jsx
  app/javascript/crayons/MarkdownToolbar/markdownSyntaxFormatters.jsx
  app/javascript/githubRepos/singleRepo.jsx
  app/javascript/listings/dashboard/rowElements/actionButtons.jsx
  app/javascript/packs/flagUserModal.jsx
  app/javascript/profilePreviewCards/MinimalProfilePreviewCard.jsx
  app/javascript/readingList/components/ItemListItemArchiveButton.jsx
  app/javascript/readingList/readingList.jsx
  app/javascript/runtimeBanner/RuntimeBanner.jsx
  cypress/integration/seededFlows/publishingFlows/uploadImage.spec.js
  cypress/integration/seededFlows/readingListFlows/readingList.spec.js
  cypress/integration/seededFlows/readingListFlows/readingListArchive.spec.js
Labels: PR: partially-approved

#15848 Storybook updates
  app/javascript/Search/__stories__/SearchForm.stories.jsx
  app/javascript/crayons/Button/__stories__/Button.stories.jsx
  app/javascript/crayons/Button/__stories__/buttons.mdx
  app/javascript/crayons/Buttons/__stories__/Buttons.stories.jsx
  app/javascript/crayons/CTAs/__stories__/CTAs.stories.jsx
  app/javascript/crayons/Dropdown/__stories__/Dropdown.stories.jsx
  app/javascript/crayons/Dropdown/__stories__/dropdowns.mdx
  app/javascript/crayons/Icons/__stories__/Icons.mdx
  app/javascript/crayons/Icons/__stories__/Icons.stories.jsx
  app/javascript/crayons/Indicator/__stories__/indicator.html.stories.jsx
  app/javascript/crayons/Indicator/__stories__/indicators.mdx
  app/javascript/crayons/Links/__stories__/Links.stories.jsx
  app/javascript/crayons/MarkdownToolbar/__stories__/MarkdownToolbar.stories.jsx
  app/javascript/crayons/MentionAutocompleteTextArea/__stories__/MentionAutocompleteTextArea.stories.jsx
  app/javascript/crayons/MentionAutocompleteTextArea/__stories__/mention-autocomplete.mdx
  app/javascript/crayons/MobileDrawer/__stories__/MobileDrawer.stories.jsx
  app/javascript/crayons/MobileDrawer/__stories__/drawers.mdx
  app/javascript/crayons/Modal/__stories__/Modal.stories.jsx
  app/javascript/crayons/Modal/__stories__/modals.mdx
  app/javascript/crayons/Notice/__stories__/notice.html.stories.jsx
  app/javascript/crayons/Notice/__stories__/notices.mdx
  app/javascript/crayons/avatarsAndLogos/Avatar/__stories__/avatars.html.stories.jsx
  app/javascript/crayons/avatarsAndLogos/Logo/__stories__/logos.html.stories.jsx
  app/javascript/crayons/avatarsAndLogos/avatars-and-logos.mdx
  app/javascript/crayons/formElements/Checkbox/__stories__/checkbox.html.stories.jsx
  app/javascript/crayons/formElements/FormField/__stories__/FormField.stories.jsx
  app/javascript/crayons/formElements/RadioButton/__stories__/RadioButton.stories.jsx
  app/javascript/crayons/formElements/RadioButton/__stories__/radioButton.html.stories.jsx
  app/javascript/crayons/formElements/Select/__stories__/Select.stories.jsx
  app/javascript/crayons/formElements/Text/__stories__/multilineText.html.stories.jsx
  app/javascript/crayons/formElements/Text/__stories__/text.html.stories.jsx
  app/javascript/crayons/formElements/form-elements.mdx
  app/javascript/crayons/guidelines/__stories__/Components.stories.mdx
  app/javascript/crayons/guidelines/__stories__/Writing-css.stories.mdx
  app/javascript/crayons/index.js
  app/javascript/crayons/navigation/MobileDrawerNavigation/MobileDrawerNavigation.jsx
  app/javascript/crayons/navigation/MobileDrawerNavigation/__stories__/MobileDrawerNavigation.stories.jsx
  app/javascript/crayons/navigation/MobileDrawerNavigation/__stories__/mobileDrawerNavigation.html.stories.jsx
  app/javascript/crayons/navigation/MobileDrawerNavigation/__stories__/mobileDrawerNavigation.md
  app/javascript/crayons/navigation/MobileDrawerNavigation/__tests__/MobileDrawerNavigation.test.js
  app/javascript/crayons/navigation/MobileDrawerNavigation/__tests__/__snapshots__/MobileDrawerNavigation.test.js.snap
  app/javascript/crayons/navigation/NavigationTabs/__stories__/navigation-tab.mdx
  app/javascript/crayons/navigation/NavigationTabs/__stories__/navigationTab.html.stories.jsx
  app/javascript/crayons/navigation/index.js
  app/javascript/crayons/navigation/mainNavigation/__stories__/main-navigation.md
  app/javascript/crayons/navigation/mainNavigation/__stories__/mainNavigation.html.stories.jsx
  app/javascript/crayons/typography/__stories__/accented-typography.mdx
  app/javascript/crayons/typography/__stories__/typography.mdx
  app/javascript/crayons/typography/__stories__/typography.stories.jsx
  app/javascript/crayons/typography/__stories__/typographyAccented.stories.jsx
  app/javascript/icons/CogIcon.jsx
  app/javascript/icons/__stories__/CogIcon.stories.jsx
  app/javascript/icons/__tests__/CogIcon.test.jsx
  app/javascript/icons/__tests__/__snapshots__/CogIcon.test.jsx.snap
  app/javascript/icons/index.js
  app/javascript/readingList/components/__stories__/MediaQuery.stories.mdx
Labels: PR: unreviewed, tech: frontend

#15860 Storybook improvements
  app/assets/stylesheets/config/_colors.css
  app/assets/stylesheets/themes/dark.css
  app/javascript/.storybook/main.js
  app/javascript/.storybook/manager.js
  app/javascript/.storybook/preview.js
  app/javascript/.storybook/storybook.scss
  app/javascript/crayons/guidelines/__stories__/Writing-css.stories.mdx
  package.json
  yarn.lock
Labels: PR: reviewed-approved, tech: frontend

#16099 Update crayons_icon_tag helper
  app/helpers/crayons_helper.rb
  app/views/articles/_actions.html.erb
  app/views/organizations/_header.html.erb
  app/views/users/_main_feed.html.erb
  app/views/users/_sidebar.html.erb
  app/views/users/show.html.erb
  spec/helpers/crayons_helper_spec.rb
Labels: PR: partially-approved

#16093 Turn featured back on as query scoring weight
  app/services/articles/feeds/weighted_query_strategy.rb
Labels: PR: partially-approved, merge by any core

#16106 Update storybook node version
  app/javascript/netlify.toml
Labels: PR: unreviewed

#16067 Patching ERB rendering of the data-info JSON
  app/assets/javascripts/utilities/buildArticleHTML.js
  app/decorators/article_decorator.rb
  app/decorators/notification_decorator.rb
  app/helpers/application_helper.rb
  app/models/application_record.rb
  app/models/tag.rb
  app/models/users/deleted_user.rb
  app/view_objects/data_info.rb
  app/views/articles/_single_story.html.erb
  app/views/organizations/_header.html.erb
  app/views/podcast_episodes/index.html.erb
  app/views/podcast_episodes/show.html.erb
  app/views/stories/tagged_articles/index.html.erb
  app/views/tags/index.html.erb
  app/views/users/show.html.erb
  db/seeds.rb
  spec/decorators/application_decorator_spec.rb
  spec/decorators/article_decorator_spec.rb
  spec/decorators/notification_decorator_spec.rb
  spec/factories/users.rb
  spec/models/application_record_spec.rb
  spec/models/tag_spec.rb
  spec/models/users/deleted_user_spec.rb
  spec/support/seeds/seeds_e2e.rb
  spec/view_objects/data_info_spec.rb
Labels: PR: partially-approved

#16095 Implement DotNetFiddle Unified Embed
  app/liquid_tags/dotnet_fiddle_tag.rb
  app/liquid_tags/youtube_tag.rb
  spec/liquid_tags/unified_embed/registry_spec.rb
  spec/liquid_tags/youtube_tag_spec.rb
Labels: PR: reviewed-approved

#16110 Implement Forem Organization Unified Embed
  app/liquid_tags/organization_tag.rb
  spec/liquid_tags/unified_embed/registry_spec.rb
Labels: PR: partially-approved

#16115 Ensuring less obnoxious usernames
  app/models/user.rb
  db/seeds.rb
Labels: PR: partially-approved

#16119 Fixing regex warning and removing unneeded groups
  app/liquid_tags/organization_tag.rb
Labels: PR: partially-approved

#16127 Fix: grammatical error
  config/locales/views/settings/en.yml
  config/locales/views/settings/fr.yml
Labels: PR: reviewed-approved

#16103 Creator Onboarding Logo Updates for launch [Will be merged and Deployed 17 January]
  app/javascript/admin/controllers/config_controller.js
  app/views/admin/settings/forms/_images.html.erb
  app/views/layouts/_logo.html.erb
  app/views/layouts/application.html.erb
  cypress/integration/creatorOnboardingFlows/creatorSettings.spec.js
  spec/system/user_views_logo_spec.rb
Labels: PR: unreviewed

#16090 Launch creator Onboarding with the Feature Flag [ To merge only on January 17 ]
  lib/data_update_scripts/20220113085122_enable_creator_onboarding_feature_flag.rb
  spec/lib/data_update_scripts/enable_creator_onboarding_feature_flag_spec.rb
Labels: PR: partially-approved

#16122 Prevent banished users from updating their profiles
  app/policies/user_policy.rb
  app/services/authentication/authenticator.rb
  spec/policies/user_policy_spec.rb
  spec/services/authentication/authenticator_spec.rb
Labels: PR: partially-approved

#16123 Extracting a not_authored_by scope
  app/models/article.rb
  app/services/articles/feeds/large_forem_experimental.rb
  app/services/articles/suggest.rb
  app/services/articles/suggest_stickies.rb
  app/services/badges/award_tag.rb
  app/services/email_digest_article_collector.rb
  app/services/users/suggest_for_sidebar.rb
Labels: PR: reviewed-approved

#16109 Remove maintenance.html
  public/maintenance.html
Labels: PR: partially-approved

#16142 Restoring tracking of custom impressions without GA
  app/assets/javascripts/initializers/initializeBaseTracking.js.erb
  app/workers/articles/update_page_views_worker.rb
Labels: PR: partially-approved

#16128 Feed experiment 4: Final order
  app/controllers/stories/feeds_controller.rb
  app/models/ab_experiment.rb
  app/services/articles/feeds/weighted_query_strategy.rb
  config/field_test.yml
  spec/models/ab_experiment_spec.rb
Labels: PR: partially-approved

#16156 Addressing rubocop violations
  app/controllers/admin/settings/mandatory_settings_controller.rb
  app/controllers/users_controller.rb
  app/models/settings/base.rb
  app/services/articles/feeds/weighted_query_strategy.rb
  app/services/images/optimizer.rb
  app/services/settings/upsert.rb
Labels: PR: reviewed-approved

#16140 Adding documentation and constant
  app/assets/javascripts/initializers/initializeBaseTracking.js.erb
  app/controllers/page_views_controller.rb
Labels: PR: partially-approved

#16112 Allow for skipping navigation link creation
  app/policies/authorizer.rb
  lib/tasks/add_navigation_links.rake
Labels: PR: partially-approved

#16160 Include badge before serializing tags
  app/services/search/tag.rb
Labels: PR: partially-approved

#16130 Series count to only include non empty series
  app/controllers/collections_controller.rb
  app/controllers/dashboards_controller.rb
  app/models/collection.rb
  app/views/dashboards/_actions.html.erb
Labels: PR: partially-approved

#16132 Remove unused Users::ProfileImageGenerator::BACKGROUND_HEXES
  app/services/users/profile_image_generator.rb
Labels: PR: reviewed-approved

#16100 Update remaining Crayons icons
  app/views/admin/pages/index.html.erb
  app/views/admin/settings/forms/_authentication.html.erb
  app/views/admin/shared/_nested_sidebar.html.erb
  app/views/comments/_comment.html.erb
  app/views/comments/_comment_footer.html.erb
  app/views/comments/_comment_header.html.erb
  app/views/comments/_comment_quality_marker.html.erb
  app/views/comments/_form.html.erb
  app/views/dashboards/_actions.html.erb
  app/views/dashboards/_dashboard_article.html.erb
  app/views/dashboards/_dashboard_article_row.html.erb
  app/views/layouts/_footer.html.erb
  app/views/layouts/_main_nav.html.erb
  app/views/layouts/_sidebar_tags.html.erb
  app/views/layouts/_social_media.html.erb
  app/views/layouts/_top_bar.html.erb
  app/views/layouts/admin.html.erb
  app/views/moderations/_mod_sidebar_left.html.erb
  app/views/moderations/actions_panel.html.erb
  app/views/moderations/mod.html.erb
  app/views/notifications/_aggregated_reactions.html.erb
  app/views/notifications/_single_reaction.html.erb
  app/views/notifications/shared/_article_preview.html.erb
  app/views/notifications/shared/_comment_box.html.erb
  app/views/pages/_editor_guide_h3.html.erb
  app/views/pages/_editor_guide_text.html.erb
  app/views/pages/_v1_editor_guide_preamble.html.erb
  app/views/shared/_hamburger.html.erb
  app/views/shared/authentication/_forem_creator_signup.html.erb
  app/views/shared/authentication/_providers_registration_form.html.erb
  app/views/stories/articles_search/index.html.erb
  app/views/stories/tagged_articles/index.html.erb
  app/views/users/_sidebar.html.erb
Labels: PR: unreviewed

#16077 Move system tests
  spec/liquid_tags/user_subscription_tag_spec.rb
  spec/services/articles/feeds/large_forem_experimental_spec.rb
  spec/system/articles/feeds/large_forem_experimental_spec.rb
  spec/system/liquid_tags/user_subscription_tag_spec.rb
Labels: PR: reviewed-approved

#16164 Resolve Rubocop Violations
  app/services/articles/feeds/weighted_query_strategy.rb
Labels: PR: partially-approved

#16092 Move work from template to controller
  app/controllers/liquid_embeds_controller.rb
  app/views/liquid_embeds/show.html.erb
  spec/requests/liquid_embeds_spec.rb
Labels: PR: reviewed-approved

#16125 app/liquid_tags i18n
  app/liquid_tags/asciinema_tag.rb
  app/liquid_tags/blogcast_tag.rb
  app/liquid_tags/codepen_tag.rb
  app/liquid_tags/codesandbox_tag.rb
  app/liquid_tags/comment_tag.rb
  app/liquid_tags/dotnet_fiddle_tag.rb
  app/liquid_tags/gist_tag.rb
  app/liquid_tags/git_pitch_tag.rb
  app/liquid_tags/github_tag/github_issue_tag.rb
  app/liquid_tags/github_tag/github_readme_tag.rb
  app/liquid_tags/glitch_tag.rb
  app/liquid_tags/instagram_tag.rb
  app/liquid_tags/js_fiddle_tag.rb
  app/liquid_tags/jsitor_tag.rb
  app/liquid_tags/kotlin_tag.rb
  app/liquid_tags/link_tag.rb
  app/liquid_tags/liquid_tag_base.rb
  app/liquid_tags/listing_tag.rb
  app/liquid_tags/medium_tag.rb
  app/liquid_tags/next_tech_tag.rb
  app/liquid_tags/null_tag.rb
  app/liquid_tags/organization_tag.rb
  app/liquid_tags/parler_tag.rb
  app/liquid_tags/podcast_tag.rb
  app/liquid_tags/poll_tag.rb
  app/liquid_tags/reddit_tag.rb
  app/liquid_tags/replit_tag.rb
  app/liquid_tags/runkit_tag.rb
  app/liquid_tags/slideshare_tag.rb
  app/liquid_tags/soundcloud_tag.rb
  app/liquid_tags/speakerdeck_tag.rb
  app/liquid_tags/spotify_tag.rb
  app/liquid_tags/stackblitz_tag.rb
  app/liquid_tags/stackery_tag.rb
  app/liquid_tags/stackexchange_tag.rb
  app/liquid_tags/tag_tag.rb
  app/liquid_tags/tweet_tag.rb
  app/liquid_tags/twitch_tag.rb
  app/liquid_tags/twitter_timeline_tag.rb
  app/liquid_tags/user_subscription_tag.rb
  app/liquid_tags/wikipedia_tag.rb
  app/liquid_tags/youtube_tag.rb
  config/locales/en.yml
  config/locales/fr.yml
  config/locales/liquid_tags/en.yml
  config/locales/liquid_tags/fr.yml
Labels: PR: partially-approved

#15445 Support alternate S3 endpoints
  .env_sample
  config/initializers/carrierwave.rb
Labels: PR: reviewed-approved

#16101 allow approved tags to show articles and not render 404
  app/controllers/stories/tagged_articles_controller.rb
  spec/requests/stories/tagged_articles_spec.rb
Labels: PR: unreviewed

#16173 Revert "Support alternate S3 endpoints"
  .env_sample
  config/initializers/carrierwave.rb
Labels: PR: partially-approved

#16172 Ensuring that we don't divide by zero
  app/services/articles/feeds/weighted_query_strategy.rb
Labels: PR: unreviewed

#16177 Select max from a subquery of two things
  app/services/articles/feeds/weighted_query_strategy.rb
Labels: PR: partially-approved, merge by any core

#16102 Finishes adding all the codepen embed options available
  app/liquid_tags/codepen_tag.rb
  app/views/pages/_editor_guide_text.html.erb
  app/views/pages/_editor_liquid_help.html.erb
  spec/liquid_tags/codepen_tag_spec.rb
Labels: PR: partially-approved

#16166 app/validators i18n
  app/validators/bytesize_validator.rb
  app/validators/color_contrast_validator.rb
  app/validators/emoji_only_validator.rb
  app/validators/existing_published_article_id_validator.rb
  app/validators/profile_validator.rb
  app/validators/unique_cross_model_slug_validator.rb
  app/validators/valid_domain_csv_validator.rb
  config/locales/validators/en.yml
  config/locales/validators/fr.yml
Labels: PR: partially-approved

#16176 Explicitly silence FastImage exceptions
  app/services/articles/enrich_image_attributes.rb
Labels: PR: partially-approved

#16181 Rubocop auto-correct
  app/liquid_tags/codepen_tag.rb
Labels: PR: reviewed-approved

#16167 Remove "connect" feedback message special treatment
  app/controllers/feedback_messages_controller.rb
  app/views/admin/feedback_messages/_feedback_message.html.erb
  app/views/admin/feedback_messages/_style.html.erb
  spec/system/feedback_message_spec.rb
Labels: PR: reviewed-approved

#16108 Bump Travis's postgresql to 13
  .travis.yml
Labels: PR: reviewed-approved

#16182 Re-enable stories specs
  spec/requests/stories_index_spec.rb
Labels: PR: reviewed-approved, merge by any core

#16183 Move BlackBox to app/lib
  .simplecov
  app/lib/black_box.rb
  spec/lib/black_box_spec.rb
Labels: PR: unreviewed

#16190 Updated indicators
  app/assets/javascripts/initializers/initScrolling.js
  app/assets/stylesheets/components/header.scss
  app/assets/stylesheets/components/indicators.scss
  app/assets/stylesheets/components/navigation.scss
  app/assets/stylesheets/config/_colors.css
  app/assets/stylesheets/settings.scss
  app/assets/stylesheets/themes/dark.css
  app/helpers/application_helper.rb
  app/javascript/crayons/Indicator/__stories__/indicator.html.stories.jsx
  app/javascript/crayons/Indicator/__stories__/indicators.mdx
  app/javascript/crayons/Indicators/Indicator.jsx
  app/javascript/crayons/Indicators/__stories__/Indicators.mdx
  app/javascript/crayons/Indicators/__stories__/Indicators.stories.jsx
  app/javascript/crayons/Indicators/index.js
  app/javascript/githubRepos/singleRepo.jsx
  app/views/admin/navigation_links/index.html.erb
  app/views/admin/users/_menu.html.erb
  app/views/articles/_widget_list_item.html.erb
  app/views/dashboards/_actions.html.erb
  app/views/dashboards/_dashboard_article_row.html.erb
  app/views/dashboards/following_tags.html.erb
  app/views/layouts/_sidebar_nav_link.html.erb
  app/views/layouts/_top_bar.html.erb
  app/views/moderations/_mod_sidebar_left.html.erb
  app/views/users/_extensions.html.erb
  app/views/users/_github_repositories_area.html.erb
  app/views/users/_org_admin.html.erb
  spec/requests/admin/users/gdpr_delete_requests_spec.rb
Labels: PR: reviewed-approved, tech: frontend

#16218 Implement Unified Embed for Tweet URLs
  app/liquid_tags/tweet_tag.rb
  spec/liquid_tags/unified_embed/registry_spec.rb
Labels: PR: reviewed-approved

#16191 app/mailers i18n
  app/mailers/digest_mailer.rb
  app/mailers/notify_mailer.rb
  app/mailers/verification_mailer.rb
  config/locales/mailers/en.yml
  config/locales/mailers/fr.yml
Labels: PR: reviewed-approved

#16219 Constantize broadcast messages
  config/locales/misc/en.yml
  config/locales/misc/fr.yml
  db/seeds.rb
  lib/data_update_scripts/20200820153340_insert_facebook_connect_broadcast_message.rb
  lib/data_update_scripts/20210921235050_insert_forem_connect_broadcast_message.rb
  lib/data_update_scripts/20220107215659_insert_google_ouauth2_connect_broadcast_message.rb
  lib/data_update_scripts/20220111192031_insert_apple_connect_broadcast_message.rb
  spec/factories/broadcasts.rb
Labels: PR: unreviewed

#16228 Add suggested_tags to "Onboarding" Section in Config
  app/views/admin/settings/forms/_onboarding.html.erb
Labels: PR: partially-approved, merge by any core

#16217 Let override of ToS and CoC show in onboarding
  app/controllers/admin/pages_controller.rb
  app/models/page.rb
  app/views/onboardings/show.html.erb
  app/views/pages/code_of_conduct.html.erb
  app/views/pages/terms.html.erb
  lib/tasks/add_navigation_links.rake
  spec/models/page_spec.rb
Labels: PR: partially-approved

#16213 Expanding the range of followed tags we show
  app/javascript/leftSidebar/TagsFollowed.jsx
Labels: PR: partially-approved

#16184 ListingsToolkit refactoring
  app/controllers/concerns/listings_toolkit.rb
  app/services/listings/create.rb
  spec/services/listings/create_spec.rb
Labels: PR: partially-approved

#16107 Color tokens
  app/assets/stylesheets/base/main.scss
  app/assets/stylesheets/base/typography.scss
  app/assets/stylesheets/components/buttons.scss
  app/assets/stylesheets/components/cards.scss
  app/assets/stylesheets/components/drawer-navigation.scss
  app/assets/stylesheets/components/dropdowns.scss
  app/assets/stylesheets/components/hamburger.scss
  app/assets/stylesheets/components/indicators.scss
  app/assets/stylesheets/components/media-cards.scss
  app/assets/stylesheets/components/modals.scss
  app/assets/stylesheets/components/navigation.scss
  app/assets/stylesheets/components/notices.scss
  app/assets/stylesheets/components/stories.scss
  app/assets/stylesheets/components/tabs.scss
  app/assets/stylesheets/components/tags.scss
  app/assets/stylesheets/components/tooltips.scss
  app/assets/stylesheets/config/_colors.css
  app/assets/stylesheets/config/_variables.scss
  app/assets/stylesheets/credits.scss
  app/assets/stylesheets/ltags/GithubReadmeTag.scss
  app/assets/stylesheets/ltags/RedditTag.scss
  app/assets/stylesheets/ltags/WikipediaTag.scss
  app/assets/stylesheets/preact/onboarding-modal.scss
  app/assets/stylesheets/settings.scss
  app/assets/stylesheets/themes/dark.css
  app/assets/stylesheets/views/article-form.scss
  app/assets/stylesheets/views/mod-actions.scss
  app/assets/stylesheets/views/mod-center.scss
  app/assets/stylesheets/views/signin.scss
  app/javascript/crayons/Indicators/__stories__/Indicators.mdx
  app/javascript/crayons/Indicators/__stories__/Indicators.stories.jsx
  app/services/color/compare_hex.rb
  app/views/dashboards/following_tags.html.erb
  app/views/layouts/application.html.erb
Labels: PR: unreviewed, tech: frontend

#16025 Add new tag autocomplete to editor
  app/assets/stylesheets/components/autocomplete.scss
  app/assets/stylesheets/views/article-form.scss
  app/javascript/article-form/components/TagAutocompleteOption.jsx
  app/javascript/article-form/components/TagAutocompleteSelection.jsx
  app/javascript/article-form/components/TagsField.jsx
  app/javascript/article-form/components/__tests__/Form.test.jsx
  app/javascript/crayons/MultiSelectAutocomplete/DefaultSelectionTemplate.jsx
  app/javascript/crayons/MultiSelectAutocomplete/MultiSelectAutocomplete.jsx
  app/javascript/crayons/MultiSelectAutocomplete/__stories__/MultiSelectAutocomplete.mdx
  app/javascript/crayons/MultiSelectAutocomplete/__stories__/MultiSelectAutocomplete.stories.jsx
  app/javascript/crayons/MultiSelectAutocomplete/__tests__/MultiSelectAutocomplete.test.jsx
  app/javascript/crayons/MultiSelectAutocomplete/__tests__/__snapshots__/MultiSelectAutocomplete.test.jsx.snap
  app/javascript/crayons/index.js
  app/javascript/listings/listingForm.jsx
  app/javascript/shared/components/tags.jsx
  cypress/integration/seededFlows/publishingFlows/addTagsToArticle.spec.js
  cypress/integration/seededFlows/publishingFlows/postBrowserPersistence.spec.js
Labels: PR: unreviewed, area: publishing experience, PR: partially-approved, tech: frontend

#16243 Fix tag autocomplete styling
  app/assets/stylesheets/views/article-form.scss
Labels: PR: partially-approved, merge by any core

#16244 Destructive button style fix
  app/assets/stylesheets/config/_colors.css
Labels: PR: reviewed-approved

#16239 Removed font-awesome from the admin section
  app/views/admin/comments/index.html.erb
  app/views/layouts/admin.html.erb
Labels: area: admin, PR: draft, PR: partially-approved, tech: frontend, merge by any core

#16234 Configured the repository to handle line endings
  .gitattributes
Labels: area: developer experience, PR: partially-approved, merge by any core

#16237 Add host tag in ForemStatsClient
  config/initializers/rpush.rb
Labels: PR: partially-approved

#16248 Stripping tags from "tags.short_summary" column
  app/models/tag.rb
  lib/data_update_scripts/20220121114445_stripping_html_tags_from_tag_short_summary.rb
  spec/lib/data_update_scripts/stripping_html_tags_from_tag_short_summary_spec.rb
  spec/models/tag_spec.rb
Labels: PR: partially-approved

#16241 Add `Settings::Base.to_h`
  app/models/settings/base.rb
  spec/models/settings/base_spec.rb
Labels: PR: reviewed-approved

#16210 Onboarding "improvements"
  app/controllers/users_controller.rb
  spec/requests/users_onboarding_spec.rb
Labels: PR: partially-approved

#16250 Implement Unified Embeds for Jsitor URLs
  app/liquid_tags/jsitor_tag.rb
  spec/liquid_tags/unified_embed/registry_spec.rb
Labels: PR: unreviewed

#16256 Implement Unified Embeds for Kotlin URLs
  app/liquid_tags/kotlin_tag.rb
  spec/liquid_tags/kotlin_tag_spec.rb
  spec/liquid_tags/unified_embed/registry_spec.rb
Labels: PR: unreviewed

#16266 Simplify implementation of :focus-visible
  app/assets/stylesheets/base/main.scss
  app/assets/stylesheets/components/buttons.scss
  app/assets/stylesheets/components/ctas.scss
  app/assets/stylesheets/components/links.scss
Labels: PR: partially-approved, tech: frontend

#16249 Adding lightweight structure .coerce methods
  app/models/notification.rb
  app/services/notifications/new_follower/follow_data.rb
  app/services/notifications/new_follower/send.rb
  app/services/notifications/reactions/reaction_data.rb
  app/services/notifications/reactions/send.rb
  spec/services/notifications/new_follower/follow_data_spec.rb
  spec/services/notifications/reactions/reaction_data_spec.rb
  spec/services/notifications/reactions/send_spec.rb
Labels: PR: reviewed-approved

#16216 Prefer custom SMTP config over Sendgrid
  app/models/forem_instance.rb
  app/models/settings/smtp.rb
  spec/mailers/application_mailer_spec.rb
  spec/models/forem_instance_spec.rb
  spec/models/settings/smtp_spec.rb
  spec/support/seeds/seeds_e2e.rb
Labels: PR: unreviewed

#16274 Implement Unified Embeds for Slideshare URLs
  app/liquid_tags/slideshare_tag.rb
  app/views/liquids/_slideshare.html.erb
  spec/liquid_tags/unified_embed/registry_spec.rb
Labels: PR: partially-approved

#16286 Appeasing rubocop
  db/seeds.rb
Labels: PR: unreviewed

#16288 Now the close X SVG icon is imported via the inline-react-svg plugin for the Modal component
  app/javascript/crayons/Modal/Modal.jsx
Labels: PR: partially-approved, tech: frontend, merge by any core
