Repository forem/forem, pull requests merged in 2022-04, with the labels that each got.

#17058 Ensuring that established tags don't respond 404
  app/controllers/stories/tagged_articles_controller.rb
  spec/requests/stories/tagged_articles_spec.rb
Labels: PR: reviewed-approved

#16686 Added a way to sort comments on an article
  app/assets/stylesheets/views/comments.scss
  app/controllers/stories_controller.rb
  app/javascript/packs/commentDropdowns.js
  app/javascript/utilities/dropdownUtils.js
  app/models/comment.rb
  app/views/articles/_full_comment_area.html.erb
  app/views/comments/_sort_option.html.erb
  config/locales/views/articles/en.yml
  config/locales/views/articles/fr.yml
  cypress/integration/seededFlows/articleFlows/commentOnArticle.spec.js
  cypress/integration/seededFlows/articleFlows/sortCommentsOnArticle.spec.js
  cypress/integration/seededFlows/publishingFlows/publishOrSavePost.spec.js
  spec/models/comment_spec.rb
  spec/views/articles_spec.rb
Labels: PR: partially-approved

#17052 Ensuring article's cache updates on org image update
  app/models/article.rb
  app/models/organization.rb
  spec/models/organization_spec.rb
Labels: PR: reviewed-approved

#17078 Reducing subtle duplication of effort/logic
  app/models/user.rb
  app/workers/users/resave_articles_worker.rb
Labels: PR: partially-approved

#17079 Add "period" to safe params list
  config/fastly/snippets/safe_params_list.vcl
Labels: PR: partially-approved, merge by any core

#17083 Add "comments_sort" to safe params list
  config/fastly/snippets/safe_params_list.vcl
Labels: PR: partially-approved, merge by any core

#17093 Revert "Added a way to sort comments on an article (#16686)"
  app/assets/stylesheets/views/comments.scss
  app/controllers/stories_controller.rb
  app/javascript/packs/commentDropdowns.js
  app/javascript/utilities/dropdownUtils.js
  app/models/comment.rb
  app/views/articles/_full_comment_area.html.erb
  app/views/comments/_sort_option.html.erb
  config/locales/views/articles/en.yml
  config/locales/views/articles/fr.yml
  cypress/integration/seededFlows/articleFlows/commentOnArticle.spec.js
  cypress/integration/seededFlows/articleFlows/sortCommentsOnArticle.spec.js
  cypress/integration/seededFlows/publishingFlows/publishOrSavePost.spec.js
  spec/models/comment_spec.rb
  spec/views/articles_spec.rb
Labels: PR: partially-approved

#17088 Removing unused instance_variable
  app/controllers/comments_controller.rb
Labels: PR: reviewed-approved

#17072 Ensuring confirmation and flash message for spaces
  app/controllers/admin/spaces_controller.rb
  app/views/admin/spaces/index.html.erb
  config/locales/controllers/admin/en.yml
  config/locales/controllers/admin/fr.yml
Labels: PR: unreviewed

#17064 Display analytics up to yesterday instead of today
  app/controllers/admin/overview_controller.rb
  app/services/admin/charts_data.rb
  app/views/admin/overview/_analytics.html.erb
  spec/requests/admin/overview_spec.rb
  spec/services/admin/charts_data_spec.rb
Labels: PR: partially-approved

#17001 OpenGraph fallback for Embeds (merge-by-any-core)
  Gemfile
  Gemfile.lock
  app/assets/stylesheets/base/typography.scss
  app/liquid_tags/open_graph_tag.rb
  app/liquid_tags/unified_embed/registry.rb
  app/liquid_tags/unified_embed/tag.rb
  app/services/open_graph.rb
  app/views/liquids/_open_graph.html.erb
  config/environments/development.rb
  spec/liquid_tags/unified_embed/tag_spec.rb
  spec/services/open_graph_spec.rb
  spec/support/fixtures/vcr_cassettes/OpenGraph/_meta_for/gets_a_specific_meta_value.yml
  spec/support/fixtures/vcr_cassettes/OpenGraph/grouped_by_key/groups_metadata.yml
  spec/support/fixtures/vcr_cassettes/OpenGraph/grouped_by_key/groups_open_graph_properties.yml
  spec/support/fixtures/vcr_cassettes/OpenGraph/meta-programmed_methods/calls_the_methods.yml
  spec/support/fixtures/vcr_cassettes/OpenGraph/twitter/returns_empty_hash_when_not_available.yml
  spec/support/fixtures/vcr_cassettes/OpenGraph/twitter/returns_twitter_data.yml
  spec/support/fixtures/vcr_cassettes/takeonrules_fetch.yml
  vendor/cache/faraday-cookie_jar-0.0.7.gem
  vendor/cache/faraday-encoding-0.0.5.gem
  vendor/cache/faraday-http-cache-2.2.0.gem
  vendor/cache/faraday_middleware-1.2.0.gem
  vendor/cache/metainspector-5.11.2.gem
  vendor/cache/nesty-1.0.2.gem
Labels: PR: unreviewed, merge by any core

#17110 Removing uncalled method ✂✂✂
  app/liquid_tags/poll_tag.rb
  config/locales/liquid_tags/en.yml
  config/locales/liquid_tags/fr.yml
Labels: PR: reviewed-approved

#17117 Remove a Letter from E2E Expectation in creatorSignup.spec.js
  cypress/integration/creatorOnboardingFlows/creatorSignup.spec.js
Labels: PR: reviewed-approved, merge by any core

#17122 Tweak crayons layout for admin section
  app/assets/stylesheets/base/layout.scss
  app/views/layouts/admin.html.erb
Labels: PR: partially-approved

#17125 Applying more liberal editor config policy
  app/views/users/_customization.html.erb
Labels: PR: reviewed-approved

#17123 Ensuring users can preview already published posts
  app/policies/article_policy.rb
  spec/policies/article_policy_spec.rb
Labels: PR: reviewed-approved

#17076 Conditional rendering of "Create Post" link
  app/controllers/async_info_controller.rb
  app/javascript/packs/applyApplicationPolicyToggles.js
  app/models/async_info.rb
  app/policies/application_policy.rb
  app/views/layouts/_nav_menu.html.erb
  cypress/integration/seededFlows/policyFlows/limitPostCreationToAdmins.spec.js
  spec/models/async_info_spec.rb
  spec/policies/application_policy_spec.rb
Labels: PR: unreviewed

#17131 Expect to raise error should use a block
  spec/requests/admin/reactions_spec.rb
  spec/services/analytics_service_spec.rb
Labels: PR: partially-approved, merge by any core

#17129 Tiny cleanup of temp debugging puts from spec
  spec/liquid_tags/codesandbox_tag_spec.rb
Labels: PR: partially-approved, merge by any core

#17128 Re-arranging method to be less surprising
  app/controllers/async_info_controller.rb
Labels: PR: unreviewed

#17113 Conditionally rendering "Search > My Posts" by policy
  app/views/stories/articles_search/_nav_menu.html.erb
Labels: PR: reviewed-approved

#17141 Fix
  app/views/layouts/_nav_menu.html.erb
Labels: PR: partially-approved, tech: frontend

#17116 Better Error Msg when Listing URL embedded and Listings are disabled
  app/liquid_tags/unified_embed/tag.rb
  config/initializers/reserved_words.rb
  config/locales/liquid_tags/en.yml
  config/locales/liquid_tags/fr.yml
  spec/liquid_tags/unified_embed/tag_spec.rb
Labels: PR: partially-approved

#17147 Adding copy to assist with space toggle decision
  app/controllers/async_info_controller.rb
  app/views/admin/spaces/index.html.erb
Labels: PR: reviewed-approved

#17033 Add Data (User Details, Status, etc.) to the Member Index View Columns
  app/helpers/admin/users_helper.rb
  app/models/user.rb
  app/views/admin/users/_member_index.html.erb
  cypress/integration/seededFlows/adminFlows/users/userIndexView.spec.js
  spec/helpers/admin/users_helper_spec.rb
  spec/models/user_spec.rb
Labels: PR: unreviewed

#17143 Narrowing when we apply "hidden" by policy attributes
  app/helpers/application_helper.rb
  app/views/stories/tagged_articles/_sidebar.html.erb
  spec/helpers/application_helper_spec.rb
Labels: PR: reviewed-approved

#17155 Add Oauth check to AwardContributorFromGithub
  app/services/badges/award_contributor_from_github.rb
  spec/services/badges/award_contributor_from_github_spec.rb
Labels: PR: unreviewed

#17159 Issue template: Use label bug instead of type: bug
  .github/workflows/issue.yml
Labels: PR: reviewed-approved, merge by any core

#17156 Adding link to Spaces admin guide
  app/views/admin/spaces/index.html.erb
Labels: PR: partially-approved

#17132 Adjusting conditional create post rendering
  app/assets/javascripts/base.js.erb
  app/controllers/authorization/articles_controller.rb
  app/views/authorization/articles/create_post_button.html.erb
  app/views/layouts/_top_bar.html.erb
  config/routes.rb
  cypress/integration/seededFlows/policyFlows/limitPostCreationToAdmins.spec.js
  package.json
  spec/requests/authorization/articles_spec.rb
  spec/requests/root_page_spec.rb
  yarn.lock
Labels: PR: reviewed-approved

#17142 Refactor runtime to webpacker JS
  app/assets/javascripts/initializePage.js
  app/assets/javascripts/initializers/initializeCommentsPage.js.erb
  app/assets/javascripts/initializers/initializePodcastPlayback.js
  app/assets/javascripts/initializers/initializeSettings.js
  app/assets/javascripts/initializers/initializeVideoPlayback.js
  app/assets/javascripts/initializers/runtime.js
  app/javascript/article-form/articleForm.jsx
  app/javascript/article-form/components/ArticleCoverImage.jsx
  app/javascript/article-form/components/ImageUploader.jsx
  app/javascript/article-form/components/__tests__/ArticleCoverImage.test.jsx
  app/javascript/article-form/components/__tests__/ImageUploader.test.jsx
  app/javascript/crayons/MarkdownToolbar/markdownSyntaxFormatters.jsx
  app/javascript/mobile/foremMobile.js
  app/javascript/packs/articlePage.jsx
  app/javascript/packs/base.jsx
  app/javascript/packs/commentDropdowns.js
  app/javascript/runtimeBanner/RuntimeBanner.jsx
  app/javascript/utilities/runtime.js
  spec/system/podcasts/user_visits_podcast_episode_spec.rb
Labels: PR: partially-approved

#17150 Revalidate embedded links that redirect
  app/liquid_tags/unified_embed/tag.rb
  config/locales/liquid_tags/en.yml
  config/locales/liquid_tags/fr.yml
  spec/liquid_tags/loom_tag_spec.rb
  spec/liquid_tags/unified_embed/tag_spec.rb
  spec/support/embeds_helpers.rb
  spec/support/fixtures/vcr_cassettes/redirected_url_fetch.yml
Labels: PR: partially-approved

#17157 cache open graph response
  app/services/open_graph.rb
Labels: PR: unreviewed

#17171 use vcr on liquid tag spec
  spec/liquid_tags/unified_embed/tag_spec.rb
  spec/support/fixtures/vcr_cassettes/UnifiedEmbed_Tag/repeats_validation_when_link_returns_not-allowed.yml
Labels: PR: partially-approved

#17177 Refactor the way we show organizations on the member index view
  app/views/admin/users/_member_index.html.erb
  app/views/admin/users/index/_organizations.html.erb
Labels: PR: partially-approved

#17178 Admin member index: stop capitalizing table headers
  app/assets/stylesheets/components/tables.scss
  app/views/admin/users/_member_index.html.erb
Labels: PR: partially-approved

#17146 Member index: add copy email to clipboard functionality
  app/javascript/packs/admin/users/memberIndex.js
  app/javascript/utilities/dropdownUtils.js
  app/views/admin/users/_member_index.html.erb
  app/views/admin/users/index/_user_actions_dropdown.html.erb
  cypress/integration/seededFlows/adminFlows/users/userIndexView.spec.js
  cypress/integration/seededFlows/policyFlows/limitPostCreationToAdmins.spec.js
Labels: PR: partially-approved

#17181 Removing Listing rate limiting when feature disabled
  app/helpers/rate_limit_checker_helper.rb
  app/views/admin/settings/forms/_rate_limit.html.erb
  spec/helpers/rate_limit_checker_helper_spec.rb
Labels: PR: unreviewed

#17179 Admin member index: bring repeating layout code into partials
  app/views/admin/users/_member_index.html.erb
  app/views/admin/users/index/_member_data.html.erb
  app/views/admin/users/index/_organizations.html.erb
  app/views/admin/users/index/_status_indicator.html.erb
Labels: PR: unreviewed

#17187 Enable :profile_admin feature flag
  lib/data_update_scripts/20220408154416_enable_profile_admin_feature.rb
  spec/lib/data_update_scripts/enable_profile_admin_feature_spec.rb
Labels: PR: partially-approved

#17138 Remove guard clauses for profile admin feature flag
  app/models/admin_menu.rb
  config/routes/admin.rb
  spec/models/admin_menu_spec.rb
  spec/models/profile_field_group_spec.rb
  spec/requests/admin/nested_sidebar_spec.rb
  spec/requests/admin/profile_field_groups_spec.rb
  spec/requests/admin/profile_fields_spec.rb
  spec/routing/profile_admin_routes_spec.rb
  spec/system/admin/admin_manages_profile_fields_spec.rb
  spec/system/user/user_edits_profile_spec.rb
Labels: PR: reviewed-approved

#17184 Produce a meaningful slug from podcast episode title
  app/services/podcasts/create_episode.rb
  spec/services/podcasts/create_episode_spec.rb
  spec/support/fixtures/podcasts/design_takoy.rss
Labels: PR: reviewed-approved

#17182 Conditionally removing listing from Admin > Consumer Apps menu
  app/models/admin_menu.rb
  spec/models/admin_menu_spec.rb
Labels: PR: reviewed-approved

#17172 fix: 🐛 Fix Color displaying over button in settings
  app/javascript/packs/stickySaveFooter.js
Labels: PR: reviewed-approved

#17199 Use the latest repo URLs in package.json
  package.json
Labels: PR: reviewed-approved

#17185 Set default box-sizing
  app/assets/stylesheets/base/reset.scss
Labels: PR: unreviewed, tech: frontend

#17195 Use correct trademarks in supported embeds
  app/views/pages/_editor_liquid_help.html.erb
  app/views/pages/_supported_url_embeds_list.html.erb
Labels: PR: reviewed-approved

#17198 Remove unused articles/_splash.html.erb
  app/views/articles/_splash.html.erb
Labels: PR: reviewed-approved

#17194 Remove profile admin feature flag
  lib/data_update_scripts/20220408203135_remove_profile_admin_flag.rb
  spec/lib/data_update_scripts/remove_profile_admin_flag_spec.rb
  spec/models/admin_menu_spec.rb
  spec/requests/admin/nested_sidebar_spec.rb
  spec/routing/profile_admin_routes_spec.rb
Labels: PR: partially-approved

#17219 Replace #to_s(:format) with #to_fs
  app/views/articles/feed.rss.builder
Labels: PR: reviewed-approved

#17211 Conditionally removing listing reference
  app/views/mailers/notify_mailer/new_badge_email.html.erb
  app/views/mailers/notify_mailer/new_badge_email.text.erb
  app/views/notifications/_badgeachievement.html.erb
Labels: PR: reviewed-approved

#17165 Disable flakey admin charts spec
  spec/services/admin/charts_data_spec.rb
Labels: PR: reviewed-approved, merge by any core

#17218 Member Index View: Role Tooltip Refactor Follow-Up
  app/views/admin/users/index/_member_data.html.erb
Labels: PR: partially-approved

#17149 Adding logic to hide Create Post on empty dashboard
  app/views/dashboards/show.html.erb
  spec/views/dashboards/show.html.erb_spec.rb
Labels: PR: partially-approved

#17207 Update table style for member index view
  app/assets/stylesheets/components/tables.scss
  app/assets/stylesheets/config/_generator.scss
  app/views/admin/users/_member_index.html.erb
Labels: PR: partially-approved

#17180 Admin member index: invitations table
  app/views/admin/invitations/index.html.erb
Labels: PR: reviewed-approved

#16437 Conditionally disabling Listings (Waiting on Product but technically Good to Go)
  app/models/listing.rb
  cypress/integration/seededFlows/adminFlows/apps/editListingCategory.spec.js
  cypress/integration/seededFlows/homeFeedFlows/feedNavigation.spec.js
  cypress/integration/seededFlows/listingFlows/deleteListing.spec.js
  cypress/integration/seededFlows/listingFlows/viewListing.spec.js
  spec/liquid_tags/unified_embed/tag_spec.rb
  spec/rails_helper.rb
Labels: PR: partially-approved, changelog: rollup

#17196 Tweak z-index for buttons in liquid tags
  app/assets/stylesheets/ltags/GithubTag.scss
  app/assets/stylesheets/ltags/StackexchangeTag.scss
  app/assets/stylesheets/ltags/TwitterTimelineTag.scss
Labels: PR: partially-approved

#17210 Member index (phase 2) - Search invitations
  app/controllers/admin/invitations_controller.rb
  app/models/user.rb
  app/views/admin/invitations/index.html.erb
  app/views/admin/users/index/_controls.html.erb
  app/views/admin/users/index/_search_field.html.erb
  cypress/integration/seededFlows/adminFlows/users/invitedUsers.spec.js
  cypress/support/commands.js
Labels: PR: reviewed-approved

#17217 First version of exporting the Users to a CSV
  app/controllers/admin/users_controller.rb
  app/helpers/admin/users_helper.rb
  app/views/admin/users/_member_index.html.erb
  app/views/admin/users/export.csv.erb
  app/views/admin/users/index/_controls.html.erb
  app/views/admin/users/index/controls/_export.html.erb
  config/routes/admin.rb
  spec/factories/users.rb
  spec/helpers/admin/users_helper_spec.rb
  spec/requests/admin/users/users_export_spec.rb
Labels: PR: unreviewed

#17252 Add Internationalization to Admin::UsersController Success Messages
  app/controllers/admin/users_controller.rb
  config/locales/controllers/admin/en.yml
  config/locales/controllers/admin/fr.yml
Labels: PR: partially-approved

#17251 Refactor Member Index View Users Query
  app/controllers/admin/users_controller.rb
  app/views/admin/users/_member_index.html.erb
Labels: PR: reviewed-approved

#17258 Fixed Typo
  app/views/admin/users/show/profile/actions/_export.html.erb
Labels: PR: partially-approved, merge by any core

#17221 Add minimal test on rss feed response
  spec/requests/articles/articles_feed_spec.rb
Labels: PR: reviewed-approved

#17263 Disable two time zone sensitive tests
  spec/requests/admin/overview_spec.rb
Labels: PR: reviewed-approved

#17261 Show a "Unable to login" message in browser when a user is unable to login.
  config/locales/devise.en.yml
  spec/system/authentication/user_logs_in_with_email_spec.rb
  spec/system/user_logs_in_with_password_spec.rb
Labels: PR: unreviewed

#17266 Move showModal/closeModal helpers into their own pack file
  app/javascript/packs/base.jsx
  app/javascript/utilities/showModal.jsx
Labels: PR: partially-approved

#17248 Adding Feed Configuration documentation
  config/feed/README.md
Labels: PR: unreviewed

#17189 Refactor: Move onboarding routes out of UsersController
  app/controllers/users/onboardings_controller.rb
  app/controllers/users_controller.rb
  config/routes.rb
Labels: PR: partially-approved

#17246 Admin member index - minor UI/a11y fixes
  app/views/admin/invitations/index.html.erb
  app/views/admin/users/_member_index.html.erb
  app/views/admin/users/index/_controls.html.erb
  app/views/admin/users/index/_filter_role_field.html.erb
  app/views/admin/users/index/_member_data.html.erb
  app/views/admin/users/index/_search_field.html.erb
  app/views/kaminari/admin/_next_page.html.erb
  app/views/kaminari/admin/_paginator.html.erb
  app/views/kaminari/admin/_prev_page.html.erb
Labels: PR: reviewed-approved

#17213 Member index (Phase 2) - Invitations actions
  app/assets/images/send.svg
  app/controllers/admin/invitations_controller.rb
  app/views/admin/invitations/index.html.erb
  config/feed/README.md
  config/locales/controllers/admin/en.yml
  config/locales/controllers/admin/fr.yml
  config/routes/admin.rb
  cypress/integration/seededFlows/adminFlows/users/invitedUsers.spec.js
  spec/requests/admin/invitations_spec.rb
Labels: PR: unreviewed

#17212 Crayons Toggle Update
  app/assets/stylesheets/components/toggles.scss
  app/javascript/crayons/formElements/Toggles/Toggle.jsx
  app/javascript/crayons/formElements/Toggles/__stories__/Toggles.stories.jsx
  app/javascript/crayons/formElements/Toggles/__tests__/__snapshots__/Toggle.test.jsx.snap
Labels: PR: partially-approved

#17092 Fix duplicate IDs on homepage
  app/assets/javascripts/initializers/initializeReadingListIcons.js
  app/views/admin/navigation_links/index.html.erb
  app/views/articles/_sidebar.html.erb
  app/views/layouts/_main_nav.html.erb
  app/views/layouts/_sidebar_nav_link.html.erb
  app/views/shared/_hamburger.html.erb
  spec/system/homepage/user_visits_homepage_spec.rb
Labels: PR: partially-approved

#17284 Resolve yarn lockfile
  yarn.lock
Labels: PR: partially-approved, merge by any core

#17286 Fix broken favicons in embeds of other Forem URLs
  app/assets/stylesheets/base/typography.scss
  app/views/liquids/_open_graph.html.erb
Labels: PR: partially-approved

#17259 Adding a modal for the CSV export
  app/assets/images/export.svg
  app/controllers/admin/users_controller.rb
  app/javascript/packs/admin/users/memberIndex.js
  app/views/admin/users/_member_index.html.erb
  app/views/admin/users/index/_controls.html.erb
  app/views/admin/users/index/controls/_export.html.erb
  cypress/integration/seededFlows/adminFlows/users/userIndexView.spec.js
Labels: PR: partially-approved

#17280 Correcting public_reactions_count
  app/services/articles/feeds/weighted_query_strategy.rb
Labels: PR: reviewed-approved

#17294 Ensuring /new remains a call to action end point for DEV
  app/controllers/articles_controller.rb
  app/services/articles/builder.rb
  cypress/integration/seededFlows/loginFlows/userLogin.spec.js
  spec/requests/editor_spec.rb
  spec/services/articles/builder_spec.rb
Labels: PR: unreviewed

#17287 Admin member index: style the GDPR requests table
  app/views/admin/users/gdpr_delete_requests/index.html.erb
Labels: PR: partially-approved

#17305 Escape user-supplied regex terms
  app/models/settings/rate_limit.rb
Labels: PR: partially-approved

#17302 Update builder spec variable names
  spec/services/articles/builder_spec.rb
Labels: PR: reviewed-approved, merge by any core

#17235 Remove references to article.spaminess_rating
  app/lib/black_box.rb
  app/models/article.rb
  app/services/articles/feeds/weighted_query_strategy.rb
  app/workers/comments/calculate_score_worker.rb
  spec/lib/black_box_spec.rb
  spec/workers/articles/score_calc_worker_spec.rb
  spec/workers/comments/calculate_score_worker_spec.rb
Labels: PR: unreviewed

#17243 Context Notifications
  app/models/article.rb
  app/models/context_notification.rb
  app/services/articles/updater.rb
  app/services/notifications/notifiable_action/send.rb
  db/migrate/20220401071321_create_context_notifications.rb
  db/schema.rb
  spec/factories/context_notifications.rb
  spec/models/article_spec.rb
  spec/models/context_notification_spec.rb
  spec/services/articles/updater_spec.rb
  spec/services/notifications/notifiable_action/send_spec.rb
Labels: PR: partially-approved

#17319 Replace links to the repo with newer URLs
  app/controllers/articles_controller.rb
  app/controllers/comments_controller.rb
  app/controllers/omniauth_callbacks_controller.rb
  spec/models/article_spec.rb
Labels: PR: reviewed-approved

#17320 Avoid redirection by replacing with newer URL
  app/lib/constants/settings/general.rb
Labels: PR: reviewed-approved

#17321 Replace Git URL with the new one
  scripts/clean_fork.sh
  scripts/sync_fork.sh
Labels: PR: partially-approved

#17328 Enable error tracking on sendFollowUser
  app/javascript/utilities/sendFollowUser.js
Labels: PR: partially-approved

#17278 Admin member index: invitations responsive layout
  app/views/admin/invitations/index.html.erb
  app/views/admin/users/_member_index.html.erb
  app/views/admin/users/index/_controls.html.erb
  app/views/admin/users/index/_expand_search_button.html.erb
  app/views/admin/users/index/_invitation_actions_dropdown.html.erb
  app/views/admin/users/index/_member_data.html.erb
  app/views/admin/users/index/_member_image.html.erb
  cypress/integration/seededFlows/adminFlows/users/invitedUsers.spec.js
Labels: PR: partially-approved

#17308 Adjusting feed query to establish a new incumbent
  app/services/articles/feeds/weighted_query_strategy.rb
  config/field_test.yml
Labels: PR: partially-approved

#17205 Update jQuery from 3.3.1 to 3.6.0 on /videos/new
  app/views/videos/new.html.erb
Labels: PR: partially-approved

#17345 Removing unclosed div tag
  app/views/stories/tagged_articles/_sidebar.html.erb
Labels: PR: partially-approved

#17351 Adding fw-heavy to spaces H1
  app/views/admin/spaces/index.html.erb
Labels: PR: partially-approved

#17314 Introducing the Articles::Feeds configurations
  app/models/articles/feeds.rb
  app/models/articles/feeds/README.md
  app/models/articles/feeds/lever_catalog_builder.rb
  app/models/articles/feeds/order_by_lever.rb
  app/models/articles/feeds/relevancy_lever.rb
  app/models/articles/feeds/variant_assembler.rb
  app/services/articles/feeds.rb
  config/feed-variants/20220415-incumbent.json
  spec/models/articles/feeds/lever_catalog_builder_spec.rb
  spec/models/articles/feeds/order_by_lever_spec.rb
  spec/models/articles/feeds/relevancy_lever_spec.rb
  spec/models/articles/feeds/variant_assembler_spec.rb
  spec/models/articles/feeds_spec.rb
Labels: PR: partially-approved

#17339 Limit an organizations displayed and add an overflow count
  app/controllers/admin/users_controller.rb
  app/helpers/admin/users_helper.rb
  app/views/admin/users/_member_index.html.erb
  app/views/admin/users/index/_organizations.html.erb
  spec/helpers/admin/users_helper_spec.rb
Labels: PR: partially-approved

#17375 Add an aria-hidden attribute
  app/views/admin/users/index/controls/_export.html.erb
Labels: PR: reviewed-approved

#17372 Update chevron left SVG
  app/assets/images/chevron-left.svg
Labels: PR: partially-approved, merge by any core

#17370 Member index: update the organizations UI
  app/assets/stylesheets/config/_generator.scss
  app/views/admin/users/index/_organizations.html.erb
  cypress/integration/seededFlows/adminFlows/users/userIndexView.spec.js
  spec/support/seeds/seeds_e2e.rb
Labels: PR: partially-approved

#17309 Enable string uuid as namespace
  config/initializers/new_framework_defaults_7_0.rb
Labels: PR: unreviewed

#17341 Fix bug in search and filter indicators (admin member index)
  app/javascript/packs/admin/users/controls.js
  app/views/admin/users/index/_controls.html.erb
  app/views/admin/users/index/_expand_search_button.html.erb
  cypress/integration/seededFlows/adminFlows/users/userIndexView.spec.js
Labels: PR: partially-approved

#17384 Busting tag cache when space changes
  app/models/space.rb
  app/workers/spaces/bust_caches_for_space_change_worker.rb
  spec/models/space_spec.rb
  spec/workers/spaces/bust_caches_for_space_change_worker_spec.rb
Labels: PR: reviewed-approved

#17367 Remove DISABLE_SPRING variables after PR#16848
  .gitpod.yml
  .travis.yml
Labels: PR: partially-approved

#17368 Update cypress from 8.7.0 to 9.5.4
  package.json
  yarn.lock
Labels: PR: partially-approved

#17385 Wait for pin article to complete (flaky pinArticles e2e test)
  cypress/integration/seededFlows/adminFlows/articles/pinArticle.spec.js
Labels: PR: reviewed-approved

#17387 e2e: Reload the page after changing authentication
  cypress/integration/seededFlows/adminFlows/config/authenticationSection.spec.js
Labels: PR: unreviewed

#17392 Confirm signout happened by looking for Log in link
  cypress/integration/seededFlows/adminFlows/articles/pinArticle.spec.js
Labels: PR: reviewed-approved

#17379 Skip rescoring draft articles
  app/workers/moderator/sink_articles_worker.rb
  spec/workers/moderator/sink_articles_worker_spec.rb
Labels: PR: reviewed-approved

#17317 Update sort to have nulls at last
  app/models/article.rb
Labels: PR: partially-approved

#17399 Remove @storybook/addon-notes 5 from devDependencies
  app/javascript/.storybook/main.js
  package.json
  yarn.lock
Labels: PR: partially-approved

#17400 Update @testing-library/cypress from 7.0.7 to 8.0.2
  package.json
  yarn.lock
Labels: PR: partially-approved

#17391 Update Bootstrap from 4.4.1 to 4.5.3
  app/views/layouts/admin.html.erb
Labels: PR: partially-approved

#17404 Disable creator onboarding feature flag
  lib/data_update_scripts/20220422141135_disable_creator_onboarding_feature_flag.rb
  spec/lib/data_update_scripts/disable_creator_onboarding_feature_flag_spec.rb
Labels: PR: reviewed-approved

#17403 Reference checkboxes by name in creatorSettings spec
  cypress/integration/creatorOnboardingFlows/creatorSettings.spec.js
Labels: PR: reviewed-approved, merge by any core

#17405 Remove redundant feat flag setup in spec
  spec/system/user_views_logo_spec.rb
Labels: PR: reviewed-approved, merge by any core

#17407 Adjusting copy per guidance
  app/views/admin/spaces/index.html.erb
Labels: PR: reviewed-approved

#17396 Tidying up the Articles::Feeds::VariantQuery
  app/services/articles/feeds/variant_query.rb
  spec/services/articles/feeds/variant_query_spec.rb
Labels: PR: partially-approved

#17388 DO NOT MERGE: Remove the Member Index View Feature Flags + old code
  app/queries/admin/users_query.rb
  app/views/admin/invitations/index.html.erb
  app/views/admin/users/_member_index.html.erb
  app/views/admin/users/controls/_expand_search_button.html.erb
  app/views/admin/users/controls/_export.html.erb
  app/views/admin/users/controls/_filter_role_field.html.erb
  app/views/admin/users/controls/_search_field.html.erb
  app/views/admin/users/gdpr_delete_requests/index.html.erb
  app/views/admin/users/index.html.erb
  app/views/admin/users/index/_controls.html.erb
  cypress/integration/seededFlows/adminFlows/users/invitedUsers.spec.js
  cypress/integration/seededFlows/adminFlows/users/manageCredits.spec.js
  cypress/integration/seededFlows/adminFlows/users/userIndexView.spec.js
Labels: PR: partially-approved

#17406 Create new feed-variant 20220422
  app/models/articles/feeds.rb
  config/feed-variants/20220422-jennie-variant.json
  config/field_test.yml
Labels: PR: partially-approved

#17414 Removing unused instance variable
  app/controllers/stories/articles_search_controller.rb
  app/controllers/stories/tagged_articles_controller.rb
  app/controllers/stories_controller.rb
Labels: PR: reviewed-approved

#17419 Multi-select autocomplete - ignore fetched suggestions if input already cleared
  app/javascript/crayons/MultiSelectAutocomplete/MultiSelectAutocomplete.jsx
Labels: PR: partially-approved

#17395 Permanently delete users from Mailchimp automatically
  app/models/user.rb
  app/services/mailchimp/bot.rb
  app/services/moderator/banish_user.rb
  app/services/users/delete.rb
  config/locales/services/en.yml
  config/locales/services/fr.yml
  spec/services/mailchimp/bot_spec.rb
Labels: PR: partially-approved

#17085 controllers/admin i18n
  app/controllers/admin/articles_controller.rb
  app/controllers/admin/badge_achievements_controller.rb
  app/controllers/admin/badges_controller.rb
  app/controllers/admin/broadcasts_controller.rb
  app/controllers/admin/consumer_apps_controller.rb
  app/controllers/admin/display_ads_controller.rb
  app/controllers/admin/html_variants_controller.rb
  app/controllers/admin/invitations_controller.rb
  app/controllers/admin/listing_categories_controller.rb
  app/controllers/admin/listings_controller.rb
  app/controllers/admin/mods_controller.rb
  app/controllers/admin/navigation_links_controller.rb
  app/controllers/admin/organization_memberships_controller.rb
  app/controllers/admin/organizations_controller.rb
  app/controllers/admin/pages_controller.rb
  app/controllers/admin/podcasts_controller.rb
  app/controllers/admin/profile_field_groups_controller.rb
  app/controllers/admin/profile_fields_controller.rb
  app/controllers/admin/response_templates_controller.rb
  app/controllers/admin/secrets_controller.rb
  app/controllers/admin/settings/base_controller.rb
  app/controllers/admin/settings/general_settings_controller.rb
  app/controllers/admin/settings_controller.rb
  app/controllers/admin/sponsorships_controller.rb
  app/controllers/admin/tags/moderators_controller.rb
  app/controllers/admin/tags_controller.rb
  app/controllers/admin/tools_controller.rb
  app/controllers/admin/users_controller.rb
  app/controllers/admin/welcome_controller.rb
  config/locales/controllers/admin/en.yml
  config/locales/controllers/admin/fr.yml
  config/locales/en.yml
  config/locales/fr.yml
  cypress/integration/seededFlows/adminFlows/users/manageUserOptions.spec.js
Labels: PR: partially-approved

#17440 Updating Rails dependency per CVE
  Gemfile.lock
  vendor/cache/actioncable-7.0.2.3.gem
  vendor/cache/actioncable-7.0.2.4.gem
  vendor/cache/actionmailbox-7.0.2.3.gem
  vendor/cache/actionmailbox-7.0.2.4.gem
  vendor/cache/actionmailer-7.0.2.3.gem
  vendor/cache/actionmailer-7.0.2.4.gem
  vendor/cache/actionpack-7.0.2.3.gem
  vendor/cache/actionpack-7.0.2.4.gem
  vendor/cache/actiontext-7.0.2.3.gem
  vendor/cache/actiontext-7.0.2.4.gem
  vendor/cache/actionview-7.0.2.3.gem
  vendor/cache/actionview-7.0.2.4.gem
  vendor/cache/activejob-7.0.2.3.gem
  vendor/cache/activejob-7.0.2.4.gem
  vendor/cache/activemodel-7.0.2.3.gem
  vendor/cache/activemodel-7.0.2.4.gem
  vendor/cache/activerecord-7.0.2.3.gem
  vendor/cache/activerecord-7.0.2.4.gem
  vendor/cache/activestorage-7.0.2.3.gem
  vendor/cache/activestorage-7.0.2.4.gem
  vendor/cache/activesupport-7.0.2.3.gem
  vendor/cache/activesupport-7.0.2.4.gem
  vendor/cache/io-wait-0.2.1.gem
  vendor/cache/net-protocol-0.1.2.gem
  vendor/cache/net-protocol-0.1.3.gem
  vendor/cache/rails-7.0.2.3.gem
  vendor/cache/rails-7.0.2.4.gem
  vendor/cache/railties-7.0.2.3.gem
  vendor/cache/railties-7.0.2.4.gem
Labels: PR: partially-approved

#17439 validate sort direction
  app/controllers/search_controller.rb
  app/queries/homepage/articles_query.rb
  app/services/search/article.rb
  spec/requests/search_spec.rb
Labels: PR: partially-approved

#17413 Fixed a grammatical error.
  config/locales/views/stories/en.yml
  config/locales/views/stories/fr.yml
  spec/requests/stories/tagged_articles_spec.rb
Labels: PR: reviewed-approved

#17449 Don't create podcast episodes without any media
  app/services/podcasts/create_episode.rb
  spec/services/podcasts/create_episode_spec.rb
  spec/support/fixtures/podcasts/codepunk.rss
Labels: PR: partially-approved

#17329 Refactor OnboardingsController
  app/controllers/onboardings_controller.rb
  app/controllers/users/onboardings_controller.rb
  app/javascript/onboarding/components/FollowTags.jsx
  app/javascript/onboarding/components/FollowUsers.jsx
  app/javascript/onboarding/components/ProfileForm.jsx
  app/javascript/onboarding/utilities.js
  app/views/articles/index.html.erb
  app/views/users/onboardings/_task_card.html.erb
  app/views/users/onboardings/show.html.erb
  config/routes.rb
  spec/requests/users_onboarding_spec.rb
Labels: PR: unreviewed

#17497 fix typo in constant name
  app/controllers/admin/users_controller.rb
Labels: PR: reviewed-approved

#17501 Replace git.io URL
  .github/workflows/codeql-analysis.yml
  spec/models/podcast_spec.rb
Labels: PR: reviewed-approved

#17293 Hide 'Save' button on posts that belong to the current user
  app/assets/javascripts/initializers/initScrolling.js
  app/assets/javascripts/utilities/buildArticleHTML.js
  app/javascript/articles/Article.jsx
  app/javascript/articles/__tests__/Article.test.jsx
  app/javascript/articles/components/SaveButton.jsx
  app/javascript/articles/components/__tests__/SaveButton.test.jsx
  app/javascript/packs/hideBookmarkButtons.js
  app/javascript/packs/homePageFeed.jsx
  app/javascript/packs/searchParams.js
  app/views/articles/_single_story.html.erb
  app/views/collections/show.html.erb
  app/views/organizations/show.html.erb
  app/views/stories/tagged_articles/index.html.erb
  app/views/users/show.html.erb
Labels: PR: partially-approved

#17402 Add prop for user-defined selections in MultiSelectAutocomplete
  app/javascript/article-form/components/TagsField.jsx
  app/javascript/crayons/MultiSelectAutocomplete/MultiSelectAutocomplete.jsx
  app/javascript/crayons/MultiSelectAutocomplete/__stories__/MultiSelectAutocomplete.mdx
  app/javascript/crayons/MultiSelectAutocomplete/__stories__/MultiSelectAutocomplete.stories.jsx
  app/javascript/crayons/MultiSelectAutocomplete/__tests__/MultiSelectAutocomplete.test.jsx
  app/javascript/listings/components/ListingTagsField.jsx
Labels: PR: partially-approved

#17511 Add search by email back
  app/queries/admin/users_query.rb
  app/views/admin/users/index/_controls.html.erb
  cypress/integration/seededFlows/adminFlows/users/userIndexView.spec.js
Labels: PR: partially-approved, merge by any core

#17500 Sharpen RegEx that matches Forem-specific links
  app/liquid_tags/forem_tag.rb
  spec/liquid_tags/unified_embed/registry_spec.rb
Labels: PR: partially-approved

#17513 Show Series counts on all Dashboard Tabs
  app/controllers/dashboards_controller.rb
  spec/system/dashboards/user_visits_dashboard_spec.rb
Labels: PR: reviewed-approved

#17516 Removing unused feature flag reference
  spec/requests/stories/feeds_spec.rb
Labels: PR: reviewed-approved

#17514 Remove sustaining member newsletter, and its settings
  app/controllers/incoming_webhooks/mailchimp_unsubscribes_controller.rb
  app/lib/constants/settings/general.rb
  app/models/settings/general.rb
  app/models/user.rb
  app/services/mailchimp/bot.rb
  app/views/admin/settings/forms/_newsletter.html.erb
  app/views/users/_notifications.html.erb
  config/locales/helpers/en.yml
  config/locales/helpers/fr.yml
  lib/data_update_scripts/20220429142653_remove_mailchimp_sustaining_members_newsletter.rb
  spec/lib/data_update_scripts/remove_mailchimp_sustaining_members_newsletter_spec.rb
  spec/requests/admin/configs_spec.rb
Labels: PR: partially-approved

#17515 drop monthly dues from users
  db/migrate/20220429150448_drop_monthly_dues_from_users.rb
  db/schema.rb
Labels: PR: partially-approved

#17517 Update readme
  README.md
Labels: PR: partially-approved, merge by any core

#17394 Community Wellness badge
  app/queries/comments/community_wellness_query.rb
  app/services/badges/award_community_wellness.rb
  config/locales/services/en.yml
  config/locales/services/fr.yml
  config/schedule.yml
  spec/queries/comments/community_wellness_query_spec.rb
  spec/rails_helper.rb
  spec/services/badges/award_community_wellness_spec.rb
  spec/support/comments_helper.rb
Labels: PR: partially-approved

#17527 Ignore CVE-2022-27311
  .travis.yml
Labels: PR: partially-approved, merge by any core
