Repository forem/forem, pull requests merged in 2022-02, with the labels that each got.

#16376 ✂️ ✂️ Removed the Connect feature flag from seed data ✂️ ✂️
  spec/support/seeds/seeds_e2e.rb
Labels: area: tests, PR: partially-approved, merge by any core, tech: backend

#16377 seeds.rb: Add registered_at to admin user to fix setup seed issue.
  db/seeds.rb
Labels: PR: partially-approved

#16268 Make home link an admin-customisable navigation link
  app/views/layouts/_main_nav.html.erb
  lib/data_update_scripts/20220126102900_create_home_navigation_link.rb
  lib/tasks/add_navigation_links.rake
  spec/lib/data_update_scripts/create_home_navigation_link_spec.rb
  spec/system/homepage/user_visits_homepage_spec.rb
  spec/tasks/add_navigation_links_spec.rb
Labels: PR: partially-approved

#16381 Fixes for home nav link positioning
  lib/data_update_scripts/20220201114309_update_home_navigation_link_position.rb
  lib/tasks/add_navigation_links.rake
  spec/lib/data_update_scripts/update_home_navigation_link_position_spec.rb
Labels: PR: partially-approved

#16373 Ensure the domain of two faker generated urls are distinct
  spec/services/analytics_service_spec.rb
Labels: PR: reviewed-approved, merge by any core

#16378 Implement Unified Embeds for Glitch URLs
  app/liquid_tags/glitch_tag.rb
  spec/liquid_tags/unified_embed/registry_spec.rb
Labels: PR: unreviewed

#16362 Adding conditional rendering of navigation links
  app/helpers/application_helper.rb
  app/views/layouts/_main_nav.html.erb
  app/views/layouts/_sidebar_nav_link.html.erb
  spec/helpers/application_helper_spec.rb
Labels: PR: reviewed-approved

#16388 Add "aggregate_failures" metadata to Registry Specs with loops
  spec/liquid_tags/unified_embed/registry_spec.rb
Labels: PR: partially-approved

#16314 Allow users to pause gifs in a post
  app/assets/images/pause.svg
  app/assets/images/play.svg
  app/assets/stylesheets/article-show.scss
  app/assets/stylesheets/base/reset.scss
  app/assets/stylesheets/config/_colors.css
  app/javascript/packs/articlePage.jsx
  app/javascript/utilities/animatedImageUtils.jsx
  cypress/integration/seededFlows/articleFlows/playOrPauseAnimatedImages.spec.js
  package.json
  public/media/test-image.gif
  yarn.lock
Labels: PR: partially-approved, area: images, tech: frontend

#16383 Applying Crayons to some Customization pages
  app/views/admin/display_ads/_form.html.erb
  app/views/admin/display_ads/edit.html.erb
  app/views/admin/display_ads/new.html.erb
  app/views/admin/html_variants/_form.html.erb
  app/views/admin/html_variants/edit.html.erb
  app/views/admin/html_variants/new.html.erb
  app/views/admin/navigation_links/_add_navigation_link_modal.html.erb
  app/views/admin/navigation_links/_edit_navigation_link_modal.html.erb
  app/views/admin/navigation_links/_form.html.erb
  app/views/admin/navigation_links/index.html.erb
  app/views/admin/pages/_form.html.erb
  cypress/integration/seededFlows/adminFlows/navigationLinks/navigationLinks.spec.js
  cypress/integration/seededFlows/adminFlows/pages/landingPage.spec.js
Labels: PR: unreviewed, tech: frontend

#16382 Avoid Intent redirect on Runtime Banner for the DEV Android app context
  app/javascript/runtimeBanner/RuntimeBanner.jsx
Labels: PR: partially-approved, merge by any core

#16395 Improved article date specs
  spec/models/article_spec.rb
Labels: PR: partially-approved

#16397 Change UI instances of "vomit" to "flag"
  app/components/admin/users/tools/reactions_component.html.erb
  app/javascript/admin/controllers/reaction_controller.js
  app/views/admin/feedback_messages/_abuse_reports.html.erb
  app/views/admin/privileged_reactions/index.html.erb
  app/views/admin/users/_negative_reactions.html.erb
  app/views/notifications/shared/_comment_box.html.erb
  config/locales/views/moderations/en.yml
  config/locales/views/moderations/fr.yml
  config/locales/views/reactions/en.yml
  config/locales/views/reactions/fr.yml
  cypress/integration/seededFlows/adminFlows/users/memberToolsSection.spec.js
  spec/components/admin/users/tools/reactions_component_spec.rb
Labels: PR: partially-approved

#16075 Add boolean attribute main_image_from_frontmatter to indicate if cove…
  app/models/article.rb
  db/migrate/20220111140539_add_main_image_from_frontmatter_to_articles.rb
  db/schema.rb
  lib/data_update_scripts/20220120052641_backfill_column_main_image_from_frontmatter.rb
  spec/factories/articles.rb
  spec/lib/data_update_scripts/backfill_column_main_image_from_frontmatter_spec.rb
  spec/models/article_spec.rb
Labels: PR: unreviewed

#16404 Place gifs correctly regardless of center tag
  app/assets/stylesheets/article-show.scss
  app/javascript/utilities/animatedImageUtils.jsx
Labels: PR: partially-approved, merge by any core

#16405 Fix flake in top tags test
  cypress/integration/seededFlows/publishingFlows/addTagsToArticle.spec.js
Labels: PR: partially-approved

#16403 Reorganized article published_at/dates specs
  spec/models/article_spec.rb
Labels: PR: reviewed-approved

#16407 Bypassing validiation for data script
  lib/data_update_scripts/20220120052641_backfill_column_main_image_from_frontmatter.rb
  lib/data_update_scripts/20220203165540_update_article_cached_attribute_around_main_image.rb
  spec/lib/data_update_scripts/update_article_cached_attribute_around_main_image_spec.rb
Labels: PR: unreviewed

#16126 app/controllers & decorators i18n
  app/controllers/api_secrets_controller.rb
  app/controllers/application_controller.rb
  app/controllers/article_approvals_controller.rb
  app/controllers/articles_controller.rb
  app/controllers/comments_controller.rb
  app/controllers/concerns/image_uploads.rb
  app/controllers/confirmations_controller.rb
  app/controllers/credits_controller.rb
  app/controllers/devices_controller.rb
  app/controllers/discussion_locks_controller.rb
  app/controllers/email_subscriptions_controller.rb
  app/controllers/feedback_messages_controller.rb
  app/controllers/follows_controller.rb
  app/controllers/github_repos_controller.rb
  app/controllers/image_uploads_controller.rb
  app/controllers/listings_controller.rb
  app/controllers/omniauth_callbacks_controller.rb
  app/controllers/organizations_controller.rb
  app/controllers/pages_controller.rb
  app/controllers/podcasts_controller.rb
  app/controllers/profile_pins_controller.rb
  app/controllers/profiles_controller.rb
  app/controllers/rating_votes_controller.rb
  app/controllers/registrations_controller.rb
  app/controllers/response_templates_controller.rb
  app/controllers/social_previews_controller.rb
  app/controllers/stories/articles_search_controller.rb
  app/controllers/stories/pinned_articles_controller.rb
  app/controllers/stories_controller.rb
  app/controllers/stripe_active_cards_controller.rb
  app/controllers/tag_adjustments_controller.rb
  app/controllers/tags_controller.rb
  app/controllers/users/settings_controller.rb
  app/controllers/users_controller.rb
  app/controllers/video_states_controller.rb
  app/decorators/article_decorator.rb
  app/decorators/comment_decorator.rb
  app/decorators/podcast_episode_decorator.rb
  app/decorators/user_decorator.rb
  app/services/users/update.rb
  app/views/layouts/application.html.erb
  config/locales/concerns/en.yml
  config/locales/concerns/fr.yml
  config/locales/controllers/en.yml
  config/locales/controllers/fr.yml
  config/locales/decorators/en.yml
  config/locales/decorators/fr.yml
  config/locales/en.yml
  config/locales/fr.yml
  config/locales/views/comments/en.yml
  config/locales/views/comments/fr.yml
  spec/system/authentication/user_request_confirmation_spec.rb
Labels: PR: partially-approved

#16414 I18n's short format for times differs from "%b %e", update test
  spec/models/article_spec.rb
Labels: PR: reviewed-approved

#16358 Copy organization secret code to clipboard
  app/assets/javascripts/initializers/initializeSettings.js
  app/views/users/_org_admin.html.erb
  config/locales/views/settings/en.yml
  config/locales/views/settings/fr.yml
  cypress/integration/seededFlows/settingsFlows/organisationSecretCode.spec.js
Labels: PR: partially-approved

#16375 Applying Crayons to Content Manager pages
  app/views/admin/badge_achievements/award.html.erb
  app/views/admin/badge_achievements/index.html.erb
  app/views/admin/badges/edit.html.erb
  app/views/admin/badges/index.html.erb
  app/views/admin/badges/new.html.erb
  app/views/admin/comments/index.html.erb
  app/views/admin/podcasts/edit.html.erb
  app/views/admin/shared/_tabbed_navbar.html.erb
Labels: PR: unreviewed, area: admin, PR: draft, PR: partially-approved, tech: frontend

#16412 Reworked some webpack aliases as prework for the new admin member detail view
  app/javascript/.eslintrc.js
  app/javascript/packs/base.jsx
  config/webpack/environment.js
  jsconfig.json
Labels: PR: unreviewed, tech: frontend, merge by any core

#16408 A suspended user returns 403 instead of 500
  app/controllers/application_controller.rb
  app/controllers/articles_controller.rb
  app/controllers/listings_controller.rb
  app/controllers/users/notification_settings_controller.rb
  app/controllers/users/settings_controller.rb
  app/controllers/users_controller.rb
  app/errors/suspended_error.rb
  app/views/pages/forbidden.html.erb
  config/initializers/honeybadger.rb
  spec/initializers/honeybadger_spec.rb
  spec/requests/listings_spec.rb
  spec/system/banned_user_interactions_spec.rb
Labels: PR: partially-approved

#16406 Scoping the :listing routes to feature
  config/routes.rb
  spec/routing/all_routes_spec.rb
Labels: PR: partially-approved

#16413 Short-circuiting parsing any articles to update
  lib/data_update_scripts/20220203165540_update_article_cached_attribute_around_main_image.rb
  lib/data_update_scripts/20220203194510_update_article_flag_without_parsing_article.rb
  spec/lib/data_update_scripts/update_article_flag_without_parsing_article_spec.rb
Labels: PR: unreviewed

#16420 Documenting and addl testing FeatureFlag.enabled?
  app/services/feature_flag.rb
  spec/services/feature_flag_spec.rb
Labels: PR: reviewed-approved

#16435 Removing deprecated User methods
  app/models/rating_vote.rb
  app/models/response_template.rb
  app/models/user.rb
  app/policies/authorizer.rb
  spec/models/user_spec.rb
Labels: PR: partially-approved

#16439 Added a custom Cypress command to get the modal compoonent.
  cypress/support/commands.js
Labels: area: tests, PR: partially-approved, merge by any core

#16349 Allow nil pubDate in Podcast sorting
  app/services/podcasts/feed.rb
Labels: PR: partially-approved

#16415 Implement Unified Embeds for StackExchange and StackOverflow URLs
  app/liquid_tags/stackexchange_tag.rb
  spec/liquid_tags/unified_embed/registry_spec.rb
  spec/support/fixtures/vcr_cassettes/stackexchange_tag_deleted_question.yml
  spec/support/fixtures/vcr_cassettes/stackexchange_tag_stackexchange.yml
  spec/support/fixtures/vcr_cassettes/stackexchange_tag_stackoverflow.yml
Labels: PR: partially-approved

#16422 Implement Unified Embeds for Github Repo, Issue, Pull-Request and Comment URLs
  app/liquid_tags/github_tag.rb
  app/liquid_tags/github_tag/github_issue_tag.rb
  app/liquid_tags/github_tag/github_readme_tag.rb
  spec/liquid_tags/github_tag/github_issue_tag_spec.rb
  spec/models/github_issue_spec.rb
  spec/services/github/oauth_client_spec.rb
  spec/support/fixtures/vcr_cassettes/github_client_comment.yml
  spec/support/fixtures/vcr_cassettes/github_client_issue.yml
  spec/support/fixtures/vcr_cassettes/github_client_issue_access_token.yml
  spec/support/fixtures/vcr_cassettes/github_client_issue_not_found.yml
  spec/support/fixtures/vcr_cassettes/github_client_pull_request.yml
  spec/support/fixtures/vcr_cassettes/github_client_pull_request_comment.yml
Labels: PR: unreviewed

#16432 Ignore device_detector warnings
  Gemfile
  Gemfile.lock
  config/initializers/warning.rb
  vendor/cache/warning-1.2.1.gem
Labels: PR: unreviewed

#16441 Ensuring that body.dataset is JSON parsable
  app/views/layouts/admin.html.erb
  app/views/layouts/application.html.erb
  app/views/onboardings/show.html.erb
Labels: PR: reviewed-approved

#16453 remove activex fallback for internet explorer
  app/assets/javascripts/initializers/initNotifications.js
  app/assets/javascripts/initializers/initializeArticleReactions.js
  app/assets/javascripts/initializers/initializeBodyData.js
  app/assets/javascripts/initializers/initializeCommentsPage.js.erb
  app/views/admin/articles/_image_upload_script.html.erb
  app/views/layouts/_top_bar.html.erb
Labels: PR: partially-approved

#16472 Remove system test for editing draft posts
  cypress/integration/seededFlows/publishingFlows/publishOrSavePost.spec.js
  spec/system/articles/user_fixes_a_draft_spec.rb
Labels: PR: reviewed-approved

#16467 Ensuring optionally rendering dashboard listings
  app/views/dashboards/_actions.html.erb
  app/views/dashboards/_analytics.html.erb
Labels: PR: partially-approved

#16480 Fixed post moderation flaky test
  cypress/integration/seededFlows/articleFlows/postModerationTools.spec.js
Labels: area: tests, PR: partially-approved, merge by any core

#16438 Feed experiment 6: recency
  app/services/articles/feeds/weighted_query_strategy.rb
  config/field_test.yml
Labels: PR: reviewed-approved

#16493 Add color-scheme: dark to dark.css
  app/assets/stylesheets/themes/dark.css
Labels: PR: partially-approved

#16491 ✂️ ✂️ Removed colour picker from onboarding as it's never used ✂️ ✂️
  app/javascript/onboarding/components/ProfileForm.jsx
  app/javascript/onboarding/components/ProfileForm/ColorPicker.jsx
Labels: area: new user experience, PR: partially-approved

#16174 Admin's Member view
  app/assets/images/badge.svg
  app/assets/images/bin.svg
  app/assets/images/edit.svg
  app/assets/images/refresh-button.svg
  app/assets/images/refresh.svg
  app/assets/images/team.svg
  app/assets/images/wallet.svg
  app/assets/stylesheets/components/cards.scss
  app/assets/stylesheets/components/list-items.scss
  app/assets/stylesheets/config/_colors.css
  app/assets/stylesheets/crayons.scss
  app/assets/stylesheets/themes/dark.css
  app/controllers/admin/users_controller.rb
  app/javascript/packs/admin/editUser.jsx
  app/views/admin/users/_actions.html.erb
  app/views/admin/users/_header.html.erb
  app/views/admin/users/_navigation.html.erb
  app/views/admin/users/_stats.html.erb
  app/views/admin/users/_status.html.erb
  app/views/admin/users/actions/_banish.html.erb
  app/views/admin/users/actions/_delete.html.erb
  app/views/admin/users/actions/_export.html.erb
  app/views/admin/users/actions/_merge.html.erb
  app/views/admin/users/actions/_social_accounts.html.erb
  app/views/admin/users/actions/_unpublish.html.erb
  app/views/admin/users/emails/_form.html.erb
  app/views/admin/users/emails/_index.html.erb
  app/views/admin/users/emails/_verification.html.erb
  app/views/admin/users/flags/_index.html.erb
  app/views/admin/users/notes/_form.html.erb
  app/views/admin/users/notes/_index.html.erb
  app/views/admin/users/reports/_index.html.erb
  app/views/admin/users/show.html.erb
  app/views/admin/users/widgets/_credits.html.erb
  app/views/admin/users/widgets/_organizations.html.erb
  app/views/admin/users/widgets/_roles.html.erb
  app/views/admin/users/widgets/_tag_moderation.html.erb
  spec/requests/admin/users_spec.rb
Labels: PR: unreviewed

#16479 Remove counts from instance API
  app/controllers/api/v0/instances_controller.rb
  spec/requests/api/v0/instances_spec.rb
Labels: area: API, PR: partially-approved

#16485 Ensuring an admin can confirm delete a user's post
  app/controllers/articles_controller.rb
  spec/requests/articles/articles_destroy_spec.rb
  spec/requests/articles/articles_spec.rb
Labels: PR: reviewed-approved

#16501 Add Disallow URLs to robots.txt for uselessly crawled endpoints
  app/views/pages/robots.text.erb
Labels: PR: reviewed-approved

#16417 Modify tags api index to allow for bulk GET of tags
  app/controllers/api/v0/tags_controller.rb
  app/views/api/v0/tags/index.json.jbuilder
  spec/requests/api/v0/tags_spec.rb
Labels: PR: partially-approved

#16512 Implement Unified Embeds for Forem-specific URLs
  app/liquid_tags/forem_tag.rb
  app/liquid_tags/link_tag.rb
  app/liquid_tags/organization_tag.rb
  app/liquid_tags/tag_tag.rb
  app/liquid_tags/user_tag.rb
  spec/liquid_tags/forem_tag_spec.rb
  spec/liquid_tags/unified_embed/registry_spec.rb
Labels: PR: unreviewed

#16511 Allowing dependency injection for LiquidTag policy
  app/liquid_tags/liquid_tag_base.rb
  app/services/markdown_processor/parser.rb
  spec/liquid_tags/liquid_tag_base_spec.rb
  spec/services/markdown_processor/parser_spec.rb
Labels: PR: reviewed-approved, merge by any core

#16518 Adding feature flag for Authorization 1-1
  app/policies/article_policy.rb
  spec/policies/article_policy_spec.rb
Labels: PR: partially-approved

#16530 Removes Leftover Comments from Admin::UsersController
  app/controllers/admin/users_controller.rb
Labels: PR: partially-approved

#16496 Add FeatureFlag.all
  app/services/feature_flag.rb
  spec/services/feature_flag_spec.rb
Labels: PR: reviewed-approved

#16531 Display Flash Messages When Adding or Removing Credits via the Admin Member Detail View
  app/controllers/admin/users_controller.rb
Labels: PR: reviewed-approved

#16492 Now Bg color hex is labeled Tag Color
  app/views/admin/tags/_form.html.erb
  app/views/tags/edit.html.erb
  config/locales/views/tags/en.yml
  config/locales/views/tags/fr.yml
  spec/system/admin/admin_updates_tag_spec.rb
  spec/system/tags/user_updates_a_tag_spec.rb
Labels: area: admin, PR: partially-approved, merge by any core, changelog: rollup

#16538 Minor accessibility fixes for member detail views
  app/views/admin/users/emails/_form.html.erb
  app/views/admin/users/flags/_index.html.erb
  app/views/admin/users/notes/_form.html.erb
  app/views/admin/users/notes/_index.html.erb
  app/views/admin/users/reports/_index.html.erb
Labels: PR: reviewed-approved

#16513 Added E2E tests for new admin member details view
  app/views/admin/users/widgets/_credits.html.erb
  app/views/admin/users/widgets/_organizations.html.erb
  app/views/layouts/admin.html.erb
  cypress/integration/seededFlows/adminFlows/users/manageCredits.spec.js
  cypress/integration/seededFlows/adminFlows/users/manageOrganizations.spec.js
  cypress/integration/seededFlows/adminFlows/users/manageRoles.spec.js
  cypress/integration/seededFlows/adminFlows/users/manageUserOptions.spec.js
  spec/support/seeds/seeds_e2e.rb
  vendor/cache/view_component-2.48.0.gem
Labels: PR: unreviewed, area: admin, area: tests, PR: partially-approved, merge by any core

#16527 Documenting ApplicationPolicy
  app/policies/application_policy.rb
Labels: PR: partially-approved

#16523 Renaming policy methods for consistency
  app/policies/admin_policy.rb
  app/policies/application_policy.rb
  app/policies/article_policy.rb
  app/policies/comment_policy.rb
  app/policies/discussion_lock_policy.rb
  app/policies/html_variant_policy.rb
  app/policies/response_template_policy.rb
  app/policies/tag_policy.rb
  app/policies/user_policy.rb
Labels: PR: partially-approved

#16541 Avoid gif CLS
  app/assets/stylesheets/article-show.scss
  app/assets/stylesheets/base/typography.scss
Labels: PR: partially-approved, merge by any core

#16524 Admin member area a11y fixes: Overview page
  app/assets/stylesheets/config/_generator.scss
  app/views/admin/users/_actions.html.erb
  app/views/admin/users/_header.html.erb
  app/views/admin/users/_navigation.html.erb
  app/views/admin/users/_stats.html.erb
  app/views/admin/users/_status.html.erb
  app/views/admin/users/actions/_merge.html.erb
  app/views/admin/users/widgets/_credits.html.erb
  app/views/admin/users/widgets/_organizations.html.erb
  app/views/admin/users/widgets/_roles.html.erb
  app/views/admin/users/widgets/_tag_moderation.html.erb
  cypress/integration/seededFlows/adminFlows/users/manageOrganizations.spec.js
  cypress/integration/seededFlows/adminFlows/users/manageRoles.spec.js
Labels: PR: partially-approved

#16553 a missing i18n key (fr only)
  config/locales/views/misc/fr.yml
Labels: PR: reviewed-approved

#16536 Removing Articles::Builder making policy decision
  app/controllers/articles_controller.rb
  app/policies/article_policy.rb
  app/services/articles/builder.rb
  spec/policies/article_policy_spec.rb
  spec/requests/editor_spec.rb
  spec/services/articles/builder_spec.rb
Labels: PR: unreviewed

#16555 add asheren to core team
  README.md
Labels: PR: reviewed-approved

#16569 Fix NoMethodError on Nil for article preview
  app/controllers/articles_controller.rb
  spec/requests/editor_spec.rb
Labels: PR: partially-approved

#16551 Fix Github Liquid Tag from repositories with dot character
  app/liquid_tags/github_tag.rb
  app/liquid_tags/github_tag/github_issue_tag.rb
  app/liquid_tags/github_tag/github_readme_tag.rb
  spec/liquid_tags/github_tag/github_issue_tag_spec.rb
  spec/support/fixtures/vcr_cassettes/github_client_issue_with_dot_character.yml
Labels: PR: partially-approved

#16570 Apply safe navigation to Reactions::Send
  app/services/notifications/reactions/send.rb
Labels: PR: reviewed-approved

#16520 Admin API use case 1: endpoint to create users
  app/controllers/api/v0/admin/users_controller.rb
  config/routes.rb
  spec/requests/api/v0/admin/users_spec.rb
Labels: PR: reviewed-approved

#16460 Rework user subscription liquid tag to avoid errors
  app/assets/javascripts/utilities/sendFetch.js
  app/controllers/async_info_controller.rb
  app/javascript/liquidTags/userSubscriptionLiquidTag.js
  app/javascript/packs/articlePage.jsx
  app/liquid_tags/user_subscription_tag.rb
  app/views/articles/show.html.erb
  app/views/liquids/_user_subscription.html.erb
  config/locales/views/liquids/en.yml
  config/locales/views/liquids/fr.yml
  cypress/fixtures/users/appleAuthAdminUser.json
  cypress/integration/seededFlows/articleFlows/liquidTagFlows/followFromArticleLiquidTag.spec.js
  cypress/integration/seededFlows/articleFlows/liquidTagFlows/userSubscriptionLiquidTagWithAppleAuthEmail.spec.js
  cypress/integration/seededFlows/articleFlows/liquidTagFlows/userSubscriptionTagWithSubscribableEmail.spec.js
  spec/support/seeds/seeds_e2e.rb
  spec/system/liquid_tags/user_subscription_tag_spec.rb
Labels: PR: partially-approved

#16572 Removing deprecation warning
  app/controllers/api/v0/listings_controller.rb
  app/controllers/application_controller.rb
Labels: PR: reviewed-approved

#16580 Fix admin user credits spec
  cypress/integration/seededFlows/adminFlows/users/manageCredits.spec.js
Labels: PR: partially-approved, merge by any core

#16568 Now the credit amount max toggles when switching between adding/removing credits.
  app/javascript/packs/admin/editUser.jsx
  app/views/admin/users/widgets/_credits.html.erb
  cypress/integration/seededFlows/adminFlows/users/manageCredits.spec.js
Labels: area: admin, PR: partially-approved, merge by any core

#16390 Require profile fields to belong to a group
  app/models/profile_field.rb
  app/views/admin/profile_fields/_profile_field_form.html.erb
  spec/factories/profile_fields.rb
  spec/lib/data_update_scripts/add_work_profile_field_spec.rb
  spec/lib/data_update_scripts/drop_profile_fields_for_static_attributes_spec.rb
  spec/lib/data_update_scripts/work_profile_field_follow_up_spec.rb
  spec/models/profile_field_spec.rb
  spec/requests/admin/profile_fields_spec.rb
  spec/services/profile_fields/add_spec.rb
  spec/support/seeds/seeds_e2e.rb
Labels: PR: unreviewed

#16497 Add a contact email address to the /admin/customization/config
  app/controllers/admin/pages_controller.rb
  app/controllers/admin/users_controller.rb
  app/controllers/api_secrets_controller.rb
  app/controllers/confirmations_controller.rb
  app/controllers/users_controller.rb
  app/helpers/application_helper.rb
  app/lib/constants/settings/general.rb
  app/models/article.rb
  app/models/forem_instance.rb
  app/models/settings/general.rb
  app/services/error_messages/clean.rb
  app/views/admin/settings/forms/_email_digest_frequency.html.erb
  app/views/admin/settings/forms/_emails.html.erb
  app/views/admin/settings/show.html.erb
  app/views/admin/users/_data_export.html.erb
  app/views/credits/new.html.erb
  app/views/deep_links/mobile.html.erb
  app/views/mailers/notify_mailer/account_deleted_email.text.erb
  app/views/mailers/notify_mailer/tag_moderator_confirmation_email.html.erb
  app/views/mailers/notify_mailer/tag_moderator_confirmation_email.text.erb
  app/views/mailers/notify_mailer/trusted_role_email.html.erb
  app/views/mailers/notify_mailer/trusted_role_email.text.erb
  app/views/moderations/_mod_sidebar_left.html.erb
  app/views/moderations/index.html.erb
  app/views/open_search/show.xml.erb
  app/views/pages/_coc_text.html.erb
  app/views/pages/_privacy_text.html.erb
  app/views/pages/_terms_text.html.erb
  app/views/pages/contact.html.erb
  app/views/pages/forbidden.html.erb
  app/views/users/_org_admin.html.erb
  app/views/users/confirm_destroy.html.erb
  app/views/users/edit.html.erb
  cypress/integration/seededFlows/adminFlows/config/emailDigestFrequencySection.spec.js
  spec/helpers/application_helper_spec.rb
  spec/models/article_spec.rb
  spec/models/forem_instance_spec.rb
  spec/requests/user/user_settings_spec.rb
  spec/system/authentication/user_request_confirmation_spec.rb
Labels: PR: partially-approved

#16591 Fix NoMethodError on User#email
  app/controllers/async_info_controller.rb
Labels: PR: partially-approved

#16557 Render social previews for tags with one of the two custom colors set
  app/controllers/social_previews_controller.rb
  app/views/social_previews/tag.html.erb
Labels: PR: reviewed-approved

#16573 Refactoring shared context to remove assumption
  spec/support/shared_context.rb
Labels: PR: reviewed-approved

#16223 Improve the UX of the SMTP Section
  app/controllers/stories/feeds_controller.rb
  app/javascript/admin/controllers/config_controller.js
  app/javascript/packs/admin/config/smtp.js
  app/lib/constants/settings/smtp.rb
  app/models/forem_instance.rb
  app/models/settings/smtp.rb
  app/services/articles/feeds/weighted_query_strategy.rb
  app/views/admin/settings/forms/_smtp.html.erb
  app/views/admin/settings/show.html.erb
  cypress/integration/seededFlows/adminFlows/config/emailServerSettingsSection.spec.js
  cypress/integration/seededFlows/adminFlows/pages/landingPage.spec.js
  spec/models/forem_instance_spec.rb
  spec/system/admin/config/admin_updates_smtp_settings_spec.rb
Labels: PR: partially-approved

#16597 ✂️✂️ Removed the pusher-js dependency ✂️✂️
  app/javascript/.eslintrc.js
  package.json
  yarn.lock
Labels: PR: reviewed-approved, merge by any core

#16359 Admin Articles view update
  app/assets/stylesheets/config/_generator.scss
  app/javascript/admin/controllers/article_controller.js
  app/views/admin/articles/_individual_article.html.erb
  app/views/admin/articles/index.html.erb
  cypress/integration/seededFlows/adminFlows/articles/pinArticle.spec.js
  cypress/integration/seededFlows/adminFlows/articles/unpinArticle.spec.js
Labels: PR: unreviewed

#16582 Tweaks to the admin flash messages flow
  app/javascript/packs/admin/flashMessages.js
  app/views/layouts/admin.html.erb
  cypress/integration/seededFlows/adminFlows/users/manageCredits.spec.js
  cypress/integration/seededFlows/adminFlows/users/manageOrganizations.spec.js
  cypress/integration/seededFlows/adminFlows/users/manageRoles.spec.js
  cypress/integration/seededFlows/adminFlows/users/manageUserOptions.spec.js
Labels: PR: partially-approved

#16584 Adding docs regarding auto-linking PR to issue
  .github/PULL_REQUEST_TEMPLATE.md
Labels: PR: partially-approved

#16571 Plumbing application for probable AuthN/Z changes
  app/controllers/application_controller.rb
  app/policies/application_policy.rb
  config/application.rb
  config/locales/misc/en.yml
  config/locales/misc/fr.yml
  spec/policies/application_policy_spec.rb
Labels: PR: partially-approved

#16499 "Reply to" and "From" Email addresses for SMTP Configurations
  app/helpers/settings_helper.rb
  app/lib/constants/settings/smtp.rb
  app/mailers/application_mailer.rb
  app/mailers/devise_mailer.rb
  app/mailers/verification_mailer.rb
  app/models/forem_instance.rb
  app/models/settings/smtp.rb
  app/views/admin/settings/forms/_smtp.html.erb
  spec/mailers/devise_mailer_spec.rb
  spec/mailers/digest_mailer_spec.rb
  spec/mailers/shared_examples/renders_proper_email_headers.rb
  spec/mailers/verification_mailer_spec.rb
  spec/models/forem_instance_spec.rb
  spec/models/settings/smtp_spec.rb
Labels: PR: partially-approved, merge by any core

#16601 Unified Embed Documentation
  app/javascript/article-form/components/Help/EditorFormattingHelp.jsx
  app/views/pages/_editor_guide_text.html.erb
  app/views/pages/_editor_liquid_help.html.erb
  app/views/pages/_liquid_tag_section_intro.html.erb
  app/views/pages/_supported_nonurl_embeds_list.html.erb
  app/views/pages/_supported_url_embeds_list.html.erb
  app/views/pages/_v1_editor_guide_preamble.html.erb
  app/views/pages/markdown_basics.html.erb
Labels: PR: partially-approved

#16615 Process Comment Embed through ForemTag
  app/liquid_tags/comment_tag.rb
  app/liquid_tags/forem_tag.rb
  spec/liquid_tags/forem_tag_spec.rb
  spec/liquid_tags/unified_embed/registry_spec.rb
Labels: PR: partially-approved

#16610 Only make one network call to fetch all existing tags in editor
  app/controllers/api/v0/tags_controller.rb
  app/javascript/article-form/components/TagsField.jsx
  spec/requests/api/v0/tags_spec.rb
Labels: PR: partially-approved

#16574 Fix pinned post not showing on feed tabs
  app/javascript/articles/Article.jsx
  app/javascript/articles/Feed.jsx
  app/javascript/packs/homePageFeed.jsx
Labels: PR: partially-approved

#16544 Small win: Add "Feature post" button alongside new "admin actions" drawer in mod panel.
  app/assets/images/admin.svg
  app/assets/stylesheets/views/mod-actions.scss
  app/controllers/articles_controller.rb
  app/javascript/actionsPanel/actionsPanel.js
  app/policies/article_policy.rb
  app/views/moderations/actions_panel.html.erb
  config/locales/views/moderations/en.yml
  config/routes.rb
  spec/policies/article_policy_spec.rb
  spec/requests/articles/articles_admin_feature_spec.rb
Labels: PR: unreviewed

#16619 Bootstrap removal: People
  app/views/admin/invitations/index.html.erb
  app/views/admin/users/_menu.html.erb
  app/views/admin/users/gdpr_delete_requests/index.html.erb
  app/views/admin/users/index.html.erb
Labels: PR: unreviewed, tech: frontend

#16627 Fix integer > nil error when sending reaction notifications
  app/services/notifications/reactions/send.rb
  spec/services/notifications/reactions/send_spec.rb
Labels: PR: unreviewed

#16626 Update PR template to ensure issue linking
  .github/PULL_REQUEST_TEMPLATE.md
Labels: PR: partially-approved, merge by any core

#16638 Escape non-character dots in Embed Regexes
  app/liquid_tags/asciinema_tag.rb
  app/liquid_tags/dotnet_fiddle_tag.rb
  app/liquid_tags/instagram_tag.rb
  app/liquid_tags/kotlin_tag.rb
  app/liquid_tags/medium_tag.rb
  app/liquid_tags/next_tech_tag.rb
  app/liquid_tags/reddit_tag.rb
  app/liquid_tags/replit_tag.rb
  app/liquid_tags/slideshare_tag.rb
  app/liquid_tags/soundcloud_tag.rb
  app/liquid_tags/speakerdeck_tag.rb
  app/liquid_tags/spotify_tag.rb
  app/liquid_tags/stackblitz_tag.rb
  app/liquid_tags/stackery_tag.rb
  app/liquid_tags/tweet_tag.rb
  app/liquid_tags/twitch_tag.rb
  app/liquid_tags/wikipedia_tag.rb
Labels: PR: partially-approved

#16616 Remove unused methods from `User`
  app/models/user.rb
  app/serializers/search/user_serializer.rb
  app/services/search/user.rb
Labels: PR: reviewed-approved

#16625 Add new color picker to user settings page
  app/views/users/_profile.html.erb
  cypress/integration/seededFlows/settingsFlows/updateProfileSettings.spec.js
Labels: PR: partially-approved

#16641 Revert "Only make one network call to fetch all existing tags in editor"
  app/controllers/api/v0/tags_controller.rb
  app/javascript/article-form/components/TagsField.jsx
  spec/requests/api/v0/tags_spec.rb
Labels: PR: partially-approved

#16640 Implement Tabs for the Admin Member Detail View
  app/controllers/admin/users_controller.rb
  app/lib/constants/user_details.rb
  app/views/admin/users/show.html.erb
  app/views/admin/users/show/_tabs.html.erb
  cypress/integration/seededFlows/adminFlows/users/navigateTabs.spec.js
Labels: PR: unreviewed

#16646 Removed hardcoded dev.to from _terms text and replaced with community_name
  app/views/pages/_terms_text.html.erb
Labels: PR: reviewed-approved

#16644 Removes Comment from Admin Menu
  app/models/admin_menu.rb
Labels: PR: partially-approved, merge by any core

#16634 Adjusting suspended user authorizations
  app/policies/comment_policy.rb
  app/policies/follow_policy.rb
  app/policies/reaction_policy.rb
  spec/policies/comment_policy_spec.rb
  spec/policies/follow_policy_spec.rb
  spec/policies/reaction_policy_spec.rb
Labels: PR: reviewed-approved

#16614 Adjusting ArticlePolicy for admin only posting
  app/controllers/application_controller.rb
  app/controllers/articles_controller.rb
  app/controllers/concerns/caching_headers.rb
  app/policies/article_policy.rb
  config/application.rb
  spec/policies/article_policy_spec.rb
  spec/requests/comments_spec.rb
  spec/requests/editor_spec.rb
Labels: PR: partially-approved

#16654 Update flipper in gemfile.lock
  Gemfile.lock
Labels: PR: partially-approved

#16633 Implement Loom Embed (not merging now)
  app/liquid_tags/gist_tag.rb
  app/liquid_tags/loom_tag.rb
  app/liquid_tags/unified_embed/registry.rb
  app/liquid_tags/unified_embed/tag.rb
  app/views/liquids/_loom.html.erb
  app/views/pages/_editor_liquid_help.html.erb
  app/views/pages/_supported_url_embeds_list.html.erb
  config/locales/liquid_tags/en.yml
  config/locales/liquid_tags/fr.yml
  spec/liquid_tags/loom_tag_spec.rb
  spec/liquid_tags/unified_embed/registry_spec.rb
Labels: PR: partially-approved

#16651 Basic theme-color
  app/views/layouts/application.html.erb
Labels: PR: partially-approved, tech: frontend

#16517 Fix RSS feed validity issue (#16418)
  app/controllers/articles_controller.rb
  app/sanitizers/feed_markdown_scrubber.rb
  app/views/articles/feed.rss.builder
  spec/requests/articles/articles_spec.rb
  spec/sanitizers/feed_markdown_scrubber_spec.rb
Labels: PR: reviewed-approved

#16667 Don't sanitize anchor elements with no href
  app/sanitizers/feed_markdown_scrubber.rb
  spec/sanitizers/feed_markdown_scrubber_spec.rb
Labels: PR: reviewed-approved, merge by any core

#16662 Add ChunkLoadError to Honeybadger's ignorePatterns
  app/assets/javascripts/base.js.erb
Labels: PR: partially-approved

#16291 Remove Remaining logo_svg Code
  app/helpers/application_helper.rb
  app/lib/constants/settings/general.rb
  app/models/settings/general.rb
  lib/data_update_scripts/20220203143904_remove_logo_svg_from_database.rb
  spec/lib/data_update_scripts/migrate_logo_svg_data_spec.rb
  spec/requests/admin/configs_spec.rb
  spec/system/articles/user_edits_an_article_spec.rb
  spec/system/user_uses_the_editor_spec.rb
  spec/uploaders/logo_svg_uploader_spec.rb
Labels: PR: partially-approved

#16665 Update `device_detector`, remove `warning` workaround
  Gemfile
  Gemfile.lock
  config/initializers/warning.rb
  vendor/cache/device_detector-1.0.6.gem
  vendor/cache/device_detector-1.0.7.gem
  vendor/cache/warning-1.2.1.gem
Labels: PR: partially-approved

#16666 Update profile image for orgs in seeds
  db/seeds.rb
Labels: PR: partially-approved

#16343 More listings refactoring
  app/controllers/admin/listing_categories_controller.rb
  app/controllers/api/v0/listings_controller.rb
  app/controllers/concerns/listings_toolkit.rb
  app/controllers/listings_controller.rb
  app/models/listing.rb
  app/services/listings/bump.rb
  spec/requests/listings_spec.rb
Labels: PR: unreviewed, merge by any core

#16642 Add new ColorPicker to organization settings
  app/javascript/packs/colorPreview.js
  app/views/shared/_logo_design.html.erb
  app/views/users/_org_admin.html.erb
  app/views/users/_org_non_member.html.erb
  config/locales/views/misc/en.yml
  config/locales/views/misc/fr.yml
  cypress/integration/seededFlows/settingsFlows/organisationSettings.spec.js
Labels: PR: partially-approved

#16192 extra tweaks for i18n
  app/lib/url.rb
  db/seeds.rb
  spec/helpers/application_helper_spec.rb
  spec/lib/url_spec.rb
Labels: PR: partially-approved

#16650 Text overflow on profile preview cards
  app/assets/stylesheets/components/profile-preview-card.scss
Labels: PR: partially-approved, tech: frontend

#16676 Update identities where the auth data dump is a plain hash
  lib/data_update_scripts/20220223160059_coerce_identity_auth_data_format.rb
  spec/lib/data_update_scripts/coerce_identity_auth_data_format_spec.rb
Labels: PR: reviewed-approved

#16681 Removing duplicate logic and adding docs
  app/controllers/api/v0/api_controller.rb
Labels: PR: reviewed-approved

#16649 GIF button z-index issue
  app/assets/stylesheets/article-show.scss
Labels: PR: partially-approved, tech: frontend

#16682 Silence `parser/current` warnings
  Gemfile
  Gemfile.lock
  config/boot.rb
  vendor/cache/warning-1.2.1.gem
Labels: PR: partially-approved

#16684 Removing somewhat duplicated logic
  app/controllers/api/v0/api_controller.rb
Labels: PR: reviewed-approved

#16671 Add ability to bulk search tags by name or id
  app/controllers/api/v0/tags_controller.rb
  app/controllers/tags_controller.rb
  app/views/api/v0/tags/index.json.jbuilder
  config/routes.rb
  spec/requests/api/v0/tags_spec.rb
  spec/requests/tags_spec.rb
Labels: PR: partially-approved

#16691 Update the Copy for the "Notes" Tab in the Admin Member Detail View
  app/views/admin/users/show/notes/_form.html.erb
  app/views/admin/users/show/notes/_index.html.erb
Labels: merge by any core

#16645 Update the Copy for the "Overview" Tab and Its Modals
  app/views/admin/users/show/overview/_credits.html.erb
  app/views/admin/users/show/overview/_organizations.html.erb
  app/views/admin/users/show/overview/_roles.html.erb
  app/views/admin/users/show/overview/_tag_moderation.html.erb
  cypress/integration/seededFlows/adminFlows/users/manageCredits.spec.js
  cypress/integration/seededFlows/adminFlows/users/manageOrganizations.spec.js
  cypress/integration/seededFlows/adminFlows/users/manageRoles.spec.js
Labels: PR: partially-approved, merge by any core

#16693 Update the Copy for the "Emails" Tab in the Admin Member Detail View
  app/views/admin/users/show/emails/_form.html.erb
  app/views/admin/users/show/emails/_index.html.erb
  app/views/admin/users/show/emails/_verification.html.erb
Labels: PR: partially-approved, merge by any core

#16672 ✂️ Remove myself from core contributors
  README.md
  app/models/article.rb
  app/services/users/suggest_for_sidebar.rb
  config/environments/development.rb
  config/environments/test.rb
  config/routes/admin.rb
  cypress/integration/seededFlows/adminFlows/pages/landingPage.spec.js
Labels: PR: reviewed-approved, merge by any core

#16699 Remove the duplicate verify email button on the admin member view
  app/views/admin/users/show/profile/_actions.html.erb
  cypress/integration/seededFlows/adminFlows/users/manageUserOptions.spec.js
Labels: PR: partially-approved

#16697 Update the Copy for the "Flags" Tab in the Admin Member Detail View
  app/views/admin/users/show/flags/_index.html.erb
Labels: PR: partially-approved, merge by any core

#16685 Ensuring POST api/v0/articles authorizes by policy
  app/controllers/api/v0/api_controller.rb
  app/controllers/api/v0/articles_controller.rb
  spec/requests/api/v0/articles_spec.rb
Labels: PR: reviewed-approved

#16714 Amend CSRF token retries
  app/assets/javascripts/utilities/getCsrfToken.js
Labels: PR: partially-approved

#16719 Revert "Remove IE-specific setting (#16073)"
  config/application.rb
Labels: PR: partially-approved

#16721 Don't send notification for invalid reactions
  app/models/reaction.rb
  spec/models/reaction_spec.rb
Labels: PR: partially-approved

#16708 Update the Copy for all Modals in the Admin Member Detail View
  app/views/admin/users/show/overview/_organizations.html.erb
  app/views/admin/users/show/profile/_actions.html.erb
  app/views/admin/users/show/profile/actions/_banish.html.erb
  app/views/admin/users/show/profile/actions/_delete.html.erb
  app/views/admin/users/show/profile/actions/_export.html.erb
  app/views/admin/users/show/profile/actions/_merge.html.erb
  app/views/admin/users/show/profile/actions/_social_accounts.html.erb
  app/views/admin/users/show/profile/actions/_unpublish.html.erb
  cypress/integration/seededFlows/adminFlows/users/manageUserOptions.spec.js
Labels: PR: unreviewed

#16703 Adding indirection for Tag#name to ease future work
  app/models/tag.rb
  app/views/admin/tags/edit.html.erb
  app/views/moderations/index.html.erb
  app/views/tags/edit.html.erb
  app/views/tags/index.html.erb
  spec/models/tag_spec.rb
Labels: PR: partially-approved
