Repository forem/forem, pull requests merged in 2023-04, with the labels that each got.

#19280 Add an article exclusion list to Billboards
  .rubocop.yml
  app/controllers/admin/display_ads_controller.rb
  app/controllers/api/v1/display_ads_controller.rb
  app/javascript/packs/admin/displayAds.jsx
  app/models/display_ad.rb
  app/queries/display_ads/filtered_ads_query.rb
  app/views/admin/display_ads/_form.html.erb
  app/views/articles/_sticky_nav.html.erb
  app/views/articles/show.html.erb
  db/migrate/20230320152715_add_exclude_article_ids_to_display_ads.rb
  db/migrate/20230320152927_add_exclude_article_ids_index_to_display_ads.rb
  db/schema.rb
  spec/models/display_ad_spec.rb
  spec/queries/display_ads/filtered_ads_query_spec.rb
  spec/requests/api/v1/display_ads_spec.rb
  spec/requests/api/v1/docs/display_ads_spec.rb
  spec/swagger_helper.rb
  swagger/v1/api_v1.json
Labels: merge by any core

#19287 Refactor cache-key on FeedbackMessagesController#create
  app/controllers/feedback_messages_controller.rb
Labels: merge by any core

#19091 Ensure rendering parity on DisplayAd, Comment, & Article
  app/models/article.rb
  app/models/comment.rb
  app/models/display_ad.rb
  app/services/content_renderer.rb
  app/services/html/parser.rb
  app/services/markdown_processor.rb
  app/services/markdown_processor/fixer/base.rb
  app/services/markdown_processor/parser.rb
  spec/models/display_ad_spec.rb
  spec/services/content_renderer_spec.rb
  spec/services/html/parser_spec.rb
  spec/services/markdown_processor/parser_spec.rb
Labels: merge by any core

#19263 Unique cross-model-slug check is likely misconfigured
  app/models/concerns/unique_across_models.rb
  app/models/cross_model_slug.rb
  app/models/organization.rb
  app/models/page.rb
  app/models/podcast.rb
  app/models/user.rb
  app/services/users/username_generator.rb
  app/validators/cross_model_slug_validator.rb
  app/validators/unique_cross_model_slug_validator.rb
  config/locales/validators/en.yml
  config/locales/validators/fr.yml
  spec/factories/pages.rb
  spec/models/user_spec.rb
  spec/services/users/username_generator_spec.rb
  spec/system/admin/admin_manages_pages_spec.rb
  spec/validators/cross_model_slug_validator_spec.rb
Labels: merge by any core, ruby

#19285 Load `post_comments` billboard asynchronously
  .github/PULL_REQUEST_TEMPLATE.md
  app/controllers/display_ads_controller.rb
  app/decorators/article_decorator.rb
  app/javascript/packs/billboard.js
  app/views/articles/_sidebar.html.erb
  app/views/articles/_sticky_nav.html.erb
  app/views/articles/show.html.erb
  app/views/display_ads/show.html.erb
  app/views/shared/_display_ad.html.erb
  app/views/shared/_display_ad_header.html.erb
  app/views/sidebars/_homepage_content.html.erb
  app/views/stories/_main_stories_feed.html.erb
  config/fastly/snippets/safe_params_list.vcl
  config/routes.rb
  spec/decorators/article_decorator_spec.rb
  spec/requests/display_ads_spec.rb
  spec/system/articles/user_visits_articles_by_timeframe_spec.rb
Labels: merge by any core

#19321 Fix image width for feed location
  app/models/display_ad.rb
  spec/models/display_ad_spec.rb
Labels: merge by any core

#19317 Load `post_sidebar` billboard asynchronously
  app/javascript/packs/billboard.js
  app/views/articles/_sticky_nav.html.erb
  app/views/articles/show.html.erb
  swagger/v1/api_v1.json
Labels: merge by any core

#19326 Fix display ad event race condition
  app/javascript/packs/billboard.js
Labels: merge by any core

#19339 Restore marking notifications as read via InstantClick
  app/javascript/packs/baseInitializers.js
Labels: merge by any core

#19348 Unify some liquid embed styles without modifying markup
  app/assets/stylesheets/base/typography.scss
  app/assets/stylesheets/config/_colors.css
  app/assets/stylesheets/ltags/CommentTag.scss
  app/assets/stylesheets/ltags/GithubReadmeTag.scss
  app/assets/stylesheets/ltags/LinkTag.scss
  app/assets/stylesheets/ltags/UserTag.scss
  app/assets/stylesheets/themes/dark.css
Labels: merge by any core

#19365 Style bug fix: Profile pic for link liquid embed on org posts misaligned
  app/assets/stylesheets/ltags/LinkTag.scss
Labels: merge by any core

#19385 Update modules so storybook can run
  package.json
  yarn.lock
Labels: area: documentation, tech: frontend

#19389 Tweak 'last step' random sampling to favor new ads
  app/models/display_ad.rb
Labels: tech: ruby, tech: backend, ruby

#19390 Improve visual consistency in some embeds
  app/assets/stylesheets/ltags/GithubTag.scss
  app/assets/stylesheets/ltags/TagTag.scss
  app/assets/stylesheets/ltags/TweetTag.scss
  app/assets/stylesheets/ltags/WikipediaTag.scss
Labels: merge by any core

#19361 Consistent rendering on preview: comments and articles
  app/controllers/articles_controller.rb
  app/controllers/comments_controller.rb
  spec/requests/articles/articles_show_spec.rb
  spec/requests/comments_spec.rb
  spec/requests/editor_spec.rb
Labels: merge by any core

#19394 Preparation of endpoint and files required for ChatGPT Plugin
  app/controllers/concerns/api/articles_controller.rb
  app/queries/articles/api_search_query.rb
  app/views/api/v0/articles/search.json.jbuilder
  app/views/api/v1/articles/search.json.jbuilder
  config/initializers/cors.rb
  config/routes/api.rb
  public/.well-known/ai-plugin.json
  public/logo.png
  public/openapi.yml
  spec/queries/articles/api_search_query_spec.rb
  spec/requests/api/v0/articles_spec.rb
  spec/requests/api/v1/articles_spec.rb
Labels: merge by any core
